### ISSUE TITLE
Interesting DMG values on an iron axe

### ISSUE THREAD

**Issue by Mooncranky** [LunaPixelStudios/Better-MC#1001]
### Describe the Bug

So i made a ex farm with some wither, husk, stray and zombies. one of them sometimes droppes an iron axe. and some of those axes have different dmg values than the rest. i got an axe with some over 8k dmg oneshoting anything. furthermore there is a strage bug if i fight with them i sometimes get oneshoted myself with the death notice: "killed by magic"

### Reproduction Steps

1. build exp farm
2. maybe skill some luck (?) dk if it effects dropps
3. hope to get lucky
...

### Screenshots and Videos

![axe](https://user-images.githubusercontent.com/123328244/213937544-b6f80c7a-2075-450f-812d-91a3fd226c97.PNG)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15.5 Medieval MC [Fabrick]

### Optifine

I used Optifine

### Other Mods

Some Macaw's decoration mods

**Comment by Mooncranky** [comment]
![image](https://user-images.githubusercontent.com/123328244/213937829-7e3b20fd-c5ec-43ed-86bf-7ebc0d0bb6d0.png)
skilled a bit more luck and dropped this : O

**Comment by Mooncranky** [comment]
update 2; bows are effected too

**Comment by chorbintime** [comment]
You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

This is an issue with Dungeon Difficulty. It will be fixed in v16.
