### ISSUE TITLE
Dragon Mounts Legacy 1.1.4 (Only Fire dragon is available at Better MC 1.18.2 v18) 

### ISSUE THREAD

**Issue by hancelpo321** [LunaPixelStudios/Better-MC#1002]
### Describe the Bug

I am running it on server and I can only find fire dragon egg on creative, plus the fire dragon egg seems to be very rare finding it for almost 3 weeks now, please fix this issue

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v18

### Optifine

No

### Other Mods

Nothing

**Comment by chorbintime** [comment]
What exactly is the issue?

**Comment by SHXRKIIE** [comment]
Update the mod
