### ISSUE TITLE
game appearance

### ISSUE THREAD

**Issue by Broreally** [LunaPixelStudios/Better-MC#1003]
### Describe the Bug

My game crashed the day before but I decided not to play until the next day and now that I loaded up the game it looks different. First the mini map only shows names now and not icons such as ice and fire or alex's mobs. Second the normal minecraft clock looks stranger as in it looks like it came from an older version of minecraft. Now thinking about it everything kinda looks older textures which could explain why the mini map only shows the names of mobs and not icons. It doesn't prevent me from playing the game or anything but I just don't like the way it looks. Do you know how to fix it?

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-01-23 (3)](https://user-images.githubusercontent.com/103301609/214093814-2f19dac9-6773-43e4-b8ca-5817c03090df.png)
![2023-01-23_10 27 37](https://user-images.githubusercontent.com/103301609/214094424-00c0f71d-f544-42f3-bbeb-376d12803dd2.png)

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v38

### Optifine

No

**Comment by chorbintime** [comment]
Reinstall the modpack using ATLauncher and transfer your saves folder
