### ISSUE TITLE
Puzzle Resource settings crash the game

### ISSUE THREAD

**Issue by OtisWong** [LunaPixelStudios/Better-MC#1005]
### Describe the Bug

Any time i click onto resource settings in the puzzle menu, the game starts saving world and then crashes for no apparent reason. i have made no modifications to the modpack but i do run a shader

### Reproduction Steps

1.Open options
2.Press onto the puzzle button
3.Press resource settings and wait a few seconds
...

### Crash Report or Log

https://gist.github.com/OtisWong/c9040a6b8d04e4779f01be1b63d9ef9f

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

CurseForge

### Modpack Version

v13.5

### Optifine

I don't use optifine

**Comment by chorbintime** [comment]
I don't know what modpack you are playing. There is no 1.19.2 Forge v13.5.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by OtisWong** [comment]
> I don't know what modpack you are playing. There is no 1.19.2 Forge v13.5.
> 
> You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

very sorry, very confusing report. I use CurseForge to download the mod and run the fabric 13.5 version. I assumed optifine was in the modpack since multiple optifine functions were present such as being able to use optifine shaders and C to zoom.

**Comment by chorbintime** [comment]
Thank you for elaborating. I'll look into disabling the puzzle button, but i'm unsure if its config allows for such a thing. This may be fixed in a newer version of whichever mod provides that button, in which case it'll be fixed in v14
