### ISSUE TITLE
Nullpointerexception

### ISSUE THREAD

**Issue by ExtraWetTowel** [LunaPixelStudios/Better-MC#1006]
### Describe the Bug

Each time i log in im able to walk around and play the game until I press my key bind for my inventory which crashes the game instantly and gives me the nullpointerexception crash report.  

### Reproduction Steps

1.Log in
2.Press e
3.crash
...

### Operating System

Windows 10

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

v15.5

### Optifine

No

**Comment by chorbintime** [comment]
Delete cosmetic armor mod

You posted this on the wrong github
