### ISSUE TITLE
Infinite Death Bug Medieval MC Fabric

### ISSUE THREAD

**Issue by realmazi** [LunaPixelStudios/Better-MC#1007]
### Describe the Bug

You're in an infinite death loop. 

No, you cannot /kill yourself to stop it.
No, you cannot be killed by another player to fix it. 
No, you cannot leave and rejoin to fix it.
And no, you cannot open your inventory to create a solution relating to it.

I died to the last stand explosion from a regular Wither. I suspect I got the bug because I had a Purple Totem of Undying in my Charm slot, instead of holding it in my off-hand. 

Unfortunately, I didn't get to clip it. I thought I could fix it with a simple /kill command or by simply rejoining the game. Those two  did not fix it. By the time I tried them, it was long after 30 seconds, which is my clipping length.

Please send me any solutions you may have in mind. I've spent way too long on my world to have to restart it. 

### Reproduction Steps

1. Spawn the Wither in a cave. 
2. Kill it. ( I had a Frost Scythe, if thats of any importance. )
3. Have the Last Stand Explosion of the Wither kill you, while you have a Purple Totem of Undying in your CHARM slot. (Not sure what material it is, can't open my inventory to check unfortunately.)
...

### Screenshots and Videos

https://youtu.be/SDXgfvBfCRA

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Medieval MC Fabric v15.5

### Optifine

No

**Comment by chorbintime** [comment]
Open your playerdata using NBTStudio and change your health attribute to 20.

Will be fixed in v16
