### ISSUE TITLE
Can't create a world

### ISSUE THREAD

**Issue by terriblewolf01** [LunaPixelStudios/Better-MC#1008]
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/10507639/latest.log)
I can't seem to create a world using better minecraft forge 1.19.2, it just gets stuck on 0% and stays there. When I end task and reload it show the world in my saves but the same thing happens when I try to run it.

**Comment by chorbintime** [comment]
Read the performance guide. Do not click while the game loads. If all else fails, try deleting the Sound Physics Remastered mod. Tell me if it fixes it.

**Comment by terriblewolf01** [comment]
removing the sound physics mod and increasing my memory allocation seems to have worked thanks for your help
