### ISSUE TITLE
low fps 

### ISSUE THREAD

**Issue by yoosof22** [LunaPixelStudios/Better-MC#1009]
### Describe the Bug

When I get close to a new structure, my fps decreases . But in normal mode, my fps is between 70 to 120

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot (62)](https://user-images.githubusercontent.com/123640501/214837426-d8aba7a4-d177-4b9c-9359-b719ba946f84.png)

### Operating System

windows 10 

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 Better MC [FABRIC] 1.19.2 v12.5

### Optifine

No

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?

**Comment by yoosof22** [comment]
> How did you install the modpack, step by step?

with tlauncher

**Comment by chorbintime** [comment]
We offer no support for TLauncher whatsoever. It's a known virus.
