### ISSUE TITLE
Updating version from v11 to v12 fps issue

### ISSUE THREAD

**Issue by WorLDz1337** [LunaPixelStudios/Better-MC#1010]
### Describe the Bug

Updating version from v11 to v12 fps near entities drastically decreased, for example farms, or big building where there are a lot of zombies and skeletons with armor. In version 11 the fps ofcourse decreased but in version 12 decreased fps doubled, tripled.

### Reproduction Steps

1.Get near many entities 
2.Fps drastically decreases 
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 v12

### Optifine

No

### Other Mods

NO

**Comment by WorLDz1337** [comment]
![v12](https://user-images.githubusercontent.com/123651055/214957645-d45d65ea-4058-4903-a7e4-a74410c88888.png)
![v11](https://user-images.githubusercontent.com/123651055/214957656-f805ab91-0d1f-47db-9c8e-36fe39805c97.png)
![vv11](https://user-images.githubusercontent.com/123651055/214957663-be397202-47a2-4d13-ad7b-be4755b8a443.png)
![vv12](https://user-images.githubusercontent.com/123651055/214957667-2f1be17a-2032-4d45-ae5d-2f4a55184ede.png)

**Comment by WorLDz1337** [comment]
Disabled Sound Physics Remastered and fps went back to normal

**Comment by chorbintime** [comment]
Will redirect to the Sound Physics Remastered dev
