### ISSUE TITLE
Can't create world

### ISSUE THREAD

**Issue by Thies99** [LunaPixelStudios/Better-MC#1011]
### Describe the Bug

Version 10.5 works great. I try to upgrade to v11 or v12 it crashes the game. It work fine till it creates the world. It keeps freezing at 0%

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC v12

### Optifine

No

**Comment by chorbintime** [comment]
Follow the performance guide please. Do not click while the game loads.
