### ISSUE TITLE
Can't assign the 'G' key.

### ISSUE THREAD

**Issue by Voidzinn** [LunaPixelStudios/Better-MC#1013]
### Describe the Bug

I just installed the modpack and I'm used to using the 'G' key to open the inventory, for me its more practical and I just can't use it for anything, I've tried even assigning it for walking and it doesn't work. Just for more information, there's no other function assigned with the 'G' key just the ones I tested. (sorry for my bad english lol)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
This is a known issue. We do not know what causes it. We do not plan on trying to fix it ourselves. Just don't bind anything to the G key. I apologize for the inconveinence.

You can use a program to make your G key activate a macro or remap the G key to E, which opens the inventory. There are several programs for this. 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by Voidzinn** [comment]
ohhh okay, its fine, thank you so much anyways :)

Em sáb., 28 de jan. de 2023 01:14, chorbintime ***@***.***>
escreveu:
