### ISSUE TITLE
Allways load my world crawling

### ISSUE THREAD

**Issue by ashvathaman** [LunaPixelStudios/Better-MC#1014]
### Describe the Bug

When I try to start my world, I always appear crawling and there is no way to stand up. I take everything off and it doesn't work.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.12

### Modloader

Fabric

### Modpack Version

v13.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Press left alt. Read quests next time, please. 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
