### ISSUE TITLE
My world crashes

### ISSUE THREAD

**Issue by Yohlef** [LunaPixelStudios/Better-MC#1015]
### Describe the Bug

When I start a world, the loading screen stays on 0% and then crashes.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

file:///C:/Users/User/Desktop/latest.log

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Optifine

No

**Comment by chorbintime** [comment]
You didn't attach a log. You attached the file path on your PC to where the log is.

Please follow the performance guide linked on the main menu.
