### ISSUE TITLE
Rendering speed super slow

### ISSUE THREAD

**Issue by zaniers** [LunaPixelStudios/Better-MC#1017]
### Describe the Bug

I'm experiencing very bad rendering speed of chunks. No matter what render distance I have, no matter how I adjust the settings.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V18

### Optifine

No

**Comment by chorbintime** [comment]
Follow the performance guide https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide

you can also pregenerate chunks using the ChunkPregenerator mod
