### ISSUE TITLE
Can't connect to multiplayer

### ISSUE THREAD

**Issue by cdthomas9** [LunaPixelStudios/Better-MC#1018]
### Describe the Bug

When trying to do a LAN game, we are getting java errors, one example is arrayindexoutofboundsexception index 167 length 3

I also tried creating a separate server to host the pack on, that gives simlar errors

### Reproduction Steps

1. Each system loads up the modpack via Curseforge
2. Player 1 starts the game and opens to LAN
3. Player 2 tries to join, can see the game in the multiplayer screen but can't join. Player 1 sees a connect and then immediate disconnect
...

### Operating System

Windows 11, Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v13.5

### Optifine

No

**Comment by chorbintime** [comment]
1) We offer no support for LAN. It does not work on modded MC and it never will.
You need to use the serverpack on the Curseforge page to selfhost the server. Read the readme file.

2) Update to v14.
