### ISSUE TITLE
1.19.2 Not getting the Void Shadow Quest after Killing Void Shadow

### ISSUE THREAD

**Issue by reidthegoat12** [LunaPixelStudios/Better-MC#1020]
### Describe the Bug

I have killed the void shadow twice now and each time after it dies and the chest spawns I have not been given the quest completion.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v13.2

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Please update to v16.5. Tell me if the issue persists.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by Sebastr06** [comment]
there is no v16.5 for fabric tho, atleast not on curseforge. mos recent is v14 and still has the bug

**Comment by chorbintime** [comment]
Will look into it, thanks

**Comment by SSHadow2000** [comment]
I am having this same issue. Killed it twice, the quest rewards are still locked. I'm on windows 10, no optifine, version 16.6. I don't see any solution to this anywhere
