### ISSUE TITLE
OTBYG open door textures backwards

### ISSUE THREAD

**Issue by wolfhartconroy** [LunaPixelStudios/Better-MC#1021]
### Describe the Bug

So I noticed when opening double doors especially, that the handles and hinges textures on flipped on the wrong side when opening the door.

### Reproduction Steps

1.open door

### Screenshots and Videos

![2023-02-01_22 45 02](https://user-images.githubusercontent.com/124231655/216233758-2a8ac5bd-0d3a-45c3-88c9-3d2dc4ba87d7.png)
![2023-02-01_22 45 04](https://user-images.githubusercontent.com/124231655/216233775-0fe78682-c1d1-439e-88bd-59dd0ad1d7c7.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v14

### Optifine

No

**Comment by chorbintime** [comment]
Not something we can fix. Report to OBYG dev or update the mod to see if it's fixed already
