### ISSUE TITLE
Armor dupe

### ISSUE THREAD

**Issue by SoSBlocking** [LunaPixelStudios/Better-MC#1022]
### Describe the Bug

v1.19.2 minecraft  | modpack v15.5
If you were to put your helmet here and die, then pick up your items once you respawn, you will have your duped item on the floor as your other item stay were it was last put.
![image](https://user-images.githubusercontent.com/124242494/216261137-85d539fd-ca42-4962-b248-ff3e11747f64.png)

### Reproduction Steps

1.put wearable item here in any of the slots that look like this
![image](https://user-images.githubusercontent.com/124242494/216261500-d6ec596b-6da3-4fb6-8442-231f774e4527.png)

2.die
3.pick items back up from grave ( I don't know if your inventory needs to be full for this to happen)
3. dupe has been done

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15.5

### Optifine

No

**Comment by chorbintime** [comment]
Fixed in v16.5
