### ISSUE TITLE
Relic EX mod bug after update medival V1.16 fabric

### ISSUE THREAD

**Issue by Nice271177** [LunaPixelStudios/Better-MC#1023]
### Describe the Bug

Relic EX mod bug after update medival V1.16 fabric

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![faaf169a9275d2a99f0f6fba1f0add88](https://user-images.githubusercontent.com/53823040/216302430-50fd1cf3-bc2b-4f10-9863-1b81ba1ad6f3.png)

### Operating System

Window 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Medival 1.16

### Optifine

No

**Comment by chorbintime** [comment]
Fixed in v16.5
