### ISSUE TITLE
Game crashing 

### ISSUE THREAD

**Issue by Janoale** [LunaPixelStudios/Better-MC#1024]
### Describe the Bug

Game crashes by rendering entity in world

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/124324535/216493402-1ea725fe-a12a-4aac-ac2d-28ff834c56b3.png)

![image](https://user-images.githubusercontent.com/124324535/216492106-5fea1128-733a-4efc-8ebf-2936bdeb6ebc.png)

### Crash Report or Log

(https://mclo.gs/KbYAYw0)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 v12

### Optifine

No

**Comment by chorbintime** [comment]
I need the full crash report file or it is impossible for me, or anyone else, to help. 

Post it on https://mclo.gs/

**Comment by Janoale** [comment]
> I need the full crash report file or it is impossible for me, or anyone else, to help.
> 
> Post it on https://mclo.gs/

https://mclo.gs/KbYAYw0

**Comment by chorbintime** [comment]
Remove any non-english characters from your Windows PC name

if issue persists remove maiden's merrymaking mod

**Comment by Janoale** [comment]
> Remove any non-english characters from your Windows PC name
> 
> if issue persists remove maiden's merrymaking mod

Hi, i am a spanish, and if i remove everything that its not english, i would need to delete a lot of things of my pc, i dont understand
