### ISSUE TITLE
Game Keeps Crashing When Entering The Nether and It Won't Let Me Submit A Crash Long

### ISSUE THREAD

**Issue by bigbrain6969** [LunaPixelStudios/Better-MC#1025]
Can't enter the nether without the game dropping my fps insanely low then crashing. Overworld is fine. I would love to submit a crash report but whenever I try to file one the file is blank.

**Comment by chorbintime** [comment]
Please follow the performance guide https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide

I don't know what you mean by "try to file one"
