### ISSUE TITLE
Aether Dimension Better Minecraft 19.2 Fabric

### ISSUE THREAD

**Issue by ManuWerner** [LunaPixelStudios/Better-MC#1026]
### Describe the Bug

So when i enterr the aether dimension my minecraft crashes. Cant join it in solo or multyplayer
Here is the log from my multyplayer server cause i dont know how to link it
<html>
<body>

[17:41:16] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.12
--
2 | [17:41:16] [ForkJoinPool-1-worker-3/WARN]: The mod "dungeons_arise" contains invalid entries in its mod json:
3 | - Unsupported root entry "credits" at line 12 column 12
4 | [17:41:16] [ForkJoinPool-1-worker-2/WARN]: Mod com_github_jctools_jctools_jctools-core uses the version v4.0.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v4'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
5 | [17:41:16] [ForkJoinPool-1-worker-3/WARN]: Mod netherdepthsupgrade uses the version fabric-2.0.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
6 | [17:41:16] [ForkJoinPool-1-worker-1/WARN]: The mod "thonkutil-customization-v1" contains invalid entries in its mod json:
7 | - Unsupported root entry "disabled:mixins" at line 11 column 20
8 | [17:41:17] [main/WARN]: Warnings were found!
9 | - Mod 'Better Statistics Screen' (betterstats) 2.1.1+1.19.2 recommends any 2.x version of mod 'TCD Commons API' (tcdcommons), but only the wrong version is present: 1.1+1.19.2!
10 | - You should install any 2.x version of mod 'TCD Commons API' (tcdcommons) for the optimal experience.
11 | - Mod 'Better Statistics Screen' (betterstats) 2.1.1+1.19.2 recommends any version of modmenu, which is missing!
12 | - You should install any version of modmenu for the optimal experience.
13 | - Mod 'Debugify' (debugify) 2.8.0 recommends any version of modmenu, which is missing!
14 | - You should install any version of modmenu for the optimal experience.
15 | - Mod 'Deepslate Cutting' (deepslatecutting) 1.5.0 recommends any version of modmenu, which is missing!
16 | - You should install any version of modmenu for the optimal experience.
17 | - Mod 'Reacharound' (reacharound) 1.1.2 recommends any version of modmenu, which is missing!
18 | - You should install any version of modmenu for the optimal experience.

</body>
</html>[17:41:16] [main/INFO]: Loading Minecraft 1.19.[2](https://aternos.org/log/#L2) with Fabric Loader 0.14.12
[17:41:16] [ForkJoinPool-1-worker-3/WARN]: The mod "dungeons_arise" contains invalid entries in its mod json:
- Unsupported root entry "credits" at line 12 column 12
[17:41:16] [ForkJoinPool-1-worker-2/WARN]: Mod com_github_jctools_jctools_jctools-core uses the version v4.0.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v4'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:41:16] [ForkJoinPool-1-worker-[3](https://aternos.org/log/#L3)/WARN]: Mod netherdepthsupgrade uses the version fabric-2.0.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:[4](https://aternos.org/log/#L4)1:16] [ForkJoinPool-1-worker-1/WARN]: The mod "thonkutil-customization-v1" contains invalid entries in its mod json:
- Unsupported root entry "disabled:mixins" at line 11 column 20
[17:41:17] [main/WARN]: Warnings were found!
 - Mod 'Better Statistics Screen' (betterstats) 2.1.1+1.19.2 recommends any 2.x version of mod 'TCD Commons API' (tcdcommons), but only the wrong version is present: 1.1+1.19.2!
	 - You should install any 2.x version of mod 'TCD Commons API' (tcdcommons) for the optimal experience.
 - Mod 'Better Statistics Screen' (betterstats) 2.1.1+1.19.2 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'Debugify' (debugify) 2.8.0 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'Deepslate Cutting' (deepslatecutting) 1.[5](https://aternos.org/log/#L5).0 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'Reacharound' (reacharound) 1.1.2 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.

### Reproduction Steps

1.build the aether portal
2.go in
3.crashes
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better Minecraft

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
This log does not help. All it shows is you starting the game. Please upload the crash report to https://mclo.gs 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
