### ISSUE TITLE
bewitchment resin

### ISSUE THREAD

**Issue by GoodBoy1983** [LunaPixelStudios/Better-MC#1027]
### Describe the Bug

When I use the athame on the dragons blood tree it shows the bleed however it docent drop the resin or put it in the inventory I checked the book and the wiki and it said its supposed to drop it so maybe something isn't working

### Reproduction Steps

1.grow a dragons blood tree from bewitchment
2.use an athame on the tree
3.
...

### Operating System

windows11

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

V15.5

### Optifine

No

**Comment by chorbintime** [comment]
Not a modpack issue
