### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by crossetth** [LunaPixelStudios/Better-MC#1028]
### Describe the Bug

The game keeps crashing either immediately after opening my world or within an hour or less of playtime. Its given me an error of dedicating more ram to it so I have. It crashes again. I take it back down to the normal 8. Crashes again. I try doing everything between. I've already tried to uninstall and reinstall, I've tried disabling the antivirus software and restarting and still, nothing. Not sure what else to do.

### Reproduction Steps

1. Open game
2. Open world
3. Wait a second

### Screenshots and Videos

n/a

### Crash Report or Log

idk how to do that

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc3 V12

### Optifine

I used Optifine

### Other Mods

n/a

**Comment by chorbintime** [comment]
It's impossible to help without logs.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by crossetth** [comment]
[crash-2023-02-03_18.13.29-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/10611558/crash-2023-02-03_18.13.29-client.txt)

**Comment by chorbintime** [comment]
Your PC is running out of storage.
