### ISSUE TITLE
HOW DO I UPDATE MODPACK

### ISSUE THREAD

**Issue by Sebastr06** [LunaPixelStudios/Better-MC#1029]
I've created a world that i dont want to lose on version 13.5 and I want to update to v14, i cant find any tutorial and im not an expert in modding minecraft whatsoever so is there any video or step by step tutorial i could follow to update my game without loosing the save file?

**Comment by chorbintime** [comment]
You click the Change Version button in Curseforge.

If you aren't using a modded launcher, you need one to properly install & play modpacks. Curseforge Launcher is not recommended, we suggest ATLauncher instead. You can always make a copy of your saves folder before updating and you can transfer it to ATLauncher.
