### ISSUE TITLE
Not bug but confused to as where improved armour sets are. 

### ISSUE THREAD

**Issue by OtisWong** [LunaPixelStudios/Better-MC#1030]
Seen many videos about better netherite gear but in game there is no such mod or crafting recipe. just wondering if you removed it or if its hidden, thanks

**Comment by chorbintime** [comment]
we don't know what modpack you're playing. there are several Better MC modpacks with different mods. the Forge version has the Upgraded Netherite mod but the mod isn't available for Fabric
