### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Lymono2137** [LunaPixelStudios/Better-MC#1031]
### Describe the Bug

So I installed server pack on a server by draging all files (without start.ps1 and start.sh beacuse Im using a hosting) to server directory.
Im using fabric on a server and client and I just can't connect to server.

### Reproduction Steps

1. Trying to connect to the server
2. Error message occurs
3.
...

### Screenshots and Videos

![2023-02-04_12 33 15](https://user-images.githubusercontent.com/124439650/216766732-dd81f5de-0726-4446-a597-92438a465c68.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v14

### Optifine

No

**Comment by SHXRKIIE** [comment]
Could you see if removing brewin and chewin from the server and client fixes it:?

**Comment by Lymono2137** [comment]
Whats brewin and chewin? Probably not a mod

**Comment by SHXRKIIE** [comment]
its a mod

**Comment by Lymono2137** [comment]
well, I can't see a mod like that

**Comment by SHXRKIIE** [comment]
could you give the latest log of the server and client please

**Comment by Lymono2137** [comment]
[rei.log](https://github.com/LunaPixelStudios/Better-MC/files/10608704/rei.log)
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/10608706/latest.log)
in server log there is only information that I was disconected, nothing important

**Comment by Lymono2137** [comment]
only server warn is this
[12:58:45] [ServerMain/WARN]: Failed to parse level-type betterx, defaulting to minecraft:normal
idk if it helps

**Comment by SHXRKIIE** [comment]
can you try an see if deleting the paxi folder in the config and default config folder on server and in the world folder delete the datapacks folder and see if you can join

**Comment by SHXRKIIE** [comment]
you did restart the server? this is a new world correct? if so could you possibly give me the seed by typing it in the hosts console /seed and give it to me

**Comment by Lymono2137** [comment]
I have created a new world and restarted server. Seed: [-4679210345056413444]

**Comment by Lymono2137** [comment]
Yep

**Comment by SHXRKIIE** [comment]
trying the seed but cant get the issue, could you delete the paxi folder in configs and default configs on the server and remove all of these mods from server and client 
farmer delight
expanded delight
cultural delight
nethers delight
and see if you can connect. sorry for this, its hard to get to the root of the cause of the log doesnt give us much info, this should work i hope.

**Comment by SHXRKIIE** [comment]
sorry also these 2 
farmers resprite
farmer knives

**Comment by Lymono2137** [comment]
I did it all and it didn't fix the problem

**Comment by Lymono2137** [comment]
Do you know any stable version of this modpack for fabric or forge?

**Comment by yash1441** [comment]
Same issue. Using v14 Fabric 1.19.2

**Comment by SHXRKIIE** [comment]
v13.5 is stable, v14.5 is suppose to be stable but this unknown issue is causing a pain.

**Comment by yash1441** [comment]
Tried v13.5 as well. Getting the same error. But I am able to join a public v13.5 server so something must be wrong with the server files?

**Comment by SHXRKIIE** [comment]
you might have a different issue then since this doesnt occur on v13.5.

**Comment by yash1441** [comment]
It is exactly as the author's screenshot, in the meantime I tried v13 as well with the same error

**Comment by Tansmh** [comment]
Same issue, tried different versions but still the exact same error.

**Comment by Tansmh** [comment]
Contacted the host, they were able to fix it and we're able to run 1.14 now

**Comment by Lymono2137** [comment]
Checked v13.5 and same issue. Maybe I'm installing server pack wrong

**Comment by yash1441** [comment]
> Contacted the host, they were able to fix it and we're able to run 1.14 now
> 
> `It appears that when you installed the modpack, it just installed MC Vanilla 1.19.2 instead of Fabric. So I just changed the server type manually.`
> 
> This is what they said.

This was my issue as well. Fixed.
