### ISSUE TITLE
Creating server files

### ISSUE THREAD

**Issue by marco898989** [LunaPixelStudios/Better-MC#1032]
### Describe the Bug

running start.ps1 powershell will block after the load of xaero's minimap

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v14

### Optifine

No

**Comment by chorbintime** [comment]
This tells me nothing. I can not help without logs.
