### ISSUE TITLE
Kicked from Server: Internal Exception: javalang. RuntimeException: Tried to read NET tag that was too big; tried to allocate: 2097181bytes where max allowed: 2097152

### ISSUE THREAD

**Issue by oracle-of-me** [LunaPixelStudios/Better-MC#1035]
### Describe the Bug

Hello, we are having a problem on our Server. 
After some time, players get kicked from the server with the following Exception:
"Internal Exception: javalang. RuntimeException: Tried to read NET tag that was too big; tried to allocate: 2097181 bytes where max allowed: 2097152" 
The number at the end sometimes changes.
After that point, one cannot reconnect, because you get kicked instantly. The worst part is that once this happens to one player, sooner or later all players get this bug. Then the server crashes and if we are really unlucky, all the player data gets deleted from individual players. All Items, all Waypoint, everything GONE. The world also seems to change. We wanted to build on one of those Volvic Water Volcanos, but after the bug there were hole chunks reset and parts of the Mountains were gone. Looked incredibly stupid and wasn't fixable by something like Worldedit regen (which we tried after the first bug appeared).

To prevent inventory loss, we stop the server the second this error occurs for any player. Unfortunately, I can't find any crash Logs of the Server. I have logs from when the server crashed because of WorlEdit and because it crashed because of Textile Backup. There are no Crash Logs from the first times this occurred. 

### Reproduction Steps

1. Play the Game like normal
2.  Get kicked by the Bug

### Screenshots and Videos

![Screenshot 2023-02-05 122243](https://user-images.githubusercontent.com/94798337/216815874-b7726ecd-0a76-4fbb-8150-d5ae73a4754a.png)

### Crash Report or Log

https://gist.github.com/oracle-of-me/a618814968b2be0b5ffc049f26753436

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

newest

### Optifine

No

**Comment by chorbintime** [comment]
update the modpack
