### ISSUE TITLE
Some Items Make Blocks Underneath Invisible 

### ISSUE THREAD

**Issue by Snailridery** [LunaPixelStudios/Better-MC#1036]
### Describe the Bug

I've been researching about this problem, and it seems to be related to Sodium, but I wasn't able to find a fix.

### Reproduction Steps

1. Place an Adorn Coffee table, for example 
2. Invisibility, as shown in the screenshot

### Screenshots and Videos

![2023-02-05_20 01 25](https://user-images.githubusercontent.com/124526670/216839797-467a19d5-c740-404d-929d-d782571699c1.png)

### Operating System

Windows 10 

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v13

### Optifine

No

### Other Mods

WorldEdit

**Comment by chorbintime** [comment]
update the modpack
