### ISSUE TITLE
Better minecraft Forge 1.19.2 Server crash on startup

### ISSUE THREAD

**Issue by TheMemorium** [LunaPixelStudios/Better-MC#1037]
### Describe the Bug

When me and my friend load into the server we get disconnected. We were in the twilight forest and loaded up a structure when the server instantly crashed. When we reconnect it crashes a second after you log in. 

We are running the server through Exaroton. 

Crashreport attached

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/lyW2Y6p

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3

### Optifine

No

### Other Mods

No.

**Comment by chorbintime** [comment]
not a modpack issue
