### ISSUE TITLE
Can't Disable Narrator

### ISSUE THREAD

**Issue by hopelesslala** [LunaPixelStudios/Better-MC#1038]
### Describe the Bug

No matter what I try I cannot disable narrator for better minecraft. it isn't a computer thing it only happens when I play this version of minecraft.

### Reproduction Steps

1. Not sure
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 v12

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Go into Accessibility Settings and disable Narrator there. Alternatively, press CTRL + B.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
