### ISSUE TITLE
Authentication Servers Aren't Responding

### ISSUE THREAD

**Issue by MildlySurprisedKitty** [LunaPixelStudios/Better-MC#1041]
### Describe the Bug

On my privately hosted server every time I or one of my friends tries to connect it just says the auth servers are down. I've tried all the solutions I could find for vanilla MC and none have worked. What's more is that I can connect to servers like Hypixel on my vanilla instance no problem.

![image](https://user-images.githubusercontent.com/125076149/218152069-85e1bf0d-1e8f-4a96-a1fd-fa5c943fef62.png)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v12

### Optifine

No

### Other Mods

Create

**Comment by chorbintime** [comment]
You did not install the modpack properly. You need to use a modded launcher such as ATLauncher to install & play modpacks. Additionally, this is not a modpack issue. If the issue persists on a proper installation, you need to migrate your Mojang account to Microsoft if it isn't already.

**Comment by MildlySurprisedKitty** [comment]
I installed the pack through GDLauncher and I've already migrated my account

**Comment by MildlySurprisedKitty** [comment]
> You did not install the modpack properly. You need to use a modded launcher such as ATLauncher to install & play modpacks. Additionally, this is not a modpack issue. If the issue persists on a proper installation, you need to migrate your Mojang account to Microsoft if it isn't already.

Also I recently tried an ATLauncher install and am getting the exact same issue. My Mojang account has already been merged into a Microsoft.

**Comment by chorbintime** [comment]
Once again, this is not a modpack issue. There is something wrong on server or clientside. You can try disabling your firewall / antivirus, and make sure others can join the server.
