### ISSUE TITLE
Game appereance 

### ISSUE THREAD

**Issue by yyy23yss** [LunaPixelStudios/Better-MC#1042]
### Describe the Bug

Hello, just a simple question how to turn off the new clouds? 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Снимок](https://user-images.githubusercontent.com/125093770/218206077-fde3d651-8e43-42c9-b84b-84e49cdd8c0a.PNG)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Delete the Nicer Skies mod

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
