### ISSUE TITLE
Waypoint bug ? more issues then anything

### ISSUE THREAD

**Issue by umemI22** [LunaPixelStudios/Better-MC#1043]
### Describe the Bug

Alright so my boyfriend and I have been playing this mod pack and everything is smooth but one thing, in particular, keeps happening and it's VERY frustrating. I have a server with said mod pack and anytime there is an update to the mod pack it messes with the waypoints and deletes ALL of them every single one I've tried going into my backup folders and I found a couple of the waypoints but by no means nowhere near all of them. On top of that annoying issue, the mini-map in the mod pack that is part of the mod for waypoints.  It regenerates?? like none of the places I explored are there when I look at the mini-map. this includes all the dimensions and overworld.
I reached out to the mod creator himself and he replied but did not help whatsoever if anyone else Is having this issue and learned how to fix it please reach out! 

### Reproduction Steps

1. HAvent found any
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
copy the journeymap folder in the modpack files to the updated modpack installation

**Comment by umemI22** [comment]
Where do I put the copy? I tried that and nothing happened I tried putting it in the backup folder and also nothing, unfortunately, nothing happened if you could be more detailed that would be appreciated.

**Comment by chorbintime** [comment]
you copy the xaeros minimap folder that is inside your modpack files (its found clientside, not serverside), then paste it to the exact same place you found it except on the new, updated installation,
