### ISSUE TITLE
Crashing v15 with mod supplementaries

### ISSUE THREAD

**Issue by vandyr-creator** [LunaPixelStudios/Better-MC#1044]
### Describe the Bug
After starting Minecraft in the Launcher, nothing appears and just crashes while loading mods.
Without only supplementaries minecraft loading succesfully...
[crash-2023-02-11_13.02.02-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/10713116/crash-2023-02-11_13.02.02-client.txt)

downloaded the modpack from here [tap](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric)
### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Fabric

### Modpack Version

bmc1 v15

### Optifine

No

### Other Mods

[tl_skin_cape_fabric_1.19.2-1.27.zip](https://github.com/LunaPixelStudios/Better-MC/files/10713066/tl_skin_cape_fabric_1.19.2-1.27.zip)

**Comment by vandyr-creator** [comment]
[crash-2023-02-11_12.43.00-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/10713079/crash-2023-02-11_12.43.00-client.txt)

**Comment by SHXRKIIE** [comment]
remove the mod you added
