### ISSUE TITLE
Trying to play Better MC and have been having problems loading to make a new world

### ISSUE THREAD

**Issue by cwt6199** [LunaPixelStudios/Better-MC#1045]
### Describe the Bug

When I try to play Better MC it has been taking a long time to load. I go into curse forge and click play it will load the launcher and then click play in the launcher. It take around 5-10 minutes to try to load but it will crash and take me back to the launcher and says The game crashed whilst rendering overlay
Error: java.lang.RuntimeException: null
[Minecraft crash log.txt](https://github.com/LunaPixelStudios/Better-MC/files/10715074/Minecraft.crash.log.txt)

### Reproduction Steps

1. Go into curse forge, click my modpacks, and click play on Better MC FORGE BMC2
2. Wait for minecraft launcher to load, when loaded click play
3. Wait for minecraft to load but it crashes instead and shows crash error
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC2

### Optifine

No

### Other Mods

No other mods

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?

**Comment by Arpello** [comment]
I have been having the same issue game will not load freezes or crashes when loading world.
Sometimes I do not get to the world load screen for this to happen.
I loaded mod pack thru curseforge.

**Comment by chorbintime** [comment]
> I have been having the same issue game will not load freezes or crashes when loading world. Sometimes I do not get to the world load screen for this to happen. I loaded mod pack thru curseforge.

I can't help without a crash report.

Make sure to follow the performance guide linked on the main menu. If you still can't get into a world and you're playing 1.19.2 then remove the Sound Physics Remastered mod.

**Comment by cwt6199** [comment]
> 

I went into the curse forge desktop app and went to browse mod packs. I saw the better mc 1.19.2 mod pack and I clicked on the orange download button

**Comment by chorbintime** [comment]
Switch to ATLauncher

Do not update or add mods

**Comment by Thritis** [comment]
I tried everything listed in the performance guide on 2 different computers and still crashes. When it loads, it's as if i have a potato computer. What are the minimum PC requirements? I have ryzen 5 with 3070 and ryzen 9 with 3070ti. Both with 16 GB of RAM. I had to switch to BMC1 fabric but it seems like a lot of stuff is missing compared to BMC3 forge.

**Comment by chorbintime** [comment]
Follow the performance guide, if the issue persists, delete the Sound Physics Remastered mod
