### ISSUE TITLE
Game crashes when you go into the eternal portal. (Better End)

### ISSUE THREAD

**Issue by JokerSix66** [LunaPixelStudios/Better-MC#1046]
### Describe the Bug

After I activate the portal with the crystals in the end and step into the portal, it automatically crashes.
I do not get a proper error message.
Fortunately there are backups because the world is no longer playable after the problem.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

[crash-2023-02-12_01.27.02-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10715834/crash-2023-02-12_01.27.02-server.txt)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC / Better End

### Optifine

No

**Comment by SHXRKIIE** [comment]
Update to latest

**Comment by linkbeta5** [comment]
The same exact thing happened to my server. We finally made the Eternal Portal, went through it, crashed, and have been stuck in a boot loop on our server. Admin will be reverting the save file to a backup. NOTE: The portal was made perfectly fine, it was upon entering the portal that it crashed the server and made the save unplayable.
