### ISSUE TITLE
Unable to get into a world

### ISSUE THREAD

**Issue by Arpello** [LunaPixelStudios/Better-MC#1048]
### Describe the Bug

I have been trying to play this version for a few weeks now. I launch the game thru curseforge and hit play on the launcher, then hit singleplayer, then create world and it freezes at 0% loaded. I waited for 10 min. to see if it would load and it did not.
I did finally get an exit code 805306369

### Reproduction Steps

1.Hit play to launch lancher
2.hit play on launcher
3.set up a world and then hit create world
4. box shows up says 0% at top Then it freezes
...

### Screenshots and Videos

![20230212_175653](https://user-images.githubusercontent.com/113543545/218354605-3766d7da-c3ed-43f8-96a5-bd2f2f87837c.jpg)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Optifine

No

**Comment by SHXRKIIE** [comment]
Try these https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide
