### ISSUE TITLE
Zombie villager missing textures

### ISSUE THREAD

**Issue by ardenyte** [LunaPixelStudios/Better-MC#1049]
### Describe the Bug

After updating to v15, some zombie villagers started spawning in without their usual textures, seemingly at random. I haven't encountered this issue before the update, nor does it happen with any other mob. Aside from the texture, the messed up zombie villagers work exactly the same as all others. 

### Screenshots and Videos

![Screenshot_233](https://user-images.githubusercontent.com/125234695/218364381-6021634a-c899-4021-bcaa-ba8434bf9b99.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc1 v15

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Does removing the VillagersPlus mod fix it?
Does removing the Chef's Delight mod fix it?

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by ardenyte** [comment]
The issue persists even after removing both mods.

The Optifine thing was my mistake - I believe I just forgot to change it, considering it is the default option and I use the mod often otherwise. You're right, I am not using it in this case, apologies for the oversight.

**Comment by chorbintime** [comment]
Copy your options.txt, saves folder, and config folder to your desktop

Delete options.txt and the config folder

Is the texture still missing?

**Comment by ardenyte** [comment]
Still very much missing.

**Comment by chorbintime** [comment]
Make a backup of your world, delete the MoreVillagers mod. If the issue persists, try deleting Smarter Farmers. Does deleting either fix it?

**Comment by ardenyte** [comment]
Could not locate MoreVillagers - I redownloaded the whole pack to a new curseforge profile just to make sure I didn't accidentally remove it, but it's not there either. 

Deleting Smarter Farmers, however, does not fix the issue.

**Comment by chorbintime** [comment]
I meant VillagersPlus, not MoreVillagers. My apologies
