### ISSUE TITLE
Server ping

### ISSUE THREAD

**Issue by EP101010** [LunaPixelStudios/Better-MC#1050]
### Describe the Bug

i had played the modpack for a couple days now without any issues. but all of a sudden i keep having bad connection to my server. but the other players in it have no issue. i keep getting timed out or syncing problems. i dont know if its me or the mods or the server. any possible solution? .... overall i just have a bad connection to the server. but the change was sudden and its only on my side. not the other players

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12 forge 43.2.3

### Optifine

No

**Comment by LightCyan01** [comment]
If you were able to play normally before and the fact that your friends have no issues, its quite obvious who the culprit is. That would be your internet connection, not the modpack. contact your isp about it.

**Comment by SHXRKIIE** [comment]
its an issue with your internet itself
