### ISSUE TITLE
Supplementaries missing textures

### ISSUE THREAD

**Issue by YamiMillennium** [LunaPixelStudios/Better-MC#1051]
### Describe the Bug

The hanging wall signs and hanging lanterns that Supplementaries allows are missing their textures.  This has happened on BMC versions 14, 14.5 and the newest version, 15.
![signleftlanternright](https://user-images.githubusercontent.com/125405602/218858440-08d22c82-f24c-4b68-96cb-3fdf7573fc63.png)

### Reproduction Steps

1. Grab a lantern or sign.
2. Hang it on a wall.
...

### Screenshots and Videos

![signleftlanternright](https://user-images.githubusercontent.com/125405602/218858630-e055ca39-cfbd-4dbb-a552-189374db27ff.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC v15

### Optifine

No

### Other Mods

Adorn
Chipped

**Comment by chorbintime** [comment]
Report to Supplementaries github
