### ISSUE TITLE
Problem with Maiden's merrymaking

### ISSUE THREAD

**Issue by JamesCZYT** [LunaPixelStudios/Better-MC#1052]
### Describe the Bug

Hey, I encountered a problem while playing with my friend on a server. Maiden's merrymaking mod is not able to load a "red leather" texture in .png on a zombie and it causes the game to crash. 

### Reproduction Steps

1.Load up a world
2.Spawn mobs modified by Maiden's merrymaking mob
3.Zombies with red on them should cause crash
...

### Crash Report or Log
error textures/models/armor/maidens merrymaking:red santa hat leather layer 1.png
error code: -1

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v12

### Optifine

No

### Other Mods

No mods added

**Comment by chorbintime** [comment]
Remove or update the Maidens Merrymaking mod
