### ISSUE TITLE
Crash when I join my survival world.

### ISSUE THREAD

**Issue by F8GG** [LunaPixelStudios/Better-MC#1053]
### Describe the Bug

I played normally for about 10 hours on this normal modpack and then it started crashing right when I open Survival World. Help.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/MNZaZm0c

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 V12

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Remove the Maiden's Merrymaking mod.
You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod.
