### ISSUE TITLE
Broken Corn Texture with Straw Golem Harvesting

### ISSUE THREAD

**Issue by Dominus01** [LunaPixelStudios/Better-MC#1054]
### Describe the Bug

Minor bug without gameplay issues. Texture on corn crop is not rendering when harvested by the straw golem.

### Reproduction Steps

1. Make Straw Golem
2. Have Golem harvest corn from cultural delights mod
...

### Screenshots and Videos

![2023-02-17_09 38 00](https://user-images.githubusercontent.com/56710909/219729010-66cc20b7-a64c-4e57-9b6e-a9c55d8f16bb.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v14.5

### Optifine

No

**Comment by chorbintime** [comment]
should report this on the github of whichever mod adds the corn
