### ISSUE TITLE
end ships

### ISSUE THREAD

**Issue by AlmightyAlex** [LunaPixelStudios/Better-MC#1055]
### Describe the Bug

there is no loot in end ships i find or elytra or the shulker spawners that suppose to be in and its a full ship

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2 v15.zip

### Optifine

No

**Comment by chorbintime** [comment]
will look into it
