### ISSUE TITLE
Server Crashes when approaching Deep Ocean Biomes.

### ISSUE THREAD

**Issue by KamilJaba** [LunaPixelStudios/Better-MC#1056]
### Describe the Bug

Server crashes with seemingly no logs when going near any Deep Ocean biome. We host on Skynode(saw the other issue from the guy with Snowy Biome on Bisect Hosting so maybe this matters with the way these providers host idk?). Assumed travelling too fast on boats caused it at first but after testing using a Natures Compass and some fly "walking" around slowly to let chunks load the server crashed without fail when trying to load any Deep Ocean biome within like 100 blocks, I tried a few different Deep Ocean biomes at different parts of the map and always the same issue force closing the server.

### Reproduction Steps

1. Go within 100 block of any Deep Ocean
2. Server Crashes
3.
...

### Crash Report or Log

https://gist.github.com/KamilJaba/1f97fb8f9e327d2dd56d8ff4deebb36d

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v15 1.19.2

### Optifine

No

### Other Mods

Create Fabric,
Croptopia,
Iron Chests Restocked.

**Comment by chorbintime** [comment]
Please click this link and follow the guide. If you are using a server host such as Bisect, you may be limited in your options and instead have a checkbox to use Aikar's Flags, which will also work:
https://github.com/etil2jz/etil-minecraft-flags 
If you can not launch your server/game after using these flags, then remove the word java from the start. Also, make sure you are using Java 18 on 1.18.2 / 1.19.2 and Java 11 on 1.16.5. These should be downloaded from Adoptium's website.

If lag persists, do the following command ingame:
/spark profiler start --only-ticks-over 50
Then, send the link here.
