### ISSUE TITLE
Game crashes after loading screen gets to 100%

### ISSUE THREAD

**Issue by strawbebbyjess** [LunaPixelStudios/Better-MC#1057]
### Describe the Bug

Every time I try to open my world, it shows the loading screen at 100% and then immediately closes the app. The error message reads "The game crashed whilst exception in server tick loop. Error: java.lang.IllegalStateException". Yesterday was when I downloaded Better Minecraft Fabric and it launched just fine.

### Reproduction Steps

1. open mod on curseforge app
2. java opens, click on singleplayer
3. select world and click on play selected world
4. loading screen gets to 100% but java crashes
...

### Crash Report or Log

I have the textedit file but not sure how to add the link.

### Operating System

MacOS 12.4

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc1

### Optifine

No

**Comment by chorbintime** [comment]
I can not help without logs or a crash report.

Please follow the performance guide linked on the main menu.

**Comment by strawbebbyjess** [comment]
[crash-2023-02-18_11.42.19-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10776016/crash-2023-02-18_11.42.19-server.txt)

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?
