### ISSUE TITLE
Game crashes after entering Eternal Portal in the end

### ISSUE THREAD

**Issue by Tapfight** [LunaPixelStudios/Better-MC#1060]
Game crashes after entering Eternal Portal in the end.
Crashes every time I load back in, Restarting minecraft doesn't fix the issue.

**Comment by Benubisnitch** [comment]
Also have this issue.
Cant get a crash report to generate. It boots the player out of my server and gets stuck there unless I TP them.

**Comment by chorbintime** [comment]
I can not help either of you without logs.

**Comment by Benubisnitch** [comment]
Got one to generate 
https://pastebin.com/4740PPie

**Comment by Tapfight** [comment]
Here is the crash report
[crash-2023-02-20_02.25.13-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10782054/crash-2023-02-20_02.25.13-server.txt)
I forgot to specify that I am on v15 1.19.2 of the mod pack

**Comment by chorbintime** [comment]
Explicitly an issue with the BetterEnd mod.
If BetterEnd & BCLib have updates available: update.
If the issue persists, or no update is available, report this on the BetterEnd github and change your coordinates by editing your playerdats using NBTStudio (google it).

**Comment by Tapfight** [comment]
Alright, thank you for the help!

**Comment by tsa96** [comment]
To confirm, updating BetterEnd and BCLib fixes this.
