### ISSUE TITLE
Server Crash in Bumblezone

### ISSUE THREAD

**Issue by Benubisnitch** [LunaPixelStudios/Better-MC#1061]
### Describe the Bug

My server crashes if someone loads in the Bumblezone Dimension.

### Reproduction Steps

1. Enter the Bumblezone.
2. 
3.
...

### Crash Report or Log

https://pastebin.com/ywYvu0jH

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V15

### Optifine

No

**Comment by chorbintime** [comment]
Add this datapack to config -> paxi -> datapacks
https://cdn.discordapp.com/attachments/841975353655951391/1075894346597023814/bumblezone_no_biome_makeover_moth.zip
