### ISSUE TITLE
Game Crashes due to CAKE!!!

### ISSUE THREAD

**Issue by shrooompy** [LunaPixelStudios/Better-MC#1062]
### Describe the Bug

Every time I eat a Slice of Strawberry Cake from the Neopolitan mod, game crashes. Also posted on their report page.

exit code:
-805306369

error msg:
The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "com.cursedcauldron.wildbackport.common.effects.EffectFactor.getFactorCalculationData()" because the return value of "com.cursedcauldron.wildbackport.common.effects.EffectFactor.of(net.minecraft.world.effect.MobEffect)" is null

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

**Comment by chorbintime** [comment]
Please attach the full crash report file. A snippet is not enough.

**Comment by chorbintime** [comment]
Fixed in latest version of Abnormals Delight
