### ISSUE TITLE
Use the supplementaries cage to capture a spectre from galosphere drops framerates to below 20

### ISSUE THREAD

**Issue by AI-nsley69** [LunaPixelStudios/Better-MC#1063]
### Describe the Bug

When caging a spectre, the framerates will plummet to unplayable rates, whether you're looking into an inventory with the cage, in an item frame, or rendering in the hand. If the item is rendered in any way, the framerates will drop a lot. I tested with another player and as soon as they turned away, their framerates returned to normal. 

I attempted to reproduce by copying over the following mods from the mods directory of the modpack in another instance:
- Fabric API
- Galosphere
- Indium
- Lithium
- Moonlight
- Sodium
- Supplementaries
and I was unable to reproduce the issue because the cage claims the spectre cannot be caged, due to it not being counted as a small animal.

### Reproduction Steps

1. Spawn spectre
2. Use a cage to capture the spectre
3. Any time the cage is rendered (item frame, hand, inventory, etc) your framerates will drop incredibly low

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v15

### Optifine

No

### Other Mods

TabTPS on the server, if relevant

**Comment by chorbintime** [comment]
Update the Galosphere mod. if issue persists, report it on their github
