### ISSUE TITLE
Crash when roaming the otherside

### ISSUE THREAD

**Issue by AI-nsley69** [LunaPixelStudios/Better-MC#1064]
### Describe the Bug

The game crashes when roaming the other side. Me and my friend who are running v15 are crashing, however, my other friend who is v14.5 has no issues with this.

### Reproduction Steps

1. Go to otherside
2. Potentially see a sculk snapper
3. Game crashes

### Crash Report or Log

https://mclo.gs/deuSFjh

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v15

### Optifine

No

**Comment by chorbintime** [comment]
report to deeper darker github
