### ISSUE TITLE
Server crash from deeper and darker

### ISSUE THREAD

**Issue by AI-nsley69** [LunaPixelStudios/Better-MC#1065]
### Describe the Bug

The server crashes when a player loads near a sculk snapper.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/s83DO9m

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v14.5

### Optifine

No

**Comment by AI-nsley69** [comment]
Wrong label, i forgot to tick the fabric box.

**Comment by AI-nsley69** [comment]
I have opened a [pull request ](https://github.com/KyaniteMods/DeeperAndDarker/pull/140) to fix this issue on the upstream mod.

**Comment by chorbintime** [comment]
known issue with deeper darker mod. they are looking into replacing the mob entirely
