### ISSUE TITLE
cant run start.sh on Linux

### ISSUE THREAD

**Issue by Maltevde** [LunaPixelStudios/Better-MC#1066]
### Describe the Bug

Cant run Start.sh on Linux.
So i just downloaded the .zip from Curseforge via wget. Unzipped it, opend the folder and run the start file via "sh start.sh". This produced the following Error Messages: 

start.sh: 8: start.sh: [[: not found
start.sh: 70: start.sh: Syntax error: redirection unexpected

Downloading and unzipping again didnt help, as well as copying the folder contents to another folder. Tried running as root or another user.

### Operating System

Ubuntu 20.04

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
I need more information, this is very likely user error

**Comment by Maltevde** [comment]
> I need more information, this is very likely user error

Added some more Information

**Comment by Maltevde** [comment]
Managed to resolve the issue by myself. The script does not come with any execute-permissions. Setting these and running with "./start.sh" instead of "sh start.sh" resolves the issue
