### ISSUE TITLE
Game crashes at loading screen 0%

### ISSUE THREAD

**Issue by TDraNix** [LunaPixelStudios/Better-MC#1067]
### Describe the Bug

Every time I try to create a new world or open my world, the game shows a loading screen at 0% and then stays there for a few minutes before closing.

### Reproduction Steps

1. Open mod on curseforge app.
2. Click Play on Minecraft Launcher.
3. Java opens, click on singleplayer.
4. Create a new world, then click Yes on the warning screen.
5. The loading screen gets to 0%, then the app freeze and crashes afterward.

### Screenshots and Videos

https://user-images.githubusercontent.com/120562875/220314277-fa920f7c-d945-44f6-958c-df0094324c25.mp4

![image](https://user-images.githubusercontent.com/120562875/220314335-ace69e28-2f3b-416c-afc8-82de8ee0325a.png)

### Crash Report or Log

https://gist.github.com/TDraNix/d98e392cf97e7b34f7ca5f289ae47ad6

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3

### Optifine

No

**Comment by TDraNix** [comment]
My specs:
[Specs.txt](https://github.com/LunaPixelStudios/Better-MC/files/10792431/Specs.txt)

**Comment by chorbintime** [comment]
Update the modpack to v13
