### ISSUE TITLE
Quests does not react the right way

### ISSUE THREAD

**Issue by unleashbear** [LunaPixelStudios/Better-MC#1069]
### Describe the Bug

I've killed the void many times but the quest has never shown that the mission is complete

### Reproduction Steps

Enter the void and kill the boss
2.
3.
...

### Screenshots and Videos

![Screenshot_20230223_103926](https://user-images.githubusercontent.com/118094250/221086510-1abf71ce-218b-4c07-a838-df8442694725.png)
![Screenshot_20230223_103939](https://user-images.githubusercontent.com/118094250/221086521-e686adfb-d323-4035-9d2e-8c6d536710f4.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
will look into it. you can do /ftbquests editingmode true, right click the quest and complete instantly in the meantime
