### ISSUE TITLE
Server crashes intermittently

### ISSUE THREAD

**Issue by snowjungsungwoo** [LunaPixelStudios/Better-MC#1070]
### Describe the Bug

I don't know why. However, the game crashes when multiple players are playing.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 8

### Minecraft Version

1.19

### Modloader

fabric

### Modpack Version

v15

### Optifine

No

### Other Mods

[crash-2023-02-24_12.56.28-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10820566/crash-2023-02-24_12.56.28-server.txt)

**Comment by chorbintime** [comment]
How did you install the modpack serverside?
