### ISSUE TITLE
Better MC Error 225

### ISSUE THREAD

**Issue by bbstudio03** [LunaPixelStudios/Better-MC#1071]
### Describe the Bug

Game Crashes on boot giving off the error 225. Currently running on the MacBook Pro with M2 chip. Game is fully updated and crashes continue.

### Reproduction Steps

1.Load MC Play Launcher
2.Play and load on mod pack
3.Crashes at the very end of the loading sequence
...

### Operating System

MacOS Ventura

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v59.5

### Optifine

No

**Comment by chorbintime** [comment]
impossible to help without the latest.log or a crash report
