### ISSUE TITLE
Fame affect ran out after killing the void shadow.

### ISSUE THREAD

**Issue by OrdinalTester** [LunaPixelStudios/Better-MC#1073]
### Describe the Bug

After killing the void shadow and getting the fame affect. I go into the overworld and the affect ran out after 20 minutes.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
there is no issue here. the effect is not supposed to be permanent
