### ISSUE TITLE
Void Totem doesn't work when falling into the void.

### ISSUE THREAD

**Issue by OrdinalTester** [LunaPixelStudios/Better-MC#1074]
### Describe the Bug

I put the void totem in my charm slot then died in the void. The totem activated and I got the achievement but it never teleported me to the surface and I died in the void.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
report to the creators of the mod which adds the void totem. check if an update for that mod is available first and see if it fixes it
