### ISSUE TITLE
Portals from mods are breaking my server constantly.

### ISSUE THREAD

**Issue by linkbeta5** [LunaPixelStudios/Better-MC#1075]
### Describe the Bug

Both portals from the Better End and the Deeper and Darker mods have made my server unplayable and had to revert save files to uncorrupt them. I'll explain. The first portal we wanted to use was the Better End's portal to the overworld found in the End. But upon entering the portal two players were unable to connect to the server until the server reverted to a backup. A week later, we attempt to use the Otherside Portal from the Deeper and Darker mod just to have the whole server crash and be unplayable for anyone until again, the server reverted to a backup. Also to be noted, I cannot find a crash log for the 2nd crash.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/sYMdPrdw

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

### Other Mods

N/A

**Comment by chorbintime** [comment]
There is no issue in the log you have posted. Your server is just laggy. I can't help without a proper crash report or client logs that display the clientside timing out issue.

Nobody else has experienced this. It's safe to say it's an issue with your server.

**Comment by prestonhinds** [comment]
> Nobody else has experienced this. It's safe to say it's an issue with your server.

I'm also experiencing this issue on my server, and no, my server isn't laggy.

**Comment by chorbintime** [comment]
There is no issue in the original report. The only thing shown in logs is normal server lag. 

A crash report is almost completely necessary.

**Comment by Sarcasmium** [comment]
> There is no issue in the original report. The only thing shown in logs is normal server lag.
> 
> A crash report is almost completely necessary.

I'm getting the same issue consistently and have to rollback my world when I open the betterend Eternal Portal. 

The game crashed whilst colliding entity with block
Error: java.lang.NoSuchMethodError: 'java.util.Optional org.betterx.bclib.api.v2.poi.BCLPoiType.findClosest(net.minecraft.class_3218, net.minecraft.class_2338, int)'

This is the error code I get and then I can't enter my world without it instantly crashing again.

**Comment by chorbintime** [comment]
Error code does not help.

I need the crash report.

Post the crash report on the mclo.gs website and reply with the link. 

To get the crash report, right click the modpack, Open Folder, and navigate to the Crash Reports folder. Drag the newest one here. If there is no crash reports folder, do the same thing with the latest.log file in the logs folder.

**Comment by Sarcasmium** [comment]
> 

https://mclo.gs/NgjOT29

Had to recreate the bug on a creative world so I wouldn't have to rollback my world again.

**Comment by chorbintime** [comment]
Issue with the BetterEnd eternal ritual. Nothing we can do about it unfortunately. Avoid doing the ritual, you can also try updating betterend & bclib
