### ISSUE TITLE
Can’t find grape seeds for vinery

### ISSUE THREAD

**Issue by MarsDasMee** [LunaPixelStudios/Better-MC#1076]
### Describe the Bug

Looking through the vinery mod, we’re trying to get grapes to make wine, hence we want seeds, but trying to break grass how it’s supposed to get grape seeds, it only gives regular seeds. How else can we get grape seeds for wine? Does biome affect it? Maybe season?

this is BMC 3, version 12

### Reproduction Steps

Break grass (tall and short), no grape seeds drop. Only got grapes from wandering traveler. 

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC 3

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Contact the devs of the Vinery mod. 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod.
