### ISSUE TITLE
[SERVER] Very long shutdown time

### ISSUE THREAD

**Issue by Emosewaj** [LunaPixelStudios/Better-MC#1077]
### Describe the Bug

I'm currently hosting this modpack for a couple of my friends and myself, whenever I shut down the server via the `stop` command, saving the world takes an abnormally high amount of time. As of writing this, I've been running the server on my PC for a solid 15 minutes in its shutdown phase. Monitoring the application on Task Manager shows very high CPU usage but seemingly unchanging memory footprint and 0 disk usage. It appears to usually be stuck either at `Saving chunks for level 'ServerLevel[world]'/minecraft:overworld` or `Saving grave backup data`.

There also appear to be a couple chunks in our world that are corrupted, `Tried to read NBT tag with too high complexity, depth > 512` errors pop up a couple times during startup alone, but usually not during gameplay.

This does not appear to happen on a newly generated world, `Saving grave backup data` still seems to take a couple seconds, and it appears to stay stuck after `Stopped IO worker!` now, instead.

I've tried the same process again with v15 and this same issue appears there as well.

I'm unsure if this issue can be fixed by some update or if I might need to poke around the world's data to fix it up by hand.

Link to a world download: https://emosewaj.eu/private-downloads/world.7z

### Reproduction Steps

1. Set up a fresh server on Fabric v15 (using [CurseForge](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric/files))
2. Unzip the world file into the server directory
3. Launch server (observe NBT Tag errors)
4. Attempt to stop server using `stop`, the server will take an obscenely high amount of time to save and close, if it ever does

### Screenshots and Videos

![](https://i.imgur.com/UlXiKxR.png)

### Crash Report or Log

https://emosewaj.eu/private-downloads/latest.log

### Operating System

Linux Debian 10/Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

fabric 1.19.2 v14.5 and v15

### Optifine

No

**Comment by vaxkun** [comment]
Same here. Exact same behaviour.

Just in case it helps with the troubleshooting, here is what ive found on my NBT data corrupted chunks:
I hade 2 chunks far away each one, one contained our storage system, like 3k free spaces, and the other chunk had another storage system of like 5 little chests.

Both chunks got corrupted and both cant tick, redstone and things doesnt work, but chests do tho.
The only thing in relation between those 2 chunks were the storage system mod.
Also to note, if i enlarge the chest connection a bit, and manage to place the  storage system things outside of that chunk, the mod will take all the chests inside the corrupted world like nothing bad is happening.

Hope this kinda helps! ^^

**Comment by chorbintime** [comment]
With the NBT issue, did you ever delete the entity folder when updating to v15, as instructed in the changelog?

**Comment by vaxkun** [comment]
In my case, we started directly on the v15.

**Comment by vaxkun** [comment]
New info, i were roaming around the world with another player, got killed and instantly got the NBT tag error. Got kicked from the server (And my friend also got kicked even if he didnt died), and when we both logged back, we got spawned on the main world spawn. (Seems like our spawn point got messed up, he lost all his things even without dying, and all the waystones saved were cleared)

**Comment by chorbintime** [comment]
Is your server on offline mode?

How are you hosting the server?

How did you install clientside?

**Comment by vaxkun** [comment]
- Nope, full premium
- On a separate computer, with las java installed and updated, and just running the server (Going smooth btw)
- All people playing, using CurseForge installer

**Comment by SHXRKIIE** [comment]
Could you see if removing the Visual Workbench fixes the issue? Both server and client

**Comment by SHXRKIIE** [comment]
Can you check if v16.5 fixes this issue?
