### ISSUE TITLE
Minecraft server Better MC fabric v15 1.19.2 keeps crashing

### ISSUE THREAD

**Issue by shadytrumpet** [LunaPixelStudios/Better-MC#1078]
### Describe the Bug

This servers being hosted by apex hosting and we looked at the crash reports and it says the issue is with base minecraft trying to generate a mansion something like that we have the coordinates for it too:) the server starts up its fine but when i go that location it crashes:(
[crash-2023-02-25_15.42.45-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10831662/crash-2023-02-25_15.42.45-server.txt)

### Reproduction Steps

1.g Go to the coordinates where the crash reports says there's and issue, therefore causing the server to crash
2. Now that my player is in the position every time I restart the server and join, I load in and the chunks to load then I die
3. Restart, join server, crash, restart then repeat:(
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc 1 v15

### Optifine

No

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/item-banning

the 1.19.2 version

**Comment by chorbintime** [comment]
Change the player's coordinates to elsewhere using the NBTStudio program. Avoid or regenerate those chunks
