### ISSUE TITLE
when I want to join my world game crash

### ISSUE THREAD

**Issue by JAPON1029** [LunaPixelStudios/Better-MC#1079]
### Describe the Bug

today when I was swiming on the ocean something attacks me. then my game crash and I cant join my world because every time my world load game stop working and crash. I checked my crash log and it something about "KrakenEntity"
i dont know what should I do. Please help!

### Reproduction Steps

1.swim 
2.get attacked by "KrakenEntity"
3.and then world stop working
...

### Crash Report or Log

https://files.fm/f/fb4x63d5n

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MC [PLUS] 1.16.5 v41

### Optifine

No

### Other Mods

Rubidium

**Comment by chorbintime** [comment]
right click modpack
open folder
config
badmobs config
search 'kraken'
enable removeAggressively for the one from the Outvoted mod
