### ISSUE TITLE
No Horse Saddle Slot?

### ISSUE THREAD

**Issue by Ebb-and-Flow** [LunaPixelStudios/Better-MC#1081]
### Describe the Bug

I set up a server, got it working with no problems, but when i tamed a horse, there was no slot to put on a saddle it.
I did add the mythic mounts mod and remove the frostiful, but this was an issue before hand.
Also, when i started a single player world, horse saddles worked with no issue, which leads me to believe this is a server config error (couldn't find any configs related to this for the life of me.) Hosting with apex.

### Reproduction Steps

1. tame horse
2. open inventory
3. attempt to put on saddle, but no slot for saddle, only armor

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/90722725/221390708-ccbce783-273f-4164-8446-e873130b9959.png)

### Operating System

win 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

I used Optifine

### Other Mods

mythic mounts

**Comment by chorbintime** [comment]
Is the saddle slot there, just not visually?

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by Ebb-and-Flow** [comment]
Ah, the slot was gone completely. On other modded mounts, there was a
visible slot, but it was non-interactable. Also i just assumed it was
optifine, must be a fabric replacement.
Anyways! I had a friend on the server who had no problems, so I guessed it
had to be some config issue. couldn't find the problem, so i just
reinstalled my server from the ground up. Problem solved.
