### ISSUE TITLE
Game Crashes 5 seconds after startup after invoking a Raid within a village.

### ISSUE THREAD

**Issue by GoblinVageen** [LunaPixelStudios/Better-MC#1082]
### Describe the Bug

So when I had the Bad Omen debuff after killing a scouting party of pillagers I decided to goto the nearest village to try it out. Several raid waves were wiped out without issue and I believe the final wave is causing my game to crash. As they spawned in and got closer my game got extremely laggy further resulting in a crash. I have closed and reopened the game to no avail.

### Reproduction Steps

1.Invoke a raid.
2.Wait to final wave to happen
3.Game Crashes
...

### Crash Report or Log

https://pastebin.com/EudingYf

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 V15

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
run the following command:
/kill @e[type=witch]

you will need cheats enabled
