### ISSUE TITLE
Game Crash on startup

### ISSUE THREAD

**Issue by Moise368** [LunaPixelStudios/Better-MC#1083]
### Describe the Bug

When I try to open the game on the FORGE version, it gives me a loading error for some mods.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/73934891/221858473-bf737a07-653e-4322-ad6a-0e69116250e9.png)

### Crash Report or Log

https://pastebin.com/D18NN15Z

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?

**Comment by Moise368** [comment]
> How did you install the modpack, step by step?

Via CurseForge, but after some digging and "f* around" by replacing the mob with an older version I got it working.

The version of the mod that I used was the 1.19.1+ version, from here: https://www.curseforge.com/minecraft/mc-mods/more-babies/files/4009535

In case that anyone needs this in the future.
