### ISSUE TITLE
Hoofty enchant from Creatures From The Snow is popping up on items that it shouldn't

### ISSUE THREAD

**Issue by Ciyuzuna** [LunaPixelStudios/Better-MC#1085]
Note: I'm on Fabric 1.19.2 v15 , CreaturesFromTheSnow 4.1.0+1.19.2

I'm finding the Hoofty enchant on all sorts of items, on the enchanting table, and getting it as a bonus enchant too.
I've been doing a lot of enchanting and it's very annoying getting a useless enchant that shouldn't be there.
It's only supposed to be on horse armor to make reindeer go faster.

I made a post about it on the Creatures From The Snow mod page anyway.

Is it possible to make a datapack or something to fix this?

**Comment by chorbintime** [comment]
I have contacted the developer of Creatures From the Snow about this issue. If they do not plan on fixing it, we will via resourcepacks.
