### ISSUE TITLE
Brighness problem

### ISSUE THREAD

**Issue by Sonil100l** [LunaPixelStudios/Better-MC#1086]
### Brightness issue

Hi,
just a minor issue, i can't change my brightness, I tried in the game settings, in the option.txt and even by searching if a mod affects it.  Nothing have done a thing and my brightness is locked at "more than max". I can't enjoy shadow anymore XD. The issue is that it only happen in my main world (updated to v60), on other worlds, no light problem.
Can you help me pls ?
Have a good day

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

v60

### Optifine

No

**Comment by chorbintime** [comment]
Try removing the Starlight mod
