### ISSUE TITLE
Naturalist Grizzly Bear Unbreedable

### ISSUE THREAD

**Issue by ItsSunee** [LunaPixelStudios/Better-MC#1087]
### Describe the Bug

Running a server with BetterMC and Simple Voice Chat on it
Player caught 2 grizzly bears from the naturalist mod, yet cant see to breed them.

I did some testing in single player, and some on the server, and cant seem to get them to breed in either. 
I also did a test in single player on JUST bettermc 1.19.2 and still cannot get the bears to breed

![image](https://user-images.githubusercontent.com/126741773/222321633-8baf6e67-ce69-4bd3-8482-b046b23606f3.png)

### Reproduction Steps

1. Catch and house 2 Grizzly bears from the modpack Naturalist
2. Right click on said mobs with food of choice (we used Honeycomb, raw salmon, and raw cod)
3. right clicking mobs will do nothing
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/126741773/222321927-5f147f72-45f6-4222-bbaa-18e4c9987df6.png)
![image](https://user-images.githubusercontent.com/126741773/222321994-96d8c8d8-3be0-43a6-91cb-5da79cb198a1.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC - BMC1 - 1.19.2 FABRIC

### Optifine

No

### Other Mods

Simple Voice Chat
https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat

**Comment by chorbintime** [comment]
Are you sure these mobs are breedable?
