### ISSUE TITLE
Very Small Typo in the Performance Guide

### ISSUE THREAD

**Issue by Banaando** [LunaPixelStudios/Better-MC#1088]
### Describe the Bug

On the performance guide under [RAM Allocation and Java Installation](https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide#ram-allocation-and-java-installation) it says "none of which are better that" which should say than.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/67934979/222325221-9530b5da-cd27-4cca-b559-0585ae4fc577.png)

### Crash Report or Log

Non applicable

### Operating System

Non applicable

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Non applicable

### Optifine

No

**Comment by chorbintime** [comment]
Fixed! Thank you
