### ISSUE TITLE
bastion remnant map

### ISSUE THREAD

**Issue by Revalious** [LunaPixelStudios/Better-MC#1089]
### Describe the Bug

hi um i was playing better mc the fabric version and i was at the aether i picked up the bastion remnant map to delete it because i didnt need it anymore anyways when i picked it up the game crashed after that i started the game again and after that i got the bastion remnant map to my hand to throw it away but when i did that the game crashed again and now i cant play the game because whenever i try the play that world the game instantly crashes

### Reproduction Steps

1.find a bastion remnant map
2.go to aether
3.and just put your mouse on the map and boom game crashes
...

### Crash Report or Log

pastebin is unavailable in my country but i can send u the crash report on discord my nickname is Revalious

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

I used Optifine

**Comment by Revalious** [comment]
oh btw i didnt download manually optifine the pack already had it

**Comment by chorbintime** [comment]
optifine is not in the modpack

I can't help without the crash report. post it on mclo.gs

**Comment by SHXRKIIE** [comment]
leave the aether then get rid of the map

**Comment by Cyakat** [comment]
It is possible to get your world back by editing your playerdata directly in the save file to get rid of the map from your inventory. This is not a permanent fix and may be an issue with Repurposed Structures (I think that is the mod that created the map).

**Comment by Cyakat** [comment]
If you have access to a browser like brave or opera gx, they come with built in VPNs that you may be able use to access pastebin if it is blocked in your country. Also I am willing to guide you into fixing your player data or I can do it for you if given the world file.

**Comment by SHXRKIIE** [comment]
This is an issue with the Aether in general, it causes crashes with any sort of hand map.
