### ISSUE TITLE
Can't Load Cell Maze Chunk

### ISSUE THREAD

**Issue by Gokufix** [LunaPixelStudios/Better-MC#1091]
### Describe the Bug

Playing on the fabric version of BMC1 and went into the bumble zone. I found a compass, and it said it would lead me to the cell maze, so I hoped I would find nice loot there. Instead, when I try to load what I assume is where the cell maze is, I crash.

### Reproduction Steps

1. Go to the Bumble Zone
2. Get close enough to load cell maze chunks
3. Crash

### Screenshots and Videos

First Crash: https://youtu.be/VyrrQ53v6io
Second Crash: https://youtu.be/GsTlxivfmIc
Third Crash: https://youtu.be/KvszlDjSGLA

### Crash Report or Log

https://pastebin.com/mXLsWQ1E

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

I used Optifine

### Other Mods

None only the mods in the mod pack

**Comment by Gokufix** [comment]
I don't know what Optifine is, so I don't know if I used it or not. If its in the mod pack then I probably did

**Comment by Gokufix** [comment]
https://mclo.gs/NMCPIAU

**Comment by chorbintime** [comment]
Add this datapack to config -> paxi -> datapacks
https://cdn.discordapp.com/attachments/841975353655951391/1075894346597023814/bumblezone_no_biome_makeover_moth.zip
