### ISSUE TITLE
Crashes after FML early loading process

### ISSUE THREAD

**Issue by ChinChin000** [LunaPixelStudios/Better-MC#1094]
### Describe the Bug

So, I have been trying to launch Better mc plus (froge), and better mc (forge) any version and none work. I tried putting -Dfml.earlyprogresswindow=false in my JMV args but that only works SOMETIMES, and very rarely... I don't understand what the issue is?? My friend is also having this issue.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Macos

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

Better Mc (FORGE) 1.19.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod.
