### ISSUE TITLE
Crashed when trying to enter that portal in the end

### ISSUE THREAD

**Issue by Gokufix** [LunaPixelStudios/Better-MC#1095]
### Describe the Bug

The portal that requires the eternal crystals, in the end, crashed my game when I touched it.

### Reproduction Steps

1. Open the Portal
2. Touch Portal
3. Crash
the 

### Screenshots and Videos

https://youtu.be/c5VgZv-yezA

### Crash Report or Log

https://mclo.gs/xacMeez

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

### Other Mods

No Other Mods

**Comment by chorbintime** [comment]
dont use the eternal portal. nothing we can do about it.

if you're stuck, change your coordinates via NBTStudio
