### ISSUE TITLE
Java reset - hamachi serwer

### ISSUE THREAD

**Issue by dziku103** [LunaPixelStudios/Better-MC#1096]
### Describe the Bug

When i want to join my friend's server i'm always seeing java error, it is sooo boring. My other friends can easily join, but they use premium mc and i have crystal launcher, but my other friend have premium and have same problem as me.

### Reproduction Steps

1.I joined my friend's hamachi
2.I joined a server
3. I see java restart error every time
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/66262999/222931443-7543896b-6216-4035-ad53-cccfd68f7615.png)

### Crash Report or Log

https://pastebin.com/hTsrYyui

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
We offer absolutely no support for piracy whatsoever.

We offer absolutely no support for Hamachi whatsoever.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
