### ISSUE TITLE
Server crashing on player join.

### ISSUE THREAD

**Issue by ThyCorruptor** [LunaPixelStudios/Better-MC#1098]
### Describe the Bug

When I join the server it crashes. I'm not sure what's causing it. A player on the server said the crashes started occuring when she accessed a storage terminal from Toms Simple Storage. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

[crash-2023-03-05_00.06.26-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10890532/crash-2023-03-05_00.06.26-server.txt)
[crash-2023-03-04_23.53.26-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10890533/crash-2023-03-04_23.53.26-server.txt)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

### Optifine

No

**Comment by chorbintime** [comment]
How did you install the modpack, step by step, clientside?

How did you install the modpack, step by step, serverside?

**Comment by ThyCorruptor** [comment]
> How did you install the modpack, step by step, clientside?
> 
> How did you install the modpack, step by step, serverside?

Client side all players used curseforge and downloaded the modpack through there. 

Server side I used Apexhosting and it was just a modpack listed in a drop down list of available ones.

**Comment by chorbintime** [comment]
try updating the toms simple storage mod client & serverside

**Comment by chorbintime** [comment]
if issue persists, try updating the supplementaries mod

**Comment by ThyCorruptor** [comment]
I'll give that a try, thank you for your help.
