### ISSUE TITLE
[1.16.5 Forge] Suggestions

### ISSUE THREAD

**Issue by Kasualix** [LunaPixelStudios/Better-MC#1100]
1. Remove Saturn as https://github.com/embeddedt/ModernFix/issues/11
2. Remove Krypton Reforged as https://github.com/TeamDeusVult/KryptonReforged/issues/7
3. Remove XL Packets as [RandomPatches includes it](https://github.com/TheRandomLabs/RandomPatches/blob/1.16-forge/src/main/java/com/therandomlabs/randompatches/mixin/packetsizelimits/NettyCompressionDecoderMixin.java)
4. Remove Chunk Saving Fix as ModernFix includes it (and [its bug](https://github.com/embeddedt/ModernFix/issues/10)).
~5.  Remove [Dead Guys Untitled Deep Dark](https://beta.curseforge.com/minecraft/mc-mods/dead-guys-deep-dark) as MCreator REALLY causes trillions of lags when it comes to worldgen related things~

**Comment by chorbintime** [comment]
1. will do
2. i have never seen this happen once across every modpack we've added it to
3. XL packets does a lot of things it technically shouldn't that also prevent bugs from being noticeable by the player
4. will do
5. MCreator is unavoidable in 1.16.5

thank you for the suggestions
