### ISSUE TITLE
"Tried to read NBT tag with too high complexity, depth > 512" error causing world corruption

### ISSUE THREAD

**Issue by Lukrecjaaa** [LunaPixelStudios/Better-MC#1103]
### Describe the Bug

After playing for some time on the server, some chunks get corrupted, things like water, entities and redstone are buggy or don't work on them, and sometimes players disconnect from the server when standing on such a chunk.

The `Tried to read NBT tag with too high complexity, depth > 512` error seems to be related to files in `world/playerdata` and `world/entities`, affected player/chunk files contain lots of nested objects in `BannerStack`. These objects (I think) exclusively contain `minecraft:air`, `minecraft:arrow`, `minecraft:tipped_arrow` and `minecraft:spectral_arrow`. Some of the arrows also had potion effects applied.

After removing bugged NBT tags from affected players/chunks, the world works normally.

I'm not sure if it's a bug with the modpack or Minecraft itself, but it never happened for me on vanilla servers.

### Reproduction Steps

The bug only happens after a couple of days of playing, I wasn't really able to reproduce it in any other way, but:
1. Some players encounter Illusioner (?) mini-boss battles
2. After getting hit with arrows, the error appears (after some time) in the server console

### Screenshots and Videos

![obraz](https://user-images.githubusercontent.com/18142313/224061217-6943d8dc-fdfe-4992-a340-5f8e0bf72a2a.png)

### Crash Report or Log

https://pastebin.com/f555cGU6

### Operating System

Debian Linux server, Windows 10/11 clients

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
Update to v16

**Comment by Lukrecjaaa** [comment]
If anyone encounters the same issue, I made a little program which can fix affected files in `world/playerdata` and `world/entities`: https://github.com/Lukrecjaaa/nbtmcafix

**Comment by chorbintime** [comment]
Thank you! This will help a lot for those with worlds that inherited the issue from v15

**Comment by ftab** [comment]
Indeed, it fixed mine. Thank you so much!

**Comment by whyimsodiao** [comment]
My archive is constantly crashing due to this issue, I am a complete newcomer and I won't be able to use this code. Could you tell me how to use it, which files need to be executed, and which parameters need to be modified? thank you so much！

**Comment by chorbintime** [comment]
Your archive? Are you playing one of the modpacks here, or is it something completely different

**Comment by chorbintime** [comment]
The original issue here was with the Supplementaries mod, on old versions the quivers would get loads of NBT data and cause this to happen

**Comment by whyimsodiao** [comment]
Yes，on modpacks of versions 1.12.2. I don't know which mod causes this trouble. I open my achieve file with NBT studio but I don't know how to determine which mod or which thing in my Inventory. Do I only need to find the most nested things?

**Comment by whatisagoodusername5256** [comment]
> If anyone encounters the same issue, I made a little program which can fix affected files in `world/playerdata` and `world/entities`: https://github.com/Lukrecjaaa/nbtmcafix

Nice, but how exactly do I download and run the program? (Kind of new to github...)

**Comment by ftab** [comment]
> > If anyone encounters the same issue, I made a little program which can fix affected files in `world/playerdata` and `world/entities`: https://github.com/Lukrecjaaa/nbtmcafix
> 
> 
> 
> Nice, but how exactly do I download and run the program? (Kind of new to github...)

In general, a GitHub project will either tell you how to build it, provide builds for you (usually in the Releases page), or it will be obvious how to build it. (Or it's quite frankly a poor project.) You can also usually hunt down instructions on how to use it either in the readme file or in the issues as someone usually runs into something weird without explicit directions.

In this case, the author provided a compiled .jar file in the Releases page that you can run with Java. And there is an issue discussing how to.

https://github.com/Lukrecjaaa/nbtmcafix/issues/1

Hope that helps!

**Comment by whatisagoodusername5256** [comment]
> > > If anyone encounters the same issue, I made a little program which can fix affected files in `world/playerdata` and `world/entities`: https://github.com/Lukrecjaaa/nbtmcafix
> > 
> > 
> > Nice, but how exactly do I download and run the program? (Kind of new to github...)
> 
> In general, a GitHub project will either tell you how to build it, provide builds for you (usually in the Releases page), or it will be obvious how to build it. (Or it's quite frankly a poor project.) You can also usually hunt down instructions on how to use it either in the readme file or in the issues as someone usually runs into something weird without explicit directions.
> 
> In this case, the author provided a compiled .jar file in the Releases page that you can run with Java. And there is an issue discussing how to.
> 
> [Lukrecjaaa/nbtmcafix#1](https://github.com/Lukrecjaaa/nbtmcafix/issues/1)
> 
> Hope that helps!

Cool, thanks!
