### ISSUE TITLE
start.sh linux screen command

### ISSUE THREAD

**Issue by Siffiey** [LunaPixelStudios/Better-MC#1104]
### Describe the Bug

Hello, i want to host a server for me and my friends but when i try to edit in screen to the start.sh file it doesnt seem to work. It opens a separate screen just not with the server commands. Where can i exactly put it so i dont have to have a terminal opened constantly for the server to run.

### Operating System

Debian 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v16

### Optifine

No

**Comment by chorbintime** [comment]
"edit in screen" I'm not sure what you're referring to, sorry

**Comment by Siffiey** [comment]
> 
Screen is a command on Linux that lets me host a server without having to have a terminal opened constantly, since im using a Google Virtual Machine it would be a pain. When i edit the start.sh file putting "screen" at the beginning the server just opens in the main terminal instead of the "screen" in the background so i can close the terminal. I can't have it opened all the time since as I mentioned I'm using Google Cloud Platform.

**Comment by chorbintime** [comment]
Try removing -nogui at the end of the args?
