### ISSUE TITLE
Leaves don't decay, Blocks not updating

### ISSUE THREAD

**Issue by oracle-of-me** [LunaPixelStudios/Better-MC#1105]
### Describe the Bug

We have a problem on our server. Some chunks are 'broken' which means there are no block updates. Water won't flow, sand won't wall etc.
On other chunks we have problems with leaves not decaying, fire not working. So here the chunks seem to be broken as well.

Is there a Command to fix this?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

16.5

### Optifine

No

**Comment by chorbintime** [comment]
What modpack version are you on? We have no 1.16.5 Fabric modpacks.

**Comment by oracle-of-me** [comment]
> What modpack version are you on? We have no 1.16.5 Fabric modpacks.

Obviously I mean 16.5 not 1.16.5.

**Comment by SHXRKIIE** [comment]
It sounds more that your server is lagging, whos your host?
