### ISSUE TITLE
Packet size error with randompatches

### ISSUE THREAD

**Issue by Anikiller4444** [LunaPixelStudios/Better-MC#1107]
### Describe the Bug

I know that RandomPatches fix packet size bug.
But I'm still having this error.
Help pls and thanks

### Reproduction Steps

1. I have it in both sides (client and server)
2. Start server
3. Enter in server, "Loading terrain", but i can't, it kick me
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/110330129/224480059-0441d730-6684-4707-917d-1c603e2890e7.png)
![image](https://user-images.githubusercontent.com/110330129/224480106-e364023f-fb54-4689-a236-68463415c7b7.png)
![image](https://user-images.githubusercontent.com/110330129/224480522-abdd2152-084c-48db-91d4-b5b652131060.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MC 1.16.5 v60.5

### Optifine

No

### Other Mods

Dungeons Mobs
Dungeons Libraries

**Comment by SHXRKIIE** [comment]
Need latest.log of server and what launcher are you using?
