### ISSUE TITLE
Crashing when in nether

### ISSUE THREAD

**Issue by Capybarachillin** [LunaPixelStudios/Better-MC#1108]
### Describe the Bug

At first it was crashing when going through the portal. It would load me into the nether but not load the biomes, everything would be black. I was thinking maybe it was the biome I was loading into it. I moved my nether portal far away and entered and I was actually able to load in. But after about 30 seconds of being in the nether the game crashes.  I always have to task manager it tho because it never fully crashes.

### Reproduction Steps

1. entered nether 
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

BMC v16.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Follow the performance guide. I need the latest.log or crash report.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
