### ISSUE TITLE
after ip change Xaero's world map stopped is blank

### ISSUE THREAD

**Issue by aballoftwine** [LunaPixelStudios/Better-MC#1109]
Im running a server for me and a couple friends and my ISP decided it was time to change my ip address

After the normal googling and found that all I need to do is rename some files in the XaeroWorldMap directory. I couldn't find the directory anywhere and am at a loss. Is there a way to get to the directory of the world map? am I just gonna have to remap everything? what would you suggest I do?

thanks for your time

**Comment by SHXRKIIE** [comment]
I dont really know, your best bet is to ask that question on the Xaeros issues page.
