### ISSUE TITLE
BMC1 Fabric 1.19.2 v16.5 - Server crashes on startup 

### ISSUE THREAD

**Issue by KCharatzas** [LunaPixelStudios/Better-MC#1110]
### Description

Issue started arising when launching the server. Server worked fine for roughly a week, then crashed and issue was present when attempting to relaunch.

### Relevant server logs:

[issue.log](https://github.com/LunaPixelStudios/Better-MC/files/10951021/issue.log)

### Resolution:

Fixed by adding
"mixin.world.temperature_cache=false" to lithium.properties 
as mentioned here:
https://github.com/CaffeineMC/lithium-fabric/issues/452#issuecomment-1463599047

### Disclaimer:

Create (Version create 0.5.0.i-961+1.19.2) has been manually added to the server mod files (as well as client mod files).

**Comment by chorbintime** [comment]
you did not install configs correctly. the shipped lithium config has this disabled.
