### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by mikeypijkie** [LunaPixelStudios/Better-MC#1111]
### Describe the Bug

Since today the Better MC 1.19.2 v15 keeps crashing when starting up
Starting the server will cause the processor to jump to 100% at the same point everytime.(at 22:54:02)
After about 2 minutes of running on 100% the server crashes

i added the crash report

### Reproduction Steps

1.start the "Start.ps1"
2.wait 1 minute for the processor to start working on 100%
3.wait another 2 minutes for the server to crash
...

### Screenshots and Videos

![Screenshot 2023-03-13 000018](https://user-images.githubusercontent.com/2294998/224579248-1cf947f4-80ff-4b1f-ad55-ed862fe8aea7.png)
[crash-2023-03-12_23.58.26-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10952323/crash-2023-03-12_23.58.26-server.txt)

### Operating System

Windows 10

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

Better Minecraft V15

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
You need to allocate more ram. Make sure you're using 64bit java.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by mikeypijkie** [comment]
Hello,

I cant seem to figure out how to allocate more ram to the server and google isnt helping me either.
i can see the following part in the start.ps1:
 "# Xmx and Xms set the maximum and minimum RAM usage, respectively.`n" +
                    "# They can take any number, followed by an M or a G.`n" +
                    "# M means Megabyte, G means Gigabyte.`n" +
                    "# For example, to set the maximum to 3GB: -Xmx3G`n" +
                    "# To set the minimum to 2.5GB: -Xms2500M`n" +
                    "# A good default for a modded server is 4GB.`n" +
                    "# Uncomment the next line to set it.`n" +
                    "# -Xmx4G`n" +
                    "${script:JavaArgs}" | Out-File user_jvm_args.txt -encoding utf8

But i dont know how this works.
i Tried editing the second last line to " -Xmx16G`n" +
but this doesnt change anything about the ram usage when starting adn crashing the server.
![2023-03-13 08_00_20-DESKTOP-DHL2355](https://user-images.githubusercontent.com/2294998/224632675-a034291b-ee90-4329-b676-22553d4cfc64.png)

**Comment by mikeypijkie** [comment]
I found the way to add more ram to the server.
This ticket can be closed
