### ISSUE TITLE
Allocating Ram

### ISSUE THREAD

**Issue by mikeypijkie** [LunaPixelStudios/Better-MC#1112]
Hello,

I cant seem to figure out how to allocate more ram to the server and google isnt helping me either.
i can see the following part in the start.ps1:
 "# Xmx and Xms set the maximum and minimum RAM usage, respectively.`n" +
                    "# They can take any number, followed by an M or a G.`n" +
                    "# M means Megabyte, G means Gigabyte.`n" +
                    "# For example, to set the maximum to 3GB: -Xmx3G`n" +
                    "# To set the minimum to 2.5GB: -Xms2500M`n" +
                    "# A good default for a modded server is 4GB.`n" +
                    "# Uncomment the next line to set it.`n" +
                    "# -Xmx4G`n" +
                    "${script:JavaArgs}" | Out-File user_jvm_args.txt -encoding utf8

But i dont know how this works.
i Tried editing the second last line to " -Xmx16G`n" +
but this doesnt change anything about the ram usage when starting adn crashing the server.
![2023-03-13 08_00_20-DESKTOP-DHL2355](https://user-images.githubusercontent.com/2294998/224632675-a034291b-ee90-4329-b676-22553d4cfc64.png)

_Originally posted by @mikeypijkie in https://github.com/LunaPixelStudios/Better-MC/issues/1111#issuecomment-1465627716_

**Comment by chorbintime** [comment]
1) Double click the start.ps1 instead of opening with Powershell
2)  On line 16, where it says $JavaArgs, you can add your args there.
 -Xmx8G will set your maximum memory usage to 8 gigabytes.
