### ISSUE TITLE
Exit code -1 Crystal Portal crashing

### ISSUE THREAD

**Issue by 1mp3rf3ctC3ll** [LunaPixelStudios/Better-MC#1113]
### Describe the Bug

Game always crashes when entering a Crystal Portal in The End

### Reproduction Steps

1. Teleport to The End
2. Head toward Crystal Portal in the dimension
3. When I hit the port, game crashes 
...

### Crash Report or Log

-1

### Operating System

Windows 10

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

Better MC [FABRIC] 1.19.2 v15

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Update to v16.5. We offer no support for old versions.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
