### ISSUE TITLE
Better MC Issues with server crashing

### ISSUE THREAD

**Issue by SpiceyLlama12** [LunaPixelStudios/Better-MC#1114]
Hello all, 

I have had persistent issues with this pack either leaking memory or filling memory up. 

I have been in constant contact with Pebblehost to trouble shoot and was directed to the modpack creators. 

To give some background I run a server of 8 users on 8GB of DDR4 RAM with Better MC [FABRIC] - BMC1 1.19.2. v15

I have received the below error  and would appreciate any assistance - thank you. 

-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraft.class_1297.method_5647(class_1297.java:1719)
Mixins in Stacktrace: None found

-- Entity being saved --
Details:
    Entity Type: minecraft:squid (net.minecraft.class_1477)
    Entity ID: 764
    Entity Name: Squid
    Entity's Exact location: 8387.23, 57.83, -8336.27
    Entity's Block location: World: (8387,57,-8337), Section: (at 3,9,15 in 524,3,-522; chunk contains blocks 8384,-64,-8352 to 8399,319,-8337), Region: (16,-17; contains chunks 512,-544 to 543,-513, blocks 8192,-64,-8704 to 8703,319,-8193)
    Entity's Momentum: -0.01, -0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: null

**Comment by chorbintime** [comment]
run the command /kill @e[type=squid]
