### ISSUE TITLE
enchantments on tools 

### ISSUE THREAD

**Issue by Chippyben** [LunaPixelStudios/Better-MC#1116]
### Describe the Bug

when i try and add enchantment books on my tools it wont let me, i have a lot of books and want to use them but it isn't letting me 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 v13

### Optifine

No

**Comment by chorbintime** [comment]
send a screenshot

**Comment by Chippyben** [comment]
So can it get resolved?

Cheers Ben

**Comment by chorbintime** [comment]
I asked you to send a screenshot and you ignored me lol

**Comment by Chippyben** [comment]
I emailed them on Friday didn’t you get it?

**Comment by chorbintime** [comment]
i did not

**Comment by Chippyben** [comment]
---------- Forwarded message ---------
From: chippyArmy Ben ***@***.***>
Date: Sun, 19 Mar 2023 at 3:16 pm
Subject: Re: [LunaPixelStudios/Better-MC] enchantments on tools (Issue
#1116)
To: LunaPixelStudios/Better-MC <
***@***.***>

**Comment by Chippyben** [comment]
Just sent again

**Comment by chorbintime** [comment]
i still dont see a screenshot
