### ISSUE TITLE
Game crash in Bumblezone

### ISSUE THREAD

**Issue by MortemX** [LunaPixelStudios/Better-MC#1117]
### Describe the Bug

The compass directs me to a place and when I go towards the place shown by the compass, the game crashes

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
update the modpack


You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
