### ISSUE TITLE
Unable to mine 

### ISSUE THREAD

**Issue by Henzilla728** [LunaPixelStudios/Better-MC#1120]
### Describe the Bug

Cannot mine any pickaxe mined objects There is also usually a preview in the top left displaying which tool to mine with which has disappeared and once the stone or any pickaxe breakable block is mined it does not drop but disappears as if I am mining by hand.

Only happening with pickaxe breakable blocks, things like wood or dirt is completely fine 

![image_2023-03-18_151036385](https://user-images.githubusercontent.com/127796344/226114321-fe387a7a-8442-4a39-b682-7cf26f8b2142.png)

### Reproduction Steps

1. Get pickaxe to mine stone
2. Attempt to mine stone 
3. Stone breaks at hand speed and does not drop anything
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FABRIC] 1.19.2 v16.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
You appear to have mining fatigue.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
