### ISSUE TITLE
Nether Crash

### ISSUE THREAD

**Issue by gamer3772** [LunaPixelStudios/Better-MC#1123]
### Describe the Bug

When entering the nether the game will lag immensely the crash or just straight out crash. I have tried in a normal world and a superflat world to test out if the size of the structures and biomes were the cause and what happened was that in a normal world once i load into the nether nothing will render and i will continue falling for a long time and the game will eventually crash, then in a superflat it will render easily but as soon as i move a few blocks the game will lag and basically freeze and then finally crash.

### Reproduction Steps

1. Enter Nether
2. Nether Tries to Load
3.  Game Crashes
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

16.5

### Optifine

No

### Other Mods

Appleskin

**Comment by chorbintime** [comment]
need logs

**Comment by SHXRKIIE** [comment]
No response
