### ISSUE TITLE
it dont let me join this server that uses the modpack

### ISSUE THREAD

**Issue by Darkismodding-2872** [LunaPixelStudios/Better-MC#1125]
i downloaded the modpack on curseforge because i wanted to join this server with some of my friends in it and it just does this
![image](https://user-images.githubusercontent.com/121525212/226495044-5756b34f-6ed7-49f4-86d4-ff67715dce96.png)
what does this mean

**Comment by chorbintime** [comment]
You did not install the modpack correctly clientside. 

You need to use a modded launcher, such as ATLauncher, to both install and launch the modpack.
