### ISSUE TITLE
Game Crashes Within Seconds of Loading

### ISSUE THREAD

**Issue by Cottoncandiedskies19** [LunaPixelStudios/Better-MC#1126]
### Describe the Bug

Once I load into the world, it takes a couple seconds to load, and then it gets super laggy, freezes up, and then crashes closing down the app. The error code I received was as follows: -1073741819

I have tried opening, closing, restarting everything but it hasn't worked.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc1

### Optifine

No

**Comment by chorbintime** [comment]
I need the crash report from the crash reports folder to help you. An exit code is never enough.

**Comment by SHXRKIIE** [comment]
Need the crash report
