### ISSUE TITLE
I can't connect my Better MC server

### ISSUE THREAD

**Issue by 3ERKC4N** [LunaPixelStudios/Better-MC#1127]
### Describe the Bug

Yesterday I opened a Better MC server with my friend and we played. Today I try to connect the server and I take this error*(Photo 1)

I looked up server panel and I saw this *(photo 2)

Please some one help me :(

Sorry for my English. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Photo 1](https://user-images.githubusercontent.com/128613306/226942628-286d1c9c-5626-4447-9130-20aef9fc8223.jpeg)
![Photo 2](https://user-images.githubusercontent.com/128613306/226942663-fb0ac4fc-c68d-426a-af42-cd6d4eb86b8f.png)

### Operating System

Windows 11 (in my client pc)

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v16.5

### Optifine

No

### Other Mods

These mods added by me but just server side:
ferritecore
lithium
phospor

**Comment by goteusz-maszyk** [comment]
You do not have No Chat Reports, and this server is configured to require it on client!
