### ISSUE TITLE
FPS drop

### ISSUE THREAD

**Issue by shaybus3** [LunaPixelStudios/Better-MC#1129]
### Describe the Bug

Hi, I made a mp server for my friends and two of them have big fps drops. They have like 40-60 fps and once for maybe 3 sec it drops to 2 fps for couple of seconds and then again works fine for a while. They had set graphic options to full minimal. They have 6gb RAM set for minecraft. Where problem can be and is it possible to repair that?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3

### Optifine

No

**Comment by SHXRKIIE** [comment]
They can try the performance guide in the main menu, other than that if you can provide their pc specs then we can see if thats the issue. If they only have 8gb for the whole that most likely is the issue.
