### ISSUE TITLE
Zoomify crashes minecraft when opening config

### ISSUE THREAD

**Issue by goteusz-maszyk** [LunaPixelStudios/Better-MC#1132]
### Describe the Bug

BetterMC (v16.5) crashes, when trying to open zoomify config
	
https://github.com/isXander/Zoomify/issues/126

### Reproduction Steps

1. /zoomify
2. good luck with playing after it
3.
...

### Crash Report or Log

https://mclo.gs/0nNBfgv

### Operating System

Win 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v16.5 BMC1

### Optifine

No

**Comment by SHXRKIIE** [comment]
Thanks, we will wait for them to update with a fix, in the meantime you can edit the config from the modpack folder instead.
