### ISSUE TITLE
Totem Of Undying

### ISSUE THREAD

**Issue by BlueScreenek** [LunaPixelStudios/Better-MC#1133]
![obraz_2023-03-24_164830465](https://user-images.githubusercontent.com/128813698/227574787-d7bcfaf8-d0f5-44c9-bb56-96843d9d3b12.png)
### Describe the Bug

While i die with the totem of undying items from slot 1 and my armor Dissapear? Is it a bug or is it an added thing, plz help ! <3

### Reproduction Steps

1.Equip Totem Of Undying
2.Get your armor on and get some items in first slot
3.Try to die and see if you have your items
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v16.5zip

### Optifine

No

**Comment by SHXRKIIE** [comment]
I am unable to reproduce this, are you on a server? did you modify the modpack? what launcher are you using?

**Comment by BlueScreenek** [comment]
> I am unable to reproduce this, are you on a server? did you modify the modpack? what launcher are you using?

Yes we are playing on the server, no we didnt modified the modpack, im using a normal minecraft launcher

**Comment by chorbintime** [comment]
You need to use a modded launcher such as Curseforge Launcher or ATLauncher to install and play modpacks,

**Comment by BlueScreenek** [comment]
> You need to use a modded launcher such as Curseforge Launcher or ATLauncher to install and play modpacks,

I mean we indeed use a curseforge, but we didnt added any modpacks to our server, only better mc is downloaded.

**Comment by SHXRKIIE** [comment]
Still unable to reproduce this issue on a server too, can you provide a video?

**Comment by KernfusionGit** [comment]
Had a similar bug happening on my server.
1.19.2

Having the charm of keeping from twilight forest and the totem of undying from the upgraded netherite mod (for example the witherite totem) equipped in the charm slots will result in losing your hand item + your armor when your totem activates.

**Comment by chorbintime** [comment]
Make sure you are on the latest version of the modpack
