### ISSUE TITLE
Slabfish Dupe

### ISSUE THREAD

**Issue by PoorPauda** [LunaPixelStudios/Better-MC#1134]
### Describe the Bug

Whenever you tame a slabfish and equip a chest onto it, if you place items in the chest, and then shift right click the slabfish to pick it up, all the items in the chest drop, if you place the slabfish beside the dropped items, it will auto pick them up. Once you look into the chest of the slabfish, there are twice the amount you put in there.

### Reproduction Steps

1. Tame a slabfish
2. Give it a chest with and add items into it
3. Pick up the slabfish, and put it down again.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Report to the developers of the mod that adds the Slabfish, if the mod is still maintained.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod.
