### ISSUE TITLE
disenchant option

### ISSUE THREAD

**Issue by coldissimo** [LunaPixelStudios/Better-MC#1136]
### Describe the Bug

i cant use the disenchant option at the grindstone, it let me put the weapon and the book but a X appears. i'm using 1.18.2 v19.

### Reproduction Steps

1.put the equipment
2.then the book
3. nothing happens
...

### Screenshots and Videos

https://imgur.com/4mUJewZ

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v19

### Optifine

No

**Comment by chorbintime** [comment]
this isn't a bug, this modpack doesnt have disenchanting
