### ISSUE TITLE
Minecraft Crashes when pausing game

### ISSUE THREAD

**Issue by Wolgwang** [LunaPixelStudios/Better-MC#1137]
### Describe the Bug

80% of the time i pause the game to look at options it freezes completely and i have to open task manager to close it, i'm using MultiMC and even the MultiMC App freezes aswell and i have to force the shutdown of the app, i have tried allocating more ram, deactivating rubidium, and also decreasing the loaded chunks but to no avail, the weird thing is that playing the game runs pretty well, the only time i had a problem was once that i threw and egg and it froze the same way when it landed, but aside from that the modpack runs well

### Reproduction Steps

1.Open World
2.Press Esc
3.Crash lol
...

### Screenshots and Videos

[Server thread/WARN] [net.minecraft.world.level.entity.PersistentEntitySectionManager/]: UUID of added entity already exists: FallingBlockEntity['Falling Block'/42494, l='ServerLevel[New World]', x=-446.50, y=77.00, z=-191.50]
[Worker-Main3/ERROR] [net.minecraft.world.entity.decoration.HangingEntity/]: Hanging entity at invalid position: BlockPos{x=255, y=7, z=-24}
[Worker-Main3/ERROR] [net.minecraft.world.entity.decoration.HangingEntity/]: Hanging entity at invalid position: BlockPos{x=259, y=6, z=-25

This seems to be the only thing the latest log has when the game freezes

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

[FORGE] 1.19.2 v13

### Optifine

No

**Comment by Wolgwang** [comment]
It seems this exact same thing happens also with a clean install in ATLauncher

**Comment by Wolgwang** [comment]
It seems this also occurs with a Clean install on the ATLauncher

**Comment by chorbintime** [comment]
Follow the performance guide linked on the main menu and send the full log file if the issue persists.
