### ISSUE TITLE
"The game crashed whilst exception in server tick loop Error: java.lang.RuntimeException: Server, expired, default and wilderness claim configs must load properly! Check the game logs for errors."

### ISSUE THREAD

**Issue by sklades** [LunaPixelStudios/Better-MC#1138]
### Describe the Bug

I play better MC with my friend on essential mod and everything worked fine until I entered the End. My game crashed and when I join my world it keeps crashing with this info: "The game crashed whilst exception in server tick loop
Error: java.lang.RuntimeException: Server, expired, default and wilderness claim configs must load properly! Check the game logs for errors.
-1" and we don't know how to fix this.

### Reproduction Steps

1. launch minecraft
2. joing to the world
3. if world load game crash 
...

### Crash Report or Log

https://pastebin.com/Z77rdsNC
### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v16.5 BMC1

### Optifine

I used Optifine

### Other Mods

essential mod. Creeper overhaul, resourcefulconfig

**Comment by chorbintime** [comment]
The Essential mod does not work. We can not and never will offer support for it.

The only two approved ways of hosting a server are by paying for a Bisect server or hosting a server for free using the serverpack that is on the modpack's Curseforge page and reading the readme file.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by sklades** [comment]
> The Essential mod does not work. We can not and never will offer support for it.
> 
> The only two approved ways of hosting a server are by paying for a Bisect server or hosting a server for free using the serverpack that is on the modpack's Curseforge page and reading the readme file.
> 
> You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

but there is a way to get back the world?

**Comment by chorbintime** [comment]
You can try copying the contents of your world from within the saves folder.

**Comment by sklades** [comment]
What should I copy?

**Comment by sklades** [comment]
> You can try copying the contents of your world from within the saves folder.
what i should copy?

**Comment by chorbintime** [comment]
Everything from inside your current world save's folder into the world folder of the actual server

**Comment by sklades** [comment]
on what server?

**Comment by chorbintime** [comment]
if the issue persists on an actual server hosted either on Bisect or on your pc then you're out of luck. once again, this is explicitly an issue with the essential mod.
