### ISSUE TITLE
Frost Walker issue 

### ISSUE THREAD

**Issue by Girlgamerb** [LunaPixelStudios/Better-MC#1140]
### Describe the Bug

Im unable to add frost walker to any boots at all iv got the book and tried on several pairs and it’s just won’t go on but if I go onto creative it goes on just fine 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Bmc v16.5

### Optifine

No

**Comment by chorbintime** [comment]
Send a screenshot of the boots

**Comment by Girlgamerb** [comment]
> Send a screenshot of the boots

![21932B84-1B1D-49F0-85BA-054C7A5E4C71](https://user-images.githubusercontent.com/129082134/228356384-6ea82144-ed44-48d3-ad84-69cf637a6f0f.jpeg)

**Comment by chorbintime** [comment]
Aerial Affinity conflicts with Frost Walking
