### ISSUE TITLE
Can't install OptiFine 1.19.2

### ISSUE THREAD

**Issue by TomiKovacs** [LunaPixelStudios/Better-MC#1141]
### Describe the Bug

I use ATLauncher, which was recommended in the Performance Guide. When I start the game, the launcher disappears, then just reappears again. The modpack can't start with optifine in the mods folder. 

### Reproduction Steps

1. Download and copy Optifine to the mods folder
2. Click Optifine and choose extract
3. Delete installer nad leave MOD file in mods folder
4. Try to start game

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 v13 [Forge]

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
This is not a bug. The modpack's Curseforge page specifically says to not install Optifine.

All modern modpacks, unless specified otherwise, are completely incompatible with Optifine.

**Comment by chorbintime** [comment]
No. As I already said, all modern modpacks, unless specified otherwise, are completely incompatible with Optifine.

We use several Optifine replacement mods across modpacks, including in 1.16.5, that allow for things like connected textures without Optifine.

**Comment by TomiKovacs** [comment]
Yea, I did some more digging and the playthrough I saw was probably the Fabric version.
