### ISSUE TITLE
some particles turn black and show through walls when picking up an item

### ISSUE THREAD

**Issue by patsayshi1** [LunaPixelStudios/Better-MC#1143]
### Describe the Bug

As the title says, when I pick up a block some particles rendered are turned black and will show through all walls for around half a second. Particles from torches, fire, and leaves falling from trees do not have issues. The particles from logs being burned to ash/ash falling shows. 
Enabling a shader pack makes this go away.

addition:particles from entities splashing in water show too.

### Screenshots and Videos

what is seen everytime i pcik anything up
![pickupblock](https://user-images.githubusercontent.com/129245741/228418228-9298548b-e8be-4205-98b9-1bb31ce00be0.png)
example of ash showing through wall
![ashshowing](https://user-images.githubusercontent.com/129245741/228418248-941b41e9-8e52-4323-8319-85160b41a5e4.png)
new addition of entity water particles showing
![waterparticles](https://user-images.githubusercontent.com/129245741/228620132-bfc2a6ae-5fe4-4f1e-9a0d-42ae9c5d455c.png)

### Operating System

Windows 11 (windows 10 too, friend's game showed too)

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 v13   -    2/20/2023 curseforge version 43.2.4

### Optifine

No

### Other Mods
Default mods for BMC3

**Comment by SHXRKIIE** [comment]
This is due to Oculus and Rubidium. I dont believe there is a fix for it, you can try updating the mod if it has updates.

**Comment by patsayshi1** [comment]
after some testing, removing oculus fixes this issue.

**Comment by MoRoN222** [comment]
> after some testing, it seems that removing oculus fixes this issue.

but that's the only way I can use shaders beside optifine which destroys rendering of a specific mod (which is why I use oculus/rubidium instead) isn't there another way of preventing that

**Comment by LaidBackSloth** [comment]
I made a fix for it, you can download it here https://www.curseforge.com/minecraft/mc-mods/oculus-particle-fix and put it into the mods folder or when playing through the CurseForge Launcher just search for Oculus Particle Fix and add that
