### ISSUE TITLE
Vinery Kitchen Sink Makes X-Ray Glitch

### ISSUE THREAD

**Issue by Train-Tracks13** [LunaPixelStudios/Better-MC#1145]
### Describe the Bug

Any time I place the kitchen sink it makes an X-Ray glitch under the lip of the sink.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![huge_2023-03-30_06 07 41](https://user-images.githubusercontent.com/129331050/228656318-7205b798-a071-4af1-8587-08ac1a1be61d.png)
![huge_2023-03-30_06 10 30](https://user-images.githubusercontent.com/129331050/228656381-2b55426d-0b0c-4bb5-9fde-57e0db09a484.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v16.5.zip

### Optifine

No

### Other Mods

Better Third Person (BetterThirdPerson-Fabric-1.19-1.9.0.jar)

**Comment by SHXRKIIE** [comment]
Thanks will fix it in next version
