### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Crabb06** [LunaPixelStudios/Better-MC#1147]
### Describe the Bug

Error: Could not find or load main class @user_jvm_args.txt

### Reproduction Steps

1.
2.
3.
...

### Operating System

Win 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
That error can mean lots of things, you are either out of memory ram or you dont have the correct java version
