### ISSUE TITLE
i lost my gravestone when i died 

### ISSUE THREAD

**Issue by gokublack360** [LunaPixelStudios/Better-MC#1149]
### Describe the Bug

Last night me and my friends were in a middle of a boss fight and when we were about to beat it i died and as soon as i respawned they beat the boss it was the hydra dragon that we were fighting i went to where i died and my gravestone was no longer there and the floor look liked it resetted. 

### Reproduction Steps

1. fighting the hydra boss fight
2. dying before you beat it
3. spawning back to see that my gravestone is gone alongside my stuff
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v16.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Update to v17.

Report to the developers of whichever mod adds Hydra's, if the issue persists.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
