### ISSUE TITLE
No Achievement from killing void shadow

### ISSUE THREAD

**Issue by SSHadow2000** [LunaPixelStudios/Better-MC#1150]
### Describe the Bug

I killed the void shadow, opened the chest, got the Source Stone, but did not get the achievement. My text only says "void shadow will respawn in 34660 ticks"

### Reproduction Steps

1. 
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC v16.5

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
Did you kill it using a sword, and did you get the final hit?

**Comment by SSHadow2000** [comment]
No I did not I killed it using the projectiles and crystals. To be more specific, one of the little minions fired a projectile that hit the crystal that deals damage, and that was the final hit. I was unable to ever melee it, even when it was in it's grey form and spinning on the platform. I went into editing mode to give myself the rewards as this happened the second time I beat it as well.

**Comment by chorbintime** [comment]
FTBQuests is likely not registering those projectiles as you killing it, ill set it to an achievement if possible in the next update
