### ISSUE TITLE
CANNOT ATTACK 

### ISSUE THREAD

**Issue by FARRQU** [LunaPixelStudios/Better-MC#1151]
### Describe the Bug

the problem is Whether I’m using a controller or mouse and keyboard it’s the same thing. I can break/place blocks but can’t attack mobs, whether it’s hostile or friendly like cows or sheep. It just doesn’t register and it won’t even swing in the air unless I’m looking at a block.
it was fine for a few days I was playing smooth until this, I think it started when I left my pc to fall asleep but not 100%, I tried resetting mc that didn't work, tried reset pc, tried to download a copy but not sure if the files ere the exact same coz copy but that still didn't work. anyway just need really help searched for hours on the internet. 

THIS IS THE VERSION IM USING >>>> better mc [forge] 1.19.2 v13

### Reproduction Steps

1.
2.
3.
...

### Operating System

WINDOWS 10 HOME

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

 better mc [forge] 1.19.2 v13

### Optifine

No

### Other Mods

vc_gliders-1.0.2-forge.jar AND SkyVillages-1.0.1-1.19-forge-release.jar

**Comment by chorbintime** [comment]
make a backup of your world and remove the two mods you added

how did you install the modpack clientside?

are you on a server?
