### ISSUE TITLE
Waystone Data Missing After v17 upgrade

### ISSUE THREAD

**Issue by RichardZimmerman** [LunaPixelStudios/Better-MC#1152]
### Describe the Bug

After upgrading from v16.5 to v17, users have lost waystone data. Users are unable to list and travel to previously discovered waystones in the waystone UI.

Note: the v17 fw_waystones.dat file seems to rebuild itself on the next server start even if I copy over the v16.5 file [that contains all the necessary waystone data].

I'm fairly new with the Waystones mod, so maybe there's an upgrade process/convention I'm unfamiliar with. 
The waystones were not global in my v16.5 instance.

### Reproduction Steps

1. Create a world in v16.5 BetterMC 1.19.2 [Fabric].
2. Have multiple players connect to the new world and create waystones.
3. Upgrade the server from v16.5 to v17, copying the contents of the world folder to preserve world/instance data to the new v17 instance.
4. Confirm the contents of the fw_waystones.dat file to verify the names of all previously created waystones (step 2) are in the file.
5. Launch the server
6. Test whether players still have waystone data from before upgrade ->>> Error, waystone data is not preserved
7. Confirm that the contents of fw_waystones.dat have been overwritten.
...

### Operating System

Debian 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v17

### Optifine

No

**Comment by chorbintime** [comment]
v17 did not update anything related to the Waystones mod. This is likely an issue on your side somehow.

**Comment by RichardZimmerman** [comment]
Thanks anyway! We'll force a fix.
