### ISSUE TITLE
Cant find any dragon eggs

### ISSUE THREAD

**Issue by SoggyUndies98** [LunaPixelStudios/Better-MC#1154]
### Describe the Bug

Ive been trying to find a dragon egg forever, im on Better MC3 version 1.19.2 v13. Wondering if there are even dragons in this mod pack, it shows dragon mounts legacy is on the mod pack but ive litteraly tried everything to find a dragon. any ideas to help with this? 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v13

### Optifine

No

### Other Mods

no

**Comment by chorbintime** [comment]
Its bugged. Report to the Dragons Mount Legacy devs.
