### ISSUE TITLE
Add Lootr

### ISSUE THREAD

**Issue by Wilson-Cal** [LunaPixelStudios/Better-MC#1155]
Any particular reason why the modpack doesn't have Lootr? Would love to have it included for instanced loot in multiplayer.

**Comment by chorbintime** [comment]
Lootr is not balanced. A lot of mods, such as When Dungeons Arise, add large structures, such as Keep Kayra, with tons of mobs and really good loot. 

letting this loot regenerate would let new players get OP way too quickly. 

theres also the fact that, every single time someone enters a structure, the structure will get easier to fight through for the next person. every block broken or torch placed means the next person has one less thing to deal with, making the structure's loot even more obtainable without consequence or challenge
