### ISSUE TITLE
Vinery - Grapevine Pot Not Working

### ISSUE THREAD

**Issue by Yosthj** [LunaPixelStudios/Better-MC#1156]
### Describe the Bug

There is a problem with the Vinery mod. I'm unable to make wine. I add grapes to the grapevine pot, as instructed, but unable to get the grape juice out. Instructions say to use an empty wine bottle but nothing happens. When I break the pot my grape juice disappears. I spent days creating a vineyard only to find out the mod doesn't work. :(
BTW - I just noticed this BetterMC modpack has an old version of vinery on it. Is there a way to fix this?

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v16.5.zip

### Optifine

I used Optifine

**Comment by Yosthj** [comment]
I updated the better minecraft modpack to the latest version and the grapevine pot still does not work. How do you get the grape juice out of the pot?

**Comment by chorbintime** [comment]
You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
 
 Report to or ask the Vinery dev.

**Comment by PandaGamersHDNL** [comment]
to be fair i have the same issue when there aren't enough grapes in the grapevine pot. then the juice is just stuck and you can't add additional grapes

**Comment by chorbintime** [comment]
> to be fair i have the same issue when there aren't enough grapes in the grapevine pot. then the juice is just stuck and you can't add additional grapes

Report it to the developer of Vinery.

**Comment by gxldCptRick** [comment]
Have you tried stomping on the grapes in the bucket?
