### ISSUE TITLE
Paradise Lost mod

### ISSUE THREAD

**Issue by JayBehindTheSlaughter** [LunaPixelStudios/Better-MC#1157]
### Describe the Bug

Me and my friend have a multiplayer server using Alternos. We've had an issue for all 1.19.2 versions of the modpack where Paradise Lost is completely broken. It only has one biome and two, maybe three mobs. Nothing else spawns and i've attempted to remove the mod and redownload it myself to no avail. I haven't seen anything online and am just at a lost on what to do.

### Reproduction Steps

1. Make a paradise lost portal, nether portal but glowstone and a bucket of water instead of obsidian and flint n steel
2. go into it ig lol
3.
...

### Crash Report or Log

no log

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Newest version currently, but as stated every 1.19.2 update has had this issue

### Optifine

No

### Other Mods

Nope. And when I tried to fix the pack I just reset it and went back to the unedited version.

**Comment by JayBehindTheSlaughter** [comment]
Paradise Lost is broken on normal single player as well. Checked with the natures compass, the other biomes don't exist.

**Comment by chorbintime** [comment]
"one biome and two, maybe three mobs" is all the dimension actually has lol. not a glitch

please do not use aternos, it's a buggy mess. create a selfhosted server using the serverpack from the curseforge page and read the readme or buy a bisect server for max stability
