### ISSUE TITLE
Redstone does not work if offline forceloaded

### ISSUE THREAD

**Issue by MvandeKamp** [LunaPixelStudios/Better-MC#1158]
### Describe the Bug

It is fixed in the new version of the open parties and claims mod:

here is the issue: https://github.com/thexaero/open-parties-and-claims/issues/235

Please update the mod to the newer version:
https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims/files/4462906

### Reproduction Steps

Full explanation on the issue mentioned above.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC 1.19.2 Forge v13

### Optifine

No

**Comment by chorbintime** [comment]
it will be updated soon, apologies for any inconvenience
