### ISSUE TITLE
Missing Recipe in 1.16.5 BCM1 v60.5

### ISSUE THREAD

**Issue by Fox-in-the-Box** [LunaPixelStudios/Better-MC#1160]
### Describe the Bug

It seems that some items may show up in JEI with recipes I cannot craft. Specifically, I have been unable to make vertical deep slate slabs on the crafting table or on the stonecutter using recipes shown in JEI. This is on a server.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/130380320/230924763-6c117e69-9b87-4a30-8846-865763853840.png)
![image](https://user-images.githubusercontent.com/130380320/230924915-f1b9a477-e512-4367-b8fb-8bf3c183a2cb.png)
![image](https://user-images.githubusercontent.com/130380320/230925036-8929d392-2037-4c5f-a1cf-403dd8cc9d1b.png)
![image](https://user-images.githubusercontent.com/130380320/230925130-6a33b9b6-a9e4-49f3-8a4a-2acb0985540c.png)
![image](https://user-images.githubusercontent.com/130380320/230925303-a02afc01-48e2-4f13-8b82-545b0fbf5b59.png)

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

60.5

### Optifine

No

### Other Mods

There are no additional mods on the server.

**Comment by chorbintime** [comment]
open the config for that mod & re-enable the vertical slabs
