### ISSUE TITLE
need help on this icone

### ISSUE THREAD

**Issue by djoblou** [LunaPixelStudios/Better-MC#1161]
### Describe the Bug

i have this on my screen and now i can't put a block in a good position
can you help me 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Capture d'écran 2023-04-10 221734](https://user-images.githubusercontent.com/130403936/230990332-97c40f19-e176-447d-a183-138a0edddf12.png)

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

better minecraft 

### Optifine

No

**Comment by chorbintime** [comment]
press K
