### ISSUE TITLE
Twilight Forest crashes the game

### ISSUE THREAD

**Issue by colbyw343** [LunaPixelStudios/Better-MC#1162]
### Describe the Bug

My game keeps crashing when exploring the Twilight Forest. It has seemingly crashed several times in the same spot, and looking at the crash logs it looks like a world generation issue. Not sure what to do about this.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/C3dbfiSd

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

16.5

### Optifine

No

**Comment by chorbintime** [comment]
update to v17

nothing you can do anyway. its not fixed in v17 but you really should update anyway. its a twilight forest issue that they're aware of & have already fixed. they just havent pushed the fix to Fabric
