### ISSUE TITLE
Otherside Server Crash

### ISSUE THREAD

**Issue by Zeolous** [LunaPixelStudios/Better-MC#1163]
### Describe the Bug

I entered the otherside dimension for the first time to see what it is all about. I then used an enchanted netherite chestplate to tame one of the shulk snappers as they will give you enchanted books. After taming it the server crashed after a few seconds, also completely crashing my game too. Errors say its something to with the otherside and the crash happened after the taming. Relaunched the server and it crased when I joined again and I cant kill my tamed snapper. I dont want to back log my server :(. Don't know if there is a way out of this. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

[11-04-2023 01:04:10] This crash report has been saved to: /home/smpicnic/server/data/./crash-reports/crash-2023-04-11_01.04.05-server.txt

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.16

### Optifine

No

**Comment by chorbintime** [comment]
/kill @e[type=deeperdarker_sculk_snapper]

kind of just assuming this is the issue because you didnt actually attach a crash report
