### ISSUE TITLE
v17 HF performance much worse than v16.5

### ISSUE THREAD

**Issue by ZTexX** [LunaPixelStudios/Better-MC#1164]
### Describe the Bug

My game runs perfectly fine on v16.5 a stable 140fps with shaders on fabric even when loading new chunks it stays perfectly smooth. The second I updated to v17 HF, there's pretty bad lag spikes and dips in fps down in the 70s plus major lag when loading new chunks.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v17 HF

### Optifine

No

**Comment by chorbintime** [comment]
update the immediatelyfast mod
downgrade the jade mod

its an issue with AMD gpus and is already fixed. v20.5 will release soon
