### ISSUE TITLE
when i break a blocks sometimes it doesn't disappear and the block image is still there although its not there

### ISSUE THREAD

**Issue by waflers-himself** [LunaPixelStudios/Better-MC#1165]
### Describe the Bug

when I break or place a blocks sometimes it doesn't disappear and the block image is still there but the actual block isn't there so u can Just walk thro it and its really annoying because u can accidently fall thro it. It tends to vary between how long the block will do that sometimes seconds sometimes minuets 

### Reproduction Steps

1. break any block
2.place any block
3.
...

### Screenshots and Videos

https://clipchamp.com/watch/W1D5vpeinDO

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v14

### Optifine

No

### Other Mods

no

**Comment by chorbintime** [comment]
v14 is very old. we offer no support for old versions whatsoever.
