### ISSUE TITLE
Cannot Sprint on V17/17.5

### ISSUE THREAD

**Issue by lJustWantFame** [LunaPixelStudios/Better-MC#1166]
### Describe the Bug

Sprint doesnt work. pressing w twice doesnt work, nor does ctrl. i tried rebinding, restarting, redownloading. fresh install. Works fine on v16.5 and below but updated versions (17/17.5) it doesnt work

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v17 and 17.5

### Optifine

No

**Comment by chorbintime** [comment]
how did you install the modpack

**Comment by lJustWantFame** [comment]
> how did you install the modpack

through curseforge, i first tried by just updating versions through the 3 dot menu, and i also tried installing a fresh version

**Comment by SHXRKIIE** [comment]
I have no issues with sprinting, did modify the modpack?

**Comment by lJustWantFame** [comment]
> I have no issues with sprinting, did modify the modpack?

no i have not, i have tried everything; reinstalling the mod pack, installing a fresh version, checked keybinds, everything, its literally only 17 and 17.5 where i cant sprint but 16.5 and below i can

**Comment by lJustWantFame** [comment]
> I have no issues with sprinting, did modify the modpack?

i have also even moved launchers and tried playing on ATlauncher and i still cant sprint on those 2 versions

**Comment by chorbintime** [comment]
Sprint does work, and you can sprint. Go into accessibility settings. You have FOV Effects at 0.
