### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by NightmarZero** [LunaPixelStudios/Better-MC#1169]
### Describe the Bug

bug and crash server

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/mJ880bH

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] - BMC1

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
This is not a bug. Your server is just lagging out. Allocate more RAM. 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
