### ISSUE TITLE
Minecraft crashes upon launch

### ISSUE THREAD

**Issue by MoustacheOff** [LunaPixelStudios/Better-MC#1171]
### Describe the Bug

The game crashes a few seconds after being launched from the launcher.

### Reproduction Steps

1. Launch the instance
2. The game log is opened
3. The game crashes

### Crash Report or Log

https://mclo.gs/DcE5goH

### Operating System

macOS 13.3.1 (22E261) - Ventura

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v17.5

### Optifine

No

**Comment by chorbintime** [comment]
Send the crash report instead please
