### ISSUE TITLE
VEIN miner enchantment doesnt work

### ISSUE THREAD

**Issue by arjxn25** [LunaPixelStudios/Better-MC#1172]
### Describe the Bug

it mines one block at a time with wein miner on the pickaxe

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V17 HF

### Optifine

No

**Comment by chorbintime** [comment]
Update to v17.5.

You need to hold the ~ key. Read the tutorial quests in the questbook please.
