### ISSUE TITLE
Enderman wont aggro on endermite

### ISSUE THREAD

**Issue by emka56** [LunaPixelStudios/Better-MC#1173]
### Describe the Bug

I am trying to make enderman xp farm and enderman wont aggro on endermite no matter my entitiy distance or render distance 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v60.5

### Optifine

I used Optifine

**Comment by dylanan1** [comment]
Hey man how did you fix this?

**Comment by emka56** [comment]
idk i just force loaded the chunks and then everything was good  
            
          
     
      
       
        Dnia 16 kwietnia 2023 19:46 dylanan1 ***@***.***&gt; napisał(a):
       
    
       
         
 Hey man how did you fix this?
