### ISSUE TITLE
Wisteria Sign drops Nether Brass Torch when broken

### ISSUE THREAD

**Issue by simspa47025** [LunaPixelStudios/Better-MC#1174]
### Describe the Bug

When using the Wisteria wooden sign from Paradise Lost, upon break, it drops a nether brass torch from Architects Palette.

### Reproduction Steps

1. Craft Wisteria Sign
2.Place in overworld
3.Break with axe (currently using Knightmetal axe with unbreaking 3 and fortune 1)
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC Fabric

### Optifine

No

**Comment by chorbintime** [comment]
will look into it, thanks
