### ISSUE TITLE
Enderman don't aggro on endermite 

### ISSUE THREAD

**Issue by dylanan1** [LunaPixelStudios/Better-MC#1175]
### Describe the Bug

Enderman aren't getting aggro'd on the endermite. Kind of an entity distance thing is what I thought, but it's only vertical and I've tried many different things. Obviously none have worked.

### Reproduction Steps

1.Build enderman farm.
2.Watch as enderman do not aggro when you are below ~30 blocks below.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc 60.5

### Optifine

No

**Comment by chorbintime** [comment]
try removing Does Potato Tick and Roadrunner
