### ISSUE TITLE
Icompatible Vanilla Server

### ISSUE THREAD

**Issue by Erosmp5** [LunaPixelStudios/Better-MC#1178]
### Describe the Bug

i have downloaded the server pack but cant join cause "Icompatible Vanilla Server" im confused

### Reproduction Steps

1.
2.
3.
...

### Operating System

11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

59.5

### Optifine

No

**Comment by chorbintime** [comment]
You need the modpack installed clientside using a launcher such as ATLauncher or Curseforge Launcher
