### ISSUE TITLE
cant attack mobs in bmc3 1.19.2 v13

### ISSUE THREAD

**Issue by 3lectr0B10cks** [LunaPixelStudios/Better-MC#1179]
### Describe the Bug

whenever i try to attack mobs the hits wont register

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13

### Optifine

No

### Other Mods

i added some cosmetic mods like legendary tooltips, item border, droplight, tiny item animation

**Comment by chorbintime** [comment]
remove the added mods and tell me if the issue persists

**Comment by SHXRKIIE** [comment]
Not Responding
