### ISSUE TITLE
Nether Portal not working

### ISSUE THREAD

**Issue by pgnotaman** [LunaPixelStudios/Better-MC#1180]
### Describe the Bug

Nether portal doesnt work and wont take me to the nether, just shows the purple swirl animation indefinitely. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC Forge BMC3

### Optifine

No

**Comment by chorbintime** [comment]
How are you hosting the server?

What modpack version are you on? (v17, v13, v12.5, etc)

**Comment by pgnotaman** [comment]
I'm using Apex Hosting for the server. modpack is Better MC [Forge] - BMC3 1.19.2 v13

**Comment by chorbintime** [comment]
contact apex support. this is not a modpack issue.
