### ISSUE TITLE
Server keeps crashing for unknown reason

### ISSUE THREAD

**Issue by tonickaa** [LunaPixelStudios/Better-MC#1181]
### Describe the Bug

Server keeps crashing/timing out while trying to play the game. 

### Reproduction Steps

1. 
2.
3. 
...

### Crash Report or Log

https://mclo.gs/cuq9sb0

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 v13

### Optifine

No

**Comment by tonickaa** [comment]
https://mclo.gs/l2X4sge a crashlog example

**Comment by chorbintime** [comment]
try updating xaero's minimap, dragon mounts legacy, and open parties & claims
