### ISSUE TITLE
Loading in Chunks Freezes and Crashes Game

### ISSUE THREAD

**Issue by Fredxster** [LunaPixelStudios/Better-MC#1182]
### Describe the Bug

Single player game freezes while loading in/rendering in chunks at particular section of map.
When the player gets to a particular part of the overworld, the game will freeze and then crash. Restarting the world with the render/chunk distances set to the bare minimum allows for you to then move around, however if you progress towards the problem area (Somewhere up north) the game will freeze and crash. Only way to fix is to load a backup of the world and make sure the problem area doesn't get rendered/generated in (unsure if it's on or the other). Everything else seems to works perfectly fine so long as you don't load up that part of the world.
Tried walking into problem spot on two different computers, tried with allocating more RAM with the CurseForge Launcher settings, both failed to fix issue.

### Reproduction Steps

1. Render/Generate/Walking into Specific Area or Chunk.

### Screenshots and Videos

n/a

### Crash Report or Log

https://gist.github.com/Fredxster/8e48ac2f81dec35884d5acc12611b8f2

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v16.5

### Optifine

No

### Other Mods

n/a

**Comment by chorbintime** [comment]
Update to v17.5. We offer no support for old versions whatsoever.
