### ISSUE TITLE
Unable to open v13 world

### ISSUE THREAD

**Issue by emmabeanz** [LunaPixelStudios/Better-MC#1184]
I might just be really stupid, but as of this morning I am unable to load my world in bmc3. its saying that some mods are for newer versions of the game and some for older. Is there any way to fix this or do i have to wait for the mods to update themselves?

**Comment by chorbintime** [comment]
You did not install the modpack properly. Mods do not update themselves, nor do you need to update anything.

To properly install the modpack:
1. Go to https://atlauncher.com/download
2. Install and run the setup, then open the program.
3. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials. 
4. Go to the Packs tab on the right, then click "Curseforge" on the left.
5. Search the modpack you wish to download.
6. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen. 
7. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
8. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.
