### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by Confused54** [LunaPixelStudios/Better-MC#1186]
### Describe the Bug

there is bug where if any tool i keep in hand and go near a wall or any other block the tool has some overlay type thinks 
![Screenshot 2023-04-21 033003](https://user-images.githubusercontent.com/131409610/233496648-84e159b0-25e4-42d2-b382-9e4571053f21.png)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2023-04-21 033003](https://user-images.githubusercontent.com/131409610/233496714-331d7ead-4f11-4fac-9756-d4448944d88c.png)

https://user-images.githubusercontent.com/131409610/233497324-d666e561-acde-42b1-b089-5155aef599f0.mp4

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

17.5

### Optifine

I used Optifine

### Other Mods

better leaves resource pack only

https://user-images.githubusercontent.com/131409610/233497555-809abca0-16a4-40cc-b045-c5899cd8eeef.mp4

![Screenshot 2023-04-21 033003](https://user-images.githubusercontent.com/131409610/233497566-d7cdb692-3481-4951-bd86-80e51a64a74f.png)

**Comment by chorbintime** [comment]
Thats your player's shadow. You're using shaders. This is not a bug in any way.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by Confused54** [comment]
Thanks for the information
Sorry for the trouble
