### ISSUE TITLE
Game Crashes Right After Loading to 100% When Opening World

### ISSUE THREAD

**Issue by Tgoldman123** [LunaPixelStudios/Better-MC#1187]
### Describe the Bug

I've already used the mod pack and had no trouble loading in earlier today, but it randomly began crashing right after the world loading box got to 100%. It works when I delete the Minimap .jar file, but I would like to find a solution that doesn't remove the insanely useful mod lol. I saw what someone tried to post as a solution to someone else's problem and said to pull up the mod's in-game settings through the keybind, but that's not possible when you can't even open the world. Any help would be appreciated! Thank you, and love the mod pack

### Reproduction Steps

1. Load BetterMC through Curse Forge
2. Load existing world or start new world
3. Crash before world renders in

### Crash Report or Log

https://pastebin.com/fj73pcnE

### Operating System

MAC OS

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v17.5

### Optifine

No

**Comment by chorbintime** [comment]
"Xaero's Minimap (1.19.1_23.3.3_fabric) has crashed! Please report here: bit.ly/XaeroMMIssues"

I already answered you in the other thread.
