### ISSUE TITLE
When I try to enter the Nether, I end up in the void instead

### ISSUE THREAD

**Issue by Mhicim** [LunaPixelStudios/Better-MC#1188]
### Describe the Bug

I tried several times today to enter the Nether. But instead, I fell into the void and fell endlessly down. After that, the performance was greatly reduced and the game freezes.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc 17.5 

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
are you on a server? if so, how is the server hosted?

please click the performance guide button on the main menu & follow the steps there too

**Comment by Mhicim** [comment]
I changed the version of Java to the one that was indicated, but it still did not help

**Comment by chorbintime** [comment]
i asked you two questions. please answer them.

the performance guide has more than just switching java.
