### ISSUE TITLE
Cannot get map for the End Remastered Mod

### ISSUE THREAD

**Issue by RiskierXenx** [LunaPixelStudios/Better-MC#1189]
### Describe the Bug

i went into creative to find a strong hold went to it and i added all different eyes to it but one had an eye in the slot, but it was grayed out and i couldn't activate the portal. I tried to create my own portal, but it said "eye already been placed" when i tried to add the eyes. Also, I think better Minecraft is missing the Castle Mod in order to get all the eyes. I've tried getting a map in creative with sooo many carpenters for the end castle which i read i need to find in order to get all the different eyes for the end portal. But ultimately never found one. 

### Reproduction Steps

1.Find end portal in strong hold.
2. Check if one frame has a grey eye already set inside.
3.Add eyes and see if it activates. 
4. go into creative and make your own portal
5. See if adding new eyes will say "already been placed."
...

### Screenshots and Videos

![Screenshot (1)](https://user-images.githubusercontent.com/131505487/233758929-27a843c1-7cce-41da-9b7c-9cbe26e3ce3d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/131505487/233758932-20e8663e-8805-42a8-99a7-da9364faa76a.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Medieval MC [FABRIC} v5.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
v5.5 is extremely old, you are 15 versions out of date. Please update the modpack. We offer no support for old versions.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
