### ISSUE TITLE
BMC Fabric v17.5 Smithing Table

### ISSUE THREAD

**Issue by tyjdu92** [LunaPixelStudios/Better-MC#1190]
In the latest version of Better Minecraft Fabric, this smithing table is updated to require smithing templates to upgrade gear, but the smithing templates are not in the game yet. Not sure if this is a Mojang/Microsoft issue, or if it's possible to put the old smithing table back into the mod until smithing templates are released.

**Comment by SHXRKIIE** [comment]
It seems its just the resourcepack changing the look, the old inputs are still there if you hover over it. Will fix in next update
