### ISSUE TITLE
Default animals in Minecraft appear purple and black

### ISSUE THREAD

**Issue by tahamoosavi** [LunaPixelStudios/Better-MC#1191]
### Describe the Bug

I encountered this bug while playing the Better Minecraft Mod version 1.19.2. The default animals such as chicken, sheep, cow and pig appear purple and black instead of their natural colors. This bug occurs in all different worlds and changing the graphic settings does not help. I am using Java RE 8 And Windows 11 as my operating system.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-04-23_12 57 38](https://user-images.githubusercontent.com/131584785/233831580-581b0d48-31ef-47ef-9df3-9a4fbc28f702.png)
![2023-04-23_12 57 59](https://user-images.githubusercontent.com/131584785/233831698-cb5e53f6-ff45-4ab9-a70c-876c129f91fa.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 v13

### Optifine

No

**Comment by chorbintime** [comment]
To reload textures and sounds, press F3 + T. If this doesn't bring up a loading screen, do the following:
1. Press escape and go to the Resourcepacks tab.
2. Move a Resourcepack on the left of the screen to the right. 
3. Move that SAME Resourcepack back to the left. 
4. Exit the menu. 
If step 4 does not bring up a loading screen, do step 2, then step 4, then step 3, and then step 4 again.
