### ISSUE TITLE
error en backpacked mod

### ISSUE THREAD

**Issue by ikerjmnz** [LunaPixelStudios/Better-MC#1193]
### Describe the Bug

se a ajustado automaticamente el espacio de la mochila a una fila, y no esta instalado el mod necesario para editar esta(config) en el modpack better minecraft

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 v13.zip

### Optifine

No

**Comment by chorbintime** [comment]
update the night config fixes mod on a fresh install
