### ISSUE TITLE
mining unavailable

### ISSUE THREAD

**Issue by Grugnation** [LunaPixelStudios/Better-MC#1194]
### Describe the Bug

the bug more or less prevents one from mining not sure it started after i beat the phantoms and after that ive ben unable to mine at all cant rightclick.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19

### Optifine

No

**Comment by erian-7** [comment]
Confirming this bug. I updated our server to the latest version, copied over the world files, and updated the client (using ATLauncher). Mining any ore drops nothing. Mining stone normally or with silk touch drops cobblestone or stone as expected, so it only affects ore. I also tried gravel for flint and clay for clay balls. Both of those seem unaffected so it's specific to pick axe at present.

**Comment by erian-7** [comment]
Follow-up for my findings. I tried in single player and found no problem, so I then created a new world folder on the server and also have no problems. In my case, then, it seems the issue is with an existing world updating to the new version.
