### ISSUE TITLE
Backpacked Mod Ignores Config File

### ISSUE THREAD

**Issue by Kastralis** [LunaPixelStudios/Better-MC#1195]
When we first setup the server with Better MC 3 (for 1.19.2) and installed the same for our client side, we were able to update the Backpacked config file to change it from 1 row of inventory space to 4. It worked fine for the first day, then ever since after a scheduled server restart the Backpacked mod basically now ignores the config file entirely and reset to functioning with only 1 row of inventory space.

We've tried to delete the config file and restart the server, expecting a new config file to be generated for the Backpacked mod, however it did not.

We've also tried reinstalling it (backpacked-2.1.10-1.19). A fresh install did not resolve the issue.

We've then tried to replace backpacked-2.1.10-1.19 with an updated version (Backpacked 2.1.12). This did not resolve the issue.

From what we are seeing, the assumption is that it is completely ignoring the existence of the "backpacked-common.toml" file under the "defaultconfigs" directory in the server.

What can we do to resolve this issue?

**Comment by chorbintime** [comment]
update to v14 on a fresh install
