### ISSUE TITLE
Mod Suggestion - Cat Jammies [Fabric] 

### ISSUE THREAD

**Issue by farrucho** [LunaPixelStudios/Better-MC#1198]
### Describe the Bug

There was a mod called Cat Jammies, made for forge that people loved. The developer unfortunately didn't keep the mod updated so the community was kinda frustrated. I think this mod would add a little bit of fun, without destroying any environment. It would be a fun thing to boost the player mood. https://legacy.curseforge.com/minecraft/mc-mods/cat-jammies-fabric

### Reproduction Steps

1.
2.
3.
...

### Operating System

W11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc fabric

### Optifine

No

### Other Mods

Cat Jammies - FABRIC

**Comment by chorbintime** [comment]
Make suggestions in the Discord server
