### ISSUE TITLE
Cannot Connect to server with Better MC installed

### ISSUE THREAD

**Issue by NaSmile88** [LunaPixelStudios/Better-MC#1200]
I started a server with some friends using Better MC. Everything works fine in single player but on our server we get the issue attached below. How do I fix this? Also I'm using the Better MC 1.19.2 version updated 3 days ago. 
![bettermc](https://user-images.githubusercontent.com/132237204/235382577-cf6494f2-f234-4ad3-a599-b1e6c199cab0.PNG)

**Comment by pizzo78** [comment]
same issue here!

**Comment by RikiiV** [comment]
Im having the same issue.

**Comment by chorbintime** [comment]
You do not have the same modpack installed as the server. This is user error. Not a modpack issue.

Please install the serverpack for proper serverside installation. Read the file named README. You can also buy a server with Bisect Hosting.

For clientside installation, use ATLauncher to install & launch.

Once again, this is not a modpack issue in any way.
