### ISSUE TITLE
Game crashes while exploring

### ISSUE THREAD

**Issue by Doggydog123579** [LunaPixelStudios/Better-MC#1201]
### Describe the Bug

I was flying in creative over an unexplored ocean when the game crashed.

### Reproduction Steps

1. Create world
2. Fly around
3. Game Crashes

### Screenshots and Videos

.

### Crash Report or Log

gist.github.com/Doggydog123579/4fcba63cdad7fc3c1e927a01ef85a065

### Operating System

Windows10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 V17.5 HF

### Optifine

I used Optifine

### Other Mods

No

**Comment by chorbintime** [comment]
Switch to Adoptium Java 18. You can find a guide here: https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
