### ISSUE TITLE
Better MC [FORGE] crashing

### ISSUE THREAD

**Issue by skeketh** [LunaPixelStudios/Better-MC#1203]
[crash log.txt](https://github.com/LunaPixelStudios/Better-MC/files/11392949/crash.log.txt)

**Comment by chorbintime** [comment]
switch to ATLauncher and use java 18. instructions can be found here https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide

**Comment by skeketh** [comment]
This is on ATLauncher and while using java 18.

**Comment by chorbintime** [comment]
Your log shows you're using Java 17.

**Comment by chorbintime** [comment]
Make sure to set your java path within ATLauncher, read the performance guide
