### ISSUE TITLE
Enchanted Book that cannot enchant

### ISSUE THREAD

**Issue by Opalie** [LunaPixelStudios/Better-MC#1204]
### Describe the Bug

If a player gets an enchanted book, sometimes they are not working with an anvil and tools you want to enchant. They also do not have the enchant description on them, or tools they can be used on.

### Reproduction Steps

1. Get an enchanted book in a treasure chest (I got these in a dungeon, for example) OR make an enchanted books with an enchanting table.

![Screenshot 2023-05-04 174408](https://user-images.githubusercontent.com/31365045/236259474-8b3d2a6b-a734-4cf9-8c2d-1c643c215e53.png)

2. Try on an anvil to put mending on a tool
![Screenshot 2023-05-04 174408](https://user-images.githubusercontent.com/31365045/236259652-97b3faaf-b1d9-4b05-8192-5c45bacc7f22.png)

### Crash Report or Log

https://mclo.gs/JwzazWB

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3

### Optifine

No

**Comment by chorbintime** [comment]
sharpness 3 is not a shovel enchant

**Comment by Opalie** [comment]
Like I wrote the enchant was mending, not sharpness.
