### ISSUE TITLE
bclib is incompatible with RecipeConfidence.

### ISSUE THREAD

**Issue by Kinato2424** [LunaPixelStudios/Better-MC#1205]
### Describe the Bug

after updating Java i tried to open a server i already had of BM but it didnt work and send me to the crash (it worked before the update).

I thought it was because there was a difference between the javas so i decided to make a new server from 0 but after trying a couple of times i ended up with the same crash. the only thing i comprehend was that it was abot an incompatibility (bclib is incompatible with RecipeConfidence.)

### Reproduction Steps

1.Download the server for the 1.18.2 BM
2.Start it with the .bat
3.Accept the EULA 
 
and then it will be there
...

### Crash Report or Log

https://gist.github.com/Kinato2424/d0b94bfbe6b61fc829f95139bc5c3e94

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better+Minecraft+Server+Pack+[FABRIC]+v12

### Optifine

No

**Comment by chorbintime** [comment]
that error means nothing

v12 is very old. we offer no support for old versions

**Comment by elpideus** [comment]
> that error means nothing
> 
> v12 is very old. we offer no support for old versions

I am using 2.1.7
Same problem here

**Comment by elpideus** [comment]
Mod Menu was the problem for me

**Comment by chorbintime** [comment]
> > that error means nothing
> > v12 is very old. we offer no support for old versions
> 
> I am using 2.1.7 Same problem here

there is no "2.1.7" version of the modpack

you are using v12 of the modpack, the latest version is v20
we do not offer any support for old versions of the modpack whatsoever
