### ISSUE TITLE
Low TPS

### ISSUE THREAD

**Issue by Sididi** [LunaPixelStudios/Better-MC#1206]
### Describe the Bug

I have an average of 13.5tps when playing Better MC v17 (didn't upgrade to 17.5 yet)
We're 3 max players and my VPS does not exceed 35% CPU usage / 40% Process Memory Usage (allocated 4gb to Better MC with an 8gb server). So it comes from Minecraft itself

I use Temurin 17 with some JVM arguments (available through the Spark link below)

When creating this issue I restarted the server and tried simple things which I will list here:
- We were all in overworld, no dimension loaded
- Very few redstone
- Only a couple of farms and animal entities
- Only did simple tasks such as using furnaces, farm crops, moving a bit (only through already generated chunks), eating

When using spark to log long lasting ticks it seemed to happen when I ride my bee from bumblezone, even though **I remain motionless**, but on tick profiler bumblezone only takes 1% of tick

I have joined a spark link with this issue which logs all the ticks exceeding 80ms

The game is currently almost unplayable as these long ticks stack themselves and the server lags more and more untill it eventually crashes
I have done all the investigation I could and hope to find some help here

Sincerely,
Sid

### Crash Report or Log

https://spark.lucko.me/HxQ8ItLKkU

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v17

### Optifine

I do not use Optifine

**Comment by Sididi** [comment]
/kill @e[type=frostiful:freezing_wind] seemed to work
Would still like to know why freezing_wind entities did not disappear on themselves and instead stacked infinitely like this

**Comment by Sididi** [comment]
Spark link expired so I'm attaching the [.sparkprofile file](https://cloud.sididi.tv/s/QeqawFx7Tqt2KZL)

**Comment by chorbintime** [comment]
Sending this to the Frostiful dev

**Comment by TheDeathlyCow** [comment]
Freezing Wind spawning can be toggled off on the config with the optional `doWindSpawning`. However, if you update to Frostiful 0.5.2, there is now a cap on the number of wind entities that can spawn.

**Comment by Sididi** [comment]
Thank you for the answers, I have disabled `doWindSpawning` for now
Freezing Winds entities stay infinitely (and are likely invisible / useless) so upgrading to 0.5.2 would just rapidly lead to freezing winds just not spawning anymore

Feel free to close the issue when you consider it solved

**Comment by TheDeathlyCow** [comment]
Freezing Wind should kill itself after a few seconds. It does also spawn high up in the sky, in addition to its ground spawning. Are you sure there isn't wind up there? It seems unusual for it to bunch up. If so, there could be a mod conflict issue here. If you use F3+b then you will be able to see the bounding boxes of freezing wind.

**Comment by Sididi** [comment]
> Freezing Wind should kill itself after a few seconds. It does also spawn high up in the sky, in addition to its ground spawning. Are you sure there isn't wind up there? It seems unusual for it to bunch up. If so, there could be a mod conflict issue here. If you use F3+b then you will be able to see the bounding boxes of freezing wind.

When I checked with *Debug hitboxes: shown* there seemed to be a totally common amount of winds in the air to me (around fifty winds max. above my chunk), nowhere as much as the thousands entities

**Comment by Sididi** [comment]
Checked with Spark out of curiosity, ~100 chunks loaded in overworld for no reason, maybe a clue?

**Comment by 630R63** [comment]
I don't know if I should post this here or make a separate issue.

We also have a Better Minecraft [FABRIC] server going and already deactivated the wind entities in the config. But, 3 players loading 3 different areas in the overworld are enough to get the server to 50mspt or above. Having 7 people on at the same time, we get 8-9 TPS with around 100mspt or more.

Also, I have the suspicion that one of the mods may have a memory leak. We had to get a server with 16GB of RAM just so we don't crash because out of memory. Just a bit of exploration immediately makes the server go to 14-15GB of RAM.

Is this modpack that difficult to host?

According to the spark profiler, the host is using an i9-9900k as their CPU, and we have asked for 4vCores.

**Comment by chorbintime** [comment]
We can't help without a spark profiler.

**Comment by chorbintime** [comment]
Your args are very weird - why is your maximum ram value an equation? I'd suggest using https://github.com/etil2jz/etil-minecraft-flags

Update to java 18 instead of 17

run /kill @e[type=item]

you can also kill all chickens, item frames, zombies, skeletons, and crepers

**Comment by Sididi** [comment]
Still having extremely low TPS (around 10-11), it does seem to come from somewhere else than Frostiful
[Spark profile](https://spark.lucko.me/bnLXapN2YF)

Note: Freezing Winds keep spawning with `doWindSpawning` set to `false`, so I have to /kill from time to time

**Comment by chorbintime** [comment]
> Still having extremely low TPS (around 10-11), it does seem to come from somewhere else than Frostiful [Spark profile (online)](https://spark.lucko.me/bnLXapN2YF) / [Spark profile (file)](https://cloud.sididi.tv/s/MPTEoHbH99dMoyP)
> 
> Note: Freezing Winds keep spawning with `doWindSpawning` set to `false`, so I have to /kill from time to time

Try updating the Frostiful mod.

@TheDeathlyCow In the above spark, the person has 4,500 freezing wind entities that won't stop spawning even with the config option disabled. Would this be fixed in the latest version of Frostiful?

**Comment by TheDeathlyCow** [comment]
I'm not sure. My best guess is that wind entities aren't actually spawning, they're just being loaded from chunks that were not loaded when the kill commands were run. The only other reasons I can think of would be either that the config files were not saved correctly or in the correct place, or there's a problem with Cloth. 

In the meantime, I think you could just set up a datapack that runs a kill function once per second for a while until it's no longer an issue. Something that just loads a function like this through `#minecraft:load`:

```mcfunction
schedule function frostiful:clear_wind 1s replace
kill @e[type=frostiful:freezing_wind]
```

**Comment by Sididi** [comment]
> 

Here is a [clone of my server](https://cloud.sididi.tv/s/TmSYLR6JwGW7BXj) (without world & mods folder) if you're interested in checking

**Comment by Sididi** [comment]
> 

Here is a [clone of my server](https://cloud.sididi.tv/s/TmSYLR6JwGW7BXj) (without world & mods folder) if you're interested in checking

Freezing winds keep spawning even though I stay afk in same chunk
