### ISSUE TITLE
Cannot place Sod Patch blocks

### ISSUE THREAD

**Issue by DovahBeat** [LunaPixelStudios/Better-MC#1207]
### Describe the Bug

I was playing the game in survival as usual and wanted to check out the sod blocks, crafted the patches which are supposed to work like carpet, and i cannot place them ANYWHERE. I don't know if this is a user error or a bug or a bad settings choice, but i would like assistance. Thank you for your time and support.

EDIT: was able to place them down on grass (not the block but the plant) but it turns the sod patch into snow and makes the grass turn into "frozen grass" from winterly.

### Reproduction Steps

1. Craft "dirt sod patch" carpet blocks
2. try to place on any solid block
3. will not place down
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v17.5

### Optifine

No

### Other Mods

Better MC Mod pack is all that's in there

**Comment by chorbintime** [comment]
report to the developer of that mod

better mc is a modpack, not a mod
