### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by lucasschmitz-dev** [LunaPixelStudios/Better-MC#1208]
### Describe the Bug

While Startup the Server is always carshing.

I am using a dedicated Server from Hetzner with:
AMD Ryzen™ 5 3600CPU6 cores / 12 threads @ 3.6 GHzGeneration:Matisse (Zen 2)
RAM64 GB DDR4 RAMDrives
2 x 512 GB NVMe SSD

------------------------------------------

Console log:
A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007fe4caab26d0, pid=1689, tid=1758

JRE version: Java(TM) SE Runtime Environment (17.0.7+8) (build 17.0.7+8-LTS-224)
Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.7+8-LTS-224, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
Problematic frame:
V  [libjvm.so+0xd606d0]  SystemDictionaryShared::has_class_failed_verification(InstanceKlass*)+0x80

Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/lucasschmitz/MinecraftServerForge/core.1689)

An error report file with more information is saved as:
/home/lucasschmitz/MinecraftServerForge/hs_err_pid1689.log

If you would like to submit a bug report, please visit:
 https://bugreport.java.com/bugreport/crash.jsp

./start.sh: line 54:  1689 Aborted                 (core dumped) "$JAVA" ${1}

Exiting...
Press any key to continue

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/lucasschmitz-dev/8968de1563739759802957186679d91a

### Operating System

Ubuntu-2204-jammy-amd64-base

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 v14

### Optifine

No

### Other Mods

none

**Comment by chorbintime** [comment]
You need Adoptium Java 18. Please read the readme.

**Comment by lucasschmitz-dev** [comment]
Similar Issue is happening with Adoptium Java 18. 

https://gist.github.com/lucasschmitz-dev/b7d2ecdcf893b70f7f5a96982b0e1ab2
