### ISSUE TITLE
Villager interacting with flax (paradise lost) issue

### ISSUE THREAD

**Issue by KozmicDaddy** [LunaPixelStudios/Better-MC#1211]
### Describe the Bug

Hi!
Sorry for my pour english, I'll try my best to explain what is happening to my world.

One of my villagers (farmer) has interacted with flax (I think it was flax) from Paradise Lost's mod. That may have caused a crash that is occuring everytime I try to run my world. Just in case it has something to see, he replaced it with Oat.

The bug report thing is telling me (I think) that the flax is still there but at a different level than expected.

### Reproduction Steps

1. Place flax (Paradise Lost)
2. Have a Farmer Villager (jungle?)
3. Let him take it (maybe, let him replace it with Oat)
4. FPS start being very low
5. Crash

### Crash Report or Log

The game crashed whilst unexpected error Error: java.lang.IllegalArgumentException: Cannot set property IntProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} to -4 on Block{paradise_lost:flax}, it is not an allowed value

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

17.5

### Optifine

I used Optifine

**Comment by KozmicDaddy** [comment]
I don't know if I was using Optifine. If it is not included in the modpack, then no

**Comment by KozmicDaddy** [comment]
EDIT : 
I reloaded a backup from the mod from just before the crash yesterday. I destroyed my fields for security but the Farmer had flax' seeds and when he placed them I instantly got disconnected when I looked at them.

I got this specific message from the launcher :
 
_The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property IntProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} to -4 on Block{paradise_lost:flax}, it is not an allowed value_

**Comment by chorbintime** [comment]
update the paradise lost mod
