### ISSUE TITLE
Vinery mod issue within better minecraft

### ISSUE THREAD

**Issue by LoneHunteress** [LunaPixelStudios/Better-MC#1214]
### Describe the Bug

For the Vinery mod- you can not fill wine bottles with the grape juice after squishing the grapes. Aging barrel also doesn't function. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 v14.zip

### Optifine

I used Optifine

### Other Mods

n/a

**Comment by chorbintime** [comment]
Report to the Vinery developer.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod.
