### ISSUE TITLE
Invincible Bosses

### ISSUE THREAD

**Issue by TehFries** [LunaPixelStudios/Better-MC#1215]
### Describe the Bug

Some bosses just becomes invincible especially the shulker bosses and since they can teleport it makes it 10x harder

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Please be more specific. I don't see how this is a modpack issue.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod.
