### ISSUE TITLE
Error during initialization of boot layer

### ISSUE THREAD

**Issue by JuicyOneExile** [LunaPixelStudios/Better-MC#1216]
### Describe the Bug

Error during the installation of the modded forge server.

Starting server...

Minecraft version: 1.19.2
Modloader:         Forge
Modloader version: 43.2.8

Java args:
Java path:         java
Run Command:       java -Dlog4j2.formatMsgNoLookups=true @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.2.8/unix_args.txt nogui
Java version:
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

Error occurred during initialization of boot layer
java.nio.file.InvalidPathException: Illegal char <:> at index 70: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar:libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar:libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar:libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar:libraries/org/ow2/asm/asm/9.3/asm-9.3.jar:libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![immagine](https://github.com/LunaPixelStudios/Better-MC/assets/97894501/5c41b192-f2f0-4916-af53-88fb6d8a90d9)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 v13

### Optifine

No

**Comment by chorbintime** [comment]
v13 is old. Update to v14.

Switch to Java 18. Read here for a guide: https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide

**Comment by DarkDisaster123** [comment]
I have a similar problem. I need some help with that.


![image](https://github.com/LunaPixelStudios/Better-MC/assets/133839405/244ba23c-9e79-4864-b482-dd3ee498a53d)
![Screenshot 2023-05-17 095940](https://github.com/LunaPixelStudios/Better-MC/assets/133839405/61dc7845-7419-4774-84ab-e3143af4bc58)

**Comment by chorbintime** [comment]
> I have a similar problem. I need some help with that.
> 
> ![image](https://user-images.githubusercontent.com/133839405/238833530-244ba23c-9e79-4864-b482-dd3ee498a53d.png) ![Screenshot 2023-05-17 095940](https://user-images.githubusercontent.com/133839405/238833801-61dc7845-7419-4774-84ab-e3143af4bc58.png)
> 
> ---- Minecraft Crash Report ---- // Hey, that tickles! Hehehe!
> 
> Time: 5/17/23 9:51 AM Description: Mod loading error has occurred
> 
> java.lang.Exception: Mod Loading has failed at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) [?:?] {re:classloading} at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) [?:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft$$Lambda$3668/1467742939.run(Unknown Source) [?:?] {} at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading} at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft$$Lambda$3450/433404596.accept(Unknown Source) [?:?] {} at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A} at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {} at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/172299409.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {} at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- Head -- Thread: Render thread Stacktrace: at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:74) ~[?:?] {re:classloading} -- MOD reeses_sodium_options -- Details: Mod File: TextruesRubidiumOptions-1.0.4-mc1.16.5.jar Failure message: Mod reeses_sodium_options requires rubidium 0.2 or above Currently, rubidium is not installed Mod Version: 1.0.4-mc1.16.5 Mod Issue URL: NOT PROVIDED Exception message: MISSING EXCEPTION MESSAGE Stacktrace: at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:74) ~[?:?] {re:classloading} at net.minecraftforge.fml.CrashReportExtender$$Lambda$3698/209029677.accept(Unknown Source) ~[?:?] {} at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {} at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:72) [?:?] {re:classloading} at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) [?:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft$$Lambda$3668/1467742939.run(Unknown Source) [?:?] {} at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading} at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft$$Lambda$3450/433404596.accept(Unknown Source) [?:?] {} at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A} at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {} at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/172299409.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {} at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
> 
> -- System Details -- Details: Minecraft Version: 1.16.5 Minecraft Version ID: 1.16.5 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_51, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 1832181344 bytes (1747 MB) / 2852126720 bytes (2720 MB) up to 3154116608 bytes (3008 MB) CPUs: 4 JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec ModLauncher launch target: fmlclient ModLauncher naming: srg ModLauncher services: /mixin-0.8.4.jar mixin PLUGINSERVICE /eventbus-4.0.0.jar eventbus PLUGINSERVICE /forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE /forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE /forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE /forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE /mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE /forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE FML: 36.2 Forge: net.minecraftforge:36.2.39 FML Language Providers: javafml@36.2 minecraft@1 kotlinforforge@1.17.0 Mod List: forge-1.16.5-36.2.39-client.jar |Minecraft |minecraft |1.16.5 |NONE |Manifest: NOSIGNATURE forge-1.16.5-36.2.39-universal.jar |Forge |forge |36.2.39 |NONE |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90

This isnt a similar issue at all. It isnt even an issue. You are likely using a pirated launcher and, as usual, it did not install files correctly. Even if that isnt the case, this is in no way a modpack issue.

Use ATLauncher to install & play modpacks. If the issue persists, make a new issue.
