### ISSUE TITLE
Enternal portal in the end crash

### ISSUE THREAD

**Issue by Ghost-415** [LunaPixelStudios/Better-MC#1217]
### Describe the Bug

Issue is I’m crashing when entering the eternal portal in the end dimension. It’s upon entering the portal that the game crashed. I’m stuck in a boot up loop and can’t seem to play the game at all. 

I attempted NBTexplorer to change the player data position to about 50 blocks away and save. 

 when I boot up Minecraft and load onto the world, I still continue to crash, and the coordinates some how change to exactly where the entity (me the player) is colliding with the block (eternal portal) and proceeds to crash. Can anyone help out??

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/133479024/3fb85835-d0e4-41d3-a1fe-65090ff01b77)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/133479024/b08e0ed4-2834-41de-9150-fccba1832d30)

### Crash Report or Log

N/a

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2 v15.zip

### Optifine

I used Optifine

### Other Mods

N/a

**Comment by chorbintime** [comment]
v15 is old. We offer no support for old versions of the modpack, please update.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
