### ISSUE TITLE
Mount health bar is all black.

### ISSUE THREAD

**Issue by ItzNatsu** [LunaPixelStudios/Better-MC#1218]
### Describe the Bug

All the mount's healthbars are black bars. you can't tell the mount's health.

At first i thought the toughness bar mod was in some way interfering with it, so i exchanged it for a forked version that stacks the toughness bar with the armor bar instead so that there's room for the mount's health bar but that did not solve the issue. 

I then assumed it might just be a resource pack issue. so i disabled my resource packs and even tried to add a different hud icons pack but that didn't fix it either. i'm not exactly sure as to what is causing this issue. this is on the latest BMC 1 Fabric pack.

I had added other mods to the pack but the issue existed before these mods were added.

### Reproduction Steps

1. Download and install BMC 1 Fabric
2. Run game and join server.
3. Find a mount and right click.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/68730384/1d26e05a-4620-4146-acc9-5f7549a9505a)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v17.5 HF

### Optifine

No

### Other Mods

![image](https://github.com/LunaPixelStudios/Better-MC/assets/68730384/99596b26-df97-48ff-bf35-eaf79022a1f2)

**Comment by chorbintime** [comment]
Remove or update the Better Mount HUD mod
