### ISSUE TITLE
MC crashes after running

### ISSUE THREAD

**Issue by Flickersir** [LunaPixelStudios/Better-MC#1220]
### Describe the Bug

This is the log https://paste.atlauncher.com/view/fde03537-a449-4122-af24-e806a9811aa0
I really dont know whats the problem

### Reproduction Steps

1. Launch MC

### Screenshots and Videos

![image_2023-05-13_125209420](https://github.com/LunaPixelStudios/Better-MC/assets/133500892/72be5645-5912-414b-a7db-5a648cd9c7bf)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13

### Optifine

No

**Comment by chorbintime** [comment]
v13 is old, update the modpack.

Update your Java to Java 18. There is a guide here https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide

If the issue persists do the following:
For users who are experiencing issues with the built-in GLFW, there's a quick and easy solution for you to use the latest, bug-free GLFW that can remedy the solution.

IF YOU WOULD PREFER HAVING PRE-BUILT FILES AVAILABLE, YOU MAY DOWNLOAD THEM FROM MY REPOSITORY: https://github.com/Frontear/glfw/releases

If you are comfortable using tools such as cmake, follow the guide below (more detailed instructions found at https://www.glfw.org/docs/latest/compile.html):
- Clone the glfw repository from github: https://github.com/glfw/glfw.git
- Run cmake -S . -B build -DBUILD_SHARED_LIBS=ON to ensure the correct makefiles are created
- Run cmake --build build to compile the source code.
- Go to ./build/src/ and copy libglfw.so (on Linux) or glfw3.dll (on Windows) somewhere that you can remember (and not delete)
- Add the following argument to your java args (the place where you put -Xmx -Xms): -Dorg.lwjgl.glfw.libname=/path/to/glfw/file, where /path/to/glfw/file should be replaced with the full path to the file you copied above. Examples of this are 
"C:\Users\Me\Documents\glfw3.dll" (Windows, yes with the quotes) or /home/user/Documents/libglfw.so` (Linux).
