### ISSUE TITLE
Curse Forge Install Issue

### ISSUE THREAD

**Issue by SimpleSanguine** [LunaPixelStudios/Better-MC#1221]
### Describe the Bug

Upon trying to install the better MC[Fabric] -BMC1 pack you get an error stating " Missing file for mod "Tokenable Decoration"(ID: 517310) in database. Aborting Installation."

### Reproduction Steps

1.Locate Better MC [Fabric] -BMC1 
2.Click orange install button
3.Wait for install error window to appear
...

### Screenshots and Videos

![curseforge error](https://github.com/LunaPixelStudios/Better-MC/assets/133819209/6ae3af7a-00ba-444d-9f98-321178359ebd)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
There is nothing we can do about this. We are not responsible in any way for issues on Curseforge's side.

Switch to ATLauncher if you don't want these issues to happen.

Optifine is incompatible with all of our modpacks. Do not use it for any Minecraft version 1.16.5 or newer. It's a pointless, laggy mod with much better alternatives out there.
