### ISSUE TITLE
Twilight Forest TowerWingComponent.makeGlyphBranches(TowerWingComponent.java:1939 method is attempting to generate a random number with a bound of 0 or less, which is not allowed in Java

### ISSUE THREAD

**Issue by jaynotgay** [LunaPixelStudios/Better-MC#1222]
### Describe the Bug

Java IllegalArgumentException, specifically stating "Bound must be positive."

Based on the traceback, this error is encountered while the server is attempting to generate features for a new chunk in the Twilight Forest. The FinalCastleMazeTower13Component.generate(FinalCastleMazeTower13Component.java:465) method is called, which eventually leads to the makeGlyphBranches() method being called, resulting in the error.

https://mclo.gs/HgolSuY

### Reproduction Steps

attempt to generate features for a new chunk in the Twilight Forest  FinalCastleMazeTower13Component.generate(FinalCastleMazeTower13Component.java:465
...

### Crash Report or Log

https://mclo.gs/HgolSuY

### Operating System

ubuntu 20 

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v17

### Optifine

I used Optifine

### Other Mods

customearnings - private mod
mceconomy - private mod
playershops - private mod
auctions - private mod
essential_commands-0.30.0-mc1.19.2
ftb-ranks-fabric-1902.1.14-build.70
holograms-1.4.0+1.19.2
LuckPerms-Fabric-5.4.46
LuckPerms-Fabric-PlaceholderAPI-Hook
Multiworld-Fabric-1.6
servercore-1.3.3-1.19.2
lithium-fabric-mc1.19.2-0.11.1
styled-chat-2.0.3+1.19.2
styled-nicknames-1.1.2+1.19
votifierrenewed-19.1.0
worldedit-mod-7.2.12
Chunky-1.3.38
kits-1.5.0-v2-mc1.19.2
observable-3.3.1

**Comment by chorbintime** [comment]
This is not a modpack issue. There is nothing we can do about this. It's an issue with the Twilight Forest mod itself, and they are already aware of the issue. You can try updating the Twilight Forest mod if an update is available. 
If a user is stuck in a crash loop, you can change their dimension and/or coordinates by opening their playerdata via the NBTStudio mod.

Lithium is already in the modpack. 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
