### ISSUE TITLE
crashes on start.bat better mc2 server 1.18.2

### ISSUE THREAD

**Issue by Salutatorian** [LunaPixelStudios/Better-MC#1223]
### Describe the Bug

bettermc 1.18.2 keeps crashing

just dropped it in the mods expecting for it to work but crashes all the time

### Reproduction Steps

1. download better mc2 1.1.8.2 server
2. put it in the server mod folder
3. run start.bat BOOM CRASH
...

### Screenshots and Videos

[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/11522588/latest.log)

### Crash Report or Log

non

### Operating System

win 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better mc 1.1.8.2 mc2

### Optifine

No

### Other Mods

no added mods

**Comment by chorbintime** [comment]
There is a lot more to the modpack than just the mods folder.

Please use the serverpack for launching the server. Do not drag files anywhere.

**Comment by Salutatorian** [comment]
U idiot ofc im using the server pack dont close this shit dumb fucker

**Comment by Salutatorian** [comment]
im not using the mod pack, i downloaded the server pack idiot dont close this thread and go on and help me

**Comment by Salutatorian** [comment]
i bet u didnt even read the logs stupid blind fucker u just assumed.

**Comment by Salutatorian** [comment]
> There is a lot more to the modpack than just the mods folder.
> 
> Please use the serverpack for launching the server. Do not drag files anywhere.

U idiot ofc im using the server pack dont close this shit dumb fucker
im not using the mod pack, i downloaded the server pack idiot dont close this thread and go on and help me
i bet u didnt even read the logs stupid blind fucker u just assumed.

**Comment by Salutatorian** [comment]
it even said in the Reproduction Steps
"download better mc2 1.1.8.2 server"

man how stupid are you as a support assuming and not helping. quit this job if u cant even take it seriously and go work a lighter job
