### ISSUE TITLE
I INSTALLED THE BETTER MC SERVER 1.18.2 and it crashes everytime i run it.

### ISSUE THREAD

**Issue by Salutatorian** [LunaPixelStudios/Better-MC#1225]
### Describe the Bug

i just wanted to run a better mc minecraft server 18.2 MC2 but when i run it, it crashes. i shared logs that i dont understand that only you guys do.

### Reproduction Steps

1.
2.
3.
...

### Operating System

win 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better mc 1.1.8.2 mc2

### Optifine

No

### Other Mods

no added mods

**Comment by chorbintime** [comment]
closed due to OP being a whiny little baby

**Comment by Salutatorian** [comment]
CLOSE THIS, MODERNFIX MOD WAS THE PROBLEM IN MY END
