### ISSUE TITLE
Entity spinning rendering bug

### ISSUE THREAD

**Issue by Lynanoctem** [LunaPixelStudios/Better-MC#1227]
### Describe the Bug

Hallo, I startet playing BM BMC1 1.16.5 a day ago. 
I have the issue that the entities won't render if I'm not standing in an 20-30 block radius. They spin around like crazy and they can't move anymore than spinning.

### Reproduction Steps

1. Disable entity culling
2. Entity Render Distanz at 500% 
3. Render Distanz at 16 Chucks or higher
4. Disable shaders
5. No max entity distance
6. Install more ram 
...

### Screenshots and Videos

I can't put a Video in, I don't know why.

### Crash Report or Log

No crashes

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC 1

### Optifine

No

### Other Mods

Better villages
Ice and Fire 1.16

**Comment by Kasualix** [comment]
This is totally not a bug, but a kind of acknowledgement.
If you don't think stopping ticking the stupid laggy entities that are very far from players is a way to optimize TPS, dpt is nothing for you.
