### ISSUE TITLE
Charm's Collection Enchantment prevents item drops

### ISSUE THREAD

**Issue by Emmescingue** [LunaPixelStudios/Better-MC#1229]
### Describe the Bug

When using a pickaxe with specifically these enchantments:

<details>
  <summary>Enchantments</summary> 
  
  Efficiency IV
  Unbreaking III
  Fortune III
  Mending
  Collection
  
</details>

Breaking some blocks like Coal Ore works as expected: drops are multiplied by Fortune, then transferred directly into inventory.

However, mining other blocks such as Iron and Redstone Ore results in the block breaking without any drop, neither in-world nor in the inventory.

In the title, I assume that this is because of the Collection Enchantment, and this is only because I've tried tools with all other enchantments, and this issue hasn't appeared; I have in fact performed no proper, rigorous testing. Also, I haven't tried all ore blocks, only the ones mentioned in this description.

### Reproduction Steps

1. Make Pickaxe with aforementioned enchants, possibly even with only Collection
2. Attempt breaking various Ore blocks
3. Profit... or not

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/134404551/c749c884-efe0-4953-ad2e-732647372a83)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 17.5 Fabric for Minecraft 1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
Report to the devs of Charm
