### ISSUE TITLE
Vanilla Recipe Search Not Working

### ISSUE THREAD

**Issue by sXdeha** [LunaPixelStudios/Better-MC#1230]
### Describe the Bug

When i type something to search bar, it shows nothing.

### Reproduction Steps

1 .Open inventory
2. Type anything to search bar
3. It shows nothing.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/134428123/ede0a2a6-5683-44a7-a406-c750f892727b)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v1

### Optifine

I used Optifine

### Other Mods

modernfix

**Comment by chorbintime** [comment]
You can't craft a hopper in your inventory crafting. You'd need to search while in a crafting table.

V1 is very old. Please update the modpack to the latest version.

You should just use the REI mod anyway, its already in the modpack. Read the quests in the questbook for more information.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
