### ISSUE TITLE
Missing texture when digging dirt blocks.

### ISSUE THREAD

**Issue by gonnerINC** [LunaPixelStudios/Better-MC#1233]
Hi there. When I dig dirt blocks the particles coming off of the block while digging and when it is done being dug have the purple and black missing texture on them. I am running the Better Minecraft Forge mod pack for 1.19.2.

![B4A20B62-25BE-4DE9-BAFD-E6021D00F713](https://github.com/LunaPixelStudios/Better-MC/assets/134878961/5815c27a-1c3d-4b97-bf55-0ffc0664ac38)
![691C6A4B-9E7E-4D08-BA29-1022578CAD45](https://github.com/LunaPixelStudios/Better-MC/assets/134878961/4ab268fa-7030-4ddd-a60b-78a52cbe9788)
![153485F5-0000-47C9-A489-EC10EB5E8366](https://github.com/LunaPixelStudios/Better-MC/assets/134878961/ef5a60a0-938a-4f4e-8eb2-65a3292ea62a)

**Comment by chorbintime** [comment]
Try reloading textures
