### ISSUE TITLE
llegalStateException that occurred when LegacyRandomSource was accessed from multiple threads

### ISSUE THREAD

**Issue by jaynotgay** [LunaPixelStudios/Better-MC#1234]
### Describe the Bug

llegalStateException that occurred when LegacyRandomSource was accessed from multiple threads.
LegacyRandomSource class seems to be designed for single-threaded use only, and any attempt to use it from multiple threads will trigger the IllegalStateException.

### Reproduction Steps

Server is active with playercounts from 10-30 players online and the crash can happen at a random time. Will happen at least once per day.

### Screenshots and Videos

https://mclo.gs/11cIskW

### Operating System

ubuntu 20

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v17.5

### Optifine

I used Optifine

### Other Mods

customearnings - private mod
mceconomy - private mod
playershops - private mod
auctions - private mod
essential_commands-0.30.0-mc1.19.2
ftb-ranks-fabric-1902.1.14-build.70
holograms-1.4.0+1.19.2
LuckPerms-Fabric-5.4.46
LuckPerms-Fabric-PlaceholderAPI-Hook
Multiworld-Fabric-1.6
servercore-1.3.3-1.19.2
lithium-fabric-mc1.19.2-0.11.1
styled-chat-2.0.3+1.19.2
styled-nicknames-1.1.2+1.19
votifierrenewed-19.1.0
worldedit-mod-7.2.12
Chunky-1.3.38
kits-1.5.0-v2-mc1.19.2
observable-3.3.1

**Comment by chorbintime** [comment]
update to v18
