### ISSUE TITLE
Error occurred during initialization of boot layer

### ISSUE THREAD

**Issue by Thiteago** [LunaPixelStudios/Better-MC#1235]
### Describe the Bug

Describe the Bug
Error during the installation of the modded forge server.

> Starting server...
> 
> Minecraft version: 1.19.2
> Modloader:         Forge
> Modloader version: 43.2.8
> 
> Java args:
> Java path:         java
> Run Command:       java -Dlog4j2.formatMsgNoLookups=true @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.2.8/unix_args.txt nogui
> Java version:
> openjdk version "18.0.2.1" 2022-08-18
> OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
> OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
> 
> Error occurred during initialization of boot layer
> java.nio.file.InvalidPathException: Illegal char <:> at index 70: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar:libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar:libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar:libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar:libraries/org/ow2/asm/asm/9.3/asm-9.3.jar:libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar
> 

Reproduction Steps
...

Screenshots and Videos
![image](https://github.com/LunaPixelStudios/Better-MC/assets/42258486/3a6c6bf7-b836-45d5-a4ce-ec8fe7afe31a)

Crash Report or Log
No response

Operating System
Windows 11

Minecraft Version
1.19.2

Modloader
Forge

Modpack Version
1.19.2 v13

Optifine
No

Other Mods
No response

### Reproduction Steps

1. Downloaded the ServerPack on curseforge
2. Extract folder from zip file
3. run start.sh

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] - BMC3 V14

### Optifine

No

**Comment by chorbintime** [comment]
You need to use the start.ps1 windows powershell file on Windows. Not the start.sh
