### ISSUE TITLE
Geophilic Filename Issue

### ISSUE THREAD

**Issue by Shinku443** [LunaPixelStudios/Better-MC#1236]
### Describe the Bug

Spinning up a new instance given the latest update I'm running into this issue. (Previous version worked fine)

Better MC Server Pack FABRIC 1.19.2/mods/geophilic‐1.19-2.0.0b.jar:  mismatching "local" filename (Better MC Server Pack FABRIC 1.19.2/mods/geophilicтАР1.19-2.0.0b.jar),
         continuing with "central" filename version

### Reproduction Steps

1.
2.
3.
...

### Operating System

Ubuntu Server (Docker)

### Minecraft Version

1.12

### Modloader

Fabric

### Modpack Version

18

### Optifine

No

**Comment by chorbintime** [comment]
report to geophilic devs

**Comment by SHXRKIIE** [comment]
THis only happens when zipping the file, unzipping shouldnt cause this, so what are you doing?
