### ISSUE TITLE
Crashing error on mac-os

### ISSUE THREAD

**Issue by RomeroSR** [LunaPixelStudios/Better-MC#1237]
### Describe the Bug

When I load up better minecraft fabric it crashes within 5 minutes of playing

### Reproduction Steps

1.
2.
3.
...

### Operating System

Mac os

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
You need to attach logs for us to help you
