### ISSUE TITLE
Fabric seasons mod is calling a method that does not exist. The specific error java.lang.NoSuchMethodError causing the server to crash in v18

### ISSUE THREAD

**Issue by jaynotgay** [LunaPixelStudios/Better-MC#1239]
### Describe the Bug

exception occurs when the mod is calling a method that does not exist. The specific error java.lang.NoSuchMethodError

getCurrentSeason() method cannot be found in the FabricSeasons class in the io.github.lucaargolo.seasons package

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://mclo.gs/rWTnHbZ

### Crash Report or Log

https://mclo.gs/rWTnHbZ

### Operating System

ubuntu 22

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v18

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Remove Seasons Exxtras Mod, will do a  hotfix removing it
