### ISSUE TITLE
Ender Dragon not spawning 

### ISSUE THREAD

**Issue by aisakastick** [LunaPixelStudios/Better-MC#1240]
### Describe the Bug

Me and other player entered end and saw a healthbar and heard the dragon but he was not there, Deleting the DIM1 folder yeilds same result

### Reproduction Steps

1. Complete portal
2. Go in
3. No dragon
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v14

### Optifine

I used Optifine

### Other Mods

no

**Comment by chorbintime** [comment]
it does spawn, you might need to remove the no see no tick mod though.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
