### ISSUE TITLE
Crash when put a skeleton head

### ISSUE THREAD

**Issue by MathIS2I** [LunaPixelStudios/Better-MC#1241]
### Describe the Bug

When I put a skeleton head my game crashed immediately, when I try to reopen the world it crashes again.

### Reproduction Steps

1.Put a skeleton head
2.The word will crash
3.Try enter again 

### Crash Report or Log

Don't have

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v13.5

### Optifine

I used Optifine

### Other Mods

apple skin, medieval craft and medieval craft (weapons)

**Comment by SHXRKIIE** [comment]
need crash report or log
