### ISSUE TITLE
Video crashes but audio continues work, game doesnt fully crash but is unresponsive.

### ISSUE THREAD

**Issue by 0xRivz** [LunaPixelStudios/Better-MC#1242]
### Describe the Bug

I have not been able to pin point what causes the crash, usually it is when exploring new areas with friends. my game will freeze visually but i can still hear people and the world around me. the game still recognizes my input as my friends can see me moving around when i ask but it forces me to tab out and then completely breaks when i do that, it switches to showing the menu but its flashing and nothing responds. game completely bricks at this point and requires a re-launch.

### Reproduction Steps

1.
2.
3.
...
unsure on how to reproduce, happens at different areas in different situations.

### Crash Report or Log

https://paste.atlauncher.com/view/73bc4b96-412e-4230-96f4-290b95403600

### Operating System

Windows 10 via Bootcamp on Macbook Pro

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc3 v14

### Optifine

I used Optifine

### Other Mods

none

**Comment by chorbintime** [comment]
Make a new issue if this persists on v15 when its released.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
