### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by meralester** [LunaPixelStudios/Better-MC#1243]
### Describe the Bug

cant open

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

060a42cb7221affbcf252931dea81395cacfadbd

### Operating System

windows10

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Please send the crash report. You just sent a line of random characters.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.

**Comment by Spvceart** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/11706330/latest.log)

Latest log for no audio

**Comment by chorbintime** [comment]
what does that have to do with the issue posted

**Comment by Spvceart** [comment]
wrong thread sorry
