### ISSUE TITLE
SE MAL RENDERIZADO ALGUNAS TEXTURAS

### ISSUE THREAD

**Issue by Jakedj16** [LunaPixelStudios/Better-MC#1244]
### Describe the Bug

En el minimapa, y dentro del menú de fabricación o del inventario... algunas texturas se pierden o se ven mal.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

<img width="976" alt="Captura de Pantalla 2023-06-02 a la(s) 09 54 32" src="https://github.com/LunaPixelStudios/Better-MC/assets/135355034/fa196ecc-2725-47c8-8b66-55c7ca984f49">
<img width="2560" alt="Captura de Pantalla 2023-06-02 a la(s) 09 54 27" src="https://github.com/LunaPixelStudios/Better-MC/assets/135355034/deb08837-83a4-49d7-92ec-e0b9bf8dc547">

### Operating System

MAC Os Monterrey

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

https://www.curseforge.com/minecraft/modpacks/better-mc-fabric

### Optifine

I used Optifine

**Comment by Jakedj16** [comment]
SOMEBODY CAN HELP ME?

**Comment by chorbintime** [comment]
Update your drivers.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
