### ISSUE TITLE
Entities Popping In and Out of Player View

### ISSUE THREAD

**Issue by EliteCheemus** [LunaPixelStudios/Better-MC#1245]
### Describe the Bug

Hi! This is my first bug report on here, so please excuse me if I'm missing anything you need. This has been an issue that has risen since Forge v12-v14. Entities are not rendering past a certain point. v11 was the last version this didn't occur, we thought we narrowed it down to Rubidium Extras had a setting that fixed it on v12 - but when going onto v14, it does not fix it. 

### Reproduction Steps

1. Load into any world, best to get into the end with the Ender Dragon
2. Ender Dragon will not appear unless you are within viewing distance for the entity
3. Go to v11, and this issue will not persist
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

No

**Comment by chorbintime** [comment]
This is an intended optimization done by the No See No Tick mod

**Comment by EliteCheez99** [comment]
> This is an intended optimization done by the No See No Tick mod

Thank you, we will look into this today 🙂
