### ISSUE TITLE
Vinery staw hat is invisible

### ISSUE THREAD

**Issue by Pirateghost777** [LunaPixelStudios/Better-MC#1246]
### Describe the Bug

The straw hat from vinery is invisible when worn or on an armor stand.

### Reproduction Steps

1. Place hat on self or armor stand

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/8490fc73-995d-4904-a649-aa71f2c1f890)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/82976588-1538-4f14-9950-a7d0de0f858e)

### Operating System

Windowns 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v15

### Optifine

No

**Comment by chorbintime** [comment]
Report to Vinery dev
