### ISSUE TITLE
Empty Tags

### ISSUE THREAD

**Issue by Pirateghost777** [LunaPixelStudios/Better-MC#1247]
### Describe the Bug

Some items have named icons resembling barrier blocks as crafting ingredients.

### Reproduction Steps

1. open jei search
2. choose winebox
3. search for the item that looks like a no symbol by clicking it

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/09bf65ff-9196-496c-8d3f-f898342d66b9)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/01754bfa-46c8-4f7d-b5b5-646677d31ab3)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/0dce30c6-819d-4b3e-9b9e-f4e90f88b4e4)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/b810d3cd-97bb-42a7-8d4c-b1443f6a145e)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/83dc5a08-80c3-4c57-8ede-78d2f01d0149)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/76c67567-b736-4b28-9f84-30508b43ce0e)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/6a3df511-1e7b-4ca5-b7ca-4275da669788)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/8515a0eb-9663-4e32-accf-bf19a05151d6)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/e34295f7-49dd-42bf-8047-f9d22a6c48c6)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/16c6ad5b-d31f-48ef-bf27-591c6136f22b)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/21a9686d-79eb-40fe-ae93-02ccc01df3e4)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/127156374/c291dcb2-c1bc-444d-abb2-8164a910426f)

### Operating System

Windowns 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v15

### Optifine

No

**Comment by chorbintime** [comment]
Report to the developers of the mods that add those items.
