### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Xhrysanthemum** [LunaPixelStudios/Better-MC#1248]
Fun pack but for some reason does register sounds such as doors closing or chest opening sometimes you cant hear anything

**Comment by chorbintime** [comment]
To reload textures and sounds, press F3 + T. If this doesn't bring up a loading screen, do the following:
1. Press escape and go to the Resourcepacks tab.
2. Move a Resourcepack on the left of the screen to the right. 
3. Move that SAME Resourcepack back to the left. 
4. Exit the menu. 
If step 4 does not bring up a loading screen, do step 2, then step 4, then step 3, and then step 4 again.
