### ISSUE TITLE
"Singleplayer" & "Multiplayer" buttons missing

### ISSUE THREAD

**Issue by TGee001** [LunaPixelStudios/Better-MC#1249]
### Describe the Bug

Simply put, I updated from v14 to v15 and the single player and multiplayer buttons are just gone! I reinstalled it multiple times and no luck.

### Screenshots and Videos

![Capture](https://github.com/LunaPixelStudios/Better-MC/assets/135569814/2751a62f-8211-47d0-9509-587789cec1f4)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
You either:
1. Did not install the modpack correctly
2. Are using TLauncher
3. Added the Essential mod to your mods folder

Please reinstall the modpack using ATLauncher, and do not modify the modpack in any way.

**Comment by TGee001** [comment]
OK, thank you!
