### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by MrSnwMan** [LunaPixelStudios/Better-MC#1250]
### Describe the Bug

audio is fine in main menu but when you load up a world you cant hear anything 

### Reproduction Steps

1. boot   minecraft 
2. create world 
3. load world 
4. break blocks 

### Crash Report or Log

n/a

### Operating System

windows 11 pro

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v15

### Optifine

No

**Comment by chorbintime** [comment]
Send your latest.log from the logs folder when your audio cuts out

**Comment by Spvceart** [comment]
I also have this bug, its a hit or miss on the audio sometimes it works but most of the time it does not. The only audio that 100% works is the minecraft music. The bug automatically happens just by starting up the modpack.

**Comment by chorbintime** [comment]
> I also have this bug, its a hit or miss on the audio sometimes it works but most of the time it does not. The only audio that 100% works is the minecraft music. The bug automatically happens just by starting up the modpack.

Send your latest.log from the logs folder when your audio cuts out

**Comment by nclpapio** [comment]
I too have same issues

boot minecraft
create world
load world
break blocks
pickup items
hitting mobs
mob sounds etc

**Comment by soluseity** [comment]
This bug seems to be a problem with the directional audio setting in audio settings, if I start the game, there is no sound, and if I flip the switch for the directional audio then start it up again I have audio. It does not seem to matter if the directional audio is on or off, because I just have to switch it to the opposite of whatever the setting is and restart.

**Comment by chorbintime** [comment]
Send your latest.log from the logs folder when your audio cuts out. 

Please. 

I can not help you without it. I don't know how you expect us to do anything if you aren't going to follow directions

**Comment by MrSnwMan** [comment]
Sorry I got it fixed in the discord but I have been at working and don’t get to go home daily so I can’t send the logs but it is in the discord if you search my name MrSnwMan

**Comment by nclpapio** [comment]
> Sorry I got it fixed in the discord but I have been at working and don’t get to go home daily so I can’t send the logs but it is in the discord if you search my name MrSnwMan

may I ask what their discord server is?

**Comment by MrSnwMan** [comment]
Luna pixel studios

**Comment by Spvceart** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/11712192/latest.log)

Log for audio bug

**Comment by chorbintime** [comment]
To reload textures and sounds, press F3 + T. If this doesn't bring up a loading screen, do the following:
1. Press escape and go to the Resourcepacks tab.
2. Move a Resourcepack on the left of the screen to the right. 
3. Move that SAME Resourcepack back to the left. 
4. Exit the menu. 
If step 4 does not bring up a loading screen, do step 2, then step 4, then step 3, and then step 4 again.
