### ISSUE TITLE
Ice doesn't melt outside of winter

### ISSUE THREAD

**Issue by Peerius1701** [LunaPixelStudios/Better-MC#1251]
### Describe the Bug

During the season winter, ice starts to generate for example in rivers. However, as said in the title, it appears that the ice doesn't melt during other seasons. This issue occured both on a server and in singleplayer. I also looked at the config files for fabric seasons and immersive weathering but didn't find a configuration which would explain this behavior.

Would love to see this issue being removed, ty in advance :)

### Reproduction Steps

1. Let ice generate in winter
2. Switch season
3. Nothing happens

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v18.5

### Optifine

I used Optifine

### Other Mods

I added chipped

**Comment by chorbintime** [comment]
Report to Serene Seasons dev

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
