### ISSUE TITLE
Block data not saving

### ISSUE THREAD

**Issue by sebbbbbbbbbbbb** [LunaPixelStudios/Better-MC#1253]
### Describe the Bug

When i place down blocks and leave and rejoin the blocks are no longer there

### Reproduction Steps

1.
2.
3.
...

### Operating System

Macbook air 2020

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v8.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
v8.5 is very old. We offer no support for old versions.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
