### ISSUE TITLE
Error with Architectury Modloading

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-MC#1254]
### Describe the Bug

I attempted to boot up my game and i was given this error. It says that Architectury is causing the issue but the thing was that i was able to play it before.

### Reproduction Steps

Unknown how to reproduce this

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/106572267/b4823846-e70a-43e1-ba55-3fc60b49d104)

### Crash Report or Log

https://pastebin.com/vy73dk4P

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

**Comment by FevilGitHub** [comment]
EDITS: This seems to be an occasional error, and yes i have Allocated RAM to the launcher (up to 10GB for extra protection), so im not too sure why this would happen.

**Comment by chorbintime** [comment]
What launcher are you using, and how did you install the modpack?
