### ISSUE TITLE
Level 4 beacon

### ISSUE THREAD

**Issue by Karlztv** [LunaPixelStudios/Better-MC#1255]
### Describe the Bug

Cant open my terminal even tho I have a level 4 beacon

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better minecraft

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Report to Tom's Simple Storage devs.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
