### ISSUE TITLE
Exit Code 1 - please help

### ISSUE THREAD

**Issue by SleepyRaine** [LunaPixelStudios/Better-MC#1257]
### Describe the Bug

Ever time I try to launch forge better mc it always gives me exit code 1 but fabric works fine. I've tried reinstalling the mod pack , java, and minecraft but I keep getting the same code.  I have no idea how to fix.  Any kind of help will be apricated. 

### Reproduction Steps

1

### Crash Report or Log

<script src="https://gist.github.com/SleepyRaine/0a18f3264a283e61f5ffc762b679e882.js"></script>

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC - Forge BMC 3 

### Optifine

No

**Comment by Frontear** [comment]
You have not uploaded that crash report correctly. Please re-upload it as a file.

**Comment by SleepyRaine** [comment]
[https://gist.github.com/SleepyRaine/0a18f3264a283e61f5ffc762b679e882](url)

Here is a link to the report it gave me

**Comment by Frontear** [comment]
Update your AMD Drivers, or follow this guide if that doesn't work:

1. Download a pre-built GLFW library from my repository at https://github.com/Frontear/glfw/releases. Ensure you download the correct file from the desription of the release. You may also compile it yourself, details can be found here: https://www.glfw.org/docs/latest/compile.html
2. Save the file in a location you can remember and will NOT delete (the file MUST stay there or else it will stop working)
3. In your launcher, go to the java parameters (this is the place you put your GC arguments), and add -Dorg.lwjgl.glfw.libname="path/to/the/file". If, for example, you downloaded the file in your Downloads (C:\Users\Me\Downloads\glfw3.dll, then your argument would be -Dorg.lwjgl.glfw.libname="C:\Users\Me\Downloads\glfw3.dll")

If neither of these help please join our discord and ask for help in \#better-mc-forge
