### ISSUE TITLE
Screen ( grapic only ) freeze

### ISSUE THREAD

**Issue by Darlf** [LunaPixelStudios/Better-MC#1258]
### Describe the Bug

my game freezes for no reason after running around the world for a while, but only the graphics, I can still use my character, mine blocks, hear sounds and the game progress is saved after the reset, in addition, after minimizing the game and trying to open it again, the screen flickers in about 1 second intervals alternately showing a stuck image from the game and a black background, interestingly, this problem also occurred on the Fabric version of the pack. yes i try many grpahic options . Do somone have somthing like that and do is imposible to repiar if your pc just dont like this modpack ? 

### Reproduction Steps

1. open the game
2. run world
3.walk for moment
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

mc3Forge mc1Fabric

### Optifine

No

**Comment by chorbintime** [comment]
please follow the performance guide linked on the main menu

**Comment by Darlf** [comment]
> please follow the performance guide linked on the main menu

what link and where ? main menu of what  ?

**Comment by Darlf** [comment]
Nothing work, and meyby not close question if, person who have question not say yes is work ? Alos is be fater for me is you give that link or say is here on Wiki files... Anyway, nothing wrok, low graphic setting, Of dynamic light, test whne all not modpack mods are delete, update windows intel ect, nothing, this game  just want i not play this modpack, sadly i do sotmign form somone  and i need test this and some mods and instal it all on server but i cant if my game random freez but only my, players who want this have normal work better  mc ...

**Comment by chorbintime** [comment]
sounds like an issue with your PC
