### ISSUE TITLE
frost walker

### ISSUE THREAD

**Issue by comfycassidy** [LunaPixelStudios/Better-MC#1259]
### Describe the Bug

I cannot put frost walker on any boots, enchanted or not, I try to put them in an anvil and it just shows a red X, I have boots and a frost walker book.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/136118733/ed857b14-62f8-4cb2-992c-0ced874078f2)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v17.5 HF.zip

### Optifine

No

**Comment by chorbintime** [comment]
update the modpack, we offer no support for old versions
