### ISSUE TITLE
game Freeze 

### ISSUE THREAD

**Issue by Darlf** [LunaPixelStudios/Better-MC#1260]
### Describe the Bug

my game freezes for no reason after running around the world for a while, but only the graphics, I can still use my character, mine blocks, hear sounds and the game progress is saved after the reset, in addition, after minimizing the game and trying to open it again, the screen flickers in about 1 second intervals alternately showing a stuck image from the game and a black background, interestingly, this problem also occurred on the Fabric version of the pack. yes i try many grpahic options . Do somone have somthing like that and do is imposible to repiar if your pc just dont like this modpack ?

for this one very nice person who say just random thing and cloused this last time, meyby wait to person who do question to tell is work ?? Alos say where is link like i need find it bcs mein menu of what ?. And no Guild https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide  not help, low grapic, update win 11 intel ect, do OFF dynamic light, try whne all no pack mods are off.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC BMC3 ( alos fabric)

### Optifine

No

**Comment by Darlf** [comment]
Steam Systme Info

Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  VivoBook_ASUSLaptop X515JAB_X515JA
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    CPU Family:  0x6
    CPU Model:  0x7e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  1190 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Supported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Supported
    AVX512VNNI:  Supported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 11 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  Intel(R) UHD Graphics
    DirectX Driver Name:  igdumdim32.dll
    Driver Version:  31.0.101.2121
    DirectX Driver Version:  31.0.101.2121
    Driver Date: 3 3 2023
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 59 Hz
    DirectX Card: Intel(R) UHD Graphics
    VendorID:  0x8086
    DeviceID:  0x8a56
    Revision:  0x7
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.64" (15.51" diag)
                                            34.4cm x 19.4cm (39.4cm diag)
    Primary Bus Type Not Detected
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Głośniki (Realtek(R) Audio)

Memory:
    RAM:  7930 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  Undetermined
    Total Hard Disk Space Available:  242620 MB
    Largest Free Hard Disk Block:  18286 MB
    OS Install Date: mar 31 2023
    Game Controller: None detected
    MAC Address hash: abb465c18b2892bbdc9d6cf8ffdc94b9579b1aa9

Storage:
    Disk serial number hash: fd311e36
    Number of SSDs: 0
    Number of HDDs: 0

**Comment by chorbintime** [comment]
update your drivers. probably a PC issue though

**Comment by Darlf** [comment]
> update your drivers. probably a PC issue though

i have all update like meyby is just a new windows... but if i need wait for devs repair it -_-
