### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by lellopello** [LunaPixelStudios/Better-MC#1263]
### Describe the Bug

when i download it and i use it, it doesen't work and say me nothing like that is not installed

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2

### Optifine

No

**Comment by chorbintime** [comment]
you probably installed the modpack incorrectly, use ATLauncher

i cant really help you without any logs
