### ISSUE TITLE
Ice does not melt outside of winter

### ISSUE THREAD

**Issue by orosmatthew** [LunaPixelStudios/Better-MC#1264]
### Describe the Bug

When the season changes to winter, rivers turn into ice but once it turns spring/summer/fall, the ice never melts

### Reproduction Steps

1. Wait for winter for water to freeze
2. Wait for Spring and Summer, the ice does not melt

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v18.5

### Optifine

No

**Comment by chorbintime** [comment]
report to the devs of Fabric Seasons
