### ISSUE TITLE
Audio cuts out

### ISSUE THREAD

**Issue by MrCloss** [LunaPixelStudios/Better-MC#1266]
### Describe the Bug

First time running the modpack I had audio, but anytime that I opened it after I'd only hear some of the mob's noises and the main menu music. No button pressing in the menu, damage noise, or anything else

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc 3

### Optifine

No

**Comment by chorbintime** [comment]
Send your latest.log when audio cuts out

**Comment by Armsman1** [comment]
I have one for you.  Exact same issue I'm experiencing. That last entries of when I logged in should be sufficient.
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/11811040/latest.log)

Let me know if you need anything else.

**Comment by chorbintime** [comment]
To reload textures and sounds, press F3 + T. If this doesn't bring up a loading screen, do the following:
**1**. Press escape and go to the Resourcepacks tab.
**2**. Move a Resourcepack on the left of the screen to the right. 
**3**. Move that SAME Resourcepack back to the left. 
**4**. Exit the menu. 
If step 4 does not bring up a loading screen, do step 2, then step 4, then step 3, and then step 4 again.
