### ISSUE TITLE
Game freezing after several minutes

### ISSUE THREAD

**Issue by LazyTimeTV** [LunaPixelStudios/Better-MC#1267]
### Describe the Bug

Hi, my game is freezing on both the main menu and in a server after a few minutes of playing. I can hear things happening and my friends can see me moving but my screen is frozen and if I open a separate window it will open the pause menu and flicker on a 1 second interval. When the game is working, I get 45-60fps. I have updated my computer and my drivers, am running on 1.19.2 and have allocated enough RAM (5GB) for the modpack. There is very little info about this online. One of my friends is running this modpack on the same setup as I am and hasn't had any issues.

### Reproduction Steps

1. Launch game through ATLauncher.
2. Wait.
3.
...

### Crash Report or Log

Unfortunately no crash log is generated

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 v15

### Optifine

No

### Other Mods

Mekanism
Mekanism: Generators
Mekanism: Tools
Mekanism: Additions
MoreVanillaLib
SimplyTools
LibX

**Comment by LazyTimeTV** [comment]
I do have the ATLauncher console log but I couldn't find anything that could help: [Here.](https://paste.atlauncher.com/view/4e2dc62a-051f-4abc-8324-29699d93eccd?fbclid=IwAR0P6ohsx1C5ZRMU2JRSYi-z9WVCIocTdCdYsZ8S0tk0BJhoRJ8RYvPflp8)

**Comment by chorbintime** [comment]
Please follow the full performance guide that is linked on the main menu
