### ISSUE TITLE
ony modded audio is working

### ISSUE THREAD

**Issue by xXSP4RKL3D0GXx** [LunaPixelStudios/Better-MC#1268]
### Describe the Bug

the defult minecraft audio has no sound (blocks breaking, doors, ect) but any audio that is only in mods works just fine. Ive checked the settings and everything is at 100. Im not having this issue with any other mods of with normal minecraft.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
Send your latest.log when audio cuts out

**Comment by xXSP4RKL3D0GXx** [comment]
the audio dosnt cut out it just dosnt work from the start. if im breaking blocks like grass there is no sound but if im breaking somthing that was added by a mod the sound works.

**Comment by xXSP4RKL3D0GXx** [comment]
https://youtu.be/IzJvXmKejCk the video was to big to post on here

**Comment by chorbintime** [comment]
Please send your latest.log when a sound that is supposed to play does not play

**Comment by xXSP4RKL3D0GXx** [comment]
what is a log? (sorry if this is really dumb)

**Comment by JaHLoVe927** [comment]
The same issue is also happening to me; I'm not sure what happened, but after playing the mod for an hour, only mod-added items and mobs have working audio.

**Comment by JaHLoVe927** [comment]
I just restarted my game and opened the appropriate version; I believe I had been using the fabric version rather than the forge. @xXSP4RKL3D0GXx, try starting the game using the appropriate curse forge or other mod-launching software and selecting the right version.

**Comment by xXSP4RKL3D0GXx** [comment]
im pretty sure I have the right version. I downloaded the forge version and am launching it through curesforge. here is a screenshot of it if it helps
![dfghdkhg](https://github.com/LunaPixelStudios/Better-MC/assets/136692279/62b3dcdb-420e-46d9-8254-0888e694ed20)

**Comment by ItsNeoOfficial** [comment]
Has anyone found a fix

**Comment by xXSP4RKL3D0GXx** [comment]
not as far as im aware

**Comment by chorbintime** [comment]
> Has anyone found a fix



> not as far as im aware

Please read the rest of the thread before reviving it. I asked for logs, and neither of you sent any.

A permanent fix is to switch to ATLauncher instead of Curseforge.

A temporary fix is to use f3 + t to reload textures.
