### ISSUE TITLE
solo and multiplayer button 

### ISSUE THREAD

**Issue by ImJustKaZe** [LunaPixelStudios/Better-MC#1269]
### Describe the Bug

hello i dont have the solo and multiplayer button to play with better mc 1.19.2 how can i have these buttons.
i just downloaded the mods and place it in my mods folder and it doesnt work. 
(Sorry for my bad English I'm french).

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Base Profile Screenshot 2023 06 15 - 18 56 36 37](https://github.com/LunaPixelStudios/Better-MC/assets/136737269/85773971-bbf1-4be8-9c75-a4432c4e3aee)

### Operating System

windows11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc3

### Optifine

No

**Comment by chorbintime** [comment]
You need to use a modded launcher such as Curseforge Launcher to install & play modpacks.
