### ISSUE TITLE
Singleplayer and Multiplayer isn't showing up when started

### ISSUE THREAD

**Issue by BeeToHorny** [LunaPixelStudios/Better-MC#1270]
### Describe the Bug

Singleplayer and Multiplayer isn't showing up on the Homescreen of BMC 3 when started with essential mod to play with a friend, please help!

### Reproduction Steps

1. Download BMC 3 (Forge) in the ATLauncher
2. Add the Essential Mod to the Modpack
3. Run the Instance
...

### Screenshots and Videos

-

### Operating System

Windows 10 & 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v1...

### Optifine

I used Optifine

### Other Mods

-

**Comment by luke8698** [comment]
same issue

**Comment by chorbintime** [comment]
This is not an issue. Essential is incompatible with all of our modpacks. Selfhost a server using the serverpack on the modpack's Curseforge page if you want a free server.
