### ISSUE TITLE
Bug when launching world

### ISSUE THREAD

**Issue by aramestu** [LunaPixelStudios/Better-MC#1272]
### Describe the Bug

Hello,
the past month, i start a server with friend and use the modpack Better-MC BMC1. I got no problem but i stoped the server because nobody play anymore and now when i try to re-installed the server, i got the error that i send you in the screenshoot. I got it too when i just try to load a new world. I'm not a expert on server's configuration so maybe i just a dumb problem.

### Reproduction Steps

1. launch the server (Bisect Hosting)
2. launch my game and connect to the world
3. get the error
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/92510285/e28c0dde-b7ee-4cd8-b4e4-b6ed66397b5e)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC - BMC1 - 1.19.2 FABRIC 18.5

### Optifine

No

**Comment by chorbintime** [comment]
you dont have the same modpack installed as the server
