### ISSUE TITLE
Better MC BMC3 Exit Code 1

### ISSUE THREAD

**Issue by velocitytime56** [LunaPixelStudios/Better-MC#1273]
### Describe the Bug

I have a bunch of friends playing a server with the BMC3 mod pack. None of them had any issues. Every time I try to launch BMC3, the game crashes and says "Exit Code 1". I've tried uninstalling both the mod pack and CurseForge multiple times just to get the same result every time. I've tried 1 other mod pack, BMC1, and I never got this error message.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/velocitytime56/c3697ed4f2689e06e3c27e47aec8e051

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 v15.zip

### Optifine

I used Optifine

**Comment by velocitytime56** [comment]
It's supposed to say 1.19, not 1.16

**Comment by Yamired** [comment]
I have the exact same issue, game version 1.19.2, no extra content and Exit Code 1 after trying to start the game from the launcher.
[hs_err_pid4284.log](https://github.com/LunaPixelStudios/Better-MC/files/11837210/hs_err_pid4284.log)

**Comment by SHXRKIIE** [comment]
Not enough ram allocated. Its crashing due to java running out of memory

**Comment by velocitytime56** [comment]
I appreciate the response, but I've tried changing allocated RAM in both the Minecraft Launcher and in CurseForge Profile Options. Neither of those seemed to change anything. I'm starting to think my computer is just too old, as I had planned to get a new one some time this summer. But if I missed something, feel free to let me know as always and thanks again.

**Comment by chorbintime** [comment]
Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed. 



> I have the exact same issue, game version 1.19.2, no extra content and Exit Code 1 after trying to start the game from the launcher. [hs_err_pid4284.log](https://github.com/LunaPixelStudios/Better-MC/files/11837210/hs_err_pid4284.log)

Please do not hijack a post with a completely unrelated issue. You have outdated GPU drivers. Update them manually from your vendor's website.
