### ISSUE TITLE
Crashing after traveling the world really fast.

### ISSUE THREAD

**Issue by TheSuppaOnion** [LunaPixelStudios/Better-MC#1274]
### Describe the Bug

After some time of traveling my world either in creative, Elytras or with my dragon, I get consistent crashes, tried to see in afterburner and in task manager how much ram was being used, and found out that I was using over 30GB of RAM despite me allocating only 8GB to minecraft (see picture below), this has been happening to me after quite some time all of the crash logs has been the same EXCEPTION_ACCESS_VIOLATION or out of memory error.

I have already tried the performance guide, using ATLauncher, reinstalling my GPU drivers witth DDU, installed Java 18 instead of 17 using the Adoptium OpenJDK, updated my OS (also runing sfc and DISM on powershell to check files integrity), uninstalled minecraft completely and reinstalled with the mod pack using the recommended launcher.

I'm truly lost here tried everything I can and think of but with no success, also I'm running the server pack on the same computer too hosting to my friends, but I'm the only one constantly crashing while exploring our world, but the picture I uploaded it's with the server closed.

My Specs:
RTX 3070 TI - Driver 536.23
Ryzen 7 5800X3D
64 GB RAM - 3200MHz
1TB SSD Gen 3 (Where minecraft is installed)
Windows 11 22H2 Build 22621.1848

### Reproduction Steps

1. Load any world.
2. Use Elytras or creative.
3. Travel really fast through the world.
4. After some time flying around, the game will use more and more RAM.
...

### Screenshots and Videos

![Better Minecraft  FORGE  1 19 2 6_19_2023 10_02_59 AM](https://github.com/LunaPixelStudios/Better-MC/assets/51060446/196b6695-0e95-4a94-88a2-14f0198abfac)

### Crash Report or Log

https://gist.github.com/TheSuppaOnion/dfd73718727075b642a5b895210bcd9e

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 V15

### Optifine

No

### Other Mods

Just added Complementary Shaders Reimagined.

**Comment by TheSuppaOnion** [comment]
I'll try to add this mod and see if it helps, thanks.

**Comment by TheSuppaOnion** [comment]
https://gist.github.com/TheSuppaOnion/eb25f6417739cb6ccd0b2f3cdfcca3c4

For what I can see using shaders makes matters worse.

**Comment by TheSuppaOnion** [comment]
The memory leak fix mod did helped improving RAM usage on a 5hr session today, got no crashes thanks for the mod, but can still get high memory usage while traveling my world suing elytras.

**Comment by SHXRKIIE** [comment]
Yes you will crash if you travel for long distances constantly for hours of gameplay because you are simply generating soo many chunks over a long period of time. Restarting your game will fix the memory issue.
