### ISSUE TITLE
Better Minecraft Fabric 1.20

### ISSUE THREAD

**Issue by Yosthj** [LunaPixelStudios/Better-MC#1275]
Hello - I noticed a new modpack was created for Better Minecraft Fabric 1.20. I use BMC1 Fabric on a gportal server. Gportal has tested BMC2 Fabric and says I can easily change the server to that modpack. However, curseforge will require a new modpack, since BMC2 is an entirely separate modpack. (rather than simply updating BMC1).  I'm afraid this will require us to create a new world and lose everything. How can I update curseforge and gportal without us losing our world and maps?

**Comment by chorbintime** [comment]
Do not reuse your BMC1 world on BMC2. You will be missing many blocks and items. I would suggest waiting a few months first. All you would need to do is transfer your world folder.
