### ISSUE TITLE
theres no audio for footsteps or for breaking blocks or placing them  

### ISSUE THREAD

**Issue by Lemmiewemmie75** [LunaPixelStudios/Better-MC#1278]
### Describe the Bug

theres just no audio i have the volume sliders for everything up to 100% but cant hear anything idk whats wrong

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

I used Optifine

**Comment by Erixon1012** [comment]
Having the same issue. Just downloaded through curseforge. Can still hear the sounds of parrots for some reason.

**Comment by SHXRKIIE** [comment]
To reload textures and sounds, press F3 + T. If issue persists try out ATLauncher instead as Curseforge Launcher is just shit and causes these kinds of problems.
