### ISSUE TITLE
Villagers can't procreate

### ISSUE THREAD

**Issue by Eperrial** [LunaPixelStudios/Better-MC#1279]
### Describe the Bug

i try to create farm to villager but they do nothing 
( no farming / no interraction between them )

### Reproduction Steps

1. Create farm with composter and bed
2. wait 
3. and see no baby
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/38047623/40df3922-e97d-4746-88c1-259435ca9bae)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BCM 3 (last curseforge update)

### Optifine

No

**Comment by SHXRKIIE** [comment]
![image](https://github.com/LunaPixelStudios/Better-MC/assets/79353591/da1b43bd-1f07-4c99-9780-a5ecc2248d0e)
No issues for me, I had beds, an extra for the child, doors and closed of area.

**Comment by SHXRKIIE** [comment]
![image](https://github.com/LunaPixelStudios/Better-MC/assets/79353591/88203db1-e22f-4a06-ae43-45afa503df35)
