### ISSUE TITLE
Crashing as soon as I launch

### ISSUE THREAD

**Issue by tubeless88** [LunaPixelStudios/Better-MC#1280]
### Describe the Bug

When opening BMC1 Fabric 1.19.2 on ATLauncher, the launcher minimizes and after some waiting it opens for a split second and closes. the error in at launcher states:
_[30/06/2023 19:48:11 PM] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\instances\BetterMCFABRICBMC1\crash-reports\crash-2023-06-30_19.48.11-client.txt
[30/06/2023 19:48:12 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support._
 
idk why its crashing. after looking through logsand reinstalling mods that gave errors i did a fresh install of the pack through atl

### Reproduction Steps

1. open the game
2. wait
3. atlauncher reopens saying "BetterMCFABRICBMC1\crash-reports\crash-2023-06-30_19.48.11-client.txt
[30/06/2023 19:48:12 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support."
...

### Screenshots and Videos

https://youtu.be/SiiBaBFsIco

### Crash Report or Log

https://gist.github.com/tubeless88/79744655fdcc9cc6ca8ea53ddbf644a0

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC1 1.18.5

### Optifine

No

### Other Mods

I added [Controller Support Mod](https://www.curseforge.com/minecraft/mc-mods/controller-mod) and [Distant Horizons](https://www.curseforge.com/minecraft/mc-mods/distant-horizons) fabric 1.19.2 versions.

**Comment by tubeless88** [comment]
1.19.2 Fabric not 1.18 forge

**Comment by SHXRKIIE** [comment]
The controller mod is failing to load, you could try the MidnightControls mod but if is still crashing due to it then remove it.

**Comment by tubeless88** [comment]
Thanks, I tried an older version of the mod first and it worked.
