### ISSUE TITLE
Unable to Start Server - Ubuntu 22.04

### ISSUE THREAD

**Issue by SniketTheLlama** [LunaPixelStudios/Better-MC#1282]
### Describe the Bug

Here is what happens when I attempt **sh start.sh**

_sniket@Dell5420:~/MCS/BetterMC$ ls
Better+MC+Server+Pack+FABRIC+1.19.2+v18.5.zip  server-icon.png
config                                         server.properties
defaultconfigs                                 start.ps1
mods                                           start.sh
READ_ME.txt
sniket@Dell5420:~/MCS/BetterMC$ sh start.sh
start.sh: 8: [[: not found
start.sh: 70: Syntax error: redirection unexpected_

When I try to run as a program after **chmod +x start.sh**

_Running Fabric checks and setup...
/home/sniket/MCS/BetterMC/start.sh: line 147: curl: command not found
/home/sniket/MCS/BetterMC/start.sh: line 149: curl: command not found
Fabric is not available for Minecraft 1.19.2, Fabric 0.14.21.
Exiting...
Press any key to continue_

### Reproduction Steps

1.
2.
3.
...

### Operating System

Ubuntu 22.04.2 LTS

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

18.5

### Optifine

No

**Comment by chorbintime** [comment]
you need to install curl
