### ISSUE TITLE
Vein Mining not working

### ISSUE THREAD

**Issue by HmmPickles** [LunaPixelStudios/Better-MC#1283]
### Describe the Bug

Vein Mining Enchantment not working

### Reproduction Steps

1.Enchant
2.Go mine 
3. It aint working

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

18.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Vein mining does work. You need the enchant and need to hold down the keybind. Please read the questbook.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
