### ISSUE TITLE
My game freeze

### ISSUE THREAD

**Issue by Soyverde12** [LunaPixelStudios/Better-MC#1288]
### Describe the Bug

Well, he started the game in the fabric version, and then he lets me play it normal and ordinary like he surely lets everyone else. After a few moments (minutes exactly) the game starts to freeze, but only the image because I can interact and hear what is happening, I just can't see it because the screen freezes. As I said, I play in the Fabric version, and this error had never happened to me and I've been playing the mod for a long time. I hope and help me to repair it, because I only enjoy a few minutes playing the MOD

### Reproduction Steps

1.I open the game
2.I play for a few minutes
3.It freezes unexpectedly
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v18.5.zip

### Optifine

No

### Other Mods

no

**Comment by chorbintime** [comment]
https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide
