### ISSUE TITLE
OpenGL Infinite Loop Error

### ISSUE THREAD

**Issue by AgWordSmith** [LunaPixelStudios/Better-MC#1289]
### Describe the Bug

I will start to play on a server running BMC and at first everything is fine until I start to notice the mine craft text corrupting and as time goes on the corruption becomes worse until my game freezes completely and has to be closed.

I have updated my CPU and GPU drivers and installed a newer version of Sodium (fixed 'blocks flash transparent often issue) and I installed Java 18 and added it's path to At launcher instead of the Mine craft default java and I have the latest Java installed.

I have done all the improvements for FPS and RAM according to Lunapixel up to the "extra's" Lists. These adjustments only prolonged the time it takes for the text corruption to appear and get worse.

The only other thing that is "wrong" when this happens that I can see is a potential issue is that My ATlauncher console simply shows a constant creation of the following line:

`[Render thread/INFO] OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error'`

And all it does is generate this over and over until my game freezes. 

Note: The Console had been cleared due to closing a previous run of BMC so I cleared to refresh the console space. 

### Reproduction Steps

1. Installed BMC1
2. Added Multiplayer Server
3. Played game
I didn't do anything other than simply run the game before experiencing the issue

### Screenshots and Videos

![Text corruption 2](https://github.com/LunaPixelStudios/Better-MC/assets/138950052/440310fe-911b-4de7-8e61-a3e896689a28)
![Text corruption](https://github.com/LunaPixelStudios/Better-MC/assets/138950052/b786e342-7ac9-42b6-a62a-6211aaadf4de)

### Crash Report or Log

https://gist.github.com/AgWordSmith/4b5a1a7e4690e0672fb902fbf1d3001f

### Operating System

WIndows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 V18.5

### Optifine

No

### Other Mods

I and the server have not downloaded anything beyond the BMC pack.

**Comment by chorbintime** [comment]
Update your GPU drivers via your vendor's website (AMD, NVIDIA, etc)

**Comment by AgWordSmith** [comment]
> Update your GPU drivers via your vendor's website (AMD, NVIDIA, etc)
As stated above I have already done  so for both the GPU and CPU

**Comment by AgWordSmith** [comment]
@chorbintime 
As Stated above, I have already done so for the GPU and CPU. I really wish it was that easy.

I have Intel Iris Plus Graphics Processor and Intel Core i7 10th Generation CPU Processor, My device has 16GB of RAM as well.

(Apologies for closing and reopening I'm new to Github)

**Comment by chorbintime** [comment]
I meant specifically from your vendor's website. You can try removing Sodium and its addons, or the ImmediatelyFast mod.

**Comment by AgWordSmith** [comment]
Yes that's what I did when updating them. I have tried removing Sodium and Iris before (and the other mods that rely on them) and still got that error but I will attempt to see how removing ImmediatelyFast Mod goes though :D Maybe that's the one causing this

**Comment by AgWordSmith** [comment]
Disabling Immediately Fast, Sodium and Iris (and Sodium and Iris dependent mods) removed the error! Disabling only Immediately Fast also kept the error removed and still let me play in the server!

Removing Sodium and Iris made it impossible to access the video setting so I'm very glad it was just immediately fast.

 Thank you so much for your help @chorbintime !!

**Comment by chorbintime** [comment]
> Disabling Immediately Fast, Sodium and Iris (and Sodium and Iris dependent mods) removed the error! Disabling only Immediately Fast also kept the error removed and still let me play in the server!
> 
> Removing Sodium and Iris made it impossible to access the video setting so I'm very glad it was just immediately fast.
> 
> Thank you so much for your help @chorbintime !!

reinstall IF and disable fast_buffer_upload in the config file, let me know what happens

**Comment by AgWordSmith** [comment]
I reinstalled it but I don't know how to disable that config file, could you walk me through it?

**Comment by chorbintime** [comment]
go into the config folder, open the immediatelyfast config

**Comment by AgWordSmith** [comment]
Ah i wasn't seeing it there for a while. I put the fast buffer on false and the error returned 

[Log](https://gist.github.com/AgWordSmith/ce1a18a7c52f1856db26c1405bd4166a)

**Comment by AgWordSmith** [comment]
I tried it, still got an error, I went and deleted the config itself after trying out the different settings one at a time to find a culprit and let it regen upon booting the instance and now everything's fine. I have no idea what happened? It looks the same as before I edited it.
