### ISSUE TITLE
Attempting to add Create Fabric causes the game to crash while loading

### ISSUE THREAD

**Issue by IamMegan** [LunaPixelStudios/Better-MC#1290]
### Describe the Bug

Attempting to add the latest patch of Create Fabric, v 0.5.1.b patch 2, causes the game to crash while loading. No other mods were added with this. The modpack was run through ATLauncer.

### Reproduction Steps

1. Add Create Fabric to the modpack, either with a direct download to the mods folder, or through the add mod function on a launcher
2. Attempt to launch Minecraft.

### Crash Report or Log

https://gist.github.com/IamMegan/35d41a2f17ef2e3b1275be4ceba88dea

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v18.5

### Optifine

I used Optifine

### Other Mods

Create Fabric
Mouse Tweaks Fabric
Compressor Fabric

**Comment by chorbintime** [comment]
This isn't a modpack issue. We do not directly support adding mods. Your best bet is updating other mods in the instance or trying an older version of Create. 

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
