### ISSUE TITLE
River won't unfreeze

### ISSUE THREAD

**Issue by hangawa** [LunaPixelStudios/Better-MC#1293]
### Describe the Bug

I was playing BMC 1 version 1.19.2 on a bisecthosting server. I made my home next to a river when I started and a 2 winters have passed since then and my river is still frozen. It was not frozen to begin with and now it won't unfreeze. can I do anything?

### Reproduction Steps

1. curseforge launcher download BMC1 1.19.2
2. buy bisect hosting 4 gb budget server 
3. stay in the same area for a long time in game maybe?
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v18.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Report to the fabric seasons developer

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.

**Comment by hangawa** [comment]
I'm probably not using optifine then I just don't know what that is and the default was to say yes
