### ISSUE TITLE
missing chests

### ISSUE THREAD

**Issue by lojedi2b** [LunaPixelStudios/Better-MC#1294]
### Describe the Bug

when i log into minecraft.  90% of my chest were missing and all the items were on the floor.

### Reproduction Steps

1.  do not know how th reproduce the bug for missing chest
2.
3.
...

### Screenshots and Videos

none

### Crash Report or Log

did not get one

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

better mc frabic 1.19.2 v18

### Optifine

No

### Other Mods

no

**Comment by chorbintime** [comment]
v18 is old, we offer no support for old versions. update to v18.5
