### ISSUE TITLE
Dont know if its a bug or a computer problem

### ISSUE THREAD

**Issue by GerardPolloRebozado** [LunaPixelStudios/Better-MC#1295]
### Describe the Bug

When I try to break blocks the 1st one breaks normally but wwhen I want to break a second block I cant if I dont stop mining and start again because the block won't break. Is this a bug? or its a feature from the modpack

### Reproduction Steps

1.Break 1 block without stop clicking
2.Try to break a second block it will never break
3.
...

### Operating System

Win11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC" v4

### Optifine

No

### Other Mods

I didnt aded any mod

**Comment by chorbintime** [comment]
update to v5
