### ISSUE TITLE
Can't make carved pumpkin

### ISSUE THREAD

**Issue by DutteB** [LunaPixelStudios/Better-MC#1296]
### Describe the Bug

I was trying to complete all the quests from the modpack, but when I was making the Snow Golem Plushie, I noticed that when you shear the pumpkin with the regular shears, the pumpkin disappears, leaving only the seeds behind. That's strange because modded shears (such as the one from the Blue Skies mod) work perfectly fine.

### Reproduction Steps

1. Put the Pumpkin Block down
2. Use vanilla shears
3. Poof! The pumpkin is gone, and now there are only seeds left on the floor
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 v15

### Optifine

No

**Comment by SHXRKIIE** [comment]
Will fix in next update
