### ISSUE TITLE
Sound Disappearing After World Generation

### ISSUE THREAD

**Issue by KoiPupper** [LunaPixelStudios/Better-MC#1297]
### Describe the Bug

At the title screen, I can hear Minecraft music but the second I start loading a world almost all sound is gone even once I spawn. The only sounds I can hear are the animal sounds from the Alex mobs animals (The blue jay caw, buffalo sounds, and I think a bear once?). 

I have tried every sort of restart imaginable multiple times. That includes uninstalling and reinstalling the mod (Many times).

### Reproduction Steps

1. open Better Minecraft
2. Spawn
3. No sound!

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v15

### Optifine

No

**Comment by chorbintime** [comment]
Reinstall the modpack using ATLauncher
