### ISSUE TITLE
Bmc3 issues with 2 mods that ive seen so far

### ISSUE THREAD

**Issue by Stoneyseth** [LunaPixelStudios/Better-MC#1298]
### Describe the Bug

quark mod is not working properly certain ancient tomes (aka enchantment books) are not able to be used. among other issues that I've noticed. 

We also experience severe crashes randomly sending us back about 5 minutes of gameplay which is super aggravating considering the people on my server really enjoy the mod pack and the world we've created with it but these bugs are very hard to not notice. if someone can help me fix these issues so we can enjoy this mod pack.

I am new to hosting a server so any help would be very appreciated.

### Reproduction Steps

1. 
2.
3.
...

### Crash Report or Log

NA

### Operating System

Windows 11 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 V15

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Need crash reports and what server host are you using?

**Comment by chorbintime** [comment]
Please be more specific about how ancient tomes aren't working.

As Sharkie said, we need logs to help you.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
