### ISSUE TITLE
Better Mc V18.5 Fabric

### ISSUE THREAD

**Issue by DerpestNoob** [LunaPixelStudios/Better-MC#1299]
### Describe the Bug

@Farmer Delight mod the cutting board does not work with beef and knife. after chopping the beef disappeared without giving you the miniced meat

### Reproduction Steps

1.cutting board
2.put the raw beef
3.cut
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/139644308/91443da4-03fa-4b79-aa22-6e8decc46c62

### Crash Report or Log

nl

### Operating System

Window 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V18.5

### Optifine

I used Optifine

### Other Mods

essential mod fabric 1.19.2

**Comment by SHXRKIIE** [comment]
Please remove Essential, its buggy because if how they make you LAN host.
