### ISSUE TITLE
Tutorial instructions say to equip a charm of life to a neck slot, but there doesn't seem to be one. 

### ISSUE THREAD

**Issue by Ryanpode** [LunaPixelStudios/Better-MC#1300]
### Describe the Bug

The tutorial says to equip the charm of life to the neck slot, but after following the instructions, there doesn't seem to be a neck slot, and the charm of life doesn't appear to be equipable anywhere. 

### Reproduction Steps

1. Launch Mod for the first time
2. Do tutorial to get "charm of life" 
3. Try to equip it

### Screenshots and Videos

![quest](https://github.com/LunaPixelStudios/Better-MC/assets/9537269/e94381de-188e-47a9-95e6-af9bf0451a96)
![inventory](https://github.com/LunaPixelStudios/Better-MC/assets/9537269/8575aff2-3fac-414e-a233-33b0451cf6b9)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

60.5

### Optifine

No

**Comment by chorbintime** [comment]
The tutorial quest is worded incorrectly, just keep the charm in your inventory.
