### ISSUE TITLE
Can I make a fork of this?

### ISSUE THREAD

**Issue by enderpirate98** [LunaPixelStudios/Better-MC#1301]
### Describe the Bug

This modpack is my favorite modpack for Minecraft but I would like to make my own version of it where I go my own route but I can't exactly keep the branding without permission, I really want to publish my fork on Modrinth but I would rather not get in trouble for plagiarism so can I get permission here?

### Reproduction Steps

1.Download v18.5
2.get rid of frostful, highlighter and Drippy 
3. Add other mods

and that is my intention

### Operating System

OpenSUSE Tumbleweed

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC v18.5

### Optifine

No

**Comment by enderpirate98** [comment]
I might not remove branding if it is okay for me to have ui as is?

**Comment by enderpirate98** [comment]
Anyway When you are seeing this have a good day!

**Comment by chorbintime** [comment]
Please do not copy our modpacks or our branding.
