### ISSUE TITLE
Cherry jar recipe is broken

### ISSUE THREAD

**Issue by ginkoguy** [LunaPixelStudios/Better-MC#1302]
### Describe the Bug

The recipe for the cherry jar from Vinery is broken. The recipe says it's one spruce slab with on top of a column of glass panes. However, the icon for the glass panes is a red circle-slash. The recipe doesn't work when I try to do it on my own. 

### Reproduction Steps

1. Search for cherry jar in JEI.
2. Look at cherry jar recipe
3. See that recipe doesn't seem to be correct
4. Try doing it outside of JEI using what is most likely the ingredients
5. Find that recipe doesn't work.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/21204852/d4e1b4a5-7c26-47ad-9674-cba42796dda9)

### Crash Report or Log

N/A

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
Report to Vinery developer
