### ISSUE TITLE
Recipe for Vinery dough conflicts with recipe for Farmer's Delight dough

### ISSUE THREAD

**Issue by ginkoguy** [LunaPixelStudios/Better-MC#1303]
### Describe the Bug

The recipe for the dough item from Vinery is conflicting with the recipe for the Farmer's Delight dough. Since the later is a shapeless recipe, it's overriding the Vinery recipe which is shaped. 

### Reproduction Steps

1.Place ingredients in configuration for Vinery dough in crafting table
2.Crafting table output is Farmer's Delight dough
3.Any configuration of water bucket and wheat is Farmer's Delight dough. 
...

### Screenshots and Videos

Attempted crafting
![image](https://github.com/LunaPixelStudios/Better-MC/assets/21204852/853ef511-539f-4e03-9c9c-929c0133eba1)
Farmer's Delight recipes
![image](https://github.com/LunaPixelStudios/Better-MC/assets/21204852/0c1e5cbc-f851-4c76-9128-01e9ffe30e78)
Vinery recipes
![image](https://github.com/LunaPixelStudios/Better-MC/assets/21204852/8feb8deb-0931-452e-9039-fd20f6974a73)

### Crash Report or Log

N/A

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

**Comment by chorbintime** [comment]
Report to Vinery developer
