### ISSUE TITLE
alchemist boss despawns as fighting, left trapped with all loot with no way to recover it 

### ISSUE THREAD

**Issue by Alexfrazier** [LunaPixelStudios/Better-MC#1306]
### Describe the Bug

Killed the boss but it teleported as we did and it registered as not dead. we are now trapped in there with no way to get our loot we have worked hard for. 

### Reproduction Steps

1.go to alchemist boss 
2. fight him and you might get the bug 
3.you are now trapped and no way to get your loot 
...

### Screenshots and Videos

none

### Crash Report or Log

none

### Operating System

windows 11 

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

60.5

### Optifine

No

### Other Mods

more quests

**Comment by SHXRKIIE** [comment]
I was not able to recreate it, it could just be unlucky that something happened. Could you wait and see if he comes back? Like 2-4mins?
