### ISSUE TITLE
Rivers near base wont unfreeze

### ISSUE THREAD

**Issue by indylohan** [LunaPixelStudios/Better-MC#1307]
### Describe the Bug

So away from my base and spawn, the seasons are working as intended, stuff melts, trees change color.

At my base and around my rivers, ice will not melt no matter the season. This only happens at my base and the chunks ~30-40 nearby.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

### Optifine

No

**Comment by chorbintime** [comment]
Report to Fabric Seasons mod developer
