### ISSUE TITLE
Game crashes on start 

### ISSUE THREAD

**Issue by McCrispy1** [LunaPixelStudios/Better-MC#1308]
### Describe the Bug

So, I downloaded the modpack through curseforge and launch the game, and I have did not changes or modifications to the modpack and I hit launch. It opens mc launcher I click play then it says game crashed error : 1
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/12083409/latest.log)

### Reproduction Steps

1.Launch the game through curseforge 
2.Click play 
3.Then crashes
...

### Crash Report or Log

https://pastebin.com/WSNedK4K

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BM3 v15

### Optifine

No

**Comment by SHXRKIIE** [comment]
Try ATLauncher, Cusrseforge seems broken

**Comment by McCrispy1** [comment]
thank you this worked
