### ISSUE TITLE
Quest for void shadow

### ISSUE THREAD

**Issue by Revguymc** [LunaPixelStudios/Better-MC#1310]
### Describe the Bug

I defeated the void shadow and got the rewards from the shadow chest but it didn't present me with the quest rewards saying I defeated it

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Desktop Screenshot 2023 07 19 - 12 39 31 90](https://github.com/LunaPixelStudios/Better-MC/assets/140000763/16e691bf-2a0a-42aa-89e9-dadc0b5530d3)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
What modpack version? v19, v18, etc

**Comment by SHXRKIIE** [comment]
![image](https://github.com/LunaPixelStudios/Better-MC/assets/79353591/526278d4-dcba-4e12-b2a5-3a3f5edaeda8)
Update ot latest please
