### ISSUE TITLE
My friend game keeps crashing 

### ISSUE THREAD

**Issue by McCrispy1** [LunaPixelStudios/Better-MC#1311]
### Describe the Bug

When my friend is playing is constantly crashing and I don't know why, but only crashes for him but everyone else has the same mods.

I have disabled the following mods:
backpacked
bh menu
corpse
drippy loading menu
fancy menu
ftb library 
ftb quests
ftb teams
invhud
xaeros minimap, icons, and worldmap

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.githubusercontent.com/McCrispy1/ef9385313be715ca5cc0ff96258811ea/raw/528cfc16dff1f98b039591012206cb63f404b541/gistfile1.txt

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BM3 v15

### Optifine

I didn't use Optifine

### Other Mods

I have disabled the following mods:
backpacked
bh menu
corpse
drippy loading menu
fancy menu
ftb library 
ftb quests
ftb teams
invhud
xaeros minimap, icons, and worldmap

**Comment by chorbintime** [comment]
Why did you remove all of those mods? That is likely the source of the issue

**Comment by McCrispy1** [comment]
Me and my friends didn't want them and it hasn't crashed once for me expect for him.

**Comment by McCrispy1** [comment]
But my friend just tried putting all the mods back and also tried reinstalling it. Still didn't work.

**Comment by SHXRKIIE** [comment]
You have basically corrupted it when removing those and adding it back wont magically fix it. Id suggest reinstalls and fresh worlds and big update coming for the modpack in 2 days so id suggest waiting
