### ISSUE TITLE
Fletcher not renewing trades once traded with.

### ISSUE THREAD

**Issue by Shadowlure2010** [LunaPixelStudios/Better-MC#1312]
### Describe the Bug

I have a Fletcher who won't renew his trades. For days now, with him in reach of his bench and a bed, his stick trade has remained depleted.

### Reproduction Steps

1.Create a fletching table.
2.Assign a villager and reroll him until he has stick trade.
3.Trade sticks for emeralds until it has a red cross.
4. Never able to do trade again as opposed to refreshing.
...

### Screenshots and Videos

![2023-07-20_01 22 58](https://github.com/LunaPixelStudios/Better-MC/assets/123444528/07068581-f783-406d-8638-16b3b73a31e1)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC[Forge]- BMC4 1.20.1 v5

### Optifine

No

### Other Mods

Create, Chipped, Resourcefullib and Athena

**Comment by chorbintime** [comment]
Send a screenshot of the villager setup

**Comment by Shadowlure2010** [comment]
On Thursday, 20 July 2023 at 11:56:06 am AEST, chorbintime ***@***.***> wrote:  
 
 


Send a screenshot of the villager setup

**Comment by SHXRKIIE** [comment]
You didnt send anything

**Comment by Shadowlure2010** [comment]
On Friday, 21 July 2023 at 11:33:49 am AEST, 丂廾闩尺长工㠪 ***@***.***> wrote:  
 
 


You didnt send anything

**Comment by rhit-liub4** [comment]
Hi there, I am experiencing the same problems as well, this isn't just with fletchers, but also with my Horticulturists as well
It might be because of the villagerPlus mod? just postulating 
![2023-07-20_21 42 48](https://github.com/LunaPixelStudios/Better-MC/assets/70913709/e5e9f228-4f0f-4e1c-9988-220635b0fa4e)
![2023-07-20_21 43 01](https://github.com/LunaPixelStudios/Better-MC/assets/70913709/d2ad43e7-bff1-4f57-bb39-cca31e1b4ccd)

**Comment by chorbintime** [comment]
You can make a backup & try removing VillagerPlus - if the issue persists try removing Smarter Farmers as well.

**Comment by rhit-liub4** [comment]
just tried that, removed VillagerPlus and then removed Smarter Farmers and the villagers still did not restock their trades

**Comment by SHXRKIIE** [comment]
Remove Canary or add this to the config 
mixin.ai.task=false
mixin.ai.poi.fast_retrieval=false
