### ISSUE TITLE
BMC3 [FORGE] No sound

### ISSUE THREAD

**Issue by Obacano** [LunaPixelStudios/Better-MC#1315]
### Describe the Bug

When i join my world, ionly listen part of the sounds.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Switch to ATLauncher.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.

**Comment by Obacano** [comment]
Sorry, i placed i used optifine, but i didn't use yet! was a big mistake!
