### ISSUE TITLE
Can't add any Texture Pack.

### ISSUE THREAD

**Issue by McBros211** [LunaPixelStudios/Better-MC#1318]
### Describe the Bug

I can't add Texture Packs. I install the right versions for 1.19.2, (playing BMC3 Forge) but the loading screen doesn't finish. Just loads all the way and stops before it's entirely full. I tested it with a few different texture packs like Sphax BD or NAPP, both 128x and 256x but none of them worked so far.

### Reproduction Steps

1.Installed Better Minecraft 3 [Forge]
2. Added a Texture Pack like Sphax BD.
3. Minecraft starts loading, showing the "Mojang" Loading Screen.
...

### Screenshots and Videos

![Bild_2023-07-21_150938967](https://github.com/LunaPixelStudios/Better-MC/assets/119093871/7b03b5c7-7b9e-441f-9443-26e0943e9cb5)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 [Forge] v14

### Other Mods

MekanismGenerators-1.19.2-10.3.9.13
MekanismAdditions-1.19.2-10.3.9.13
Mekanism-1.19.2-10.3.9.13
MekanismTools-1.19.2-10.3.9.13
domum_ornamentum-1.19-1.0.76-ALPHA-universal
blockui-1.19-0.0.69-ALPHA
multipiston-1.19.2-1.2.21-ALPHA
ProjectE-1.19.2-PE1.0.1B
LittleFrames_FORGE_v1.1.9_mc1.19.2
structurize-1.19.2-1.0.491-ALPHA
minecolonies-1.19.2-1.1.27-RELEASE

**Comment by chorbintime** [comment]
Follow the performance guide: https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide

You can force a resourcepack to be put into the load order by opening your options.txt file and adding it there. You may also need to open the config folder and add `file/resourcepack_file_name_here` at the top of the resourcepackoverrides config
