### ISSUE TITLE
Can't open version

### ISSUE THREAD

**Issue by Janoale** [LunaPixelStudios/Better-MC#1319]
### Describe the Bug

I try to open a new version (v19) but i can't. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/6VpUxMa

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v19

**Comment by chorbintime** [comment]
Did you add or remove mods?

**Comment by Janoale** [comment]
I think it was solved, but there is another issue, look this issues page again, i have published it
