### ISSUE TITLE
1.19.2 v16 doesn't open

### ISSUE THREAD

**Issue by ahmedcraftt** [LunaPixelStudios/Better-MC#1320]
### Describe the Bug

i updated the modpack from v15 to v16 yesterday and when i try to open it from atlauncher it takes too long loading but it never open i tried waiting for it for like 15 min but nothing the instant doesn't open 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

**Comment by chorbintime** [comment]
You need to send your logs or we can't help

**Comment by Janoale** [comment]
It happens the same to me

**Comment by chorbintime** [comment]
> It happens the same to me

Once again, we can not help you unless you send logs.
