### ISSUE TITLE
1.19.2 v16 doesn't open

### ISSUE THREAD

**Issue by Janoale** [LunaPixelStudios/Better-MC#1321]
### Describe the Bug

i updated the modpack from v15 to v16, and when i try to open it takes too long loading but it never opens i tried waiting for it but nothing

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/YzvNJDn

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v16

**Comment by chorbintime** [comment]
Reinstall using ATLauncher

If issue persists, try removing the Equipment Compare mod

**Comment by Janoale** [comment]
Sorry, is there another solution to not uninstall my launcher?

**Comment by chorbintime** [comment]
Try both solutions that I mentioned in my message
