### ISSUE TITLE
1.20.1 BMC4 [Forge]

### ISSUE THREAD

**Issue by DrunkElmo** [LunaPixelStudios/Better-MC#1322]
### Describe the Bug

I just downloaded the modpack and whenever I try to open the game it doesn't start and the console says the game crashed.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/r6gdQTjh

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v6

**Comment by chorbintime** [comment]
Reinstall using ATLauncher

If issue persists, try removing the Equipment Compare mod

**Comment by DrunkElmo** [comment]
> Reinstall using ATLauncher
> 
> If issue persists, try removing the Equipment Compare mod

I reinstalled and that didn't work and I don't see the mod you're talking about.

**Comment by chorbintime** [comment]
the mod in the mods folder called equipmentcompare. or click edit mods in ATLauncher

**Comment by DrunkElmo** [comment]
![Screenshot 2023-07-23 220913](https://github.com/LunaPixelStudios/Better-MC/assets/140354168/022bfb16-4785-4303-b8e4-d233c30707a7)
![Screenshot 2023-07-23 221022](https://github.com/LunaPixelStudios/Better-MC/assets/140354168/cabefd5c-881a-4ba1-9e2f-b05b70192a5f)
I don't see that mod in either place

**Comment by DrunkElmo** [comment]
i deleted the launcher and redownloaded the pack and it still doesn't work

**Comment by chorbintime** [comment]
Please check your logs & crash reports folders for a file named hs_err_pid. If you see one, that means you need to update your GPU drivers directly through the vendor's website
