### ISSUE TITLE
Part Of House Reverting to default. BMC 1.16.5

### ISSUE THREAD

**Issue by LordRCJAI** [LunaPixelStudios/Better-MC#1324]
### Describe the Bug

Part of my house keeps reverting all of my progress. I replace the wood, I log off, I join back on, and its back to the way is started! I've added several more mods to the modpack.

### Reproduction Steps

1. Replace any blocks in the area
2. Log off
3. Rejoin world
4. And its back to normal

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC v59

### Other Mods

Umm, It might take a while to do that.

**Comment by LordRCJAI** [comment]
![image](https://github.com/LunaPixelStudios/Better-MC/assets/140644179/e6292e76-9722-4a80-a07c-4d3a1f7139c8)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/140644179/3044740e-a660-4a10-86fc-5fa5b1d5fed3)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/140644179/d7495d29-e611-424d-85d6-4c065db8d347)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/140644179/6b2f0f09-9c5c-4579-98b9-05f3de2ab582)

**Comment by chorbintime** [comment]
v59 is old, and you didn't install the modpack correctly

**Comment by LordRCJAI** [comment]
How so?

**Comment by LordRCJAI** [comment]
Also if I l update it will I lose any of the mods a installed along with the modpack?

**Comment by chorbintime** [comment]
> How so?

You're missing resourcepacks and configs,



> Also if I l update it will I lose any of the mods a installed along with the modpack?

Just make a copy of the mods you added. Sort the mods folder by date modified
