### ISSUE TITLE
Villager Breading

### ISSUE THREAD

**Issue by xolexh** [LunaPixelStudios/Better-MC#1325]
### Describe the Bug

I tried to  bread 2 villagers with 3 beds and a lot of  carrots and nothing happened. they just stood there looking at me. Same thng happened when i tried a villager breader with farmer villagers and a 8/8 crop land and they again just stood there looking at me. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc forge 1.20.1 v 5

**Comment by chorbintime** [comment]
v5 is old, update the modpack
