### ISSUE TITLE
bmc 3 forge will not start on 19.2 v16

### ISSUE THREAD

**Issue by PancakesYT** [LunaPixelStudios/Better-MC#1326]
### Describe the Bug

whenever i click the play button, it closes the minecraft launcher and it then proceeds to pop up with a crash report labeled 1. I have tried everything related to said crash report and nothing has changed. also tried to use ATlauncher, same thing, the mod wouldn't launch.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://docs.google.com/document/d/14XMoXBD5eDC-augfYT5QUakVeV5WiWkIhpnZl8L8HpA/edit?usp=sharing

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc 3 v16

**Comment by chorbintime** [comment]
Update your GPU drivers directly from your vendor (AMD, NVIDIA, etc)'s website
