### ISSUE TITLE
Resource Reload failed 

### ISSUE THREAD

**Issue by AlphaKipz** [LunaPixelStudios/Better-MC#1327]
It worked fine with the previous versions, and my resource pack works normally in vanilla minecraft.
I'm launching BetterMC using prism launcher.

Im playing on a server

Everytime i open the resource packs tab, i dont even select any resource packs to be added and if i go back, it'll say
"Resource Reload Failed", and remove some of the texture packs that are on by default (Simple Storage Network)

Theres no option for lower resolution texture packs because i tried testing using 16x packs and it still wouldnt work, resource reload failed. Please help.

1. Open resource packs tab
2. Select a resource pack, or just press done even though nothing was selected
3. Wait until it loads and you will be brought back to home screen with the notification "Resource Reload Failed"
...

**Comment by AlphaKipz** [comment]
Also won't work on forge launcher

**Comment by chorbintime** [comment]
Update the ModernFix mod
