### ISSUE TITLE
Better MC 2 (1.18.2)- Sever Update Creates Mismatched Mod List Error

### ISSUE THREAD

**Issue by HttpsXintecqx** [LunaPixelStudios/Better-MC#1328]
### Describe the Bug

My Aternos-based server automatically upgraded my Better MC server from version 19 to version 20. When I upgraded my Curse Forge modpack to version 20 and launched it, it said it had a mismatched mod (Excavated Variants), yet below it it says the server has the same version as mine. I'd delete the mod, but Aternos doesn't allow you to do so with modpacks.

### Reproduction Steps

1. Opened the modpack via the Curseforge app
2. Opened server via Aternos Hosting Platform
3. Loading seemed to be going alright
4. Then the screen linked below showed up.
...

### Screenshots and Videos

![Screenshot (34)](https://github.com/LunaPixelStudios/Better-MC/assets/140827145/0d3e189a-868a-4f18-983d-ea66de1742b5)

### Crash Report or Log

https://pastebin.com/NVatzLa4

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [FORGE] -BMC2 (Version 20)

**Comment by chorbintime** [comment]
You did not install the modpack correctly. Reinstall the modpack using ATLauncher.

Do not use Aternos. It does not install modpacks correctly either. Self-host a server using the server files on the modpack's Curseforge page.
