### ISSUE TITLE
@spirit mod

### ISSUE THREAD

**Issue by nscwb** [LunaPixelStudios/Better-MC#1329]
### Describe the Bug

In the Spirit mod the Soul Glass isn't showing any recipe. it's made with 4 lapis lazuli blocks soul sand, 1 tinted glass.

Please fix this for others 

THX!

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/140833946/16fa9468-c699-475d-9f8d-3dbcbc4d8e88)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

19.5

**Comment by chorbintime** [comment]
Report to the developer of the Spirit mod
