### ISSUE TITLE
Crashing due to a Null Issue

### ISSUE THREAD

**Issue by NewtParty** [LunaPixelStudios/Better-MC#1330]
I am playing on a friends server and I seem to be the only one affected by this crashing issue. It was fine at first with randomly at around a 1 hour increment. However I entered the Paradise Dimension and now I am stuck in a loop of crashing.

I think I attached the file of the crash. 

Exit Code was -1
[crash-2023-07-29_20.52.51-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/12208374/crash-2023-07-29_20.52.51-client.txt)

**Comment by chorbintime** [comment]
What modpack version are you playing?

**Comment by NewtParty** [comment]
I resolved the issue using the performance guide that was provided in other reports. Thanks!
