### ISSUE TITLE
Game stuck on "starting world"

### ISSUE THREAD

**Issue by LeSniffa** [LunaPixelStudios/Better-MC#1331]
### Describe the Bug

Quiting the game right after dying in the nether without respawing has made my game get stuck on "starting world" after trying to re-enter the world.

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v7

**Comment by chorbintime** [comment]
Download the NBTStudio program from Github

Open your playerdata file using the program

Change the health attribute to 20
