### ISSUE TITLE
Save crashes right after opening

### ISSUE THREAD

**Issue by vassily6** [LunaPixelStudios/Better-MC#1332]
### Describe the Bug

The game crashed as I was exploring the twilight forest dimension and now crashes every time I open the save file, although other saves are unaffected. The game lets me look around for one or two seconds before freezing/crashing. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/3RHi9G1

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v19.5

**Comment by chorbintime** [comment]
You didn't send the crash report so it's hard to be sure, but this is probably the Final Castle crash. It's an unfixed issue with Twilight Forest itself. You can open your playerdata file using the NBTStudio program and change your dimension and/or coordinates then just avoid the crashing area
