### ISSUE TITLE
Can't Craft Chests from the every compat mod.

### ISSUE THREAD

**Issue by FriendlyKoala** [LunaPixelStudios/Better-MC#1333]
### Describe the Bug

Cannot craft chests from any wood with the every compat mod either with regular chest recipe with the Oh The biomes you will go chest recipe. Only Recipe I can find is for using  Uncrafting Table from the Twilight Forest mod.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v16 forge 43.2.19

**Comment by chorbintime** [comment]
update to v17
