### ISSUE TITLE
Fabric Server - No price drop after Zombie Villager Cure

### ISSUE THREAD

**Issue by CoryKelly** [LunaPixelStudios/Better-MC#1334]
### Describe the Bug

Creating a villager trading hall, I started with two villagers and they lowered there prices only once out of the 5 times that I tried to cure and have not seen a price drop since. 

### Reproduction Steps

1. Get villagers 
2. Get zombie 
3. Let them play ( On hard mode )
4. Throw splash potion of weakness and follow up with a nice golden apple 
5.  Wait..............
6.  Once villagers turn back ( with slight hangover 0.o) Check prices. 
7. Be disappointed that your archer is still high balling you for sticks.. Not cool.  

### Crash Report or Log

None

### Operating System

Mac OS

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v19.5

### Other Mods

Mob Catcher - FABRIC

**Comment by chorbintime** [comment]
yea this isn't intended but i'm going to consider it a feature because https://bugs.mojang.com/browse/MC-181190
