### ISSUE TITLE
Server Unable to Start after PC Crash

### ISSUE THREAD

**Issue by Draygoh** [LunaPixelStudios/Better-MC#1336]
### Describe the Bug

After I was done playing my game [for specified game Apex Legends] I decided to reopen the server. *server runs normally* and I had chrome opened while watching videos on doing massive builds. and my pc crashed probably my GPU is already at its limit because its now 6 or 7 years old. Once my PC Restarted after the crash I opened start.ps1 with PowerShell like I usually do and now I am unable to open the server. Sad to say I have not create a back-up for this server and I want to know if there's any fix to this issue.

Heres one of the methods i tried doing.
- Restart PC
- Shutdown PC
- create a new server folder and copy the world onto that folder

Note:
- On the New Server Folder it run properly but after adding in the world I was having issues I got the same problem
- I had a crash report but it happened in the morning and the server had no problem running until my PC Crashed that night.
- My PC never crashes while having the server on for these games I've played (Destiny 2, MW2 2022, CSGO and Battlebit) the only game I Avoid playing because it happened a few times when trying to play Destiny 2 and its just Valorant...
- *Just in case you need more info* I have a set schedule for my friends that also plays on the server. 4:30pm - 5am weekdays, Weekends depends whoever wants it on for the whole day because I do Uber Delivery on weekends for 4 hours in the afternoon.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/EYlFcVb

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

**Comment by chorbintime** [comment]
Send your level.dat file in the world folder

Also try allocating 8gb of RAM to the server in the variables.txt, or try reinstalling the serverpack & transferring your world folder over

**Comment by Draygoh** [comment]
I tried Allocating 8gb of ram into the variables.txt it still did not work and reinstalling the serverpack & transferring my world folder over did the same heres the log for the reinstalled serverpack [https://mclo.gs/mUxtKJB](url)

**Comment by Draygoh** [comment]
Umm good news i found the issue. So inside the world folder there's 2 level file one thats level.dat and the other was level.dat_old so what i did is delete the level.dat and rename the level.dat_old into level.dat along with the playerdata folder that has a .dat file with .dat_old and i ran the start.ps1 one more time along with allocating the 8gb RAM into the variables.txt and now it finally works. Here is the Log for the working Server (sadly it did not get everything in the log.) [https://mclo.gs/5bqQTnZ](url)
