### ISSUE TITLE
Huge FPS drops while moving or jumping

### ISSUE THREAD

**Issue by Meciej** [LunaPixelStudios/Better-MC#1339]
### Describe the Bug

Im playing on BetterMC modpack on version 1.20.1 and FPS is dropping while im moving up or down. FPS drop while im jumping or walking on stairs. How to solve this? It makes the game unplayable

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC v8

**Comment by chorbintime** [comment]
Run /sparkc profiler start

send the link here after running the stop command

**Comment by Meciej** [comment]
"An error occurred whilst uploading the results. Attemting to save to disk instead"  Then the file was saved on (C:). I will attach the file here but i have to put it in ZIP

[profile-2023-08-07_11.07.45.zip](https://github.com/LunaPixelStudios/Better-MC/files/12274360/profile-2023-08-07_11.07.45.zip)

**Comment by patedeclodo** [comment]
https://spark.lucko.me/0857XugXAN

**Comment by Meciej** [comment]
Yup, exactly. Cant explore anything cuz of these lags

**Comment by elitesdead** [comment]
I also have this problem, and it's only noticeable when moving up and down in my experience

**Comment by chorbintime** [comment]
> I have the same problem and it is only on caves and stuctures



> Yup, exactly. Cant explore anything cuz of these lags



> I also have this problem, and it's only noticeable when moving up and down in my experience



> yep i guess this is when we are in air or someting idk

I can not help any of you if you do not send a spark report. I don't know how I could possibly make this more clear.

Run /sparkc profiler start
send the link here after running the stop command


> "An error occurred whilst uploading the results. Attemting to save to disk instead" Then the file was saved on (C:). I will attach the file here but i have to put it in ZIP
> 
> [profile-2023-08-07_11.07.45.zip](https://github.com/LunaPixelStudios/Better-MC/files/12274360/profile-2023-08-07_11.07.45.zip)

I need more information. Were you in the Twilight Forest? What modpack version are you on? Does the latest update fix this?

**Comment by chorbintime** [comment]
I will also be closing this issue so people stop piggybacking and giving completely unhelpful replies. Feel free to reply if you were already in the thread.

**Comment by Meciej** [comment]
While this spark file was created i was in twilight forest but this bug occurs also in basic world. Lags decrease a little when im just running in open world but as soon as i enter structure or cave from 200FPS it drops to 1-20. Im using the latest version of modpack. I started playing it after latest update like 2 days ago and since then there werent any new updates soo it isnt fixed. The version im using is Better MC [FORGE] - 1.20.1 v8.zip

**Comment by chorbintime** [comment]
> While this spark file was created i was in twilight forest but this bug occurs also in basic world. Lags decrease a little when im just running in open world but as soon as i enter structure or cave from 200FPS it drops to 1-20. Im using the latest version of modpack. I started playing it after latest update like 2 days ago and since then there werent any new updates soo it isnt fixed. The version im using is Better MC [FORGE] - 1.20.1 v8.zip

Create a spark profiler while you are in an overworld cave.

**Comment by Meciej** [comment]
I was in overworld caves and again there was an error. I
[profile-2023-08-08_13.56.11.zip](https://github.com/LunaPixelStudios/Better-MC/files/12290849/profile-2023-08-08_13.56.11.zip)
m uploading created file here

**Comment by chorbintime** [comment]
Does the issue persist with the Starlight mod disabled?

**Comment by chorbintime** [comment]
Send the crash report

**Comment by Meciej** [comment]
Okay really appreciate your help but im gonna just find some other modpack to play. Cya and thanks again
