### ISSUE TITLE
Grindstone duplication glitch

### ISSUE THREAD

**Issue by Thooooreeee** [LunaPixelStudios/Better-MC#1340]
### Describe the Bug

I tested with every enchantable item I could find, even the modded ones, works the same.
Also found this on my friends server, so not just a thing in singleplayer

### Reproduction Steps

1. Use Grindstone to remove enchantment
2. Duplicate item
3. profit???
...

### Screenshots and Videos

https://youtu.be/JoLrcd0wak8

### Operating System

Win11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc2 v7.5

### Other Mods

InvMove [https://modrinth.com/mod/invmove]

**Comment by chorbintime** [comment]
Issue with the VillagersPlus mod
