### ISSUE TITLE
FPS Stuttering on 1.20.1 Forge Modpack (Latest)

### ISSUE THREAD

**Issue by elitesdead** [LunaPixelStudios/Better-MC#1342]
### Describe the Bug

In enclosed spaces, when I jump or move up and down in any manner (this includes ladders, stairs, swimming up water, etc) there is a noticeable choppiness and fps drop. I have made no changes to the modpack, I just ran it on curseforge.

### Reproduction Steps

1. Go into tight spaces, or in just certain niche areas.
2. Try going up and down in any manner
3. Check FPS (it decreases)
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v8

**Comment by patedeclodo** [comment]
I have the same problem and i didn't found how to fix it, it is when you jump or mount stairs on stuctures or caves.

**Comment by patedeclodo** [comment]
https://spark.lucko.me/0857XugXAN

**Comment by patedeclodo** [comment]
https://spark.lucko.me/0857XugXAN

**Comment by chorbintime** [comment]
There's no issues here, your game is running at maximum performance consistently. The only thing taking up a lot of the server tick is Xaero's Minimap, and its only responsible for 10%. This seems completely fine to me. 

If the lag only happens in specific situations, please recreate the situation while you're running the profiler.

**Comment by patedeclodo** [comment]
https://spark.lucko.me/iI80Aqxw3i this link should be more accurate cause in the other i didn't tried the bug srry

**Comment by patedeclodo** [comment]
so i have to change the minimap lvl ?

**Comment by patedeclodo** [comment]
I tried to delete Xaero's minimap and it removed the lags so you right so thank you

**Comment by patedeclodo** [comment]
xaero plus is 100% the mod that makes lags

**Comment by elitesdead** [comment]
Oh, sweet. It is the Xaero Plus mod. Thank you chorbintime and patedeclodo!

**Comment by rfresh2** [comment]
I opened an issue on my repo, will track this there
