### ISSUE TITLE
MASSIVE fps drop in caves

### ISSUE THREAD

**Issue by DreamKiller69** [LunaPixelStudios/Better-MC#1343]
### Describe the Bug

My fps gos from 110 to 60-38 fps in a cave or under a small cliff and i do not have a potato pc i have a 3070ti 32gigs of ram and a ryzen 5

### Reproduction Steps

1.i just walk in to a cave or something underground
2.
3.
...

### Screenshots and Videos

https://youtu.be/2IaM_pXxoeE just copy and paste url and you will get the video

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

V8

**Comment by chorbintime** [comment]
You need to send a spark profiler or I can not help.

Run /sparkc profiler start

send the link here after running the stop command

**Comment by JJM6701** [comment]
https://spark.lucko.me/PoYw9scnrD

**Comment by chorbintime** [comment]
Fixed with https://github.com/rfresh2/XaeroPlus/issues/42
