### ISSUE TITLE
Grindstone Dupe Glitch

### ISSUE THREAD

**Issue by Potatoman967** [LunaPixelStudios/Better-MC#1344]
### Describe the Bug

Placing an enchanted item into the lower slot of the grindstone will produce an unlimited amount of the unenchanted item with the same durability, but without the enchantment.

### Reproduction Steps

1. Enchant an item, a sword or chestpiece or something
2. Place enchanted item into the bottom-most slot of the grindstone
3. Either shift-click or take the item out of the grindstone
4. Duped items galore

### Screenshots and Videos

Here I load up a world where I tested the dupe glitch earlier, its about a minute long, this is just with the modpack. None of the other mods i was using in regular play are installed at this point.

https://clipchamp.com/watch/Z9ecEeBDEuw
The file uploader on github is worthless and wont let me upload the video itself

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2 1.20.1 v7.5

### Other Mods

I was using other mods but took them out to verify that it was this modpack, Im not sure what mod could be causing this, tested it on vanilla to make sure i wasnt insane and it didnt dupe,

In case you wanna check for yourself the mods I was using when I discovered this are all using fabric and are as follows

ad astra 1.20.1
botarium 1.20.1
darkorb 1.0.0
digs dnd origins 1.20.1
origins 1.20.1
origins classes 1.20-1.7.0
pehkui 3.7.7 1.14.4-1.20.1
resourceful config 1.20-2.0.0
resourcefullib 1.20.1-2.1.8

Again I removed all these and tested the glitch again with JUST the modpack installed, unsure if one of these couldve caused it though.

**Comment by Potatoman967** [comment]
how do i add labels lol

**Comment by chorbintime** [comment]
Its an issue with the VillagersPlus mod. Already reported it to them.

**Comment by Potatoman967** [comment]
tysm for quick response

**Comment by Potatoman967** [comment]
Hey idk how github works or if youll see this, but i saw u closed the bug report on VP's github page, felt i should add through my own testing removing villagersplus didnt fix it. on a whim i decided to remove guardvillagers as i thought maybe u were onto something with villagersplus, which did end up fixing it. understandable mistake as they were both made by same mod author, lmk if this fixed it for u as well

**Comment by chorbintime** [comment]
Yeah I'm retesting it right now and its 100% a Guard Villager issue. Will report it to their github
