### ISSUE TITLE
BMC 4  

### ISSUE THREAD

**Issue by patedeclodo** [LunaPixelStudios/Better-MC#1345]
### Describe the Bug

Some stone blocks are invisible and make like xray bug, i think this is an alternative texture that dosen't work.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-08-08_12 14 44](https://github.com/LunaPixelStudios/Better-MC/assets/84086834/78ce8e34-6b64-4826-9136-0b775957ae99)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v8

**Comment by patedeclodo** [comment]
It is when you delete xaero plus

**Comment by chorbintime** [comment]
Can you be more specific - what does this have to do with Xaero Plus

**Comment by patedeclodo** [comment]
idk i deleted xaero's plus cause of lags and it makes some stone invisible so I took another minimap mod and it removed lags

**Comment by chorbintime** [comment]
Deleting a minimap mod will not cause stone to go missing. Thats not how mods work. Read https://github.com/rfresh2/XaeroPlus/issues/42 for a solution to the lag
