### ISSUE TITLE
unkillable Alchemist in Everdawn

### ISSUE THREAD

**Issue by midnightfairy** [LunaPixelStudios/Better-MC#1346]
### Describe the Bug

managed to bring the Alchemist boss to almost half life with my sword and he is never going down to below half live. playing on better mc 1.18.2 v19

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.18.2 v19.zip

**Comment by chorbintime** [comment]
report to blue skies dev, we dont modify the dimension in any way
