### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Huantanhua** [LunaPixelStudios/Better-MC#1347]
I think “CERBON's Better Totem of Undying” can replace “Void Totem” and “Charm of Undying”. Because it contains the functions of both.
https://www.curseforge.com/minecraft/mc-mods/better-totem-of-undying-forge

**Comment by chorbintime** [comment]
We tend to prefer to use 2 separate mods for this sort of thing - there is a lot of room for bugs in the features of both Void Totem and Charm of Undying. both mods are still maintained separately so we'd rather just use two 

I appreciate the suggestion though!
