### ISSUE TITLE
better mc forge bmc1 crash

### ISSUE THREAD

**Issue by deadend12345** [LunaPixelStudios/Better-MC#1348]
### Describe the Bug

i click start in the luncher to play better mc forge bmc1 it load and after 2 seconds in close and in the luncher it tells me the game crashed exit code:1
please help me

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![](https://cdn.discordapp.com/attachments/942406430437310625/1139529006820114452/image.png)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc1

**Comment by chorbintime** [comment]
Please send logs. We can not help without logs. Check the logs folder in the modpack files
