### ISSUE TITLE
Need operator for players to do functions

### ISSUE THREAD

**Issue by AvadaKedavraEagle** [LunaPixelStudios/Better-MC#1349]
Hello, I am having an issue where the player cant do any function such as opening doors and opening chests unless you have operator. Is this intended? If so, how do I change the config? Thanks.

**Comment by chorbintime** [comment]
The players are in chunks claimed by other players. The claim owner can add those players to the claim.

**Comment by AvadaKedavraEagle** [comment]
Can I disable this feature?

**Comment by chorbintime** [comment]
Check the config for the claim mod. I don't know what modpack you're using because you did not follow the issue format.

**Comment by AvadaKedavraEagle** [comment]
Sorry for me overlooking that. I am using Better MC 1.20.1 V8, and there is no config or command for anything related to the claim mod
.

**Comment by chorbintime** [comment]
The mod is called Open Parties and Claims. Its config is likely called opac

**Comment by AvadaKedavraEagle** [comment]
I deleted open parties and claims, but it did not resolve the issue that I am having.

**Comment by chorbintime** [comment]
you're probably in spawn chunks then
