### ISSUE TITLE
Crash on start up BetterMCv8 1.20.1 Forge-47.1.43

### ISSUE THREAD

**Issue by soldierboy45** [LunaPixelStudios/Better-MC#1350]
### Describe the Bug

I have tried updating drivers, my mod loaded and uninstalling and reinstalling the mod pack. I'm trying to add a few extra mods in with it, and they work fine on their own. When I add BetterMC into it, it crashes, so I removed all and just installed the BetterMC mods and was still receiving a crash error.
![Screenshot 2023-08-11 165205](https://github.com/LunaPixelStudios/Better-MC/assets/142065597/b143cdad-17cf-4128-8c4f-8a92bf2f2a81)

### Reproduction Steps

1. install mod pack
2. open launcher
3. start up forge 47.1.43
4. game crash on startup

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v8

### Other Mods

appleskin 1-2.5.0
blockui 0.0.84 alpha
cfm 7.0.0-pre36
citadel 2.4.2
cloth config 11.1.106
collective 6.57
create 0.5.1.d
creeperoverhaul 3.0.1
cucumber 7.0.0
curios 5.2.0-beta.3
domum ornamentum 1.0.104
dungeon crawl 2.3.14
durabilitytooltips 1.1.4
fullbrightness toggle 1.20.0-3.0
geckolib 4.2.1
jei 15.2.0.22
lootr 0.7.30.73
mcw bridges 2.1.1
minecolonies 1.20.1-1.1.9-alpha
pamhc2foodcore 1.0.0
puzzleslib-v8.0.15
repuropsed structures-7.0.0+
resoursefulconfig-forge-1.20-2.0.0
simplefarming 1-2.0.5
simplehats 0.2.1
structurize 1.0.583-beta
supermartijn642configlib-1.1.7
supermartijn642corelib-1.1.10
xaeroplus forge-1.20.1-19-wm1.31.0
xaeros minimap 23.6.0
xaerosworldmap 1.31.0

**Comment by chorbintime** [comment]
Its an issue with mods you added or updated. This is for you to figure out. It's just an incompatibility.

**Comment by soldierboy45** [comment]
Even when running just the BetterMC mod pack I still receive the same crash error. I took out the 30 mods that I was running and only tried to launch with BetterMC

**Comment by chorbintime** [comment]
This does not happen on an unmodified instance. Do a fresh install of the modpack on ATLauncher.
