### ISSUE TITLE
Bees and Dispensers

### ISSUE THREAD

**Issue by HomicidalDoc** [LunaPixelStudios/Better-MC#1351]
### Describe the Bug

Trying to make an automatic bee farm. Made a basic one and when trying to get it to work the dispenser just shoots out the bottle without collecting the honey. The beehive and Bee nest are at full honey and dispenser is facing the hive but it won't collect the honey. I can still manually do it but want to auto it for ease of living.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC 3

**Comment by chorbintime** [comment]
Might be an issue with the Canary mod. Can you remove it & test?

It could also be DoesPotatoTick

**Comment by HomicidalDoc** [comment]
Tried turning both mods off separate and then together and did the entire process of automation but still nothing worked.

**Comment by chorbintime** [comment]
Are you sure this works in vanilla

**Comment by HomicidalDoc** [comment]
Yes I duplicated the entire setup in Vanilla and it works fine.

**Comment by chorbintime** [comment]
Try with the Alternate Current mod removed

**Comment by kotaro-osaka** [comment]
I have the exact same problem, was this issue ever resolved? @chorbintime @HomicidalDoc 

Playing on BMC3 v18 1.21.1

I removed the Alternate Current mod, because @HomicidalDoc never replied with the results of doing so, but this didn't fix anything for me.
