### ISSUE TITLE
nitrado server, version

### ISSUE THREAD

**Issue by Reynaldo1212** [LunaPixelStudios/Better-MC#1353]
### Describe the Bug

got nitrado and downloaded better minecraft, but it keeps telling me my server is an older version v18.5 and the mod pack is the newest v19.5. and everytime i try download the 18.5 version. it gives me error message "missing file for mod "project-865618 in datebase. aborting installation." 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot (84)](https://github.com/LunaPixelStudios/Better-MC/assets/142184192/1fe2f3a1-5503-489a-bb96-d94f13bd1e6d)

### Operating System

window 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC1

**Comment by chorbintime** [comment]
Nitrado needs to update your server to v19.5

There is nothing we can do about this, this is not a bug. The modpack has a v19.5 serverpack available.
