### ISSUE TITLE
Crash better mc modpack

### ISSUE THREAD

**Issue by mmanucorrea** [LunaPixelStudios/Better-MC#1355]
### Describe the Bug

Hi, I have this crash with the better mc modpack, the game doesn't even open

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/p164yGF

### Operating System

windonws 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

better mc  v17

**Comment by chorbintime** [comment]
You didn't install the modpack correctly. You need to use a modded launcher to install & play modpacks. Please read the performance guide for steps on how to install a modpack https://github.com/LunaPixelStudios/Medieval-MC/wiki/Performance-Guide
