### ISSUE TITLE
Advancements not updating in quest book

### ISSUE THREAD

**Issue by ratseggs72** [LunaPixelStudios/Better-MC#1358]
### Describe the Bug

 The quest book that comes with the mod is not updating with the in game achievements. Any known fixes?

### Reproduction Steps

Obtain different achievements in twilight forest

### Screenshots and Videos

![2023-08-15_17 32 30](https://github.com/LunaPixelStudios/Better-MC/assets/142356586/cda9f3c6-9e09-4d4b-8f93-39d4bf448b15)
![2023-08-15_17 32 07](https://github.com/LunaPixelStudios/Better-MC/assets/142356586/5b1f0c75-517e-4461-8761-350d0d83dd87)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v17

**Comment by chorbintime** [comment]
the bottom quest is probably just not set correctly - you can edit it by typing /ftbquests editingmode true
