### ISSUE TITLE
Breaks my minecraft skin, anyone else had this issue?

### ISSUE THREAD

**Issue by RNGsusII** [LunaPixelStudios/Better-MC#1359]
### Describe the Bug

When I go into vanilla, my skin works fine, but whenever I go into this modpack, I'm stuck as Ari, but it may be an outside issue.

### Reproduction Steps

1. Equip skin via launcher
2. Go into the Curseforge app
3. Play BMC4 and see your skin, or lack thereof
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v9

**Comment by Frontear** [comment]
Try relogging your account on CurseForge, or fully restart your PC to allow CurseForge to update its caches.

**Comment by RNGsusII** [comment]
> Try relogging your account on CurseForge, or fully restart your PC to allow CurseForge to update its caches.

This did not work for me, I have also tried it on another modpack, and I'm not stuck as Ari, though.

**Comment by chorbintime** [comment]
Are you playing on a server? If so, is the server on offline mode?

**Comment by RNGsusII** [comment]
> Are you playing on a server? If so, is the server on offline mode?

No I am not I'm in singleplayer

**Comment by chorbintime** [comment]
Does the issue persist on ATLauncher

**Comment by RNGsusII** [comment]
Ok, I don't have that but I will actually test that thanks for the good idea!
Ok that worked, issue resolved
