### ISSUE TITLE
can't do anything, infinite lag, random death, chests won't open, Unplayable.

### ISSUE THREAD

**Issue by Nilla27** [LunaPixelStudios/Better-MC#1361]
### Describe the Bug

I came out of the nether to infinite lag, tried to open chests didn't work, reloaded the sever multiple times. Upon logging back in I randomly died and my grave is also unlootable. Not sure what happened but I haven't been able to fix it. Not sure what to do, please help.

### Reproduction Steps

1. Come out of the nether ?
2. Relogin cause of the lag 
3. Randomly die ?
...

### Screenshots and Videos

![Game Broken](https://github.com/LunaPixelStudios/Better-MC/assets/142712670/6beb920f-82a5-4689-8f84-d8c350813289)

### Crash Report or Log

Java.Net.SocketException: Connection Reset

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2v9.5

### Other Mods

End Remastered, Better animations, Tree Harvester

**Comment by chorbintime** [comment]
We can't help if you don't post logs
