### ISSUE TITLE
Vanilla recipe search is not working (Inventory and Craftingtable)

### ISSUE THREAD

**Issue by Ashanter** [LunaPixelStudios/Better-MC#1362]
### Describe the Bug

When i open the Inventory or Craftingtable i see all recipes, but 
when i type something to search bar, it shows nothing.

I´ve unlock all recipe´s.

### Reproduction Steps

1. Open my inventory or craftingtable
2. type anything to the search bar
3.  it show nothing

### Screenshots and Videos

![2023-08-21_14 53 55](https://github.com/LunaPixelStudios/Better-MC/assets/142804568/6547c1a2-a59a-455e-90f2-b82bef16e466)
![2023-08-21_14 55 12](https://github.com/LunaPixelStudios/Better-MC/assets/142804568/17b6c5a7-9970-45fa-ad6b-0124cdd3a592)
![2023-08-21_14 55 16](https://github.com/LunaPixelStudios/Better-MC/assets/142804568/cba970f9-5f8f-4c2a-9762-3b0437aaf207)
![2023-08-21_14 55 29](https://github.com/LunaPixelStudios/Better-MC/assets/142804568/a88a05e6-4ecd-4084-b0c7-202697c57634)
![2023-08-21_14 55 35](https://github.com/LunaPixelStudios/Better-MC/assets/142804568/2a234c5c-8edd-452c-a4cf-3a3f65ec3dcc)
![2023-08-21_14 56 29](https://github.com/LunaPixelStudios/Better-MC/assets/142804568/90ced758-04f6-46e0-869f-58354d4798c0)

### Crash Report or Log

no crashreport or log

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC 3  V17

### Other Mods

no

**Comment by chorbintime** [comment]
not a bug, its an intentional optimization. just use jei. you can disable blast search trees in the modernfix config.
