### ISSUE TITLE
Aether Crash

### ISSUE THREAD

**Issue by itsjustme12** [LunaPixelStudios/Better-MC#1363]
### Describe the Bug

I've been playing the modpack on a server perfectly fine for a while now, up until this point.
I went to check out the aether for a bit, but as I'm walking around the game crashes and I'm no longer able to enter the server due to Minecraft automatically crashing. The crash message im given on the launcher is
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1043.method_4525()" because "this.field_2048" is null
Exit code: -1

### Reproduction Steps

No clue how to recreate the bug

### Crash Report or Log

https://anotepad.com/notes/k2g3adb3

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

19.5

### Other Mods

No other mods added.

**Comment by chorbintime** [comment]
update the paradise lost mod
if the issue persists report it to their devs

in the meantime you can change your coordinates by opening your playerdata with the NBTStudio program
