### ISSUE TITLE
Snowing in incorrect areas

### ISSUE THREAD

**Issue by b1psycho** [LunaPixelStudios/Better-MC#1364]
### Describe the Bug

Where ever we go in any biome it starts snowing! Snow doesn't melt.

### Reproduction Steps

1.
2.
3.
...Just started 8/21/23, as soon as any player moves to a new spot in any biome it starts snowing. Only way to stop it is by toggling the rain button, snows on beaches, freezing the warm ocean.

### Operating System

windows 10 and 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc 3

**Comment by chorbintime** [comment]
the season is winter. wait for the season to change. this is not a bug.
