### ISSUE TITLE
mods not compatible with Forge 47.1.44

### ISSUE THREAD

**Issue by JeremyC04** [LunaPixelStudios/Better-MC#1367]
### Describe the Bug

It seems like some mods do not support forge 47.1.44. I run a Minecraft server with the modpack and when I updated the server with Better MC [FORGE] 1.20.1 v10.zip, it kept warning me about mods not loading, thus not allowing the server to start. Since I am new with the modding aspect of Minecraft I immediately went back and loaded back up server with the previous version of better MC, it still did not want to work until I saw a message stating that the twilight forest was not compatible with forge 47.1.44. I changed the server back to 47.1.3 and it worked fine, I will probably wait for another one of your updates to try to update the server, love your mod pack. I am currently running v9 of your modpack in 1.20 mc version.

### Screenshots and Videos

![Screenshot 2023-08-24 143435](https://github.com/LunaPixelStudios/Better-MC/assets/143128060/7a6ff1a2-3e2d-4b86-b02f-0c4b734d1777)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V10

**Comment by chorbintime** [comment]
you chose to use the latest forge modloader version. the modpack itself uses the old one

this isnt a modpack issue. please use the serverpack files and don't change versions of things
