### ISSUE TITLE
Have been playing with friends hosting a serer but when I launch the world it crashed after a bit

### ISSUE THREAD

**Issue by iconiclia** [LunaPixelStudios/Better-MC#1369]
### Describe the Bug

Game crashes when launching the game, I was playing normally until I found the final castle in twilight dimension. Here are the logs.

### Reproduction Steps

1. Launch Game
2. Launch Singleplayer world
3. Crash after few seconds
...

### Crash Report or Log

https://pastebin.com/Q1bg7Yx3

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 V18.5

### Other Mods

Essential

**Comment by iconiclia** [comment]
I also use ATLauncher and have reinstalled the instance

**Comment by chorbintime** [comment]
Update to v19.5. We offer no support for old versions
