### ISSUE TITLE
No server pack for BMC2 v10 Fabric.

### ISSUE THREAD

**Issue by sekuza009** [LunaPixelStudios/Better-MC#1370]
### Describe the Bug

There is no listed link for the Server Pack for Better MC [FABRIC] 1.20.1 v10 on CurseForge, and because of that it's hard to update your server to the new version.

### Reproduction Steps

1. Try to go to CurseForge to download server pack for BMC2 Fabric v10.
2. The newest version for servers listed is v9.5.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/1396541/3dee68de-b4d5-467e-a77b-021b6685617e)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2 Fabric V10

**Comment by chorbintime** [comment]
Not an issue on our side. CF still hasnt approved it. I'll talk to my curseforge contact though
