### ISSUE TITLE
Slabs will not place properly and sometime will not place at all

### ISSUE THREAD

**Issue by YTDoombringer** [LunaPixelStudios/Better-MC#1371]
### Describe the Bug

the bug is ill try place a slab then it will glitch as i try to place it and just vanish then if i run out of slabs due to the glitch i have to die or wait until they return 

### Reproduction Steps

1. place a slab
2. it will glitch sometimes not place
3. or it will be wonky and not how you wanted to place it
4. if run out of slabs either die or wait then the slabs should return to your inventory

### Screenshots and Videos

i dont have a video currently but if needed i can probably get one!!

### Operating System

Windows10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v9.5

### Other Mods

idk i dont own the world but i believe its just the bmc one atm

**Comment by chorbintime** [comment]
update the modpack
