### ISSUE TITLE
Error Code 1 on fresh install

### ISSUE THREAD

**Issue by 5haquilleOatmeal** [LunaPixelStudios/Better-MC#1372]
### Describe the Bug

Game fails to launch due to error code 1 on startup

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

1.20.1

### Other Mods

No other Mods

**Comment by chorbintime** [comment]
I can't help if you don't post any logs
