### ISSUE TITLE
Emeralds No Longer Drop From Pillagers Spawned From Soul Cages

### ISSUE THREAD

**Issue by shraeder** [LunaPixelStudios/Better-MC#1374]
### Describe the Bug

before updating to 19.5, I had two pillager farms. Neither seem to drop emeralds anymore. The only pillagers that do are naturally generated

### Reproduction Steps

1. Make a pillager Soul Cage
2. Kill any Pillager Spawned

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

19.5

**Comment by chorbintime** [comment]
Spirit cage functionality wasn't modified outside of anything in the changelog. Might be a bug with the Spirit mod
