### ISSUE TITLE
Crashing upon start with ImprovedMobs

### ISSUE THREAD

**Issue by isaq-ue** [LunaPixelStudios/Better-MC#1375]
### Describe the Bug

Hello. I'm using Better MC 3 with ImprovedMobs 1.11.0. Since I like to add a bit more difficulty to balance the opness of player that usually comes with modpacks items, I always like to use this specific mod in association. Please, could you tell me which mod is incompatible so I could remove it and add improvedmobs?

Thank you.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/83044550/44f257bd-84ec-4210-a6a9-1981dd705504)

### Crash Report or Log

https://pastebin.com/PRQ8PKxc

### Operating System

W11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3

### Other Mods

Improved Mobs.

**Comment by chorbintime** [comment]
the mod is incompatible with something, it'd be very hard to tell what. make sure you installed any dependencies, and check the mods github
