### ISSUE TITLE
You have added a mod that is incompatible with our modpack

### ISSUE THREAD

**Issue by Tommyleonardo** [LunaPixelStudios/Better-MC#1376]
### Describe the Bug

![image](https://github.com/LunaPixelStudios/Better-MC/assets/72585517/8cd15b32-f966-44e8-a722-f8197298dd9d)

### Reproduction Steps

1.Just downloaded the BMC3 from crseforge 
2.Open Tlauncher forge 1.19.2 
3.Then cannot play cause of error
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/72585517/7dbaa71c-d82b-4714-962a-4125ec2e34ee)

### Crash Report or Log

None

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v17

### Other Mods

None

**Comment by MoRoN222** [comment]
1. why T-Launcher?
2. Better Minecraft as far as I know just recently got infected with a virus of a group going around CurseForge injecting malware into popular MC mods, so if you are a victim, it's too late.

**Comment by Tommyleonardo** [comment]
uhmm frankly i am still saving up money to buy :>

anyways i found the problem, when using T-Launcher dont use the tlauncher forge version but rather download the "forge 43.2.21" version it fixed the issue for me and all mods are working

**Comment by muon-rw** [comment]
> * why T-Launcher?
> * Better Minecraft as far as I know just recently got infected with a virus of a group going around CurseForge injecting malware into popular MC mods, so if you are a victim, it's too late.

Fractureiser happened months ago and was resolved within a few days, please don’t spread misinformation. 

For future reference, Tlauncher is intentionally blocked. We do not support piracy.

**Comment by ITShet** [comment]
solution ?

**Comment by Tommyleonardo** [comment]
The problem is that the tlauncher forge version that is preloaded in the tlauncher app is outdated

i fixed it by manually downlading the forge version and picking that version on the launcher
