### ISSUE TITLE
Spawner Range

### ISSUE THREAD

**Issue by Ocpkayp6662** [LunaPixelStudios/Better-MC#1377]
### Describe the Bug

Spawner spawns the mob beyond the wall normal spawner doesnt does that even it has 16 spawn range i think its bug

### Reproduction Steps

1.Built Mob Farm
2.Saw Mobs Escape the farm even tough farm is closed
3.Some of them spawn beyond the walls 
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

2.2.6

**Comment by chorbintime** [comment]
not a bug - spawner behavior is unchanged from vanilla.
