### ISSUE TITLE
some resource packs clash with reg mc textures and some mods specifically endermen break in every resource pack i use  

### ISSUE THREAD

**Issue by Av3rry** [LunaPixelStudios/Better-MC#1378]
### Describe the Bug

read title lmao 

### Reproduction Steps

1.use a ender man retexture 
2.
3.
...

### Screenshots and Videos

![image_2023-09-08_041320230](https://github.com/LunaPixelStudios/Better-MC/assets/90588584/423f6ed3-82c4-42e8-9671-66b05f58a0c9)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v19.5

### Other Mods

n/a

**Comment by chorbintime** [comment]
please provide more details, the title is very hard to read without punctuation or properly spelled words
