### ISSUE TITLE
XP Bar Missing

### ISSUE THREAD

**Issue by CainInPain** [LunaPixelStudios/Better-MC#1380]
### Describe the Bug

My experience bar disappeared, Unsure of how to fix/ bring it back. It has happened before but I don't know how it reappeared.

### Reproduction Steps

It just disappeared idk how it happened

### Screenshots and Videos

![Screenshot (99)](https://github.com/LunaPixelStudios/Better-MC/assets/144644543/52f93dae-14b9-4ba2-b300-03dbf7afc599)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2 v19.5 bmc1

**Comment by chorbintime** [comment]
reinstall on ATLauncher
