### ISSUE TITLE
The caves are as bright as outside

### ISSUE THREAD

**Issue by Great-Honor** [LunaPixelStudios/Better-MC#1381]
### Describe the Bug

When you enter the caves, they are as bright as outside. It`s not brightness settings. Under big trees i can see shadows and dark areas. Also there can't spawn any hostile night mobs in there, like zombies, spiders, skeletons, etc. The caves become dark only at nightfall.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

Screenshot

[https://preview.redd.it/3vi0d1ag5lnb1.png?width=1920&format=png&auto=webp&s=65c46d8edfe6fc8f1f5ff04d2619f88beecf449f](url)

### Operating System

Windows 10 Home

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v60.5

**Comment by chorbintime** [comment]
remove the starlight mod

**Comment by Great-Honor** [comment]
Yeah, That`s helped. Thank you very much!

**Comment by MeowPowPow** [comment]
Ty
