### ISSUE TITLE
Multiplication of item when using grindstone

### ISSUE THREAD

**Issue by Ezakiel02** [LunaPixelStudios/Better-MC#1382]
### Describe the Bug

![image](https://github.com/LunaPixelStudios/Better-MC/assets/144790658/93c2e265-c069-44d3-86da-b33593b25671)

When disenchant an item such as tools, weapons, and armor. Putting the item in the second row, then holding shift while left-clicking the outcome will multiply the item until your inventory is full.

### Reproduction Steps

1. Put an enchanted tool into the second slot of the grindstone.
2. Hold shift and left-click the outcome.
3. Duplicate the item in your empty slot of inventory
...
![image](https://github.com/LunaPixelStudios/Better-MC/assets/144790658/dc816804-a81c-45d4-be98-d651b45f2181)

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/144790658/401159e0-a60d-406f-b3f5-71a51c479350)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC 2 - V12 (Latest)

**Comment by chorbintime** [comment]
update the guard villagers mod, if issue persists then report it to the devs of guard villagers
