### ISSUE TITLE
Elevator Mod Crashes Server

### ISSUE THREAD

**Issue by MostlyPride** [LunaPixelStudios/Better-MC#1383]
### Describe the Bug

I had some friends place elevator blocks in their base and use them just fine for a while.

Once midnight hit, the server stopped. Backed up. Then did a reboot. Upon them attempting to reconnect the server would crash.

To fix this issue I disabled the mod "elevatorid-1.20.1-1.8.15.jar". Located the areas that the elevator blocks were placed and replaced the blocks there with another.

After re-adding the same version of the mod, the server booted up normally and everyone could connect.

### Reproduction Steps

1.Place elevator blocks.
2.Have the server shut down and then start up
3.Have players attempt to reload the chunk/area of the placed elevator blocks.
...Crash

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/10325931/4c256b79-6a17-4a8a-a27d-24fcd73bd168)

![image](https://github.com/LunaPixelStudios/Better-MC/assets/10325931/1a122187-c342-4e4d-8998-9091829dbf70)

![image](https://github.com/LunaPixelStudios/Better-MC/assets/10325931/dc1bdc95-fd92-4479-ab95-398df7da09ef)

These where the oak wood logs are is where the elevator blocks were placed. Just providing the best info I can in hopes that the bug can be fixed or patched. 

### Crash Report or Log

https://gist.github.com/MostlyPride/0db7bc34bc0f024aae794d97f0991f0d

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [Forge] 1.20.1 v12 HF - (Beta) - (Current)

**Comment by chorbintime** [comment]
report it to the devs of that mod
