### ISSUE TITLE
Stone Cutter Not Working

### ISSUE THREAD

**Issue by CubanGamer67** [LunaPixelStudios/Better-MC#1384]
### Describe the Bug

Hello, playing on a private server with some friends, and after updating to the newest version of Better Minecraft our Stone Cutter is no longer working. Either Crafting recipes won't show up or we are unable to craft them. 

### Reproduction Steps

1. Make a Stone Cutter
2.Put an item in stone cutter
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/17555041/830b9d60-12e7-411f-8551-bd5be3f76986)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/17555041/898290e7-cac8-406a-a68b-c28465bff697)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V12 HF

### Other Mods

Added, DarkTimer - Clear Entities Mod, and Chunk+Pregenerator mod.

**Comment by chorbintime** [comment]
bug with the recipe essentials mod, remove it until a fix is released
