### ISSUE TITLE
Simple Storage Mod Can't scroll through inventory

### ISSUE THREAD

**Issue by CubanGamer67** [LunaPixelStudios/Better-MC#1385]
### Describe the Bug

Hello, playing on a private server with some friends, and after updating to the newest version of Better Minecraft we can no longer scroll through our inventory while using any of the remotes or request blocks. 

### Reproduction Steps

1. Used remote or request block
2. Scroll Wheel
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/17555041/bba5678f-90b0-42ff-81dc-f8637e67165a)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/17555041/83de6bba-b41c-4577-9bbd-dccd08d59d61)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/17555041/044421e6-b473-49fd-a9f6-dfe3b3416538)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V12 HF

### Other Mods

Added, DarkTimer - Clear Entities Mod, and Chunk+Pregenerator mod.

**Comment by chorbintime** [comment]
report on simple storage network github
