### ISSUE TITLE
Large Brown Mushroom not growing

### ISSUE THREAD

**Issue by Halpharox** [LunaPixelStudios/Better-MC#1386]
### Describe the Bug

Using bonemeal on a Brown Mushroom planted on Nether Mycelium won't make it grow to its large variant. (found in the Nether Mushroom Forest [Better Nether]).

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v19.5

**Comment by chorbintime** [comment]
report to better nether devs
