### ISSUE TITLE
Place block/Use Item not working in VR (quest2)

### ISSUE THREAD

**Issue by Bjrey** [LunaPixelStudios/Better-MC#1388]
### Describe the Bug

After loading into the game with default settings using oculus quest 2 with steam VR (through oculus link) it's not possible to place blocks with the A buttons (which works with normal vivecraft). I tried changing controls and pressing A shows up as right click on the controls menu. So far I haven't been able to find a way to place blocks in VR.

### Reproduction Steps

1. Set VR to On on the main menu
2. Load up a game with Oculus Quest 2 using Oculus Link and SteamVR
3. Try to place a block using the A button.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

 Better MC [FORGE] 1.20.1 v13.zip

**Comment by Bjrey** [comment]
Every other button on the controllers seems to work as expected and it’s possible to place blocks using the radial menu

**Comment by Bjrey** [comment]
I was able to find the option to bind Use /Place Item under the Modded tab in Steam VR control bindings

**Comment by chorbintime** [comment]
report to devs of vivecraft if you still have an issue
