### ISSUE TITLE
Nether portals not linking properly. remembering which portal you came through.

### ISSUE THREAD

**Issue by Darkenwolf2050** [LunaPixelStudios/Better-MC#1390]
### Describe the Bug

When building an xp farm you should be able to go from the portal at sea level to a portal in the nether then from that portal to the portal at the killzone but you are instead returned to the portal you entered through despite the killzone one being in the perfect location.

Using Better Minecraft Modpack 1.13 with no changes. I have built the farm but the sea level portals link to the one in the nether and then back to the sea level portals rather than the kill zone. The kill zone portal links to the right one in the nether but then back to the killzone.

This means the guardians just travel between the sea level portals and the nether then back again rather than into the killzone. I didn't even think that was possible.

co-ords of portals:
sea level 1 : 802,63,1232-1219
sea level 2 : 810,63,1232-1219
sea level 3 : 818,63,1232-1219

Kill Zone : 767-768,191,1189

Nether roof portal : 97-97,191,150

lilly pad 1 chunk away diagonally from sea level portals : 784,63,1200

### Reproduction Steps

1.Build xp farm on seed -7336913712698408127 at the location specified using tutorial https://www.youtube.com/watch?v=6CcbT7d4x-k
2.issue should be replicatable.

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better minecrat v13

### Other Mods

no

**Comment by chorbintime** [comment]
its a feature of the netherportalfix mod
