### ISSUE TITLE
No scroll in simple network storage interfaces 

### ISSUE THREAD

**Issue by Darkenwolf2050** [LunaPixelStudios/Better-MC#1391]
### Describe the Bug

Open any simple storage interface and you cannot scroll the items. I have tried clicking in the search box, out of the search box in the item display space but no interface will scroll through contained items. Tried remote interface and standard as well as crafting interface. No scroll on any of them. Item searching still works. 

### Reproduction Steps

1.build a simple network storage using a few chests
2.add a storage interface 
3.put 100 different types of items into storage network
4.attempt to scroll through items
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

13

### Other Mods

No

**Comment by chorbintime** [comment]
report it to the developers of that mod
