### ISSUE TITLE
Mod Elevatorsid crash game and server

### ISSUE THREAD

**Issue by LastWardMZ** [LunaPixelStudios/Better-MC#1392]
### Describe the Bug

The elevator mod crashes the game and servers when used and corrupts the area where the elevator was placed..

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v12 HF & v13

**Comment by chorbintime** [comment]
report it to the developers of that mod

**Comment by TigerWalts** [comment]
Bug has already reported:

https://github.com/VsnGamer/ElevatorMod/issues/119
