### ISSUE TITLE
Can't move when in combat with Tiger

### ISSUE THREAD

**Issue by Gamarleton** [LunaPixelStudios/Better-MC#1393]
### Describe the Bug

I snuck up behind a tiger that was stuck in a fenced off area and sprint-slashed it so it flew away from me a bit. But even though it was 3 blocks away from me I couldn't move at all, so no matter what you do when you're in combat with a tiger you can't move. This does not make sense so I figured it was a bug. 

### Reproduction Steps

1. Make sure the tiger is either not looking at you or fenced in where they shouldn't be able to reach you that well.
2. Hit it while sprinting and make sure you don't get too close before the strike hits the tiger so you make sure they are too far away to technically be able to reach you.
3. Notice you cannot move, back away or sidestep when it jumps you. 

### Crash Report or Log

https://gist.github.com/Gamarleton/dc6ecdb62571bab378d061866b15a21c

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v13

**Comment by chorbintime** [comment]
report it to the devs of the mod that adds the tiger
