### ISSUE TITLE
BMC1 - Crash on world load hits 100%

### ISSUE THREAD

**Issue by SelenZzz** [LunaPixelStudios/Better-MC#1395]
### Describe the Bug

BMC1 installed with CurseForge
After opening saved game, when loader hits 100% game crashes

### Reproduction Steps

1. open game
2. open saved world
3. wait until load gets 100%

### Crash Report or Log

https://gist.github.com/SelenZzz/9412e130273a46f12976162c5d77bd33

### Operating System

macOs Ventura 13.5.2 ARM M1 PRO

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v19.5

**Comment by chorbintime** [comment]
update the xaeros minimap & worldmap mods
if issue persists report it to their devs
