### ISSUE TITLE
BMC4 game stops when trying to load into world

### ISSUE THREAD

**Issue by SirSpagetBoy** [LunaPixelStudios/Better-MC#1396]
### Describe the Bug

game stops when trying to load into world

### Reproduction Steps

1. start game
2. wait
3. click singleplayer
4. click world
5. game stops

### Screenshots and Videos

https://www.dropbox.com/scl/fi/128vkyqkfh7dsqg2udh5r/2023-09-22-15-58-06.mp4?rlkey=x728txjqcc82id3w4qfs1p7fy&dl=0

### Crash Report or Log

https://www.dropbox.com/scl/fi/495md7phie1b8c7p594d7/latest.log?rlkey=0b9dvi2cyfevtitqm3h9dpvtp&dl=0

### Operating System

win 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v13

**Comment by chorbintime** [comment]
Reinstall on ATLauncher
