### ISSUE TITLE
Vinery Mod - Stopped working, grape juice turns back into wine bottles

### ISSUE THREAD

**Issue by Suriel08** [LunaPixelStudios/Better-MC#1397]
### Describe the Bug

This mod worked fine first on our server. Now when I harvest grapes, I can put 6 into the vine pot, turn them into grape juice.
But when I use wine bottles on the pot, the level in the pot doesn't lower. I can turn all wine bottles into grape juice.
Or just a few of them.
When I move a little then or activate the aging barrel, all grape juice bottles turn back into wine bottles. I cannot use them.

Addition: I had some other players test and it still works for them.

### Reproduction Steps

1. Use grapes on pot.
2. Fill bottles with grape juice
3. Watch grape juice turn back into wine bottles.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Minecraft Medieval MMC1 Fabric

### Other Mods

Only those included in the Modpack.

**Comment by chorbintime** [comment]
report to dev of Vinery mod

**Comment by kb8tfe-gif** [comment]
Has this issue been resolved?

**Comment by chorbintime** [comment]
please refer to my previous response
