### ISSUE TITLE
Cannot reach above 20 FPS (1.20/1.20.1)

### ISSUE THREAD

**Issue by JustArkzy** [LunaPixelStudios/Better-MC#1399]
### Describe the Bug

I am unable to get above 20 fps. (Almost like there is a secret setting limiting my fps from going higher)

My FPS limit is set to unlimited in-game.

Before the bug I averaged around 100-120 fps with shaders on. Now, all the sudden, no matter what I do I can't get above 20 fps.
I've tried increasing my memory to 10gbs, I have tried turning shaders off, and I even restarted my pc. Nothing seems to fix my FPS.

I am unaware of how it was even occured so the reproduction is my best guess.

### Reproduction Steps

1. I made a slab (Stone, if that matters)
2. placed it down in my base (Small, has 12 chests, a bed, 2 blast furnaces, 2 smokers, and a crafting table.)
3. I was trying to place it in the center but with the vertical slab mod it was bugging out a bit, not appearing, etc. I placed some blocks to make sure there weren't ghost blocks.
4. I finally placed the slab down where i wanted, and about 5-10 minutes after, the fps dropped drastically.

### Screenshots and Videos

![2023-09-22_20 48 56](https://github.com/LunaPixelStudios/Better-MC/assets/105407199/f165021b-759b-4087-99b9-ea8edc39da99)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC v13

### Other Mods

MiniHud (https://www.curseforge.com/minecraft/mc-mods/minihud)
ReplayMod (https://www.replaymod.com/download/)

**Comment by chorbintime** [comment]
Update the Autoslabs mod
if issue persists, report it to the dev of the mod

**Comment by JustArkzy** [comment]
> Update the Autoslabs mod if issue persists, report it to the dev of the mod

Just checked, mod doesn't need updated according to the CurseForge profile.

**Comment by JustArkzy** [comment]
If anyone else has this problem, I disabled the AutoSlabs mod and it worked.

**Comment by chorbintime** [comment]
Report it to the developer of AutoSlabs or the issue will not be fixed.

**Comment by JustArkzy** [comment]
Happened again with the mod off, not the mod, must've been a coincidence. I will try to see if I can fix it.

**Comment by JustArkzy** [comment]
Found the problem, interference with MSI-Afterburner. Whenever I my keybind for Toggle Overlay, it drops my frames to 20 max.
