### ISSUE TITLE
Stuck in nether

### ISSUE THREAD

**Issue by Guadidy** [LunaPixelStudios/Better-MC#1400]
### Describe the Bug

Went into the nether, around 5 minutes later my game crashes. I proceed to venture the nether and come back to my nether portal which I made a waypoint for, only to find its disappeared. I assume the crash took me back a few minutes within game time and deleted my previous blocks but didn't change where I was standing.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot](https://github.com/LunaPixelStudios/Better-MC/assets/145868060/984e4c51-c874-4c82-bac5-041ece2e046d)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC 1

**Comment by chorbintime** [comment]
cant help without a crash report

if you need help getting out you can press escape, open to lan, and allow cheats there

if you're on multiplayer just op yourself & go into creative then build a nether portal
