### ISSUE TITLE
[Bug][BMC4] Aether FTB Quest Random Reward Gives Me No Items

### ISSUE THREAD

**Issue by chemlzh** [LunaPixelStudios/Better-MC#1401]
### Describe the Bug

I have updated BMC Forge 1.20.1 to v14, then entered the aether dimension. The FTB Quest showed that I have done the first Aether quest, therefore could obtain a random reward. However, I click the reward button, and no items gave me. Maybe you have forgotten to write the reward table, so you'd better fill it in. Thanks!

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC Forge 1.20.1 v14

**Comment by chorbintime** [comment]
will be fixed in v15
