### ISSUE TITLE
Really bugged out main menu

### ISSUE THREAD

**Issue by FanaticExplorer** [LunaPixelStudios/Better-MC#1402]
### Describe the Bug

Just downloaded the modpack from CurseForge and ran into some issues. First, the main menu is glitched, as you can see in my screenshot. Second, Ukrainian language was added even though my system is set to Russian and I usually play in English. Removing Ukrainian and restarting didn't fix the issue.

Also, the menu disappears when I go to settings and come back. I have to resize the window to get it back. I've allocated 7 GB of RAM, so that shouldn't be the problem.

### Reproduction Steps

1. Be Ukrainian
2. Download modpack from curseforge
3. Launch it

### Screenshots and Videos

![javaw_DO60FEG9HN](https://github.com/LunaPixelStudios/Better-MC/assets/52747818/ecc4f8e8-ad91-498e-982f-e0f1666b672f)

### Operating System

Windows 10 Home

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v19.5

**Comment by FanaticExplorer** [comment]
Update: I managed to improve the situation by removing FancyMenu and drippyloadingscreen, but then the changelog button overlapped with the singleplayer button. After also removing ModpackUpdateChecker, the main menu reverted to a more vanilla look but is now functional.

**Comment by chorbintime** [comment]
You likely installed the modpack incorrectly.

Reinstall using ATLauncher.
