### ISSUE TITLE
this.moonlight$customDecorations\" is null

### ISSUE THREAD

**Issue by Nynetoez** [LunaPixelStudios/Better-MC#1403]
### Describe the Bug

This happened when I picked up something in my inventory. (Not sure what exactly, I broke a chest and grabbed all the items).
Game crashed and displayed this message:

"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot read the array length because \"this.moonlight$customDecorations\" is null"

Now every time I log into my server, it kicks me out immediately.

### Reproduction Steps

1. Pick up corrupted item ( a guess)
2. Game crashes
3.
...

### Crash Report or Log

https://gist.github.com/Nynetoez/fbc48c2e5781e8eb6e57319d661bc13b

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v14

**Comment by chorbintime** [comment]
Can you pinpoint which item caused it?

**Comment by Nynetoez** [comment]
No, but completely wiping my inventory fixed it

**Comment by Sonamiya** [comment]
Getting the same error when opeing a blank vanilla Minecraft map

**Comment by chorbintime** [comment]
> Getting the same error when opeing a blank vanilla Minecraft map

That is a different issue.
Update the Moonlight Lib mod.
