### ISSUE TITLE
Issue with StoneCutter

### ISSUE THREAD

**Issue by dozio** [LunaPixelStudios/Better-MC#1405]
### Describe the Bug

StoneCutter doesn't show all crafting recepies

### Reproduction Steps

1. Craft a Stoencutter
2. Place a stack of cobblestone

Expected Result
- Ability ti choose between stairs, slabs, twigs custom items.

Real Result
- Can only craft Stone walls

This applies to all stonecutting blocks

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v14

**Comment by SHXRKIIE** [comment]
I guess it will be fixed in v15? it doesnt seem to happen in my new test
