### ISSUE TITLE
all byg sandstones cannot be crafted

### ISSUE THREAD

**Issue by treinebbie** [LunaPixelStudios/Better-MC#1406]
### Describe the Bug

something is wrong with the recipes for sandstone in Oh The Biomes You'll Go. They all require error tags for their respective sand colors instead of the actual sand.

### Reproduction Steps

try to craft any byg sandstone

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/116917034/da5dcc62-5cc9-4585-9f0f-ba18c6a15c97)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/116917034/d31b89a4-844c-4a54-968c-d2dc8df10de3)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v18

**Comment by chorbintime** [comment]
Report it to the developers of Oh The Biomes You'll Go
