### ISSUE TITLE
BMC4 1.20.1 V14 - Crash when launching the game

### ISSUE THREAD

**Issue by Julien107** [LunaPixelStudios/Better-MC#1407]
### Describe the Bug

When I click play from curseforge with this modpack, everything goes well for the first part with the red interface and loading bars. At the end of the second part, with the minecraft loading bar and a picture of the game in the background, when the bar complete, it crashes. Please look at the crash report on https://gist.github.com/Julien107/091be5d0f6296348421ec0ac8bab7810
Thanks!

### Reproduction Steps

1.Click play on curseforge with this modpack
2.Wait for the crash at the end
3.
...

### Screenshots and Videos

![1](https://github.com/LunaPixelStudios/Better-MC/assets/75165112/c5d62bd2-23f7-4c00-bfbf-7f61a1f138b0)
![2](https://github.com/LunaPixelStudios/Better-MC/assets/75165112/802a5253-a7ce-4393-b17b-c53a2744091a)

### Crash Report or Log

https://gist.github.com/Julien107/091be5d0f6296348421ec0ac8bab7810

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V1.20.1 V14

### Other Mods

No

**Comment by chorbintime** [comment]
Remove the Controllable mod and report it to the mod developer
