### ISSUE TITLE
i can't run, jump, etc. red bindings

### ISSUE THREAD

**Issue by ghostkid5747** [LunaPixelStudios/Better-MC#1408]
### Describe the Bug

i've gotten this on both the fabric and forge versions today that i can't use certain functions, and even when i try to change key bindings to not be conflicted they are still red and i can't use the function. i was playing bmc 1.16 and didn't notice that it was that version until i realized it all stopped at y0, then i found the other versions for 1.18 (fabric) and 1.19 (forge) and both of them are having the same issue, even tho b,c 1.16 (forge) was working fine 5 minutes before trying the other versions. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/146132647/24ee3c31-7e23-4e6a-bb38-694673ff797d)

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3

**Comment by ghostkid5747** [comment]
i'm not extremely tech savvy, i just know how to make things functional, so idk what to do

**Comment by chorbintime** [comment]
Reinstall using ATLauncher and make sure you are on the latest version of the modpack

**Comment by ghostkid5747** [comment]
i've been using curseforge and i was using one that was updated 1 day ago

**Comment by chorbintime** [comment]
Reinstall the modpack on ATLauncher instead of CF
