### ISSUE TITLE
my game crashes everytime i try open a world

### ISSUE THREAD

**Issue by peachycee** [LunaPixelStudios/Better-MC#1409]
### Describe the Bug

when i open a world as soon a it loads it crashes straight away. i am also on macbook

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

<img width="583" alt="Screen Shot 2023-09-28 at 2 26 42 pm" src="https://github.com/LunaPixelStudios/Better-MC/assets/146311362/949b843a-f06f-485f-913a-36b61c2777c0">

### Crash Report or Log

6

### Operating System

macbook air (M1, 2020)

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

1.19.2

### Other Mods

i dont have any other mods

**Comment by SHXRKIIE** [comment]
Need logs

**Comment by texel** [comment]
Hi @SHXRKIIE I'm running into the same issue on two different ARM Macs using the Curseforge launcher. 

[Here's a crash log](https://github.com/LunaPixelStudios/Better-MC/files/12773059/hs_err_pid872.log)

I'm running a vanilla version of the FORGE BMC4 mod 1.20.1 v15, but it's happening with earlier versions of BMC4 as well.

It's working fine in ATLauncher, and the difference from what I can tell is that ATLauncher is using the JRE bundle for `java-runtime-gamma` at 17.0.3, and Curseforge is using 17.0.8.

I haven't dug in to understand how to control the runtime version, but I assume that's related to the Minecraft Launcher? Not a Java or Minecraft mod dev, so I'm still learning the ropes 😎 

I can try getting you more info if it's helpful!

**Comment by Frontear** [comment]
This is an M1 Mac specific bug unfortunately. Java 17.0.9 and above will fix this bug, as will Java 17.0.6 and below.

The reason ATLauncher works is because the bug was introduced in Java 17.0.7, fixed in Java 17.0.9.

You can read about this bug here: https://bugs.openjdk.org/browse/JDK-8283326

**Comment by texel** [comment]
@Frontear yeah I found that bug report and figured it was related.

I know it's a bit out of scope here, but is there a way to control either the launcher version that Curseforge uses, or the runtime version that the launcher bundles?

I'm guessing that I can also install my own version of the JRE and point the launcher at it...

**Comment by Frontear** [comment]
Unfortunately Curseforge specifically does not provide a way to easily change the launcher. Your best bet would be to use ATLauncher and change the JRE you're using from it.

Curseforge, by default, bundles whatever Microsoft recommends, which is Microsoft OpenJDK 17.0.8, which also, by unfortunate coincidence, is bugged for M1 Macs. Your only choice would be ATLauncher, and if you desire, you can grab a copy of any new JRE and point ATLauncher to use it instead.

**Comment by texel** [comment]
Ah yep, just as I feared 😂

Thanks for the info though this gives me enough to work around it until the launcher gets updated!
