### ISSUE TITLE
Neruina server tick bug

### ISSUE THREAD

**Issue by ViceBanshee52** [LunaPixelStudios/Better-MC#1411]
### Describe the Bug

I host a Better MC 4 server for my friends and I and ever since the new update I cannot join the server, however they can join fine.

### Reproduction Steps

1. Host the server
2. Launch BMC4
3. Join server
...

### Screenshots and Videos

![Screenshot (2)](https://github.com/LunaPixelStudios/Better-MC/assets/130810904/a4e4ac5c-fbdb-4ec7-afa9-a182c43d03e0)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v15

**Comment by SHXRKIIE** [comment]
Need logs

**Comment by ViceBanshee52** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/12756291/latest.log)

Here you go

**Comment by SHXRKIIE** [comment]
Remove Neruina and see if you can join, if you are not able to see if deleting your playerdata fixes it?

**Comment by muon-rw** [comment]
Update Moonlight Lib on the client and server.
