### ISSUE TITLE
(Main Hand) You are not allow to interact with this block

### ISSUE THREAD

**Issue by Sanling123213** [LunaPixelStudios/Better-MC#1412]
### Describe the Bug

I play in Singleplayer Mode and after a while after 2-3 days of playing. I couldn't destroy blocks in the game. I can still craft, open chest, etc. I wonder what is going on. I still want to continue my journy.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/146421866/03115c02-8280-490b-af78-046486fe7cec)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BetterMinecraft BMC3

**Comment by justaguy123321** [comment]
im also having this problem how do i fix it

**Comment by pristupnikk** [comment]
its probably because of plugin, that makes private in Xaero's map. That's what was my problem, but maybe there's the same error in diff situation. good luck, if i helped someone

**Comment by akio1g** [comment]
I had this problem, and I didn’t have any plugins on my server. The way I solved it was by going to the ./world/serverconfig folder.

In the following files:

- openpartiesandclaims-default-player-config.toml
- openpartiesandclaims-expired-claim-config.toml
- openpartiesandclaims-server-claim-config.toml
- openpartiesandclaims-wilderness-config.toml

I set claims.protectClaimedChunks to **false**.
