### ISSUE TITLE
BMC3 Forge Neapolitan Mint

### ISSUE THREAD

**Issue by Erxti** [LunaPixelStudios/Better-MC#1413]
### Describe the Bug

Unable to find mint in any biome, is it an issue caused by BYG ? It's supposed to spawn in mountains near small lake.

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v18

**Comment by chorbintime** [comment]
Vanilla biomes still spawn with BYG. My guess is you're just unlucky - you could ask the Neapolitan developers for more specific details on how mint spawns, though.
