### ISSUE TITLE
Lagging all of a sudden

### ISSUE THREAD

**Issue by Gooseman234** [LunaPixelStudios/Better-MC#1414]
### Describe the Bug

I was playing Better Minecraft for a few days, then all of a sudden i booted it and it was lagging like hell, even on the main menu.
I uninstalled it and redownloaded it again and got the same issue.

Any help?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

**Comment by chorbintime** [comment]
follow the performance guide https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide
