### ISSUE TITLE
"tried to read nbt tag with too high complexity depth 512" seems to be back

### ISSUE THREAD

**Issue by scameronde** [LunaPixelStudios/Better-MC#1415]
### Describe the Bug

- Singleplayer
- BMC3 Forge v18 and v19
- installed and launched using GD-Launcher

After entering the woodland mansion and fighting an evoker that summons fangs, my savefile is corrupted reproducibly (I have a backup of the savefile from just before the encounter, so I can retest the situation).

### Reproduction Steps

1. Enter woodland mansion
2. Fight evoker
3. Save / Reload
4. Bang!
5. 

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 v19

**Comment by muon-rw** [comment]
Please send the full crash report/log

**Comment by scameronde** [comment]
Will do.

I also did a few more tests. I thought previously, that fighting the evoker causes the problem. I was wrong. Entering the woodland mansion is enough to wreck the save file. 

If you want, you can have my save file just prior to enter the building. It is a 330 MB ZIP file.

btw: in my log file the relevant stack trace starts at / with

[14:55:02] [Render thread/ERROR]: Exception reading ..\..\instances\BMC3v19\saves\Explore This (1)\level.dat
java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512

**Comment by scameronde** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/12777217/latest.log)

**Comment by scameronde** [comment]
https://u.pcloud.link/publink/show?code=VZVBnvVZXVrueSEun7jrXsTJCJKv54HNub8k

You can access two save files using this link. One is outside the building (the earlier one) and one from inside the building. When I save from outside the building and reload, everything is OK. When I save from inside the building and reload, I am getting the error.

**Comment by muon-rw** [comment]
This really has nothing to do with where you are specifically, but is just a weird worldgen bug that accumulates over time. 

It should be fixed in v19, though, which is concerning.

I can at least fix your level.dat for now. I’ll do so later today

**Comment by scameronde** [comment]
Thank you! And no hurry. I just ended a 12-hour work shift. All that I am doing for the next 10 hours is sleeping ;-)

**Comment by muon-rw** [comment]
Try replacing the `level.dat` file in your saves folder with this one:

https://cdn.discordapp.com/attachments/973331886103474236/1158255908414046208/level.dat

Which versions of Citadel and Terrablender do you have?

**Comment by scameronde** [comment]
Thank you!

Citadel: 2.1.4
Terrablender: 2.0.1.166

I am currently running v19, the world was started with v17 and the part I am currently in was generated with v18.

**Comment by muon-rw** [comment]
Thanks. 

Looking further into this issue it just looks like worlds which were started on older versions keep the bug when updating, and it has to be fixed manually. 

For future reference, the issue will persist unless you:
- Update to the latest version of Citadel
- Make a new world with the same seed and settings 
- Copy the overworld surface rules compound tag from the new level.dat and overwrite your existing one


The file I sent should work. Feel free to reopen if you still have problems.

**Comment by scameronde** [comment]
Thank you a lot for your help. As far as I am concerned, the bug is resolved.
