### ISSUE TITLE
Crashes at start

### ISSUE THREAD

**Issue by YisuiDenghua** [LunaPixelStudios/Better-MC#1416]
### Describe the Bug

Better MC crashes at start. To disable Modpack Update Checker before first run can solve the problem at present.

### Reproduction Steps

1. Launch Better-MC Fabric v19.5 via PrismLauncher
2.
3.
...

### Crash Report or Log

https://gist.github.com/YisuiDenghua/dbb8d8360a0539393f0e7e33066568cb

### Operating System

Gentoo Linux

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v19.5

**Comment by chorbintime** [comment]
just a bug with the older versions of MPUC, you can update the mod instead
