### ISSUE TITLE
Magic Map + Magic Maze Map Twilight Forest Causes Ticking Player disconnect

### ISSUE THREAD

**Issue by ZacOT** [LunaPixelStudios/Better-MC#1417]
### Describe the Bug

When player has a Magic Map or Magic Maze Map Twilight Forest Causes Player Ticking error + disconnect

### Reproduction Steps

1. Take Blank Magic / Magic Maze Map
2. Activate the Blank Map
3. Cause Player Ticking Crash Client side and can't reconnect
...

### Screenshots and Videos

![bug1](https://github.com/LunaPixelStudios/Better-MC/assets/62330525/cbce384e-09c2-4ee6-90a3-46cc2bc07c60)
![bug2](https://github.com/LunaPixelStudios/Better-MC/assets/62330525/b84ecb37-0821-4a1a-aabf-6219c91e87ba)
![bug3](https://github.com/LunaPixelStudios/Better-MC/assets/62330525/748a5f52-6cc2-41bd-9786-ac8eb0f76b8c)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v15 HF

**Comment by muon-rw** [comment]
Update Moonlight Lib
