### ISSUE TITLE
BMC4 forge crash bug

### ISSUE THREAD

**Issue by Jeve-Sobs** [LunaPixelStudios/Better-MC#1419]
### Describe the Bug

On the server list menu if you click the arrow to move a sever up you get an index out of bounds exception and the game crashes

### Reproduction Steps

1.Launch game
2.Open multiplayer 
3.Click up arrow on server 
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

V15HF

**Comment by qwek1** [comment]
Send logs please.

**Comment by SHXRKIIE** [comment]
Fixed in v16
