### ISSUE TITLE
Twilight Forest empty map causing game to crash

### ISSUE THREAD

**Issue by DropDeadDarling** [LunaPixelStudios/Better-MC#1420]
### Describe the Bug

So me and some friends are playing on a world together using Better MC mod and when we went to the Twilight forest and opened the Blank Magic Map our game crashed. We've tried uninstalling and reinstalling Better MC as well as the Twilight Forest mod separately but it still keeps on crashing. Not sure if I should be posting this here or on the Twilight Forest forum so sorry if this is the wrong place. Any help would be much appreciated! 

### Reproduction Steps

1. Go to the Twilight Forest Dimension 
2. Open the Blank Magic Map
3.
4.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v15

### Other Mods

We are using Essential mod to play together but I'm able to recreate the crash without it.

**Comment by qwek1** [comment]
Try updating Moonlight Lib
