### ISSUE TITLE
BM3 1.19.2 V19 crashes on start

### ISSUE THREAD

**Issue by itsjermey** [LunaPixelStudios/Better-MC#1421]
### Describe the Bug

game just crashes and gives me exit code 1 and i dont know what is causing it could you please help me thank you.

### Reproduction Steps

1. downloaded BM3 Forge 1.19.2 V2
2. click launch
3. crashes exit code 1 error
...

### Screenshots and Videos

![Screenshot 2023-10-03 092421](https://github.com/LunaPixelStudios/Better-MC/assets/81801784/f117f641-70af-4856-93de-429ab064218d)

### Crash Report or Log

https://gist.github.com/itsjermey/1411217de2cb0c601cf4d76302e499e7

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v19

### Other Mods

none

**Comment by qwek1** [comment]
Update your Drivers directly through your vendors wesbite.

**Comment by itsjermey** [comment]
after updating my AMD Cpu drivers it now works properly
