### ISSUE TITLE
BMC4 Game Crash

### ISSUE THREAD

**Issue by ninuh** [LunaPixelStudios/Better-MC#1422]
### Describe the Bug

When launching the game, it tries to load and then comes up with Game crashed error box.

### Reproduction Steps

1. Clicked Play on Curseforge.
2. When launcher opened, clicked Play on the Launcher.
3. Initialising and then the game crashed.

### Screenshots and Videos

![Picture2](https://github.com/LunaPixelStudios/Better-MC/assets/125196027/ea54668f-f614-43d3-9244-5770c5649879)

### Crash Report or Log

https://pastebin.com/JkAvwZeQ

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v14

### Other Mods

No

**Comment by SHXRKIIE** [comment]
Reinstall or try ATlauncher, its CFLauncher issue
