### ISSUE TITLE
BMC4 Game crashes at world gen

### ISSUE THREAD

**Issue by UsamaKhan** [LunaPixelStudios/Better-MC#1423]
### Describe the Bug

The game launches and when I go to create a new world, the game crashes.

There is also a visual glitch on game load where the game takes up the bottom left quarter of the window instead of the whole window

### Reproduction Steps

1. Launch the game
2. Click Single Player
3. Create new world
4. Game crashes

### Screenshots and Videos

<img width="966" alt="image" src="https://github.com/LunaPixelStudios/Better-MC/assets/3194581/f735ca8f-79f2-4aa6-a35f-2a82a0343a60">

### Crash Report or Log

https://mclo.gs/rgkeQBO

### Operating System

macOS 14.0 (23A344)

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v15 HF

**Comment by L0oty** [comment]
Did this get fixed I am having this problem also
