### ISSUE TITLE
BMC2 Game crashes at world gen

### ISSUE THREAD

**Issue by UsamaKhan** [LunaPixelStudios/Better-MC#1424]
### Describe the Bug

The game launches and when I go to create a new world, the game crashes.

### Reproduction Steps

1. Launch the game
2. Single player
3. Create new world
...

### Crash Report or Log

https://mclo.gs/DvWPmXG

### Operating System

macOS 14.0 (23A344)

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC v15 HF

**Comment by baileylopez** [comment]
This same thing has been happening to me! I asked all my friends if they knew what was happening and they had no idea. Hopefully, it will be figured out soon because I really want to try out Better MC. Everyone I've talked to loves Better MC so I'm pretty disappointed I didn't get that experience.

**Comment by SHXRKIIE** [comment]
We don't test modpacks on MacOS but the solution to this is not the modpack but the java version that the launcher installs it with, you need Java 17.0.9 or 20/21 in order to play on MacOS

**Comment by UsamaKhan** [comment]
> We don't test modpacks on MacOS but the solution to this is not the modpack but the java version that the launcher installs it with, you need Java 17.0.9 or 20/21 in order to play on MacOS

Java 17.0.9 hasn't been released yet. I have tried on 17.0.8 and get this crash. Tried 21 and I get the following error on Prism Launcher:

```
This instance is not compatible with Java version 21.
Please switch to one of the following Java versions for this instance:
Java version 17
Go to instance Java settings to change your Java version or disable the Java compatibility check if you know what you're doing.
```

**Comment by UsamaKhan** [comment]
Also, I dont think this is an error with the java version as I am able to load Minecraft with fabric/forge and mods, just not BMC. 

Here is a log of Minecraft 1.20.1 with Fabric running successfully: https://mclo.gs/fCVJrXd

**Comment by pironc** [comment]
Installing the latest Temurin version (aarch64 / macOS - https://adoptium.net/en-GB/temurin/releases/?version=18&os=mac&arch=aarch64&package=any) and using the path in ATLauncher and not CurseForge fixes the issue.

https://github.com/LunaPixelStudios/Medieval-MC/wiki/Performance-Guide Follow the following for ATLauncher settings.
macOS path for Temurin is **/Library/Java/JavaVirtualMachines/temurin-18.jre/Contents/Home/bin/java**
