### ISSUE TITLE
BMC4 Game Crash Random

### ISSUE THREAD

**Issue by NunzioArdi** [LunaPixelStudios/Better-MC#1425]
### Describe the Bug

At a random moment (afk or not), the game crashes.
I use the version of java recommended in the documentation: Adoptium

### Crash Report or Log

Log: https://pastebin.com/zDtq6jbD | Crash: https://gist.github.com/NunzioArdi/5d45c665c4d2b640211d0739c967cd32

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v15

**Comment by SHXRKIIE** [comment]
There is insufficient memory for the Java Runtime Environment to continue.
Please allocate more ram

**Comment by NunzioArdi** [comment]
the XMX is at 9984MiB. Beyond that, the game tells me I'm allocating too much if I put in more than 10Gib!
I'm sorry, but I don't think that's where the problem lies, as your documentation says 5G min.
I've set the XMS to 5120MiB and after 30 min of play there's still a crash.
```
[15:14:01] [Chunk Render Task Executor #9/ERROR] [me.je.mo.so.cl.ut.NativeBuffer/]: EMERGENCY: Tried to allocate 74880 bytes but the allocator reports failure
[15:14:01] [Chunk Render Task Executor #9/ERROR] [me.je.mo.so.cl.ut.NativeBuffer/]: EMERGENCY: ... Attempting to force a garbage collection cycle (attempt 1/3)
```
(sorry for my english i use translator)
