### ISSUE TITLE
twilight forest magic map crash

### ISSUE THREAD

**Issue by sooda600** [LunaPixelStudios/Better-MC#1426]
### Describe the Bug

my game keeps crashing wont even open the main menu 

### Reproduction Steps

1. Killed Naga 
2.got magic map from quest tab
3.game crashed
...

### Crash Report or Log

---- Minecraft Crash Report ---- // Don't do that.  Time: 2023-10-04 18:53:58 Description: Rendering overlay  java.lang.ExceptionInInitializerError: null 	at com.aizistral.nochatreports.common.config.NCRConfig.load(NCRConfig.java:51) ~[NoChatReports-FORGE-1.20.1-v2.2.2.jar%23515!/:1.20.1-v2.2.2] {re:mixin,re:classloading} 	at com.aizistral.nochatreports.common.config.NCRConfig.checkLoaded(NCRConfig.java:44) ~[NoChatReports-FORGE-1.20.1-v2.2.2.jar%23515!/:1.20.1-v2.2.2] {re:mixin,re:classloading} 	at com.aizistral.nochatreports.common.config.NCRConfig.getClient(NCRConfig.java:29) ~[NoChatReports-FORGE-1.20.1-v2.2.2.jar%23515!/:1.20.1-v2.2.2] {re:mixin,re:classloading} 	at net.minecraft.client.gui.components.toasts.ToastComponent.handler$bno000$onAddToast(ToastComponent.java:520) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinToastComponent,pl:mixin:APP:sodium-extra.mixins.json:toasts.MixinToastManager,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.components.toasts.ToastComponent.m_94922_(ToastComponent.java) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinToastComponent,pl:mixin:APP:sodium-extra.mixins.json:toasts.MixinToastManager,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.components.toasts.SystemToast.m_94855_(SystemToast.java:141) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,re:classloading,pl:mixin:APP:sodium-extra.mixins.json:toasts.MixinSystemToast,pl:mixin:A} 	at net.minecraft.client.gui.components.toasts.SystemToast.m_94869_(SystemToast.java:147) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,re:classloading,pl:mixin:APP:sodium-extra.mixins.json:toasts.MixinSystemToast,pl:mixin:A} 	at net.minecraft.client.Minecraft.m_271937_(Minecraft.java:694) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_272186_(Minecraft.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$reloadResourcePacks$26(Minecraft.java:882) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.Util.m_137521_(Util.java:419) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:A} 	at net.minecraft.client.Minecraft.lambda$reloadResourcePacks$28(Minecraft.java:880) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.LoadingOverlay.m_88315_(LoadingOverlay.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:rubidium_extras.mixins.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.GameRendererMixin,pl:mixin:APP:forge-immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {} Caused by: java.lang.NullPointerException: Cannot invoke "com.aizistral.nochatreports.common.platform.PlatformProvider.getConfigDir()" because the return value of "com.aizistral.nochatreports.common.NCRCore.getProvider()" is null 	at com.aizistral.nochatreports.common.config.JSONConfig.<clinit>(JSONConfig.java:20) ~[NoChatReports-FORGE-1.20.1-v2.2.2.jar%23515!/:1.20.1-v2.2.2] {re:mixin,re:classloading} 	... 32 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at com.aizistral.nochatreports.common.config.NCRConfig.load(NCRConfig.java:51) ~[NoChatReports-FORGE-1.20.1-v2.2.2.jar%23515!/:1.20.1-v2.2.2] {re:mixin,re:classloading} 	at com.aizistral.nochatreports.common.config.NCRConfig.checkLoaded(NCRConfig.java:44) ~[NoChatReports-FORGE-1.20.1-v2.2.2.jar%23515!/:1.20.1-v2.2.2] {re:mixin,re:classloading} 	at com.aizistral.nochatreports.common.config.NCRConfig.getClient(NCRConfig.java:29) ~[NoChatReports-FORGE-1.20.1-v2.2.2.jar%23515!/:1.20.1-v2.2.2] {re:mixin,re:classloading} 	at net.minecraft.client.gui.components.toasts.ToastComponent.handler$bno000$onAddToast(ToastComponent.java:520) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinToastComponent,pl:mixin:APP:sodium-extra.mixins.json:toasts.MixinToastManager,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.components.toasts.ToastComponent.m_94922_(ToastComponent.java) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinToastComponent,pl:mixin:APP:sodium-extra.mixins.json:toasts.MixinToastManager,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.components.toasts.SystemToast.m_94855_(SystemToast.java:141) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,re:classloading,pl:mixin:APP:sodium-extra.mixins.json:toasts.MixinSystemToast,pl:mixin:A} 	at net.minecraft.client.gui.components.toasts.SystemToast.m_94869_(SystemToast.java:147) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,re:classloading,pl:mixin:APP:sodium-extra.mixins.json:toasts.MixinSystemToast,pl:mixin:A} 	at net.minecraft.client.Minecraft.m_271937_(Minecraft.java:694) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_272186_(Minecraft.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$reloadResourcePacks$26(Minecraft.java:882) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.Util.m_137521_(Util.java:419) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:A} 	at net.minecraft.client.Minecraft.lambda$reloadResourcePacks$28(Minecraft.java:880) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.gui.screens.LoadingOverlay.m_88315_(LoadingOverlay.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:classloading,pl:runtimedistcleaner:A} -- Overlay render details -- Details: 	Overlay name: ~~ERROR~~ NullPointerException: Cannot invoke "Object.getClass()" because the return value of "net.minecraft.client.Minecraft.m_91265_()" is null Stacktrace: 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:rubidium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:rubidium_extras.mixins.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.GameRendererMixin,pl:mixin:APP:forge-immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: No 	Packs: vanilla, file/NoBushyLeaves.zip, file/Icons.zip, file/Created Simple Storage 1.3.zip, file/Mandalas_Legacy_Gui_Background.zip, file/MandalasGUI+Modded_Dakmode_v4.6.zip, file/Stay_True_1.20.zip, essential 	Recovery: Yes 	Recovery reason: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot read field "activeCITs" because "shcm.shsupercm.forge.citresewn.CITResewn.INSTANCE" is null 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) Caused by: java.lang.NullPointerException: Cannot read field "activeCITs" because "shcm.shsupercm.forge.citresewn.CITResewn.INSTANCE" is null 	at TRANSFORMER/citresewn@1.20.1-5/shcm.shsupercm.CITHooks.linkBakedCITItemModels(CITHooks.java:64) 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.resources.model.ModelBakery.handler$eko000$linkBakedCITItemModels(ModelBakery.java:1537) 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.resources.model.ModelBakery.m_245909_(ModelBakery.java:184) 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.resources.model.ModelManager.m_245476_(ModelManager.java:158) 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.resources.model.ModelManager.m_246937_(ModelManager.java:89) 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) 	... 6 more  Stacktrace: 	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2326) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 1018501120 bytes (971 MiB) / 1497366528 bytes (1428 MiB) up to 4294967296 bytes (4096 MiB) 	CPUs: 16 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 7 7700 8-Core Processor               	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2 	Microarchitecture: Zen 3 	Frequency (GHz): 3.79 	Number of physical packages: 1 	Number of physical CPUs: 8 	Number of logical CPUs: 16 	Graphics card #0 name: NVIDIA GeForce RTX 3070 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x2488 	Graphics card #0 versionInfo: DriverVersion=31.0.15.3742 	Graphics card #1 name: AMD Radeon(TM) Graphics 	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002) 	Graphics card #1 VRAM (MB): 512.00 	Graphics card #1 deviceId: 0x164e 	Graphics card #1 versionInfo: DriverVersion=31.0.22011.1008 	Memory slot #0 capacity (MB): 16384.00 	Memory slot #0 clockSpeed (GHz): 4.80 	Memory slot #0 type: Unknown 	Virtual memory max (MB): 35960.91 	Virtual memory used (MB): 19101.66 	Swap memory total (MB): 20480.00 	Swap memory used (MB): 355.38 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m 	Loaded Shaderpack: (off) 	Launched Version: forge-47.2.1 	Backend library: LWJGL version 3.3.1 build 7 	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.42, NVIDIA Corporation 	Window size: 1920x1080 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs:  	Current Language: en_us 	CPU: 16x AMD Ryzen 7 7700 8-Core Processor  	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.5.jar eventbus PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar essential-loader TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		javafml@null 		kotlinforforge@4.5.0 		lowcodefml@null 	Mod List:  		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		forge-1.20.1-47.2.1-universal.jar                 |Forge                         |forge                         |47.2.1              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v15

**Comment by SHXRKIIE** [comment]
Not crashing for me, please remove essential we already have a mod that does this.
![image](https://github.com/LunaPixelStudios/Better-MC/assets/79353591/0df79643-548e-4fa2-ad89-eede56c82077)
