### ISSUE TITLE
Accesories from aether redux 

### ISSUE THREAD

**Issue by Erxti** [LunaPixelStudios/Better-MC#1427]
### Describe the Bug

I'm unable to equip the accesories from aether redux such as sentry ring or enchanted ring, Whatever I do it doesn't equip in the aether slot but the rings from basic aether are working fine. Any Idea where this could come from? 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v19

**Comment by chorbintime** [comment]
report to devs of aether redux mod

**Comment by Erxti** [comment]
Well I mean I looked it up and in a newer version they patched it we just don't have the right one, it's still in 1.19.2
