### ISSUE TITLE
BMC4 Crahes After World Load

### ISSUE THREAD

**Issue by denayeisnotokay** [LunaPixelStudios/Better-MC#1431]
### Describe the Bug

After creating a new world or opening an existing one in BMC4, the game will crash after 1-10 seconds. I currently have the recommended 9024MB of RAM allocated for the instance.

### Reproduction Steps

1. Loaded mod with ATLauncher
2. Ran Minecraft using Java 17.0.6
3. Created/loaded world

### Crash Report or Log

generate world log: https://paste.atlauncher.com/view/75681a24-6347-49c1-8c86-973d84f9a38d
load world log: https://paste.atlauncher.com/view/c5129327-6a14-4026-84ec-0437fb8d07fa

### Operating System

macOS Sonoma

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

16

**Comment by chorbintime** [comment]
Install Java 21 and make ATLauncher use it 

Follow the guide here for changing java version, but instead of 18 choose 21 https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide
