### ISSUE TITLE
Crash when entering the nether

### ISSUE THREAD

**Issue by syncline-owo** [LunaPixelStudios/Better-MC#1432]
### Describe the Bug

getting a timeout error and crash when entering the nether.

### Reproduction Steps

1.go into the nether
2.server time out 
3.server crash
...

### Crash Report or Log

https://gist.github.com/syncline-owo/3c87d8ec4d8c62d3551885078cf841d2

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC_4

**Comment by syncline-owo** [comment]
also experiencing this issue when another player joins my server

**Comment by syncline-owo** [comment]
after more testing it has to do with travelling between dimensions too fast I think

**Comment by SHXRKIIE** [comment]
How are you hosting the server?

**Comment by syncline-owo** [comment]
Hosting through Apex MCOn Oct 10, 2023, at 12:28 PM, 丂廾闩尺长工㠪 ***@***.***> wrote:﻿
How are you hosting the server?

**Comment by chorbintime** [comment]
Contact Apex support, its likely an issue on their side
