### ISSUE TITLE
Soul Stone blocks dont spawn

### ISSUE THREAD

**Issue by CoolFreeze23** [LunaPixelStudios/Better-MC#1433]
### Describe the Bug

I know you need soulstone to spawn the wither, but theyre almost IMPOSSIBLE to come by. You can only find them in catacombs and those are even rare, and then if you do find one its even rarer to find it in a chest.

I'm pretty sure its suppose to spawn in soul sand valleys, but due to Oh the Biomes well go, the biome never pops up.

Is there another way I'm not thinking of? Or can we add the biome locator compass mod or something? I think that'll help with the 1/1000 chance of finding a soul sand valley naturally.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

.19

**Comment by SHXRKIIE** [comment]
Should bee able to use soul sand now too  or just usee a natures ccompass
