### ISSUE TITLE
Corn doesn't grow when planted

### ISSUE THREAD

**Issue by Noirsette** [LunaPixelStudios/Better-MC#1436]
### Describe the Bug

In my quest to cultivate as many plants as I can I noticed that the corn from the Cultural Delights mods doesn't grow. I'm unsure if I've simply got the wrong conditions for the corn, but even during spring it doesn't grow, meaning I have no idea how to get the corn on the cob that is part of the same mod. Any help would be appreciated.

### Reproduction Steps

1. Grab corn kernels from wild corn
2. Plant corn kernels into farmland
3. Wait
4. The plant remains unchanged.
5.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 1.19.2 v19.5

**Comment by chorbintime** [comment]
Report it to the developers of that mod if updating it doesn't fix it
