### ISSUE TITLE
Inventory System

### ISSUE THREAD

**Issue by LPGavs** [LunaPixelStudios/Better-MC#1438]
### Describe the Bug

So when playing my inventory builds up and I dont know which mod it is where you see your inventory whenever just looking around

### Reproduction Steps

1. Just load the game and put things in your inventory
2.
3.
...

### Screenshots and Videos

![Screenshot 2023-10-12 185554](https://github.com/LunaPixelStudios/Better-MC/assets/147776008/864796a4-f9af-4cd0-b28b-daeccb9fa22a)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

**Comment by PCMasterRays** [comment]
Press 'I' for Inventory, and this will disappear :)
