### ISSUE TITLE
Sildur's Enhanced Shaders cause Forge BMC4 v17 Client to crash in the Nether

### ISSUE THREAD

**Issue by PCMasterRays** [LunaPixelStudios/Better-MC#1440]
### Describe the Bug

Closed previous issue as was not concise, and I have new info.

Sildur's Enhanced Default shaders, specifically "v1.16 Fancy", cause my v17 Client to crash when entering the nether.
It also crashes when entering nether with no shaderpacks enabled, and then enabling them once teleported into the nether.

If it's impossible to support, then that sucks, but if it could be supported, this would be (in my opinion) the best shaders for this pack.

The bundled shaders are nice, but full of grain, bloom, and graphical glitches like glowing water edges; not to mention I went from 500+ fps to around 45 fps, which I believe vastly detracts from the Vanilla+ nature of this project, given that a lot of my players want to play BetterMC, because it's quite lightweight compared with other popular packs, and tanking the FPS with shaders is something they can't do on "Dad's old laptop", whatever the spec on that is lol.

Sildur's Enhanced Default shaders adds some subtle shadows, water texture, and a _little_ atmospheric bloom, which looks amazing on Default settings out of the box.

I passionately believe that this, if possible, would be a better addition to the modpack than the current shaders.

Thanks for your time, please let me know how this progresses, regardless of the outcome :)

### Reproduction Steps

1. Enable Sildur's Enhanced Default v1.16 FANCY shaders
2. Attempt to enter the Nether

OR

1. Disable all shaders
2. Enter the Nether
3. Enable Sildur's Enhanced Default v1.16 FANCY Shaders

Tested with "Sildur's Enhanced Default Shaders v1.16 FANCY"
I have not tried the "v1.16 FAST" version, although some of my players wish to use this version on lower end hardware.

### Screenshots and Videos

![shaders1](https://github.com/LunaPixelStudios/Better-MC/assets/26150829/99c9dd40-8551-41b3-9b6d-d1d22368b363)
![shaders2](https://github.com/LunaPixelStudios/Better-MC/assets/26150829/f046782c-a400-4577-81a7-f9538c18be6c)
![shaders3](https://github.com/LunaPixelStudios/Better-MC/assets/26150829/524a53de-2638-47ff-9a6e-ef4e63204824)

These don't explain the problem, but are some example screenshots from my server. They work really well in the Overworld, taking my FPS from 500+ to around 150, well worth the hit if you ask me :)

### Crash Report or Log

https://pastebin.com/kzWj3k5f

### Operating System

Ubuntu 22.04 LTS (server), Ubuntu 22.04 LTS (client) - They are separate hardware machines, just the same OS.

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 1.20.1 Forge v17 HF

### Other Mods

SHADER LINKS:
- v1.16 Fancy (Tested): https://www.curseforge.com/minecraft/shaders/sildurs-enhanced-default/files/4688998
- v1.16 Fast (Untested): https://www.curseforge.com/minecraft/shaders/sildurs-enhanced-default/files/4688997

**Comment by chorbintime** [comment]
You should report this to the developer of the shader itself, or the developer of Oculus. There's realistically nothing we could do about this on our side
