### ISSUE TITLE
Iceologer can't spawn

### ISSUE THREAD

**Issue by Rav10li** [LunaPixelStudios/Better-MC#1441]
### Describe the Bug

I can't spawn an iceologer with a spawn egg or summon command.

### Reproduction Steps

1. Open Better MC
2. Go in creative mode
3. Use an iceologer spawn egg or use a /summon command
4. See how it doesn't spawn

### Screenshots and Videos

![ezgif com-video-to-gif](https://github.com/LunaPixelStudios/Better-MC/assets/81896177/fc034f44-7a54-4b74-907c-988d7e7d2a5b)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

**Comment by chorbintime** [comment]
Check if the mob is disabled in the badmobs config

If it's not disabled then report this to the developer of the mod that adds icelogers
