### ISSUE TITLE
Inmis Backpack disapear when clicking on Backpack Shelves

### ISSUE THREAD

**Issue by Zareon-Feryel** [LunaPixelStudios/Better-MC#1443]
### Describe the Bug

When we click on a Backpack Shelf from Backpacked mod, Inmis Backpack is disapearing

### Reproduction Steps

1. Place a Backpack Shelf of the Backpacked Mod
2. Click on it with a Backpack from the Inmis Mod equipped
3. Backpack disapear

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v16 HF

**Comment by chorbintime** [comment]
Report it to the developers of Inmis

**Comment by Zareon-Feryel** [comment]
> Report it to the developers of Inmis

I'm okay with that, but isn't a compatibility bug between Inmis and Backpacked ? Cause Shelves are from Backpacked Mod, and not Inmis
