### ISSUE TITLE
Server unwantedly launched an old world save 

### ISSUE THREAD

**Issue by paytonchan** [LunaPixelStudios/Better-MC#1444]
### Describe the Bug

Today, I launched the server using the start.sh shell file for Better-MC [FABRIC] BMC1 and the world was what we had a couple weeks ago. We are missing a lot of progress (buildings, equipment, achievements). The most recent time we played was the night before which was roughly 12 hours before the this bug appeared.

### Reproduction Steps

1. Launch Server
2. Launch CurseForge
3. Enter Server
...

### Operating System

Windows 11 Home

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

### Other Mods

N/A

**Comment by paytonchan** [comment]
[crash-2023-10-13_23.48.51-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/12908425/crash-2023-10-13_23.48.51-server.txt)
It also appears that the server crashed sometime the night before

**Comment by paytonchan** [comment]
Yesterday, it began to work when I specified the server-ip in the server.properties file but today, it cannot connect to localhost when the ip address is specified. The primary issue remains the same.

**Comment by chorbintime** [comment]
dont specify the ip in server.properties
