### ISSUE TITLE
Entering end cause server to crash (suspicious asynch chunkload)

### ISSUE THREAD

**Issue by BeyondMighto** [LunaPixelStudios/Better-MC#1445]
### Describe the Bug

Entering end causes server to crash. I already beat the ender dragon with a friend, the bug began while building an enderman xp farm in the void.

### Reproduction Steps

1. entering end
2. crash

### Crash Report or Log

https://pastebin.com/Gyt0vGNX

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v16

### Other Mods

1 data pack for anti grief creeper

**Comment by ShroomKing** [comment]
I have the same problem

`[Worker-Main-49/ERROR] [ModernFix/]: Async chunk load took way too long, this needs to be reported to the appropriate mod.`

when exiting the nether

Also using v16, @BeyondMighto have you tried updating to v17 HF?

**Comment by ShroomKing** [comment]
I found the cause, for me it was the elevator blocks (elevatorid-1.20.1-1.8.15.jar)

I built some in the overworld, now server crashes when anybody enters the overworld.

Updating the mod to 1.19 doesn't fix it, removed the mod for now.

**Comment by BeyondMighto** [comment]
I've just delete my end to correct the problem, we were also using elevator block. New farm is done without elevator block (using waystone instead) seems to work fine.

**Comment by chorbintime** [comment]
remove the starlight mod
