### ISSUE TITLE
BMC2 - 1.20.1 - overworld waypoints showing in the nether

### ISSUE THREAD

**Issue by ftab** [LunaPixelStudios/Better-MC#1446]
### Describe the Bug

I can't find a setting to fix this, and Xaero says it is one of the other mods causing it. Not sure how to find out which one it is, any hints?

### Reproduction Steps

1. Set a waypoint
2. Enter nether
3. Waypoints from the other dimension are visible

### Screenshots and Videos

![2023-10-10_19 04 25](https://github.com/LunaPixelStudios/Better-MC/assets/1690894/6caaf7ed-0e72-4f0d-8dfd-4513cbf57761)
![2023-10-10_19 05 47](https://github.com/LunaPixelStudios/Better-MC/assets/1690894/398b5f95-a4ba-4169-a096-c17ca97ccaa5)
![2023-10-10_19 06 33](https://github.com/LunaPixelStudios/Better-MC/assets/1690894/a25c8eeb-6aad-49e7-b5da-4f0513d208cf)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2 v15 HF

**Comment by chorbintime** [comment]
update xaeros minimap & xaeroplus, if issue persists report it to the xaerosplus dev
