### ISSUE TITLE
Carry on mod does respond

### ISSUE THREAD

**Issue by lokiiexe** [LunaPixelStudios/Better-MC#1448]
### Describe the Bug

carry on mob does work

### Reproduction Steps

1. pick up mob ( note it is only mods allowed to be picked up)
2.try to place mobs
3. nth happens
...

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc 4 v18

### Other Mods

n/a

**Comment by chorbintime** [comment]
report it to the mod developer
