### ISSUE TITLE
Bugged textures

### ISSUE THREAD

**Issue by BBmanCrafter** [LunaPixelStudios/Better-MC#1449]
### Describe the Bug

After upgrading to v18 I joinned to my world and I saw a lot of bugged textures. From my field of cabages I had cherry pies, forest next to me was made of waterlogged signs and high grass on other side is now only many bugged flowers and many, many other block bugged textures like this and my friends had these problems with some blocks too

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/55876973/57d2cd09-6088-4f27-a0ec-555b59f9ffe7)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/55876973/7f3eea7f-0ef0-4ec1-bf0c-9a804b243ff4)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/55876973/35b94232-92ed-40a3-9a9a-645b2d67697f)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/55876973/e02abe02-1095-439a-8572-474b2216c294)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v18

**Comment by chorbintime** [comment]
you dont have the same modpack installed as the server
