### ISSUE TITLE
goblin trader trades iron ore

### ISSUE THREAD

**Issue by PiikaKitten** [LunaPixelStudios/Better-MC#1451]
### Describe the Bug

I have the newest update of the modpack but for some reason the Goblin Trader trades iron ore instead of raw iron. The same issue happens with the gold as well. How do I fix this?

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/148661043/e5afe3b8-78cc-4e32-a63d-c2452cf4e0f3)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v60.5

**Comment by chorbintime** [comment]
will be fixed in the next update
