### ISSUE TITLE
Bugged Chunk in Everdawn

### ISSUE THREAD

**Issue by Lasuroph** [LunaPixelStudios/Better-MC#1452]
### Describe the Bug

Everytime using a waystone or other means to a certain spot in everdawn, it will crash my server. 

### Reproduction Steps

1.no 
2.clue
3.just happened from playing
...

### Crash Report or Log

https://gist.github.com/Lasuroph/82d5f47a8e90d06dfff57110d6156757#file-crash-2023-10-21_22-49-43-server-txt

### Operating System

Windows 10 pro

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

BETTTER MC 1.20.1

**Comment by chorbintime** [comment]
what modpack version are you on? (v15, v9, etc)
