### ISSUE TITLE
Charm of keeping and totem of undying interfering with eachother 

### ISSUE THREAD

**Issue by jwc1000** [LunaPixelStudios/Better-MC#1453]
### Describe the Bug

I was doing a woodland mansion and  I died to vexes My armer dissapeared along with my sword No way to retrieve the items that were lost and I went back to spawn to see if they were there. They were not

### Reproduction Steps

1. Equip totem of undying and charm of life
2. Die items dissapear
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better minecraft 19.5

**Comment by chorbintime** [comment]
report it to the twilight forest devs
