### ISSUE TITLE
Unable to place blocks using default VR settings

### ISSUE THREAD

**Issue by JaredStock20** [LunaPixelStudios/Better-MC#1454]
### Describe the Bug

When playing in VR with the included mod the 'place block/interact' button does not work. I am playing on Meta Quest 2. The A button works for in game UIs and menus, does not work to interact with blocks or place. All other VR controller keybinds work as expected. 

### Reproduction Steps

1. Connect VR headset to PC and launch Better Minecraft
2. Enable VR mode @ top left corner of main menu
3. Enter world, attempt to place or interact with block
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v18

**Comment by chorbintime** [comment]
report to Vivecraft devs
