### ISSUE TITLE
Entities not moving unless in close proximity rendering mob farms useless. Better MC [FORGE] - BMC4 1.20.1 v15HF 

### ISSUE THREAD

**Issue by SelfishBG** [LunaPixelStudios/Better-MC#1455]
### Describe the Bug

So im having an issue with mobs not moving/pathfinding at all unless im really close to them, they are just standing there not moving  and stuttering in place, so was wondering if it is a modpack issue or a setting i need to change?

### Reproduction Steps

1.Go above the nether roof and make a platform for magma cubes to spawn.

2.Fly up and let them spawn or spawn them with a egg on the platform.

3.You will notice how they are standing still, now fly down and get really close to make them move again and as soon as they start moving fly up again, they should stand completely still stuttering mid jump.
..

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [FORGE] - BMC4 1.20.1 v15HF

**Comment by chorbintime** [comment]
v15 is old - we offer no support for old versions of the modpack
update the modpack, ur world is safe
