### ISSUE TITLE
Entities not moving unless in close proximity rendering mob farms useless. Better MC [FORGE] - BMC4 1.20.1 v18 the latest version.

### ISSUE THREAD

**Issue by SelfishBG** [LunaPixelStudios/Better-MC#1456]
### Describe the Bug

After updating the issue is still there.

So im having an issue with mobs not moving/pathfinding at all unless im really close to them, they are just standing there not moving and stuttering in place, so was wondering if it is a modpack issue or a setting i need to change?

### Reproduction Steps

1.Go above the nether roof and make a platform for magma cubes to spawn.
2.Fly up and let them spawn or spawn them with a egg on the platform.
3.You will notice how they are standing still, now fly down and get really close to make them move again and as soon as they start moving fly up again, they should stand completely still stuttering mid jump.

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [FORGE] - BMC4 1.20.1 v18

**Comment by muon-rw** [comment]
This is likely caused by DoesPotatoTick or NoSeeNoTick, and sounds like intended behavior. 

There should be an entity blacklist you can use, or you can remove the mod if you’re willing to take a performance hit.

**Comment by SelfishBG** [comment]
> This is likely caused by DoesPotatoTick or NoSeeNoTick, and sounds like intended behavior.
> 
> There should be an entity blacklist you can use, or you can remove the mod if you’re willing to take a performance hit.

I will take a look and try to remove the mod and see if that changes anything! :)

**Comment by SelfishBG** [comment]
> > This is likely caused by DoesPotatoTick or NoSeeNoTick, and sounds like intended behavior.
> > There should be an entity blacklist you can use, or you can remove the mod if you’re willing to take a performance hit.
> 
> I will take a look and try to remove the mod and see if that changes anything! :)

So i have removed the DoesPotatoTick mod and it seems to be working, the only problem i can see now is that the mobs are stuttering in place and not rendering their movement properly even tho they are finally moving, not sure what mod would control that.

**Comment by chorbintime** [comment]
retry on v19
