### ISSUE TITLE
Simple Storage UI not scrolling

### ISSUE THREAD

**Issue by Shiala1** [LunaPixelStudios/Better-MC#1457]
### Describe the Bug

Been having a blast so far with the pack, but I've noticed that the menu for both Simple Storage UIs (the normal and crafting grid versions) do not have a scroll bar, or allow mouse-wheel scrolling. Digging into the issue, it seems like Vivecraft caused this in the past, but they fixed it? I'd be super thankful if this could be resolved, as I'm on an Aternos server, so I can't tweak individual mods or configs for the most part.

### Reproduction Steps

1.Create a Simple Storage network large enough to hold more than a full menu's worth of item types
2.Attach all three components of the controller blocks (the heart, the crafting UI block, and the regular menu block, can't recall the name)
3. Fill the containers, and be unable to scroll down, only use various "sort by" to see one screen's worth of each option.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.20.1 v18

**Comment by muon-rw** [comment]
From that issue report it looks like it may also be an Oculus issue. Try disabling that mod as well.

**Comment by Shiala1** [comment]
Update: As none of us use VR, On a whim I tried deleting the vivecraft.jar file on my own installation, and somehow, it still let me onto the server, and now the scrollbar works without any errors in the logs or other bad side effects. It'll do!

**Comment by fayer3** [comment]
was a bug in vivecraft, fixed with https://github.com/Vivecraft/VivecraftMod/commit/1729f67ee586485cc855edf8b194dc183365e785
which will be in 1.1.3

**Comment by muon-rw** [comment]
> was a bug in vivecraft, fixed with [Vivecraft/VivecraftMod@1729f67](https://github.com/Vivecraft/VivecraftMod/commit/1729f67ee586485cc855edf8b194dc183365e785) which will be in 1.1.3

Good to know, thank you - I didn’t look closely enough at the issue and thought their fix was already released.
