### ISSUE TITLE
Using MineColonies crashed the game

### ISSUE THREAD

**Issue by P1gn** [LunaPixelStudios/Better-MC#1458]
### Describe the Bug

When installing and attempting to use the MineColonies mod, the game is unable to open and instantly crashes. Sometimes it lets me open a crash report, sometimes it doesn't.

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [Forge]

**Comment by chorbintime** [comment]
report to mod developer
