### ISSUE TITLE
Charm of Life not working

### ISSUE THREAD

**Issue by sp4hire2021** [LunaPixelStudios/Better-MC#1460]
### Describe the Bug

Going through the quest tutorials, and the second quest rewards a Charm of Life (from The Twilight Forest). It "suggests" I take a moment to familiarize myself with the back/charm slots and to equip the charm of life. I can interact with the charm by picking it up and moving it to various slots in my inventory, but I am unable to drop it into either charm slots.

FYI: this is the Forge version of BetterMC.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

60.5

**Comment by chorbintime** [comment]
it works in your inventory but the bug will be fixed in v61

**Comment by chorbintime** [comment]
To get the Charm of Life you simply claim the quest reward
