### ISSUE TITLE
Unable to Infuse Aether: Redux items

### ISSUE THREAD

**Issue by Shiala1** [LunaPixelStudios/Better-MC#1461]
### Describe the Bug

Me and others on the server have found that we cannot infuse any infusable items from the Aether: Redux with ambrosium. We click the ambrosium to hold it, right click over the item in the inventory. and it vanishes. it's just a visual bug, as soon as we put the ambrosium back down it will reappear, but it won't have any infusion and the ambrosium is returned. The achievement is still granted for doing it, but nothing is gained (or lost) in the process. 

The server log showed the following when it happened, using a veridium Sword, and the same later for a pickl (that it claimed was non-veridium?)

[27Oct2023 14:24:08.921] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Zandalara has made the advancement [Next Level]
--
1479 | [27Oct2023 14:24:08.921] [Server thread/WARN] [net.zepalesque.aether.Redux/]: Attempting to get infusion level of non-veridium item! Reading NBT data anyway
1480 | [27Oct2023 14:24:08.977] [Server thread/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
1481 | [27Oct2023 14:24:09.210] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@6d68f73e, suppressing error
1482 | net.minecraft.ReportedException: Container click
1483 | at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1484 | at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1550) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1485 | at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1486 | at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1487 | at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1488 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1489 | at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1490 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1491 | at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1492 | at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1493 | at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1494 | at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1495 | at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1496 | at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1497 | at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1498 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1499 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1500 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
1501 | Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
1502 | at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:1.0]
1503 | at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?]
1504 | at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?]
1505 | at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?]
1506 | at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
1507 | at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
1508 | at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
1509 | at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
1510 | at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
1511 | at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
1512 | at net.minecraftforge.network.simple.SimpleChannel.sendToServer(SimpleChannel.java:87) ~[forge-1.20.1-47.2.0-universal.jar%23502!/:?]
1513 | at net.zepalesque.aether.network.ReduxPacketHandler.sendToServer(ReduxPacketHandler.java:58) ~[aether-redux-1.2-1.20.1-neoforge.jar%23300!/:1.2-1.20.1-neoforge]
1514 | at com.aetherteam.aether.item.materials.AmbrosiumShardItem.handler$bne000$overrideStackedOnOther(AmbrosiumShardItem.java:532) ~[aether-1.20.1-1.0.0-beta.1.3-neoforge.jar%23299!/:1.20.1-1.0.0-beta.1.3-neoforge]
1515 | at net.minecraft.world.item.Item.m_142207_(Item.java:186) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1516 | at net.minecraft.world.item.ItemStack.m_150926_(ItemStack.java:392) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1517 | at net.minecraft.world.inventory.AbstractContainerMenu.m_246200_(AbstractContainerMenu.java:514) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1518 | at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:405) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1519 | at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[server-1.20.1-20230612.114412-srg.jar%23497!/:?]
1520 | ... 17 more
1521 | [27Oct2023 14:24:10.105] [Server thread/WARN] [net.zepalesque.aether.Redux/]: Attempting to get infusion level of non-veridium item! Reading NBT data anyway
1522 | [27Oct2023 14:24:10.106] [Server thread/WARN] [net.zepalesque.aether.Redux/]: Attempting to get infusion level of non-veridium item! Reading NBT data anyway
1523 | [27Oct2023 14:24:10.106] [Server thread/WARN] [net.zepalesque.aether.Redux/]: Attempting to get infusion level of non-veridium item! Reading NBT data anyway
1524 | [27Oct2023 14:24:10.106] [Server thread/WARN] [net.zepalesque.aether.Redux/]: Attempting to get infusion level of non-veridium item! Reading NBT data anyway
1525 | [27Oct2023 14:24:10.106] [Server thread/WARN] [net.zepalesque.aether.Redux/]: Attempting to get infusion level of non-veridium item! Reading NBT data anyway
1526 | [27Oct2023 14:24:10.107] [Server thread/WARN] [net.zepalesque.aether.Redux/]: Attempting to get infusion level of non-veridium item! Reading NBT data anyway
1527 | [27Oct2023 14:24:10.107] [Server thread/WARN] [net.zepalesque.aether.Redux/]: Attempting to get infusion level of non-veridium item! Reading NBT data anyway

### Reproduction Steps

1. Get an infusable item from the Aether; Redux mod
2. Get Ambrosium and try and right click the item to infuse it
3. Nothing happens
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.20.1 v18

**Comment by chorbintime** [comment]
report to mod developers
