### ISSUE TITLE
I found a bug that deletes your backpack.

### ISSUE THREAD

**Issue by Theluckgod76** [LunaPixelStudios/Better-MC#1462]
### Describe the Bug

I did it once on accident and lost all my stuff, also found out the glitch is replicable. It somehow deletes your equipped backpack.

### Reproduction Steps

1. Equip a backpack in the back slot.
2. Place something in the backpack.
3. Left click on a quiver to pick it up.
4. Hover over the equipped backpack.
5. Right click...and poof! It's gone!

### Screenshots and Videos

![image_2023-10-29_101947727](https://github.com/LunaPixelStudios/Better-MC/assets/143624631/e6443164-6b0b-4289-afb0-461e8f3e9d44)

![image_2023-10-29_102229508](https://github.com/LunaPixelStudios/Better-MC/assets/143624631/3d6279b0-a46b-4e9f-b676-9ff892c87fb7)

 It just disappears.

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 v19

**Comment by chorbintime** [comment]
report to mod developers
