### ISSUE TITLE
"Better MC [Fabric] - BMC2 v17/v18" // Server crashing

### ISSUE THREAD

**Issue by DaRealDevoly** [LunaPixelStudios/Better-MC#1463]
### Describe the Bug

The bug appears as soon as i join my BMC2 Server.

Around one hour before the first crash i started with "Tom's Simple Storage" and everything worked fine for the next hour. Only things i did are listed in the reproduction steps.

Nothing else was noticable just from the gameplay. Usually it takes around 10-60 Seconds to disconnect with a server crash.

Crash first appeared 4 times on v17. Tried to fix with updating to v18. Still crashes with the same error.
I don't know if it's important but the Server runs on Linux. I'm using g-portal for my server.

I'm pretty bad at reading crash logs or codes in general, so i ask here for help. :)

### Reproduction Steps

1. placing my Vanilla Auto Smelters to a new place in my Base (Chests, hoppers, blast furnace, furnace, smoker)
2. placing some walls inside of my base (used new Diorite block variant, dark oak and glass panes)
3. placed dark oak trapdoors with a dark oak door in the middle for a fancy door design of my base. (i'm pretty bad at describing in english
4. placed the season calendar to a new place

### Crash Report or Log

https://gist.github.com/DaRealDevoly/635bfc5fc3c9e1a25cc3f99fb39d15e3

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2 v17 and v18

**Comment by chorbintime** [comment]
replace let me despawn with despawntweaker
