### ISSUE TITLE
[Suggestion?] Is Modular Golems mod suitable to add in the future Better MC update?

### ISSUE THREAD

**Issue by chemlzh** [LunaPixelStudios/Better-MC#1464]
There are some bosses that is too hard to beat down, like vanilla Warden, as well as Cataclysm Ignis and Leviathan. Besides, the Otherside dimension is too dangerous even if you wear Warden suit. Therefore I long for golems enhancement like [Modular Golems](https://www.curseforge.com/minecraft/mc-mods/modulargolems), which can help me to fight with these bosses. I don't know whether Modular Golems mod will break the game balance, so I upload this issue.

Looking forward to your reply!

**Comment by chorbintime** [comment]
doesnt fit very well - anyway we'd rather have players fight the bosses themselves
