### ISSUE TITLE
Farmer Villager Bug

### ISSUE THREAD

**Issue by VolvelaBVolvic** [LunaPixelStudios/Better-MC#1465]
### Describe the Bug

To put it simply, I wanted to create a farm with a villager farmer but he doesn't harvest or cultivate the soil. I thought it came from my world so I did the test on another world in the best condition I gave them food, a bed a bell and I activated the "mob griefing" gamerule to true but he doesn't do anything.

### Reproduction Steps

1. Spawn a villager and give him the job of farmer
2. Put him in a field and give him seeds or potatoes
3. If you want add a bed and a bell
4. And he doesn't farm

### Screenshots and Videos

![2023-11-02_02 07 22](https://github.com/LunaPixelStudios/Better-MC/assets/98283108/8772f5a4-0644-46a2-9295-9767a80d2e6b)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v18

**Comment by chorbintime** [comment]
read up on the "Smarter Farmers" mod thats in the pack - this is likely intended behavior
