### ISSUE TITLE
Crafting Table Recipe book gone

### ISSUE THREAD

**Issue by Bobbeltrouble** [LunaPixelStudios/Better-MC#1466]
i cannot make bug issue thread work.. 

Minecraft v1.20 BMC v19 
Windows 11

whenever i open inventory to craft the crafting recipes are gone.
same happens when opening the 3x3 crafting table
but the book appears when i open a furnace. 

help ? 

![2023-11-02_09 08 49](https://github.com/LunaPixelStudios/Better-MC/assets/149662233/17fae231-c19f-45f7-b659-ecf6b3d03f4b)
![2023-11-02_09 08 53](https://github.com/LunaPixelStudios/Better-MC/assets/149662233/0a674f5a-c624-419c-b859-27f4758621f6)
![2023-11-02_09 08 57](https://github.com/LunaPixelStudios/Better-MC/assets/149662233/21af9e2c-003f-4c16-acc9-bbbf6dc9fd76)

**Comment by Darkerowl** [comment]
Same here and it show inside the furnace and other places and inside inventory but not if you hit (E) to see inventory, but it shows if you hit ( I ) to show inventory. The magnify glass button doesn't show also in not on the crafting table which JEI is okay to do it with but million times slower. I did notice if you click the arrow that points to item made after recipe it will bring up all recipes but that still over 2k to go through. Best way is to favorite ones you use a lot and wait for a fix. hover+a on item in jei to favorite.

**Comment by Darkerowl** [comment]
I found a work around: if you hit ( i ) and click the mag glass and close the menu with the book still open close menu with→ (esc) and then go to the Crafting Bench it will have the window still open for the crafting recipe book.

**Comment by chorbintime** [comment]
dont use the recipe book

**Comment by ManosDaskos** [comment]
> dont use the recipe book

but what should we use when the jei craftable section is so laggy all the time?
for early game at least searching one by one the recipes?
