### ISSUE TITLE
Can't launch BMC no matter the version, or whether forge or fabric.

### ISSUE THREAD

**Issue by ARC-2** [LunaPixelStudios/Better-MC#1468]
I've been a fan of betterMC for a while now, and I recently got a new computer. however, when I try to launch BetterMC or my own custom modpack using specific mods in BMC, it always crashes with exit code 1. I'm really confused, I've never had this issue before on previous windows devices.
How can I fix the constant crashes and get Better-MC to launch?

**Comment by wectra** [comment]
I have the same problem. Game crashes with exit code 1.

**Comment by chorbintime** [comment]
you need to send logs or we can not help you. check the logs folder or the crash reports folder
