### ISSUE TITLE
Ice not melting after winter seasons end

### ISSUE THREAD

**Issue by dabush03** [LunaPixelStudios/Better-MC#1469]
The Ice formed on rivers/lakes are still not melting after winter ends, even during Summer. I've updated the version of Fabric Seasons yet it still doesn't melt so I don't know what's causing it.

![2023-11-04_01 55 08](https://github.com/LunaPixelStudios/Better-MC/assets/149855469/6a48a1d4-fe0c-4d41-9ee1-4551a45a0095)

Windows 11

1.19.2

Fabric

v19.5

**Comment by muon-rw** [comment]
In fabric seasons config set `shouldIceNearWaterMelt: true`. Will be fixed next update.

**Comment by dabush03** [comment]
> In fabric seasons config set `shouldIceNearWaterMelt: true`. Will be fixed next update.

What's the name of the config file?
