### ISSUE TITLE
BMC v19.5 Editing mods crashed game

### ISSUE THREAD

**Issue by mjromine** [LunaPixelStudios/Better-MC#1470]
### Describe the Bug

I was looking to update the modpack, and thought I could check for updates for each individual mod... it was taking much longer than expected, so I cancelled the process. But then the instance wouldn't start up in AT Launcher, so I went back and finished updating the individual mods, but I'm still getting errors.

### Reproduction Steps

1. Ran Check For Updates for the modpack in AT Launcher (there were no updates)
2. Selected "Edit Mods"
3. Selected "Enabled Mods"
4. Clicked "Check for updates"
5. Clicked "Add" for each updated mod
6. Clicked "Play"
7. Disabled any mods that were causing conflicts 
(such as:
Replace mod 'ImmediatelyFast' (immediatelyfast) 1.2.6+1.19.2 with any version that is compatible with:
		 - fabricloader, version 0.14.23 or later
		 - memoryleakfix 1.0.0)
8. Minecraft now crashes with crash report

### Crash Report or Log

https://gist.github.com/mjromine/f5e10bd7e6a122223bcfc53764068954

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v19.5

**Comment by muon-rw** [comment]
Mods are often incompatible in various versions - running update all almost always breaks modpacks. We have to troubleshoot things like this when releasing modpack versions and can't reasonably provide support for someone trying to update the mods themselves. 

You are welcome to do so, but I would recommend reinstalling and testing one mod update at a time. It also looks like you need to update the Fabric loader version in this case.
