### ISSUE TITLE
inventory HUD always showing

### ISSUE THREAD

**Issue by Samuel9043** [LunaPixelStudios/Better-MC#1471]
My inventory hud is always there even if the inventory is close. I've tried to remove it in the setting but I can't find anything to remove it. Can anyone help me?
![Capture d’écran 2023-11-04 202028](https://github.com/LunaPixelStudios/Better-MC/assets/72711325/114ef546-f411-4fce-8f8e-54e717d2954f)
![Capture d’écran 2023-11-04 202041](https://github.com/LunaPixelStudios/Better-MC/assets/72711325/40ab1bd6-4128-42e7-98d6-e8793a1447d5)

**Comment by chorbintime** [comment]
press I
