### ISSUE TITLE
No UI model? 

### ISSUE THREAD

**Issue by kianxavier1** [LunaPixelStudios/Better-MC#1472]
### Describe the Bug

When I try to open Minecraft through CurseForge, I make sure that it has the correct version of the mod and everything. The Minecraft launcher says the version that I'm wanting to play, Better MC [FABRIC] 1.19.2 v19.5. When I try to load it up, it says owo-ui error; No context provided; No UI model with id owo:config was found; Check your log for details. When I go to check my log, there isn't one for the attempt at opening Minecraft 

### Reproduction Steps

1. uninstalled and reinstalled modpack
2. uninstalled and reinstalled minecraft launcher 
3.
...

### Screenshots and Videos

![IMG_5173](https://github.com/LunaPixelStudios/Better-MC/assets/149920657/9b3e6e0e-7630-4265-9643-a77cc1101cc1)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FABRIC] 1.19.2 v19.5

### Other Mods

n/a

**Comment by SHXRKIIE** [comment]
Only reason this would happen is bad installs and why it keeps happing idk, and not giving a log doesnt give us any help. Use ATLauncher instead
