### ISSUE TITLE
Sakura vertical slabs

### ISSUE THREAD

**Issue by N1EMI3C** [LunaPixelStudios/Better-MC#1474]
### Describe the Bug

While placing sakura wood slabs vertically they have Purple-Black texture.

### Reproduction Steps

1. Make Sakura Wood Slabs
2. Place them vertically
3. Cry

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/63743997/f5d5538e-7dbb-4531-b580-077c421496a1)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2 v19

### Other Mods

WiZoom

**Comment by SHXRKIIE** [comment]
Remove autoslabs mod
