### ISSUE TITLE
Server crashing after growing a flowering fieldsprout sapling from the aether mod

### ISSUE THREAD

**Issue by oila40** [LunaPixelStudios/Better-MC#1475]
### Describe the Bug

After running around in the Aether dimension, my server crashes.
Through a coincidence, I found out, that it was actually due to a flowering fieldsprout sapling growing into a tree.

I think it's from The Aether: Redux mod

### Reproduction Steps

1. get a flowering fieldsprout sapling
2. use some bonemeal on it
3. crash your server

### Crash Report or Log

https://pastebin.com/gwVZgNxj

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v20

### Other Mods

Chunky pregenerator (https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator-forge)

**Comment by oila40** [comment]
I have tested every sapling that comes up from the creative mode search bar when you type in "sapling", and it is only the flowering fieldsprout sapling that continues to crash the server.

**Comment by SHXRKIIE** [comment]
Will be fixed in v21
