### ISSUE TITLE
taking damage when eating

### ISSUE THREAD

**Issue by xsolane** [LunaPixelStudios/Better-MC#1476]
### Describe the Bug

i have a mohist server with btmc4 installed. at least half of my players are taking damage when eating any food (bread, apples, steak, anything) is this a bug? or a mod that’s causing this? 

### Reproduction Steps

1. eat any food
2. take random damage

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

btmc4 v19

**Comment by qwek1** [comment]
Its an issue with your serverhost
