### ISSUE TITLE
Mangrove recipe materials for certain mods mixed up/missing

### ISSUE THREAD

**Issue by Gamarleton** [LunaPixelStudios/Better-MC#1477]
### Describe the Bug

The types of wood used to make the Decorative Blocks things using mangrove are currently mixed up. 
The minecraft red mangrove is made using Twilight Forest white mangrove instead, and the white mangrove items currently can't be crafted.
The Twilight Forest mangrove recipes for Every Compat also seem to be missing, but these work like normal for the red mangrove ones from Minecraft itself. 

### Screenshots and Videos

![mangroverecipedecorativeblocks](https://github.com/LunaPixelStudios/Better-MC/assets/33168591/1b2d2430-46c4-440c-9a73-28e548ff7a37)

### Crash Report or Log

https://gist.github.com/Gamarleton/16accea90f73f3477f4ed954cdcccff9

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v20

### Other Mods

I did add GoProne and possibly other similar things that I don't recall but I didn't add anything that changes the block/item selection. Let me know if it's still important and I'll make a second profile just to test.

**Comment by chorbintime** [comment]
Report it to the mod developers

**Comment by Gamarleton** [comment]
This is obviously not a single mod bug, this is obviously the decorative blocks mod having a conflict with the twilight forest mod. Isn't that more of a thing for the modpack creator to manage?

**Comment by chorbintime** [comment]
likely an every compat issue - it'd be better if the issue was fixed in the mod itself because then the issue doesnt happen to other people
