### ISSUE TITLE
Server crashes on launch after entering the aether.

### ISSUE THREAD

**Issue by yunghalfndhalf** [LunaPixelStudios/Better-MC#1481]
### Describe the Bug

After playing for around 2 hours my friend entered the aether, it instantly crashed the server but he was able to fall out after server restart. I then entered the aether and now the server crashes instantly when I join.

### Reproduction Steps

1.Friend entered aether
2.crashed server
3. he left aether
4. I entered aether
5. server crashes when I join now

### Crash Report or Log

https://gist.github.com/yunghalfndhalf/abb341bed4fec1cfdf50830f109d05c2

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v20

### Other Mods

none

**Comment by yunghalfndhalf** [comment]
the Minecraft version is 1.20.1

**Comment by SHXRKIIE** [comment]
Will be fixed in v21
