### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Golfmk394** [LunaPixelStudios/Better-MC#1482]
### Describe the Bug

crashes when i try to launch game

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/Golfmk394/a5d666545fd3acb8675c21f7b93032d6

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v21

**Comment by Golfmk394** [comment]
SOLVED:  It was an issue with AMD display drivers.

**Comment by mbainter** [comment]
That error is usually either a bad install of java, outdated gpu drivers, or sometimes windows UAC or data execution protection capabilities.  Error excerpted here to make it easier to find for anyone searching for it in the issues:

> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  EXCEPTION_ACCESS_VIOLATION (0xc0000005)

**Comment by mbainter** [comment]
(By the way - you should be able to mark your own issue as closed, you don't have to wait for the maintainer)
