### ISSUE TITLE
Macbook Pro M1 2020, Crashes

### ISSUE THREAD

**Issue by rippsquad** [LunaPixelStudios/Better-MC#1483]
### Describe the Bug

Whenever a world is made or a server is joined within BetterMC 4 1.20.1, it crashes immediately and provides "Exit Code 6." This is an ongoing issue with a lot of people and there are no solutions from the official team of the BetterMC other than to update Java to an unsupported version. I notice people complain about this issue on other modpacks too, so not just this one. The Macbook used can run other mod packs fine, it is just the LunaPixel packs. 

### Reproduction Steps

1. Open Curseforge and open BetterMC4 1.20.1 
2. Allow it to load to the menu and create a world
3. Game may crash

### Crash Report or Log

https://mclo.gs/k8fYMdD

### Operating System

Macbook Pro M1 2020

### Minecraft Version

1.20

### Modloader

CurseForge

### Modpack Version

BMC 4 V20

### Other Mods

N/A

**Comment by chorbintime** [comment]
Java 18 is not an "unsupported version". It works completely fine.

Read the [performance guide](https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide) for how to switch java versions.

**Comment by szantaikis** [comment]
Note that the below error from the crash report indicates a bug in the Java Runtime: https://bugs.openjdk.org/browse/JDK-8310844 . Workaround is to add `-XX:CICompilerCount=2 -XX:CompilationMode=high-only` to the JVM Arguments in the Launcher and use a latest Java 17.0.10
```
Internal Error (assembler_aarch64.hpp:267), pid=59502, tid=23811
guarantee(chk == -1 \|\| chk == 0) failed: Field too big for insn

```
