### ISSUE TITLE
Reproducible crash with SkinnedLanterns in BMC3 1.19.2

### ISSUE THREAD

**Issue by mbainter** [LunaPixelStudios/Better-MC#1484]
### Describe the Bug

Something about the skinnedlanterns mod causes a reproducible crash when connected to a server. We've been able to reproduce it on multiple platforms and multiple launchers.

When the pack is loading, it throws these errors:

> [18:12:06] [Render thread/ERROR] [minecraft/LootTables]: Couldn't parse loot table skinnedlanterns:blocks/present_green_soul_lantern_block: com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'skinnedlanterns:present_green_soul_lantern_block'

repeated for each block type in the mod, and then when it crashes the error is:

> Caused by: java.lang.NullPointerException: Registry Object not present: skinnedlanterns:pufferfish_lantern_block
> 	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
> 	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.3.2-universal.jar%23689!/:?] {re:mixin,re:classloading}
> 	at at.nuxnux.skinnedlanterns.SkinnedLanterns$Tab.m_6976_(SkinnedLanterns.java:55) ~[skinned_lanterns-1.19.2-1.3.4.jar%23623!/:1.3.4] {re:classloading}
> 	at net.minecraft.world.item.CreativeModeTab.m_40787_(CreativeModeTab.java:120) ~[client-1.19.2-20220805.130853-srg.jar%23684!/:?]

I also noticed that there are some newer releases of this mod though for later releases like 1.19.4, and one of the key changes is that all of the block files have been changed similar to this:

```diff
 {
   "parent": "skinnedlanterns:block/head_lantern_hanging_east_west_template",
   "textures": {
-    "2": "skinnedlanterns:blocks/zombie_soul_lantern"
+    "2": "skinnedlanterns:block/zombie_soul_lantern"
   }
 }
```

### Reproduction Steps

1. Setup a server instance built on BMC3
2. Log in and set gamemode to creative
3. Open your inventory, and then click the arrows to walk through the first four tabs of the UI 
4. Crash

Note: This doesn't happen in single-player, and doesn't happen when navigating through the JEI's UI. Just the creative one, as indicated in the screenshot.  Happens on tab 4.

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/123376/7768b158-79e6-4dda-87dd-d79557ab51c1)

### Crash Report or Log

[Crash Report](https://gist.github.com/mbainter/9ea71c1b5bf6d929bdcba08be35416e4)

### Operating System

Ubuntu and Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v19

**Comment by chorbintime** [comment]
report it to the skinned lanterns mod developer

**Comment by mbainter** [comment]
I discovered the actual issue was that when BisectHosting installed the modpack their automated tool disabled the server-side mod.  Frustratingly there are no notifications or anything on that, you just have to scroll through the list of mods and see they renamed it from .jar -> .jar.disabled.
