### ISSUE TITLE
Quark Variant Chest anti-overlap prevents crafting Every Compat BYG chests

### ISSUE THREAD

**Issue by Magiwarriorx** [LunaPixelStudios/Better-MC#1485]
### Describe the Bug

When using BYG woods, you are unable to craft the matching Every Compat chest. This is (presumably) due to Quark's anti-overlap feature disabling Quark variant chests when it detects Woodworks. Setting "Ignore Anti Overlap" to true for Quark variant chests fixes the issue.

### Reproduction Steps

1. Take any type of plank from BYG
2. Try to craft a chest with said planks

### Screenshots and Videos

![bmc1](https://github.com/LunaPixelStudios/Better-MC/assets/76668941/e066328c-8906-4867-8999-b681a3460edf)
![bmc2](https://github.com/LunaPixelStudios/Better-MC/assets/76668941/9070285f-92d4-4f8d-97b2-b33842635ea8)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 v19

**Comment by chorbintime** [comment]
report it to the every compat mod developer
