### ISSUE TITLE
Fence error

### ISSUE THREAD

**Issue by ShadowPlayz7** [LunaPixelStudios/Better-MC#1486]
### Describe the Bug

i did everything that i should to fix any bugs that i found, the game was lagging just a lil bit - i though it'll be fine - then again "cant load the fence" or smth like that and now i cannot fix it, its like da fence was never there or is deformed somehow
 mb 6036/ 8096 (changed it multiple times cuz da game asked for it)
 
### Crash Report or Log

less memory allocated + "fence error"

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

CurseForge (Forge)

### Modpack Version

Better MC (BMC4)

### Other Mods

No

**Comment by chorbintime** [comment]
we can't help if you do not provide logs
