### ISSUE TITLE
Ender dragon won't drop eggs when killed after one time

### ISSUE THREAD

**Issue by Paul-le-romaing** [LunaPixelStudios/Better-MC#1487]
### Describe the Bug

Dragon mounts legacy add the possibility to kill the ender dragon many times while always receiving an egg. Some other mods seem to interfere with this functionality and after the first dragon kill, the other won't drop any eggs.

### Reproduction Steps

1.Kill the ender dragon a first time and take the egg.
2.Respawn the dragon and kill it a second time. The egg won't respawn.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

V21

**Comment by chorbintime** [comment]
i'm pretty sure that functionality was disabled by us. either way we dont want infinite dragon eggs to be a thing

**Comment by Paul-le-romaing** [comment]
> i'm pretty sure that functionality was disabled by us. either way we dont want infinite dragon eggs to be a thing

Hum, so is the functionality that let dragon eggs appear in chests on by default in that case?

**Comment by chorbintime** [comment]
likely yes
