### ISSUE TITLE
Load Distance for mobs

### ISSUE THREAD

**Issue by HaiTeppich** [LunaPixelStudios/Better-MC#1488]
### Describe the Bug

In Better Minecraft Forge 1.16.5 Mod Pack i encountered an issue with mob load/spawn distance while building an enderman XP farm in the end. Mobs only load within 32 blocks. When flying up within 32 block range in creative, the farm works. when on the kill platform (43 block distance), the mobs that spawned in bug out wildly and dont fall down anymore, also no new mobs spawn in.

Please help, i cant find any settings or reports of simmilar problems. Ty

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

(https://youtu.be/B9lGRHbySRc)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better Minecraft 1.16.5 BMC 1

**Comment by HaiTeppich** [comment]
Problem was resolved, you can change vertical Mob tick distance in "Does Potato Tick" Mod Settings

**Comment by INeedHelpGit** [comment]
does who know 💀
