### ISSUE TITLE
CTD upon entering Nether

### ISSUE THREAD

**Issue by ctelliot** [LunaPixelStudios/Better-MC#1489]
### Describe the Bug

I'm playing on Better Minecraft Forge 1.16.5 v60.5 and I CTD every time I try to enter the Nether. I created my survival world on v60.5 and have played quite a lot on it. I haven't been able to successfully enter Nether before. Attached is the crash report from the crash and a video of it. I haven't modified the modpack in any way and I'm using CurseForge. I have followed the performance guide but to no avail. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/151618409/63d5441d-2df2-406a-a0c1-7b304d4f7624

### Crash Report or Log

https://gist.github.com/ctelliot/43f3e44d819a3289fcacfd87fc6ae73e#file-crash-2023-11-14_13-22-03-server-txt

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC1 v60.5

**Comment by chorbintime** [comment]
add/update both oPotato and ModernFix then send a new log

**Comment by Kasualix** [comment]
Can you share the crashing world folder's zip file in your saves?

**Comment by ctelliot** [comment]
> add/update both oPotato and ModernFix then send a new log

Thank you so so much! Updating ModernFix and adding oPotato fixed my issue! I was able to load into the Nether for the first time. I restarted my game and tried it again to make sure it wasn't a one time thing and it's working perfectly. I'll come back if I find anything not working properly. Thanks again!
