### ISSUE TITLE
Java.Trojan.GenericGBA.33803 Was detected on fresh install from cruseforge app

### ISSUE THREAD

**Issue by KscUwU** [LunaPixelStudios/Better-MC#1490]
The file C:\Users\H\curseforge\minecraft\Instances\Better MC [FABRIC] - BMC1\.fabric\processedMods\net_lenni0451_reflect-1.3.0-ee146a2a56a8e3f2.jar=>net/lenni0451/reflect/accessor/FieldAccessor.class is infected with Java.Trojan.GenericGBA.33803 and was moved to quarantine.

**Comment by chorbintime** [comment]
ImmediatelyFast is being falsely flagged - just ignore it
