### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by Ponkichi23** [LunaPixelStudios/Better-MC#1492]
### Describe the Bug

Whenever I try to open the game, it just causes the exit code 1 and I can't play it.

### Reproduction Steps

1. I've got a few extra but installed the BMC4 mods
2. I run the game
3. Before it launches minecraft, the exit code 1 just pops up.
...

### Screenshots and Videos

It's normal exit code 1, no crash reports

### Crash Report or Log

They won't generate

### Operating System

Mac

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.20.1 v21.zip

### Other Mods

![Uploading Screenshot 2023-11-22 at 10.06.38 PM.png…]()

**Comment by chorbintime** [comment]
dont add extra mods
