### ISSUE TITLE
I'm having trouble in the Minecraft Launcher.

### ISSUE THREAD

**Issue by TempoSlayer** [LunaPixelStudios/Better-MC#1493]
Describe the Bug:
When I tried to open the game, it just caused the "Exit Code: 1" and I couldn't launch the game at all.

Reproduction Steps:
Before it launches Minecraft, the exit code 1 just pops up.

Screenshots and Videos:

![Screenshot 2023-11-22 182548](https://github.com/LunaPixelStudios/Better-MC/assets/151792097/e0a86081-0fa4-4122-ba10-f39f64a39560)

Crash Report or Log:
They won't generate

Operating System:
Windows 11

Minecraft Version:
1.20

Modloader:
Forge

Modpack Version
Better MC [FORGE] - BMC4 Version 1.20.1

**Comment by Ponkichi23** [comment]
I've got the same error!

**Comment by SHXRKIIE** [comment]
is says tright there to view crash report so it does generate and logs always generate. 
1. Have you modified the modpack in any way? If so, what did you do? (Updating/adding/removing mods, changing configs)
2. What launcher, or program, are you using to launch the game? (CurseForge, ATLauncher, etc)
3. What Minecraft version are you playing? (1.18.2, 1.16.5, 1.19.2)
4. What version of the modpack are you playing? (v11, v9, etc)
7. Send the crash report file into this channel. Right click the modpack, Open Folder, and navigate to the Crash Reports folder. Drag the newest one here. If there is no crash reports folder, do the same thing with the latest.log file in the logs folder.

**Comment by SHXRKIIE** [comment]
> I've got the same error!

A Exit Code 1 is a general crash anyone can get it and its never the same issue, so if you have an issue dont reply and make issue report or ask in the discord
