### ISSUE TITLE
Anything that isn't a block or a UI element is invisible.

### ISSUE THREAD

**Issue by rehnolds** [LunaPixelStudios/Better-MC#1494]
### Describe the Bug

On the modpack Better MC survival,  I was moving a chest with a mod that allows me to pick up blocks with both hands (Carry On), but when I put down the chest anything that isn't a block turned invisible for no apparent reason. My thirdperson and firstperson playermodels, all chests, entities all invisible. I've already tried killing myself, reloading the game, and changing rendering settings. I feel like I just might have been pressing too many buttons too fast and some mods interfered with each other.

It's kinda liminal. Send help, I fear for my life.

### Reproduction Steps

1. Pick up a chest w/ "Carry On" mod
2. Put down the chest
3. Everything is invisible
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/151958267/da321ea1-a45f-45e7-a7fa-09d76578ba96)

![image](https://github.com/LunaPixelStudios/Better-MC/assets/151958267/4b1e2324-9230-45e4-839c-e742085bfec3)

![image](https://github.com/LunaPixelStudios/Better-MC/assets/151958267/e1a5ad53-eb8b-4479-b698-10a4d4ad4669)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC v20

### Other Mods

Distant Horizons

**Comment by chorbintime** [comment]
you didnt install the modpack correctly, and distant horizons is unsupported.

do a fresh install on ATLauncher
