### ISSUE TITLE
Twilight Forest Portal Makes World Unplayable

### ISSUE THREAD

**Issue by Bilbo1121** [LunaPixelStudios/Better-MC#1496]
On Better MC Forge BMC4 Java 1.20.1
anytime I create a portal to the Twilight Forest and jump through I receive an error msg:
Internal Exception: java.lang.RuntimeException: Unknown dimension: ResourceKey[minecraft:dimension / twilightforest:twilight_forest]

is this a known issue that has a fix?
is anyone else having this issue?

**Comment by SHXRKIIE** [comment]
update v22
