### ISSUE TITLE
missing stats on tools

### ISSUE THREAD

**Issue by moldydoughnut** [LunaPixelStudios/Better-MC#1498]
### Describe the Bug

on all the tools it only shows attack damage and attack speed. missing dig speed

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-11-29_10 04 27](https://github.com/LunaPixelStudios/Better-MC/assets/41700346/e06ec66b-33d8-4d63-8519-ae5eceb505d5)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC V20

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?
