### ISSUE TITLE
Missing item from "important controls" quest

### ISSUE THREAD

**Issue by otter939** [LunaPixelStudios/Better-MC#1500]
### Describe the Bug

the reward for the "important controls" quest is the missing item "aspen_sapling"

### Reproduction Steps

1. open quest book
2. go to important controls quest

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/59325969/574b5474-c6de-480b-ba9e-6370b6a5dd77)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

Better Mc v21

**Comment by SHXRKIIE** [comment]
Fixed
