### ISSUE TITLE
Can't make a Carved Pumpkin.

### ISSUE THREAD

**Issue by PlayerSomething** [LunaPixelStudios/Better-MC#1501]
### Describe the Bug

whenever I try to carve a pumpkin, it instantly disappears.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [FORGE] - BMC2 by SHXRKIE

**Comment by chorbintime** [comment]
What modpack version are you on? (v11, v19, etc)

**Comment by Frontear** [comment]
I think a video of the issue would be very helpful for investigation, alongside answering the above question

**Comment by SHXRKIIE** [comment]
Works in v23, wait for that i guyess
