### ISSUE TITLE
Waypoints doesn't work in the Nether

### ISSUE THREAD

**Issue by bor-is-lov** [LunaPixelStudios/Better-MC#1503]
### Describe the Bug

There is no opportunity to make a waypoint related with the nether but it works with any other dimension.

### Screenshots and Videos

Here I'm in the Nether, but there is no opportunity to pick this dimension for the waypoint to be in
![image](https://github.com/LunaPixelStudios/Better-MC/assets/138852100/fe7a2883-97d2-4d3f-ac7d-12b0731731ba)

### Operating System

Windows 10 22H2

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v22

### Other Mods

WorldEdit 7.2.15 for 1.20.1 (I've tried without it, nothing changed)

**Comment by SHXRKIIE** [comment]
Instead of choosing the dimension just create a waypoint and it should place it in the nether
