### ISSUE TITLE
Would you consider bumping BMC3 to 1.19.4

### ISSUE THREAD

**Issue by mbainter** [LunaPixelStudios/Better-MC#1504]
### Describe the Bug

This is not a bug in the modpack, but rather in forge itself in versions built against releases prior to 1.19.4.  [This PR describes the problem in detail](https://github.com/MinecraftForge/MinecraftForge/pull/9133), which was merged back in March and released in 45.0 for 1.19.4 only.

The sheer number of entities that can be generated with even a few players can have a heavy impact on performance. Being able to tweak the mob spawning rates and caps would be a useful tool for running a server on this modpack. Unfortunately, because of this bug there are significant downsides to attempting that (disabling mob spawners, for example)

### Reproduction Steps

No real reproduction steps here, because this is a known bug, it's just a question of whether 1.19.4 is a feasible target for support, or if the changes in .3 and .4 are too significant to compensate for.

### Crash Report or Log

N/A

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc 3 v19 and v20

### Other Mods

N/A

**Comment by SHXRKIIE** [comment]
1.19.4 just still misses some mods and it will cause issues for older worlds. if you want to mob cap then just add a mod that does that
