### ISSUE TITLE
Crash upon load start

### ISSUE THREAD

**Issue by queeringtheconstruct** [LunaPixelStudios/Better-MC#1506]
### Describe the Bug

I begin starting up BMC4 and it loads to the forge mod loader but exits and crashes with exit code 1 before it can fully load the game

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/queeringtheconstruct/c264fd61b49921369a61cff0578bd407

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC v21

### Other Mods

Minecolonies
Tough as Nails

**Comment by Frontear** [comment]
your error log indicates no chat reports is causing the crash, and as far as I am aware, we do not ship with NCR. Please remove it or consult their mod developers on how to fix the crash.

**Comment by queeringtheconstruct** [comment]
Removed NCR, I think I saw that that somehow got added to my mods and was causing trouble i thought i removed it but i guess it added itself back somehow, went to launch the game now and got a different error message;

**Comment by Frontear** [comment]
I'd need your whole log to know what's causing it

**Comment by SHXRKIIE** [comment]
You are crashing because you didnt add Minecolonies dependancies, please remove it
