### ISSUE TITLE
spawning and falling into the void after game crashed

### ISSUE THREAD

**Issue by intox-slimy** [LunaPixelStudios/Better-MC#1509]
### Describe the Bug

so i tried to go fight The Void boss and my crashed
i restart it , and i find myself falling into the void , elytras wont work, my void totem popped , still falling into it and i dunno what to do, this world is in hardcore so if i die i loose everything

### Reproduction Steps

1. enderpearl in the portal to go fight The Void
2.game crashed
3.restart and falling into the void 
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/152788035/06beaf1c-9ef6-465b-bfcf-235af0b5b9af)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 V20

**Comment by SHXRKIIE** [comment]
Need crash report and what mods you added
