### ISSUE TITLE
BMC4 - 1.20.1 - java 18 - forge 47.2.6 - "gigant mushroom like structure freezes our computer without crashing" - 8 gb ram on server - 4gb ram each pc

### ISSUE THREAD

**Issue by pizzul** [LunaPixelStudios/Better-MC#1510]
### Describe the Bug

it's okay when we (my girl and i, each one on different pc's) are around the mushroom village. but when any of the two of us get close to the big mushroom structure like on the center; the game of the one who did it; just freezes a long time without crashing. there's no error report from the server console neither, everything seems to keep working okay from there. i hope there's something, at least, to try. and i hope my english is readable, im from argentina. out of this, we are really enjoying the modpack, thanks <3

### Reproduction Steps

1.get close to the gigant mushroom like structure on the center of the mushroom village, that's it
2.
3.
...

### Operating System

Windows 11 the one who host the server and Windows 10 the other. both freezes 

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

### Other Mods

i've deleted "falling trees" bc it was to overpowered or not well configured and added "panda's falling trees" to replace it. also added "small ships" and "simple planes". everything on 1.20.1

**Comment by SHXRKIIE** [comment]
In the future dont modify the modpack
