### ISSUE TITLE
I can't fill buckets with lava/water because it fills with milk when I right click

### ISSUE THREAD

**Issue by VekuVT** [LunaPixelStudios/Better-MC#1511]
### Describe the Bug

When I have a bucket on the hand and I right click it fills with milk. No matter where you look, even when you look at water or lava, it fills with milk which makes it impossible to collect water or lava.

### Reproduction Steps

1.get a bucket
2.Right click

### Crash Report or Log

No

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v60.5

### Other Mods

No

**Comment by SHXRKIIE** [comment]
No issues here, unles you added mods or updated mods it shouldnt happen
