### ISSUE TITLE
Bug with recipe from Sculked mod

### ISSUE THREAD

**Issue by DeadPigman17** [LunaPixelStudios/Better-MC#1512]
### Describe the Bug

You can't craft the echo copper ingot from the Sculked mod, in fact, it doesn't even appear in the JEI menu. Also, when placing 9 copper ingots into the crafting grid, you get the option to craft both a regular copper block and an echo copper block, which shouldn't happen.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC3 v20

**Comment by SHXRKIIE** [comment]
Update to latest

**Comment by DeadPigman17** [comment]
Update what? I have the latest version of both the modpack and the Sculked mod.
