### ISSUE TITLE
Eternal Slumber

### ISSUE THREAD

**Issue by KrispyKrabR714** [LunaPixelStudios/Better-MC#1513]
### Describe the Bug

Upon updating the BMC4 realm I'm on to v23, my character suddenly entered a sleeping animation and refused to wake up. Restarting the game, and redownloading the mod pack didn't address the issue.

### Reproduction Steps

1. Update to v23
2. Try to take tomatoes out of a skillet
3. Fall the fuck to sleep
...

### Screenshots and Videos

![Better MC  FORGE  1 20 1 12_5_2023 9_03_31 AM](https://github.com/LunaPixelStudios/Better-MC/assets/153024982/3fbfc71a-5810-43b7-8597-f634add20ede)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v23

### Other Mods

None

**Comment by SHXRKIIE** [comment]
Disable th eidle state in the watut-client config or update to the HF version
