### ISSUE TITLE
BMC-4 (1.20.1) Twilight Dimension, Map Not Working Correctly

### ISSUE THREAD

**Issue by HinashiSenpai** [LunaPixelStudios/Better-MC#1514]
### Describe the Bug

![2023-12-06_04 07 26](https://github.com/LunaPixelStudios/Better-MC/assets/96591580/bc9a8597-e67d-4c80-9f01-29c481cccc36)

Just Visited Twilight Dimension and saw this bug, tried to restart the game etc but nothing working, running a server version and given 6gb of ram

### Reproduction Steps

1.
2.
3.
...

### Operating System

Server- Win 10, Client- Win 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V23

### Other Mods

no

**Comment by SHXRKIIE** [comment]
Update Xaero's mod or wait for new update

**Comment by HinashiSenpai** [comment]
> Update Xaero's mod or wait for new update

i just noticed one more thing that my friends are playing
![image](https://github.com/LunaPixelStudios/Better-MC/assets/96591580/94affd22-9737-49e7-adb0-c53c1f676d15)

and in the player tab its showing "ZZ" instead of ping what is this ?? its a bug or what

**Comment by SHXRKIIE** [comment]
Will be fixed in next update
