### ISSUE TITLE
Borderless Fullscreen Option Missing in BMCv23

### ISSUE THREAD

**Issue by CrabdaddyLonglegs** [LunaPixelStudios/Better-MC#1515]
### Describe the Bug

Before there was an option for borderless fullscreen in video settings. Now there's just a checkbox for whether or not fullscreen is on.

### Reproduction Steps

options>video settings>

### Screenshots and Videos

before
![image](https://github.com/LunaPixelStudios/Better-MC/assets/124300018/a772eb3e-ee98-4491-b980-631686fda31e)
after
![image](https://github.com/LunaPixelStudios/Better-MC/assets/124300018/3778bf23-8e2d-4b47-94de-939f8adc2cff)

### Crash Report or Log

N/A.

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMCv23HF

### Other Mods

N/A

**Comment by VongSak15** [comment]
use Borderless Minecraft tool https://github.com/Mr-Technician/BorderlessMinecraft/releases/tag/v1.3.4

**Comment by CrabdaddyLonglegs** [comment]
Was Borderless Minecraft tool baked into previous versions or something? Just curious what changed and why.
