### ISSUE TITLE
The game keep crashing because of lambdynlights class error

### ISSUE THREAD

**Issue by hachimanhiki12** [LunaPixelStudios/Better-MC#1516]
### Describe the Bug

The log says something like "[04:05:45] [main/ERROR]: Error loading companion plugin class [dev.lambdaurora.lambdynlights.LambDynLightsMixinPlugin] for mixin config [lambdynlights.mixins.json]. The plugin may be out of date: InvocationTargetException:null
java.lang.reflect.InvocationTargetException: null" but The mod "lamb dynamic lights" is not there I do not know why the game register this mods
I have tried to manually added the mod but it does not work, still same error I needed help so bad on this 
I will include the full log here 
[2023-12-08-1.log](https://github.com/LunaPixelStudios/Better-MC/files/13605376/2023-12-08-1.log)

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/vMjf01bG

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC v23hf

### Other Mods

Inventory profiler next
Ironchested
Travellers backpack
Resourful lib
Crop Marker
Better F3

**Comment by SHXRKIIE** [comment]
Please dont modify the modpack and expect it to be a fault of ours, the real reason its crashing is because of the forge version change
