### ISSUE TITLE
Better MC PLUS 1.19.2 Keeps Crashing When Trying To Launch

### ISSUE THREAD

**Issue by saintlucifer-WG** [LunaPixelStudios/Better-MC#1517]
### Describe the Bug

I get error code 1 every single time I try launching the game, no matter what it just crashes everytime I try to launch the modpack.

### Reproduction Steps

1. Download
2. Launch
3. Crash
...

### Crash Report or Log

https://file.io/EfmJSZ538TQc

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMCPLUSv2

**Comment by SHXRKIIE** [comment]
Your file is deleted, try using ATLauncher
