### ISSUE TITLE
Bmc2 wont load

### ISSUE THREAD

**Issue by Murchadh89** [LunaPixelStudios/Better-MC#1518]
### Describe the Bug

Installed tinkers and sophisticated backpacks with the modpack. Ran it through curseforge and ran fine twice. Then third time goes to the launcher screen but wont go into the game. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Bmc v20

### Other Mods

Tinkers construct
Sophisticated backpacks

**Comment by SHXRKIIE** [comment]
Well we need logs but you modified the modpack so its mostly an issue with that
