### ISSUE TITLE
Better end island prevents additional egg spawns

### ISSUE THREAD

**Issue by Al2CHANGEL** [LunaPixelStudios/Better-MC#1519]
### Describe the Bug

BEI prevents the respawn egg function of dragon mounts. Is there a way to to have dragon mounts supersede BEI in the creation and management of the egg respawn?

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMCv4

**Comment by SHXRKIIE** [comment]
I would say ask integration on the BEI github

**Comment by Al2CHANGEL** [comment]
or remove it from bmc4 since it conflicts with one of the major selling points of the mod pack
