### ISSUE TITLE
Float glitch

### ISSUE THREAD

**Issue by IceVemon** [LunaPixelStudios/Better-MC#1520]
### Describe the Bug

You get to float on the same Y level as the bottom of a lit Nether Portal and move around by using Tidal Claw (leviathan) on the bottom of the Nether Portal. You can use it on the top and go flying up but you stop, I think it's because of the momentum. The only way to stop it is by using the Tidal Claw, Ender Pearl doesn't work.

### Reproduction Steps

1. Lit Nether Portal
2. Use Tidal Claw on it 
3. You float or fly up a bit
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/153370276/df2c91c2-b38c-4aa7-a79f-83d6d50141f5)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/153370276/277a4fc0-31c3-4c2d-8c4d-bc04844615e1)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC v23 (latest version)

### Other Mods

None

**Comment by SHXRKIIE** [comment]
Will report to Cataclysm mod

**Comment by IceVemon** [comment]
I found a way to fly with it. Just use a Elytra, fly down. Then hold w and press space and you'll fly into the air
