### ISSUE TITLE
iventory items show when inventory is not open

### ISSUE THREAD

**Issue by blujay073** [LunaPixelStudios/Better-MC#1521]
### Describe the Bug

After playing for a while I realized the items in my inventory show onscren even when my inventory is not open.

### Reproduction Steps

I honestly have no idea how this happened, it seems pretty random

### Screenshots and Videos

![image_2023-12-10_155911435](https://github.com/LunaPixelStudios/Better-MC/assets/153461871/1b61f48c-4084-4b8e-b774-0b67936c12c4)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4

**Comment by CrabdaddyLonglegs** [comment]
It's the "i" key on the keyboard. Pressing it swaps modes. Tap it a few times.

**Comment by blujay073** [comment]
omg. im soooo smart
