### ISSUE TITLE
Use Light and Shadow Sky Anomaly

### ISSUE THREAD

**Issue by 1YuanJie1** [LunaPixelStudios/Better-MC#1524]
### Describe the Bug

The light and shadow I use is photon-main, during the day and at night, there will be two large white textures in the sky, I guess it is the purple sky at night that conflicts with the light and shadow, I want to know how to solve it, thank you.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

This mod was crashing my game a lot, so it was removed

**Comment by 1YuanJie1** [comment]
![screenshot20231212](https://github.com/LunaPixelStudios/Better-MC/assets/153535683/1981386c-de8d-438d-886f-048fef914b5b)

**Comment by chorbintime** [comment]
report it to the creators of the shaderpack
