### ISSUE TITLE
Infinite void in the Aether

### ISSUE THREAD

**Issue by Orchard28** [LunaPixelStudios/Better-MC#1525]
### Describe the Bug

Fell off of an island in the Aether and I'm just in a continuous freefall, well under a Y level of -20,000 currently, didn't do anything specific as I was falling like using a parachute, opening the questbook or opening my inventory, it seems like the game missed the trigger to teleport me into the overworld

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-12-11_22 38 11](https://github.com/LunaPixelStudios/Better-MC/assets/153578022/4c5b4cf8-2fd4-4944-87a5-3bd715fc64d7)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC Forge, BMC4, V23 HF, on Curseforge

### Other Mods

No additional mods downloaded

**Comment by Orchard28** [comment]
Seemed restarting the game completely fixed this, not sure how the interaction happened though

**Comment by chorbintime** [comment]
report it to the aether devs
