### ISSUE TITLE
Eden Ring Portal

### ISSUE THREAD

**Issue by tinypandamaster** [LunaPixelStudios/Better-MC#1527]
### Describe the Bug

After building the Eden Ring Portal exactly as told, when wanting to activate through lighting the gold block, nothing happens. The portal doesn't open.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-12-13_10 11 22](https://github.com/LunaPixelStudios/Better-MC/assets/153716155/c03b266f-2787-45c5-be27-b1587210b4a2)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc v23.5

**Comment by SHXRKIIE** [comment]
Oops, we forgot to remove the Eden ring quest my bad, it is not available for 1.20

**Comment by Hosni-24bey** [comment]
well that's a bummer, wished I tried activating the portal before building a whole floor for it -_-
