### ISSUE TITLE
Can't add an enchantment

### ISSUE THREAD

**Issue by EvilMDR** [LunaPixelStudios/Better-MC#1528]
### Describe the Bug

I've tried to add Shared Pain 1 book to my Infernal Forge and I couldn't, tried it with an iron sword as well and still nothing

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/108546427/9aab33c7-6851-4e63-9df6-23155b0a33b5

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v24HF

**Comment by SHXRKIIE** [comment]
It seems shared pain I doesnt exist only III, you could have obtained it before the mod might have changed, III works

**Comment by EvilMDR** [comment]
I've obtained it when I updated the pack so idk
