### ISSUE TITLE
Snow layers spawning mid-air and piling up in cherry grove biome

### ISSUE THREAD

**Issue by catAngent** [LunaPixelStudios/Better-MC#1530]
### Describe the Bug

Snow layers spawn mid-air in cherry grove biome, piling up and making the biome look ugly and impossible to move through given enough time. This does not happen with any adjacent biomes like the frozen peaks, lavender fields or forest.

### Reproduction Steps

1. Create a new world
2. Find a cherry grove biome
3. Run /weather rain
4. Observe snow layers appearing mid-air and piling up over time.

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/97902025/3e4ffb99-8c33-46ac-bd8f-caa263464a55)

### Operating System

gentoo linux

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v24

**Comment by chorbintime** [comment]
try removing snowy spirit / snow real magic
