### ISSUE TITLE
crashed upon launching

### ISSUE THREAD

**Issue by raffi2132** [LunaPixelStudios/Better-MC#1531]
### Describe the Bug

So i just installed bmc4 V24 then when i launched it just crashed. I didnt modify it, tried upgrading my driver, reinstalling but still it just keeps on crashing

### Reproduction Steps

1. launch minecraft
2. crash
...

### Crash Report or Log

https://pastebin.com/rRXLc7he

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v24

### Other Mods

no

**Comment by SHXRKIIE** [comment]
delete the server browser mod or config
