### ISSUE TITLE
mobs freezing 

### ISSUE THREAD

**Issue by Xqwsd** [LunaPixelStudios/Better-MC#1532]
### Describe the Bug

while around 32 to 37 blocks away or above mobs they will completely freeze even if they are in lava burning they will freeze and take no damage until ur around 28 block from them making afk farms impossible 

### Reproduction Steps

1.Go into creative and near any mob fly 32 blocks above them maybe a little more
3.
...

### Screenshots and Videos

https://streamable.com/qyegj0

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v21

**Comment by SHXRKIEgg** [comment]
They are just out of culling range

**Comment by Xqwsd** [comment]
> They are just out of culling range

how would i go about fixing/changing the culling range
