### ISSUE TITLE
Z-fighting with snow real magic mod and biomes o plenty

### ISSUE THREAD

**Issue by Ahnaf-Ahmed** [LunaPixelStudios/Better-MC#1533]
### Describe the Bug

When it is snowing the snow will layer within leaves and cause bad z-fighting issues. This seems to also cause some leaves to break and entities to drop to the ground leaving a lot of entities as well. This is observed with Jacaranda leaves and flowering oak leaves from biomes o plenty but not normal oak leaves. This is not however observed with redwood and mahogany leaves which are both also from biomes o plenty.

### Reproduction Steps

1. Navigate to a biome it can snow in
2. Wait for it to snow (observed during winter season)
3. Go to a leaf with z-fighting and observe that in the f3 menu it says you are looking at a snow real magic block
4. Observe when breaking the leaf the snow layer inside breaks leaving the leaf.
...

### Screenshots and Videos

![2024-01-06_22 18 37](https://github.com/LunaPixelStudios/Better-MC/assets/28603391/2fc6e9ae-a8eb-4f33-a79e-f0ab655927f8)
![2024-01-06_22 32 44](https://github.com/LunaPixelStudios/Better-MC/assets/28603391/4405245c-2060-4267-83ec-1ca0864e0018)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc 4 v24

**Comment by chorbintime** [comment]
report it to the snow real magic developer
