### ISSUE TITLE
Paradise Lost Portal Error

### ISSUE THREAD

**Issue by DetectiveEugene** [LunaPixelStudios/Better-MC#1536]
### Describe the Bug

When attempting to build a Paradise Lost/Aether portal, the expected blue portal frame is instead red. Hovering over the red portal frame lists the frame as _block.customportalapi.customportalblock_. Going through this portal teleports the player to the roof of the Nether.

Note: This is my first ever bug report, apologies if I missed anything or included information that isn't helpful.

### Reproduction Steps

1. Create a Paradise Lost / Aether portal frame and light it.
2. Go through the portal to teleport to the roof of the Nether.

### Screenshots and Videos

![Portal Error 2](https://github.com/LunaPixelStudios/Better-MC/assets/155937878/87eccd25-138f-451e-9379-8156576bbb74)
![Portal Error 1](https://github.com/LunaPixelStudios/Better-MC/assets/155937878/c6de4617-f77b-4588-8ea1-335f34d1f985)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] - BMC1 (1.19.2 v20.zip)

### Other Mods

I really loved Tinkers' Construct on Sky Factory, but I know that mod is Forge. However, [this](https://www.curseforge.com/minecraft/mc-mods/hephaestus-fabric) looks like a port? Loving the modpack otherwise :)

**Comment by chorbintime** [comment]
you did not install the modpack correctly. please reinstall using ATLauncher

**Comment by gaberust** [comment]
I am experiencing the same issue (1.19.2, Better MC Fabric v20, macOS, Prism Launcher).

I reinstalled the modpack from scratch using ATLauncher, and I am still experiencing the issue.

@DetectiveEugene , have you had any luck with this?

**Comment by gaberust** [comment]
@DetectiveEugene , see [Paradise-Lost Issue #781](https://github.com/devs-immortal/Paradise-Lost/issues/781)

"
Please download this version of the portal API and drop it into your mods folder, this should resolve the problem:
[https://maven.kyrptonaught.dev/net/kyrptonaught/customportalapi/0.0.1-beta63.5-1.19.X/customportalapi-0.0.1-beta63.5-1.19.X.jar](https://maven.kyrptonaught.dev/net/kyrptonaught/customportalapi/0.0.1-beta63.5-1.19.X/customportalapi-0.0.1-beta63.5-1.19.X.jar)
"

This fixed it for me, ATLauncher not required. This is also the pinned fix in the LunaPixel Discord server

**Comment by annasajkh** [comment]
can you guys update the modpack with the fix
i'm using aternos and you can't add or remove mod from a modpack

**Comment by chorbintime** [comment]
aternos is unsupported, and theres nothing we can do about it on our end if the portalapi version is not available on curseforge. if you want to host a server that actually works while still being free just use the serverpack on the modpack page

**Comment by chorbintime** [comment]
ill also reiterate the fact that the screenshots you provided clearly show you did not install the modpack correctly - you are missing every single resourcepack.
