### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by KillerBunnyKay** [LunaPixelStudios/Better-MC#1537]
### Describe the Bug

Trying to start a new world crashes the game.

### Reproduction Steps

1. open Minecraft
2. create new world 
3. crashes 
[hs_err_pid1868.log](https://github.com/LunaPixelStudios/Better-MC/files/13875987/hs_err_pid1868.log)

4.
5.
...

### Operating System

Mac 

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

**Comment by chorbintime** [comment]
follow the performance guide linked on the main menu and change your java version to the recommended one
