### ISSUE TITLE
exit code 6 and 9

### ISSUE THREAD

**Issue by Noeeeeeeeeeee** [LunaPixelStudios/Better-MC#1538]
### Describe the Bug

I'm on m1 and I can't stop getting either of these exit codes, I've been able to run it briefly just fine before it crashed, but it always does. I have no clue what to do atp

### Reproduction Steps

1.open minecraft with modpack
2.try to play on a friendgroup server
3.fucking crashes
...

### Operating System

MacOs Sonoma 14.2.1

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

newest one

**Comment by SHXRKIEgg** [comment]
Cant help with no crash report

**Comment by gaberust-penconsultants** [comment]
My buddy and I have had this issue earlier today. Make sure you are using the x86_64 build of Temurin 17+, even if you are on apple silicon.

**Comment by ShivanshGupta0073** [comment]
and are you using curseforge if yes then try ATLauncher

**Comment by gaberust** [comment]
@Noeeeeeeeeeee My buddy went through the same problem on an M1 mac the other day. There's a couple things you can do to remedy it (I'm assuming, as already pointed out, there's a serious lack of details here):

Use an optimized version of Java, and specifically, use an x64 version. This modpack does not like Apple Silicon for some reason, and short of doing this we couldn't get it to work for him at all. Your M1 mac has a translation layer built in for x86/64 code, so this will work with a slight performance impact. If you're using the official launcher, you'll need a different one for this, such as ATLauncher or Prism (ATLauncher will be easier). I've already filtered this down to what works, you'll need to download and run the .pkg file:
[](https://adoptium.net/temurin/releases/?os=mac&arch=x64&package=jre&version=17
)

In your launcher of choice, make sure you change the Java version to the x64 Temurin one you just installed ^

Beyond that, Better MC is not a light modpack. You'll probably need to bump up the default RAM allocations. I personally run a maximum allocation of 8192 (8GB), but I have friends who get away with 6144 (6GB). With all this, you still probably won't be able to run a local singleplayer world (unless you give it more RAM), but you should be able to play on the server with no issues.

If you get stuck with any of this or need more help/details, let me know.

**Comment by hmongdev** [comment]
@gaberust 

> Use an optimized version of Java, and specifically, use an x64 version.

I'm running on an M2 Mac Mini, but you're saying you have to use the x64 version?

As opposed to the ARM64? (That's designed for Mx models)
![Uploading Screenshot 2024-02-07 at 11.05.25 PM.png…]()

**Comment by gaberust** [comment]
@hmongdev I know it sounds strange, but that is correct. Your M2 Mac supports running x64 binaries using Rosetta 2, which is probably already installed. Switching to the x64 version of the Java runtime solved that exact problem for my buddy on his M1 Mac. My suspicion is that there is some low level reflection or C code going on in one of the mods in the pack that doesn't play well with ARM, causing your code 6. There is a slight performance impact to using the x64 version of Java since it isn't native, but in my experience the impact was negligible and the game actually worked.

**Comment by ALFIE243** [comment]
Hey, on Mac, there is a mod called Spark. You just need to remove that to fix exit code 6 I don't know how to fix exit code 9

**Comment by chorbintime** [comment]
## For Mac devices using Apple Silicon/arm (M1/M2/etc.) CPUs
There is an issue with Java 17.0.8 and newer where you may experience "A fatal error has been detected by the Java Runtime Environment", which can cause the Java runtime to crash under a variety of circumstances. To resolve this:
1. Install the `Zulu JDK 17.0.1+12 arm64` build of Java:
Direct download: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=7eb8ee44-ab7f-4afb-9e42-32bd76416400 
2. Download/Install ATLauncher or Prism Launcher (CurseForge Launcher is known to cause issues)
3. In Instance settings > Java, manually specify the following Java path: `/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home`
4. If using ATLauncher, Disable "Use Minecraft-bundled JDK"
5. Launch the game

**Comment by chorbintime** [comment]
Also, spark likely has nothing to do with this. If you are still experiencing issues related to this please open a new issue.
