### ISSUE TITLE
Server crash caused by configured defaults in v24

### ISSUE THREAD

**Issue by JulianVennen** [LunaPixelStudios/Better-MC#1539]
### Describe the Bug

The server files for v24 crashes due to an error with configured defaults.

### Reproduction Steps

1. Download the server files
2. Start them

### Crash Report or Log

https://mclo.gs/HwLZhfx

### Operating System

Linux

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v24

**Comment by SHXRKIEgg** [comment]
There were no server files for v24 until 7 hours ago so not sure where you got it from, please download the proper serve files

**Comment by JulianVennen** [comment]
We use the serverFileId (or alternateFileId if that's not set) from the CurseForge API.
Maybe CurseForge shows server files in the API even if they haven't been approved yet?
