### ISSUE TITLE
[Bug][BMC4] FTB Quest Description and Demand Don't Match

### ISSUE THREAD

**Issue by chemlzh** [LunaPixelStudios/Better-MC#1540]
### Describe the Bug

The FTB Quest shows that defeating Harbinger will give me an ignitium ingot. However, the actual demand for this quest is to defeat Leviathan. Therefore, when I defeat the Harbinger, FTB Quest shows me that the quest is not done, and I cannot have the reward.
In addition, I have defeated the Leviathan before the quest list is updated. However, the FTB Quest for Leviathan is not unlocked after modpack update, and I don't know how to unlock it. Could you please give me some hint to solve it?

### Reproduction Steps

1. Finish dependency quest for Harbinger.
2. Find the ancient factory and defeat Harbinger.
3. The FTB Quest reward is not unlocked.

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/32123043/3511b04e-7c28-4ba9-8f2c-f4391f3ee470)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/32123043/d391681a-a115-4f45-909f-135f5ba8a491)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/32123043/23bcf69d-a2c4-4561-8c22-5579e617a9c2)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/32123043/8e7b8a9e-3d96-42e0-85f2-2c4844cb08a5)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v24 HotFix

**Comment by chorbintime** [comment]
will be fixed in next update, thank you

**Comment by chorbintime** [comment]
fixed
