### ISSUE TITLE
Hydra isnt taking damage 

### ISSUE THREAD

**Issue by Tvmpxn** [LunaPixelStudios/Better-MC#1541]
### Describe the Bug

The hydra does all the attacks (I'm Assuming so) but its not taking any damage from my bow, sword, axe nor even instant damage potions, no matter how close or far I am from the hydra. Doesn't do anything. and the hydra started with 3 heads, then came out with 5. Please fix this, I would love to progress through the twilight forest quest tree 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MC [FORGE] - BMC1

**Comment by ShivanshGupta0073** [comment]
Hydra from the twilight forest right you can damage it only on the head with the mouth open

**Comment by ShivanshGupta0073** [comment]
> Hydra from the twilight forest right you can damage it only on the head with the mouth open

And it takes more fire damage
