### ISSUE TITLE
eror crash

### ISSUE THREAD

**Issue by KaramilkManiac** [LunaPixelStudios/Better-MC#1542]
### Describe the Bug

Cant open the game with the mode pack

### Reproduction Steps

1.install the mod pack (version v24 HF)
2.try to run mod pack from cursed forge
3. When I launch the game from minecraft luncher in the profile forge, I get this messsage error: «Error Game crash exit code: 1»
See the crash report bellow:

### Screenshots and Videos

[hs_err_pid18596.log](https://github.com/LunaPixelStudios/Better-MC/files/13929946/hs_err_pid18596.log)

### Operating System

windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

version v24 HF

**Comment by chorbintime** [comment]
Update your drivers and reinstall on ATLauncher

**Comment by KaramilkManiac** [comment]
When I use minecraf vanilla it work. Also work with other modpacks

**Comment by KaramilkManiac** [comment]
so, this is not the problem

**Comment by chorbintime** [comment]
it is the problem, you just need to update your drivers.

**Comment by KaramilkManiac** [comment]
Wich drivers? because  they all are up to date. So say my computer when I check

**Comment by KaramilkManiac** [comment]
Well... it seems that you where right... so... LOts of thanks... XD
