### ISSUE TITLE
Mod guide books not working

### ISSUE THREAD

**Issue by Ste-Mich** [LunaPixelStudios/Better-MC#1543]
### Describe the Bug

Mod guide books seem to be broken. Some not opening or even crashing. The end for dummies, Seasonal Compendium. Both do not open. Guide from AE2 even crashes, though that is an external mod.

I just updated to the newest version. Unfortunately it did not help.

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v23.5 and v24

### Other Mods

FabricTailor, AE2, EasyAuth

**Comment by chorbintime** [comment]
please report it to the developers of the individual mods, as we do not have control over how their books operate
