### ISSUE TITLE
Z to crawl won't work (as well as C to zoom)

### ISSUE THREAD

**Issue by FriendKevren** [LunaPixelStudios/Better-MC#1544]
### Describe the Bug

I'm trying to complete the quest Important Controls and while attempting to Z to crawl I zoomed the camera forward instead. I remapped the controls so Z was free and still I cannot crawl. Same goes with C to zoom

### Reproduction Steps

1. Z to crawl
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc 4 v24

**Comment by chorbintime** [comment]
will be fixed in next update
