### ISSUE TITLE
CTD when viewing Wheat's breeding page in JEI

### ISSUE THREAD

**Issue by 404exchange** [LunaPixelStudios/Better-MC#1545]
### Describe the Bug

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "com.faboslav.friendsandfoes.api.MoobloomVariant.getName()" because the return value of "com.faboslav.friendsandfoes.api.MoobloomVariantManager.getDefaultMoobloomVariant()" is null

### Reproduction Steps

1. Press U on wheat to view uses in JEI
2. Go to the breeding tab, and press next to go to page 2 or 3
3. This caused a CTD for me
...

### Crash Report or Log

https://pastebin.com/D9jjc91J

### Operating System

Debian 12

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 1.20.1 v@$ HF - Forge 47.2.17

### Other Mods

None

**Comment by chorbintime** [comment]
report it to the friends and foes developers, if updating that mod doesnt fix it
