### ISSUE TITLE
ender dragon fight is broken 

### ISSUE THREAD

**Issue by 78r785** [LunaPixelStudios/Better-MC#1546]
### Describe the Bug

the middle end crystals wil not be destroyed no matter what i do

### Reproduction Steps

1.i spawned the dragon and set a way stone before it fully spawned 
2.use the waystone to go back to over world 
3.go back to the end 
...

### Screenshots and Videos

![Screenshot 2024-01-15 200623](https://github.com/LunaPixelStudios/Better-MC/assets/156650140/3c97cf71-7a8c-4c56-a70e-fc14053eea7e)

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmcv20

### Other Mods

essentail mod

**Comment by chorbintime** [comment]
Essential is incompatible with all of our modpacks. It is known to cause world corruption and other issues.
