### ISSUE TITLE
[QoL Enhancement][Forge][BMC4] Need more ways to get dragon heads for trading with goblins

### ISSUE THREAD

**Issue by chemlzh** [LunaPixelStudios/Better-MC#1547]
### Describe the Bug

(The original description remains here. However, since I have solved the problem, I decided to change this issue from bug report to QoL enhancement suggestion)

Since "Better End Cities" datapack rewrites the end city & end ship generation, the vanilla end ship (with a dragon head) cannot be spawned anymore, therefore we cannot obtain dragon head in BMC4. However, the highest grade trade that goblins can offer needs dragon head, so we cannot make a deal with goblins using dragon head.

I suggest that BMC4 should add approaches for obtaining dragon heads, either by slaining ender dragon, or by end city looting. By this way we can trade with goblins to get finest pickaxes/swords!

(Updated on 2024/01/17)

I finally located the dragon head position, so it's not a bug. Still, the dragon head attainment is a bit difficult, and dragon heads are not renewed resources once they are collected. Therefore, I would like to have more approaches for obtaining dragon heads.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

BMC4 v24 HF

**Comment by chemlzh** [comment]
After examining the renewed end ship structure thoroughly, I finally found the dragon head. So it's not a bug. It just means players should examine with more caution. Still, I would like to have more approaches for obtaining dragon heads. I have searched CurseForge for a while, and I can't find a suitable mod for dragon head obtainment.

**Comment by chorbintime** [comment]
will look into it
