### ISSUE TITLE
Buried treasure maps are not working - can't get heart of the sea

### ISSUE THREAD

**Issue by Samo26o** [LunaPixelStudios/Better-MC#1549]
### Describe the Bug

Whenever I try to view buried treasure maps they turn into normal Minecraft maps, means I can't find heart of the sea without extreme luck or cheats

### Reproduction Steps

1. Find a buried treasure map in a sunken ship
2. Try to view it
3. Right click the map

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v24 HF

**Comment by chorbintime** [comment]
did you modify the modpack in any way? 

where did you obtain the map? what structure, etc

**Comment by Samo26o** [comment]
> did you modify the modpack in any way?
> 
> where did you obtain the map? what structure, etc

Modpack has not been modified in any way. Found multiple maps in different structures including shipwrecks, underwater ruins and other vanilla water-based structures. None of them work, it shows as a buried treasure map in the chest and then when you pick it up it is blank without any marker (just like a normal blank map) and right clicking makes it a blank map

**Comment by Samo26o** [comment]
did not mean to close

**Comment by chorbintime** [comment]
will test in next update
