### ISSUE TITLE
Crafting Table Lag

### ISSUE THREAD

**Issue by SenpaiOfWeebs** [LunaPixelStudios/Better-MC#1552]
### Describe the Bug

Every time I open the crafting table menu, the game starts to lag horribly. It makes it near impossible to craft items.

### Reproduction Steps

1. Use crafting table
2. Try to craft item
3. Lag
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC v24

**Comment by chorbintime** [comment]
please run a spark profiler by running the following command:
/sparkc profiler start

then, open the crafting table and run the stop command after closing the GUI
