### ISSUE TITLE
Damage freezing

### ISSUE THREAD

**Issue by floobfloob** [LunaPixelStudios/Better-MC#1553]
### Describe the Bug

Whenever I play using this modpack on my friend's server the game runs fine. Whenever I take any damage in survival my game will freeze and I will have to close out of the game. It's not a crash so I'm not seeing any crash logs - not sure what is causing this issue. I recently switched to Windows 11 and it doesn't seem like Minecraft installed cleanly. 

### Reproduction Steps

1.Take any type of damage in survival
2. Game freezes
3. Terminate game
...

### Crash Report or Log

https://paste.atlauncher.com/view/de48207c-09e6-4df8-827e-809fe3c18f3f

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC

### Other Mods

N/A

**Comment by floobfloob** [comment]
Game is crashing when trying to launch after trying to tweak. 
Latest crash log: https://paste.atlauncher.com/view/b76181c3-bce1-4135-ba24-c08bac7f2bd8

**Comment by chorbintime** [comment]
please follow the performance guide @ https://rpg.prominence.wiki/performance-guide
