### ISSUE TITLE
better minecraft fabric server BMC1 1.19.2 v19.5

### ISSUE THREAD

**Issue by Teembias** [LunaPixelStudios/Better-MC#1554]
### Describe the Bug

better minecraft fabric server BMC1 1.19.2 v19.5 isn't work, i open it and few sencond it crashed,How to fix it?

### Reproduction Steps

1.Open fabric server 1.19.2
2.Put Better minecraft server pack into server modpack
3.start server
4.server crashed

### Crash Report or Log

https://drive.google.com/file/d/1CsQRowAP2qQpR1FBBbsxwmIVK1BaD-dT/view?usp=sharing

### Operating System

window 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v19.5

**Comment by ShivanshGupta0073** [comment]
Upload the log through https://mclo.gs

**Comment by chorbintime** [comment]
please update to v20. we offer no support for old versions.
