### ISSUE TITLE
"Curse.Radium.InstallManagement.InstallTaskFailedException' was thrown."

### ISSUE THREAD

**Issue by hyperfruit-Official** [LunaPixelStudios/Better-MC#1556]
### Describe the Bug

i get an error called "Curse.Radium.InstallManagement.InstallTaskFailedException' was thrown." when trying to import a modpack into curseforge.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

"Curse.Radium.InstallManagement.InstallTaskFailedException' was thrown."

### Operating System

Windows 10 Pro

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v24

**Comment by chorbintime** [comment]
Do not import the modpack into Curseforge. Just search the modpack and click install.

**Comment by Nubberslaw** [comment]
> Do not import the modpack into Curseforge. Just search the modpack and click install.

That would be a great suggestion if all packs were posted, but some of us have custom packs that CF wont allow to be posted due to a mod thats not on their site.

**Comment by aeholy** [comment]
Would be easy to do if you didnt want to play custom modpacks shared by friends. currently experiencing this issue and quite literally cannot find any solution to this problem anywhere.

**Comment by KitanaiWeeb** [comment]
Not sure if people are still having this issue, I was having this issue with pretty much all NeoFroge mod packs, officially posted ones and custom ones for ages, and all I had to to was hit Repair Installation

<img width="1484" height="811" alt="Image" src="https://github.com/user-attachments/assets/26351bde-de0f-4c05-8c2a-210f02ed4097" />

**Comment by chorbintime** [comment]
guys this is the better mc github we dont have anything to do with Curseforge
