### ISSUE TITLE
World Crashing on Load

### ISSUE THREAD

**Issue by graceparmesan** [LunaPixelStudios/Better-MC#1557]
### Describe the Bug

The bug that occured was when I placed a Springshroom sign and then the game crashed. Now, when attempting to load into that specific world, it will always load, freeze for about 1-2 seconds, hit the save screen, and then crash.

As of this point, I've fixed one bug, and made a few other attempts to fix things:
- I added the dynamic asset loader, as it said it wouldn't load. This issue has gone away
- I've updated the modpack to the newest version (as referenced in Modpack version in form)

Otherwise, I've run out of ideas Thanks for any help you can provide.

### Reproduction Steps

1. Open GDLauncher
2. Load BetterMC instance
3. Load world
...

### Screenshots and Videos

![gdlauncher crash](https://github.com/LunaPixelStudios/Better-MC/assets/158121053/018215d5-2d3d-464a-bed8-494875308be6)

### Crash Report or Log

https://gist.github.com/graceparmesan/291357babc8512e179452b12d38ea1d8

### Operating System

Zorin OS 16.3 x86_64 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 - v20

### Other Mods

- [Dynamic Asset Generator [Forge] v 1.2.0](https://www.curseforge.com/minecraft/mc-mods/dynamic-asset-generator)

**Comment by chorbintime** [comment]
Update the Aether Redux mod, if issue persists then report it to their devs
