### ISSUE TITLE
Warp plates broken - waystones needs an update (1.20.1)

### ISSUE THREAD

**Issue by Jorue23** [LunaPixelStudios/Better-MC#1560]
### Describe the Bug

Warp plates are currently broken in the 1.20.1 version of the pack on multiplayer servers. This is because the version of the waystones mod that is used in the pack is from the [11th Dec 2023](https://www.curseforge.com/minecraft/mc-mods/waystones/files/4947569) and the issue got fixed on the [17th Dec 2023](https://www.curseforge.com/minecraft/mc-mods/waystones/files/4963448). Please update the mod version :)

### Reproduction Steps

1. Join a multiplayer server running the latest version of BMC4
2. Place a warp plate
3. Attune a crystal to it
4. Place the attuned crystal into another warp plate
5. Observer that it doesn't work even tho the crystal is correctly attuned

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v24 HF

**Comment by chorbintime** [comment]
will be fixed soon
