### ISSUE TITLE
Twilight Forest Multiplayer Mission Not Working (1.20.1)

### ISSUE THREAD

**Issue by OniMirage01** [LunaPixelStudios/Better-MC#1561]
### Describe the Bug

When fighting bosses in multiplayer, upon giving boss heads to others, the mission will not be completed unless the person who last hit the boss completes the mission.

### Reproduction Steps

1. Fight Boss with another person
2. After boss dies only one person completes the mission
3. Second person must kill the same boss again to complete mission 
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v24 HF.zip

### Other Mods

Essential Mods, Simply Houses

**Comment by chorbintime** [comment]
this is intentional
