### ISSUE TITLE
Server timeout when player enters the server

### ISSUE THREAD

**Issue by carottX** [LunaPixelStudios/Better-MC#1562]
### Describe the Bug

The server will show "[17:59:56] [spark-async-sampler-worker-thread/WARN] [spark/]: Timed out waiting for world statistics" and later all exisiting players in the server will be disconnected when a player in certain chunks login to the server. 
The server is 2c8g and os is ubuntu 22

### Reproduction Steps

1.  On the server: "sudo bash start.sh"
2.  On the client: enter multiplayer and enter the server
3.
...

### Crash Report or Log

https://paste.ubuntu.com/p/sSGDqPnxBp/

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc4 v24

**Comment by chorbintime** [comment]
let me know if the issue persists in v25

**Comment by hof1102** [comment]
> let me know if the issue persists in v25

so when will v25 serverpack comes out? Now clients are clear to update v25 but waht about servers?

**Comment by chorbintime** [comment]
curseforge needs to approve the serverpack. nothing we can do on our end
