### ISSUE TITLE
Game crashes due to something called "Serverbrowser" and mentions "JSON Readers" this makes the client's game crash.

### ISSUE THREAD

**Issue by Alvaaz16** [LunaPixelStudios/Better-MC#1563]
### Describe the Bug

The bug occurs when I launch the instance again after reinstalling it to try to fix the issue,I keep having to reinstall it every time it crashes but I am looking for a alternate solution to fix the issue. Thats why I need help from a staff member to fix the crash issue occuring without having to reinstall it everytime. 
[crash-2024-02-07_17.34.41-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/14202749/crash-2024-02-07_17.34.41-client.txt)

### Reproduction Steps

1.Install BMC1
2.Launch the instance one time.
3.Try to launch the instance a second time
4.Wait a while, and then the game crashes thus showing the crash report mentioned above
5. Reinstall the instance and it all starts over again every time I want to play BMC1 a second or third time.

### Screenshots and Videos

The crash: ![image](https://github.com/LunaPixelStudios/Better-MC/assets/139409863/df79e881-38a2-4a7f-aae8-833beb2a1075) 
Installing the instance: ![image](https://github.com/LunaPixelStudios/Better-MC/assets/139409863/a9c7dbb0-95f8-41da-8e56-48c158aae3aa)
The instance launches correctly the first time: 
![image](https://github.com/LunaPixelStudios/Better-MC/assets/139409863/1db6b977-1b19-46d0-b2a9-89142eda0e08)
Then when I close that out and try to launch it again the second time: It usually crashes but for some reason it works sometimes but other times it crashes. (The screenshot of the crash message is what happens sometimes when I launch it second times)

### Crash Report or Log

[crash-2024-02-07_17.34.41-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/14202749/crash-2024-02-07_17.34.41-client.txt)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v20 1.19.2

### Other Mods

The original pack no other modifications to the pack has been done.

**Comment by Alvaaz16** [comment]
Also the version is BMC1 v20 1.19.2

**Comment by SHXRKIEgg** [comment]
delete the server browser config
