### ISSUE TITLE
[Server Crashes]Timed out waiting for world statistics.

### ISSUE THREAD

**Issue by hof1102** [LunaPixelStudios/Better-MC#1564]
### Describe the Bug

When players join the server, they have no blocks or terrain in their sight (completely void) and their coordinates show that they are falling; mean time the server begins to report error:
[spark-java-sampler-0-4/WARN] [spark/]: Timed out waiting for world statistics
And it usually also has another error behind:
[Server thread/WARN] [co.ae.ni.Nitrogen/]: Failed to read supporter data.
Minutes later, players are disconnected.
When the server is initially started with a new world save, everything is fine.
This problem occurs after several hours playing, it is really confusing :(

### Reproduction Steps

1.Start a new server and world
2.Play for hours or less, with your friends or alone
3.Log out and log in
4.Here it comes...

### Crash Report or Log

https://gist.github.com/hof1102/3504b05902a56a6bf93b3b6a7ae7e9c6

### Operating System

Windows 10 22H2

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v24 HF

### Other Mods

Scaling Health(And its base silent-lib)
drinkbeer-refill
sophisticatedbackpacks(And its base sophisticatedcore)
appleskin
origins-forge(And its base caelus-forge)
origins-classes
born_in_chaos
Butchersdelight
domesticationinnovation
ToughAsNails

**Comment by hof1102** [comment]
I wonder if there are any updates and fixes in v25 for this problem, and also I didn't see any serverpacks of v25 on curseforge page.

**Comment by SHXRKIEgg** [comment]
update to v25

**Comment by hof1102** [comment]
> update to v25

I dont see any serverpacks of v25, which means only clients need to update, and server only need to simply add these new mods？
