### ISSUE TITLE
 "Tooltip error, see logs." on JEI interface.

### ISSUE THREAD

**Issue by kawakitten** [LunaPixelStudios/Better-MC#1565]
### Describe the Bug

Every item on the JEI sidebar shows "Tooltip error, see logs." after updating and joining our server after new version.
Log may be accessed here: https://mclo.gs/NvM1hEd

### Screenshots and Videos

https://i.imgur.com/7R7kYMJ.png
https://i.imgur.com/CKEwbhd.png
 https://i.imgur.com/rCa1nnT.png

### Crash Report or Log

https://mclo.gs/NvM1hEd

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC 4 v25 HF

**Comment by BastardNeko** [comment]
I'm getting the same issue for BMC 4 v25 HF on 1.20.1

**Comment by Deltoush** [comment]
I also have the same problem on my BMC4 v25HF 1.20.1 server!
No crash, only this error.

**Comment by muon-rw** [comment]
Fixed in v25.5
