### ISSUE TITLE
"The game crashed whilst tesselating block in world" while using the Chipped tables

### ISSUE THREAD

**Issue by EnzoGaGu** [LunaPixelStudios/Better-MC#1566]
### Describe the Bug

When I use a table from the Chipped mod, I can't even grab an item from my inventory that would work with that table without the game crashing.

### Reproduction Steps

1. Craft and put a Chipped table somewhere on the world
2. Open that table's menu 
3. Try to use an object with it
4. The game crashes and gives the error I pasted here. 

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/96706572/df802b63-ec33-405c-b945-7da3bbd3ed8f)

### Crash Report or Log

https://pastebin.com/2dEKKaUa

### Operating System

Windows 10 

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC v25.5

### Other Mods

Nothing but the BSL shaders

**Comment by chorbintime** [comment]
remove Continuity or update to v26 when released

**Comment by EnzoGaGu** [comment]
> remove Continuity or update to v26 when released

Thanks! It worked. Amazing modpack, by the way!
