### ISSUE TITLE
BMC4 Dedicated Server Crash on start.

### ISSUE THREAD

**Issue by ZizzyZizzy** [LunaPixelStudios/Better-MC#1567]
### Describe the Bug

Using forge v1.20.1-47.2.20.
Using Java JDK on Linux version 18.0.2
Using BMC4 FORGE 1.20.1 Server Pack v26.zip from the Additional downloads.

Pastebins for latest.log and debug.log:
http://sprunge.us/SfWmU0
http://sprunge.us/AhBI0Z

### Reproduction Steps

1. Install forge v1.20.1
2. Download and extract BMC4 FORGE 1.20.1 Server Pack v26.zip
3. Run forge with Java18

### Screenshots and Videos

N/A

### Crash Report or Log
http://sprunge.us/SfWmU0
http://sprunge.us/AhBI0Z

### Operating System

Ubuntu 20

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 FORGE 1.20.1 Server Pack v26

### Other Mods

No additional mods.

**Comment by ZizzyZizzy** [comment]
I also tried Java 17, removing radium mod because it was throwing errors. Pulling my hair out for an hour trying to get this to work on a dedicated server.

**Comment by SHXRKIEgg** [comment]
"Using forge v1.20.1-47.2.20."
Our serverpack doesnt not come with 47.2.20 it has .17 so you arent not using our serverpack and using something else

**Comment by ZizzyZizzy** [comment]
Thanks. I didn't catch that minor version difference.

The start.sh supplied with the server pack did not work, so I manually installed the "starred", newer version from Forge downloads.

`The server installed successfully
You can delete this installer file now if you wish
Installation complete. forge-installer.jar deleted.

libraries/net/minecraft/server/1.20.1/server-1.20.1.jar present.

Mojang's EULA has not yet been accepted. In order to run a Minecraft server, you must accept Mojang's EULA.
Mojang's EULA is available to read at https://aka.ms/MinecraftEULA
If you agree to Mojang's EULA then type 'I agree'
Response: I agree
User agreed to Mojang's EULA.

Starting server...
Minecraft version: 1.20.1
Modloader:         Forge
Modloader version: 47.2.17

Java args:         -Xmx4G -Xms4G
Java path:         java
Run Command:       java -Dlog4j2.formatMsgNoLookups=true @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.20.1-47.2.17/unix_args.txt nogui
Java version:
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

Error: Could not find or load main class @user_jvm_args.txt

Exiting...

ls
BMC4_FORGE_1.20.1_Server_Pack_v26.zip
config
defaultconfigs
eula.txt
libraries
modernfix
mods
READ_ME.txt
server-icon.png
server.properties
start.ps1
start.sh
user_jvm_args.txt
variables.txt


`
