### ISSUE TITLE
Missing xp bar

### ISSUE THREAD

**Issue by Waspinatorr** [LunaPixelStudios/Better-MC#1569]
### Describe the Bug

XP bar has visually disappeared from GUI while remaining completely functional

### Reproduction Steps

Repeatedly using a waystone caused the disappearance.
Was well above the level required to travel, I am not able to reproduce on another world

### Screenshots and Videos

![2024-02-13_20 50 56](https://github.com/LunaPixelStudios/Better-MC/assets/159973606/d3f8a409-4d54-4b6a-9646-71fe45c40fea)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v20

### Other Mods

Explorer's Compass

**Comment by chorbintime** [comment]
report it to the waystones devs
