### ISSUE TITLE
my minecraft screen glides like when u zoom in

### ISSUE THREAD

**Issue by deadbysmiley** [LunaPixelStudios/Better-MC#1570]
### Describe the Bug

when i just pressen c so the standard zoom button i couldnt go out anymore even leaving the wolrld and joining again or creatinf a new world 

### Reproduction Steps

1.just pressed c
2.
3.
...

### Screenshots and Videos

[2024-02-14 16-16-45.zip](https://github.com/LunaPixelStudios/Better-MC/files/14281539/2024-02-14.16-16-45.zip)

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

47.2.17

### Other Mods

essential cuz im fr broke rn for an real server to play with my friends pleas help me

**Comment by chorbintime** [comment]
Essential does not work. It will corrupt your world. If you want a free server, the modpack already comes with a mod by default that lets you host one. Just go into a singleplayer world and press escape, the button is there.
