### ISSUE TITLE
Paint Kit not working correctly

### ISSUE THREAD

**Issue by zPalo02** [LunaPixelStudios/Better-MC#1571]
### Describe the Bug

At first seems all fine, when I shift right click a block I get it, but then i right click on the paintable block and it always gives me stone.
Im using toms_storage_fabric-1.20-1.6.5.jar
Modloader Fabric - 0.15.3

### Reproduction Steps

1.Shift+right click on the desired block
2. right click on the paintable block
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/64591827/2c1679bf-7522-44fd-b6cd-32097284b1ce)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

1.20.1

### Other Mods

Fantasy MC modpack

**Comment by chorbintime** [comment]
report it to the devs of the mod that adds the paint kit
