### ISSUE TITLE
Missing textures with Biomes O Plenty rainbow birch tree

### ISSUE THREAD

**Issue by jgg123** [LunaPixelStudios/Better-MC#1572]
### Describe the Bug

I just updated to V26 and the rainbow birch tree has missing textures, and is not working correctly, i tried to change a few settings but nothing is working. I tried graphic settings and shader settings. In version 25.5 of the modpack it was just red with no missing textures, now i updated today and now has missing textures.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image_2024-02-14_130328053](https://github.com/LunaPixelStudios/Better-MC/assets/11604502/da640e80-7dc4-4a3d-a399-162846a63b11)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

V26

**Comment by chorbintime** [comment]
report it to the Biomes O Plenty developers

**Comment by MrTiano** [comment]
Same mistake with me, it's ridiculous that they say "contact the mod developers" when the chances of them responding are basically zero.

hope somebody help us on how to fix this one.

**Comment by chorbintime** [comment]
i dont know what you expect us to do when this is an issue with the mod itself lol
