### ISSUE TITLE
crafting rezeptbook didn't exist

### ISSUE THREAD

**Issue by USBTOASTER19** [LunaPixelStudios/Better-MC#1574]
### Describe the Bug

it is not there, i want to cook some more stuff but it's a little anoying without a rezeptbook

### Reproduction Steps

1.click rightclick on mouse on the Craftingtable btw.
2.click rightclick on mouse on the Craftingtable btw.
3.click rightclick on mouse on the Craftingtable btw.
...

### Screenshots and Videos

![Bild_2024-02-17_142046101](https://github.com/LunaPixelStudios/Better-MC/assets/160328599/d758e643-cd42-4f96-9ec3-9ace1bb8bf46)

### Crash Report or Log

there is no crash report

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

1.20.1

**Comment by USBTOASTER19** [comment]
please help quickly i want to play normal with an crafting book or whaterver the name is

**Comment by chorbintime** [comment]
you did not install the modpack correctly. reinstall on ATLauncher
