### ISSUE TITLE
Sugarcane isn't growing

### ISSUE THREAD

**Issue by Orgranuim** [LunaPixelStudios/Better-MC#1576]
### Describe the Bug

Sugarcane will trigger an observer, so it's trying to grow, but it does not grow. It's placed on both Mud and dirt with water next to the mud/dirt.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

### Other Mods

no additional mods installed

**Comment by chorbintime** [comment]
send a screensht of the farm
