### ISSUE TITLE
Game completely freezes when using a crafting table

### ISSUE THREAD

**Issue by MsBaru** [LunaPixelStudios/Better-MC#1577]
### Describe the Bug

Game completely freezes when using a crafting table. When you open it, even moving your cursor causes it to freeze for a good while and then unfreeze, but as soon as you move again, it repeats. My computer is powerful enough, hardware is not the problem. I have tried to allocate less ram, more ram, but nothing worked. Crafting in inventory works nicely tho.

### Reproduction Steps

1. open crafting table
2. move cursor
3. freeze
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc 2 v24

### Other Mods

none

**Comment by chorbintime** [comment]
Please run a spark profiler ingame by running /sparkc profiler start

Then, after 30-ish seconds of recreating the laggy behavior, run the stop command, and send the link here.

**Comment by slashingg** [comment]
> Please run a spark profiler ingame by running /sparkc profiler start
> 
> Then, after 30-ish seconds of recreating the laggy behavior, run the stop command, and send the link here.
I'm having the same exact problem, so here's my Sparkc 

https://spark.lucko.me/PgrHkKySfh
https://spark.lucko.me/PgrHkKySfh

**Comment by chorbintime** [comment]
pretty much just the REI mod causing the lag. you can go in the REI mod config and reduce the column count
