### ISSUE TITLE
My Launcher Keeps Crashing Loading UP Better MC

### ISSUE THREAD

**Issue by Silvalliox** [LunaPixelStudios/Better-MC#1578]
### Describe the Bug

Everytime I try loading up my Better MC Launcher it just crashes i've been playing perfectly fine for weeks now at this point but after I logged off and got back on today it just won't load up.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://paste.atlauncher.com/view/7d27c390-8424-4c62-a026-0168c9ddfbe5

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

1.20.1

### Other Mods

Butchers Delight Mod

**Comment by Astonimos** [comment]
same

**Comment by chorbintime** [comment]
Do a fresh reinstall on ATLauncher and transfer over your saves folder
