### ISSUE TITLE
Minecraft game won't open when i launch it from ATlauncher

### ISSUE THREAD

**Issue by N0tV1per** [LunaPixelStudios/Better-MC#1579]
### Describe the Bug

I tried adding essential mod to Better MC Forge 1.20.1 but when I launch the mod from ATlaucher it wont work. Same thing happend with me trying to install Mustard Virus by Forge Labs to play zombies and I also added essential mod to it and when I tried to launch it. It didn't work. But it worked once and that was both of them without the essential mod. So I tried to launch it again without essential mod again, only to find out it doesnt launch now. Can someone please help me asap? Thanks.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

1.20.2

**Comment by chorbintime** [comment]
The Essential mod is incompatible and is known to cause world corruption.
