### ISSUE TITLE
Game instantly crashes when loading BMC4 v26

### ISSUE THREAD

**Issue by Dragster-10** [LunaPixelStudios/Better-MC#1580]
### Describe the Bug

Game will not load and crashes after pressing 'Play' on the MC launcher opened via CurseForge
![image](https://github.com/LunaPixelStudios/Better-MC/assets/161269153/ffd74b54-4469-4166-a4f7-fa9f0a3fba56)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/161269153/e19b42b3-8d60-4007-98ca-4f223626f3bc)

### Reproduction Steps

1.Open CurseForge on Overwolf
2.Download BMC4 from the 'Browse' Section
3.Launch BMC4
4.Click 'Play' in the launcher
5.Wait for this
![image](https://github.com/LunaPixelStudios/Better-MC/assets/161269153/0f0ed4a4-c3c5-4aa5-88c7-91062ce15ef1)
6.Game will crash with an exit code of 1.

### Screenshots and Videos

Screenshots listed above.

### Crash Report or Log

Copied exit code, it's just 1.

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V26

### Other Mods

No.

**Comment by APinchofDill** [comment]
Have the same issue

**Comment by APinchofDill** [comment]
@Dragster-10 

I fixed this issue with Forge 47.2.6

https://adfoc.us/serve/sitelinks/?id=271228&url=https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.2.6/forge-1.20.1-47.2.6-installer.jar

**Comment by chorbintime** [comment]
cant help without logs
