### ISSUE TITLE
GUI offset

### ISSUE THREAD

**Issue by SpencerReitz** [LunaPixelStudios/Better-MC#1581]
### Describe the Bug

Any UI (inventory, pause menu, etc.) is moved 10-ish pixels from the actual places the items exist, making it difficult to use your inventory when an Elytra is equipped

### Reproduction Steps

UPDATE: SEEMS TO ONLY HAPPEN WITH ELYTRA

### Screenshots and Videos

![2024-02-26_13 58 52](https://github.com/LunaPixelStudios/Better-MC/assets/90951185/57f2360c-b6dc-43f6-b851-0c4caf5e8905)
![2024-02-26_13 59 02](https://github.com/LunaPixelStudios/Better-MC/assets/90951185/9176f307-6586-4155-9003-3743921f1424)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
try removing the blur mod, if presentt

**Comment by rayzuhl** [comment]
This also happens in v26 of the 1.20.1 Forge modpack

**Comment by DaveTheRadish** [comment]
Did you find a fix?

**Comment by lowis7277** [comment]
im having the exact same issue but im playing with a custom modpack. Has anyone find a solution?

**Comment by chorbintime** [comment]
Fixed in v27.5

**Comment by chorbintime** [comment]
> im having the exact same issue but im playing with a custom modpack. Has anyone find a solution?

Disable the elytra indicator in the quark config
