### ISSUE TITLE
Better MC [Fabric] 1.20.1 v24 Crashing on World Load

### ISSUE THREAD

**Issue by snekbaby** [LunaPixelStudios/Better-MC#1582]
### Describe the Bug

When trying to load or create a new world in the modpack, the game will crash on the world loading screen. If you create a new world, the game will register that you've created a new world and make a "save file", but it still crashes upon trying to open the world. 

The error code it gives is 6! I am on a Mac OS if that changes anything!

### Reproduction Steps

1. Start BetterMC modpack/Minecraft
2. Select world save and/or create new world 
3. Wait for Minecraft to crash on the next screen
...
*The screenshot below is the screen where the crash always happens

### Screenshots and Videos

<img width="1440" alt="Screenshot 2024-02-26 at 5 25 00 PM" src="https://github.com/LunaPixelStudios/Better-MC/assets/151260315/64cf32bc-6854-46f2-aed7-4ff2e03d60ae">

### Operating System

Mac OS Sonoma 14.2.1

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2

### Other Mods

No mods added to the pack! :) Just wanted to say thank you to the mod team!!

**Comment by chorbintime** [comment]
we cant help if you dont provide logs. please look in the logs folder in your modpack files and send the one named "latest"
