### ISSUE TITLE
Better MC [Fabric] 1.20.1 v24 Crashing on World Load

### ISSUE THREAD

**Issue by snekbaby** [LunaPixelStudios/Better-MC#1583]
### Describe the Bug

When trying to load or create a new world in the modpack, the game will crash on the world loading screen. If you create a new world, the game will register that you've created a new world and make a "save file", but it still crashes upon trying to open the world.

The error code it gives is 6! I am on a Mac OS if that changes anything! Included the logs this time--thank you for explaining where they were!! 

### Reproduction Steps

1. Start BetterMC modpack/Minecraft
2. Select world save and/or create new world
3. Wait for Minecraft to crash on the next screen

### Crash Report or Log

https://gist.github.com/snekbaby/8325249bb69d8071a016f029ad62c436

### Operating System

Mac OS Sonoma 14.2.1

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2

### Other Mods

N/A :) Thanks in advance for your help! Hoping it's not just something I didn't download 🤦‍♀️

**Comment by chorbintime** [comment]
Check the modpack files for a file named hs_err_pid, and send it here.

**Comment by Canertsz** [comment]
having the same issue. @chorbintime
[hs_err_pid38457.log](https://github.com/LunaPixelStudios/Better-MC/files/14528762/hs_err_pid38457.log)
[hs_err_pid38652.log](https://github.com/LunaPixelStudios/Better-MC/files/14528764/hs_err_pid38652.log)

**Comment by snekbaby** [comment]
Here is one of mine as well if it is useful/needed! (also thank you Canertsz for uploading as well!!) 

[hs_err_pid10515.log](https://github.com/LunaPixelStudios/Better-MC/files/14532240/hs_err_pid10515.log)

**Comment by KingBobbyB** [comment]
yeah im having the same probelm has anyone figured out the reason yet

**Comment by Canertsz** [comment]
### **For Mac devices using Apple Silicon/arm (M1/M2/etc.) CPUs**
There is an issue with Java 17.0.8 and newer where you may experience "A fatal error has been detected by the Java Runtime Environment", which can cause the Java runtime to crash under a variety of circumstances. To resolve this:

1. Install the Zulu JDK 17.0.1+12 arm64 build of Java:
Direct download: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=7eb8ee44-ab7f-4afb-9e42-32bd76416400
 
2. Download/Install ATLauncher or Prism Launcher (CurseForge Launcher is known to cause issues)

3. In Instance settings > Java, manually specify the following Java path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

<img width="1333" alt="Screenshot_2024-03-08_at_02 32 11" src="https://github.com/LunaPixelStudios/Better-MC/assets/64376593/8302c3d1-1f77-43d3-8c37-9234beb36b65">


5. If using ATLauncher, Disable "Use Minecraft-bundled JDK" (I couldn't find that setting, but the game is still working fine anyway.)

6. Launch the game

I followed these instructions from the Luna Pixel Studios discord, and it worked perfectly fine for me!
@snekbaby @KingBobbyB
