### ISSUE TITLE
Dragon Mounts Legacy

### ISSUE THREAD

**Issue by Nakins005** [LunaPixelStudios/Better-MC#1585]
### Describe the Bug

There is only the aether dragon and you can no longer hatch the eggs

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V26

**Comment by chorbintime** [comment]
check the dragon mounts config in the serverconfig folder
