### ISSUE TITLE
RightClickHarvest has a  conflict with Quark

### ISSUE THREAD

**Issue by izumiChan16** [LunaPixelStudios/Better-MC#1586]
### Describe the Bug

RightClickHarvest has a  conflict with Quark. Quark has a same function named Simple Harvest.

### Reproduction Steps

On BMC4 v26, Use a hoe to hoe the ground, leaving only the seeds of the block pointed by the pointer.
but it's narmal when we use hand right click。

solution:
set `Simple Harvest = false`, `Hoe Harvesting = false`, at `config/quark-common.toml`
**or**
delete `RightClickHarvest` mod (not recommened)

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/24999984/92249a32-9ddf-451e-8476-a937288b19f9)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/24999984/cbf33b60-3f88-4251-94ec-7e913f36aea7)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/24999984/845f7543-7599-4a38-b93d-9b93d8e437a2)

### Operating System

ArchLinux server

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
fixed in https://github.com/LunaPixelStudios/Better-MC/commit/8492e6e852a6d90fa981a376d0077039b271e45c

in the future you are free to PR config changes but i suppose it doesnt matter much as it'll get fixed either way

thank you for the report - the issue will not be present in v27
