### ISSUE TITLE
Elytra installation causes UI misalignment

### ISSUE THREAD

**Issue by izumiChan16** [LunaPixelStudios/Better-MC#1587]
### Describe the Bug

When the elytra is installed in the slot on the back, everything is normal, but when it is installed in the chest armor slot, the UI is misaligned.

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/24999984/f67c476d-41ae-424b-a33b-13ceed970d69

### Operating System

Windows11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
Does it persist with the Elytra Slot mod removed? I'll look into this for the next update - let me know if you find anything

**Comment by cookietea06** [comment]
same here

**Comment by Kungpung** [comment]
me too and my other friend is too
