### ISSUE TITLE
Crashes immediately upon startup

### ISSUE THREAD

**Issue by Saiko-log** [LunaPixelStudios/Better-MC#1588]
### Describe the Bug

Minecraft crashes immediately upon startup with error 1, and from the logs I absolutely don’t understand what the problem is, I’ve already tried reinstalling the assembly but it doesn’t help

### Crash Report or Log

https://pastebin.com/fSKP7T6s

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.20.1 v26

**Comment by Phoenix55537** [comment]
i got rid of all aether related mods and it started working

**Comment by muon-rw** [comment]
We can not provide support for cracked launchers.
