### ISSUE TITLE
Diagonal Fences mod conflicts with Snow! Real Magic! ⛄ mod

### ISSUE THREAD

**Issue by izumiChan16** [LunaPixelStudios/Better-MC#1589]
### Describe the Bug

The snow mod allows snow to fall under the fence, but this also disables the diagonal fence (which has cost me my hard-earned animals)

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/24999984/4e78b57e-ed8c-449c-ab6b-abf461c4e49c)

### Operating System

Window11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
report it to the snow real magic devs so they can add compatibility
