### ISSUE TITLE
veinmine

### ISSUE THREAD

**Issue by SarmanC1** [LunaPixelStudios/Better-MC#1591]
### Describe the Bug

veinmine not working on pickaxes? even when using the enchant and holding down the keybind?, please switch to FTB UltiMine?

### Reproduction Steps

1.play game
2. mine stone or ores
3.
...

### Operating System

Windoiws 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v24

**Comment by chorbintime** [comment]
the enchant works. you need it on your tool and need to keep the keybind held.
