### ISSUE TITLE
vein mining not working

### ISSUE THREAD

**Issue by MelihAslan63** [LunaPixelStudios/Better-MC#1592]
### Describe the Bug

I'm playing 1.20 forge better mc, I pressed the vein mining spell but it doesn't work.

### Reproduction Steps

1.vein mining 
2.not 
3.working
...

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

**Comment by chorbintime** [comment]
the enchant works. you need it on your tool and need to keep the keybind held.

**Comment by AdamWayne-dev** [comment]
For anyone looking for why this happens - hold the tilde key (button to the left of "1" on an English keyboard) whilst mining.
