### ISSUE TITLE
Better End crashes

### ISSUE THREAD

**Issue by HukakHePak** [LunaPixelStudios/Better-MC#1594]
### Describe the Bug

Hi guys. When I'm in better_end:crystal_mountains, the game crashes after a few minutes.
Judging by the logs, Better End cannot find the Sound file. 
Turning off the sound does not help.

I downloaded modpack via TLauncher (https://tlauncher.org/)

### Reproduction Steps

1. Start game
2. Load local world
3. Teleport to The End
4. Find Crystal Mountains biome
5. Afk few minutes

### Screenshots and Videos

![4e5ad2e6-9c4a-46a8-874b-bbc1a68f8942](https://github.com/LunaPixelStudios/Better-MC/assets/91820343/be8a5676-d4f5-4f9d-929d-052e74e2275b)

### Crash Report or Log

https://gist.github.com/HukakHePak/fd91c05cec154e67cff4eb4ba93eb94c

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v26

**Comment by chorbintime** [comment]
TLauncher is spyware and does not install modpacks correctly.
