### ISSUE TITLE
Shaders problems

### ISSUE THREAD

**Issue by LVEL5** [LunaPixelStudios/Better-MC#1595]
### Describe the Bug

Game is crash when using shader after load world.

**Shader that i try using**
- ComplementaryReimagined_r5.1.1 + EuphoriaPatches_1.2
- Sildurs Vibrant
- Complementary Reimagined r5.1.1
- Nostalgia_v5.0
- Pastel-Shaders-Universal-v1.100
- Sildur's Vibrant Shaders v1.51 Lite
- Sildur's Vibrant Shaders v1.51 Medium
- Voyager shader 2.0.7

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
Are you on MacOS?

**Comment by LVEL5** [comment]
Windows 10

**Comment by chorbintime** [comment]
have you updated your gpu drivers? and no, optifine will never be compatible and you should never use it

**Comment by LVEL5** [comment]
found the problem.. i use wrong gpu driver software.. i change the amd driver software and work fine.
