### ISSUE TITLE
Better MC [Fabric] 1.20.1 v24 crashing on start the minecraft server

### ISSUE THREAD

**Issue by xpcchx** [LunaPixelStudios/Better-MC#1596]
### Describe the Bug

I don't know what happened.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/kX3XkWK

### Operating System

win10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v24

**Comment by chorbintime** [comment]
How did you setup the server, step by step?
