### ISSUE TITLE
Incapable of moving

### ISSUE THREAD

**Issue by JohnAB9** [LunaPixelStudios/Better-MC#1598]
### Describe the Bug

I am unable to move or use cheats, but I am able to break blocks and look around and go into my inventory

### Reproduction Steps

1.Create a world
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

0.14.25

**Comment by chorbintime** [comment]
please be more specific

also, how did you install the modpack?
