### ISSUE TITLE
Backpack Craffting Bug.

### ISSUE THREAD

**Issue by xKamaxCWG** [LunaPixelStudios/Better-MC#1599]
### Describe the Bug

Unable to craft a backpack from Backpacked even tho having the materials.

### Screenshots and Videos

![Base Profile Screenshot 2024 03 16 - 05 12 55 52](https://github.com/LunaPixelStudios/Better-MC/assets/131653345/8750e879-9fb6-4635-ad9a-37956c3f698c)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.20.1 v24

**Comment by chorbintime** [comment]
please check the recipe directly through JEI - i dont think the tooltip is correct for whatever reason. if this persists then it may be due to the datapack we made to change the backpack recipe. you can try going into config -> paxi -> datapacks and deleting the one named 'backpacked recipe fix'
