### ISSUE TITLE
Recipe book not visible in the crafting table

### ISSUE THREAD

**Issue by ManosDaskos** [LunaPixelStudios/Better-MC#1600]
### Describe the Bug

The recipe book from minecraft does not show in the crafting table neither in my inventory it doesn't have a problem with furnaces or smokers 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v24

**Comment by chorbintime** [comment]
its disabled by REI, you can check the config to re-enable
