### ISSUE TITLE
BMC4 v26 crashed immediately when it start up

### ISSUE THREAD

**Issue by SkyrimBlacksmith** [LunaPixelStudios/Better-MC#1601]
### Describe the Bug

I downloaded the pack from curseforge. And the modpack crashed when I start it up and left me an error code 1. There's log below.

### Reproduction Steps

1.Launch game
2.Do nothing
3.The game crash
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/31271842/c4381981-0dc2-48b2-88d7-a643f8b77fea)

### Crash Report or Log

https://gist.github.com/SkyrimBlacksmith/5a2bfffa481688756c10336ed1c091ed

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v26

**Comment by chorbintime** [comment]
reinstall using ATLauncher
