### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by 21xno** [LunaPixelStudios/Better-MC#1602]
### Describe the Bug

My inventory is tilted to right on my world which makes me point at different slots other that I want to pick.
![image](https://github.com/LunaPixelStudios/Better-MC/assets/164055947/6eb2a7a6-6fd9-4ff9-9383-b32ef4ad2e00)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/164055947/b468667b-50cd-4ce4-b2da-e72be189a2f1)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/164055947/c725656e-a8e0-49ee-92cb-967f06242e46)
(pointing at ender chest)

### Operating System

Windows 10 

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v26

**Comment by Kungpung** [comment]
How do you solve this i get the same when i equip elytra
