### ISSUE TITLE
Crash Report 1

### ISSUE THREAD

**Issue by lamesoupp** [LunaPixelStudios/Better-MC#1603]
### Describe the Bug

I was able to play this game yesterday fine, now all of a sudden it won't open today. I looked at the crash report and it says a few mods have an error but I when I tried installing maybe the more updated versions it still didn't work. Not sure what the problem is seeing as it was just fine yesterday.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

1.20.1

**Comment by chorbintime** [comment]
i cant help if you dont provide the crash report

**Comment by lamesoupp** [comment]
> i cant help if you dont provide the crash report

My bad I don't know anything about this website. I could have given it to you, you didn't need to close my comment.
