### ISSUE TITLE
Can't open game

### ISSUE THREAD

**Issue by AmberAxolotl223** [LunaPixelStudios/Better-MC#1604]
### Describe the Bug

Game will crash before even opening the main game
![Screenshot (3079)](https://github.com/LunaPixelStudios/Better-MC/assets/164436246/db87d4c8-e791-4088-872a-49c260ef6ab4)

### Reproduction Steps

1. Go onto forge
2. Click on Play for BMC4 
3. Click play on Launcher
4. Wait for it to load
5. Crash

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC v26

### Other Mods

None

**Comment by chorbintime** [comment]
Reinstall on ATLauncher and update your drivers
