### ISSUE TITLE
Elytra Resolution Bug

### ISSUE THREAD

**Issue by Kungpung** [LunaPixelStudios/Better-MC#1605]
### Describe the Bug

I just got the elytra in my survival world and as soon as i put it on the resolution changed and my mouse is inaccurate 1cm to the right

### Reproduction Steps

1. Put elytra on 
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
https://github.com/LunaPixelStudios/Better-MC/issues/1587#issuecomment-1989502275

Can you try this, please?
