### ISSUE TITLE
Elytra UI Bug

### ISSUE THREAD

**Issue by Kungpung** [LunaPixelStudios/Better-MC#1606]
### Describe the Bug

https://github.com/LunaPixelStudios/Better-MC/assets/164538132/c1102f2a-a36d-499b-ab60-6efe3cb1cb3d

### Reproduction Steps

1. put on elytra
2. UI Bugs
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by cookietea06** [comment]
so it's not really a fix but if you use an elytra template and aeternium ingot on your elytra it becomes an armour piece and you can wear it on your chest without the ui bug. Good stats as well with enchantments:)
