### ISSUE TITLE
BMC2 Fabric v24 - Multiple Versions of ModMenu

### ISSUE THREAD

**Issue by Ancendae** [LunaPixelStudios/Better-MC#1607]
### Describe the Bug

Two Versions of ModMenu present in BMC2 Fabric v24
v7.2.2 (for Minecraft 1.20.1)
v2.0.17 (for Minecraft 1.17)

### Reproduction Steps

Exact Files:
1. Download Instance of BMC2 Fabric from Curseforge Website 
2. Extract Files
3. Open manifest.json
4. Mod Menu ("projectID": 308702) has "fileID": 4145216, which matches with v2.0.17
5. Open folder overrides
6. Note modmenu-7.2.2

Via Curseforge Launcher:
1. Download Modpack via Curseforge Launcher
2. Open the Profile
3. Select Open Folder in the settings section
4. Open Mods Folder
5. Note two files for modmenu

Via Modrinth Launcher:
1. Download Modpack via Modrinth Launcher
2. Open the Profile
3. Search ModMenu
4. Note two instances of ModMenu

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc v24

**Comment by chorbintime** [comment]
yeah, been aware of this for a while, its just bc modmenu's latest versions were modrinth-only for a while so it was installed from modrinth as a 3rd party file, but then some mods had the old CF version of the mod set as a dependency. 

fabric only loads the latest version of mods so its fine. going to fix it this update though, thank you for the detailed report
