### ISSUE TITLE
sinking into the world

### ISSUE THREAD

**Issue by iovesejin** [LunaPixelStudios/Better-MC#1609]
### Describe the Bug

This issue has occurred quite a lot recently. I have yet to see if this issue occurs in single player, but I have been experiencing this on multiplayer servers. When joining into my world it would sink me down to -1356 or lower honestly (that should not be possible.) With this sinking, it would also fix me into one place, glitching me back into position when I attempt to move around. There are further issues however, i'm not really confident to say whether it's a mod issue or external factors causing this. 

### Reproduction Steps

1. Launching the game, loading bar glitches into the main menu
2. Server takes a while to load in
3. Enter with black screen, nothing in item bar and sinks down to -1000+ into the map
4. glitches back to previous log out spot and will lock you into place, not allowing you to move around
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/164770263/2cb2ee5c-9964-493c-ab42-cd441f42ac42)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/164770263/f7238267-9742-49cc-92f6-8ade9c15ba75)
https://github.com/LunaPixelStudios/Better-MC/assets/164770263/4ded2c23-373b-4639-a529-dc54b71b00e8

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2

### Other Mods

-

**Comment by chorbintime** [comment]
try updating the Connectivity mod
