### ISSUE TITLE
Chunks And Falling

### ISSUE THREAD

**Issue by GBRFinesse** [LunaPixelStudios/Better-MC#1610]
### Describe the Bug

When loading in to a single player world or a server, the chunks past the first one will not load. The world loads the spawn area and when you try to venture out you're hit with an invisible wall because the chunks are not loading. I've tried reloading chunks and shaders and even updated Xenon. When you try to force it to load you just end up falling into the void until the server kicks you.

### Reproduction Steps

1.Load Minecraft 
2.Join server
3.Try to load chunk that's not loaded
4. Fall into the void

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v26

**Comment by chorbintime** [comment]
How did you install the modpack? 

Are you playing on a server?

**Comment by GBRFinesse** [comment]
Installed through CurseForge and yes I am playing on a server that has 9GB.

**Comment by chorbintime** [comment]
How is the server hosted, and what is your ping to the server?

Also, please follow the performance guide https://rpg.prominence.wiki/performance-guide
