### ISSUE TITLE
Items and blocks disappearing

### ISSUE THREAD

**Issue by emmachlo444** [LunaPixelStudios/Better-MC#1611]
### Describe the Bug

If the game crashes or failed to load all items in the inventory, hot bar and armour are deleted as well as so many blocks being deleted that had just been placed. EG if the game crashes while building the blocks placed before it crashed are gone.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC V26

**Comment by chorbintime** [comment]
please provide a crash report file
