### ISSUE TITLE
The ui is like offset

### ISSUE THREAD

**Issue by s7yna** [LunaPixelStudios/Better-MC#1612]
### Describe the Bug

I was looting and then all the sudden the ui was like offset when when i try and click stuff with my cursor it chooses the next black closest in my hot bar

https://github.com/LunaPixelStudios/Better-MC/assets/165234393/7bd006bc-a88a-4f43-aa74-2bcc92979ed5

### Reproduction Steps

1. im not sure how it happened 
2.
3.
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/165234393/c81ca8f7-ffa9-42ea-8c41-b3455442d23c

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.20.1 v26.zip

**Comment by chorbintime** [comment]
will look into it for the next update - still not too sure what the cause is
