### ISSUE TITLE
I can't access the game, at all.

### ISSUE THREAD

**Issue by lamesoupp** [LunaPixelStudios/Better-MC#1613]
### Describe the Bug

I can't even load into the game. Anytime I try I notice the "Heap" will load to like 600 and the all of sudden its back down to 300. That part never fully loads at all. I don't know if that has anything to do with it but I thought I'd mention it anyways. I thought maybe it was my RAM so i bought more but that didn't fix it. I don't know if I did the paste bin right, if I didn't can someone help me instead of just commenting and closing my comment. I was able to play it only one day and I wanna be able to play it again, I really just need some help. Please and thank you.

### Reproduction Steps

1. Load in curse forge
2. Click play on Better Minecraft
3. Wait for it to load
4. Notice my "Heap" just goes up and then down then back and forth
5. Sends crash report
...

### Screenshots and Videos

![FORGE](https://github.com/LunaPixelStudios/Better-MC/assets/164110947/cfe97bbf-9ecb-4cad-8fbd-f171fe7abab8)

### Crash Report or Log

https://pastebin.com/z7Gw2P3v

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

1.20.1

**Comment by chorbintime** [comment]
Reinstall on ATLauncher and follow the performance guide https://rpg.prominence.wiki/performance-guide. If issue persists then check for a file named hs_err_pid
