### ISSUE TITLE
Straw Golem not available

### ISSUE THREAD

**Issue by SurefirePack** [LunaPixelStudios/Better-MC#1614]
### Describe the Bug

When i go to make hte straw golem nothing happens, and nothing is available to spawn the straw golem either, it doesnt seem to exist.

### Reproduction Steps

1. place carved or normal pumpkin on hay bale
2. nothing happens
3.
...

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v24

**Comment by pannicola** [comment]
Same here, on latest version of the modpack. There's no straw golem mod in the mod list. I decided to place it in the modpack myself and it's not available for this mc version. Until it comes out, the quest should be replaced.

**Comment by chorbintime** [comment]
will be fixed in next update, thank you for the report
