### ISSUE TITLE
End Cities Not Spawning

### ISSUE THREAD

**Issue by DScarySquid** [LunaPixelStudios/Better-MC#1615]
### Describe the Bug

I have traveled more then 50,000 blocks and have found only broken ships and little cubby's. I don't know if this is just a rare occurrence or not but I should be able to find one right?

I have started this world through aternos to play with friends, don't know if that changes anything

### Reproduction Steps

1. Have more end cities
2. Make them easier to find
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/165550537/6df91811-22b6-4163-9e89-9b4119056d57)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc 2 v24

**Comment by chorbintime** [comment]
Aternos is unsupported as it is prone to many issues and is overall not a very good host.

You can regenerate your end dimension file if you'd like, it may fix the issue.
