### ISSUE TITLE
Ui shifts only on the server

### ISSUE THREAD

**Issue by hy-pnotic** [LunaPixelStudios/Better-MC#1616]
### Describe the Bug

we where playing on the server i made with the server kit on forge and after 2-3 days the ui of the game sifts to the right  if i go into a solo world it dose not happen and if i reset the world folder in the server it dosent happen and everyone on the server is affected by it 
also we are 5 on the server i can provide the server files if needed 
i've seen two other person with that glitch on reddit and tried to backup then remove the playerdata and it fixed the issue seems like the issue is in the player data from what i've seen

### Reproduction Steps

1.play the game 
2.happend to me after we placed a shulker down
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/157171636/2416dac6-408c-440d-ab00-7765f4ee458d)

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4_FORGE_1.20.1_Server_Pack_v26

### Other Mods

i have added NBT edit and world edit (the bug still happens with them removed) and fastbackups (did not try to remove)

**Comment by hy-pnotic** [comment]
i tested a bit and noticed it only happens with 2 players (both players that went  to get the elytra)

**Comment by hy-pnotic** [comment]
the glitch is caused by the elytra if i remove it everything is fixed

**Comment by hy-pnotic** [comment]
sorry for putting many comments but i noticed it only happens to me when the elytra is in the torso emplacement not in the back emplacement

**Comment by chorbintime** [comment]
will look into it for the next update
