### ISSUE TITLE
Game keeps freezing after a few minutes

### ISSUE THREAD

**Issue by jrf1103** [LunaPixelStudios/Better-MC#1617]
### Describe the Bug

I'll walk around, start swimming, or try flying with my elytra, and after about 2-4 minutes, the game will completely freeze

### Reproduction Steps

1. Open the world
2. Walk around (or swim or fly with elytra) for about 2-4
3. Game freezes

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

Better MC [Fabric] 1.20.1 v24 

### Other Mods

trash-it- 1.0.1+1.20.1

**Comment by chorbintime** [comment]
Follow the performance guide https://rpg.prominence.wiki/performance-guide
