### ISSUE TITLE
Better MC [Forge] BMC4- Ice won't melt.

### ISSUE THREAD

**Issue by baileyacoates** [LunaPixelStudios/Better-MC#1618]
### Describe the Bug

After winter a bunch of lakes and rivers got frozen over near my house (which is near my spawn). Despite it being summer now the ice is still there. This is a server that I play on with my friends. 

### Reproduction Steps

1. Play Better MC Forge BMC4.
2. Wait until winter when it snows and water freezes to ice.
3. Wait until summer and the ice is still there with no sign of melting whatsoever. 
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC 4

### Other Mods

NIL

**Comment by chorbintime** [comment]
What modpack version are you playing? (v11, v20, etc)

**Comment by orosmatthew** [comment]
I also have this issue and I am on BMC4-v26 Forge

**Comment by baileyacoates** [comment]
BMC4 - v26 
Forge version is 47.2.17

**Comment by chorbintime** [comment]
If keeping the problematic chunk(s) loaded for a long time doesn't melt the ice, then you can try updating the Serene Seasons mod. If no update is available, or the update doesn't fix it, please report it to the Serene Seasons developers.
