### ISSUE TITLE
Cannot place other objects on fences, ex. Torches, Lanterns, Other fences

### ISSUE THREAD

**Issue by setralime** [LunaPixelStudios/Better-MC#1621]
### Describe the Bug

When attempting to place torches or lanterns or other things on fences it just wont work. I am a builder, so this function (if not a bug) can get a bit frustrating.
I've been able to place lanterns by bypassing, and using blocks next to the fence in order to place it, but the same does not work for torches.
I am unsure if this is a genuine bug, or if it's just a mod causing this issue. Either way I would like to know the proper fix if anyone is able to figure out the reason why. And if I find the reason, I will make an edit.

The Better MC Version I am using is Forge, v26, 1.20.1

### Reproduction Steps

1. Place fence
2. Try placing a torch, lantern, or other object on top of the fence
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC v26

**Comment by chorbintime** [comment]
Try updating the Diagonal Fences mod

**Comment by setralime** [comment]
@chorbintime Updating the mod did not fix the issue unfortunately.

**Comment by chorbintime** [comment]
Will look into it for next update - should be fixed by then. Let me know if you find anything
