### ISSUE TITLE
Incompatible FML 

### ISSUE THREAD

**Issue by POPOZAME** [LunaPixelStudios/Better-MC#1623]
### Describe the Bug

i started a modded server and did as many tutorial said but it still indicate a missmatch on the mod installed 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image_2024-04-06_124605887](https://github.com/LunaPixelStudios/Better-MC/assets/166217987/aba30692-04f7-4cf4-b998-fe249913b3df)

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
You didn't install the modpack correctly. Please read the readme file in the serverpack for how to install serverside, and use ATLauncher to install clientside
