### ISSUE TITLE
Better Minecraft Crash exit code 1

### ISSUE THREAD

**Issue by charleyyyxo** [LunaPixelStudios/Better-MC#1624]
### Describe the Bug

Hi, I've been using Curseforge for a while now and recently I've been unable to play Better Minecraft (Forge), and I could just be being stupid, but I recently downloaded and played it on my partners PC with no difficulty so I'm unsure on why it does not work for me. When i load up the launcher it launches the game and then comes up with the crash and exit code 1. I've deleted and redownloaded multiple times so I don't know what else to do/look for that may be causing the problem?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

### Other Mods

have not added or deleted any mods

**Comment by chorbintime** [comment]
Please send your latest.log file or the newest crash report file in the crash reports folder
