### ISSUE TITLE
UI shifts a little to the right when elytra is equipped

### ISSUE THREAD

**Issue by llamalauncher** [LunaPixelStudios/Better-MC#1625]
### Describe the Bug

When in survival mode, equipping an elytra will shift the entire UI (excluding the hotbar and FPS display) a bit to the right, i have tested 2 screens and 2 different worlds the bug happens on both, on creative it doesnt happen

also sorry for the low video quality, github would only let me upload 10MB of video

https://github.com/LunaPixelStudios/Better-MC/assets/46113785/e3d4d99a-b7fe-480c-9658-352001954cbd

### Reproduction Steps

1.get an elytra
2.go in survival
3.equip the elytra

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v26

### Other Mods

/

**Comment by chorbintime** [comment]
known issue - will look into it for next update

**Comment by Fuzss** [comment]
https://github.com/Fuzss/overflowingbars/issues/19
