### ISSUE TITLE
Game Lag

### ISSUE THREAD

**Issue by RealPyretic** [LunaPixelStudios/Better-MC#1626]
### Describe the Bug

The lag is from in the game, not sure how it works but i can move around but i cannot break blocks, kill mobs, get out of boats, and stop flying elytra when i hit the ground i just kind of stay prone and have to leave and come back to the world.

I think it has something to do with chunk loading as when i load new chunks it happens a lot, its kind of like if the game tick speed was set to 0 or a server TPS went to 0 and you can move around but cant do anything. sometimes it loads fully and goes away, other times i have to leave the world and come back for it to load properly 

### Reproduction Steps

1. Not completely sure but ive been messing with some of the performance options to try and fix it but nothing seems to work

### Crash Report or Log

No Crashes

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V26

### Other Mods

None

**Comment by chorbintime** [comment]
Follow the full performance guide https://rpg.prominence.wiki/performance-guide and send a screenshot with F3 open if issue persists
