### ISSUE TITLE
Server Won't Start

### ISSUE THREAD

**Issue by GodSize** [LunaPixelStudios/Better-MC#1629]
### Describe the Bug

I am attempting to run Better MC 4 forge on my dedicated minecraft server and everytime I attempt to start it, it displays the same thing in the logs and nothing else after that.  I would greatly appreciate some help on this issue. I will attach the latest.log.  For reference, I am running in under Crafty 4 installed on unRaid.  I have been in contact with Crafty 4 support, and it seems like everything is setup properly.

### Reproduction Steps

1. Install the BetterMC 4 Pack to a forge installation on Crafty 4
2. Start the server
3.
...

### Crash Report or Log

https://gist.github.com/GodSize/fe1bf0669d2a98cb94103d1021cc7ea9

### Operating System

unRaid

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC v26

**Comment by chorbintime** [comment]
Are you sure you have java 17/18 installed? Please check the readme in the server files for more info.

**Comment by GodSize** [comment]
Positive.  I am running a docker image that comes with several different java versions installed.  I have tried 17, as well as 21.  Same problem regardless.

**Comment by frakier** [comment]
same error, in both 17 and 21.

**Comment by frakier** [comment]
New info...
New to Crafty Controller got to wondering how it started the modpack and it used the forge jar file... switched it to start.sh as per readme once I figured out where to change it. Same error though, will dig more later.

**Comment by frakier** [comment]
disabled Neruina on the server and the client and it workes

**Comment by chorbintime** [comment]
I'll ask the Neruina developer about this - thank you for the report

**Comment by Fespinoza831** [comment]
had the same issue, removed the Neruina mod and the server started up.

**Comment by chorbintime** [comment]
It seems that either the server pack is using an incompatible forge modloader version, or you are updating the version yourself and that's what's causing it.

Either remove Neruina or try a different version of Forge. This will be fixed in the next modpack update.
