### ISSUE TITLE
Paradise Lost Takes to the Nether roof

### ISSUE THREAD

**Issue by LooihV** [LunaPixelStudios/Better-MC#1631]
### Describe the Bug

I was playing BMC1 V20 1.19.2 the fabric version... everything went well until we tried to go to the "paradise lost" dimension, it takes us to the nether roof, I tried in a singleplayer world, and it happened again. I started a new world, I installed the modpack with curseforge, I have an original mc copy and I'm using their original launcher. The server I'm hosting online is on exaroton, but since I tried it in a single player world I assume that it has nothing to do with the host. I tried asking in the Luna Pixel discord server, in Better Minecraft Fabric, they told me to update the paradise lost mod, but it has the lastest version available.
Some screenshots (single player world):
![image](https://github.com/LunaPixelStudios/Better-MC/assets/119136837/cf312477-351c-411d-9536-79c35bc1dab2)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/119136837/599060e2-122f-4446-bc9a-19dfa45d9a31)

### Reproduction Steps

1. Build the portal for paradise lost (5x4 frame just as the nether one but with glowstone, and a bucket of water)
2. Enter it, and spawn at the nether roof.

### Screenshots and Videos

https://youtu.be/SnXENwl0oUs

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 V20

### Other Mods

No

**Comment by chorbintime** [comment]
report it to the paradise lost mod developers
