### ISSUE TITLE
Server is not starting

### ISSUE THREAD

**Issue by Blunerz** [LunaPixelStudios/Better-MC#1632]
### Describe the Bug

The server is not starting

Warning! Running with administrator-privileges is not recommended.
Start script generated by ServerPackCreator 5.1.11.
To change the launch settings of this server, such as JVM args / flags, Minecraft version, modloader version etc., edit the variables.txt-file.
start.sh: line 40: source: variables.txt: file not found

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos
![image](https://github.com/LunaPixelStudios/Better-MC/assets/105878986/a47054db-3af3-4f14-b2cb-c8e5d172c99e)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/105878986/7afc197f-0bac-4dd5-987a-f5f9bf408b49)

_No response_

### Operating System

Linux

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
You appear to be running the server from inside a zip file. Please extract the zip file before running the server.
