### ISSUE TITLE
Cannot place lanterns on fences

### ISSUE THREAD

**Issue by alocalorange** [LunaPixelStudios/Better-MC#1633]
### Describe the Bug

You cannot directly place a lantern on a fence. I have only tried placing lanterns on oak fences. You must place a lantern adjacent to a full block then delete the block if you want the lantern to stand on the fence

### Reproduction Steps

1. Place down oak fence (unsure if the bug reproduces on other fences or not)
2. Attempt to place a lantern on top of it
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
known issue - will look into it for next update
