### ISSUE TITLE
falling through the floor

### ISSUE THREAD

**Issue by smb0934** [LunaPixelStudios/Better-MC#1634]
### Describe the Bug

I just fall through the map for ever no matter what I do. I change gamode or tp but nothing works 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better mv 1.20.1

**Comment by chorbintime** [comment]
What launcher did you use to install the modpack?

Are you on a server or a singleplayer world?

Are you on the latest version of the modpack?

Did you follow the performance guide linked on the main menu?

**Comment by smb0934** [comment]
1. It was a problem of the server not the actual mod, sorry.
If you want me to delete my github comment please send me the link because
I cant find it. Sorry for the waste of your time sir.
