### ISSUE TITLE
Golem farm issue

### ISSUE THREAD

**Issue by BimbustheWise** [LunaPixelStudios/Better-MC#1635]
### Describe the Bug

Ive noticed that the villagers will actually kill the zombie inside of its pen. using this exact same setup has no issues in vanilla so im wondering if theres a mod thats causing that or what. a little disappointing after all the work to set it up so im hoping theres a config option or something

### Reproduction Steps

1.build iron farm
2.observe zombie and villagers staring at eachother
3.zombie randomly dies within a minute or so
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v26

**Comment by chorbintime** [comment]
Can you be more specific on "villager kills zombie"? The only way a villager could kill something is if its a guard villager with a sword equipped.
