### ISSUE TITLE
Incorrect Quests

### ISSUE THREAD

**Issue by Thornbrier** [LunaPixelStudios/Better-MC#1636]
### Describe the Bug

Just got started and the quests are already incorrect.

### Reproduction Steps

1. Open Quest Book
2. Go to Tutorial > Important Controls
3. Z does not let you crawl, in fact, I don't see any control for letting you crawl.

2. Got to Tutorial > Inventory
3. Charm of Life does not go in the Necklace slot, and I don't even see what it does.

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc 4 v26

**Comment by chorbintime** [comment]
Thank you for the report - will be fixed in the next update.
