### ISSUE TITLE
I can't join my server and random text comes up

### ISSUE THREAD

**Issue by STROGANOFF32** [LunaPixelStudios/Better-MC#1637]
### Describe the Bug

Whenever i try to join my server random text comes up and it just stays there.
I can create and load worlds but i just can't join my server.
I even tried waiting for around 10 minutes but i just stays there, the tips (that can be seen in the screenshot at the bottom left corner) still keeps showing and changing but anything else doesn't change.

### Reproduction Steps

i dont know...

### Screenshots and Videos

![Screenshot_4](https://github.com/LunaPixelStudios/Better-MC/assets/72437660/79240cc8-7ee9-4691-a0bd-e402494e5341)

### Crash Report or Log

https://paste.atlauncher.com/view/58063103-d2a1-4f5f-ab8d-3ed3a644aab4

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc4 v26

**Comment by STROGANOFF32** [comment]
The Minecraft verson is 1.20.1, i'm not sure why it changed to 1.16 after i submitted the problem.

**Comment by chorbintime** [comment]
You do not have the same modpack installed both client and serverside. On clientside, use ATLauncher, and on serverside, use the serverpack files from the Curseforge page and read the readme file.
