### ISSUE TITLE
Client-only mods included in mrpack overrides

### ISSUE THREAD

**Issue by JulianVennen** [LunaPixelStudios/Better-MC#1640]
### Describe the Bug

The mrpack files for this modpack on modrinth include client-only mods in the overrides directory.
According to the file specification this means they should also be installed on the server.

Please place client-only files in the client-overrides folder instead: https://support.modrinth.com/en/articles/8802351-modrinth-modpack-format-mrpack#h_15261c2651

### Reproduction Steps

1. Download the mrpack
2. Extract it or open it as a zip
3. Check the overrides folder

### Operating System

Linux

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v4 HF

**Comment by JulianVennen** [comment]
entity_model_features is also marked as required on the server in the modrinth.index.json even though it is client-only according to their modrinth page and causes a crash on the server: https://mclo.gs/yfgd8l1

**Comment by JulianVennen** [comment]
Same thing for oculus: https://mclo.gs/lFZde0J

**Comment by chorbintime** [comment]
The modrinth version of the modpack is currently very outdated, and we're working on getting it properly updated. I would suggest installing the curseforge version for the time-being via ATLauncher or Prism
