### ISSUE TITLE
Better End and Better Nether slabs don't render

### ISSUE THREAD

**Issue by Manusia413** [LunaPixelStudios/Better-MC#1641]
### Describe the Bug

When I place a slab from the better end/better nether mod, it loads as a black and pink tile thing (or error texture)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Mac Sonma 14.1

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC 2 v24

### Other Mods

REI and REP is replaced with JEI and JEP

**Comment by chorbintime** [comment]
Will be fixed in the next update. In the meantime you can add this resourcepack https://modrinth.com/datapack/autoslabs-compat
