### ISSUE TITLE
GUI offsets when wearing elytra

### ISSUE THREAD

**Issue by alocalorange** [LunaPixelStudios/Better-MC#1642]
### Describe the Bug

The gui becomes offset when the player wears an elytra

### Reproduction Steps

1. Equip an Elytra

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/71112039/8904f6c0-9744-4403-ba6f-1c54454df9c5)
Without Elytra ^

![image](https://github.com/LunaPixelStudios/Better-MC/assets/71112039/38aea17c-4d1b-46ed-9e4a-8f710b5562e0)
With Elytra ^ Notice the gray border being offset
The following picture is showing how the cursor interacts with selection borders while wearing an elytra
![image](https://github.com/LunaPixelStudios/Better-MC/assets/71112039/92e54da1-49c5-4d97-b1af-0f05f96f98fc)
As you can see the cursor is on the gold ingot however it highlights the ender chest.

This bug is only active when the elytra is equipped. Unequipping it fixes it

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by alocalorange** [comment]
I see in my screenshot you can not actually see the cursor but I encourage you to reproduce it so that u can see for yourself

**Comment by alocalorange** [comment]
This is also in mc version 1.20.1--unsure why it is labeled 1.12

**Comment by chorbintime** [comment]
disable the elytra armor icon in the mod config for quark
