### ISSUE TITLE
Tried to read NBT tag with too high complexity, depth > 512 [level.at]

### ISSUE THREAD

**Issue by 570b94b0b898524bfeed84cf639316cb** [LunaPixelStudios/Better-MC#1643]
### Describe the Bug

Running game in single player mode.
Tried to load saved world. Game crashed while reading world data.

```
Exception reading XXX\minecraft\Instances\Better MC [FORGE] - BMC3\saves\Test2\level.dat
        java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512
```

[latest_cleaned.log](https://github.com/LunaPixelStudios/Better-MC/files/15137777/latest_cleaned.log)
(I already tried to run https://github.com/Lukrecjaaa/nbtmcafix, but it looks like it is only working on playerdata and entities and not the level.dat)

### Reproduction Steps

Last things done: fishing, trading with villagers, leveling villagers.
Not sure if the bug is reproducible.

### Crash Report or Log

https://github.com/LunaPixelStudios/Better-MC/files/15137777/latest_cleaned.log

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

**Comment by muon-rw** [comment]
This looks like the bug between Citadel and Terrablender that causes recursive nesting overworld Surface Rules. I would have to see the level.dat to be sure.

See  https://github.com/LunaPixelStudios/Better-MC/issues/1415#issuecomment-1743944136 for how to fix it, you can use a program like NBTStudio for that. 

Just to make sure, did you start this world on a version before v19?
