### ISSUE TITLE
Hoe just breaking every crop around target crop

### ISSUE THREAD

**Issue by Gamarleton** [LunaPixelStudios/Better-MC#1644]
### Describe the Bug

When right clicking with the hoe on a crop to collect an area of crops around the targetted crop (how it worked before) it just replants the targetted crop and breaks all the rest, regardless of whether the ones broken are done growing already or not, then you have to replant them. 

Happens with all crops, with any crop as target.
The only crop that doesn't do this is the rice, but only if you target the lower block of the rice, which is pretty hard to click through the field of growing upper block of rice crops. 
Tomatoes will all pop off and break, even the vines growing on rope. 

### Reproduction Steps

1. Grow field of crops.
2. Right click fully grown crop with hoe.
3. All around will pop off.

### Screenshots and Videos

![2024-04-29_00 58 06](https://github.com/LunaPixelStudios/Better-MC/assets/33168591/152ea17f-187a-4a48-895f-6213fea4191f)
![2024-04-29_00 58 07](https://github.com/LunaPixelStudios/Better-MC/assets/33168591/bd0d7c5d-296d-497f-a373-fcc30d679e90)

### Crash Report or Log

https://gist.github.com/Gamarleton/e3c1eb61c5e9064274f6bd80be75c8a7

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

### Other Mods

GoProne was added, I don't remember what else I added as I set this up months ago and didn't play actively for a couple of bmc versions.

**Comment by chorbintime** [comment]
will look into for the next update - thank you for the report
