### ISSUE TITLE
Cant chage skin?

### ISSUE THREAD

**Issue by InfinityIncorporated** [LunaPixelStudios/Better-MC#1645]
### Describe the Bug

Its probably me but i cant change the skin.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc 4

**Comment by chorbintime** [comment]
Skin changing works the exact same way as normal. The modpack does not change it in any way.
