### ISSUE TITLE
Commands dot work

### ISSUE THREAD

**Issue by InfinityIncorporated** [LunaPixelStudios/Better-MC#1646]
### Describe the Bug

Commands dont work on a server running this mod even if have everithing in configuration right

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc 2 fabric

**Comment by chorbintime** [comment]
Please be more specific. Are you getting an error message? Are you opped?
