### ISSUE TITLE
Better MC 1.20.1 Forge crash on start

### ISSUE THREAD

**Issue by po-0ya** [LunaPixelStudios/Better-MC#1647]
### Describe the Bug

Hi, Im trying to play better mc 1.20.1 forge, i already installed minecraft 1.20.1 forge and also installed better mc correctly but when im trying to launch the game after a short loading game crashed i couldn't find the issue i will upload my log file so hopefully someone help me to fix this issue <3

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/po-0ya/a8cd7586396a8e989043c00508fa04a0

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better Mc 1.20.1 Forge v26

**Comment by chorbintime** [comment]
You did not install the modpack correctly. You need a modded launcher to install & launch modpacks. I'd suggest ATLauncher
