### ISSUE TITLE
BackPacked Backpack recipe does not work.

### ISSUE THREAD

**Issue by SirSquill** [LunaPixelStudios/Better-MC#1650]
### Describe the Bug

The BackPacked recipe from the BackPacked Fixed Recipe data pack is not working.

It DOES work with the original recipe after disabling the Recipe Fix datapack.

### Reproduction Steps

1.Attempt to craft the BackPacked backpack.
2.
3.
...

### Screenshots and Videos

![2024-05-01_19 03 30](https://github.com/LunaPixelStudios/Better-MC/assets/136201049/493e1d1e-217e-41f7-88bd-18da56a07970)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v24

### Other Mods

Advancement Plaques, BetterAnimations Collection, Deepslate Cutting, Not Enough Animations, More Mob Variants

**Comment by chorbintime** [comment]
Can you retry on an unmodified instance? The datapack should work fine, it's just a recipe change.

**Comment by Neekodesu** [comment]
It doesn't work for me either.

https://github.com/LunaPixelStudios/Better-MC/assets/47283957/c9e3e11b-9497-4de6-afed-4ec17ef983ec
