### ISSUE TITLE
Dynamic lighting causes entities to glow white

### ISSUE THREAD

**Issue by ilyfairy** [LunaPixelStudios/Better-MC#1651]
### Describe the Bug

Dynamic lighting causes entities to glow white

### Reproduction Steps

Turn on `ComplementaryShaders_v4.7.1` light and shadow, enter the game and wait for 2 minute

### Screenshots and Videos

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/dMW73raRDhA/0.jpg)](https://www.youtube.com/watch?v=dMW73raRDhA)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v60.5

**Comment by chorbintime** [comment]
Update Complementary Shaders to the latest version. If it keeps happening, then report this to the creators of the shaderpack
