### ISSUE TITLE
chunks stop charging after 2/3 minutes

### ISSUE THREAD

**Issue by SimonS12S** [LunaPixelStudios/Better-MC#1652]
### Describe the Bug

After a while, when I'm exploring for 2 or 3 minutes, the chunks stop charging, and when I'm in a zone that's not charging, everything goes white. I'm playing on Tlauncher on crack, I've tried changing the memory allocation but nothing works. Whether on a server or solo locally. When I launch minecraft without BMC4, I don't have the problem even at 64 chunk render distance, they all load without problem when I move forward.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Bug BetterMC (1)](https://github.com/LunaPixelStudios/Better-MC/assets/111075521/19232cf1-5391-4dc3-b5fa-7ea8cb4a75ab)
![Bug BetterMC (2)](https://github.com/LunaPixelStudios/Better-MC/assets/111075521/ed3df3a8-624c-4776-9f0f-e17beeaf7e76)
![Bug BetterMC (3)](https://github.com/LunaPixelStudios/Better-MC/assets/111075521/296e37a7-9fb4-4cda-ab32-28d3cd3ede6b)

https://github.com/LunaPixelStudios/Better-MC/assets/111075521/f9c239d3-fe4d-4144-be97-a9f4384247db

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
TLauncher is spyware and does not install mods or modpacks correctly. We offer no support for it whatsoever.
