### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by AbyssStudios2009** [LunaPixelStudios/Better-MC#1653]
### Describe the Bug

Just started playing this modpack and i love it but i see missing textures in a few spots it's not a huge issue but it is emersion breaking plus it might be something on my side

### Screenshots and Videos

![Screenshot 2024-05-02 182924](https://github.com/LunaPixelStudios/Better-MC/assets/168788450/2972bd80-bdc8-414a-98cd-1f77bb2ccd38)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v26

**Comment by chorbintime** [comment]
Specifically what block has the invalid texture?

How did you install the modpack?
