### ISSUE TITLE
Cursor Offset when game is paused or in inventory

### ISSUE THREAD

**Issue by Maleviolentbenvolence** [LunaPixelStudios/Better-MC#1654]
### Describe the Bug

The screen has shifted slightly to the right and as a result, the hitboxes of the inventory slots are not aligned with the cursor. 

### Reproduction Steps

After some more research, I learned that this occurs when an elytra is equipped.

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/168870468/964a6561-5adb-48a3-b8c8-5304238c6d29)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/168870468/3ba89b9a-2f4c-404c-8a03-4acc815c4fd1)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v26

### Other Mods

Not that I'm aware of.

**Comment by chorbintime** [comment]
disable the elytra armor icon in the mod config for quark
