### ISSUE TITLE
Cannot place down, destroy or grow mushrooms in Better minecraft modpack

### ISSUE THREAD

**Issue by Angelicanoream** [LunaPixelStudios/Better-MC#1656]
### Describe the Bug

The vanilla mushrooms from minecraft cannot be interacted with, if i try to grow an already spawned in mushroom (brown or red) it disappears, if i try t destroy it, it reappears. I cannot place down any that i got from chests either

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

1.20.1

### Other Mods

Just Another Rotten Flesh to Leather and Sophisticated Backpacks

**Comment by chorbintime** [comment]
Are you placing the mushrooms in the darkness?
