### ISSUE TITLE
Can't add the better combat mod to a server

### ISSUE THREAD

**Issue by sLAV16** [LunaPixelStudios/Better-MC#1657]
### Describe the Bug

When i add the better combat mod to the server it crashes it. is there another mod that includes dual wielding that could interfere with better combat. Also i have the architecture API so it's not because of that

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

no

### Crash Report or Log

server crash

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc3

**Comment by chorbintime** [comment]
Make sure you installed all of the mods dependencies, and send your latest.log and/or crash report.
