### ISSUE TITLE
an error occurred in Luna

### ISSUE THREAD

**Issue by Jia97s** [LunaPixelStudios/Better-MC#1658]
### Describe the Bug

Unable to share to local area network

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![cc3fc2f46ec280756a4f8a865431f75](https://github.com/LunaPixelStudios/Better-MC/assets/84956950/5e27f5aa-7088-4041-881f-3b5863a4c078)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v26

**Comment by chorbintime** [comment]
The server capacity is likely full. Please use the serverpack from the modpack's Curseforge page.
