### ISSUE TITLE
Paintings++ UI deosn't apply Painting choice due to conflict with Fast Paintings.

### ISSUE THREAD

**Issue by dabush03** [LunaPixelStudios/Better-MC#1659]
### Describe the Bug

When placing a Painting on the wall, the Paintings++ UI appears, but the painting does not change after making your selection. However, after testing, I found that updating Fast Paintings to version 1.2.7 fixes this problem.

### Reproduction Steps

1. Place a painting.
2. Make your selection.

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by chorbintime** [comment]
All mods will be updated in the next modpack update.
