### ISSUE TITLE
"You have added a mod that is incompatible with our Modpack!"

### ISSUE THREAD

**Issue by FranLeme** [LunaPixelStudios/Better-MC#1660]
### Describe the Bug

I play Minecraft through TLauncher and this is the first time I see this error occurring. The game loads normally until the menu opens, which says "You have added a mod that is incompatible with our Modpack! Please remove any extra mod you added to the modpack until this warning disappears." I didn't add any extra mods and even with a friend of mine, with the original Minecraft, downloading the same version gave the same error.

### Screenshots and Videos

![imagem_2024-05-08_190015876](https://github.com/LunaPixelStudios/Better-MC/assets/169311663/c9907620-d64c-46fa-84af-1687c3975a8c)

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v26

**Comment by chorbintime** [comment]
TLauncher is spyware that is incapable of installing mods or modpacks correctly. We offer no support for it whatsoever. Please buy a valid copy of Minecraft and reinstall using https://atlauncher.com/downloads

**Comment by TheHarelator** [comment]
for anyone else looking for the solution you can just delete "error.txt" from these directories:
minecraft\defaultconfigs\fancymenu\customization
minecraft\config\fancymenu\customization
for fabric versions i've also seen the luna jar mod interfering just so you have a lead lol
