### ISSUE TITLE
bug(FTB-Quests): Better MC [FORGE] 1.20.1 v26 twilight forest

### ISSUE THREAD

**Issue by axel7083** [LunaPixelStudios/Better-MC#1662]
### Describe the Bug

When killing the hydra by sending back fireball, we do not get the quest `Defeat the Hydra` validated.

The problem is coming from the following

https://github.com/LunaPixelStudios/Better-MC/blob/f738b9d68c1199c904bcd702077ded162539bf0c/Better%20MC%20%5BFORGE%5D%201.20.1%20v26/config/ftbquests/quests/chapters/the_twilight_forest.snbt#L95-L102

The quest is not based the achievement but the `kill` action of the hydra, we can make it complete by killing with a sword in create the hydra, but this is not the intended way, as it is pretty difficult to kill it like this...

### Reproduction Steps

1. Go to the twilight forest
2. Do quest before hydra a normal
3. Kill the hydra by sending back fireball
...

### Screenshots and Videos

We can see the issue if from the quest system as we have the archievement validated

![image](https://github.com/LunaPixelStudios/Better-MC/assets/42176370/27ae7ab3-2494-4053-9e56-a934e6177018)

However inside the quest book, the quest is not marked as validated

![image](https://github.com/LunaPixelStudios/Better-MC/assets/42176370/f0a8cbb8-1bd1-4896-a31a-bc9be019fc2e)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

/Better MC [FORGE] 1.20.1 v26

**Comment by chorbintime** [comment]
Will be fixed in the next modpack update, thank you for the report!
