### ISSUE TITLE
Cannot access inventory, use scroll wheel, break blocks, run, etc

### ISSUE THREAD

**Issue by zkulld** [LunaPixelStudios/Better-MC#1664]
### Describe the Bug

I was playing and placed a 2x2 painting on the side a door opens to, blocking it. I tried to break the object and none of my blocks will break. I've tried removing paintings++ and it did not work. I tried replacing that area of blocks with air and it didn't work. I recreating the world with the same save and it is having the same issues. When I created a world with the same seed, it would let me access inventory and everything.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc2 v24

### Other Mods

No.

**Comment by chorbintime** [comment]
Can you please record a video demonstrating the issue?
