### ISSUE TITLE
Quest mod is missing

### ISSUE THREAD

**Issue by wolena** [LunaPixelStudios/Better-MC#1665]
### Describe the Bug

In the description it say's "100+ Quests", but no quests show up in game. In the modlist there also is no longer a quest mod listed

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

1.20.1

**Comment by chorbintime** [comment]
On the modrinth version of the modpack, you need to manually add the ftbquests mod
