### ISSUE TITLE
GUI offset with elytra

### ISSUE THREAD

**Issue by Spyroooo** [LunaPixelStudios/Better-MC#1666]
### Describe the Bug

When equipping a elytra the screen gets offset by a few pixels which causes the cursor to not be aligned correctly.

### Reproduction Steps

Equip elytra in chest armor slot. Found out that this only happens in survival mode, creative looks fine

### Screenshots and Videos

![image_2024-05-12_215340837](https://github.com/LunaPixelStudios/Better-MC/assets/81745526/36ac4492-c8f2-4b49-856f-62e42b3f3374)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v26

**Comment by chorbintime** [comment]
disable the elytra armor icon in the mod config for quark

**Comment by Spyroooo** [comment]
Where in the mod config is this located?

**Comment by chorbintime** [comment]
Its in the client section

**Comment by chorbintime** [comment]
You need to change it clientside only and restart your game after. This fix does work. If it doesn't work for you, you're doing something wrong.

The option is specifically called "Elytra Indicator"

**Comment by vmzHernandes** [comment]
> You need to change it clientside only and restart your game after. This fix does work. If it doesn't work for you, you're doing something wrong.
> 
> The option is specifically called "Elytra Indicator"

This does work! Thanks

**Comment by chorbintime** [comment]
this issue is fixed on the latest modpack update. please update to v28
