### ISSUE TITLE
Game crashes straight after loading

### ISSUE THREAD

**Issue by Blu3-Martian** [LunaPixelStudios/Better-MC#1667]
### Describe the Bug

I've downloaded cursed forge and the modpack properly and have even used ATLauncher to fix the issue but every time the launcher crashes before it starts loading the launcher. 
Added more ram to game, updated java but nothing seems to help.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/Blu3-Martian/50785264b6fa80fbaf3b969c3f8f9b63

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

**Comment by chorbintime** [comment]
update your drivers
