### ISSUE TITLE
Coarse Dirt not appearing

### ISSUE THREAD

**Issue by FetinMGBP** [LunaPixelStudios/Better-MC#1668]
### Describe the Bug

The placed coarse dirt texture appears to be missing. Idk what other blocks have this problem, but so far only the coarse dirt has that problem. Even when I break it, the particle effect appears as the black and purple "missing textures".

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/169741915/8faf6e23-afc3-45db-a766-7849a48a4a49)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC [FORGE] - BMC4

**Comment by FetinMGBP** [comment]
Forgot to show the particle effect.

![image](https://github.com/LunaPixelStudios/Better-MC/assets/169741915/2a4a7d78-dc40-4897-a5bf-bf49d88f5330)

**Comment by chorbintime** [comment]
How did you install the modpack?
