### ISSUE TITLE
bmc4 dragon mounts legacy

### ISSUE THREAD

**Issue by AlfredoAlpha** [LunaPixelStudios/Better-MC#1670]
### Describe the Bug

hey can someone help me, so my problem is in bmc4 there is the dragon mounts legacy mod that comes with different variants of dragons but when i go in creative there is only one type of dragon when there is supposed to be multiple

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4

**Comment by chorbintime** [comment]
Update the Dragon Mounts Legacy mod. If the issue persists then report it to the mod developer

**Comment by AlfredoAlpha** [comment]
how do report it?

**Comment by chorbintime** [comment]
Find the mod developer's github or discord server
