### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Fer36009** [LunaPixelStudios/Better-MC#1672]
### Describe the Bug

Missing textures on sand and stone there is more but can't seem to find them 
I Installed the mod with curse forge launcher

### Reproduction Steps

1. Install mod on curse forge
2. Launch
3. Create World
...

### Screenshots and Videos

![image_2024-05-17_190419612](https://github.com/LunaPixelStudios/Better-MC/assets/170151250/e060eea9-209c-41b7-9d22-41c9355efe55)
![image_2024-05-17_190430777](https://github.com/LunaPixelStudios/Better-MC/assets/170151250/f3118752-d1b8-4055-97e6-899b295b2a53)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

### Other Mods

No freshly installed

**Comment by chorbintime** [comment]
Reinstall the modpack on ATLauncher. You can also try reloading your textures by pressing F3 + T
