### ISSUE TITLE
Server crashing whenever I join (bumblezone mod issue)

### ISSUE THREAD

**Issue by lhammersmith** [LunaPixelStudios/Better-MC#1673]
### Describe the Bug

I was exploring the bumblezone while the host of the server (using the essential mod) was just in the overworld afk. At one point I jumped into a large pollen pile and I think the amount of particles overloaded the server client and crashed it. Now whenever I rejoin, the hosts game crashes, so we're essentially soft locked.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v24 for fabric

**Comment by chorbintime** [comment]
Essential is an unstable and unsupported mod. The mod causes world corruption and many other issues. Please switch to an approved hosting method, such as the world hosting button ingame (click Open to LAN) or by selfhosting via the serverpack file on the modpack's Curseforge page.
