### ISSUE TITLE
Additional mod message on the main screen doesn't allow u to play the game

### ISSUE THREAD

**Issue by MUGXN88** [LunaPixelStudios/Better-MC#1674]
### Describe the Bug

"you have added a mod that is not compatible with our Modpack! please remove any extra mods you added to the modpack until this warning disappears." message on the main screen that doesn't allow me to play the game with the modpack on knowing that i didn't install any additional mod

### Reproduction Steps

1. download the modpack from cursed forge 
2. lunch the game
3. load the modpack automatically
4. the main screen shows the message "you have added a mod that is not compatible with our Modpack! please remove any extra mods you added to the modpack until this warning disappears.  " under the title "Better Minecraft"
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/170198053/73e20756-0b5f-4a4f-ab57-e31f7d2f950b)

### Operating System

windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

betterMC 1.20.1 Forge 47.2.17

**Comment by chorbintime** [comment]
What launcher are you using?
