### ISSUE TITLE
getting 3 error lines, not sure what it is

### ISSUE THREAD

**Issue by Salutatorian** [LunaPixelStudios/Better-MC#1675]
### Describe the Bug

everytime i launcher a server, i get three error lines. i went to the host server im using and they said im using client side mods that needs to be removed but which one?? if not what is the problem....

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/3LFO6Wp

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bettermc v26

### Other Mods

no mods

**Comment by chorbintime** [comment]
You need to use the serverpack on the modpack's Curseforge page to install the modpack serverside.
