### ISSUE TITLE
Issue with my server (crash)

### ISSUE THREAD

**Issue by YounesBrz** [LunaPixelStudios/Better-MC#1677]
### Describe the Bug

Hello Guys,

I need your help on this issue, when im tryin to lauch my MC server with the run.bat files i have an crash message.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/tEG45gqa

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Server Pack v26

**Comment by chorbintime** [comment]
The pastebin link is no longer valid, so I'm unable to view your log
