### ISSUE TITLE
Crafting Table Lag Spike

### ISSUE THREAD

**Issue by hunnnna** [LunaPixelStudios/Better-MC#1680]
### Describe the Bug

I place down crafting table, i click and huge lag spike, I then go to move items i get hit with another lag spike.

### Reproduction Steps

1.Place Crafting Table
2.Click on Table, Huge Lag Spike
3.Move Item i get hit with another Lag Spike
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/171112174/cefb6796-f3aa-4fe3-b512-75a698c0dc6f

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2

**Comment by DrBurnzo** [comment]
Same. Better MC [FABRIC] 1.20.1 v24.  

https://spark.lucko.me/VxrrQNHh50

**Comment by chorbintime** [comment]
update to v25
