### ISSUE TITLE
Chunks not loading fast enough

### ISSUE THREAD

**Issue by Xtraluvv** [LunaPixelStudios/Better-MC#1681]
### Describe the Bug

every time i get to new areas its hard for the chunks to load in time for me and my 2 friends to explore so we have to wait for the chunk to load in to go to the next chunk

### Reproduction Steps

1.
2.
3.
...
jjj

### Screenshots and Videos

![2024-05-30_00 16 09](https://github.com/LunaPixelStudios/Better-MC/assets/171218561/6e7fce14-6824-4154-b924-7a06a5810340)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

Better MC

**Comment by chorbintime** [comment]
fixed in v25
