### ISSUE TITLE
Better MC Server error on startup

### ISSUE THREAD

**Issue by Dog1e** [LunaPixelStudios/Better-MC#1682]
### Describe the Bug

Every time i start my server i get an error with betterEnd

### Reproduction Steps

1.Run server
2.Error
3.
...

### Crash Report or Log

https://gist.github.com/Dog1e/1ae5c000f5eee8548609ac2db6e5f963

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v26

**Comment by Dog1e** [comment]
Ok, I did this and for some reason it works:
1.deleting connector mod (Connector-1.0.0-beta.36)
2.adding the newest version of connector (Connector-1.0.0-beta.43)
3.running server (it doesn't work with this version)
4.adding connectors version from begining (Connector-1.0.0-beta.36)
5.Now everything works

No idea how does that work. I think something downloaded when I was trying to launch the server with (Connector-1.0.0-beta.43) but I don't know to be honest.

**Comment by acepilot3342** [comment]
Having the same issue and unfortunately this fix didn't work.

**Comment by chorbintime** [comment]
The fix for OP's issue is to simply launch the server a second time, or just updating Connector. 

acepilot's issue was completely unrelated. They did not have the right version of Java installed.
