### ISSUE TITLE
I cant use Essentials mod

### ISSUE THREAD

**Issue by takeriso** [LunaPixelStudios/Better-MC#1684]
### Describe the Bug

I tried downloading it but this appears.

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/170906561/7eba690a-f61c-42be-8d82-e111a1d72276)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

26

### Other Mods

Essentials

**Comment by chorbintime** [comment]
The Essential mod is completely incompatible with all of our modpacks. The mod is known to cause world corruption and a plethora of crashes and other issues. 

In other modpacks, you can use the e4mc mod for easy, free world hosting.
In our modpacks, we have our own custom fork of e4mc already included, which also offers free world hosting. At the time of writing, the world hosting is down for maintenance but it will return soon.

For free server hosting with full control, you can use the serverpack files on the modpack's Curseforge page. Read the "README" file included in the serverpack files for more information.
