### ISSUE TITLE
Backpacked

### ISSUE THREAD

**Issue by Rovermat** [LunaPixelStudios/Better-MC#1688]
### Describe the Bug

Curseforge Better Minecraft - BMC2 Fabric 1.20.1 v24

Unable to craft the backpacked (MrCrayFish) and the crafting recipe is different. The 5 enchanted books can be obtained from villagers. Only able to craft another version of backpack (Inmis
 By
 [Draylar1]).

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-06-01_18 54 18](https://github.com/LunaPixelStudios/Better-MC/assets/93138508/481c1e91-57fa-4bd0-a0a0-7d44bfad9507)

### Operating System

Window 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2 v24

**Comment by chorbintime** [comment]
update the modpack to the latest version

**Comment by SaikoTSP** [comment]
Same issue with backpacked in Bmc2 Fabric v25

**Comment by chorbintime** [comment]
it's fixed in v26 which isn't released yet. just craft the backpacks from Inmis instead
