### ISSUE TITLE
Can't connect to my server "nethersdelight" 1.20.1

### ISSUE THREAD

**Issue by Aquakd** [LunaPixelStudios/Better-MC#1689]
### Describe the Bug

Well I was playing with friends on a aternos server which forced us to update bettermc from v24 to v25 and when we tried to connect on the server it says "joining world" then an connection lost message with "nethersdelight" appears and we don't know how to fix it 
![image](https://github.com/LunaPixelStudios/Better-MC/assets/171423891/32f1df8f-eba9-432c-aa5a-50c0f7715ca5)

### Screenshots and Videos

![image_2024-06-01_134658121](https://github.com/LunaPixelStudios/Better-MC/assets/171423891/973f40fb-1703-42fd-bd33-eeffec9a3e32)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

BMC2 V25

**Comment by HaxHaxA** [comment]
same

**Comment by epicgamer2747** [comment]
Anyone find a fix ?

**Comment by toonicat** [comment]
Had this same problem until I pressed the update to new modpack button

**Comment by bjonkmyplonk** [comment]
> Had this same problem until I pressed the update to new modpack button

where is that located

**Comment by chorbintime** [comment]
update the modpack to the latest version
