### ISSUE TITLE
Eden Ring Portal

### ISSUE THREAD

**Issue by lamalu94** [LunaPixelStudios/Better-MC#1690]
### Describe the Bug

After the new reforked eden ring update, I opened the portal but as I go to enter my game crashes and I get an error message saying that the "biome is null"

### Reproduction Steps

1.create eden ring portal
2.ignite it
3.try to go inside
...

### Operating System

windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc v25

### Other Mods

n/a

**Comment by chorbintime** [comment]
please report the issue to the mod author

**Comment by sil0o** [comment]
exact same issue
