### ISSUE TITLE
Better MC [FABRIC] - BMC2 | Join Error in the Launcher 

### ISSUE THREAD

**Issue by xKaaniii** [LunaPixelStudios/Better-MC#1691]
### Describe the Bug

I installed the modpack. Then I startet it then MC Launcher startet, I click Play.

In MC Multiplayer then the IP from the Server and then Join but then a ERROR

### Screenshots and Videos

![Screenshot 2024-06-01 040918](https://github.com/LunaPixelStudios/Better-MC/assets/171442255/9d62b7c6-f554-4f65-b7a3-51490aba26bd)

### Crash Report or Log

Dont find onee

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] - BMC2

**Comment by chorbintime** [comment]
you dont have the same modpack installed as the server
