### ISSUE TITLE
BMC4 CRASHES ON STARTUP

### ISSUE THREAD

**Issue by YatezV2** [LunaPixelStudios/Better-MC#1692]
### Describe the Bug

game crashes on start up

### Reproduction Steps

1.
2.
3.
...
tried on both cursed forge and atlaucher

### Screenshots and Videos

n/a

### Crash Report or Log

https://gist.github.com/YatezV2/09df295d2c530ce08f6f739666ec67ad

### Operating System

win 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 forge 1.20.1

### Other Mods

n/a

**Comment by chorbintime** [comment]
update your gpu drivers
