### ISSUE TITLE
BMC1 1.16.5 CRASH IN BLUE SKIES EVERBRIGHT DIMENSION

### ISSUE THREAD

**Issue by PermaCrasher** [LunaPixelStudios/Better-MC#1693]
### Describe the Bug

A couple of friends and I started a modded mc server with Better MC. While we are trying to get to the everbright dimension my game just freezes and crashes. For them its not an issue and now i cant even join the server without instantly crashing. It has only been crashing for the dimension. I have already tried re-installing the latest 1.16.5 version.

### Reproduction Steps

1. I join the server 
2. My screen freezes for about a sec
3. I crash

### Screenshots and Videos

![afbeelding_2024-06-04_014144648](https://github.com/LunaPixelStudios/Better-MC/assets/171633155/90c2f156-4ee5-43b1-b168-31d1d6ba6d4b)

### Crash Report or Log

https://pastebin.com/RfSLx505

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC 1 V60.5

**Comment by chorbintime** [comment]
update the mod, if the issue persists then report it to the mod author
