### ISSUE TITLE
Tooltip Error in Just Enough Items

### ISSUE THREAD

**Issue by bottleofstress** [LunaPixelStudios/Better-MC#1695]
### Describe the Bug

When hovering over an item in Just Enough Items, the text "Tooltip error, see logs" is displayed instead of the item name and mod it's from. This happens for every item.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot (28)](https://github.com/LunaPixelStudios/Better-MC/assets/171700489/b8788047-5d05-4cf5-8dfe-166b2b1cc2a8)
![Screenshot (29)](https://github.com/LunaPixelStudios/Better-MC/assets/171700489/4ef32c03-385e-438f-b334-cd0ac7f68f57)
![Screenshot (30)](https://github.com/LunaPixelStudios/Better-MC/assets/171700489/a6a4c9c4-913f-42e4-98f2-0468d3000d50)

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v27

**Comment by thehamish555** [comment]
Also, another UI thing could possibly be this?
![image](https://github.com/LunaPixelStudios/Better-MC/assets/89168856/0b36113c-a049-413f-a747-45a06ef91de2)

**Comment by bottleofstress** [comment]
That wasn't an issue I've seen. I restarted Minecraft and it seemed to fix the issue for me

**Comment by bottleofstress** [comment]
I fixed the issue. I just reverted JEI to an older version.
