### ISSUE TITLE
BMC4 Game Crash

### ISSUE THREAD

**Issue by Blu3-Martian** [LunaPixelStudios/Better-MC#1697]
### Describe the Bug

Minecraft loads game and before initial loading screen for the game to start it instantly crashes. All drivers are up to date and I have re downloaded modpacks multiple times and used modded launchers but nothing seems to help. Even have downloaded latest version of java and it shouldnt be a memory issue either. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/Blu3-Martian/4aed4cc194cd6a63a5fd9d8f3152818e

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

**Comment by chorbintime** [comment]
update your GPU drivers
