### ISSUE TITLE
my server always crash

### ISSUE THREAD

**Issue by Darkericy** [LunaPixelStudios/Better-MC#1698]
### Describe the Bug

I am using version 1.19.2 of the server and after running it for about a week, an error occurred. Powershell keeps reminding me that the server is overloaded (but it seems like we haven't done anything big). Now every time I start the server, it will directly prompt me that the server is overloaded, and then crash. We can no longer play games
Is this a local issue for me? Do I have a chance to restore him?

### Reproduction Steps

1.click the Start.ps1 file and Open with Powershell. 
2.Powershell prompts me that the server is overloaded
3.crash
...

### Screenshots and Videos

![屏幕截图 2024-06-07 160917](https://github.com/LunaPixelStudios/Better-MC/assets/78835438/b8cab779-f29a-4924-aef8-57f5cd472b9b)

### Crash Report or Log

<script src="https://gist.github.com/Darkericy/2e0b5f77fd3fe06dcf844af9656a4010.js"></script>

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1_FABRIC_1.19.2_Server_Pack_v20

**Comment by Darkericy** [comment]
sorry
crash report here: [https://gist.github.com/Darkericy/2e0b5f77fd3fe06dcf844af9656a4010](url)

**Comment by chorbintime** [comment]
try updating the neruina mod

**Comment by Darkericy** [comment]
> try updating the neruina mod

It needs a higher version fabric-loader

**Comment by chorbintime** [comment]
then remove it
