### ISSUE TITLE
BMC2 Fabric Server starting, but not fully loading with error

### ISSUE THREAD

**Issue by RealMrUnknownymous** [LunaPixelStudios/Better-MC#1699]
### Describe the Bug

I'm trying to run a Better MC server on Crafty Controller, but I'm getting the error:

`[Netty Epoll Server IO #6/ERROR]: Exception occurred in netty pipeline
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer`

I've tried other modpacks, mainly from Modrinth, that start completely fine, but BMC2 keeps getting this error.

### Reproduction Steps

1. import Server Pack from Curseforge to Crafty Controller
2. Install curl so start.sh works
3. Start the server
4. Wait until server gives the error: 

```
[Netty Epoll Server IO #6/ERROR]: Exception occurred in netty pipeline
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```
...

### Crash Report or Log

https://mclo.gs/pc3lCwk

### Operating System

Debian 12/CasaOS

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

BMC2 v25

### Other Mods

No

**Comment by chorbintime** [comment]
Do not install the server using files from Modrinth. If you're using one of those weird dockers that require a manifest file, then you're completely wasting your time and need to find something different. 

The server files directly from the modpack's Curseforge page are the only proper and supported way to start a server.

**Comment by bm** [comment]
Is there a way to replicate the functionality of the server pack start scripts without actually running them? I am using a hosted game server service with a cPanel, and they understandably don't allow execution of external shell scripts, so the server is just ran by the regular Fabric loader process. The modpack works but I am similarly getting Netty console spam.

**Comment by RealMrUnknownymous** [comment]
> Do not install the server using files from Modrinth. If you're using one of those weird dockers that require a manifest file, then you're completely wasting your time and need to find something different.
> 
> The server files directly from the modpack's Curseforge page are the only proper and supported way to start a server.

The thing is, I did use the server files from Curseforge.

**Comment by chorbintime** [comment]
> Is there a way to replicate the functionality of the server pack start scripts without actually running them? I am using a hosted game server service with a cPanel, and they understandably don't allow execution of external shell scripts, so the server is just ran by the regular Fabric loader process. The modpack works but I am similarly getting Netty console spam. @chorbintime I see your comment above, but unfortunately this is an unavoidable issue for people using game hosting services with limited machine access.

You dont need to use the start scripts if you bought a server from another host. You just need to transfer the main serverpack files, and ignore the scripts. 



> > Do not install the server using files from Modrinth. If you're using one of those weird dockers that require a manifest file, then you're completely wasting your time and need to find something different.
> > The server files directly from the modpack's Curseforge page are the only proper and supported way to start a server.
> 
> @chorbintime The thing is, I did use the server files from Curseforge.

I'm not exactly sure what the issue is. If the error is spamming console, there's nothing to be worried about if you're able to join the world & play. Is the server not running properly?

**Comment by allen546** [comment]
I've got this issue too, modpack is completely self-hosted, using crafty controller and BMC2 v25 fabric 1.20.1. Plays perfectly, but this message keeps spamming console. This message seems to be only occurring when crafty's webpage is not asleep, that is, opened. When I switch to a different tab the error stops spamming.

**Comment by chorbintime** [comment]
Ignore the error or add it to the logbegone mod config
