### ISSUE TITLE
Opening the Advancements menu freeze my computer

### ISSUE THREAD

**Issue by Funcat1234cool** [LunaPixelStudios/Better-MC#1702]
### Describe the Bug

Whenever i press "L" on the keyboard or open the advancement menu through clicking the escape button first, my computer freezes. It works as normal for about 1 frame (i think).
The weird thing is, that i can just press "L" or the escape button again, like nothing happened, even though my entire computer freezes while the advancements menu is open. If i have a youtube video open, on my other moniter, the video freezes but the audio doesn't.

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v27.5

**Comment by chorbintime** [comment]
Please try following the performance guide linked on the main menu
