### ISSUE TITLE
"Returning Straddleboard" enchantment not returning Straddleboard

### ISSUE THREAD

**Issue by Antitect** [LunaPixelStudios/Better-MC#1704]
### Describe the Bug

When breaking a Straddleboard with the "Returning Straddleboard" enchantment, it should return to the player's inventory. It does this successfully while the straddleboard is in lava, however when the straddleboard is on land it just disappears and does not return to the player's inventory.

### Reproduction Steps

1. Place down straddleboard with "Returning Straddleboard" enchantment on land.
2. Break the Straddleboard
3. Bug happens as Straddleboard does not reappear in player's inventory.

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 v26

**Comment by chorbintime** [comment]
v26 is old. We offer no support for old versions.
