### ISSUE TITLE
Void shadow boss quest

### ISSUE THREAD

**Issue by CatAaron** [LunaPixelStudios/Better-MC#1705]
### Describe the Bug

After beating the void shadow boss no one on our server cant get the void shadow quest complete.

I think its because you beat him with crystals that explode so its not registering that the player killed it.

### Reproduction Steps

1. beat all the end quest
2. beat the void shadow
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
Might be unfixable if no advancement is given for the quest, but I'll look into how this could be changed. Thank you for the report

**Comment by CatAaron** [comment]
I understand, thank you for looking into it for us
