### ISSUE TITLE
Shaders ???

### ISSUE THREAD

**Issue by The-Weirdo000** [LunaPixelStudios/Better-MC#1706]
### Describe the Bug

no idea if its related to anything within the folders, but my shaders are freaking out my HUD, I've tried multiple shaders they all do the same thing and turn all characters pitch black. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image_2024-06-10_030759089](https://github.com/LunaPixelStudios/Better-MC/assets/172252689/f9bc950d-bea7-4410-9b65-727f75f21c68)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 1.19.2 v14.5.zip

**Comment by chorbintime** [comment]
v14.5 is extremely old. We offer no support for old versions whatsoever
