### ISSUE TITLE
Game crashed whilst initializing game, Exit Code: -1

### ISSUE THREAD

**Issue by Rovermat** [LunaPixelStudios/Better-MC#1707]
### Describe the Bug

I was the reporter of "backpacked", so I updated all the mods on curseforge and use the updated fabric loader 0.15.11. And it crashed. Please help, thank you.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/93138508/11331988-61b3-4546-8c55-f7df0a0813d8)

### Crash Report or Log

https://gist.github.com/Rovermat/6a9f7a8947e50bf6faf5ce731af37212

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v24

### Other Mods

I read the v25 changelog, so I personally delete the mods:
1: Too Fast
2: Yeetus Experimentus
3: Model Gap Fix
4: Sever Country Flags
So there are 273 mods now.

**Comment by chorbintime** [comment]
Please update to v25 properly and do not remove/add/update mods randomly. 

I would highly suggest a fresh install on ATLauncher. Transfer over your saves folder - your world is safe to update.
