### ISSUE TITLE
1.20.1 server keeps crashing

### ISSUE THREAD

**Issue by Aydan-xd** [LunaPixelStudios/Better-MC#1708]
### Describe the Bug

Server keeps crashing about 3 minutes after joining. I think 2 mods are causing it but i have no clue. After joining before it crashes it is very laggy and chunks do not load.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/Vx6qQzqW

### Operating System

Ubuntu server

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
report the issue to the developers of Mowzies Mobs. In the meantime you could try setting maxticktime to -1 in server.properties

**Comment by Aydan-xd** [comment]
Alright will do, thank you.
