### ISSUE TITLE
Ores not dropping raw items when mined with correct pickaxe or higher.

### ISSUE THREAD

**Issue by ImPlushie** [LunaPixelStudios/Better-MC#1709]
### Describe the Bug

When I went mining, I found some iron and it didn't drop any raw iron like it is suppose to.. so I tried gold, nothing... Copper, nothing.. Coal, nothing.. I tried different pickaxes and everything. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/172523321/ce629e22-1db4-4ca6-8402-5066b1ec212a

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
was resolved in the discord - the items were going into their backpack
