### ISSUE TITLE
Recipe book

### ISSUE THREAD

**Issue by pztrick347** [LunaPixelStudios/Better-MC#1710]
### Describe the Bug

I was working on the storage system that comes with toms simple storage mod and i decided to use the crafting terminal and i clicked the magnifying glass and it caused an INSANE frame drop anytime i try to craft anything anywhere. I think the issue has to do with the compatability with the recipe book but im j putting it out there.

### Reproduction Steps

1.Make an inventory via Toms simple storage mod
2.connect a crafting terminal
3.click the magnifying glass next to the crafting grid in the terminal
...

### Operating System

Windows 11 

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v25

**Comment by chorbintime** [comment]
The most you can do is follow the performance guide by pressing the button on the main menu. A lot of this is just unavoidable due to the nature of having a storage system.
