### ISSUE TITLE
Game keeps crashing before it opens

### ISSUE THREAD

**Issue by BluPrizim** [LunaPixelStudios/Better-MC#1711]
### Describe the Bug

Each time I press play in Curseforge it will open the launcher then I press play and wait. After a few seconds it says that the game has crashed. Couldn't paste the crash report so I copied it into a doc.

### Reproduction Steps

1. Press play on Better MC in Curseforge
2. Press play on the Better MC version of Minecraft in launcher
3. Crashes
...

### Crash Report or Log

https://docs.google.com/document/d/1U4n12YFfAtcmbCeMgOfYBQ5isqeEQTWnqEtNW4jyyaU/edit

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

Essential

**Comment by chorbintime** [comment]
update your GPU drivers directly from the vendor's website
