### ISSUE TITLE
Inventory visual

### ISSUE THREAD

**Issue by OWENRCACS** [LunaPixelStudios/Better-MC#1712]
### Describe the Bug

My screen shows every item in my inventory with exception to what is in my hotbar and what I am wearing

### Reproduction Steps

1. I
2. Don't
3. Know
...

### Screenshots and Videos

![Screenshot 2024-06-14 172237](https://github.com/LunaPixelStudios/Better-MC/assets/172855009/a5ea788a-6515-4a71-8b08-f24949d40120)

### Crash Report or Log

June 13 2024

### Operating System

Windows acer

### Minecraft Version

1.16.5

### Modloader

Fabric

### Modpack Version

Latest as of June 13

**Comment by chorbintime** [comment]
Press I on your keyboard
