### ISSUE TITLE
Missing Recipe Book

### ISSUE THREAD

**Issue by Pumkindeer346** [LunaPixelStudios/Better-MC#1714]
### Describe the Bug

Lack of recipe book when in my inentory

### Screenshots and Videos

<img width="529" alt="Screenshot 2024-06-18 at 5 59 50 PM" src="https://github.com/LunaPixelStudios/Better-MC/assets/173207464/a0a6d457-d1a1-4d5b-9c6b-560fbba13809">

### Operating System

Mac 

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

Fabric BMC 2

**Comment by chorbintime** [comment]
this is intended. you can re-enable it in the recipeessentials mod config in the config folder
