### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sodz1aX** [LunaPixelStudios/Better-MC#1716]
### Describe the Bug

When Minecraft Is loading it crashes

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/SqZapLyp

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
reinstall on ATLauncher and update your GPU drivers
