### ISSUE TITLE
i don't know what to do!

### ISSUE THREAD

**Issue by Domghg** [LunaPixelStudios/Better-MC#1718]
### Describe the Bug

I recently downloaded better Minecraft but it's very laggy and I don't know what to do with that and I can't play And I love you better Minecraft i need help pls as fast as you can.
thanks
Domghg

### Reproduction Steps

1.i don't know i'm know to mincraft
2.
3.
...

### Screenshots and Videos

![why-are-you-here-adam](https://github.com/LunaPixelStudios/Better-MC/assets/173720470/34fc7fa6-33d5-472f-a1bf-4edf7804ce2a)

### Operating System

windows 10

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

1.16.5

### Other Mods

no

**Comment by chorbintime** [comment]
follow the https://rpg.prominence.wiki/performance-guide
