### ISSUE TITLE
Getting This Error When Starting A Server with BetterMC ServerPack

### ISSUE THREAD

**Issue by dermeister600** [LunaPixelStudios/Better-MC#1719]
### Describe the Bug

Hello, I am getting this error when I try to host a server. I think it's caused by RecipeManager but don't how to fix that.

### Reproduction Steps

1.  Tried running the server on my local and on my VPS.
2. Tried on Java 17 and Java 22 
3. 
...

### Screenshots and Videos

None

### Crash Report or Log

https://gist.github.com/dermeister600/738402b4e93df10100921767fd6f7062

### Operating System

Windows 11 (On Local) Windows Server R2 2012 (On VPS)

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

Nothing, only the BetterMC 1.20.1 Forge Modpack

**Comment by chorbintime** [comment]
mohist doesnt work, theres no reason to use plugins in the first place
