### ISSUE TITLE
The "A" and "D" keys do not work, and character is consistently sliding. 

### ISSUE THREAD

**Issue by WisterianDragon** [LunaPixelStudios/Better-MC#1720]
### Describe the Bug

I just downloaded BMC4 and as soon as I load into the game for the first time, without touching anything, my character is just sliding indefinitely to the right and I can't use "A" and "D". "W" and "S" both work fine. Same with all my other keys. So I close out the game and reopen it, same thing. I close out the game, open vanilla MC and everything works perfectly no issues. So I delete and redownload BMC4, make a new world and the same issue occurs. I try changing the key biding to strafe left and right and that still doesn't work so it isn't a binding issue. When I open a chest it stops, but then resumes when I exit it.  I've looked everywhere for an answerer and it seems like no one has had this specific problem. Its not my keyboard, its not MC, its not my computer. Its something in BMC4 specifically that is causing this but idk what. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V28

**Comment by chorbintime** [comment]
Did you add any extra mods?
How did you install the modpack, step by step?
Do you have a controller plugged in, alongside your keyboard? If so, disconnect the controller

**Comment by WisterianDragon** [comment]
Turns out my brother did in fact use my computer and used a controller and forgot to unplug it. I unplugged it and it is now working. Thank you.
