### ISSUE TITLE
Minecraft keeps crashing when at world border (Exit Code -805306369)

### ISSUE THREAD

**Issue by notVixu** [LunaPixelStudios/Better-MC#1721]
### Describe the Bug

I wanted to go to the world border. I used Shattered Dimensional Carver in the nether to travel faster and went to 4 milion blocks. I built a portal, went to overworld and came back to nether to get my waystone. After going through the portal back into the overworld, my game crashed and continues to crash after I close the game and restart my pc. I have 6GB of RAM allocated to Minecraft and even increasing it to 8GB doesn't change anything.

### Reproduction Steps

1. Use Shattered Dimensional Carver in the nether 4 times
2. Build a portal and go through it to the overworld world border
3. Go back to the nether and go to the overworld again
...

### Crash Report or Log

https://gist.github.com/notVixu/6524e173fba82f337c083c237473215e

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v27.5

**Comment by chorbintime** [comment]
Please follow the full [performance guide](https://rpg.prominence.wiki/performance-guide)
