### ISSUE TITLE
Mod content doesn't not appear in game.

### ISSUE THREAD

**Issue by Spectritus** [LunaPixelStudios/Better-MC#1722]
### Describe the Bug

When I play the modpack I don't have any of its content, just vanilla Minecraft.

### Reproduction Steps

1. Install Better MC
2. Play it (via the CurseForge app)
3. Create a world and you'll notice the mods aren't there.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
This is not a modpack issue. It's likely something you did wrong on your end, or something wrong with Curseforge Launcher.
Please do a fresh install on [ATLauncher](https://atlauncher.com/downloads) with no modifications to the modpack.
