### ISSUE TITLE
Stinger Spear is continuously falling and I can't pick it up

### ISSUE THREAD

**Issue by DougIsGaming** [LunaPixelStudios/Better-MC#1724]
### Describe the Bug

I through my stinger spear in the air and hit myself with it and then got paralyzed. After the effect was over, the spear fell to the ground and then teleported back to the point it hit me at, then it kept repeating this.
The spear still reacts to blocks be add or broken as well as water.

### Reproduction Steps

1. Threw the stinger with Neurotoxins 2 on it in the air
2. The Spear hit me and I received paralysis.
3. The teleported back to the point it hit me and fell to the ground
4. It teleported back to the point it hit me again and feel to the ground to again. This continued to happen.
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/173969457/4a129967-0a54-411a-b4df-adcc828e9c46

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by DougIsGaming** [comment]
I played on the world for a while after and left the game a few times and the spear is still there doing it's thing.

**Comment by chorbintime** [comment]
Report it to the developers of the mod that adds the item
