### ISSUE TITLE
Exit Code 6 on startup

### ISSUE THREAD

**Issue by Arno989** [LunaPixelStudios/Better-MC#1725]
### Describe the Bug

On game startup, game almost loads completely but crashes on Exit Code 6 at the end

Tried with 16Gb, 10Gb and 8Gb of RAM, no difference

Also tried using different versions of Java but from the crash log i presume the modpack uses an internal java installation

### Reproduction Steps

1. Install Game
2. Launch Game
3. Crash

### Crash Report or Log

https://pastebin.com/i80vB2N7

### Operating System

Garuda Linux x86_64, Linux 6.9.6-zen1-1-zen

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by Arno989** [comment]
I also attempted to play BMC2 [Fabric] v25, but same results

**Comment by chorbintime** [comment]
The pastebin expired. Please repost the file on Github Gist. Also, look for a file in the crash reports folder, or a file named "hs_err_pid"

**Comment by Arno989** [comment]
Apologies, i'm not familiar with pastebin
Here's the gist: https://gist.github.com/Arno989/c1998e67695fa81467d6e840cb93bf7d

**Comment by githubplanetarparrot** [comment]
I am experiencing the same issue on both Forge MC4 and Fabric MC2.

**Comment by chorbintime** [comment]
Remove the Sound Physics Remastered mod, and report this issue to the Sound Physics Remastered developer on their Github if this resolves the issue
