### ISSUE TITLE
Corundum not spawning nor in JEI menu

### ISSUE THREAD

**Issue by jarlokarlo** [LunaPixelStudios/Better-MC#1726]
### Describe the Bug

No corundum from quark mod spawns and i cant find it in the JEI menu

### Reproduction Steps

1. make a new world
2. look for corundum
3. not able to
4. search for corundum in jei
5. dont find :(
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/174136067/a07fb69d-7dae-4ba0-b0e4-6077b602b1e0)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by jarlokarlo** [comment]
it is in the game, i can spawn it using commands

**Comment by chorbintime** [comment]
its probably disabled in the Quark mod config
