### ISSUE TITLE
Error loading mods

### ISSUE THREAD

**Issue by Sodz1aX** [LunaPixelStudios/Better-MC#1727]
### Describe the Bug

![image](https://github.com/LunaPixelStudios/Better-MC/assets/105017966/17875519-1abd-4f10-8d24-176b0964300f)

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/CzyD1jm6

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
You need to provide the crash report:

Crash report saved to C:\Users\ociep\curseforge\minecraft\Instances\Better MC [FORGE] - BMC4\crash-reports\crash-2024-06-29_19.46.35-fml.txt
