### ISSUE TITLE
Better MC [Fabric] 1.20.1 v28 Crashing on World Load in macOS

### ISSUE THREAD

**Issue by Billyhnrjea** [LunaPixelStudios/Better-MC#1729]
### Describe the Bug

When attempting to load or create a new world within the modpack, the game crashes at the world loading screen. If you create a new world, the game acknowledges the creation and generates a "save file," but it still crashes when attempting to open the world.

### Reproduction Steps

1. Start BetterMC modpack/Minecraft
2. Select world save and/or create new world
3. Wait for Minecraft to crash on the next screen
...

### Crash Report or Log

https://gist.github.com/Billyhnrjea/69d7d53608065ed7dea820c321f58cd4

### Operating System

macOS Sonoma 14.4.1

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V28 BMC4

**Comment by chorbintime** [comment]
For Mac devices using Apple Silicon/arm (M1/M2/etc.) CPUs
There is an issue with Java 17.0.8 and newer where you may experience "A fatal error has been detected by the Java Runtime Environment", which can cause the Java runtime to crash under a variety of circumstances. To resolve this:
Install the Zulu JDK 17.0.1+12 arm64 build of Java:
Direct download: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=7eb8ee44-ab7f-4afb-9e42-32bd76416400 
Download/Install ATLauncher or Prism Launcher (CurseForge Launcher is known to cause issues)
In Instance settings > Java, manually specify the following Java path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
If using ATLauncher, Disable "Use Minecraft-bundled JDK"
Launch the game
