### ISSUE TITLE
Can't find infestations potions

### ISSUE THREAD

**Issue by RafaelDvbr27** [LunaPixelStudios/Better-MC#1731]
### Describe the Bug

Hello, I can't find the potion of infestation on better Minecraft. I need for a xp farm but I can't even on creative mode. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2024-06-30 135057](https://github.com/LunaPixelStudios/Better-MC/assets/174270120/5a787d67-399d-40b0-b084-3ee9b1ea4c86)
![Screenshot 2024-06-30 135011](https://github.com/LunaPixelStudios/Better-MC/assets/174270120/f0a6d26d-b462-47e4-9625-cf6d6f76b8c8)

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

enemyexpansion-2.3.1-forge-1.20.1
ironfurnaces-1.20.1-4.1.6
ironchest-1.20.1-14.4.4

**Comment by chorbintime** [comment]
potions of infestation dont exist lol

**Comment by YellowSmiley** [comment]
It is now? Why don't we have it now?

**Comment by chorbintime** [comment]
???

potions of infestation were added in 1.20.5 and bmc4 forge is a 1.20.1 modpack. we dont use the vanilla backport mod because we want to keep those features for our 1.21.1 modpacks. if you want to use the potion of infestation then play on BMC5 Neoforge or BMC3 Fabric

**Comment by YellowSmiley** [comment]
Thanks for clarifying ❤️
