### ISSUE TITLE
Eden Ring Reforked not updated

### ISSUE THREAD

**Issue by facudom** [LunaPixelStudios/Better-MC#1732]
### Describe the Bug

The mod is not updated. The latest version was released on June 5th. Manually updating it fixes the issue. With the stock mod you cannot access the dimention

The mod is not updated. The latest version was released on June 5th. Manually updating it fixes the issue. With the stock mod you cannot access the dimention

### Reproduction Steps

1.Create the portal
2.Enter the portal
3.Game crashes

To fix it, just update the mod

### Screenshots and Videos

None

### Crash Report or Log

None

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

Eden Ring Reforked
https://www.curseforge.com/minecraft/mc-mods/eden-ring-reforked/download/5400208

**Comment by chorbintime** [comment]
we're aware, it'll be updated in the next modpack version
