### ISSUE TITLE
Crashing right before getting to main menu Arch Linux

### ISSUE THREAD

**Issue by sorcracker63** [LunaPixelStudios/Better-MC#1733]
### Describe the Bug

I downloaded BMC4 from the CurseForge launcher like I would normally. I then launched it and it crashed right before I would get to the main menu screen. After a bit of research and a little help from Google Gemini, I found the issue. It was the libopenal.so library that was the issue. It is responsible for the sound engine. I deleted the Sound Physics mod from the mod folder, and the game launched perfectly. I am not sure why this issue is caused, but it can at least help for v29.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://docs.google.com/document/d/1EmU3inVHs-cKc66vc_p3CQMcWSFZxz400XnGnAwzPjg/edit?usp=sharing

### Operating System

Arch Linux

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by githubplanetarparrot** [comment]
THANK YOU!!
I had the same issue on Mint! Disabling the mod in the MultiMC menu fixed it.

**Comment by inverse** [comment]
Worked for me too! Thanks!

**Comment by chorbintime** [comment]
Please report this to the Sound Physics Remastered developers

**Comment by sorcracker63** [comment]
I did not bother reporting the issue to the Sound Physics Remastered developers as it already has been reported. Possible solutions are included in the thread. https://github.com/henkelmax/sound-physics-remastered/issues/199
