### ISSUE TITLE
BMC wont load into main menu and crashes with ending code -1

### ISSUE THREAD

**Issue by PPPatrik** [LunaPixelStudios/Better-MC#1735]
### Describe the Bug

I press play and the modpack starts loading up all the mods and when the screen switches to minecraft loading screen it crashes when the loading bar is at the end. After it crashes it gives me the ending code of -1

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![screenshot](https://github.com/LunaPixelStudios/Better-MC/assets/63549094/647c5706-606b-44f1-bf7c-edd97644b390)

### Crash Report or Log

https://pastebin.com/DVpCuXEq

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
remove the controllable mod, will be fixed in v29
