### ISSUE TITLE
inventory item on my screen

### ISSUE THREAD

**Issue by Zolboo126** [LunaPixelStudios/Better-MC#1736]
### Describe the Bug

i died and i pick my item i close my inventory but i still see my itmes

### Reproduction Steps

1.idk
2.
3.
...

### Screenshots and Videos

kk

### Crash Report or Log

just sees my item

### Operating System

windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

1.19.2

**Comment by chorbintime** [comment]
press i on your keyboard
