### ISSUE TITLE
BYG Nether Config does not effect nether biome generation 

### ISSUE THREAD

**Issue by RealR053** [LunaPixelStudios/Better-MC#1738]
### Describe the Bug

I am trying to edit the nether biomes for BYG but changing the biomeWeights for each biome does nothing. I have even tried giving a weight of 0 to all BYG nether biomes but nothing has changed. I am creating a new world each time I test this and I am not sure what I am doing wrong, is there another mod that handles the BYG biome generation that I am missing? I am on a fresh install of Better MC (BMC1)

### Reproduction Steps

1. Locate config file and enter byg folder, followed by nether-biomes json
2. Change any of the biomeWeights of byg biomes and launch game (I set them all to 0 to notice all biomes are still present)

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/47960112/43789074-10ee-46b1-8048-eab303da2ea2)
![image](https://github.com/LunaPixelStudios/Better-MC/assets/47960112/f96a2007-c0c1-4572-9322-66d11ec22d1d)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Fabric

### Modpack Version

v20

**Comment by chorbintime** [comment]
report this to the BYG devs, as we can't really fix this & its not a config file we provide or anything
