### ISSUE TITLE
internal exception java.net.socketexception connection reset

### ISSUE THREAD

**Issue by Fishpeeli** [LunaPixelStudios/Better-MC#1739]
### Describe the Bug

Me and my friend were just playing on his world through lan, and the world is already around a week old and it worked without any issues but for 3 days straight when we are playing I keep getting this error, we both tried everything we could to fix it like resetting our IPs etc. but it's still happening, it also happened earlier ocassionaly but not for that long and we have no idea how we can fix it, I tried downloading the server pack which I don't know what really does but it said that I'm missing some manifest file, I'm making this ticket because we can't enjoy playing the modpack together anymore and we don't know what to do

### Reproduction Steps

1. Share to lan (friend)
2. Joining the world through lan
3. playing for around 3-5 minutes
4. Everything freezing and internal exception java.net.socketexception connection reset popping up after disconnecting me.

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/167317161/7e0e9e06-56fc-4818-bbd2-7b6a1bdc303a
![2024-07-08_17 07 01](https://github.com/LunaPixelStudios/Better-MC/assets/167317161/e3aa5f87-5828-46e0-a11b-78e8cca93e51)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

Alex's caves,Alex's caves: stuff & torpedoes, advancement plaques, creeper overhaul, enderman overhaul, Bosses of mass destruction (fabric), better nether (fabric), choicetheorem's overhauled village, sophisticated backpacks, dragonloot (fabric), gravestone mod, regions unexplored (about fabric mods, the synitra connector is present)

**Comment by chorbintime** [comment]
Just selfhost a server normally using the serverpack files on the modpack's Curseforge page. We don't offer support for LAN, and this is a LAN issue
