### ISSUE TITLE
Iron gloms can float 

### ISSUE THREAD

**Issue by Likeabosslinc** [LunaPixelStudios/Better-MC#1741]
### Describe the Bug

When iron gloms are in lava  they can swim which is a mechanic that does not happen in regular mc

### Reproduction Steps

1.make a 3x3 hole place signs and then lava on top instead of iron goms sinking they float
2.
3.

### Crash Report or Log

None

### Operating System

Win 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V28-V26

**Comment by Likeabosslinc** [comment]
I’ve only tested from versions 26-28 it’s present on both

**Comment by chorbintime** [comment]
theres a million mods that could be causing this, and its not really in scope for us to fix. its a minor vanilla parity issue. 

my only idea is that Radium could be causing it but that seems really unlikely
