### ISSUE TITLE
Tree chopper mod not working

### ISSUE THREAD

**Issue by Brittbatt101** [LunaPixelStudios/Better-MC#1743]
### Describe the Bug

Supposed to chop tree from bottom blocks, having to mine tree manually 

### Reproduction Steps

1.using axe to chop tree
2.chopping from the bottom 
3.making sure to only chop small/skinny trees
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

Bmc4

**Comment by chorbintime** [comment]
you need an axe in your hand, and need to be standing up while mining. do not crouch
