### ISSUE TITLE
Server Pause Menu Button Overlap (16:10 aspect ratio -- GUI Scale: Auto)

### ISSUE THREAD

**Issue by emorrow1** [LunaPixelStudios/Better-MC#1744]
### Describe the Bug

I can't for the life of me figure out if this is just my server, but after reinstallations of the modpack via Curseforge on the client side & the server side, the problem persists. I can't find which part of the code is causing this small bug, so I have come here. For context, I have a 4K 16:10 aspect ratio monitor and I have my GUI scale (in video settings) set to "Auto". If a manipulate the aspect ratio manually (lower the scale), the "Player Reporting" button moves in the positive direction on the Y-axis. The first screenshot is when the GUI scale is set to auto and the second is when it's set to 5x. I did not include other screenshots, but lowering the GUI scale causes the "Player Reporting" button to move up higher. Not sure if this is only with my aspect ratio.
My first thought is that specific button is not locked in place with the others.

### Reproduction Steps

1. Open v28 of BetterMC4 and connect to a public server with a 16:10 monitor and a GUI scale set at Auto
2. Once connected, press ESC to open the pause menu
3. Notice the button overlap between "Disconnect"

### Screenshots and Videos

![Screenshot 2024-07-11 232202](https://github.com/user-attachments/assets/87d00e65-2e61-43b1-b6fe-37c8849affc0)
![Screenshot 2024-07-11 233450](https://github.com/user-attachments/assets/45004a63-9a04-45b7-a3e6-168b64fc8c03)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by Likeabosslinc** [comment]
It’s not just u happening to me too but tbh it’s not that big of a deal

**Comment by emorrow1** [comment]
> It’s not just u happening to me too but tbh it’s not that big of a deal

Perhaps not a big deal to many, but a bug is a bug and it hinders functionality that may be important to a small few.

**Comment by chorbintime** [comment]
will try to fix next update - fancymenu is really finicky about this so its difficult
