### ISSUE TITLE
Game crash with error 6

### ISSUE THREAD

**Issue by Omiikcron** [LunaPixelStudios/Better-MC#1745]
### Describe the Bug

When i launch the game it load the modpack, show the Mojang loading screen then crash at the very end of it.
Then the launcher warn me that the game crash with error 6.

### Reproduction Steps

1. Install the modpack via Forge
2. Launch it
3. On the minecraft launcher press play
4. Wait for it to load and crash

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/dade3f90-11b9-46e2-8438-ff2aa45f6247)

### Crash Report or Log

https://gist.github.com/Omiikcron/1403c7c8cf71d5ceba6188e58bad36b4

### Operating System

Pop!_OS 22.04 LTS

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

None

**Comment by chorbintime** [comment]
Two options:
 Download the latest OpenAL library files from your distros official repositories.
Add -Dorg.lwjgl.openal.libname=/usr/lib/libopenal.so (this path might be different depending on your distribution so please double check).


or, update the Sound Physics Remastered mod. If no update is available or it doesn't resolve the issue, then remove the Sound Physics Remastered mod and report this issue to the mod developer.
