### ISSUE TITLE
Trying to run on Linux results in error

### ISSUE THREAD

**Issue by marvin1099** [LunaPixelStudios/Better-MC#1747]
### Describe the Bug

I tried installing the modpack better mc 4 on the prism launcher 
and after trying to run on my linux box with openjdk 17 it prints: 
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGFPE (0x8) at pc=0x0000768c3049fb4d, pid=59249, tid=60501
#
# JRE version: OpenJDK Runtime Environment (17.0.11+9) (build 17.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM (17.0.11+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libopenal.so+0x9fb4d]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /mnt/Standart-Festplatte/Program Files/MultiMC/instances/1.20.1 BMC4/minecraft/core.59249)
#
# An error report file with more information is saved as:
# /mnt/Standart-Festplatte/Program Files/MultiMC/instances/1.20.1 BMC4/minecraft/hs_err_pid59249.log
[thread 59250 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Process crashed with exitcode 6.
```
The full log and error is in the log files

### Reproduction Steps

1. Install the modpack
2. Run the modpack
3. Minecraft opens
4. I thinks it gets to the loading screen just before the main menu should appear
5. Then it crashes (see the log files)  

### Crash Report or Log

[bmc4-cli-error.log](https://github.com/user-attachments/files/16201482/bmc4-cli-error.log) and [hs_err_pid59249.log](https://github.com/user-attachments/files/16201483/hs_err_pid59249.log)

### Operating System

Garuda Linux

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
Two options:
1. Download the latest OpenAL library files from your distros official repositories.
Add -Dorg.lwjgl.openal.libname=/usr/lib/libopenal.so (this path might be different depending on your distribution so please double check).

2. Update the Sound Physics Remastered mod. If the issue persists or no update is available, remove the Sound Physics Remastered mod and report this issue to the mod author.

**Comment by marvin1099** [comment]
Yep adding that as java argument worked, thanks.

**Comment by SimplyCEO** [comment]
Both options worked, thank you. @chorbintime

**Comment by L0g123** [comment]
@chorbintime i've been looking for a solution for so long thank you so so much!
