### ISSUE TITLE
Ender Dragon did not spawn

### ISSUE THREAD

**Issue by UnnoticedLEGACY** [LunaPixelStudios/Better-MC#1748]
### Describe the Bug

When we entered the End to fight the dragon for the first time the game crashed. When we all loaded back in the dragon did not spawn. We are using "Better MC [FORGE] 1.20.1 v28.zip" 

We are not versed in mods that much so we don't have a lot of experience to fix most likely a simple issue.

### Reproduction Steps

1. Loaded into End Dimension
2. Instantly Crashed
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
please send logs from the crash
