### ISSUE TITLE
Can someone please tell me how I could get it to work with Essential Mod?

### ISSUE THREAD

**Issue by dribyelir** [LunaPixelStudios/Better-MC#1749]

**Comment by chorbintime** [comment]
The Essential mod is completely incompatible with all of our modpacks, and there's no reason to use it. All of our modpacks already come with built-in, free world hosting, by clicking the "Share World' button in the Open to LAN menu. You can properly host a server using the free serverpack files we provide on the modpack's Curseforge page for better performance and more flexibility. Read the "README" file in the serverpack for more information. In modpacks that aren't owned by us, you can use mods such as e4mc or WorldHost to host a server completely for free without Essential's many issues and crashes and the microtransactions that they constantly bother users with. To learn more about alternatives to the Essential mod, check out [this website](<https://notessential.blurryface.xyz/>).
