### ISSUE TITLE
Crash when opening world. Singleplayer. New to modding.

### ISSUE THREAD

**Issue by anvpineau** [LunaPixelStudios/Better-MC#1750]
### Describe the Bug

I'm new to modding minecraft, so it might be something simple. I've downloaded the modpack from the curseforge launcher and it works until I spawn into a world. I barely have time to look around before the screen freeze for a few minutes and then crash. I've also tried to launch from the ATlauncher and the same thing happened. I believe it might be a compatibility issue as, when I go into data pack, several packs are red and labeled incompatible and intended for an older minecraft version. I've no idea how to launch the modpack into an older version of minecraft however.
[ReportLog.txt](https://github.com/user-attachments/files/16228917/ReportLog.txt)

### Reproduction Steps

1.Install modpack
2.Launch the game.
3.Create a new world in singleplayer
4.Enter world, try to play, then game freeze and crash.
...

### Operating System

Windows 11 Home

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

None

**Comment by chorbintime** [comment]
Do not touch anything in the datapacks screen please. The "errors" present there are not relevant to any kind of issue you may be experiencing, and are not of any concern. 

You appear to have outdated drivers. Updating them will likely fix this issue.

**1. Identify your graphics card**
_if you already know skip to the next step_
- Open task manager
- Navigate to the "Performance" tab (on Windows 11 this is the button that looks like a heart pulse)
- Press the GPU 0 graph and read your GPU from the top right

**Note:**
*In some cases you may see a GPU 0 and GPU 1. This means your CPU has its own GPU, as well as a dedicated one. You probably want GPU 1 (which is usually the better one), but you can ask staff to clarify if necessary.*

**2. Download your drivers from the manufacturers site**
Depending on what you read before, you likely need drivers from either AMD, Intel, or NVIDIA

**AMD**: <https://www.amd.com/en/support> 
**Intel**: <https://www.intel.com/content/www/us/en/download-center/home.html> 
**NVIDIA**: <https://www.nvidia.com/Download/index.aspx?lang=en-us> 

**Note:**
- *For NVIDIA you want to select "Game Ready Driver (GRD)" (this is the default option) for the best performance. Once installing you'd probably prefer downloading GeForce Experience, which will notify you when there's an available drivers update.*
- *For Intel, you probably want to press "Get Started" under the "Automatically update your drivers and software", which will simplify the process and update everything automatically*
- *For AMD you probably want to just press "Download Windows Drivers", which will download something called AMD Adrenaline, which will update your drivers automatically.*

**3. Run the installation, restart your computer, and try playing MC again**
- At this point, hopefully your Minecraft is running. If it still does not work, please post any new logs and staff will help assist you with finding the right solution.
