### ISSUE TITLE
Inventory is still showing

### ISSUE THREAD

**Issue by Oelipoeli** [LunaPixelStudios/Better-MC#1752]
### Describe the Bug

![Unbenannt](https://github.com/user-attachments/assets/5fe546d9-e083-4e80-bbd5-a90e4dcf4352)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

I've tried to turn off every single ressource-pack and shader - still there

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

BMC3 - Its 1.21. !

**Comment by chorbintime** [comment]
press i on your keyboard

**Comment by Oelipoeli** [comment]
just tried it - still there

**Comment by chorbintime** [comment]
how did you install the modpack
