### ISSUE TITLE
Crafting table lag

### ISSUE THREAD

**Issue by thatdudeaustin** [LunaPixelStudios/Better-MC#1753]
### Describe the Bug

When crafting certain items or upon entering crafting table I get a lag spike that lasts 15-30 seconds

### Reproduction Steps

1. Enter crafting table
2. Immediate lag sometimes. Hitting "show only craftable items" also causes lag spike. 
3. Waiting 15-30 sec before exiting table
...

### Crash Report or Log

https://spark.lucko.me/UZIua0iFIf

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

BMC2 Fabric. v25 (Modloader 0.15.11)

**Comment by mightyaussie** [comment]
having this same issue

**Comment by wunimal** [comment]
having same issue

**Comment by chorbintime** [comment]
Please follow the [performance guide](https://rpg.prominence.wiki/performance-guide)
