### ISSUE TITLE
crafting table lagging or crashing game BMC2

### ISSUE THREAD

**Issue by wunimal** [LunaPixelStudios/Better-MC#1754]
### Describe the Bug

When I open a crafting table It will sometimes severely lag my game or crash it altogether often after I switch between craftable and all items preview. My task manager shows nothing wrong and I've ran a spark profile but i don't know what to do with this information. after initiation bug will stick around for 10-20 minutes before going away. Spamming buttons while in lag state will induce a full crash 

### Reproduction Steps

1. Open crafting table
2. switch between craftable and non craftable recipe's 
3.  If no bug activation try again
...

### Crash Report or Log

-805306369

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

### Other Mods

no additional

**Comment by chorbintime** [comment]
Please follow the [performance guide](https://rpg.prominence.wiki/performance-guide)
