### ISSUE TITLE
Quark config conflicts with Serene Seasons changing colour feature (BMC4)

### ISSUE THREAD

**Issue by stubkan** [LunaPixelStudios/Better-MC#1755]
### Describe the Bug

Quark config conflicts with Serene Seasons changing season colours feature which means players likely never got to see the biome colours change over the seasons.

From the Serene Seasons FAQ, https://github.com/Glitchfiend/SereneSeasons/wiki/FAQs: 

>Q: Why aren't my grass/foliage colors changing?
A: If you're using OptiFine, you must make sure the "Swamp Colors" option is enabled, or colors will not change with vanilla blocks. The Custom Colors option can also conflict when using a texture pack. Additionally, if you are using Quark, the Greener Grass option may conflict with Serene Seasons, and should be disabled.

The default and defaultconfig Quark config file, quark-common.toml, has the following value set :

>[client]
	"Greener Grass" = true

### Reproduction Steps

1.
2.
3.
...

### Operating System

Ubuntu

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
will be fixed in the next modpack update, thank you for the report!
