### ISSUE TITLE
FallingTree cannot be configured to use the inbuilt enchant without breaking the modpack (BMC4)

### ISSUE THREAD

**Issue by stubkan** [LunaPixelStudios/Better-MC#1756]
### Describe the Bug

FallingTree, by default uses no enchants - so all axes can use the tree instamining ability by default, or not at all.  If the server owner wishes to balance this feature by placing it behind an enchantment requirement - and switching on, in the server config:

It is configured via fallingtree.json in the config folder;

>  "enchantment": {
    "registerEnchant": false,
    "registerSpecificEnchant": false,
    "hideEnchant": false,
    "requireEnchantment": true
    
Because I do not wish all axes to instamine trees, and want to instead, 'balance' it to be more vanilla by placing this ability behind an enchantment - I tried changing "registerEnchant" to true, and "registerSpecificEnchant" to true, both break compatibility by causing the client and server mods to be different.  Presumably, by causing the server to have the enchant registered, and the client not having it registered.

![2024-07-09_19 58 40](https://github.com/user-attachments/assets/d345352a-2bcf-4268-9eb7-210a3fbc5db0)

It appears the only way to 'balance' this mod is to disable the FallingTree function instead, by having "requireEnchantment" being true.  I am therefore going to use an alternative datapack to add FallingTree instamining enchantments.

According to the Fallingtree mod page:  any attempt to modify the FallingTree mods enchantments (and change of speeds, apparently) cannot only be server-side but also client-side;

>"NOTE: On servers this mod can be server-side only, client isn't required (except if you use the change speed feature and/or enchants configurations)."

It is a known problem that both the server and client must match - https://github.com/RakambdaOrg/FallingTree/issues/360

THOUGHTS:

I think this FallingTree mod should be preconfigured to require enchantments, and not be on all axes by default - as this is non-vanilla and unbalanced

Or an alternative: use a different mod or version of FallingTree that allows the server owner the choice to balance it to their discretion

### Operating System

Ubuntu

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
I mean, if you want to gate fallingtree behind an enchantment, you'd be better off disabling the mod entirely.

There is already a vein mining enchantment, so there wouldn't be any reason for people to choose a fallingtree enchant over normal vein mining. It's like if there was an enchant in the game called "Worse Sharpness" thats just sharpness but worse. It ends up becoming more of an annoyance than anything that benefits players or balance.
