### ISSUE TITLE
Large Biomes worldgen is disabled for servers due to BCLib bug

### ISSUE THREAD

**Issue by stubkan** [LunaPixelStudios/Better-MC#1757]
### Describe the Bug

If a BetterMC server owner wishes to make their worlds use Large Biomes - they cannot set it normally.  There are two barriers to this.

**Bug One.** 

There is no documentation on how to enable large biome generation, ie no one knows what is the correct biome label term to place under your server.properties file under "level-type"

Online documentation seems to not answer this question, and questions asked about this over the years on the official discord have gone unanswered.

The answer: it is "level-type=bclib\:large"

The ability for the generation engine is definitely there - as when the player creates a world in single player, they can set the world generation to be bclip BetterX type with Large Biomes enabled.  The way to get this to properly be enabled on a server world is to transplant the level.dat generated with a single player world into the server world folder, and then let it generate.  

But this does not seem to actually work, the worlds generated do not seem to actually be Large Biomes.

**Bug Two**

There is a bug in bclip that force overwrites world generation values in level.dat with Normal biome values.

The bug is documented in this issue - that arose out of a server owner struggling to set his biomes to Large; 

https://github.com/quiqueck/BCLib/issues/135

I was only able to make my server world generate Large Biomes by creating a datapack that forced all world generation values for Normal to be Large Biome values instead - so then bclip overwrites the level.dat values with Normal generation values that have been pre-set to Large instead on each server world startup.

Here is the datapack that fixes the BCLib bug, to allow world generation to be Large Biomes properly:

[fix-bclib-end-gen-pack.zip](https://github.com/user-attachments/files/16346112/fix-bclib-end-gen-pack.zip)

BCLib devs have said they will fix it in the 'next version', however the dev seems to have potentially misunderstood the bug; as they say;

>[quiqueck](https://github.com/quiqueck) commented [on Dec 20, 2023](https://github.com/quiqueck/BCLib/issues/135#issuecomment-1864626341)
>Yes, the next major update to BCLib will address those configuration issues.

>You could als use the bclib:large world-type (in your server.properties) That combines the vanilla large biomes settings with changed biome sizes for the nether/end.

To get around the bug, they say to use the bclip:large world generation in server.properties file, however this bug is one that disables that specific option because it force overwrites the level.dat - And it has been 6 months since, with no fix yet - so I dont know if updating the BCLib library will have the fix.

But some documentation and datapack/level.dat fixes could be provided for server owners to be informed about their customization options at least. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

Here is a screenshot of the End map with Large Biomes selected in the level.dat, yet it does not generate Large Biomes properly.

![2024-07-08_14 19 50](https://github.com/user-attachments/assets/f0ee4d12-d2aa-4810-b2a2-ee0a76946581)

Here is a screenshot of the same End area, but after the BCLib datapack fix is placed in the world/datapack folder to force Large Biomes to generate.

![2024-07-08_14 52 21](https://github.com/user-attachments/assets/4126a1a0-0d21-4f3e-9e20-337f6f2101a3)

### Operating System

Ubuntu

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
> ### Describe the Bug
> If a BetterMC server owner wishes to make their worlds use Large Biomes - they cannot set it normally. There are two barriers to this.
> 
> **Bug One.**
> 
> There is no documentation on how to enable large biome generation, ie no one knows what is the correct biome label term to place under your server.properties file under "level-type"
> 
> Online documentation seems to not answer this question, and questions asked about this over the years on the official discord have gone unanswered.
> 
> The answer: it is "level-type=bclib:large"
> 
> The ability for the generation engine is definitely there - as when the player creates a world in single player, they can set the world generation to be bclip BetterX type with Large Biomes enabled. The way to get this to properly be enabled on a server world is to transplant the level.dat generated with a single player world into the server world folder, and then let it generate.
> 
> But this does not seem to actually work, the worlds generated do not seem to actually be Large Biomes.
> 
> **Bug Two**
> 
> There is a bug in bclip that force overwrites world generation values in level.dat with Normal biome values.
> 
> The bug is documented in this issue - that arose out of a server owner struggling to set his biomes to Large;
> 
> [quiqueck/BCLib#135](https://github.com/quiqueck/BCLib/issues/135)
> 
> I was only able to make my server world generate Large Biomes by creating a datapack that forced all world generation values for Normal to be Large Biome values instead - so then bclip overwrites the level.dat values with Normal generation values that have been pre-set to Large instead on each server world startup.
> 
> Here is the datapack that fixes the BCLib bug, to allow world generation to be Large Biomes properly:
> 
> [fix-bclib-end-gen-pack.zip](https://github.com/user-attachments/files/16346112/fix-bclib-end-gen-pack.zip)
> 
> BCLib devs have said they will fix it in the 'next version', however the dev seems to have potentially misunderstood the bug; as they say;
> 
> > [quiqueck](https://github.com/quiqueck) commented [on Dec 20, 2023](https://github.com/quiqueck/BCLib/issues/135#issuecomment-1864626341)
> > Yes, the next major update to BCLib will address those configuration issues.
> 
> > You could als use the bclib:large world-type (in your server.properties) That combines the vanilla large biomes settings with changed biome sizes for the nether/end.
> 
> To get around the bug, they say to use the bclip:large world generation in server.properties file, however this bug is one that disables that specific option because it force overwrites the level.dat - And it has been 6 months since, with no fix yet - so I dont know if updating the BCLib library will have the fix.
> 
> But some documentation and datapack/level.dat fixes could be provided for server owners to be informed about their customization options at least.
> 
> ### Reproduction Steps
> 
> ...
> 
> ### Screenshots and Videos
> Here is a screenshot of the End map with Large Biomes selected in the level.dat, yet it does not generate Large Biomes properly.
> 
> ![2024-07-08_14 19 50](https://private-user-images.githubusercontent.com/34361592/351255589-f0ee4d12-d2aa-4810-b2a2-ee0a76946581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzQxMTQsIm5iZiI6MTcyMTczMzgxNCwicGF0aCI6Ii8zNDM2MTU5Mi8zNTEyNTU1ODktZjBlZTRkMTItZDJhYS00ODEwLWIyYTItZWUwYTc2OTQ2NTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDExMjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmM2IzNjM1M2NjMWI4MGYxOTZmNzFmM2U1YWIzNmRjZjgwYjFhNTBkNjljYzliZWYwMDA4MTBiN2FhYmU1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XBWwqymCu20P_VR6_DpKnEH9pdCjdkWtWj8M5-OwjJc)
> 
> Here is a screenshot of the same End area, but after the BCLib datapack fix is placed in the world/datapack folder to force Large Biomes to generate.
> 
> ![2024-07-08_14 52 21](https://private-user-images.githubusercontent.com/34361592/351255525-4126a1a0-0d21-4f3e-9e20-337f6f2101a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzQxMTQsIm5iZiI6MTcyMTczMzgxNCwicGF0aCI6Ii8zNDM2MTU5Mi8zNTEyNTU1MjUtNDEyNmExYTAtMGQyMS00ZjNlLTllMjAtMzM3ZjZmMjEwMWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDExMjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1M2M4NDAzMWFmMThiMmE0NjRmMGViNzljMDc3NjJkMzY5MWY1Yjk0NzBkZjI2MjA4OGNhNGZlMzM4YWJhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jpZBgV4NoB8Fo7F3BA3E7LhGeIzVTBl-eDhsL352rVw)
> 
> ### Crash Report or Log
> _No response_
> 
> ### Operating System
> Ubuntu
> 
> ### Minecraft Version
> 1.20.1
> 
> ### Modloader
> Forge
> 
> ### Modpack Version
> v28
> 
> ### Other Mods
> _No response_

Does this datapack only work when large biomes is selected, or is it more of a "only-use-if-you-want-large-biomes" thing?



> @chorbintime
> 
> I have been documenting all the bmc4 mods and going through the configs, as Im setting up a server - so I have kind of a long list of things. Would it still be ideal to make github issues for them, or do this in some other way?

I appreciate it a lot! You can add me on Discord @chorb.txt if you'd like faster responses.

**Comment by stubkan** [comment]
> Does this datapack only work when large biomes is selected, or is it more of a "only-use-if-you-want-large-biomes" thing?

As the BCLib bug causes only "normal" biome size to be used no matter what - the datapack adjusts the normal biome into a Large Biome, so it would be an only-use-if-you-want-large-biomes datapack.  If, for instance - amplified was desired, that would need a different datapack patch.

**Comment by chorbintime** [comment]
I see - if you have any Java experience & end up making a mod for this which only activates the datapack when large is chosen, we'll use it in our modpacks & I'm sure many others will too! Other than that, I'll make sure to let people know if they run into the same issue. Thanks!
