### ISSUE TITLE
Distant Horizons Compatiblity

### ISSUE THREAD

**Issue by Elite911** [LunaPixelStudios/Better-MC#1759]
Is there a way to make Distant Horizons work with this mod pack? https://www.curseforge.com/minecraft/mc-mods/distant-horizons

Every time I join either MP server or singleplayer the game crashes. Maybe one of the mods is crashing the game?

My log is attached.
[message.txt](https://github.com/user-attachments/files/16369579/message.txt)

**Comment by chorbintime** [comment]
Distant Horizons is only confirmed to work on BMC2 Fabric. I have no clue what causes it to not work on BMC4 Forge as none of the logs I've seen have any info, and I have no reason to debug this as it's not our responsibility to maintain mods that other people add to the modpack themselves.
