### ISSUE TITLE
Enter Eden Ring dimension

### ISSUE THREAD

**Issue by BrewenLePage** [LunaPixelStudios/Better-MC#1763]
### Describe the Bug

On a server host on Aternos. When we try to go in the dimension the game crashed with "Cannot read field 'settings' because 'biome' is null"
It works in solo game.

### Reproduction Steps

1.Have a server
2.Try to go in Eden ring dimension
3.
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/b9551df3-6f16-4475-ba11-f422b4c5fae9)

### Crash Report or Log

https://pastebin.com/zEaKcnUU

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

V25

### Other Mods

_No_

**Comment by chorbintime** [comment]
update the eden ring reforked mod
