### ISSUE TITLE
tool dont show up or moved down in hand

### ISSUE THREAD

**Issue by xXBeniXx105** [LunaPixelStudios/Better-MC#1764]
### Describe the Bug

Tools like pickaxes, axes, shovels, and hoes don't show up in hand after I break one block with them.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

Better MC [Fabric] - BMC3

**Comment by chorbintime** [comment]
fixed in v3.5

**Comment by xXBeniXx105** [comment]
Thanks. Is there a way to install that version on CurseForge, or do I need to wait until it gets updated there?

**Comment by chorbintime** [comment]
just click "Change Version" in the Curseforge launcher and switch to v3.5. you dont need to do anything else
