### ISSUE TITLE
The Eye Shrine

### ISSUE THREAD

**Issue by lorddodo02** [LunaPixelStudios/Better-MC#1766]
### Describe the Bug

I cannot summon The Eye. When i try to summon through the shrine, Dragon Egg breaks and The Eye appears for a moment and then disappears

### Reproduction Steps

1. Build The Eye Shrine
2.
3.
...

### Screenshots and Videos

https://github.com/user-attachments/assets/b15c2c5a-7114-40c0-a923-fc5e166e1d7d

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.20.1 v25

**Comment by chorbintime** [comment]
update betterend and bclib - if no update is available or the issue is unfixed then please report the issue to the betterend mod author
