### ISSUE TITLE
Stuck on Loading Terrain

### ISSUE THREAD

**Issue by 4saN1337** [LunaPixelStudios/Better-MC#1767]
### Describe the Bug

When i try to enter a server I get stuck on Loading terrain like forever.

### Crash Report or Log

https://paste.ee/d/PqJ9o

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v20

**Comment by chorbintime** [comment]
how is the server hosted?

how did you install clientside?
