### ISSUE TITLE
Having trouble with server pack BMC4_FORGE_1.20.1_Server_Pack_v28

### ISSUE THREAD

**Issue by BrilliantIsotope** [LunaPixelStudios/Better-MC#1768]
### Describe the Bug

Downloaded Better MC [FORGE] - BMC4 1.20.1 v28 and BMC4_FORGE_1.20.1_Server_Pack_v28. 
But when trying to join server it kicks out saying server is missing mods. Tried copying the client mods over to the server mods folder and no change. Tried installing client on a different pc same issue. Redownloaded and installed server files.
Server mods directory 236 and client mods directory is 272

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2024-08-02 092223](https://github.com/user-attachments/assets/8292976b-6611-4cf8-be1e-362f6aae386f)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

None

**Comment by BrilliantIsotope** [comment]
Looking at logs

[09:40:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\garet\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.1\fmlcore-1.20.1-47.3.1.jar is missing mods.toml file
[09:40:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\garet\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.1\javafmllanguage-1.20.1-47.3.1.jar is missing mods.toml file
[09:40:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\garet\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.1\lowcodelanguage-1.20.1-47.3.1.jar is missing mods.toml file
[09:40:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\garet\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.1\mclanguage-1.20.1-47.3.1.jar is missing mods.toml file

**Comment by chorbintime** [comment]
> ### Describe the Bug
> Downloaded Better MC [FORGE] - BMC4 1.20.1 v28 and BMC4_FORGE_1.20.1_Server_Pack_v28. But when trying to join server it kicks out saying server is missing mods. Tried copying the client mods over to the server mods folder and no change. Tried installing client on a different pc same issue. Redownloaded and installed server files. Server mods directory 236 and client mods directory is 272
> 
> ### Reproduction Steps
> 
> ...
> 
> ### Screenshots and Videos
> ![Screenshot 2024-08-02 092223](https://private-user-images.githubusercontent.com/173708227/354524727-8292976b-6611-4cf8-be1e-362f6aae386f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODA3NDQsIm5iZiI6MTcyMjY4MDQ0NCwicGF0aCI6Ii8xNzM3MDgyMjcvMzU0NTI0NzI3LTgyOTI5NzZiLTY2MTEtNGNmOC1iZTFlLTM2MmY2YWFlMzg2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxMDIwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDMxZjA1OWZhZDZkNzllZDM1ZDljMzFlZDIxNGY2N2JjN2NlN2U1ZTkyMGI5NzM4YmQwNzIxNDAxMGVlMTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V_wUIveNDagYWDxETEKyZ8kHg172PPoxmgqAa892QCI)
> 
> ### Crash Report or Log
> _No response_
> 
> ### Operating System
> Windows 11
> 
> ### Minecraft Version
> 1.20.1
> 
> ### Modloader
> Forge
> 
> ### Modpack Version
> v28
> 
> ### Other Mods
> None

You do not have the same modpack installed as the server.

Do not copy over files from your client to the server, nor the other way around. The serverpack only has the files that the serverpack needs, and the client pack only has the files that the client needs.

For installing a server, please read the [updated guide](https://github.com/chorbintime/LPS-readme/wiki/1.20.1).

For installing clientside, follow the steps below:
**1**. Go to <https://atlauncher.com/download> 
**2**. Install and run the setup, then open the program.
**3**. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
**4**. Go to the Packs tab on the right, then click "Curseforge" on the left.
**5**. Search the modpack you wish to download.
**6**. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
**7**. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
**8**. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.
This video explains the process: <https://youtu.be/xMYW1wMbmkM>

**Comment by chorbintime** [comment]
> Looking at logs
> 
> [09:40:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\garet\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.1\fmlcore-1.20.1-47.3.1.jar is missing mods.toml file [09:40:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\garet\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.1\javafmllanguage-1.20.1-47.3.1.jar is missing mods.toml file [09:40:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\garet\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.1\lowcodelanguage-1.20.1-47.3.1.jar is missing mods.toml file [09:40:55] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\garet\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.1\mclanguage-1.20.1-47.3.1.jar is missing mods.toml file

These errors are not relevant - nothing is wrong here. 99% of errors you see in a log are completely normal.
