### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by daliborstanek** [LunaPixelStudios/Better-MC#1769]
### Describe the Bug

Big Dripleaf is missing textures. Only the top is missing though, the vine that is underneath it is not missing. This only happens if the leaf is facing north.

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/1a2b9a2b-3eb4-4c6f-8b5b-271be37385e2)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

BMC4

**Comment by chorbintime** [comment]
Reinstall the modpack:
**1**. Go to <https://atlauncher.com/download> 
**2**. Install and run the setup, then open the program.
**3**. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
**4**. Go to the Packs tab on the right, then click "Curseforge" on the left.
**5**. Search the modpack you wish to download.
**6**. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
**7**. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
**8**. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.
This video explains the process: <https://youtu.be/xMYW1wMbmkM>
