### ISSUE TITLE
Text in minimap

### ISSUE THREAD

**Issue by YisusAdan20** [LunaPixelStudios/Better-MC#1770]
### Describe the Bug

Idk what happend. I´ve never use Java, but I follow the instructions in the CurseForge app, open it direct from there and I have this issue.
![Captura de pantalla 2024-08-02 190119](https://github.com/user-attachments/assets/21524f59-ed65-4272-a5fb-9f64cae23b10)

### Reproduction Steps

1.Open curseforge app
2.Play the game from it
3.It appears in the corner
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
Reinstall the modpack:
**1**. Go to <https://atlauncher.com/download> 
**2**. Install and run the setup, then open the program.
**3**. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
**4**. Go to the Packs tab on the right, then click "Curseforge" on the left.
**5**. Search the modpack you wish to download.
**6**. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
**7**. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
**8**. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.
This video explains the process: <https://youtu.be/xMYW1wMbmkM>
