### ISSUE TITLE
Cherry Blossom Tree Texture

### ISSUE THREAD

**Issue by MorophineHeart** [LunaPixelStudios/Better-MC#1771]
Cherry blossoms texture not loading properly, not sure if I'm doing something wrong or what, just want to know how to fix it. Haven't seen any other tree that does this either, tried changing settings, exiting and re-loading etc. 
![2024-08-03_22 52 12](https://github.com/user-attachments/assets/828c34e2-5b85-4914-9a19-1f99fe83289b)

**Comment by chorbintime** [comment]
put your graphics quality on fancy

**Comment by MorophineHeart** [comment]
> put your graphics quality on fancy
Awesome, tysm <3
