### ISSUE TITLE
v26 and v28 when I equipped an elytra it shift the click alignment

### ISSUE THREAD

**Issue by talmiior** [LunaPixelStudios/Better-MC#1772]
### Describe the Bug

Whenever I equip an elytra the click alignment shifts to the right by about three quarters of an inventory slot. This results in having to click further to the left to select an item. 

### Reproduction Steps

1. equip elytra using hand, or by drag dropping it or shift left clicking the elytra to where you usually put the elytra
2. Issue appears immediately
3.
...

### Screenshots and Videos

![2024-08-04_01 29 10](https://github.com/user-attachments/assets/943bf35c-20ad-439e-9f74-65dfdb2a6629)
![2024-08-04_01 29 20](https://github.com/user-attachments/assets/7987944e-7659-4043-95a0-a2c776cbcfbc)

https://github.com/user-attachments/assets/9759656b-3735-46ad-b753-e2d6ddbd1561

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28 also v26

**Comment by chorbintime** [comment]
update to v29.5
