### ISSUE TITLE
Game Crash in Twilight Forest

### ISSUE THREAD

**Issue by AkkiTheGamerFox** [LunaPixelStudios/Better-MC#1776]
### Describe the Bug

While I was walking around, the game crashed, and now the internal server crashes once attempting to reload the game. The Crashlogs are saying that the "BlockChainGoblin" and it's "SpikeBlock" entity is causing the issue.

### Reproduction Steps

1. Enter the Twilight Forest or Spawn the entity using a Spawn Egg
2. Upon rendering the mob, the game should crash

### Crash Report or Log

https://pastebin.com/2mYFyDMT

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

- Player Animator
- Better Combat
- Respawning Animals

**Comment by chorbintime** [comment]
update to v30, we offer no support for old versions
