### ISSUE TITLE
chest don't spawn in ender cityes and ships

### ISSUE THREAD

**Issue by Daix06** [LunaPixelStudios/Better-MC#1777]
when i reach a new ship or ender city there are no chest and the elitras are dropped in the floor. the other structures have chests

**Comment by chorbintime** [comment]
are you on v30.5

**Comment by StefAmeye** [comment]
I've done some testing, this seems to be an issue since v29, also the better end cities genration is not working properly

**Comment by roxxel** [comment]
Can confirm

**Comment by roxxel** [comment]
FIX:
Backup your world
Open modpack folder
Go to `defaultconfigs\paxi\datapacks` and remove ichphillip_endcity_...`
Go to `config\paxi\datapacks` and remove ichphillip_endcity_...`
this wont affect existing chunks but will work for new ones

**Comment by chorbintime** [comment]
will be fixed in the next update

**Comment by ofekn2010** [comment]
when is next update
