### ISSUE TITLE
Server Crash - Ubuntu - Modpack Version v28 - 1.20.1

### ISSUE THREAD

**Issue by Setting4988** [LunaPixelStudios/Better-MC#1778]
### Describe the Bug

Hi, if possible I need some help in resolving a server crash that recently occurred. I have filled out the support questions from the #get-support page:

1. What Minecraft version are you using? - 1.20.1
2. What launcher did you run Minecraft with? - CurseForge
3. Have you changed the modpack in any way? - No
4. What version of the modpack are you using? - v28
5. What version of the server pack are you using? -v28 and I am self hosting on Ubuntu.
6. Have you ever gotten past the crash condition without crashing, or does the game always crash? - The server crashed while playing, and now crashes consistently on start up before anyone can connect.
7. What steps cause the crash? - I'm not sure exactly but one player was 4000 blocks away while two others just went through the portal to the Aether. We have all been through previously, so this was not the first time the world was generated. Additionally, 4 out of the 5 players online at the time had a Dragon mount from the 'Dragon Mounts: Legacy' modpack. I say this as under the detailed walkthrough section of crash log shows 'Dragon Mounts: Legacy' as a suspected cause for the crash.

Thank you in advance.

### Reproduction Steps

1. Start the Server
2. Crash after 60 seconds before server is fully running.

### Crash Report or Log

https://pastebin.com/SUNyUwV0

### Operating System

Ubuntu

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

N/A

**Comment by chorbintime** [comment]
Update to v30.5. We offer no support for old versions

**Comment by Setting4988** [comment]
Updated to v30.5 and still crashed on startup. 

Turns out the crashes were due to the mod "Dragon Mounts: Legacy". I've since removed this mod from the server.
