### ISSUE TITLE
Ruby's Fire doesn't apply knockback or fire to swords

### ISSUE THREAD

**Issue by Miradden** [LunaPixelStudios/Better-MC#1779]
### Describe the Bug

I got a fireruby sword and noticed I wasn't getting any knockback or fire on swords when I hit something. I tried applying the Ruby's Fire enchant to a normal diamond sword and had the same problem. The enchant works as expected when applied to armor (mobs get set on fire and knocked away if I'm wearing Fireruby armor)

### Reproduction Steps

1. Get a Fireruby sword or any sword that has the Ruby's Fire enchantment
2. Hit something
...

### Operating System

Linux (NixOS)

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

### Other Mods

- Create

**Comment by chorbintime** [comment]
update the mod that adds the enchant/item - if the issue persists / no update is available, please report the issue to the mod author
