### ISSUE TITLE
Jellyshroom Vertical Slabs - You can walk through them

### ISSUE THREAD

**Issue by DeanGrey** [LunaPixelStudios/Better-MC#1781]
### Describe the Bug

I checked all of the other darker tinted jellyshroom items and none of them can be walked through, just the vertical slabs.

I am using the latest version 30.5 of bettermc and 1.20.1 of Minecraft. I am using ATLauncher. No additional mods are installed. It is fresh from a couple of days ago, including the ATLauncher install.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Fedora 40

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

30.5

**Comment by chorbintime** [comment]
what mod are the slabs from?

**Comment by DeanGrey** [comment]
> what mod are the slabs from?

Vertical slabs compat. I believe they original in better end.

**Comment by DeanGrey** [comment]
![Screenshot_20240809_235150](https://github.com/user-attachments/assets/6d219cad-47cd-4f88-829a-c0c527a48d9f)

**Comment by chorbintime** [comment]
reported to mod author - thank you for the report
