### ISSUE TITLE
Vertical planks don't have variants for vanilla wood types.

### ISSUE THREAD

**Issue by ChelloVibes** [LunaPixelStudios/Better-MC#1782]
### Describe the Bug

Vertical planks from added by Quark don't have variants for vanilla wood types, whereas Every Compat adds variants for every other wood type. The same also applies for bookshelves from Quark, although that isn't as much of a problem since Woodworks also adds bookshelves.

### Screenshots and Videos

Installed the mod on another instance and vanilla wood variants exist there.
![2024-08-10_12 43 50](https://github.com/user-attachments/assets/769b285a-7ee5-4b7b-8bb0-49738bed50e9)
![2024-08-10_12 51 57](https://github.com/user-attachments/assets/7ded9a61-8501-4640-8c5c-4e6715097d84)

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v20

**Comment by chorbintime** [comment]
the mod is just outdated as 1.19.2 bmc hasnt been updated in ages
