### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by six7n** [LunaPixelStudios/Better-MC#1784]
### Describe the Bug

Nether quests not registering, for example me and 2 other friends killed the 2 Nether Bosses that require nether starts to spawn and only 1 got the achievement both times while the other 2 didnt. 

### Reproduction Steps

1. Spawn boss
2. Kill it
3. Dont get rewarded for it.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

Better MC v30

### Other Mods

Goatman

**Comment by chorbintime** [comment]
"only 1 got the achievement both times while the other 2 didnt." do you mean achievement or quest?

**Comment by six7n** [comment]
I mean the quest for slaying the Ghast and also the Nether Keeper. We've killed it like like 4 times now and we still have not gotten the quest rewards. It has also happened with other stuff in the past but I don't remember. Some quests just dont register

**Comment by chorbintime** [comment]
it'll be fixed in the next modpack update, thanks
