### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by o-sonu** [LunaPixelStudios/Better-MC#1785]
### Describe the Bug

Today I went to continue my journey in the Eden dimension, but every time i try to load into my server it keeps crashing my game and i cant get in

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

### Other Mods

N/A

**Comment by chorbintime** [comment]
update the eden ring reforked mod
