### ISSUE TITLE
Browsing statistics causes massive FPS drop on servers

### ISSUE THREAD

**Issue by ChelloVibes** [LunaPixelStudios/Better-MC#1786]
### Describe the Bug

When first opening the statistics screen, everything works just fine. But when switching the filter to anything but "General", the game suddenly receives a massive drop in FPS. Sometimes it straight up crashes.

The issue occurred only on servers for me so far. I created a singleplayer world to see if the issue would also occur there, but everything seemed to work just fine there.

### Reproduction Steps

1. Join a server.
2. Open the statistics screen.
3. Change the filter to anything other than "General".

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v20

**Comment by chorbintime** [comment]
Follow the [performance guide](https://rpg.prominence.wiki/performance-guide), and update the Better Statistics Menu mod
