### ISSUE TITLE
Better minecraft Quest bug

### ISSUE THREAD

**Issue by Divvxll** [LunaPixelStudios/Better-MC#1787]
### Describe the Bug

after killing the UR GHAST we are not receiving the actual quest for it any help 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10 

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

Better MC (FORGE) - BMC3

**Comment by chorbintime** [comment]
force-complete the quest in /ftbquests editingmode true

**Comment by chorbintime** [comment]
it'll be fixed next update
