### ISSUE TITLE
not a bug but a fuckup on my end

### ISSUE THREAD

**Issue by raccoonloverfr** [LunaPixelStudios/Better-MC#1788]
so i was trying to make a server with this and then for some reason i decided since it wasnt working id just delete the mod files in my compputer and see if that worked (it didnt) and now even after ive tried like reinstalling the mod files and stuff it still doesnt work. like when i say it doesnt work it launches as kinda a normal mc but without all my normal things right?? but like i cant join any of the servers my friend had made or my own server with the modpack and im pretty sure its cause i was stupid as shit and deleted the mods off my computer and i need them back soon cause were supposed to play on the server my freinds bf made for us tonight in like an hour

**Comment by chorbintime** [comment]
just reinstall the modpack on ATLauncher
