### ISSUE TITLE
Hydra Game Crash

### ISSUE THREAD

**Issue by myzzekzptaszynca** [LunaPixelStudios/Better-MC#1789]
### Describe the Bug

Me and my friend were playing on our BMC4 world and we went to the Twilight Forsest to defeat Hydra and after we defeted mynoshroom we got soup from him and after i ate the soup i got "Hydra Slayer" achivment even tho i didint defeat a Hydra, and when we ran to the Hydra Lair the game crashed with this error:  The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class twilightforest.entity.boss.HydraHead cannot be cast to class net.minecraft.world.entity.Mob (twilightforest.entity.boss.HydraHead is in module twilightforest@4.3.2508 of loader 'TRANSFORMER' @361a1e86; net.minecraft.world.entity.Mob is in module minecraft@1.20.1 of loader 'TRANSFORMER' @361a1e86)

### Reproduction Steps

1. Defeat Minoshroom
2. Eat Soup
3. Get "Hydra Slayer" achivment
4. Go to Hydra Lair
5. Get game crash

### Crash Report or Log

Error: java.lang.ClassCastException: class twilightforest.entity.boss.HydraHead cannot be cast to class net.minecraft.world.entity.Mob (twilightforest.entity.boss.HydraHead is in module twilightforest@4.3.2508 of loader 'TRANSFORMER' @361a1e86; net.minecraft.world.entity.Mob is in module minecraft@1.20.1 of loader 'TRANSFORMER' @361a1e86)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

Better Nether, Bosses of mass destruction, Sophisticated Backpacks, Alexs Caves, Call of Yutacan, ChoiceTheorem's Overhauled Village, End Remastred, gravestones, Regions unexplored, advacment plaques, Alex's caves: Stuff and torodes, Biome makeover, and some more

**Comment by chorbintime** [comment]
update to v30.5, we offer no support for old versions
