### ISSUE TITLE
Grass/Tall Grass inside a piled up full snow block returns missing texture on the snow block

### ISSUE THREAD

**Issue by MokaChaos** [LunaPixelStudios/Better-MC#1791]
### Describe the Bug

Currently on winter season where the snow gradually generate on top of fullblocks, origin spawn on Grassland biome.

i just casually roam around while leaving the snow gradually build up on the ground, and suddenly i saw some missing texture, went up to it to see why it looks like that, turns out it's grass/tall grass on top of coarse dirt/grass block while also a full block piled up snow. if i break the grass or remove one layer of snow, the snow turns back to normal snow texture.

i've attached some screenshots on how it looks like in game. if you know anything to fix this or something that might help with the missing texture please do tell. have a nice day

### Reproduction Steps

1. find a snow biome or set the season to winter where sometimes it'll cover the grounds with snow.
2. find a block that has grass/tall grass on it
3. wait until the snow pile up on the grass until it's a full block of snow
4. and then, a missing texture block
...

### Screenshots and Videos

How it looks like :
![image](https://github.com/user-attachments/assets/6a428cb4-d52d-4065-8019-48fd5ff15a0e)
![image](https://github.com/user-attachments/assets/7919984b-d0a5-4a28-96db-695e2a90eed8)
Before (with grass):
![image](https://github.com/user-attachments/assets/c1dc55e8-db02-4e93-a9cb-f77ba9dd1f97)
After (without grass):
![image](https://github.com/user-attachments/assets/f4806137-c1cf-4d02-8616-7baa8d6f1bcb)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

### Other Mods

- Inventory Profiles Next (this probably wouldn't be related but this is the only thing i added)

**Comment by chorbintime** [comment]
Reinstall the modpack on ATLauncher and transfer over your saves folder, alongside your XaerosMinimap folders

**Comment by MokaChaos** [comment]
yeah, it works. idk why changing launcher fixes the problem but it works
