### ISSUE TITLE
Crafting table issues with modded wood variants

### ISSUE THREAD

**Issue by Keokolo** [LunaPixelStudios/Better-MC#1793]
### Describe the Bug

Wood variants from the Biomes O'plenty mod will not allow wood to be placed in a 2x2 arrangement to make a crafting table. Unsure if this caused by interference with the variant craft tables [fabric] mod.

### Reproduction Steps

1. chopping down biomes o'plenty tree wood and crafting in inventory to be planks
2. 2x2 arrangement of planks of biomes o'plenty wood will not craft crafting table
3. jei instructions only show vanilla woods to only being able to craft a crafting table
...

### Screenshots and Videos

![image_2024-08-14_014029190](https://github.com/user-attachments/assets/34adc323-7013-438c-a54e-bbdbef3e3f22)
![image](https://github.com/user-attachments/assets/fc742839-2dc2-423b-9298-fe1124936b93)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

Fabric 1.21 ver 0.16.0

### Other Mods

stock mod list, additional font resource pack (Serified Fonts - Cats)

**Comment by chorbintime** [comment]
will be fixed in the next update, thanks
