### ISSUE TITLE
A bug with opening doors

### ISSUE THREAD

**Issue by PILTof** [LunaPixelStudios/Better-MC#1794]
### Describe the Bug

The doors do not always open fully. Sometimes they appear to open, but they actually block your passage like an invisible barrier, or they swing back and forth.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-08-15_22 27 47](https://github.com/user-attachments/assets/52fe8a25-5577-4adb-9c07-0d48c29eef71)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

### Other Mods

Passive Skill Tree, Iron chests

**Comment by chorbintime** [comment]
try breaking & replacing the door
