### ISSUE TITLE
Cherry blossom leaves seems strange in game

### ISSUE THREAD

**Issue by xiaopangju** [LunaPixelStudios/Better-MC#1796]
### Describe the Bug

When you see the cherry blomssom in game, it will be strange. I can reproduce it when shaderpack Pastel-Shaders-Universal-v1.100 or VanillAA is enabled. I can also reproduce it when the shaderpacks are all disabled.

### Reproduction Steps

1. Open the game
2. Join a world
3. See a cherry blossom leave
4. and you can see the strange leaves

### Screenshots and Videos

![0F7FF821833FFC694291340332A3ABEF](https://github.com/user-attachments/assets/a4815a6d-87b4-45cc-abbc-067b0e09b665)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
put leaves quality on fancy
