### ISSUE TITLE
Leaf Textures

### ISSUE THREAD

**Issue by Szerowa** [LunaPixelStudios/Better-MC#1797]
### Describe the Bug

Just some of Fir Leaves are generated with no texture. (It only appears on world generated trees or on planted trees)

### Screenshots and Videos

![Zrzut ekranu 2024-08-19 163631](https://github.com/user-attachments/assets/f58d525c-af7c-447d-94d7-f082298ca6eb)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

**Comment by Szerowa** [comment]
Oh and the modpack is BMC4.

**Comment by chorbintime** [comment]
update the moonlight lib mod
