### ISSUE TITLE
Slow chunk loading(BMC 2 fabric)

### ISSUE THREAD

**Issue by TheCrispyGod** [LunaPixelStudios/Better-MC#1798]
### Describe the Bug

When traveling faster then sprint+jump, the chunks are stuttering and are slow to load, making the elytra impossible to use.

### Reproduction Steps

1.Flying with the elytra in new chunks
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
follow the performance guide https://rpg.prominence.wiki/performance-guide
