### ISSUE TITLE
Claims

### ISSUE THREAD

**Issue by fernyfern16** [LunaPixelStudios/Better-MC#1800]
I'm a new player to Better Minecraft and I'm loving it but I'm having a hard time figuring out claims. I was thinking alongside all the quests, if maybe a claims and parties quest could be a thing for the future? So new players like myself can get an idea on how to work with it. I really enjoy these features and hate that I'm missing out especially cause I can't start a base without one

**Comment by chorbintime** [comment]
the keybind quest mentions the claim keybind already and pretty much everything is self-explanatory within the claim menu
