### ISSUE TITLE
RyoamicLights causing exit code -1 

### ISSUE THREAD

**Issue by RedBlueKyle** [LunaPixelStudios/Better-MC#1801]
### Describe the Bug

Was able to open game from the initial upgrade yesterday, but my version and all of my friends who are running a server are running into the issue. Removing the mod will allow us to load the launcher

### Reproduction Steps

1. change or install version to v5
2. launch MC from curseforge
3. Exit Code -1
...

### Crash Report or Log

https://pastebin.com/eAeyaYJy

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v5 Beta

### Other Mods

Only added client mod would be Distant Horizons

**Comment by chorbintime** [comment]
Update the modpack to v5.5

**Comment by RedBlueKyle** [comment]
The v5.5 update failed to fix this issue.

**Comment by chorbintime** [comment]
do a fresh install of the modpack
