### ISSUE TITLE
Exit code: 6 (Macbook Air M1)

### ISSUE THREAD

**Issue by ldvegas** [LunaPixelStudios/Better-MC#1802]
### Describe the Bug

Im using a Macbook Air M1. I've installed Better MC modpack through the curseforge app and when I try to create a singleplayer world it crashes before I enter the world. But I can play on the BetterMC server idk why. I've also tried to install the modpack manually (without the cursefoge app) and I still get the same error. 

### Reproduction Steps

1. launch minecraft with the modpack
2. try to create a singleplayer world
3. crashes before I enter the world
...

### Crash Report or Log

https://gist.github.com/ldvegas/d88a6ea49d2ce86b88ed735a5b5a1a13

### Operating System

macOS Sonoma 14.5

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

**Comment by chorbintime** [comment]
There is an issue with Java 17.0.8 and newer where you may experience "A fatal error has been detected by the Java Runtime Environment", which can cause the Java runtime to crash under a variety of circumstances. To resolve this:
Mac:
1. Go [here](<https://www.azul.com/downloads/?version=java-21-lts&os=macos&package=jdk&show-old-builds=true#zulu>) and hover over the Download buttons until you see one with the option to install a .dmg file. If you have an M-series Mac, then make sure to install the ARM64 version of this file.
2. Install ATLauncher and open it. For more information on how to install and use ATLauncher, run the ``!alternates`` command in #bots.
3. Click "Settings" on the right
4. Click "Java/Minecraft" at the top
5. Set "Use Java Provided by Minecraft" to false by unchecking the checkbox
6. Manually specify the following Java path in the text box to the left to the "Reset" button: ``/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home\``
