### ISSUE TITLE
Fallo v 30.5 mod Bclib

### ISSUE THREAD

**Issue by Brandyk17** [LunaPixelStudios/Better-MC#1803]
### Describe the Bug

Tengo un fallo al intentar iniciar el modpack, siempre he metido mods diferentes al paquete, que me gustan a mi. No había tenido fallo hasta es actualización y no me deja meter mods específicamente que son de creación de mundos, cuando los meto me dicen que el mod bclib tiene fallo pero en la versión que llegue a usar anteriormente del modpack tenia la misma versión del bclib y nunca presentó algún fallo. Ya intente de muchas maneras y me di cuenta al ir metiendo los mods de manera individual que el fallo se presenta al momento de meter uno de creacion de mundo. ¿Podrían ayudarme?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V30.5

### Other Mods

Ejemplo de mods que fallan al meterlos

Alexcaves
Aquamirae
AwesonDungeons 
Etc...

**Comment by chorbintime** [comment]
you need to attach logs or we cant help
