### ISSUE TITLE
Leaf issue #2 On Better MC4

### ISSUE THREAD

**Issue by MRypper** [LunaPixelStudios/Better-MC#1804]
### Describe the Bug

Like @Szerowa i have random texture missing on leaves on the v30.5.
It appears on default tree, and tree plant by sappling.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-08-21_19 39 14](https://github.com/user-attachments/assets/d1984fa3-9139-4c1a-8443-cfc767663625)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

Better MC4 v30.5

**Comment by chorbintime** [comment]
update the moonlight lib mod
