### ISSUE TITLE
Elytra and item frame despawn

### ISSUE THREAD

**Issue by DeltaVictor89** [LunaPixelStudios/Better-MC#1806]
### Describe the Bug

When chunk is loaded item frame and elytra break meaning items respawn before you can collected, possible that block that they are attached to isn’t there when chunk is loaded

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V30.5

**Comment by chorbintime** [comment]
update the better end cities datapack

**Comment by DeltaVictor89** [comment]
Better end cities datapack is on version 1.20.4 + 15 and elytra and item frame appear as in image

![2024-08-23_22 16 26](https://github.com/user-attachments/assets/1c5bc93e-212c-4bcb-8908-198e9e85606e)

**Comment by chorbintime** [comment]
you need to use [this](https://www.curseforge.com/minecraft/texture-packs/better-end-city-for-better-end/files/4525273) file, and it wont fix existing end ships
