### ISSUE TITLE
Right clicking a painting 

### ISSUE THREAD

**Issue by hydn217** [LunaPixelStudios/Better-MC#1807]
### Describe the Bug

After placing down a 1x1 painting infront of a trap door and right-clicking it, I got stuck where I could no longer access my inventory, I received slowness, I couldn't interact with any blocks, and I couldn't change any item in my hot bar. My arms are also locked in front of me like a zombie 
![image](https://github.com/user-attachments/assets/fe360e12-a5a3-46f8-bf17-f4b87ebdaf52)

### Reproduction Steps

1. place 2 trapdoors and a door with a slab infront of the door.
![image](https://github.com/user-attachments/assets/fce48387-bb00-4040-9c51-ec0e4c8caa69)

2. place a 1x1 painting on top of the higher trapdoor.
![image](https://github.com/user-attachments/assets/60c96cf1-22a7-4f14-8156-b9cce2fd794b)

3. choose the bat option then shift and right-click.
![image](https://github.com/user-attachments/assets/205bc802-cb37-4458-86bb-c5bf0f8b12d1)

4. get stuck
![image](https://github.com/user-attachments/assets/e7684c37-f532-450c-ba88-d5b841e94723)

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

BMC 3

**Comment by hydn217** [comment]
I also learned if you were to right-click snow you can abuse it to make infinite snowballs.

**Comment by hydn217** [comment]
My theory is because it thinks the painting is a holdable entity, you hold it without being able to place it anywhere. Therefore being stuck to you unless death.

**Comment by chorbintime** [comment]
run the /carryon clear command
