### ISSUE TITLE
Error Internal exception

### ISSUE THREAD

**Issue by Marznite19** [LunaPixelStudios/Better-MC#1808]
### Describe the Bug

Hello. I'm having problems tto start my online server with Better-MC. It says the seerver its online but every time I tray to get inside it gives me this error:

internal exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 18, length: 114 (expected: range(0, 37))

I'm really new at this minecraft servers thing and all so I would really appreciate the help. Thanks.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![imagen_2024-08-23_040600682](https://github.com/user-attachments/assets/3137c8d5-8278-4f81-9597-37b0cc566ea1)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
you dont have the same modpack installed as the server
