### ISSUE TITLE
BMC4 (Forge) Crashing On Startup

### ISSUE THREAD

**Issue by Papotheos** [LunaPixelStudios/Better-MC#1809]
### Describe the Bug

I downloaded the Better Minecraft modpack off of ATLauncher and when i pressed play ATLauncher closed and turned back on again where i left off without any crash code. I also tried it on curseforge and it didn't work. i tried switching the version but every forge version wasn't working, only fabric.

@chorbintime commented this and closed the issue but I don't know how to reopen the issue so I made a new report.

You (likely) need to update your graphics drivers in order to resolve the crash. Here's how to go about doing that!

1. Identify your graphics card if you already know skip to the next step

Open task manager
Navigate to the "Performance" tab (on Windows 11 this is the button that looks like a heart pulse)
Press the GPU 0 graph and read your GPU from the top right
Note: In some cases you may see a GPU 0 and GPU 1. This means your CPU has its own GPU, as well as a dedicated one. You probably want GPU 1 (which is usually the better one), but you can ask staff to clarify if necessary.

2. Download your drivers from the manufacturers site Depending on what you read before, you likely need drivers from either AMD, Intel, or NVIDIA

AMD: https://www.amd.com/en/support Intel: https://www.intel.com/content/www/us/en/download-center/home.html NVIDIA: https://www.nvidia.com/Download/index.aspx?lang=en-us

Note:

For NVIDIA you want to select "Game Ready Driver (GRD)" (this is the default option) for the best performance. Once installing you'd probably prefer downloading GeForce Experience, which will notify you when there's an available drivers update.
For Intel, you probably want to press "Get Started" under the "Automatically update your drivers and software", which will simplify the process and update everything automatically
For AMD you probably want to just press "Download Windows Drivers", which will download something called AMD Adrenaline, which will update your drivers automatically.
3. Run the installation, restart your computer, and try playing MC again

At this point, hopefully your Minecraft is running. If it still does not work, please post any new logs and staff will help assist you with finding the right solution.

My response:

Thank you for your reply but the issue still stands. I updated my graphics driver, restarted my pc, tried to run minecraft on both CurseForge and ATLauncher but again it didn't work. I looked online and it also said to update my graphics driver. I use NVIDIA 3050 Ti if that helps. And one more thing, I used the NVIDIA app and not GeForce Experience so I don't know if that's the reason.

### Reproduction Steps

I don't know what you mean by reproducing the bug so I wrote what I thought was correct.

1. Download BMC4 Modpack on ATLauncher
2. Select "Instances"
3. Hit Play under BMC4
4. Crash

### Crash Report or Log

https://paste.atlauncher.com/view/82f57e6e-23cf-4711-9395-d66fa62ecff6

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30

**Comment by chorbintime** [comment]
I very clearly told you that you need to update drivers. I'm not sure why you just copied the contents of my response and didnt actually follow the directions. 

Changing modpack versions is not the fix. You specifically need to update your GPU drivers through the vendors website.

**Comment by Papotheos** [comment]
@chorbintime 
I updated my GPU drivers using the vendors website now and still no change. If it helps, on CurseForge after crashing the exit code is 1...

**Comment by chorbintime** [comment]
please send new logs

**Comment by Papotheos** [comment]
Ok so I tried to run it on CurseForge trying to find a crash log, but when it crashed it only gave me exit code 1, so I tried it on ATLauncher to copy the log from the ATLauncher Console and this time Minecraft actually started but it says that I have less memory allocated than recomended. Is that the problem? Here's the log:
https://paste.atlauncher.com/view/5e96e81a-14eb-4456-900d-c5948e159552

**Comment by Papotheos** [comment]
I tried to run it on CurseForge now with more memory but it didn't help, still the same exit code 1. I would send the CurseForge logs but I can't figure out where to find it.

**Comment by chorbintime** [comment]
> Ok so I tried to run it on CurseForge trying to find a crash log, but when it crashed it only gave me exit code 1, so I tried it on ATLauncher to copy the log from the ATLauncher Console and this time Minecraft actually started but it says that I have less memory allocated than recomended. Is that the problem? Here's the log: https://paste.atlauncher.com/view/5e96e81a-14eb-4456-900d-c5948e159552

The warning is normal, it just means you didnt allocate enough RAM. Your game started fine and theres nothing wrong here. You're able to play the game

**Comment by Papotheos** [comment]
Yes, modpacks on ATLauncher, but other modpacks such as Steampunk (LPS) don't work on Forge even after allocating max memory. Also still BMC doesn't work on Forge andI know I can play it on ATLauncher but the issue still isn't resolved.

**Comment by chorbintime** [comment]
Do not allocate max memory. You only need to allocate 8.

You need to send logs for me to help you with you crashes.

**Comment by Papotheos** [comment]
Sorry for the late reply. Here's the log: 
[latest.log](https://github.com/user-attachments/files/16825031/latest.log)

**Comment by chorbintime** [comment]
reinstall the modpack on ATLauncher and update your gpu drivers:

**1. Identify your graphics card**
_if you already know skip to the next step_
- Open task manager
- Navigate to the "Performance" tab (on Windows 11 this is the button that looks like a heart pulse)
- Press the GPU 0 graph and read your GPU from the top right

**Note:**
*In some cases you may see a GPU 0 and GPU 1. This means your CPU has its own GPU, as well as a dedicated one. You probably want GPU 1 (which is usually the better one), but you can ask staff to clarify if necessary.*

**2. Download your drivers from the manufacturers site**
Depending on what you read before, you likely need drivers from either AMD, Intel, or NVIDIA

**AMD**: <https://www.amd.com/en/support> 
**Intel**: <https://www.intel.com/content/www/us/en/download-center/home.html> 
**NVIDIA**: <https://www.nvidia.com/Download/index.aspx?lang=en-us> 

**Note:**
- *For NVIDIA you want to select "Game Ready Driver (GRD)" (this is the default option) for the best performance. Once installing you'd probably prefer downloading GeForce Experience, which will notify you when there's an available drivers update.*
- *For Intel, you probably want to press "Get Started" under the "Automatically update your drivers and software", which will simplify the process and update everything automatically*
- *For AMD you probably want to just press "Download Windows Drivers", which will download something called AMD Adrenaline, which will update your drivers automatically.*

**3. Run the installation, restart your computer, and try playing MC again**
- At this point, hopefully your Minecraft is running. If it still does not work, please post any new logs and staff will help assist you with finding the right solution.

**Comment by Papotheos** [comment]
My drivers are up to date as I have mentioned. I have downloaded the drivers from the vendors website (NVIDIA) but it isn't only BMC thats crashing it's almost every large Forge modpack such as SteamPunkLPS.

**Comment by chorbintime** [comment]
do you have a file named hs_err_pid in your modpack files? if so send it here

**Comment by Papotheos** [comment]
Sorry again for the late reply, I do not have a file named hs_err_pid.

**Comment by chorbintime** [comment]
Are you on ATLauncher?

**Comment by Papotheos** [comment]
No, I installed ATLauncher thinking the modpack problem was with the mod launcher. I mainly use curseforge.

**Comment by chorbintime** [comment]
Install & launch the pack via ATL and follow the [performance guide](https://rpg.prominence.wiki/performance-guide)
