### ISSUE TITLE
Frostmaw Quest Bug

### ISSUE THREAD

**Issue by Spore59** [LunaPixelStudios/Better-MC#1810]
### Describe the Bug

I was exploring when I came across the frostmaw. After sneaking up and taking away its item and defeating the boss I was given the achievement, but the quest reward was not unlocked. 

### Reproduction Steps

1.steal the held item from the frostmaw
2.defeat the frostmaw
3.
...

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

**Comment by chorbintime** [comment]
make sure to get the last hit on the boss using a melee weapon, not fire aspect or a potion effect
