### ISSUE TITLE
Unable to start server with illager Invation

### ISSUE THREAD

**Issue by 17721250181** [LunaPixelStudios/Better-MC#1811]
### Describe the Bug

When i start a server on https://pixelcloud.cn/ Java sent an error (attached log via link).
When i remove illager invation, I can successfully start the server.

### Reproduction Steps

1. upload serverpack to the website, choose fabric 1.20.1 loader
2. start the server with the modpack
3. Error appears in console
...

### Crash Report or Log

https://drive.google.com/file/d/1Yz9RhYNqcLC5TrO34bGZ8NumBmfBUDcd/view?usp=sharing

### Operating System

cloud server (likely windows)

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.20.1 v25

### Other Mods

None

**Comment by chorbintime** [comment]
https://github.com/Fuzss/illagerinvasion
