### ISSUE TITLE
Fresh install of Server and Client not synced

### ISSUE THREAD

**Issue by arlight1** [LunaPixelStudios/Better-MC#1813]
### Describe the Bug

A friend installed BMC v30.5 server version and client and I installed v30.5 client on my own machine. Upon attempting to join the server, a config mismatch for "backpacked:server" shows up. screenshot below.

### Reproduction Steps

1. Install BMC 30.5 server version on machine 1 using curseforge app
2. Install BMC 30.5 client on machine 2 using cruseforge app
3. Run server on machine 1
4. Run client on machine 2 and attempt to connect

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/cbbcdb30-e5d7-4533-a80a-fbf1a2811791)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V30.5

**Comment by chorbintime** [comment]
its not a modpack issue, you just didnt install the modpack correctly. use ATLauncher for clientside installation and follow the [guide](https://github.com/chorbintime/LPS-readme/wiki/1.20.1) for serverside
