### ISSUE TITLE
Backpack

### ISSUE THREAD

**Issue by skeenasty** [LunaPixelStudios/Better-MC#1814]
### Describe the Bug

When opening a new backpack, it glitches out the backpack you're wearing and everything in it

### Reproduction Steps

1. wear a backpack
2. craft new backpack (preferably the same one, in this instance it was the bejewled backpack)
3. open new backpack in hotbar or by hand
4. old backpack/stuff in it will be gone

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
which backpack are you using

**Comment by skeenasty** [comment]
It was the Frayed

**Comment by chorbintime** [comment]
you can try updating the inmis backpacks mod - if the issue persists then report the issue to the mod author
