### ISSUE TITLE
Small lag spike when crafting stacks

### ISSUE THREAD

**Issue by Bryan-visarr** [LunaPixelStudios/Better-MC#1816]
### Describe the Bug

everytime I craft 128 planks into sticks I get a very annoying lagspike

### Reproduction Steps

1.open the inventory
2.2 stacks of planks to make sticks
3.shift + click and lag
...

### Screenshots and Videos

https://github.com/user-attachments/assets/261fca84-f651-4215-a471-d80eabdfb531

### Crash Report or Log

none

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

30.5

**Comment by Bryan-visarr** [comment]
you can notice the small tp of the mobs

**Comment by Bryan-visarr** [comment]
Never mind, I just reseted the profile and all came back to normal

**Comment by chorbintime** [comment]
please follow [the performance guide](https://rpg.prominence.wiki/performance-guide)
