### ISSUE TITLE
Villager Pathing Changed

### ISSUE THREAD

**Issue by heavyhuntr** [LunaPixelStudios/Better-MC#1818]
### Describe the Bug

Villager pathing has been changed in this pack after v28 of the pack, they do not seem to view trapdoors as something they could walk through. This has been something left in the game intentionally and used in multiple villager breeder designs.

### Reproduction Steps

1. Make two 3x3x3 internal rooms connected by a 1x2x3 internal hallway where the hallway height is offset by -1.
2. Place trapdoors against the top of the hallway and even with the ground of each 3x3x3 room.
3. Put villagers in one room and beds against the far wall of another.
4. Feed the villagers enough so they start attempting to breed.
5. Note how villagers fail to breed and at night won't walk towards the trapdoors.
...

### Screenshots and Videos

Minimum reproducible setup as described above, done in v30.5: ![image](https://github.com/user-attachments/assets/3241a0a6-142a-4ce7-bbb8-7df88cddad4d)

https://github.com/user-attachments/assets/f7bc9ae4-d69c-44e6-84c8-da38f1252159

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v29+

**Comment by chorbintime** [comment]
it'll be fixed in v31, its just the libertys villagers mod config. technically intentional but we dont want it enabled

**Comment by heavyhuntr** [comment]
Thank you, I spent a while looking for this and trying to figure it out and didn't get around to that mod and its config, so that also helps me until v31 is ready.
