### ISSUE TITLE
Can't connect to server 

### ISSUE THREAD

**Issue by Zero-Alien** [LunaPixelStudios/Better-MC#1819]
### Describe the Bug

My friend is hosting the server, it was working fine last night but is now giving an error.  I can give you the log if you need.

I've tried the following:
- reinstalling 
- changing timeout length on the mod "connectivity"
- allowing java and minecraft through firewall
- changing network to private
- windows is up to date
- restarted internet  

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2024-08-27 151125](https://github.com/user-attachments/assets/66d0c1dd-ec00-4844-a39c-9adfaad8e38d)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V30.5

### Other Mods

ParCool!

**Comment by chorbintime** [comment]
its an issue on your friends side. nothing to do with the modpack. make sure your friend portforwarded
