### ISSUE TITLE
Armor and Shield bug in BMC5 [NEOFORGE] 1.21

### ISSUE THREAD

**Issue by DarylDpro** [LunaPixelStudios/Better-MC#1820]
**Describe the Bug**
Hi this is a bug report, i recently downloaded BetterMC 5 on curseforge and there seems to be an issue whereby shields and armors do not reduce any damage taken by the player. Whenever i wear full netherite armor with prot 4 and suffer damage like a skeleton shot or a zombie attack, i seem to suffer the same amount of damage as when I do not have armor on. For the shields, the animation and sound of the shields blocking attacks seems to be working but i still suffer damage when  i get shot by a skeleton while holding up a shield. This issue seems consistent throughout all the versions of BMC5 (v1, v2, v3) and i doubt i am the only one with this issue. thanks for taking the time to read and i hope this gets patched soon🙂

### Steps to reproduce:
1. Install BetterMC 5 [NEOFORGE] 1.21
2. Start up a new world and obtain netherite armor with protection 4 enchantment and a shield
3. Spawn a skeleton and have it attack and shoot arrows at you
4. wear your armor and hold up your shield
5. the shield seems to have the animation of deflecting the shot but you still suffer 2 hearts of damage
6. now without the shield but still having netherite armor on, have the skeleton shoot at you, it will still deal about 2 hearts (same as without armor)

**Operating System**
windows 11

**Minecraft Version**
1.21

**Modloader**
NeoForge

**Modpack Version**
v1, v2, v3

**Other Mods**
None

**Comment by chorbintime** [comment]
can you send a video? does the issue only happen with zombie/skeletons?

**Comment by DarylDpro** [comment]
heres the link to the video: https://vimeo.com/1003504806
i think this happens for all hostile mobs

**Comment by chorbintime** [comment]
try without the deeper darker mod

**Comment by DarylDpro** [comment]
it seems to work now, the deeper darker mod is the issue, thanks for your help, really appreciate it 🙏

**Comment by chorbintime** [comment]
deeper darker devs are aware, and will fix this soon
