### ISSUE TITLE
end black screen

### ISSUE THREAD

**Issue by Loekd123** [LunaPixelStudios/Better-MC#1821]
### Describe the Bug

After entering the portal to go to the end for a second i see the end sky but after my screen turns black with only the tips

### Reproduction Steps

1.enter the end
2. and thats it
3.
...

### Screenshots and Videos

![Screenshot 2024-08-28 140145](https://github.com/user-attachments/assets/7d0fe887-763d-4b9e-aa7d-a7950b3be4fa)

### Crash Report or Log

non

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

### Other Mods

no fog

**Comment by chorbintime** [comment]
Follow [the performance guide[(https://rpg.prominence.wiki/performance-guide)
