### ISSUE TITLE
paintings disappear after you place them

### ISSUE THREAD

**Issue by LiamHaste** [LunaPixelStudios/Better-MC#1822]
### Describe the Bug

when i place down a painting and then press escape to back out of the selection screen if i don't want to place it or something, the painting just disappears from my inventory, but it doesn't get placed down either, it just disappears.

### Reproduction Steps

1.place down a painting
2.press ESC
3. painting just disappears 
...

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

### Other Mods

none

**Comment by chorbintime** [comment]
does it persist with the fast paintings mod removed? make a backup first
