### ISSUE TITLE
Base game leaves display the wrong textures in BMC3 v5.5 [Fabric] 1.21

### ISSUE THREAD

**Issue by samanthot** [LunaPixelStudios/Better-MC#1823]
### Describe the Bug

Oak, Birch, Spruce, Jungle, Acacia, and Dark Oak leaves use their Programmer Art textures, with Birch, Acacia, and Dark Oak being the exception (they're using the Oak leaves texture)

![huge_2024-08-28_12 01 31](https://github.com/user-attachments/assets/7039a151-c9d1-423f-88d6-2129e5e76158)

Other base game leaves, like Mangrove, Cherry Blossom, and Azalea are unaffected. 

I'm using the latest version of the modpack, with no changes made to the modpack, modifications made to the resource packs, and no additional mods. I've also downgraded to v5 of this modpack, and the issue still stays.

Removing all resource packs doesn't affect the leaf textures, aside from Birch leaves regaining their color (The birch leaves being colorless probably isn't an issue though, and more has to do with how Stay True works)

### Reproduction Steps

Simply install and launch BMC3 v5.5, create a world, and look at any of the base-game leaf textures.

### Screenshots and Videos

![huge_2024-08-28_12 26 52](https://github.com/user-attachments/assets/be79ccd8-556b-4322-aec5-d81fc656990c)
Glitched base game leaves next to leaves which have their intended textures (in different colors of course)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

5.5

### Other Mods

None

**Comment by chorbintime** [comment]
yeah i have genuinely no clue what's been causing this - im going to look into it soon though. if you end up finding anything let me know

**Comment by samanthot** [comment]
Removing Paxi fixed the issue for me. There's also someone who opened an issue on the mod's github page who's running into the exact issue that I was having, so it's definitely Paxi. Hopefully it isn't being used for anything important
