### ISSUE TITLE
Hopper craft bug 1.21 [NEOFORGE]

### ISSUE THREAD

**Issue by Domonkos-Balazs** [LunaPixelStudios/Better-MC#1824]
### Describe the Bug

Hi!
I downloaded BetterMC 5 and the BMC5 v3 server pack on curseforge.
I can't craft a hopper but I have all the materials. I linked a video for this problem.
I couldn't select the minecraft version 1.21 and the neoforge modloader

### Reproduction Steps

1. Install BetterMC 5 [NEOFORGE] 1.21
2. Download the BMC 5 server pack
3. Launch the server
4. Connect to the server
5. Try to craft a hopper

### Screenshots and Videos

https://youtu.be/0nCdUNUO1Fs

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v1, v2, v3

**Comment by Domonkos-Balazs** [comment]
I tried on singplayer and it worked, so the bug is in the server files.

**Comment by chorbintime** [comment]
will look into it for next update, thanks for the report
