### ISSUE TITLE
Unable to Launch Modpack

### ISSUE THREAD

**Issue by TheSamsonite16** [LunaPixelStudios/Better-MC#1825]
### Describe the Bug

Over the last 3 or so updates to the Better MC [FABRIC] - BMC3 modpack, I have been unable to actually enter the game. It keeps giving me this error, saying that a mod called RyoamicLights is causing issues of some kind that keep the modpack from fully loading.

### Reproduction Steps

1. Go into CurseForge
2. Open Better MC [FABRIC] - BMC3 modpack
3. When launcher is loaded, click "Launch Game" and wait for a bit.
4. It'll give you an error saying that RyoamicLights is causing issues in the files.

### Screenshots and Videos

![image_2024-08-29_165219258](https://github.com/user-attachments/assets/05034b64-731d-4628-9c6d-9e231f88afb1)

### Crash Report or Log

[crash-2024-09-02_17.50.39-client.txt](https://github.com/user-attachments/files/16841420/crash-2024-09-02_17.50.39-client.txt)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v3, v4, v5, v5.5, v6

### Other Mods

Complementary Shaders - Unbound
Wildfire's Female Gender Mod

**Comment by chorbintime** [comment]
you need to send logs or we cant help

**Comment by TheSamsonite16** [comment]
@chorbintime I just added the crash report.

**Comment by chorbintime** [comment]
do a fresh install of the modpack on ATLauncher, or replace the RyoamicLights mod with https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged

**Comment by TheSamsonite16** [comment]
@chorbintime Thank you!
