### ISSUE TITLE
cured zombie villagers dont take damage from mobs(solution found)

### ISSUE THREAD

**Issue by JAKAFI** [LunaPixelStudios/Better-MC#1826]
### Describe the Bug

When a zombie villager is spawned from either spawner or egg and cured to a villager it will not take any damage from hostile mobs. tested with zombie, zombie villager, husk, evoker, and pillager. Emerald particles are released when pillager shoots it but arrow rebounds off villager. When the variations of zombie attack they make the attacking animation but no damage is taken from teh villager and no particles are released. evoker does its attacks and does no damage either. The villager still takes damage from player, wither roses, and suffocation. There could be more that's all I've tested)

When a villager is spawned in, it can be converted and cured. It takes damage from other entities as well. Seems to only happen when starting from zombie villager.

I cant seem to find a config folder on my server that would allow something like this to happen.

### Reproduction Steps

1. Use zombie villager egg to spawn one villager
2. Use splash potions of weakness on zombie villager and right click with golden apple. wait for villager to cure.
3. Use zombie spawn egg to spawn a zombie next to the cure villager in an enclosed space as to not let the villager run away.

### Screenshots and Videos

https://github.com/user-attachments/assets/d04e64dd-2bfe-4c32-a643-cb195a5f1cb2

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

30.5

### Other Mods

silk spawners (bug was already noticed before adding)
https://www.curseforge.com/minecraft/mc-mods/silkspawners

**Comment by chorbintime** [comment]
try without the libertys villagers mod

**Comment by JAKAFI** [comment]
Uninstalling the liberty mods did not work. however what i noticed is the invincibility of the villagers is based on what chunks they are in.(the video i uploaded is very compressed to get less than 10mb so please bear with me) 

https://github.com/user-attachments/assets/80ef9e89-51e4-452e-ad94-8cffaa42c150

You can actually see the villager running between the chunks and the zombie not hitting it in one chunk and hitting it in the other. Now i really go no idea what is going on.

**Comment by JAKAFI** [comment]
Just realized that the zombies not being converted are in claimed chunks. oops lol. didnt realize that was a feature of the modpack. Idk maybe someone else has been a little slow like me and will find this useful.

**Comment by ArchaeanDragon** [comment]
LOL.. was about to suggest that, but took forever to get the 2FA code to log in to reply. XD 

Yes, claimed chunks change a lot of mechanics, so be aware
