### ISSUE TITLE
Breeding Dragons (Dragon Mounts: Legacy)

### ISSUE THREAD

**Issue by skeenasty** [LunaPixelStudios/Better-MC#1827]
### Describe the Bug

Our dragons won't breed again after they've bred twice. They get the heart particles, but they disappear, and don't want to breed.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

**Comment by chorbintime** [comment]
report it to the dragon mounts legacy devs
