### ISSUE TITLE
Plank textures missing

### ISSUE THREAD

**Issue by HowdYQT** [LunaPixelStudios/Better-MC#1828]
### Describe the Bug

When i went inside a tower or temple(idk what it is tbh) i noticed the spruce plank textures were seethrough. I just started playing today and i'm new to modded minecraft so i have no idea how to fix it. I tried organizing the resource packs another way but it still did not work.

### Reproduction Steps

1. Launch the game and play it I guess, thats how it happened for me.
2.
3.
...

### Screenshots and Videos

![2024-08-30_17 23 24](https://github.com/user-attachments/assets/293d049f-f030-42bc-a5ae-6cb1a4fd5bba)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

### Other Mods

FTB Ultimine

**Comment by chorbintime** [comment]
update the moonlight lib mod, if issue persists reinstall the modpack on ATLauncher and transfer both your xaerosminimap folders and saves folder over
