### ISSUE TITLE
Problème nom complet des items et affichage

### ISSUE THREAD

**Issue by PiXxElEvO** [LunaPixelStudios/Better-MC#1830]
### Describe the Bug

J'ai commencé a jouer a better mc en fabric v25 1.20.1 . Sur la minimap les point cardinaux ( nord, sud, ouest et est ) s'affiche sous la forme  de texte comme :` gui.xaero_compass_west `
il y a aussi beaucoup d'items qui sont nommé sous des noms complet comme celui au-dessus.
Merci pour votre aide.

### Reproduction Steps

Lancer une partie en solo

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/d45e39c3-d8b3-4e42-a4a5-592201a99dda)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
reinstall the modpack on ATLauncher
