### ISSUE TITLE
I found a problem and a simple solution

### ISSUE THREAD

**Issue by Francoprox004** [LunaPixelStudios/Better-MC#1835]
### Describe the Bug

Hello! I found a problem, the default ModPack comes with the REI mod, but I was not convinced by this mod, I don't remember why, I think it had performance problems, so I decided to change it for the JEI, and here I found a problem. It turns out that for some reason there is an incompatibility and the vanilla minecraft search engine in creative mode does not work when installing the JEI with this modpack.

I've been researching, pulling and pulling mods until I found the mod that causes problems with the JEI and it turns out to be the "Modern fix", specifically these versions:

modernfix-fabric-5.17.0+mc1.20.1 (current version in the modpack)
modernfix-fabric-5.18.0+mc1.20.1
modernfix-fabric-5.18.1+mc1.20.1
modernfix-fabric-5.18.6+mc1.20.1

starting with version "modernfix-fabric-5.18.9+mc1.20.1" this error was solved.

so I would like to suggest that you update the modern fix in the modpack. I know that it is not your problem that users modify the modpack to their liking, but since the solution seems simple I thought that maybe you want to take it into account.

(It is necessary to update the fabric loader to version 0.16.3 or higher)

Modpack used: https://www.curseforge.com/minecraft/modpacks/better-mc-fabric-bmc2

### Reproduction Steps

1. Install the latest version of JEI
2. Install the latest version of fabric api
3. install Modern Fix 5.17.0
4. and use a fabric loader version equal to or greater than 0.16.3

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/jei

**Comment by chorbintime** [comment]
REI works completely fine, i dont know why you removed it in the first place lol
