### ISSUE TITLE
Proplem with start modpack

### ISSUE THREAD

**Issue by Max1585** [LunaPixelStudios/Better-MC#1836]
### Describe the Bug

The mod cannot be started,

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://securelogger.net/files/cf492a9c-14b7-49b5-89ee-47608eecb800.txt

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

**Comment by chorbintime** [comment]
reinstall the modpack on ATLauncher
