### ISSUE TITLE
amendments causing crash

### ISSUE THREAD

**Issue by ramirez223** [LunaPixelStudios/Better-MC#1837]
### Describe the Bug

amendments wall lanterns and signs when bumped into cause crash
the server updated from 30.5 to 31.5
caught by neruina, but every time player joins it would crash

### Reproduction Steps

1a: place down wall lantern ( lantern hanging form a wall added by complementary)
1. update from 30.5 to 31.5
2. run into it
3. crash

### Crash Report or Log

https://pastebin.com/YCEFHJSp

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

31.5

### Other Mods

none

**Comment by chorbintime** [comment]
update the amendments mod
