### ISSUE TITLE
ancient temple in deeper and darker is not being generated

### ISSUE THREAD

**Issue by Inxura** [LunaPixelStudios/Better-MC#1838]
### Describe the Bug

the ancient temple is not generated, but can be “found” via command. there is a small, round cave where the temple should probably be.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

 Im using the newest v.6 on 1.21

**Comment by chorbintime** [comment]
report it to the deeper darker devs
