### ISSUE TITLE
exit code 6

### ISSUE THREAD

**Issue by oumskiki** [LunaPixelStudios/Better-MC#1839]
### Describe the Bug

I'm playing better mc at my mac book pro m2 series. the game loads until i enter my world and then crashes gives me exit code 6

### Reproduction Steps

1. open better mc 
2. click singleplayer
3. enter my world
4. stuck at loading page
5. crashes

### Crash Report or Log

https://mclo.gs/PUmnTDi

### Operating System

Mac OS Sonoma 14.2.1

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v32

**Comment by chorbintime** [comment]
For Mac devices using Apple Silicon/arm (M1/M2/etc.) CPUs
There is an issue with Java 17.0.8 and newer where you may experience "A fatal error has been detected by the Java Runtime Environment", which can cause the Java runtime to crash under a variety of circumstances. To resolve this:
Mac:
1. Go [here](<https://www.azul.com/downloads/?version=java-21-lts&os=macos&package=jdk&show-old-builds=true#zulu>) and hover over the Download buttons until you see one with the option to install a .dmg file. If you have an M-series Mac, then make sure to install the ARM64 version of this file.
2. Install ATLauncher and open it. For more information on how to install and use ATLauncher, run the ``!alternates`` command in #bots.
3. Click "Settings" on the right
4. Click "Java/Minecraft" at the top
5. Set "Use Java Provided by Minecraft" to false by unchecking the checkbox
6. Manually specify the following Java path in the text box to the left to the "Reset" button: ``/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home\``

**Comment by chorbintime** [comment]
you are still using Curseforge launcher so you very clearly did not follow the steps lol

**Comment by LivLopez27** [comment]
@chorbintime i also had the same issue and followed all of your steps but it still crashes even on ATLauncher, maybe its a problem that i have an M3. im starting to worry that i simply cannot do mods.

**Comment by chorbintime** [comment]
> [@chorbintime](https://github.com/chorbintime) i also had the same issue and followed all of your steps but it still crashes even on ATLauncher, maybe its a problem that i have an M3. im starting to worry that i simply cannot do mods.

you need to send logs if you want me to help you. saying 'i have the same issue' doesnt help
