### ISSUE TITLE
Can’t find end city..

### ISSUE THREAD

**Issue by walty69** [LunaPixelStudios/Better-MC#1840]
I am new to this mod and playing it for the first time. I have just accessed the end islands after beating the ender dragon and I cannot find an end city? Are they extremely rare or is this a bug with all the end mods that are installed?
Thanks

**Comment by chorbintime** [comment]
you didnt say what modpack you're playing or the modpack version so i cant really help here

**Comment by walty69** [comment]
It is 1.20.1 Better MC mod pack. V 30.5
It has a bunch of End related mods that change everything so I wasn’t sure if they made the spawns of end cities more rare or if it’s an issue. I have travelled over like 5000 blocks in multiple directions

**Comment by chorbintime** [comment]
its fixed in v32.5. update the modpack.
