### ISSUE TITLE
Cannot find End City

### ISSUE THREAD

**Issue by walty69** [LunaPixelStudios/Better-MC#1841]
### Describe the Bug

Playing Better MC Mod Pack 1.20.1  v30.5 

I am new to this mod and playing it for the first time. I have just accessed the end islands after beating the ender dragon and I cannot find an end city? Are they extremely rare or is this a bug with all the end mods that are installed?
Thanks

### Reproduction Steps

1. Tried going to the config file and changing the Endcityfail from 5 to 1 and haven’t noticed anything

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V30.5

**Comment by chorbintime** [comment]
update to v32.5, we offer no support for old versions and the issue is fixed
