### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by SteveBlowjobs-eng** [LunaPixelStudios/Better-MC#1842]
### Describe the Bug

The server is online but when me or my friend tries to join we are getting kicked and we are getting this message-Internal Exception: io.netty.handler.codec.Decoder:Exception: Failed to decode packet 'clientbound/minecraft:recipe'

The minecraft version is actually 1.21

[disconnect-2024-09-10_16.09.02-client.txt](https://github.com/user-attachments/files/16977994/disconnect-2024-09-10_16.09.02-client.txt)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/b9a10046-a7c2-4538-8cb6-ef79d6607ee0)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

BMC 3

**Comment by chorbintime** [comment]
how did you install the modpack client and serverside
