### ISSUE TITLE
Chunk Loading

### ISSUE THREAD

**Issue by TexRah71** [LunaPixelStudios/Better-MC#1843]
### Describe the Bug

 while flying on a dragon, I came up on an area where the chunks stopped loading and at that moment my game froze. Now every time I load into the game, there is no ground only sky. so it looks like none of the chunks are loading anywhere around me, but anyone else who joins the server is totally fine.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-09-13_14 34 01](https://github.com/user-attachments/assets/bda32a70-f390-417f-a9e4-985bb90c3d6d)

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

31.5

**Comment by chorbintime** [comment]
update to v32.5. we offer no support for old versions
