### ISSUE TITLE
Found End City with no chest or Elytra

### ISSUE THREAD

**Issue by walty69** [LunaPixelStudios/Better-MC#1845]
### Describe the Bug

I have been playing the Better MC mod pack recently v30.5 (1.20.1) and at first could not find any end city’s or ships. After traveling 5000+ blocks I finally found around 3 end city’s but the loot generation is messed up because none of them had a single chest or elytra on any of the end ships. Is this a bug? I know there are a few mods in the pack that change the End dimension but I’m not sure if it’s buggy and nothing spawns or it’s super rare to find a ship with an Elytra… 
Pls help!
Thanks!

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V30.5

**Comment by chorbintime** [comment]
update to v32.5. we offer no support for old versions and this issue was already fixed a long time ago
