### ISSUE TITLE
Freezing when open crafting table, when raining 

### ISSUE THREAD

**Issue by mag1str2004** [LunaPixelStudios/Better-MC#1846]
### Describe the Bug

My pc is pretty good and i have BETTERMC 4 (1.20.1 forge version), i increase to 8gb ram for the modpack, everything is good, but sometimes it's freezing, when raining (a little bit) and when opening crafting table and closing it. Also when i'm breaking any of blocks (stone for example) the texture dissapears sometimes and i see white texture for 1 milisecond and after that block is removing.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

BetterMC 4 v32.5

### Other Mods

TacZ (weapon), BSL shaders and Arthropod Phobia Expansions.

**Comment by mag1str2004** [comment]
YOU MUST SEE THIS VIDEO TO UNDERSTAND ME - [VIDEO](https://youtu.be/0mSSXJAP1kQ)

**Comment by chorbintime** [comment]
follow the performance guide https://rpg.prominence.wiki/performance-guide
