### ISSUE TITLE
Collect all dragon eggs bug 

### ISSUE THREAD

**Issue by chillidogs24** [LunaPixelStudios/Better-MC#1847]
### Describe the Bug

I started a new world and close to me was a spruce jungle temple, i looted the chests near the pistons in the hidden room, and there was a forest egg in one of them. I took it and then it showed that i collected every dragon egg and could collect the ender dragon one.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v32.5

**Comment by chorbintime** [comment]
the quest title is just incorrect. its not really a bug, this is mostly intended behavior
