### ISSUE TITLE
BMC4 crashes when lookin for recipes in JEI

### ISSUE THREAD

**Issue by likmum001** [LunaPixelStudios/Better-MC#1848]
### Describe the Bug

Hi,
I am playing BMC 4 on custom server with few added mods (mekanism, create and ender IO). Sometimes when looking for recipes in JEI the game crashes after pressing Escape or E. Also tried to update JEI, but it did not help.

### Reproduction Steps

1. Look for recipes in JEI
2. Press E or Esc

### Screenshots and Videos

[crash-2024-09-16_17.06.42-client.txt](https://github.com/user-attachments/files/17015466/crash-2024-09-16_17.06.42-client.txt)
![obrázek_2024-09-16_172051909](https://github.com/user-attachments/assets/1eb33ee4-c2f6-4b0e-8194-954c7d80fedc)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v32.5

### Other Mods

Mekanism, Ender IO, Create

**Comment by Tym0neK** [comment]
exactly the same problem would be nice if its fixed soon

**Comment by chorbintime** [comment]
report the issue to the inventorymanagement devs
