### ISSUE TITLE
crashing 

### ISSUE THREAD

**Issue by veinzsa** [LunaPixelStudios/Better-MC#1849]
### Describe the Bug

everything loads correctly but just crashes at the end

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://paste.atlauncher.com/view/d7de1bbf-a76a-46c5-932c-fe2abdae208e

### Operating System

Windows 11

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

1.20.1

**Comment by chorbintime** [comment]
you added the obscure api mod, which is causing the crash
