### ISSUE TITLE
Its says its not a valid mod file can i have help

### ISSUE THREAD

**Issue by VGameAC** [LunaPixelStudios/Better-MC#1850]
### Describe the Bug

Basically it keeps saying its not a valid mod file. This problem isn't about mine mine no mi not working, its about the file not being valid. Please help me.

### Reproduction Steps

1. Download both mods which i will attack in a zip folder
2. Run the game
[mods.zip](https://github.com/user-attachments/files/17064110/mods.zip)

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/35f3c2a1-4481-4725-82a8-18f6278b2f9e)

### Crash Report or Log

---- Minecraft Crash Report ---- // You should try our sister game, Minceraft!  Time: 9/19/24 1:06 PM Description: Mod loading error has occurred  java.lang.Exception: Mod Loading has failed 	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading} 	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft$$Lambda$3603/814150784.run(Unknown Source) [?:?] {} 	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading} 	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft$$Lambda$3386/1384323699.accept(Unknown Source) [?:?] {} 	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$436/1418851979.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading} -- MOD mineminenomi -- Details: 	Mod File: mine-mine-no-mi-1.16.5-0.10.1.jar 	Failure message: Mod mineminenomi requires forge 36.2.39 or above 		Currently, forge is 36.2.34 	Mod Version: 0.10.1 	Mod Issue URL: NOT PROVIDED 	Exception message: MISSING EXCEPTION MESSAGE Stacktrace: 	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading} 	at net.minecraftforge.fml.CrashReportExtender$$Lambda$3633/798319935.accept(Unknown Source) ~[?:?] {} 	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {} 	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) [?:?] {re:classloading} 	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft$$Lambda$3603/814150784.run(Unknown Source) [?:?] {} 	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading} 	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft$$Lambda$3386/1384323699.accept(Unknown Source) [?:?] {} 	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$436/1418851979.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.16.5 	Minecraft Version ID: 1.16.5 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_51, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 435948696 bytes (415 MB) / 1659895808 bytes (1583 MB) up to 3817865216 bytes (3641 MB) 	CPUs: 4 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m 	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec 	ModLauncher launch target: fmlclient 	ModLauncher naming: srg 	ModLauncher services:  		/mixin-0.8.4.jar mixin PLUGINSERVICE  		/eventbus-4.0.0.jar eventbus PLUGINSERVICE  		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE  		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE  		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE  		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE  		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE  		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE  		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE  	FML: 36.2 	Forge: net.minecraftforge:36.2.34 	FML Language Providers:  		javafml@36.2 		minecraft@1 	Mod List:  		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |NONE      |Manifest: NOSIGNATURE 		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |NONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90

### Operating System

Windows 10

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

36.2.34

**Comment by chorbintime** [comment]
you arent even playing one of our modpacks, or you added a bunch of extra mods
