### ISSUE TITLE
Crafting table lagging behind

### ISSUE THREAD

**Issue by Tym0neK** [LunaPixelStudios/Better-MC#1853]
### Describe the Bug

Im having an issue with the crafting table. As described in the steps any recipe crafted with stacks or even more items at once produces lag (not the client the world).

### Reproduction Steps

1. Open workbench
2. Craft anything with stacks

### Crash Report or Log

None

### Operating System

Win 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V32.5

**Comment by chorbintime** [comment]
Follow the [performance guide](https://rpg.prominence.wiki/performance-guide)
