### ISSUE TITLE
visual leather armor glitch

### ISSUE THREAD

**Issue by ZacDD** [LunaPixelStudios/Better-MC#1854]
### Describe the Bug

leather armor seems to have glitched out textures while being worn by either mobs or the player but seems fine while in inventory

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/63de9f21-48b8-4e85-b1e6-44b08a543927)
![image](https://github.com/user-attachments/assets/6abb8cf3-ad23-4915-8aaa-ac8633caad65)
![image](https://github.com/user-attachments/assets/e4f151e3-729c-42ed-be88-d5d032f8f491)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v32.5

**Comment by chorbintime** [comment]
try reinstalling on ATLauncher, updating drivers and disabling shaders. let me know if any of those fix it

**Comment by ZacDD** [comment]
tried everything but the problem still persists, it does seem like it comes back to normal once shaders are completely turned off. 
changing to different shader packs has the same problem aswell

**Comment by chorbintime** [comment]
Its likely a driver issue, or an issue with Oculus. Not much we can do, unfortunately
