### ISSUE TITLE
Armor break sound Crystaline Elytra Cape Slot

### ISSUE THREAD

**Issue by Tanner253** [LunaPixelStudios/Better-MC#1856]
### Describe the Bug

when crystaline elytra in cape slot flying causes armor break sound constantly

### Reproduction Steps

1.equip crystaline elytra, mending umbr 3 and fly
2.
3.
...

### Operating System

11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v8

**Comment by chorbintime** [comment]
update the mod that adds the elytra, if issue persists report it to the mod authors
