### ISSUE TITLE
cant craft natures compass

### ISSUE THREAD

**Issue by Tanner253** [LunaPixelStudios/Better-MC#1857]
### Describe the Bug

title

### Reproduction Steps

1.
2.
3.
...

### Operating System

11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v8

**Comment by chorbintime** [comment]
Update the natures compass mod, if issue persists report to the mod author

**Comment by Tanner253** [comment]
![image](https://github.com/user-attachments/assets/4b885848-f1dd-46a6-ba7e-8de366bb6e94)
