### ISSUE TITLE
Better Minecraft gets laggy by using shaderpacks

### ISSUE THREAD

**Issue by xXMitzuhideXx** [LunaPixelStudios/Better-MC#1858]
### Describe the Bug

Unfortunately if I play with shaders regardless which is it, the game is getting laggy and I have like 10 FPS. Without Shaders I have 144 FPS. I don't know what cause the issue but it can't be my hardware.

My System:

RTX 4070 TI
32 GB Ram
Intel I7 13700k

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

Better Minecraft 1.20.1

**Comment by chorbintime** [comment]
Follow the [performance guide](https://rpg.prominence.wiki/performance-guide)
