### ISSUE TITLE
File detection issues during manual install

### ISSUE THREAD

**Issue by GoldRequiem64** [LunaPixelStudios/Better-MC#1859]
### Describe the Bug

during the manual download part of install, mods are downloaded (into the downloads folder as specified), console states FileNotFoundException (mod name) OperationNotPermitted, stopping me from continuing install as normal
Java.io.FileNotFoundException: /Users/GoldRequiemDownloads/Mandala's GUI - Dark mode Mod Compat 0.2.7 beta Hotfix.zip (Operation not permitted)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Ventura 13.4.1

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v23.5

**Comment by chorbintime** [comment]
Reinstall the modpack on ATLauncher, and choose the version on the Curseforge tab of ATLauncher's instances tab instead
