### ISSUE TITLE
Music no longer plays in BMC5v3+

### ISSUE THREAD

**Issue by binury** [LunaPixelStudios/Better-MC#1862]
### Describe the Bug

~6 of us have spun up a new BMC5 server-- many of us use various third party launchers- Prism, ATL, etc, and not one of us hears in-game music; not even the Jukebox music player works. I've seen no-music bug reported a few times in Discord support although it doesn't seem to be a documented known issue yet

(5v4, 5v5, 5v6 also exhibit the issue so it doesn't appear to be a regression)

if I add a mod for it **I can see notifications that music is supposed to be playing but it is inaudible**

### Reproduction Steps

This occurs in fresh install

### Crash Report or Log

 5v2 (working) - https://mclo.gs/nP7VCET 5v3 (not working at all) - https://mclo.gs/W4h0IqX

### Operating System

Windows

### Minecraft Version

1.21.1

### Modloader

NeoForge

### Modpack Version

5v3, v4, v5, v6

**Comment by SHXRKIEgg** [comment]
Will be Fixed in v7
