### ISSUE TITLE
BetterMC 1.21.1 Fabric

### ISSUE THREAD

**Issue by SonnenPingu** [LunaPixelStudios/Better-MC#1863]
### Describe the Bug

net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Replace mod 'Improved Signs' (improved-signs) 1.4.2 with any version that is compatible with:
                 - minecraft 1.21.1
         - Replace mod 'mediumcore' (mediumcore) 1.0.0 with any version that is compatible with:
                 - minecraft 1.21.1
More details:
         - Mod 'Improved Signs' (improved-signs) 1.4.2 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
         - Mod 'mediumcore' (mediumcore) 1.0.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
        at net.fabricmc.lo

### Reproduction Steps

install v9 on server

### Operating System

Linux

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v9

**Comment by SHXRKIEgg** [comment]
Remove the mods you added
