### ISSUE TITLE
Oak crafting table broken/missing mesh, which also causes crashes on waystone teleport

### ISSUE THREAD

**Issue by TheDandyGuy** [LunaPixelStudios/Better-MC#1864]
### Describe the Bug

The oak crafting table has a missing or broken mesh (purple and black checkerboard) for me and my friends server, and it wasn't a problem until we started using the newly added waystone mod to teleport. I noticed that when I had an oak crafting table placed near our home waystone, teleporting back to that waystone would always cause a crash. As soon as I removed that block from the nearby area, the crashes would stop happening. I checked a lot of other things first, but finally realized it must have been the broken crafting tables.

I'm not sure what's causing this strange interaction but I'll attach a crash log so someone smarter than me can look at it.

### Reproduction Steps

1. Place oak crafting table near waystone
2. Teleport from another waystone to the waystone with a crafting table near it
3. Crash

### Crash Report or Log

https://pastebin.com/eCS9xKfQ

### Operating System

Windows 11, Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

logo Better MC [FABRIC] - BMC3

### Other Mods

none

**Comment by chorbintime** [comment]
Try updating the Visual Workbench & PuzzleLib mod. If the issue persists, or no update is available, please report the issue to the mod author.
