### ISSUE TITLE
The crafting terminal started lagging after clicking on the magnifying glass.

### ISSUE THREAD

**Issue by WorkShop02** [LunaPixelStudios/Better-MC#1866]
### Describe the Bug

Every time I open crafting terminal or classic/advanced wireless terminal it starts to lagging.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://github.com/user-attachments/assets/75c5b4f1-4035-44b4-a8a4-7c260b4f1522

### Operating System

win 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
Follow the performance guide https://rpg.prominence.wiki/performance-guide

**Comment by WorkShop02** [comment]
> Follow the performance guide https://rpg.prominence.wiki/performance-guide

Well :D My mistake I forgot to write the details of the game settings, I'm using the official Curse Forge launcher and I have 8GB of RAM free from the 16GB I have in my pc. I was more trying to point out that it starts to lag after I click on it. I wonder if there is somewhere in the configuration to deactivate the book/recipes when REI is in the modpack. :D
