### ISSUE TITLE
Villages and structures does not spawn on the server

### ISSUE THREAD

**Issue by stevenmatts** [LunaPixelStudios/Better-MC#1867]
### Describe the Bug

So i have looked through config and structures are set to true. But i have failed to spot any village. Some dungeons are spawning, but 99% of these are big towers with some jacuzzi and narrow towers with ladders. Ofc some fireplaces scattered around the map. But as i have seen the modpack contains more structures to offer. I am using 1.21.1 version of the mc
Also i could spot any 'when dungeons arise' structures. I have attached the log file from the server console on wetransfer

### Reproduction Steps

1. Downloaded the bmc3 fabric v10, started it using bat file
2. agreed to eula
3. when world generated, i entered with curseforge loader with the same version of the modpack
4. 4. explored the world and see only a few structures

### Crash Report or Log

https://we.tl/t-bBmqDKWvoD

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v10

### Other Mods

no other mods except bmc3

**Comment by chorbintime** [comment]
Structure spawn rates are intentionally lowered. You can increase rates by removing the sparser structures mod
