### ISSUE TITLE
Water bucket in dispenser dispenses bucket as entity [BMC3 1.21]

### ISSUE THREAD

**Issue by ollie5050** [LunaPixelStudios/Better-MC#1868]
### Describe the Bug

When you put a water bucked into slot for dispenser, and push button it dispenses the water bucket entity, not water/source block of water.
This occurs on both current version (V10) and was first noticed on v8. 

### Reproduction Steps

1. Install current version (v10) 
2. Launch game
3. Create new world (also tested on server version)
4. give yourself dispenser, water bucket, button
5. Place down dispenser, place button next to dispenser on solid block
6. Open dispenser GUI
7. Add water bucket
8. Exit dispenser GUI
9. Press button

### Screenshots and Videos

![2024-10-10 16_46_02-Better MC  FABRIC  1 21 1](https://github.com/user-attachments/assets/13613927-62e1-47e2-8f97-471800bbdd1c)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v10

### Other Mods

No other mods.

**Comment by chorbintime** [comment]
will be looked into next update

**Comment by Deetss** [comment]
This is also happening on v12 fabric 1.21.1

**Comment by SHXRKIEgg** [comment]
Will let the Dev know, not sure if they will fix it though
