### ISSUE TITLE
Fractureiser

### ISSUE THREAD

**Issue by KENZOBASAR** [LunaPixelStudios/Better-MC#1869]
### Describe the Bug

fractureiser is found in this modpack. Please remove it.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10 And 11

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

Idk

**Comment by chorbintime** [comment]
lmao what
fractureiser hasnt been a thing for like a whole year. i am literally the person who made knowledge of fractureiser public and i can personally verify that almost everyone responsible for fractureiser is currently in german prison. the servers that fractureiser sends info to were also taken down within like 10 hours

**Comment by Vazkii** [comment]
why arent u removing it then

**Comment by valiray** [comment]
ya chloe, what the flip

**Comment by chorbintime** [comment]
lunapixel is evil and we love malware

**Comment by nthxny** [comment]
this modpack hacked my computer and stole all of my VBucks

**Comment by NyagiByte** [comment]
fracturizer ate my parents!!!!

**Comment by nvb-uy** [comment]
john fractureiser just loves playing bmc

**Comment by Xplodin** [comment]
Fracturizer stole my cat :(

**Comment by Szedann** [comment]
I fractured a skeleton playing your modpack, please remove

**Comment by KENZOBASAR** [comment]
Shut it.

**Comment by NyagiByte** [comment]
> Shut it.

 The Bee Movie Script but it's just vowels

Aoi o a o a o aiaio ee i o a a ee ou e ae o

I i ae oo a o e i a ie o o e ou

e ee o oue ie aa eaue ee o ae a ua i i ioie

eo a eo a eo a eo a

Oo a a eo

e ae i u a ie

a eaa i ea

oi

a o a eo

eo

a

Aa

a ou eiee i i aei

I a

I i ou u

ooi a

Ue e ai ou ae ai oo oe o oe

o I eie

ee e auae

ee e ou o ou o

A ee eo a a

e ou

a I o a i oi ee

ou o i o ou u

O a e

ae o u e e i o

e

a I o ou o i i e oue

e Aa

e a

I a u e

A ie eia a auaio

ee ou I ae i

ee a ae oo ee a i oo

oe ee aa

ee a oee I a I oo a a a iie aou e ie

ou i oe a iee

i a Aie oi a uae oo oo

ea aou aie

ea

ou oi o e uea

o I o oi

Eeo o i oeoe ou ie

o ae i o a uie

u a oea

I ue e ou ae u oe ou o e a

I oe i iooai a auee a io ou a

a e o ee aaio

o uie a i o o ue e iuae

e Aa oa e ae e

e ae

eee

Ae

aeua

ue au iiuie ee

eae eoe ea ue

eoe e ie i auai a o

a oue ou eeoie A ei ou aee a oe Iuie

i e i ou o oa

I ea i u oieaio

ea u ee e o

ee ou a a aea iie e a a a ie

oe a i e ie

A ie a

eoe o oe a iiio o oeo a a a o e eao ou

i i i

o

o

e o a ou a a ee ae oe ou oe ie o e o e oi ee ou a o o ou oe ie

oe ei e ou aia oe o i e ea o e ie

Ou oee oua i auoaia oooee eaue a ueooue io i ooi ee u i i iiie oe o ou o a oe

a i a o

e oui

e i

e ee a oui

i oue i

A oe e oa ie o ioe ee ae o ee eiee

ee ee ae eei a e ee eoo

a o ou i e ae

o eou

ee e ae ou ae aaee e ea

a oe a o

ae a ie a o oe a a ae ou ou i

ae u iio

a aoe o o e ea

O oue o ee o ae a oe

u ee o a ee a o i i oe e ea a o

u ooe aeu eaue ou a i e o ou i o e e o ou ie

e ae o e e o ou ie I i o a

a e ieee

ou e a o o a ee a a eie ae a oe a o i iio ea

o ou u o u o ea

e ue

o a e i

a e ieee

o a ou a a

Oe o oee

a a iae oie o ae o ae

I eiee o e o ae o ae oe eiio i ie

u Aa o ou e ee ae o u a

ou ou ueio ai ee ee

ee e o ee uioi oie o Ea

ou ee i ae i o a ie oo e ee

ie a ie e oe eae

I o o u ou o a I ai aou

eae ea e ae oa ea oe o aoa

ai a eo e i ou

e oe ae oe o

o

Ie ee ee e i oe

e o a i ie ouie e ie

ea u oe o oe a

e o

i o

ou u i ea

oue oe

oue ea I oe i I oe i

I oe ee e ee

I o o

ei a o ae

Ouie e ie i o o ee oi o o a

ou a u eie o e a oe o ou ae o e e o a

i

oo a oe oe a ou a I i ee i a ieie

I u a au o

ee ae oo u o i

ea Ue oue eai i a e aie ee ou eai i

oe aie

Ae e ou oui oo

ia ia

oo a ee o

oue o ie a

e ae u i e

I u e aeou ei a oe o

ea Oe a ea ie e aai a uoo

e a a a o oa a i e oe e a ai e

O

I ee ou I o i ou

a ee ou oi ui i

i o ae e auoiie

I a auoa a

A ie u ou ee oa a i oae

ea u

ee ii a uoe a i ie o ee ooo

i ie u

a

A ue u o u u ae oue o u o i

ae I a

ou ae o

ee oi a ae

a o ou i uo

Ae ou ee eou

I i e I a ee o a ea

e oe

a ou uie e

ou eie a oue ieee i

e ee a o o oie

u ou o e oe

o ou ee e oe oi e ae o ee a

o e e e ou aou ii

ou a a i a ou u oe i aou a ou i i aou

ou e oue io a

I a eauiu i

ou o a e oe I i aou i

ae e oe ie u i i o e

ou ee ii o a ai aoo aia

a a a o o a u i a ie

ae ou o o ue e a o o io oe

a ou ae o u oeie

I o i o e u

oue o u oue oi io oe Ou o e ie

oue oa e a ie

o oe iei o e

ai i ou ee e i I ae

I ou a ai i o

I oa e a a aoo

e oe oe oe a eeae

ae I iee oa ae aeae a u i a aoe e a o oo a a eeo a

I o ou

ee ai o oa

oa e a

oe o A e oo o i e oe

ea i

oe oui u ee oui ie o e ai eoa

I i i aaiae

a o o e

Oe o e ou oauaio

e o e ie

a ou e

ii u ou ea

o

oue o eie

e i Ou i a e ae ea

ae ou oie

ou a o o i

o ou o

O a aaiae

eoo aea oe o o e eao ou i

A ae o ei e ea

ue oue o

I o e ea u oe ou

a oe aa oe

e ea oee u aai

a aee

A ee ie ae a oei ee e ea Aoe ea oe

ea eaiie o oe ea

ea o e e u ea o e e o a ie

O i i o a

eai ooi u ee oue ie ui ieo ue ee i ooiao ie ueio ie ae

a a o ou i I ou a

a

A i ee o e uoe a i uaa ie

a aee o ou

ee ae ou

I oi ou

Ou Ou ee

Ou ee

O o

I ae o eoe I o o o o e e o ie

oue oa ie oue a eo

Aoe a oi i

I aoe eei ae ee a oea ei o a e ei oe oa

e u

oo a a

I a e i e a eea

o i o i e eie

I O ou ee oa ae i u

ea eei u ae ou

i ee ee u iiia a

a ou

O

ou o a ai aio oa a a ou a o ee ao i ai

o e aeu A aa a ou oo oe i o i ea a a

Ao I o a oue o eo o oo ee ei oue o u

u i a oe eaue o i ai ie a iaa

a au

A a eie o ou ooie ee a ue oe aoue o ai o ua

A i au oiio

u u u u u u u u u u u u

a a eo

eo

ou ea o i o o

ea ea i i o

i e

Aeae e

ea a e

i e

ie e

ae ou o o e

O aie

e oe i ou

ou oe euia ou ie eue

A o ou ai oe oe

o I ou

I a eiee I ou

o ue

I ee o a a ee

o ie

o

oe

i i ue eae e ae oe iua

i i aou eee a o

oe

eee oe ii i aou

a o e ie i

I o a i o a i

a i oe ea oeo

Ee ee oiaio u oe

o i

I i u oe oe ee ie i oe ee ae a a oe ee a i o a oe

ee a I a ie i o ai

a aai o e o a

a oe oe oe oe oe oe oe ea oe oe o u

oo

I ii u a o o i eo ou e aiie o e ee oe

o a iua

ai Oe o ee oe ee o e o e oe

a aai oue eoi a oi oe

Aiaie

a a o e ie

i i e ooe a i i

I o o u I oi i oo

I e oo

o ie a oe u I ie i

ea u

eia

aeu u I a ie a

ee o o ee

aai e o ee

oe

u

i ou e a

Aiaie

e oe

oa u

aa ie o

ou ae a ou o oiio ooie

oi i a ou ie a iie

e e

I o i ee ae oe

ou e e i

I i e o

a i i

a oi

ou a a ai u oe eaue oue aou o ea i

oe

o

ee a ee i e a

o oei

I ii

i ee

e a ee

e oi o i e

oo oe I ou o oe e o i ou eee

e ie

a i a

a ae ou oi

o e eio ee ou ee i ueieae

I oa e oe

a i ai a i ai a i ai

aa aa ee oi o

e ou ou oe e io eae

e ou ou oe e io eae

e ou e eue I ae i io a oou oue ou ee o ou

O o oe ua I o ee i

a a a

ae i ie i ie i ie i ie i ie i ae

a i iaoia

I aai I o a eia i ee oe aoie oie

a ue oe a a

a I o o o a i o u

o oe e ou a o e ee ou o ei i

e I eae a o ieie ee aeae a eiee a I a

ee e u ae a a a ou

I o eee e u ai a i o i

I eie oa ai I ou ee i ei oe A i I ou i a u e

ai o ee

a a ee ae ie oo

ai

o i i

ou o I aei o e i i ou i e

oe i ie ae e aue a ou

oe i ie ae a e aue a ie I a ou aee

I u ai a ie a aue ou o o a e aae o eei

oue

ee ou o ie u

I o ae o iI a aei i

u a o ou eue oue

oe ae ou u u

ae i oe o ou eia i

oi oeoe ou i ao a eia i

i e aea a

aea e ee ou i

ue e ou o aee

ou ou u ao i o ee

e

uoe o e e aoie

e

I oa a oei e ae ie I oa a oei

A i ee i oe

a

a ou I a

I ou ea e i oue I a ee a oue o uoe o a o a ua

I a eiee I oi i Ie o o

O I a o i oe o

o e o o i I a

o ou I a i ou ie a o a o oo

ee e oe ea ou oo

i

I o oue ai

e I o

oue ai

I o o

o i O I ie

I o I eai u I o ea oi o e

e I ue i i e ioei

i i a i o a uie o e I ea oue a ee

I a A I o uoe o e oi i u e ee a i o i e

A i i a o ou I a o a ou I u o I a aie

a a a ie ei I ai i a ee

ea

I ai o a ee A e ee i ai o e

I u a o a I aeu

I eae o

ai o i ou ea o o a

a

e ai i

ae a ou i I ue aa aa oe ou i i u

a e u

ea

ee ae u I e i au e i a e ae o ea i

Aa a I e ou oei

ie a

I o o I ea I o o oee

I o a o u ou ou

I o oue I ae o iue

I u oee

I ae o ioe

o e iiuou

Aua I ou oe a u

e ou a u ae

I ou

ae oe

o I a

oe o

I i o oe a oue ioa

ee

ee ie o e

ou oo ea

I o o i ou o ai aou aio

Ae ou a i

o

e ai e ie i e a a ee i u aio

e ia e ee

e u u e e io e u

e ei i o

A e a aeeo

I ou ou ai uaeaa

ou I a a aeeo

I a a ee oe

a e i o u e o

ea iee

o a ae ou oa o a

Aou o I o o

I a o o a o e ie u I a o i e a e a

I o o ou ee

ou o

ue

ae ae e o e a ae o a oo u I ae o e a oi

ea

o iee i oe

Ou e uee a u eee i a ae aai oa

Aa i ou oo ee ie i ee ee i

oue i ee eao

e I i o e ue o

o a I o a aea I o a oe i ee oe

o i u i o ei oe

o

I ie ui a a o ou ee

ae I a

ou a i aa

O ea ie

u ai o u o oee

Aa i a ee ea

a o e oee

ea i o oue

o I ou ii i I I i I e u e e o ie

Ae ou

a I ae a iee o i i e

ue ee ae a u

a

ea

A i e e I ue I ee ou aou O o

O a

A a ou o u aai o eoe

O a a a oi

e o oi u Aa

i a oi o

e a e o o

e a a e i

O ae u e ue

ou aai

I a aai

I a e aie aie oe o ie

ua I a eiee ou ee i ua

ia a ua

a ee e ie

ue a a e a a

e ea a ia i

e ie a

o e a i ou ie o

oe o e u oe o e o

o ou e a

ooe

ou i i a I a ou a aee ou ae o ee

ou a ou eeiee o ou a i ou ouo a e oa

e

e

e I e oeoe

ou i a e eei

A a ou ae i i ou

o o o o a a

ie

I o aae o ie

I o i e oe i i e ei e a a I a e a ae

o o i e

e ua

o o a a ee a ou ou ea a ee a

e ae aea

O o

e o ie A e a oi

O o oue ai a ua oi

ee o ai

oue i ouie e ie ai o ua a aa ou oe i oe ae a Oeei a i o aie

e ae ie A e uea e

i i oe

Ea i

i i o oe a a a

e a i a u

I a o ii ie

A a o a e ea

a a a o a e ea

ou o a a iao i

o

I ea a iao a oi e ea i u

i o

ea o

ie o e

e ae o e ee u

ee u a ee e

e u o a e e ea a i eai

ee o eai o eai ie o e

ou ae o o a ii ee ie ii ee

ii ee

ii ee

ii ee ii ee ii ee ii ee

ee e i e i e oo

ou o a ou oe i a

I oa a ii ee

o u oe i i o o

I ee ee a ae ou oi

Ie o a o o i ie eiio o i aou

a ie ou ae o ie

ou ae o o oue ae a ee

ou i i ou o ae a ie oe

a oe ou ou ae ai o ou

ai ou ou a o i

a I ai o ou

ou oi

o eei

A e

o aea I a u

o e oo o

a i

aea

ee i ee

I o ou o o e a i

e oe eo o ei

e e a e

eaue ou o ie

I o iei o i

o Ie oa o

ee ae ou oi

I eei a ie

A i I i ou a eie

e

I u oe e eei

e ae a ue aae o oe ee ea i aaea

o e i e ouae o oe a ee oi ea

U o a oa uoue oe o eei

A ouae o e oe oee i aei ee

o A i Ie o oe

o oe ou o eeee

I eaui o ou u eeee I ae

ea O I ee I ee

A i ou u

io ou a u eee ie a iae

ou o ae a

e ae io u i a ieae I a oie oie ieae

O

u ee

ou u a o i a oe e

e o o i I uua aa o u

o ou ae o a ou ee

e aeu

ou i a a ae a a ie a a ee a o i ou o ou i ie a eoio Ae eaou u

O ooe Ae ou O

ea

a i o i ou

I a u

e o oei ao

e ou o ee ou ee

a a a A i ae iua

ea i a o i ou o

I e ie aou ae eeie i e u ou ii

oue ea o a o o a iee

I o a oui o Iaia oue

I e

a i e ae o i eue i i

o i i e ee ue ee oe oo a ioa iae ee

I e a ao

I ee ea o i

i i ee

o eoe e ea i

ou o ae eou oo o ou o

e e

o o ou e i

ee ae i

I o o ae i A i a o ae i

ee eai ooi ii ou ee a oe ea i

I oai

I ouai

I u oe a

u a

ee o o aou i i i eai A o o eai

oue ae ou oe oooia i i a e ae

A i o ae I ei o e oo o i

I ei o e oo o a o i

e eo ou ao oe

Ao

e i ee I ee i

e I ue I o oe o a u eae i ie oe ou i o oe aou

oue ue o o

I e I ea oei

o ou a a

I a a A o ou a ai

ee ou ei e ee u o ou uie

I o uea

I ou e ee ie

e a i e a o o i ue ee

oue oo ae I ou o

ou i ae oe e o o

ou i i e u o iuaa Iaio

ee i e oe oi o e e ee

oe a I oe o oe a

a eo

a oie i a aee ee

ee ae e ee e a i e A o

ee o e oa o oee

u ee i

a oue o ea

o I oo ea e i ie ai a oe ee ou eae

o oe a I a oo oei ue ee

I oi o Aaa ooe oo a u o ou ea o

I oi o aoa

A ou
