### ISSUE TITLE
Backpacked doesn't open with B

### ISSUE THREAD

**Issue by findbl0k** [LunaPixelStudios/Better-MC#1870]
### Describe the Bug

Backpacked doesn't open with B

### Reproduction Steps

1. Press B
2. nothing happens
3. rebinding doesn't work either
4. If it needs to be crafted, not explanation of that anywhere
...

### Operating System

Win 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33.5

**Comment by chorbintime** [comment]
you need the backpack equipped
