### ISSUE TITLE
Aether redux:sign crashing my aternos' server

### ISSUE THREAD

**Issue by jodhyrbz** [LunaPixelStudios/Better-MC#1872]
### Describe the Bug

Hello, when i log in my aternos server, its crashes and says that it's because of a sign from the mod Aether Redux, it also crashes my solo world when i log in..  

here's the log : 
[latest.log](https://github.com/user-attachments/files/17368309/latest.log)

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

BMC3

**Comment by jodhyrbz** [comment]
okay i agree on the aternos part, but the thing is that even in my solo world when i open my world it crashes my minecraft

> we offer no support for aternos whatsoever - use the serverpack on the modpack files to selfhost a server for free or use the built-in world sharing by clicking "share world" in the escape menu on a singleplayer game

**Comment by jodhyrbz** [comment]
i tried creating a new world as an example, and it crashed : 
[crash-2024-10-20_18.02.16-client.txt](https://github.com/user-attachments/files/17451025/crash-2024-10-20_18.02.16-client.txt)

**Comment by chorbintime** [comment]
update aether redux, if the issue persists report the issue to the mod author
