### ISSUE TITLE
bmc2 fabric crashing at boot

### ISSUE THREAD

**Issue by GLOSHSEP** [LunaPixelStudios/Better-MC#1873]
### Describe the Bug

On a fresh Arch Linux installation a fresh installation from Modrinth of BMC2 Fabric will crash when the splash screen loading bar is almost finished 
Modrinth gives no exit code

### Reproduction Steps

1. install bmc2 fabric from modrinth on a fresh arch linux installation 
2. launch the game 
3. crash
...

### Crash Report or Log

https://gist.github.com/GLOSHSEP/acea0a4e42d30475b97e0559bbc6f4bd

### Operating System

Arch Linux

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

V25

**Comment by chorbintime** [comment]
do you have an hs_err_pid file in your main modpack directory?

**Comment by GLOSHSEP** [comment]
Oops sorry here https://gist.github.com/GLOSHSEP/860fce3e5724850e00d22767b07e2f9a

**Comment by chorbintime** [comment]
update the sound physics remastered mod
if issue persists report the issue to the mod author and remove the mod
