### ISSUE TITLE
BMC2 crashed on loading - stack smashing detected

### ISSUE THREAD

**Issue by Grand-Ben** [LunaPixelStudios/Better-MC#1875]
### Describe the Bug

Using Multi MC 5, I added the bmc2 modpack using the add instance button from Modrinth. I launched it and it crashed upon loading. 

I'm using Manjaro Linux release 24.1.1,  a Dell Precision 7520 laptop. 

### Reproduction Steps

1. Launched
2. It loaded for a while.
3. Never completed.  Crashed with exit code 6.
...

### Crash Report or Log

https://gist.github.com/Grand-Ben/755ce0040063d64f20ee537218cd5f0e

### Operating System

Manjaro Linux - release 24.1.1

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

25

**Comment by Frontear** [comment]
Please download and use the latest version of `glfw` from your distro’s repository. If you use wayland then you will instead need a patched glfw source build. The AUR has one, since youre on Manjaro, so use that (called glfw-minecraft-fix).

**Comment by Grand-Ben** [comment]
That worked!  Thanks for your assistance.

**Comment by Grand-Ben** [comment]
I should mention that there was not a file called glfw-minecraft-fix in the AUR repository, but there was a glfw-wayland-minecraft-libdecoration file.  The posting by Admicos at github.com/Admicos/minecraft-wayland was also helpful.
