### ISSUE TITLE
Enchanting tables and Dark Oak Crafting bench missing textures

### ISSUE THREAD

**Issue by KrozacNexus** [LunaPixelStudios/Better-MC#1876]
The above workbenches have missing textures in V9, but have correct textures in V10+. Not shader or resource pack related, issue persists after disabling either one. 
![2024-10-20_12 54 22](https://github.com/user-attachments/assets/cfb70aaa-012b-40cd-a73f-2a0e0108e190)
![2024-10-20_12 54 33](https://github.com/user-attachments/assets/df78e807-37d9-44d2-8826-2b27f3c03a8a)

**Comment by KrozacNexus** [comment]
This is on Fabric 1.21 v9 of Better MC. Both server and client are running v9

**Comment by SHXRKIEgg** [comment]
If its fixed in v10+ then update the modpack?
