### ISSUE TITLE
Errors in currently selected data packs prevented the world from loading

### ISSUE THREAD

**Issue by catarotaru231** [LunaPixelStudios/Better-MC#1877]
Hi, i've been playing BMC (FORGE) 33.5 with a friend( I'm using e4mc( F 5.2.1)). Today, when i tried to open my world it had this error that said my data is corrupted. I have to mention that i got this error after beating the ender dragon and wandering the end, not going back to the portal finishing the game.

Here's my log:

https://paste.atlauncher.com/view/0dea767d-2a47-4745-a9b9-adc7d1a7ab10

Is there any way i can save this? Thank you

**Comment by chorbintime** [comment]
try installing https://www.curseforge.com/minecraft/mc-mods/long-nbt-killer
