### ISSUE TITLE
Can't enter the end

### ISSUE THREAD

**Issue by lucifersspawn** [LunaPixelStudios/Better-MC#1878]
### Describe the Bug

Game gets stuck every time I try to enter the end and have to force close it 

### Reproduction Steps

1.Just trying to enter the end to kill the dragon
2.
3.
...

### Crash Report or Log
-805306369
_No response_

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33.5

**Comment by chorbintime** [comment]
Follow the performance guide fully https://rpg.prominence.wiki/performance-guide
