### ISSUE TITLE
i cant join my world

### ISSUE THREAD

**Issue by klazustrem** [LunaPixelStudios/Better-MC#1879]
### Describe the Bug

aparently i got a single player world, i was opening so my freind could enter, we failed so we forgot bout this idea, on the next day me trying to join my hardcore world getting a weird error on the "world loading" like the server error, and after it pops the ony button i can press redirects me to the lan servers with bisecthosting ad

### Reproduction Steps

1. create world
2. open it to other players
3. relog
4. problem is made

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/4acbacf8-f47f-4222-98ea-151717c1b8e8)

### Crash Report or Log

-

### Operating System

macOs 15.0.1 (24A348)

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

idk like the latest

### Other Mods

[Let's Do] all mods and addons except throwable cheese
<img width="820" alt="image" src="https://github.com/user-attachments/assets/1487cd20-94b0-41b8-8dc4-6923e140aabb">
<img width="834" alt="image" src="https://github.com/user-attachments/assets/2e4281a7-0a1d-4b8d-a57d-486f9bd32c60">

**Comment by klazustrem** [comment]
the version 1.20.1
 NOT 1.17

**Comment by klazustrem** [comment]
i wanna add that if i creating a new single player world the same error pops, what is wrong?? maybe i can fix that??

**Comment by klazustrem** [comment]
upd.
my version is better mc2 fabric

**Comment by chorbintime** [comment]
Its likely due to the mods you added. You can retry on a fresh install on ATLauncher
