### ISSUE TITLE
Items and Armor disappearing from inventory  

### ISSUE THREAD

**Issue by SgtKrhea** [LunaPixelStudios/Better-MC#1880]
### Describe the Bug

Was using Leviathan grapple hook, froze for a second, unfroze and 95% of my inventory was gone. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

-

### Crash Report or Log

-

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

-

**Comment by chorbintime** [comment]
v28 is very old, we offer no support for old versions
