### ISSUE TITLE
Vein mining not vorking

### ISSUE THREAD

**Issue by polskiunbreaking** [LunaPixelStudios/Better-MC#1881]
### Describe the Bug

I have set a kay for vein mining but not working while im holding it (1.21)

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

0.16.5

**Comment by chorbintime** [comment]
you need the vein mining enchantment and need to hold down the keybind
