### ISSUE TITLE
start .sh wont run

### ISSUE THREAD

**Issue by ItsKruml** [LunaPixelStudios/Better-MC#1882]
### Describe the Bug

the start .sh file quits after a second and errors out saying
`Start script generated by ServerPackCreator 6.3.11.
To change the launch settings of this server, such as JVM args / flags, Minecraft version, modloader version etc., edit the variables.txt-file.
start.sh: 383: Bad substitution`

os: ubuntu 20.4.1

im only using the commandline with ssh

### Reproduction Steps

1.  use Wget to get the latest version from curseforge
2. run the start.sh file using `sudo sh start.sh` or `sh start.sh`
3.see that error
4. fix it (hopefully ;) )

### Operating System

Ubuntu 20.4.1

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33.5

### Other Mods

none

**Comment by Frontear** [comment]
Please use `bash` instead of `sh` to run the script. Also please don't use `sudo` :), in general its a very bad idea to run any kind of program randomly with the highest privileges possible.
