### ISSUE TITLE
Impossible to join or create world on mac M1

### ISSUE THREAD

**Issue by MercierCharles** [LunaPixelStudios/Better-MC#1883]
### Describe the Bug

When trying to create a world a sigbus error happen with exit code 6 (tried different minecraft launcher such as curseforge multi mc or prism)

### Reproduction Steps

1. use Mac M1
2. create world
3.
...

### Crash Report or Log

https://pastebin.com/D3jnNZF2

### Operating System

Mac OS Sonoma 14.2 (23C64)

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33.5

**Comment by dogoryan** [comment]
https://github.com/LunaPixelStudios/Better-MC/issues/1583
