### ISSUE TITLE
Serene Seasons season duration config is not orking in BMC4 v33.5

### ISSUE THREAD

**Issue by dimtrunov** [LunaPixelStudios/Better-MC#1884]
### Describe the Bug

Serene Seasons sub_season_duration in sereneseasons-server.toml config is not working in BMC4 v33.5 both, single- and multiplayer. Works fine with the same Serene Seasons and sereneseasonfix mods versions in v32.5

### Reproduction Steps

1. Open singleplayer world or connect server
2. Check Serene Season's Calendar

### Screenshots and Videos

![Screenshot 2024-10-25 150621](https://github.com/user-attachments/assets/44a33b28-da0b-4cf4-8005-70b5451725a2)
![Screenshot 2024-10-25 150653](https://github.com/user-attachments/assets/59a9a269-12ad-4985-84c3-20fa160106d0)

### Operating System

Win11, any

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33.5

**Comment by chorbintime** [comment]
Update the Serene Seasons mod, if the issue persists / no update is available, then report the issue to the mod author
