### ISSUE TITLE
Vein mining not working

### ISSUE THREAD

**Issue by polskiunbreaking** [LunaPixelStudios/Better-MC#1885]
### Describe the Bug

I have enchant on pickaxe "vein mining" i set a keybind ` and while im holding it it doesnt work on cobble and deepslate, but on ores its working 1.21

### Reproduction Steps

1. vein
2. not 
3. working
4 propely

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v10

**Comment by SHXRKIEgg** [comment]
` key doesnt work, use another, worked for me

**Comment by polskiunbreaking** [comment]
not working bruh
