### ISSUE TITLE
Crash on Debian when starting mod downloaded from Forge Launcher

### ISSUE THREAD

**Issue by NoahShomette** [LunaPixelStudios/Better-MC#1886]
### Describe the Bug

When launching mod it crashes while loading with the following error code and text:
```
The game crashed whilst initializing game
Error: net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'client' due to errors, provided by 'aaa_particles' at 'mod.chloeprime.aaaparticles.fabric.AAAParticlesFabricClient'!

Exit code 255
```

### Reproduction Steps

1. Launch minecraft with modpack installed

### Crash Report or Log

https://pastebin.com/FEGqnBBG

### Operating System

Debian 12

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

33.5

**Comment by SHXRKIEgg** [comment]
Install aaa particles mod
