### ISSUE TITLE
item frame not allowing to display items

### ISSUE THREAD

**Issue by mrsurnom** [LunaPixelStudios/Better-MC#1887]
### Describe the Bug

so , I wanted to craft an item frame to put on some lapis lazuli mixed with some amethyst , and it didnt worked , I tried an vanilla item in case but it didnt worked either , may you fix this bug please ?

### Reproduction Steps

1.
2.
3.
...
simply place item frame and try putting an item in it

### Operating System

Window 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

its v12 and in 1.21.1

### Other Mods

none

**Comment by chorbintime** [comment]
Update to v13, and let me know if the issue persists. Please record a video as well
