### ISSUE TITLE
worn backpack from imnis mod disappears

### ISSUE THREAD

**Issue by Markv02** [LunaPixelStudios/Better-MC#1888]
### Describe the Bug

I'm playing with a girl in the v12 build on Fabric and 1.21.1

This is the second time that something like this happens that when I create this backpack, put it on my back and after re-entering the game, this backpack along with all the loot disappears from my back 

### Reproduction Steps

1. I don't know how to repeat this
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v12 Beta

### Other Mods

No one

**Comment by SHXRKIEgg** [comment]
Fixed in v13
