### ISSUE TITLE
Game Crash to launcher on load of World

### ISSUE THREAD

**Issue by Jam13Gaming** [LunaPixelStudios/Better-MC#1890]
### Describe the Bug

The game crashes at the "Saving world" step of loading a previously saved world since updating mods in mod pack.

### Reproduction Steps

Load World
Game crashes to launcher

### Crash Report or Log

https://pastebin.com/h2ercFbc

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33.5

**Comment by chorbintime** [comment]
Do not update mods in the modpack
