### ISSUE TITLE
Getting long names instead of actual ones

### ISSUE THREAD

**Issue by Chis900** [LunaPixelStudios/Better-MC#1891]
### Describe the Bug

Names show up as "block.variantcraftingtables.spruce_crafting_table" instead of "Crafting Table". Or Minmap directions shows as "gui.xaero_compass_north" instead of "North". Check image.

1.21.1 FABRIC 0.16.7- BMC3 v13

### Reproduction Steps

1. Open game

### Screenshots and Videos

![2024-10-28_00 13 18](https://github.com/user-attachments/assets/f26c2763-3814-4781-9019-12effee214f8)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v13

### Other Mods

No

**Comment by JuanchiWachi** [comment]
Lenguaje / Language
-
Bro, yo tuve el mismo problema. Puse el juego en español y quité el ingles de la lista de idioma, y me generó ese problema. Solo agrega el español y ponlo arriba del idioma ingles y se soluciona.

Bro, I had the same problem. I put the game in Spanish and removed English from the language list, and it caused me that problem. Just add Spanish and put it above English and it will be solved.

**Comment by chorbintime** [comment]
Set your language to English
