### ISSUE TITLE
(request) Add Oh the biomes we’ve gone for 1.20.1

### ISSUE THREAD

**Issue by vinnyg0621** [LunaPixelStudios/Better-MC#1892]
### Describe the Bug

for the 1.20 version of this pack, you should add oh the biomes we’ve gone like before 1.20 you added oh the biomes you’ll go!

### Screenshots and Videos

https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-weve-gone

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

33.5

### Other Mods

oh the biomes we’ve gone

**Comment by chorbintime** [comment]
The modpack has been around for very long, and people already have established worlds. Switching a major world gen mod in the end of the pack's lifespan is not a good idea. If you want Oh The Biomes We've Gone then play our newer 1.21.1 packs.

**Comment by vinnyg0621** [comment]
oh i thought you were gonna just add it, not switch it from BoP.
