### ISSUE TITLE
Dispenser is not working properly

### ISSUE THREAD

**Issue by BLAZXENO** [LunaPixelStudios/Better-MC#1893]
### Describe the Bug

I made an automatic chicken farm, however when the eggs are dispensed from a dispenser they never whether it is manually with a lever or automatically with a redstone clock, i have checked many times and i am 100% sure i am using a dispenser, however this bug is preventing me from properly using it

### Reproduction Steps

1.place a dispenser down
2.place a level next to the dispenser
3.fill the dispenser with eggs
4.continuously flick the lever until empty
5. No chickens would have hatched

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33.5

### Other Mods

just a heads up the version i used was 1.21.1 not 1.20.1, the option to pick 1.21.1 was not available

**Comment by chorbintime** [comment]
Tracked here https://github.com/LunaPixelStudios/Better-MC/issues/1868
