### ISSUE TITLE
worldedit mod incompatible

### ISSUE THREAD

**Issue by xVryz** [LunaPixelStudios/Better-MC#1894]
### Describe the Bug

worldedit doesnt work in singleplayer and servers.
also found someone with same problem https://www.reddit.com/r/CurseForge/comments/1g7fnwf/world_edit_with_better_mc_possible/?rdt=40138

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v32.5

**Comment by chorbintime** [comment]
not a modpack issue - use Axiom instead and update the modpack to v34
