### ISSUE TITLE
Infusion Pedestal

### ISSUE THREAD

**Issue by Wilsonthedark** [LunaPixelStudios/Better-MC#1895]
### Describe the Bug

My infusion pedestal is not working have tried it in several places and used the F3 button to make sure was placing right

### Reproduction Steps

1.Tried and home base
2.Tried at different biome
3.Tried at the End
...

### Screenshots and Videos

na

### Crash Report or Log

na

### Operating System

Windows 11 Pro

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

34 HF

### Other Mods

Forbidden and Araneus

**Comment by chorbintime** [comment]
likely nothing that can be done - the betterend developers have abandoned 1.20.1 and they dont care about forge support it seems. we'll look into it for next update but i doubt theres anything we're able to do
