### ISSUE TITLE
BMC3 [FABRIC] - Crash on world load

### ISSUE THREAD

**Issue by SimplySwatch** [LunaPixelStudios/Better-MC#1899]
### Describe the Bug

Opening/creating a flat world causes the game to close at 2% on the loading screen. 

### Reproduction Steps

1. Launch modpack through the CurseForge app
2. Launch Minecraft
3. Create a superflat world
...

### Screenshots and Videos

![image_2024-10-31_181336634](https://github.com/user-attachments/assets/4de4a5ab-577e-44f6-b98d-3946a77424c7)

### Crash Report or Log

https://pastebin.com/9vECyzzX

### Operating System

Windows 10

### Minecraft Version

1.21

### Modloader

Fabric

### Modpack Version

v13

**Comment by chorbintime** [comment]
Flat worlds are unsupported. Its a BCLib issue as far as I know
