### ISSUE TITLE
BMC3

### ISSUE THREAD

**Issue by Ammarmyf481** [LunaPixelStudios/Better-MC#1900]
[disconnect-2024-11-03_20.29.11-client.txt](https://github.com/user-attachments/files/17610585/disconnect-2024-11-03_20.29.11-client.txt)
I'm having trouble when trying to join multiplayer servers in the BMC3 version 1.21.1. Every time I attempt to connect, I get timed out, sometimes it says incompatible version. I’m not sure if it’s a problem with TLauncher itself, my internet connection, or something else entirely.
someone help me please

**Comment by PeterSk123** [comment]
I operate a Minecraft server where I play with friends, but I encounter an issue when attempting to allocate more RAM to the server. Each time I start the server, the allocated memory resets to 4 gigabytes. While I can change the RAM allocation to my desired amount once the server is running, I am unsure if the increased memory usage is working or not.

**Comment by chorbintime** [comment]
> [disconnect-2024-11-03_20.29.11-client.txt](https://github.com/user-attachments/files/17610585/disconnect-2024-11-03_20.29.11-client.txt) I'm having trouble when trying to join multiplayer servers in the BMC3 version 1.21.1. Every time I attempt to connect, I get timed out, sometimes it says incompatible version. I’m not sure if it’s a problem with TLauncher itself, my internet connection, or something else entirely. someone help me please

TLauncher is known spyware and is also unable to install mods or modpacks correctly. We offer no support for piracy.



> I operate a Minecraft server where I play with friends, but I encounter an issue when attempting to allocate more RAM to the server. Each time I start the server, the allocated memory resets to 4 gigabytes. While I can change the RAM allocation to my desired amount once the server is running, I am unsure if the increased memory usage is working or not.

This has nothing to do with the original issue, I'm unsure why you're asking this here. Make sure you're editing the variables.txt file, and if you still experience issues then make a new issue.
