### ISSUE TITLE
bmc1 - 1.16.5 - v60.5 -Saving world

### ISSUE THREAD

**Issue by Amirali299** [LunaPixelStudios/Better-MC#1902]
### Describe the Bug

Hey supports,
my problem is about that version I wrote at title.i allocated 5018 MB of my laptop ram but when I run it and create or open a created world that do 100% of loading and show joining world... but crash for a bit seconds and then show Saving world.. and close the minecraft.in terminal the error code is -1

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

v60.5

**Comment by chorbintime** [comment]
You need to provide logs or we cant help
