### ISSUE TITLE
Villager trades wont go down

### ISSUE THREAD

**Issue by 1bis01** [LunaPixelStudios/Better-MC#1903]
### Describe the Bug

I cured my villagers and no matter how much I healed them their prices won't go lower than the prices of the first healing attempt, for example, I healed my fletchers way over 3 times and the prices haven't changed from 26 sticks for 1 emerald

### Reproduction Steps

1. Turn a fletcher villager into a zombie
2. heal them and see if the prices have changed 
3. turn them into a zombie again 
4. the prices won't go down after healing them the first time 
...

### Operating System

windows 10

### Minecraft Version

1.21

### Modloader

Forge

### Modpack Version

V13 

### Other Mods

Fresh animations, muffeler mod

**Comment by MC-Mods-Pete** [comment]
as far as I know this was changed in vanilla and does not at all work anymore (not mod related).
https://www.reddit.com/r/Minecraft/comments/1dgfyds/is_zombie_curetrading_still_a_thing_in_bedrock_121/
