### ISSUE TITLE
losing itemed

### ISSUE THREAD

**Issue by abelbear** [LunaPixelStudios/Better-MC#1904]
i keep losing my backpack and lost lot of stuff

**Comment by Nachololollol** [comment]
same happened to me, im afraid of building other one bc of that, do u play on server or one player

**Comment by Nachololollol** [comment]
it happens to me when i put it on the trinkets slot an then i go out of the server, im playing on a athernos server with better mc 3 v13

**Comment by SHXRKIEgg** [comment]
Will be fixed in next update
