### ISSUE TITLE
Accessories inv reset

### ISSUE THREAD

**Issue by HotJoint024** [LunaPixelStudios/Better-MC#1907]
### Describe the Bug

problems with equipped accessories, they disappear when I close server.

### Reproduction Steps

1.I equip backpack
2.i close the server
3. when it start up, my backpack (on back slot of accessories inv) disappear.

### Operating System

Windows 11

### Minecraft Version

1.21

### Modloader

Fabbric

### Modpack Version

v14, v13 too

### Other Mods

...

**Comment by SHXRKIEgg** [comment]
Fixed in latest
