### ISSUE TITLE
Stripping crash

### ISSUE THREAD

**Issue by trisk0s** [LunaPixelStudios/Better-MC#1908]
### Describe the Bug

 stripping does crashing minecraft

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Snímek obrazovky 2024-11-09 000433](https://github.com/user-attachments/assets/0ca98877-32eb-4063-b9f9-79cce5b01511)

### Operating System

Windows 11

### Minecraft Version

1.21

### Modloader

Fabric

### Modpack Version

BMC3 v14

**Comment by SHXRKIEgg** [comment]
Fixed in latest
