### ISSUE TITLE
Villager Job Refresh Issue

### ISSUE THREAD

**Issue by freehostwang** [LunaPixelStudios/Better-MC#1909]
### Describe the Bug

The villager either doesn't adapt from the job or tries to get an job further away from the job site block. It makes refreshing the librarian's enchantment book incredibly difficult.

### Reproduction Steps

1. remove the original villager's job site block or breed villagers to get a jobless villager 
2. place a new  job site block in front of it 
3. the villager either doesn't adapt from the job or tries to get an job further away from the job site block
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

34 HF

**Comment by chorbintime** [comment]
you can remove the libertys villager mod
