### ISSUE TITLE
Press 'C' to Zoom not working

### ISSUE THREAD

**Issue by ablay13** [LunaPixelStudios/Better-MC#1910]
### Describe the Bug

During the tutorial phase when you first start using Better Minecraft [FORGE] BMC3 it states "press C to zoom." However, it does not work. when I go to options-controls-key binds I do not even find zoom as an option. I am not sure what the exact issue is but it is frustrating and mildly inconvenient in gameplay. 

### Screenshots and Videos

![image_2024-11-10_171356275](https://github.com/user-attachments/assets/67aa6fbb-9596-4f56-8c90-4c374476c454)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v20

**Comment by chorbintime** [comment]
The modpack does not currently have a Zoom mod to my knowledge - you can add Zoomify

**Comment by minecraftguyorsmth** [comment]
> The modpack does not currently have a Zoom mod to my knowledge - you can add Zoomify

zoomify isnt for forge
