### ISSUE TITLE
Brewing stands give low comparator output

### ISSUE THREAD

**Issue by Bananacody** [LunaPixelStudios/Better-MC#1911]
### Describe the Bug

Now that potions stack to 16 (what mod causes this?) Comparators in front of brewing stands now give out a redstone output of 1 even if 3 bottles are present (previously it was 1 for no potions but just blaze powder and/or ingredient, 3 with first potion, 5 with second and 8 when full, allowing for proper redstone automation). Since brewing stands can still hold just 1 potion per slot they should be treated as unstackables in that case and give out the previously proportional comparator output.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

BMC4 v34

**Comment by chorbintime** [comment]
pretty sure the mod is responsible is Supplementaries or Quark
