### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by samikinzz** [LunaPixelStudios/Better-MC#1913]
### Describe the Bug

The inventory buttons aren't working. I can't sort, take all, or stack. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16.5

### Modloader

Fabric

### Modpack Version

BetterMC [FABRIC} 1.20.1 v25

**Comment by chorbintime** [comment]
please record a video
