### ISSUE TITLE
Error Code 6 in Modded Mincraft

### ISSUE THREAD

**Issue by justapersonxX** [LunaPixelStudios/Better-MC#1916]
### Describe the Bug

I'm on a Mac m1 chip, but whenever I try to boot certain modpacks ( Prom., better Minecraft,crazy craft etc ), it gives me Minecraft error code 6. 

I feel like I've tried every solution there is: prism launcher, updated java, AT launcher, but I still get one error or another. 

### Reproduction Steps

1. I choose a mod pack on forge 
2. click play
3. brings me to the minecraft launcher
4. I can boot the start up menu, but when i try to create a world or join a server it crashes. 
...

### Screenshots and Videos

<img width="587" alt="Screenshot 2024-11-16 at 5 40 53 PM" src="https://github.com/user-attachments/assets/0d31d7e6-0676-4574-bb03-26e7d8accf82">

### Crash Report or Log

6

### Operating System

Mac M1 Chip 

### Minecraft Version

1.21

### Modloader

Forge

### Modpack Version

v15

**Comment by chorbintime** [comment]
You need to provide the log file or we can't help. If there is an hs_err_pid file in the modpack files then please send that as well
