### ISSUE TITLE
how to repair this?

### ISSUE THREAD

**Issue by Tubusiek** [LunaPixelStudios/Better-MC#1917]
### Describe the Bug

When i join to the server i see this, 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/cb95fb40-c5a7-4426-a7f1-777e99c30513)

### Crash Report or Log

i dont have any crashreport 

### Operating System

Windows 10

### Minecraft Version

1.21

### Modloader

Forge

### Modpack Version

v21

### Other Mods

I dont have any other mods

**Comment by chorbintime** [comment]
You don't have the same modpack installed as the server.
