### ISSUE TITLE
Visual Glitches

### ISSUE THREAD

**Issue by QuestionMark210** [LunaPixelStudios/Better-MC#1918]
### Describe the Bug

When I place blocks, they tend disappear and reappear few moments after. This usually happens randomly when I play, although it also seems to happen much more after I just entered my world. (Played on 1.18.2).

https://github.com/user-attachments/assets/fd60a6b6-329e-4a08-91fd-d46d258d3afc

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Modloader

Forge

### Modpack Version

v20

### Other Mods

I deleted Villager Guards mod as well as Serene Seasons. Turned off modpack's resourcepacks for block textures and HUD and added: Spartan Weaponry, Dungeon Crawl, Hunter Illager, Blocky Siege and Scuba Gear mods.

**Comment by chorbintime** [comment]
Is this issue reproducible on a fresh installation of the modpack?

**Comment by QuestionMark210** [comment]
> Is this issue reproducible on a fresh installation of the modpack?

Yeah. Just reinstalled modpack and it's still there.

**Comment by chorbintime** [comment]
What launcher did you use to install the modpack?

**Comment by QuestionMark210** [comment]
> What launcher did you use to install the modpack?

CurseForge.

**Comment by chorbintime** [comment]
Try reinstalling on ATLauncher and following the full [performance guide](https://rpg.prominence.wiki/performance-guide)
