### ISSUE TITLE
Shader packs

### ISSUE THREAD

**Issue by tikizeraa** [LunaPixelStudios/Better-MC#1919]
### Describe the Bug

I'm not able to see the shader packs option even though I have the mod pack installed (Better MC v34.5)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![shader pack option non existing](https://github.com/user-attachments/assets/2a3e43ca-06af-4132-81b1-41864c91a421)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v34.5

### Other Mods

JustHammers

**Comment by chorbintime** [comment]
You did not install the modpack correctly. Please do a fresh installation on [ATLauncher](https://atlauncher.com/)
