### ISSUE TITLE
Creaking overspawning after updating server to Forge v34.5

### ISSUE THREAD

**Issue by riverence** [LunaPixelStudios/Better-MC#1920]
### Describe the Bug

After updating both my client and server to Forge BMC4 v34.5, the creaking now overspawns an absurd amount, causing server crashes in some scenarios if staying within the biome longer than maybe a minute. The mobs themselves are unkillable, even via the /kill command. Before updating the server, the creaking seldom spawned at all.

### Reproduction Steps

1. Exist in a Pale Garden biome in BMC4 Forge V34.5.

### Operating System

Windows 11 [Client] / Linux [Server] (lilypad.gg)

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v34.5

### Other Mods

N/A, any mods added exclusively clientside

**Comment by SHXRKIEgg** [comment]
Disable the mod via YSNS, will fix in next update
