### ISSUE TITLE
Can't type letter "E" in JEI

### ISSUE THREAD

**Issue by QuestionMark210** [LunaPixelStudios/Better-MC#1921]
### Describe the Bug

When trying to type anything with letter "E" in it in JEI, game just closes my inventory.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://github.com/user-attachments/assets/157286b5-0ad0-4621-972b-04c57b923a4a

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Modloader

Forge

### Modpack Version

v20

**Comment by chorbintime** [comment]
Update the JEI mod + all addons, alongside the ModernFix mod. Should fix it
