### ISSUE TITLE
2 Broken Galosphere Advancements

### ISSUE THREAD

**Issue by w-stewart** [LunaPixelStudios/Better-MC#1923]
### Describe the Bug

Galosphere:
1. "I spy with my little eye" (Use a Spectre Flare) not activating when using a Spectre Flare.
2. "Spread the Light!" (Deploy a Glow Flare) not activating when using a Glow Flare.

### Reproduction Steps

Both can be tested by giving yourself the Spectre Flare and Glow Flare items and attempting to unlock the Advancements.

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

34.5 (also was an issue on earlier versions)

### Other Mods

None

**Comment by chorbintime** [comment]
If there is an update available for the Galosphere mod, please update to the latest version.

If no update is available or the issue persists, then please report the issue to the mod author
