### ISSUE TITLE
Broken Better Nether Blue Obsidian Conversion and Advancement

### ISSUE THREAD

**Issue by w-stewart** [LunaPixelStudios/Better-MC#1924]
### Describe the Bug

1. "Something Blue" (Obstain blue Obsidian by converting Lava above Soulsand or Soulstone to Obsidian) not activating, likely due to conversion not working properly (see #2).
2. When converting lava to obsidian when the lava is placed on top of soulsand or soulstone, blue obsidian is not created.
3. "Make 'em Cry" (Use a Lightning-Rod to create all types of crying and weeping obsidian) not activating for crying and weeping normal obsidian (the counter does advance for crying and weeping blue obsidian).

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

34.5

**Comment by chorbintime** [comment]
If there is an update available for the mods that add these advancements, please update to the latest version.

If no update is available or the issue persists, then please report the issue to the mod author

**Comment by Cbelkster** [comment]
Still an issue on better-nether-9.0.10.jar - latest release for 1.20.1.
