### ISSUE TITLE
Dispenser dropping Water Buckets instead of using it

### ISSUE THREAD

**Issue by XaErus0** [LunaPixelStudios/Better-MC#1925]
### Describe the Bug

When I try to make a mob farm, I have to use dispensers with water buckets in them, but instead of dropping the water, it drops the water bucket.

### Reproduction Steps

1. Put the Water Bucket inside the Dispenser
2. Active the Dispenser
3. It will drop the Water Bucket

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/efed19e9-ad71-430d-b2ec-f328125b9e36)
![image](https://github.com/user-attachments/assets/7671e5d5-d262-4efa-9b6e-39bbd780c858)

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] v15

### Other Mods

AppleSkin
ReplayMod

**Comment by SkandalBeu** [comment]
I've the same bug!

Modpack Version:
Better MC [FABRIC] BMC3 v14.5

**Comment by HotJoint024** [comment]
water bottle too

**Comment by chorbintime** [comment]
This also occurs when shooting eggs out of a dispenser - not sure exactly what is causing it but we are looking into it. My best suggestion currently would be to remove the Lithium mod

**Comment by chorbintime** [comment]
Both issues should be fixed by updating Charm to the latest version

**Comment by Jhon2880** [comment]
![屏幕截图 2024-12-02 221317](https://github.com/user-attachments/assets/db64f807-9508-4aa8-a6d5-de837f123889)
I update the charm and the game crash

**Comment by chorbintime** [comment]
Use this file https://www.curseforge.com/minecraft/mc-mods/charm-forked/files/5958541
