### ISSUE TITLE
Can't get a broken charm

### ISSUE THREAD

**Issue by SmokeyTwix28** [LunaPixelStudios/Better-MC#1927]
### Describe the Bug

After I die, and when I loot my body, the charm I wanted to break (for a wandering villager trade) was still intact. I tried this multiple times but it never worked.
Note: I died to fall damage and zombies so maybe that's why

### Reproduction Steps

1.Equip a fragile charm in the charm slot
2.Die
3.
...

### Screenshots and Videos

https://github.com/user-attachments/assets/32f8cf57-3349-454d-b40d-b97438ec4e4f

### Operating System

Windows 11 Home

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
Your best bet is to update the Mythic Charms mod to the latest version available for 1.20.1 Fabric, as I'm pretty sure we're currently using an older version of the mod. You can also try removing the Universal Graves mod from the modpack, and see if that makes the charm break.

I would suggest reporting this to the Mythic Charms developer if this persists on the latest version of Mythic Charms

**Comment by chorbintime** [comment]
I've confirmed that removing the Universal Graves mod does fix the issue, but this shouldn't be an issue if the Mythic Charms mod had proper compatibility with graves. This should be reported to the Mythic Charms devs
