### ISSUE TITLE
I can't spawn chicken with eggs into a dispenser

### ISSUE THREAD

**Issue by HotJoint024** [LunaPixelStudios/Better-MC#1928]
### Describe the Bug

I can't spawn chicken with eggs into a dispenser, it throws the eggs but no chickens spawn... If i unclaim there it works...  can it be solved please?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.21

### Modloader

Fabric

### Modpack Version

v15 and older

**Comment by chorbintime** [comment]
This also occurs when shooting a water bucket out of a dispenser - not sure exactly what is causing it but we are looking into it. My best suggestion currently would be to remove the Lithium mod

**Comment by chorbintime** [comment]
Issue should be fixed by updating Charm to the latest version
