### ISSUE TITLE
Can I turn off (bclib) “auto sync”?

### ISSUE THREAD

**Issue by enjoyable1** [LunaPixelStudios/Better-MC#1931]
I have changed the language files and some settings of some mods on the client side, but it always gets replaced with the server side content. For example: language changes in the config. I would like to ask, can I disable auto sync in all bclib? How does it affect the modpack experience? Thank you!

Ver : Better MC Forge 1.20.1 V34.5

**Comment by chorbintime** [comment]
It should be fine to change that in the bclib config, yes

**Comment by enjoyable1** [comment]
> It should be fine to change that in the bclib config, yes

good
