### ISSUE TITLE
Sulfur crystal doesn't drop sulfur

### ISSUE THREAD

**Issue by HotJoint024** [LunaPixelStudios/Better-MC#1932]
### Describe the Bug

the better end's wiki  says that when i mine a sulfur crystal, it should drop 1-3 sulfur, but nothing comes out of the crystal. i think its a bug. thanks

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.21

### Modloader

Forge

### Modpack Version

v15

**Comment by chorbintime** [comment]
Update the BetterEnd mod. If issue persists / no update is available, report the issue to the mod author
