### ISSUE TITLE
Item icon error

### ISSUE THREAD

**Issue by GradovV** [LunaPixelStudios/Better-MC#1933]
When closing inventory, item icons are saved on the screen
![yqG7Opgoohg](https://github.com/user-attachments/assets/5b09b0bc-6b2c-4f3c-9b59-806772b65d35)
![eWXwKpstT7c](https://github.com/user-attachments/assets/24d0583a-9a74-41ac-bf08-d052e8137d7d)

**Comment by chorbintime** [comment]
You did not install the modpack correctly. Please reinstall on [ATLauncher](https://atlauncher.com/)
