### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by LordD0g** [LunaPixelStudios/Better-MC#1934]
### Describe the Bug

I loaded up the world, and noticed that any "Every compat" item texture was broken. I tried re-installing the version but it didn't fix anything. 

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/ccd3f854-789d-4a30-994e-2559d1065453) 
![image](https://github.com/user-attachments/assets/6dab9bda-83d6-4a77-905d-5ea34637c4ff)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v26

**Comment by SHXRKIEgg** [comment]
Fixed in v26.5
