### ISSUE TITLE
Skin shows other skin when custom is installed

### ISSUE THREAD

**Issue by Alcobelm** [LunaPixelStudios/Better-MC#1936]
### Describe the Bug

It appears that the Kai skin in the installation is what appears on my character at launch although another custom skin is installed as shown in the picture. However when botting up and connecting to our server the Kai skin appears.

### Reproduction Steps

1.Opened minecraft from curseforge
2.Made sure to equip custom skin
3.Connected to server 
...

### Screenshots and Videos

<img width="1283" alt="Screenshot 2024-12-01 at 2 42 34 PM" src="https://github.com/user-attachments/assets/97b65906-93c3-4514-901c-65c52bd1d0fb">

### Operating System

macos

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

BMC3 v15

**Comment by chorbintime** [comment]
Reinstall the modpack on ATLauncher
