### ISSUE TITLE
Mechanical Pressers not Working

### ISSUE THREAD

**Issue by MattyWaltSwag** [LunaPixelStudios/Better-MC#1938]
### Describe the Bug

When the mechanical presser is hooked onto a constant rotating power source, the presser will fail to press after creating one of the object. 
ie - it will make one blaze cake but then not press again to make more

### Reproduction Steps

1.Place presser and connect to power 
2.Place basin 
3.Fill basin with ingrediants
Presser will make one item then not again
...

### Screenshots and Videos

![Use](https://github.com/user-attachments/assets/3511b76f-f1c2-477f-9108-6a9f11f9ef91)
![use2](https://github.com/user-attachments/assets/36214a27-cb8a-4899-b1d2-f3e747a09bab)

### Crash Report or Log

n/a

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

V26.5

**Comment by chorbintime** [comment]
Create is not in the modpack, so we can't offer support for any glitches that you experience while using it. I recommend reporting to the developers of Create
