### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by sizeableoyster** [LunaPixelStudios/Better-MC#1939]
### Describe the Bug

Hi! When I want to start Better MC via the ATLauncher, the Minecraft startup window opens as expected before the application fails to load the mods and crashes.

### Reproduction Steps

1. Install Better MC [Forge] BMC4 from the ATLauncher
2. Click play to launch the modpack

### Crash Report or Log

https://pastebin.com/eziSmvdJ

### Operating System

MacOS Sequoia 15.1.1

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v35

**Comment by chorbintime** [comment]
Reinstall the modpack via the jar version of [ATLauncher](https://atlauncher.com/)
