### ISSUE TITLE
crash on world load

### ISSUE THREAD

**Issue by ScoobyBaby** [LunaPixelStudios/Better-MC#1940]
### Describe the Bug

crashing when loading world. very first step, crashes when preparing world.

### Reproduction Steps

1. launch game
2. create single player world

### Crash Report or Log

with incompatible mods with FML disabled - https://pastebin.com/VZKHvTXP    ||     with all mods enabled - https://pastebin.com/3xzWnGwF    ||     with connector disabled - https://pastebin.com/xEizrabR

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

BMC4

**Comment by chorbintime** [comment]
Please do not disable mods. Connector is essential for the pack to run correctly.

Retry on a fresh install on [ATLauncher](https://atlauncher.com/).
