### ISSUE TITLE
Tried to read NBT tag with too high complexity, depth > 512 [level.dat]

### ISSUE THREAD

**Issue by sjager501** [LunaPixelStudios/Better-MC#1942]
### Describe the Bug

This issue might be similar to this one https://github.com/LunaPixelStudios/Better-MC/issues/1643, however I couldn't manage to get my single player world working again. 

Background:
I'm running a single player game for Better Minecraft 4. Before my game stopped working, I had last left off in the Twilight Forest within one of the Phantom Knight temples in the Dark Forest.

Today when I went to start up my world, I ran into this error:
![image](https://github.com/user-attachments/assets/6d1b3bd9-977e-4752-98f5-0f5ff49ea032)

This last run was at around 5:07pm (see logs starting at 17:07:29). My [latest.log](https://github.com/user-attachments/files/18054183/latest.log) says the following:

> [17:07:29] [Render thread/WARN]: Failed to load level data or datapacks, can't proceed with server load
> java.util.concurrent.ExecutionException: java.lang.RuntimeException: **Tried to read NBT tag with too high complexity, depth > 512**
> 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
> 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
> 	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_246486_(WorldOpenFlows.java:164) ~[client-1.20.1-20230612.114412-srg.jar%23744!/:?]
> 	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:113) ~[client-1.20.1-20230612.114412-srg.jar%23744!/:?]
> 	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:181) ~[client-1.20.1-20230612.114412-srg.jar%23744!/:?]
> 	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23744!/:?]

As described in the linked issue, I've attempted to run nbtmacafix, however that didn't seem to fix anything (I performed it on a copy of my save and then moved the new save into my saves folder):

> PS D:\Backup> java -jar .\nbtmcafix.jar .\Icarus_IV\
> [88047da8-9fbb-4ed6-a1a1-4d09db6bf2e6.dat] Reading file
> [88047da8-9fbb-4ed6-a1a1-4d09db6bf2e6.dat] File saved
> [88047da8-9fbb-4ed6-a1a1-4d09db6bf2e6.dat_old] Reading file
> [88047da8-9fbb-4ed6-a1a1-4d09db6bf2e6.dat_old] File saved
> [r.-1.-1.mca] Reading file
> [r.-1.-1.mca] File saved
> [r.-1.-2.mca] Reading file
> [r.-1.-2.mca] File saved
> [r.-1.-3.mca] Reading file
> [r.-1.-3.mca] File saved
> [r.-1.-4.mca] Reading file
> [r.-1.-4.mca] File saved
> [r.-1.0.mca] Reading file
> ...

### Reproduction Steps

1. Start minecraft
2. Select Singleplayer
3. Select world (Icarus IV)
4. Press 'Play Selected World'
5. Zipped up the level.dat file: [level.dat.zip](https://github.com/user-attachments/files/18054195/level.dat.zip)
(If necessary, I can send my world data folder or any other information to the developer who is debugging this).

### Screenshots and Videos

None

### Crash Report or Log

[latest.log](https://github.com/user-attachments/files/18054184/latest.log)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33

### Other Mods

None

**Comment by sjager501** [comment]
I do have a working backup save from a couple days before this incident, however a lot was progress was completed in the last couple days which I'm hoping to recover if possible. Let me know if there's anything I can provide or do to help! 

Thank you, 
Sam

**Comment by chorbintime** [comment]
Update to v35. We offer no support for old versions.

The old version of the modpack that you're playing on had this issue, but it was fixed.

**Comment by sjager501** [comment]
@chorbintime Upgrading to v35 ended up fixing my issue. Thank you!
