### ISSUE TITLE
Broken redstone

### ISSUE THREAD

**Issue by Ch3nk0** [LunaPixelStudios/Better-MC#1945]
### Describe the Bug

I’m on version 8 of BMC 3 1.21.1 as i cant update it on my server (not smart enough)
And im building a clay farm, the dispenser doesnt apply the water bottle to the dirt to make it mud, just dispenses it through the dirt
It does work on vanilla (tested) but there must be a mod that effects redstone, im happy to remove it from the server if required, or if theres a fix im happy to work on it 

### Reproduction Steps

1. Place water bottle or water bucket in Dispenser 
2. Trigger dispenser 

### Screenshots and Videos

None at the moment

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

V8

**Comment by SHXRKIEgg** [comment]
Fixed in later versions, please update

**Comment by Ch3nk0** [comment]
As stated i can’t **update** on the server..
