### ISSUE TITLE
Client Side Crash

### ISSUE THREAD

**Issue by ImNotASpy** [LunaPixelStudios/Better-MC#1947]
### Describe the Bug

Just updated to the v35.5 and I am crashing when trying to connect.

Suspected Mod: BCLib (bclib-3.0.14).

The crash occurs during the process of loading custom models in BCLib's CustomModelBakery class.
Error: java.lang.NullPointerException when trying to add an item model to a ConcurrentHashMap.

### Reproduction Steps

1. replace the new v35.5 files in base directory
2. launch game
3. client crash
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/b1f051e4-5460-4099-9c4e-7c69168a249c)

### Crash Report or Log

https://pastebin.com/hPMGeNLT

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v35.5

### Other Mods

Sophisticated Backpacks
AutoModPack Mod
AppleSkin
Colytra
Armor Visbility
Enchanted Books
Disenchanter
Mighty Mail

**Comment by chorbintime** [comment]
You did not update the modpack correctly. The issue has nothing to do with BCLib. Please do not "replace the new v35.5 files in base directory", as there's alot more to updating than just that. All launchers have an "update modpack" button which does the proper steps for you.

Please reinstall the modpack on ATLauncher and transfer over your xaerosminimap folder, alongside your saves folder. You are also free to transfer over the new mods you added.

**Comment by ImNotASpy** [comment]
Are there installation instructions to install this manually(without a launcher), or is it not supported by the Modpack team? @chorbintime
