### ISSUE TITLE
BMC4 Server Pack issues

### ISSUE THREAD

**Issue by eliodalte** [LunaPixelStudios/Better-MC#1948]
### Describe the Bug

Some mods cause a mismatch and the server pack doesn't work on linux.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Ubuntu 22

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

35.5

**Comment by chorbintime** [comment]
Please provide logs or provide more information. The serverpack works completely fine, so anything breaking for you would be user error.
