### ISSUE TITLE
Cannot dismount dragon or die

### ISSUE THREAD

**Issue by Gunslinger44837** [LunaPixelStudios/Better-MC#1950]
### Describe the Bug

after hatching and taming a dragon I hopped on and flew around the map now I cannot dismount the dragon and if I try to kill myself to re spawn I cannot die or lose any health. I am also getting kicked from server for "flying".
this has happened to me and the other person playing on the server also updated to v12 to attempt to fix it and it did not work

### Operating System

windows 10

### Minecraft Version

1.21

### Modloader

NeoForge

### Modpack Version

v9.5

**Comment by chorbintime** [comment]
update to the latest version of the modpack

update the dragon mounts legacy mod if an update is available. if the issue persists report the issue to the mod author
