### ISSUE TITLE
World stopped loading chunks and has missing textures 

### ISSUE THREAD

**Issue by Mexicanstyle1939** [LunaPixelStudios/Better-MC#1951]
### Describe the Bug

My world suddenly stopped loading chunks correctly and started having missing texture issues with no other bugs or issues present before this, also freezes/crashes 

### Reproduction Steps

1. Load the modpack as normal from curseforge
2. start up from the curseforge loader
3. Select and load the world 
4. Missing (base and mod) textures 
5. After a while game crashes/freezes or a loading screen appears with only the tips visible 

### Screenshots and Videos

![Captura de pantalla 2024-12-12 203039](https://github.com/user-attachments/assets/f9cb8aa4-2763-4389-890a-d7b0f0711e85)
![Captura de pantalla 2024-12-12 203128](https://github.com/user-attachments/assets/155dbfa8-7641-41de-81b0-41953b1c5874)
![Captura de pantalla 2024-12-12 205814](https://github.com/user-attachments/assets/cdfc829d-d96c-4a31-b02e-57627fd2af7d)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v33 and v35.5

### Other Mods

- Traveler's Backpacks
- Trade cycling

**Comment by chorbintime** [comment]
Reinstall the modpack on ATLauncher
