### ISSUE TITLE
Server not working for no reason

### ISSUE THREAD

**Issue by Zyzzbrah73** [LunaPixelStudios/Better-MC#1953]
I have been hosting a private server for better minecraft for me and a friend. Upon opening it yesterday I had the error where i had a lunapixel.gg address instead of my private ip. the server comes up with the error when joining that the server is still starting. this continues endlessly. Its very confusing as i cannot figure whats causing this, its been fine for weeks and then this happens overnight. Can I get some advice please?

**Comment by chorbintime** [comment]
Please follow the issue creation format provided
