### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by SonnenPingu** [LunaPixelStudios/Better-MC#1955]
### Describe the Bug

The server crash during operation simply... Unfortunately I don't know exactly why.

[Crash] https://mclo.gs/zok2igU and https://mclo.gs/eHJvQ61 [Logs]  https://mclo.gs/DR6R1DP and https://mclo.gs/CbPIyxr [Jade] https://mclo.gs/sysXz0p

### Reproduction Steps

Reproduces by itself

### Crash Report or Log

[Crash] https://mclo.gs/zok2igU and https://mclo.gs/eHJvQ61 [Logs]  https://mclo.gs/DR6R1DP and https://mclo.gs/CbPIyxr [Jade] https://mclo.gs/sysXz0p

### Operating System

Linux

### Minecraft Version

1.21

### Modloader

Fabric

### Modpack Version

16,5

### Other Mods

TravelersBackPack, Plan, BlueMap +Adons +mysql

**Comment by chorbintime** [comment]
Please retry with added mods removed
