### ISSUE TITLE
Spawners in BMC4 Stop working overtime (Didn't do this before)

### ISSUE THREAD

**Issue by BubbleBunnie** [LunaPixelStudios/Better-MC#1958]
### Describe the Bug

So i'm playing in a Minecraft server thats public to the community and Ever since the newest update, Spawners will stop working over a few hours once given a soul into a inactive mob spawner turning it into a active mobspawner. Nobody knows why this happens or such...

### Crash Report or Log

No Log

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v35.5

**Comment by chorbintime** [comment]
Update the spawners+ mod.

If issue persists or no update is available, report the issue to the mod author
