### ISSUE TITLE
xaero's minimap not showhing another dimension map

### ISSUE THREAD

**Issue by cxfeemp4** [LunaPixelStudios/Better-MC#1959]
### Describe the Bug

when i enter aether dimension, the minimap doesnt show aether dimension but the overworld instead

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

BMC4

### Other Mods

shoulder surfing

**Comment by chorbintime** [comment]
Update the xaeros minimap mod.
If issue persists or no update is available, report the issue to the mod author
