### ISSUE TITLE
Kiln (furnace bug)

### ISSUE THREAD

**Issue by mrsurnom** [LunaPixelStudios/Better-MC#1960]
### Describe the Bug

the kiln block wich basically is a furnace that allow you to smelt some items faster doesnt work anymore, you cant interract with it at all .

### Reproduction Steps

1.Simply craft the kiln
2.try to interract with it
3. it doesnt work
...

### Operating System

Window 11

### Minecraft Version

1.21

### Modloader

Forge

### Modpack Version

v16

### Other Mods

none was added.

**Comment by chorbintime** [comment]
Update the mod that adds the kiln block. If issue persists or no update is available, report the issue to the mod author
