### ISSUE TITLE
my game crashed code -1

### ISSUE THREAD

**Issue by keraizy14** [LunaPixelStudios/Better-MC#1962]
### Describe the Bug

it say that it cant read bclib

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

[crash-2024-12-27_22.00.06-client.txt](https://github.com/user-attachments/files/18261021/crash-2024-12-27_22.00.06-client.txt)

### Crash Report or Log

https://mclo.gs/OokEO4d

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v35.5

**Comment by chorbintime** [comment]
Reinstall the modpack on ATLauncher.
To install ATLauncher, do the following:
**1**. Go to <https://atlauncher.com/download> 
**2**. Install and run the setup, then open the program.
**3**. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
**4**. Go to the Packs tab on the right, then click "Curseforge" on the left.
**5**. Search the modpack you wish to download.
**6**. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
**7**. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
**8**. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.
This video explains the process: <https://youtu.be/xMYW1wMbmkM>
