### ISSUE TITLE
dont know how to make the mod work

### ISSUE THREAD

**Issue by Mumbohex** [LunaPixelStudios/Better-MC#1963]
### Describe the Bug

im trying to put the mod on (forge 1.20.1) same as the mod update and it wont appear in my mods how do you get to work?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Mac M3 chip 

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.20. 1 v35.5 zip

**Comment by kian2981** [comment]
been having the same problem it just come up with minecraft and forge as the the 2 mods

**Comment by Mumbohex** [comment]
> been having the same problem it just come up with minecraft and forge as the the 2 mods

Haven’t found a way around yet I’m about to eat rn so I’ll try later

**Comment by Mumbohex** [comment]
> been having the same problem it just come up with minecraft and forge as the the 2 mods

download the forge app then it will work

**Comment by kian2981** [comment]
ur a savour

**Comment by kian2981** [comment]
> download the forge app then it will work 
how do i download it

**Comment by kian2981** [comment]
> download the forge app then it will work

how do i get the forge app

**Comment by Mumbohex** [comment]
> > download the forge app then it will work
> 
> how do i get the forge app

what device are you one mac? windows? linux?

**Comment by chorbintime** [comment]
Neither of you are installing the modpack correctly.

You do not need to do anything with a mods folder or a "forge app". 

To install ATLauncher, do the following:
**1**. Go to <https://atlauncher.com/download> 
**2**. Install and run the setup, then open the program.
**3**. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
**4**. Go to the Packs tab on the right, then click "Curseforge" on the left.
**5**. Search the modpack you wish to download.
**6**. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
**7**. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
**8**. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.
This video explains the process: <https://youtu.be/xMYW1wMbmkM>
