### ISSUE TITLE
internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Emeraldsoul2203** [LunaPixelStudios/Better-MC#521]
### Describe the Bug

Keep getting 'internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException' when trying to join the server. We had this before but reloggin and restarting the server fixed it until now as it will not let anyone join. Tried restarting pc, serve and clients, reinstalled all but still get this error.  We have a few extra mods installed besides what was in the pack but had no issue since the server started a while back. 
[crash-2022-07-10_13.58.10-client.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/9079199/crash-2022-07-10_13.58.10-client.txt)

### Reproduction Steps

1.Start up server and client
2.Attempt to join and successfully connect
3. hit with internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException and disconnected.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

better minecraft v56

### Optifine

No

### Other Mods

chunkloaders-1.1.12-mc1.16.jar
DungeonCrawl-1.16.5-2.3.8.jar 
minecolonies-1.16.5-1.0.736-RELEASE.jar
structurize-1.16.5-1.0.392-RELEASE.jar
TConstruct-1.16.5-3.3.4.335.jar
Mantle-1.16.5-1.6.157.jar

**Comment by SHXRKIIE** [comment]
Need the server and client log, the crash has nothing to do with this
