### ISSUE TITLE
Game Crashing - V12.5 BETA - 1.18.2 - Better Minecraft - Picking up 

### ISSUE THREAD

**Issue by AriseKM** [LunaPixelStudios/Better-MC#522]
### Describe the Bug

When picking up items, animals etc. 
Think the keys are (Shift + right click)
It sometimes causes a crash in the game for other players

### Reproduction Steps

1. Shift + right click (or whichever keys are used to pick up items with your hands)
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft v12.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Need crash report and what mobs were you trying to pick up?

**Comment by AriseKM** [comment]
The game crashed whilst rendering entity in world
Error: java.lang.IllegalStateException: Already building!
Exit Code: -1
