### ISSUE TITLE
Cant play on server with PC windows PC players

### ISSUE THREAD

**Issue by WesternCat13** [LunaPixelStudios/Better-MC#523]
### Describe the Bug

Im playing on my Mac with the same mod pack better Minecraft and on fabric. But when I try and load in to my friends server it tells me that I've received ID maps for Minecraft:entity_type contains IDs - (then a specific item). We tried deleting the mod it had a problem with but then moved to another. I just don't know what else to try.

### Reproduction Steps

1. Downloaded fabric and installed 1.19
2. downloaded curse forge
3. downloaded better Minecraft 1.19 
4. tried to join server 
5. Got hit with error message

### Operating System

Mac

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v2 

### Optifine

No

**Comment by SHXRKIIE** [comment]
Screenshot and logs please

**Comment by RazvanBd** [comment]
> Screenshot and logs please

Same v2.5.
[2022-07-12-2.log](https://github.com/LunaPixelStudios/Better-MC/files/9095863/2022-07-12-2.log)

**Comment by SHXRKIIE** [comment]
it doesnt really say why you are disconnecting other than its a network timeout error. How much ram is allocated? This could be a MAC problem as I cant test on MACs myself. See if removing the sdrp mod fixes it?
