### ISSUE TITLE
Missing Texture on Dirt.

### ISSUE THREAD

**Issue by SomeSinner420** [LunaPixelStudios/Better-MC#524]
### Describe the Bug

I had just started a new world and it looks like there's a debug texture when dirt is in certain positions. I can find multiple instances of these dirt blocks throughout the world.

### Reproduction Steps

1.Create a new world.
2.Look for dirt block cliffs, or dirt blocks in specific block placements.

### Screenshots and Videos

![2022-07-10_13 11 59](https://user-images.githubusercontent.com/109037013/178155467-b20afafe-9400-4815-8a7b-5dcf1ffc02ec.png)
![2022-07-10_13 21 11](https://user-images.githubusercontent.com/109037013/178155474-5beb191b-900a-4b18-a75e-4c37c238fed9.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v2

### Optifine

No

**Comment by SHXRKIIE** [comment]
have you tried reloading the resourcepacks and restarting your game?
