### ISSUE TITLE
Shaders option not showing up

### ISSUE THREAD

**Issue by mxarment** [LunaPixelStudios/Better-MC#526]
### Describe the Bug

Shaders option not showing up in Video settings. I dont know if its an error of the mod which changes the graphics settings or something else

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/109087512/178282772-5882ec89-f8e5-4228-8cfe-ee58413244bd.png)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57

### Optifine

No

**Comment by mxarment** [comment]
> then you arent on v57, please check

100% I am, I update it yesterday

**Comment by SHXRKIIE** [comment]
Check if you have the Oculus and Rubidium mod installed? if not then the modpack is installed wrong.
