### ISSUE TITLE
texture problem through stained glass

### ISSUE THREAD

**Issue by squeshs** [LunaPixelStudios/Better-MC#528]
### Describe the Bug

if you place down stained glass near water the water will not always appear through and it will be as if you're looking through air on the other side making builds in water really poor looking once inside

### Reproduction Steps

1.place stained glass near an ocean or sea
2.look through it 
3. most of the time you wont see the water
...

### Screenshots and Videos

![ss](https://user-images.githubusercontent.com/109111982/178364235-117d280e-9436-497a-ad0c-2fa4e21a3819.png)

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v12.5

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
I will report this to the rubidium dev
