### ISSUE TITLE
Home Page Dead Link

### ISSUE THREAD

**Issue by Caprikey** [LunaPixelStudios/Better-MC#529]
### Describe the Bug

Github Home Page / Wiki link from Curseforge has a dead link for the "Mod List" page.

Dead Link:
https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack-new/relations/dependencies

Working Link:
https://www.curseforge.com/minecraft/modpacks/better-mc-modpack-new/relations/dependencies

### Reproduction Steps

1. Open Web browser
2. Navigate to https://www.curseforge.com/minecraft/modpacks/better-mc-modpack-new
3. Click Wiki (Opens https://github.com/LunaPixelStudios/Better-MC/wiki)
4. Click Mod List (Opens https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack-new/relations/dependencies)
5. 404 Error 

Or 
1. Open Web Browser
2. Navigate to Git Hub Page, https://github.com/LunaPixelStudios/Better-MC/wiki
3. Click Mod List (Opens https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack-new/relations/dependencies)
4. 404 Error 

...

### Screenshots and Videos

![BetterMC-BugReport-Resourse-LinkError](https://user-images.githubusercontent.com/5361497/178385935-ab26c035-5baf-4325-a12c-1b8bc70597d6.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [FORGE] v12.5

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
It works for me and its not something I have control over. Dependencies is auto generated by CF
