### ISSUE TITLE
Not being able to kill the hydra twilight forest

### ISSUE THREAD

**Issue by Sogus** [LunaPixelStudios/Better-MC#530]
### Describe the Bug

After kiling the minoshroom I am not able to kill the hydra due to the barrier that would normaly be there if I still needed to kill it

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![sss](https://user-images.githubusercontent.com/109125080/178404406-5bda7467-e9ed-4429-bb27-461ccc809667.png)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v56

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Remove Optifine
