### ISSUE TITLE
Ender dragon crash

### ISSUE THREAD

**Issue by WalkerCuz** [LunaPixelStudios/Better-MC#533]
### Describe the Bug

me and 8 people defeated the ender dragon, once we collected his xp the server crashed, evrytime i load back in all the enderman are frozen, the dragons health is full but he is dead, i walk around for a few seconds before crashing again, my one friend was able to leave the end and whne he plays on the world himself he can play fine but all of us trapped in the end cant leave cause the server crashes as we join and load in the end

### Reproduction Steps

1.join server 
2. load into the end (where im standing during crash)
3.crash
...

### Crash Report or Log

https://pastebin.com/LX4iy92B

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v12.5

### Optifine

No

**Comment by WalkerCuz** [comment]
> can you see if removing the mod radium on server fixes it?

just attempted and did not work

**Comment by SHXRKIIE** [comment]
Send the new Crash Report
