### ISSUE TITLE
Random Missing Textures

### ISSUE THREAD

**Issue by Firebirdie713** [LunaPixelStudios/Better-MC#534]
Each time I load into a save file, a different block texture is missing.  The first time was deepslate gold ore, this time it is gravel.  The issue occurs with a different block each time, but only when the block is placed into the world.  The block shows up normally in the player inventory and in the REI.  The name of the block is also fine, looking at the block registers the name and the source with no odd formats.  Saving and relaunching just shifts the issue to affect a different block.  See screenshots for confirmation of missing texture, correct appearance in inventory/REI, and correct name recognition.

![Missing_Texture](https://user-images.githubusercontent.com/25965296/178803255-fb50da9e-3d50-4e7b-8d52-39fe3b466b6e.jpg)

![Gravel_block_REI](https://user-images.githubusercontent.com/25965296/178803423-ff4cb198-cdc7-45f0-ac58-63b691a80643.jpg)

![Gravel_Name](https://user-images.githubusercontent.com/25965296/178803723-ca3c23b9-da38-4cb5-9c98-a3cc6f69efab.jpg)

**Comment by SHXRKIIE** [comment]
See if reinstalling the modpack helps
