### ISSUE TITLE
Server Crashed when my friend activated a sculk shrieker

### ISSUE THREAD

**Issue by Jexoblammo1** [LunaPixelStudios/Better-MC#536]
### Describe the Bug

When my friend was exploring the new sculk area the server closed, after the server host restarted the server it continues to crash anytime he tries to log in. All he said hes done is break two sculk blocks and one of the sculk sensors, when attempting to break a sculk shrieker it screamed and then the server crashed.

### Reproduction Steps

1. Locate the sculk biome underground
2. Activate a sculk shrieker by making noise

...

### Crash Report or Log

https://pastebin.com/YUZcBn3U

### Operating System

WIndows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v12.5

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Mod Dev is working on a fix, this should be out tomorrow hopefully. Either you can remove the block at Block location: World: (-871,-36,466) or wait for the update

**Comment by Jexoblammo1** [comment]
Has the fix been implemented yet? I managed to reset the chunk and tp my friend out last time but the same error just occurred and this time it's somewhere I would like to not reset if possible. Thanks so much
