### ISSUE TITLE
Bonemeal Dupe

### ISSUE THREAD

**Issue by uncle-jamal** [LunaPixelStudios/Better-MC#538]
### Describe the Bug

For some reason I can just infinitely right click on a composter and it'll just fill up all the day. Not sure if this is a local bug on my specific pack or a universal bug for everyone, but it's probably worth a look into.

Might also be a feature in a mod where you can use the composter anytime and it'll take any seeds in your chests away, but idk if that would even be possible. Probably a bug

### Reproduction Steps

1.Create composter
2.Right click
3.Fills up without any seeds or anything that can be used in a composter
4.Boom, infinite bonemeal

### Screenshots and Videos

https://youtu.be/usVA-I6IPrU

### Operating System

win11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC 1.19 v1

### Optifine

No

### Other Mods

Upgraded Shulkers (us)

**Comment by TimestaticYT** [comment]
Doesn't work when I try to recreate it
