### ISSUE TITLE
World problem

### ISSUE THREAD

**Issue by Radi5224** [LunaPixelStudios/Better-MC#539]
### Describe the Bug

When i start new world i get tool i get diamond set and when i close minecraft once the world don't open and the games crashes with the exit code -805306369! Please help!

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57

### Optifine

No

**Comment by SHXRKIIE** [comment]
Running out of Memory, please allocate more

**Comment by Radi5224** [comment]
> Running out of Memory, please allocate more

I have memory but when i open the world it's only typing Reading world data and after 2 minutes its shows this
![proof](https://user-images.githubusercontent.com/106247146/179195999-78a21666-642a-4b86-a16d-da7fe4770921.jpg)
s
