### ISSUE TITLE
Better End "EndStoneSmelter" Crashes Server (not in singelplayer)

### ISSUE THREAD

**Issue by rotgruengelb** [LunaPixelStudios/Better-MC#540]
### Describe the Bug

Server Crashes when Opening the Better End Smelter

### Reproduction Steps

1. Place End Stone Smelter.
2. Open End Stone Smelter.
---> Server Crashes (not singelplayer)

### Crash Report or Log

https://pastebin.com/N7EaUNCM

### Operating System

Debian 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v2.5

### Optifine

No

**Comment by TimestaticYT** [comment]
I tested it and figured out you just need to update BetterEnd and Bclip to the newest versions (currently bclib-2.0.16.jar & better-end-2.0.9.jar) and it stops the crashing

**Comment by SHXRKIIE** [comment]
Thanks will update the modpack today

**Comment by rotgruengelb** [comment]
thanks
