### ISSUE TITLE
World problem 2.0

### ISSUE THREAD

**Issue by Radi5224** [LunaPixelStudios/Better-MC#542]
### Describe the Bug

I have memory but when i open the world it's only typing Reading world data and after 2 minutes its shows thi
![proof](https://user-images.githubusercontent.com/106247146/179219218-b7a006b0-4ade-47c6-b838-a8e664d45773.jpg)
s

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57

### Optifine

No

**Comment by SHXRKIIE** [comment]
Whats your PC Specs? How much you allocated and what launcheR?

**Comment by Radi5224** [comment]
> Whats your PC Specs? How much you allocated and what launcheR?
16.0 GB (15.8 GB usable) RAM 
AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 2.10 GHz Processor and i use Minecraft launcher

**Comment by SHXRKIIE** [comment]
no what launcher are you using to launch and install the modpack?

**Comment by Radi5224** [comment]
> no what launcher are you using to launch and install the modpack?
Ohh i use curse forge

**Comment by Radi5224** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/9121285/latest.log)

**Comment by Radi5224** [comment]
> See if deleting this config "upgradednetherite_items-server.toml" in your saves > world > serverconfig and if its in the nomral config folder

Sorry but its the same

**Comment by Radi5224** [comment]
> See if deleting this config "upgradednetherite_items-server.toml" in your saves > world > serverconfig and if its in the nomral config folder

Can i do something different to play in my worlds

**Comment by SHXRKIIE** [comment]
can you send the latest.log again?

**Comment by Radi5224** [comment]
> can you send the latest.log again?
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/9125804/latest.log)

**Comment by SHXRKIIE** [comment]
Delete the serverconfig folder in your saves > world and see then

**Comment by Radi5224** [comment]
> Delete the serverconfig folder in your saves > world and see then

i can go in my servers but the Alchemist boss and the Summoner boss are not spawning when i use the 4 keys. Can you help me?

**Comment by SHXRKIIE** [comment]
Leave the dimension and then close the game. Go to your saves > world and delete the dimensions folder.

**Comment by Radi5224** [comment]
> Leave the dimension and then close the game. Go to your saves > world and delete the dimensions folder.

Thank you so much for everything
