### ISSUE TITLE
start.sh seems to contain a syntax error

### ISSUE THREAD

**Issue by ToasterUwU** [LunaPixelStudios/Better-MC#543]
### Describe the Bug

It seems like start.sh has a syntax error in the new version, just updated my server to v14 and try to use start.sh like i always do, and this is what i got:

```
start.sh: line 106: unexpected EOF while looking for matching `"'
start.sh: line 107: syntax error: unexpected end of file
```

### Reproduction Steps

1. Download server pack
2. Unzip it with "unzip" in ther terminal
3. cd into the new folder
4. `bash start.sh`

### Operating System

Ubuntu Server 22.04 LTS

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v14

### Optifine

No

**Comment by ToasterUwU** [comment]
Just checked and found the problem, line 31 is missing the closing " at the end.

Current: `echo "Something went wrong during the server installation. Please try again in a couple of minutes and check your internet connection.`
Fixed: `echo "Something went wrong during the server installation. Please try again in a couple of minutes and check your internet connection."`

**Comment by SHXRKIIE** [comment]
Does it work after adding "?

**Comment by ToasterUwU** [comment]
@SHXRKIIE Yes it does.
