### ISSUE TITLE
Not working with Minecolonies.

### ISSUE THREAD

**Issue by Shadow4-18** [LunaPixelStudios/Better-MC#544]
### Describe the Bug

1.18.2 versions of Better MC Forge crashes immediately after hitting play on the launcher with MineColonies installed with a exit code 1 error but not crash log. This doesn't occur on the 1.16.5 versions.

### Reproduction Steps

1. Install Better MC 1.18.2 forge Modpack.
2. Install 1.18.2 Minecolonies.
3. Launch instance and hit play on launcher and wait for the error to pop up.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v14

### Optifine

No

### Other Mods

Minecolonies
Better With Minecolonies
BlockUI
Domum Ornamentum
Multi-Piston
Structurize

**Comment by SHXRKIIE** [comment]
Send the latest.log and if I cant find the issue I wont help much as these mods arent in my modpack

**Comment by Shadow4-18** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/9125734/latest.log)

**Comment by SHXRKIIE** [comment]
Missing mandatory dependencies: blockui, structurize
Go to the minecolonies version you are using and use the correct mods version dependencies
