### ISSUE TITLE
Crash while being raided

### ISSUE THREAD

**Issue by despapito** [LunaPixelStudios/Better-MC#545]
### Describe the Bug

Hi,

I'm using BetterMC fabric. Today while being attacked by illagers i just get crashed and cant play anymore.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/7nJGtBAk

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

2.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
I am unable to reproduce this issue/ Do you mean when being raided as a Pillager Raiding a Village or?

**Comment by despapito** [comment]
Yes, pillager on singleplayer. I can upload my world if there is a need.

**Comment by despapito** [comment]
It started to crash when Pillager witches arrived

**Comment by SHXRKIIE** [comment]
So it was a Village Raid?

**Comment by despapito** [comment]
Yes

**Comment by despapito** [comment]
I've tried several times to run away but its crashing just after loading finished.
https://pastebin.com/s81papdy

**Comment by SHXRKIIE** [comment]
I have gone through a whole raid with no Issues. Did you add any mods?

**Comment by despapito** [comment]
No other mods, just BetterMC Fabric only

**Comment by SHXRKIIE** [comment]
What launcher are you using?

**Comment by despapito** [comment]
CurseForge with 6gb ram allocated

**Comment by SHXRKIIE** [comment]
Ok, can you see if updating all the mod fixes this? You do this by clicking the modpack on CurseForge then the 3 dots next to play and clicking Profile Options then Tick Allow Content Management then done, then go to installed mods and click the update button for all of them, just do 4 at a time. After you updated them all press play and see if you can join your world.

**Comment by despapito** [comment]
Did update of ~20mods but after that issue is still existing :/

**Comment by SHXRKIIE** [comment]
How long can you play until it crashes? does it immediately crash when you join or a few seconds?

**Comment by despapito** [comment]
Sometimes it crashes immediately, sometimes not - i was able to run away few meters then crash.

**Comment by SHXRKIIE** [comment]
When you join your world can you pause, click open to lan and enable cheats, then paste this in chat /kill @e[type=minecraft:witch]

**Comment by despapito** [comment]
This fixed the issue, thanks. I hope it was one time problem.
Unfortunately my entire village is dead :D

**Comment by SHXRKIIE** [comment]
Cool, I hope this doesnt happen again
