### ISSUE TITLE
Optifine crash

### ISSUE THREAD

**Issue by Piernest** [LunaPixelStudios/Better-MC#546]
### Describe the Bug

Better minecraft modpack crashes after adding optifine. Without it works perfect but affter adding it keep getting crash. I was looking for solution in the internet so i deleted dynamic assets generator, dynamic lights and magnum torch but it didn't helped.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v14

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Don't support Optifine Crashes here. Their is a mod that already makes it be able to use Shaders. I dont remember all the mods you need to remove but Oculus, Rubidium, Rubidium Extras, Rubidium Dynamic Lights, Radium Reforged & Radon I think.
