### ISSUE TITLE
Chaotic blocks

### ISSUE THREAD

**Issue by fluorohexane** [LunaPixelStudios/Better-MC#547]
![2022-07-17_20 44 05](https://user-images.githubusercontent.com/76961172/179431705-63438ce2-f8d1-419a-b48c-fbdec8ae2ef2.png)I was loading into a server and was met with chaos. I was using the aternos server service, used 0.14.8 fabric on both the mod pack loader as well as the server, had 1.19 on both but was still met with this issue. I have no clue where to start to resolve this. Please help

### server:
software : fabric
version : 1.19 (0.14.8)

### CurseForge loader
software : Fabric
Mod loader : Fabric - 0.14.8
Minecraft Version : 1.19

**Comment by SHXRKIIE** [comment]
I dont support Aternos servers as they dont have enough ram to run modded. However your issue is that Mods are not matchin the server and its up to you to fix that
