### ISSUE TITLE
serverpack start.sh line 32 lack "

### ISSUE THREAD

**Issue by lmytime** [LunaPixelStudios/Better-MC#549]
### Describe the Bug

I downlaod the lastest version serverpack. And run the start.sh script, but I find that line 32 lack a " in the end. Please notice this typo!

### Reproduction Steps

1.
2.
3.
...

### Operating System

Linux

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v14 2022/7/14 version

### Optifine

No

**Comment by SHXRKIIE** [comment]
Thanks
