### ISSUE TITLE
Missing textures. 

### ISSUE THREAD

**Issue by StonerJesuswthaBeard** [LunaPixelStudios/Better-MC#550]
### Describe the Bug

Textures for ingots and bricks are missing and a black and purple box is all there is

### Reproduction Steps

1.Launch Game with your Pack only
2.Creative Invo
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] - 1.19 & 1.18.2

### Optifine

No

**Comment by SHXRKIIE** [comment]
should be fixed in v3
