### ISSUE TITLE
stuff not loading in game for me

### ISSUE THREAD

**Issue by cbishopc** [LunaPixelStudios/Better-MC#552]
### Describe the Bug

![minecraft error](https://user-images.githubusercontent.com/109563739/179642637-05844e3e-7613-4afa-a1c1-71bf1c99dff7.png)

things like shells are loading as just a brown block for me, guessing its a modpack thats not working but dont know how to fix

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] - 1.19 & 1.18.2

### Optifine

No

**Comment by SHXRKIIE** [comment]
Your Modpack version is not matching the server
