### ISSUE TITLE
Block particles lose texture (go dark) when picking up broken block

### ISSUE THREAD

**Issue by kalisture** [LunaPixelStudios/Better-MC#553]
### Describe the Bug

When breaking blocks, there are lots of particles based on the broken block.
When picking up the dropped block, the particles immediately go black, and it is very distracting.
Decreasing Particles and other settings seems to have no effect on it.

### Reproduction Steps

1. Break a block
2. Pick up the dropped block
3.
...

### Screenshots and Videos

https://gfycat.com/meanflippantdwarfmongoose

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [FORGE] v13

### Optifine

No

**Comment by SHXRKIIE** [comment]
This is just the oculus mod doing it
