### ISSUE TITLE
Missing Texture - Plain Item Frame

### ISSUE THREAD

**Issue by Nobodyknowsnothin** [LunaPixelStudios/Better-MC#555]
### Describe the Bug

Whenever I place a non-glowing Item Frame, it shows up as a 1x1 block of checkered pink & black pattern instead of the item frame being placed.

### Reproduction Steps

1. Equip any Item Frame (the plain, non-glowing kind) in hand.
2. Click to try to place Item Frame anywhere an Item Frame can normally be placed (wall, floor, etc).
3. See the weird box placed instead of an Item Frame.

### Screenshots and Videos

![Screenshot (5)](https://user-images.githubusercontent.com/109646103/179903035-4735e738-5aa1-43da-9fe7-f23c4938d8c3.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] v3

### Optifine

No

**Comment by SHXRKIIE** [comment]
Try F3 + A if that doesnt work try F3 + T to reload resourcepacks
