### ISSUE TITLE
Crashes when player joins the singelplayer server

### ISSUE THREAD

**Issue by p1kuke** [LunaPixelStudios/Better-MC#558]
### Describe the Bug

My game crashes every time when my friend joins the server. I open the port and share it with a friend who is just joining me. Without making a server btw.

### Reproduction Steps

1. Joining the world
2. Open to LAN
3. Open ports
4. Friend joining
5. Game crashes
...

### Crash Report or Log

https://pastebin.com/YXBedsMH

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

No

**Comment by SHXRKIIE** [comment]
LAN is untested and shouldnt be used. Either host the server on your pc or from the error it suggests Merchant Markers, so remove that mod other than that I cant help much
