### ISSUE TITLE
MP Server Bug (java.lang.IndexOutOfBoundsException)

### ISSUE THREAD

**Issue by salemrya** [LunaPixelStudios/Better-MC#559]
### Describe the Bug

Server running in docker on V1.19

Internal exception: io.netty.handler.codec.DecoderException

### Reproduction Steps

1.Open Better MC [Fabric]
2.Connect to server
3.
...

### Screenshots and Videos

https://imgur.com/c1Y6TjA

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v3

### Optifine

No

**Comment by SHXRKIIE** [comment]
What is a docker? and on Windows 11 and Bisect Hosting I have no issues connecting
