### ISSUE TITLE
Occasional Crashing allegedly caused by something in Twilight Forest mod

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-MC#560]
### Describe the Bug

Hello! i have come to give a bug that occasionally happens almost like the audio bug that is a common occurrence. when you boot up the game after the said bug, or by random chance, this crash occurs where the synopsis of the crash is caused by the Twilight Forest Mod. Its a strange glitch for sure, but i hope this is a very minor blip that only happens randomly

### Reproduction Steps

1. Boot up the game
2. have the occasional chance where the game's loading bar loads twice. wait for the crash.

### Crash Report or Log

https://pastebin.com/iYKYU3mh

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

14

### Optifine

No

**Comment by SHXRKIIE** [comment]
This seems to be a loading error by Twilight causing all the resourcepacks to be disabled. Thanks for the report
