### ISSUE TITLE
Lava is missing textures

### ISSUE THREAD

**Issue by Chaserbug0709** [LunaPixelStudios/Better-MC#561]
### Describe the Bug

All lava is missing its textures, even after relogging, in the overworld and nether

### Reproduction Steps

1. Just view lava
2.
3.
...

### Screenshots and Videos

![Uploading 2022-07-20_20.02.23.png…]()
![2022-07-20_20 01 57](https://user-images.githubusercontent.com/109706624/180108018-38b9a1df-01d5-40ef-b7c8-1589573bc76d.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC V3

### Optifine

No

**Comment by SHXRKIIE** [comment]
Try F3 + A if that doesnt work try F3 + T to reload resourcepacks
