### ISSUE TITLE
Can't play after saving and closing

### ISSUE THREAD

**Issue by PoetG** [LunaPixelStudios/Better-MC#562]
### Describe the Bug

The resources packs that are used at world generation don't show up in the main menu. So whenever I go to play a world I've saved it says missing resource packs and to start up in safe mode or to re-enable them. I don't know how to fix it or maybe if it's a bug.

### Reproduction Steps

1. Make a new world
2. Use resource packs as shown in screenshot (6)
3. Save and leave
4. Try to rejoin but get safe mode message
5. Can't find resource packs in screenshot (10)
...

### Screenshots and Videos

![Screenshot (6)](https://user-images.githubusercontent.com/93642145/180128714-a70a4bbb-52e0-4d36-babd-95b986097665.png)
![Screenshot (10)](https://user-images.githubusercontent.com/93642145/180128856-1a520c48-e03b-448d-818c-e01c866c14cb.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

https://www.curseforge.com/minecraft/modpacks/better-mc-fabric/files/3882402

### Optifine

No

**Comment by PoetG** [comment]
So I've found a what I think is temp. fix. I found all the necessary datapacks online and manually downloaded them and threw them into my world's datapack folder. I dunno if this is something that could be a result of downloading a couple more mods but it works now hopefully...

**Comment by SHXRKIIE** [comment]
This shouldn't be happening and it is probably caused by something you did
