### ISSUE TITLE
game crashes when i open a chest.

### ISSUE THREAD

**Issue by chrisd63** [LunaPixelStudios/Better-MC#563]
For the past 3 or 4 times I have tried to play, every time I have loaded in, I wait about 2-3 minutes to make sure everything is rendered and working. I try to open a chest, and the entire game freezes. I'm able to walk around, but unable to craft, interact with anything, or explore the map. Also, upon quitting to the main menu, I get stuck on "Saving Game" screen with the dirt background. I'm unable to terminate the program with task manager, nor able to force it closed any other way than a restart. Some help with this would be greatly appreciated, I've fallen in love with the game and would love to be able to continue playing!

**Comment by SHXRKIIE** [comment]
Please use the Template next time.
Describe the Bug (What chest from where any specific place?, on a server?)
Reproduction Steps
Crash Report or Log
Operating System
Minecraft Version
Modloader
Modpack Version
Other Mods

**Comment by chrisd63** [comment]
Pictures show the steps I take to launch the game, and several pictures to show that I do not have the ability to craft or interact with anything

Sorry about this, I filled out your template, but the website told me “all fields marked with a * are required to submit” and all required fields had been filled out, So I Went to the option that gave me an alternative if the bug report didn’t work lol I’ll fill out this template for you no problem though, I just figured you would want to know that since I saw the bug template was fairly new! :)

**Describe the Bug (What chest from where any specific place?, on a server?)**

it was on a local single player survival game. Within this game, I have been looking for a way stone before I set up a home, so I have uncovered a lot of the map wandering with a full inventory. Maybe about 2000 south of spawn I came across a village, and this is where this bug keeps happening. I try to open any chest in the village (one inside a house, the other is a set of double chests in a grave) and the game freezes. I’ve had this same type of crash happen before on other worlds though, seems like when I’m exploring above ground uncovering the map. The first time it happened I was in a boat trying to reach the next continent over and chunks stopped loading, map stopped updating, and I eventually was in a boat floating in space (also, same as previously stated, i can’t craft or interact with anything, I couldn’t leave the boat, I would press shift and I would crouch in the boat) 

I’ve had this ALMOST happen a couple of times as well. I would go to access a chest (at home, out looting, anywhere) there would be about 5-7 seconds were I could walk around before it caught up and opened the chest UI. 

The worst part of this is the restart that is needed to close out the game. The last picture of the “saving world” dirt screen will never go away. I have tried terminating the parent file, ending task in the task manager, but to no avail. There are 3 Minecraft launchers running in my task manager that, when ended, will repopulate after a couple of minutes. 

My next step is to uninstall and reinstall if possible, and that may very well fix it. If it doesn’t, you will most likely hear from me again for possible solutions to solve this. Thank you so much! 😁

**update on this, when launching the game for the video, I didn’t even open a chest, or walk or anything before the game froze. It happened about 2 minutes after the game started. The game loaded, all of the villagers were walking around for a minute or two, then when I started trying to move around, everything froze. Unfortunately, my Gmail app couldn’t attach the video, so I won’t be able to include the video***

![unnamed](https://user-images.githubusercontent.com/109714979/180246704-bbe3ffb1-c500-47ec-8aeb-6a142fd926b7.jpg)
![image_6487327 (10)](https://user-images.githubusercontent.com/109714979/180247106-e0932c76-43dc-4e76-b8c8-31c9de7d7b72.JPG)
![image_6487327 (9)](https://user-images.githubusercontent.com/109714979/180247119-b66f4878-d27c-4f35-92b0-0199f4201f7d.JPG)
![image_6487327 (8)](https://user-images.githubusercontent.com/109714979/180247125-6da23064-be25-43a1-8097-dc1bae539ffa.JPG)
![image_6487327 (7)](https://user-images.githubusercontent.com/109714979/180247134-058a2739-822d-4dea-a506-100104596541.JPG)
![image_6487327 (6)](https://user-images.githubusercontent.com/109714979/180247138-7baca592-aded-4fdf-9411-f096d7530295.JPG)
![image_6487327 (5)](https://user-images.githubusercontent.com/109714979/180247149-8ddc14c3-5c9b-496b-9731-79ad15a5637c.JPG)
![image_123927839](https://user-images.githubusercontent.com/109714979/180247154-d6834e78-0b0d-4c9d-b699-c0b63ba22400.JPG)
![image_6487327 (4)](https://user-images.githubusercontent.com/109714979/180247158-8eaa1278-bddb-4444-9e4f-f48a78386f1a.JPG)
![image_6487327 (3)](https://user-images.githubusercontent.com/109714979/180247161-ebe825c0-3c8c-4775-873f-980db740d2c8.JPG)
![image_6487327 (2)](https://user-images.githubusercontent.com/109714979/180247165-252e4f12-21ee-44f4-ad28-e780fc5a8c8d.JPG)
![image_6487327 (1)](https://user-images.githubusercontent.com/109714979/180247174-21c2c44a-b918-41f7-b826-c4f8742efe2b.JPG)
![image_6487327](https://user-images.githubusercontent.com/109714979/180247179-abc5a8da-b182-4093-b608-04b8d6d7d5d7.JPG)


**Reproduction Steps**

upon loading in the game, any attempt to open a chest in the village I am in freezes the game.

**Crash Report or Log**

no crash report associated that I know of. I can double check the system files if need be 

**Operating System**

windows 10

**Minecraft Version**

1.18.2

**Modloader**

curseforge better Minecraft [fabric] - 1.18.2
Fabric-loader-0.13.3-1-18.2

**Modpack Version**

V3

**Other Mods**

no other mods have been added to this pack.

**Comment by SHXRKIIE** [comment]
From what I can see is this modpack is very outdated. v12 is the latest for 1.18.2. and v3 for 1.19 which you are not on. Please reinstall the modpack.
