### ISSUE TITLE
start.sh file missing in newest server pack.

### ISSUE THREAD

**Issue by TimestaticYT** [LunaPixelStudios/Better-MC#564]
### Describe the Bug

Now the only way to use it now is to manually install a fabric or copy the old script to use it. I wonder why that happened.

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Server Pack [FABRIC] v3

### Optifine

No

**Comment by SHXRKIIE** [comment]
I dont include it anymore because I dont test with it as I dont have other operating systems so their is no way for me to make sure it works
