### ISSUE TITLE
Apotheosis not working properly

### ISSUE THREAD

**Issue by clipperkid** [LunaPixelStudios/Better-MC#565]
### Describe the Bug

The shelves and enchants aren't working properly with the enchantment table. I'm not seeing the different bars and I'm not getting any enchants passed lvl 30 regardless of what shelves I use. I also can't infuse bookshelves to progress passed the low level shelves because the enchantment table isn't reading the bookshelves as enchantable items. I can still anvil enchants passed vanilla level.

Thank you for your time.

### Reproduction Steps

1. Create standard 15 bookshelf enchantment area
2. Test enchantment levels
3. Use Apotheosis bookshelves along side vanilla shelves
4. Test enchants
5. Remove vanilla shelves and only use Apotheosis shelves
6. Test enchants
7. Add Apotheosis bookshelves and attempt to infuse them
...

### Screenshots and Videos

![2022-07-21_20 04 23](https://user-images.githubusercontent.com/109771275/180334882-ac3b916b-4250-45c9-b5a1-96608235a23b.png)
![2022-07-21_20 02 32](https://user-images.githubusercontent.com/109771275/180334887-7f27718e-f6bc-40cc-8a92-c2f63ff365ce.png)
![2022-07-21_20 03 06](https://user-images.githubusercontent.com/109771275/180334893-1edeb751-7106-479b-b418-ba044abdcbb5.png)
![2022-07-21_20 03 22](https://user-images.githubusercontent.com/109771275/180334897-a9a5b893-435b-4b80-8fa7-d1a107b0a24a.png)
![2022-07-21_20 03 24](https://user-images.githubusercontent.com/109771275/180334901-ad57d6d0-2cba-4b90-9cd9-2d62a67672ca.png)
![2022-07-21_20 03 28](https://user-images.githubusercontent.com/109771275/180334907-3544d36d-fba9-4279-8db0-09d4e4cfe3f6.png)
![2022-07-21_20 03 57](https://user-images.githubusercontent.com/109771275/180334911-b7d7b2a7-5b4a-46fa-b370-4843293dbb09.png)
![2022-07-21_20 03 59](https://user-images.githubusercontent.com/109771275/180334916-8a7f0fd7-22f5-4b02-a7e1-0a1ce2f0942c.png)
![2022-07-21_20 04 00](https://user-images.githubusercontent.com/109771275/180334919-efab885f-54e1-4230-b2dd-1fe47b17dc82.png)
![2022-07-21_20 04 10](https://user-images.githubusercontent.com/109771275/180334924-674dfd0d-44fe-4111-b449-0ca0871c5d91.png)
![2022-07-21_20 04 20](https://user-images.githubusercontent.com/109771275/180334926-38127d3d-f83d-4e01-9ed9-f000612fdb7a.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC+ v13

### Optifine

No

### Other Mods

I have added:
Falling tree 1.18.2-3.5.3
Vein mining 1.18.2-0.18
Every Compat 1.18.2-1.5.9

**Comment by clipperkid** [comment]
I removed the resource pack and the same thing is happening. There was one
other who had the same issue as I did a while back on reddit, but there was
no clear resolve to it. None that I found anyways.

**Comment by SHXRKIIE** [comment]
Can you show me  a screenshot without the resourcepacks?
