### ISSUE TITLE
Missing Texture - Dirt Blocks

### ISSUE THREAD

**Issue by Nobodyknowsnothin** [LunaPixelStudios/Better-MC#566]
### Describe the Bug

I just loaded up my game, it downloaded a few mbs update and when I started up the game world and now the pink & black checkered tiles are Everywhere where dirt blocks used to be.

### Reproduction Steps

1. Ran the game launcher from Curseforge app.
2. Started up the game.
3. Watched said game do a small update.
4. Loaded up a Minecraft world that predates the recent update.
5. Look upon the checkered pink & black tiles that now dot the entire landscape.
6. Test with dirt (not grass, specifically Dirt) blocks, place dirt block anywhere. 
7. See the checkered pink & black blocks placed where dirt texture would've been.

### Screenshots and Videos

![Screenshot (6)](https://user-images.githubusercontent.com/109646103/180395295-0a43626c-be7d-4b1a-8554-6eecc9720783.png)
![Screenshot (7)](https://user-images.githubusercontent.com/109646103/180395978-21a62ca0-5311-4afb-9ed9-d37150dd7322.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] v3

### Optifine

No

**Comment by SHXRKIIE** [comment]
Press F3+T
