### ISSUE TITLE
Magnetic Ring Adds slot called BYG Biomepedia in Inventory

### ISSUE THREAD

**Issue by 100123424** [LunaPixelStudios/Better-MC#568]
### Describe the Bug

Magnetic Ring Adds a button under the crafting table in your inventory and when clicked it takes you to the biomepedia.

### Reproduction Steps

1. Equip Magnetic Ring
2. Open Inventory And go to the button located under the crafting menu
3. Click it to open BYG Biomepedia
...

### Screenshots and Videos

![bug](https://user-images.githubusercontent.com/104964069/180595743-5d059fa3-6146-4401-a10d-36b1febb59b6.JPG)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

https://www.curseforge.com/minecraft/modpacks/better-mc-plus-new

### Optifine

No

### Other Mods

No Mods Added

**Comment by SHXRKIIE** [comment]
Disable the biompedia in config in BYG
