### ISSUE TITLE
I have problems with the particles of the atmosphere.

### ISSUE THREAD

**Issue by Ancard** [LunaPixelStudios/Better-MC#570]
### Describe the Bug

some kind of problem with the textures of some environmental particle mod.

### Reproduction Steps

1.Install from curse.
2.start new game.
3.wait for night.

### Screenshots and Videos

![2022-07-23_23 26 29](https://user-images.githubusercontent.com/24949481/180629705-b9f93c78-f3e0-426f-be35-ee12e71f12b4.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

[FABRIC] v3

### Optifine

No

### Other Mods

No

**Comment by SHXRKIIE** [comment]
Press F3 + T
