### ISSUE TITLE
Cannot load CraftTwekaer mod correctly 

### ISSUE THREAD

**Issue by p1kuke** [LunaPixelStudios/Better-MC#571]
### Describe the Bug

Open the mod pack on ATLauncher, then wait for Minecraft to start loading, while loading there is a red Mojang screen and then pop-ups the error. That Crafttweaker mod cannot load correctly.

### Reproduction Steps

1. Start BMC on ATLauncher
2. Wait for BMC to load
3. Error occurred

### Crash Report or Log

https://paste.atlauncher.com/view/ba6d18b2-5911-4825-8496-89ef1a269329

### Operating System

macOS Monterey

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

No

**Comment by SHXRKIIE** [comment]
See if you can launch it again if not remove the mod

**Comment by p1kuke** [comment]
No, I couldn't.

**Comment by p1kuke** [comment]
> See if you can launch it again if not remove the mod
No, I couldn't.
