### ISSUE TITLE
No Nether Quarz and Gold generation in the Nether

### ISSUE THREAD

**Issue by Xo-larian** [LunaPixelStudios/Better-MC#572]
### Describe the Bug

I installed the Modpack on my Minecraft Fabric Server. There is for some reason no generation of Nether Quarz and Gold in the Nether. I tried turning off the "Better Nether"-Mod but that didn't fix the issue. 

### Reproduction Steps

1. Start the Modpack and go to the Nether.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v3

### Optifine

No

### Other Mods

I just added "MC Dungeons Artifacts".

**Comment by salvailuciano** [comment]
Did You try it in modpack versión bcm v4?

**Comment by Faerlinchen** [comment]
Hello,
I got the same problem. 
I just tested it with bcm v4 ( and no additional mods installed )... here is also no gold and netherquarz generation in the nether.

**Comment by SHXRKIIE** [comment]
Will be fixed in v5
