### ISSUE TITLE
Texture-bug

### ISSUE THREAD

**Issue by Akashixkun** [LunaPixelStudios/Better-MC#573]
### Describe the Bug

Hello nice support, I currently have a texture error with scrolling on the map. There are water blocks all around me as well as graves, so I wanted to reach out to you that you might be able to help me with this problem.

### Reproduction Steps

1. 
2.
3.
...

### Screenshots and Videos

![texture bug](https://user-images.githubusercontent.com/109903888/180646569-ce9540a7-efda-4c53-b10a-e2fb421ea31b.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Server and Client mods dont match
