### ISSUE TITLE
Bug Textures - Missing Textures

### ISSUE THREAD

**Issue by RasTeck** [LunaPixelStudios/Better-MC#575]
### Describe the Bug

In the game, I could see that the "Dirt" texture has a bug. I'm playing v4. But in the "JEI" the texture is normal, I think the problem is when the "SPRITE" joins another.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-07-24_17 17 53](https://user-images.githubusercontent.com/30821017/180668703-2d64d153-a026-42d2-8199-6d00674f33a2.png)
![2022-07-24_17 19 14](https://user-images.githubusercontent.com/30821017/180668704-7dad0259-19dc-45e6-80f0-62cb33695b22.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V4

### Optifine

No

**Comment by SHXRKIIE** [comment]
Press F3 + T
