### ISSUE TITLE
No generation of Big Structures

### ISSUE THREAD

**Issue by Xo-larian** [LunaPixelStudios/Better-MC#576]
### Describe the Bug

The fabric Modpack is installed to my fabric server. Since v3 (also tried v4) somethings wrong with the generation of those big structures which are from "When the Dungeons Arise", i guess. They won't generate by generating new Chunks while exploring the World.
I think I kind of fixed the issue by deleting puzzles lib and the mods that require it.
But still not sure what causes this problem. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v4

### Optifine

No

### Other Mods

I just added "MC Dungeons Artifacts".

**Comment by SHXRKIIE** [comment]
They are generating for me and v4 literally just came out so not sure how already played it.

**Comment by Xo-larian** [comment]
Alright weird, because I startet several new worlds in v4 and flew around the world generating new chunks and it didn't work for me. Maybe the problem lies somewhere on my server, I'll look further into it. Thanks.
