### ISSUE TITLE
screen

### ISSUE THREAD

**Issue by fifpro** [LunaPixelStudios/Better-MC#577]
### Describe the Bug

i cant play normally cuz i have yellow screen 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-07-25_16 54 59](https://user-images.githubusercontent.com/109974063/180807333-593410ed-e638-47b0-a1d2-2b6f03132d72.png)

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

idk

### Optifine

No

**Comment by SHXRKIIE** [comment]
Reinstall the modpack, other than that i cant really help
