### ISSUE TITLE
warden and sculk biome wont load 

### ISSUE THREAD

**Issue by D1nkelberg** [LunaPixelStudios/Better-MC#578]
### Describe the Bug

i get this spammed in my server console, the server doesnt crash but i still would like to fix this message spamming. Its also happends in the v11, v12 and in the current v13 version of the mod
![server log](https://user-images.githubusercontent.com/110016196/180943821-bb8837cc-7d66-4d3a-8e17-b20ebdc501f5.PNG)
 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC Plus v13

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
This mod was replaced in v12.5 with the Wold backport.

**Comment by D1nkelberg** [comment]
and what does that mean now?
