### ISSUE TITLE
my fps are weird

### ISSUE THREAD

**Issue by JamonSan** [LunaPixelStudios/Better-MC#579]
### Describe the Bug

well idk if this is a bug or something but when I press F3 my fps increases but when I turn it off again and my fps go down, 
idk why it works like this.

(my english is shit i'm sorry)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/110034885/181003389-504c9732-49f9-4c37-8213-26c7c104ff4c.mp4

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2

### Optifine

No

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/charging-gadgets/download/3725841
https://www.curseforge.com/minecraft/mc-mods/shrink_/download/3786356
mining gadgets
global xp

**Comment by SHXRKIIE** [comment]
Allocate more ram
