### ISSUE TITLE
Custom Texture Pack Doesn't Work?

### ISSUE THREAD

**Issue by Aura1847** [LunaPixelStudios/Better-MC#580]
### Describe the Bug

So I have tried to use faithful x64 and noticed some textures change and some stay the normal minecraft textures i thought maybe its the load order but no matter where it goes it still doesnt fix i tried a different texture pack and also does the same thing was wondering if this is fixable.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V14

### Optifine

No

**Comment by SHXRKIIE** [comment]
Update the Modpack
