### ISSUE TITLE
Better MC Crashes consecutively

### ISSUE THREAD

**Issue by villaxd123** [LunaPixelStudios/Better-MC#581]
### Describe the Bug

After play between 10 - 20 minutes with some friends the modpack the game crashes, mostly crashes and doesn't closes the game and sometimes shows server tick loop, i already tried using the official launcher and ATLauncher and the problem persist.
Aclaration, the game crashes when i (the host) is in other dimension, when i'm on the overworld it takes almost 40 minutes to crash.

### Reproduction Steps

1. Open the world: La 3ra es la vencida (The 3rd is lucky one)
2. Open in LAN
3. My friends connect to my world
4. Play between 10 - 20 minutes
5. Game Crashes
...

### Screenshots and Videos

![imagen](https://user-images.githubusercontent.com/29488884/181133512-22632aa7-9422-4be9-9d1b-091406438227.png)
![imagen](https://user-images.githubusercontent.com/29488884/181133525-6d0413fd-87c5-48f6-88b4-58a71815cb8d.png)
![imagen](https://user-images.githubusercontent.com/29488884/181133538-223b900c-107f-46f8-8c15-07f2e38eaa50.png)

Sorry but i didn't take a screenshot from ATLauncher.

### Crash Report or Log

https://pastebin.com/PApMumBG

### Operating System

Windows 10 (21H1) - Compilation 19043.1826

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v39.5 

### Optifine

No

**Comment by SHXRKIIE** [comment]
LAN is untested and this is why you dont use it, Depth is crashing your game, either host a server on your pc and not play LAN
