### ISSUE TITLE
run.sh doesnt work on linux server

### ISSUE THREAD

**Issue by Suver112** [LunaPixelStudios/Better-MC#583]
### Describe the Bug

When I want to run my server on ubuntu server there appears some kind of a problem,
On Windows everything works perfectly

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![obraz_2022-07-27_134744179](https://user-images.githubusercontent.com/110102662/181239191-44e51159-f59d-4835-b46f-7423827d2e28.png)

### Operating System

Ubuntu Server

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v14

### Optifine

No

**Comment by SHXRKIIE** [comment]
add " on line 32 otherwise just create your own start.sh which is easy youtube search
