### ISSUE TITLE
Corrupted chunks/Server crashing

### ISSUE THREAD

**Issue by KillerChris** [LunaPixelStudios/Better-MC#585]
### Describe the Bug

After updating from Better Minecraft Plus v11.5 to v13, many areas previously discovered end up lagging or ultimately crashing the server. When I go into console to check logs to see what could be happening I get lines of code such as the image I have attached. It only happens in the overworld and in already explored chunks. This occurs in multiple different parts of the world.

### Reproduction Steps

1. Going to my friend's house in the overworld
2. Simply just travelling to previously explored parts of the world.
3.
...

### Screenshots and Videos

![Console Logs](https://user-images.githubusercontent.com/93053852/181341951-3fe16ba7-e93f-4d60-aa42-97cc06d9f92f.PNG)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft Plus V13

### Optifine

No

**Comment by SHXRKIIE** [comment]
Need crash report

**Comment by KillerChris** [comment]
How do I get a crash report

**Comment by SHXRKIIE** [comment]
in the crash reports folder in the modpack folder

**Comment by KillerChris** [comment]
[crash-reports_crash-2022-07-28_22.56.12-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/9216106/crash-reports_crash-2022-07-28_22.56.12-server.txt)

**Comment by SHXRKIIE** [comment]
Either revert back to older version or make a new world as you updated with a mod removed that caused some issues

**Comment by KillerChris** [comment]
There's no work around for this? What mod was removed?
