### ISSUE TITLE
Item search

### ISSUE THREAD

**Issue by 01Marquis10** [LunaPixelStudios/Better-MC#586]
### Describe the Bug

Whenever i press E to access my inventory and press the search bar to find a specific item nothing happens. leading to me having to scroll through 60ish pages to find a specific item.
![2022-07-27_21 50 01](https://user-images.githubusercontent.com/110128420/181369697-c9e16a0d-4848-458c-bbb4-9ff3bc3b8978.png)

### Reproduction Steps

1. Press E
2. Click on search bar
3. Type item
4. UI on left side doesn't change.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [Fabric] - 1.19 & 1.18.2 (v3)

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Restart your game, did you happen to mess with the REI settings?

**Comment by 01Marquis10** [comment]
My REI setting was the default i started with,
