### ISSUE TITLE
Spirit mod recipes crashing client

### ISSUE THREAD

**Issue by RavenSST** [LunaPixelStudios/Better-MC#587]
### Describe the Bug

When looking for recipes or uses for spawners client crashes.

### Reproduction Steps

1.Simply search uses for spawners.

### Crash Report or Log

https://pastebin.com/eFfjipw3

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

No

### Other Mods

Luggage, Sophisticated core/backpacks.

**Comment by SHXRKIIE** [comment]
Update the mod or wait for Modpack Update
