### ISSUE TITLE
no, there are no shaders mr moderator

### ISSUE THREAD

**Issue by wilkuwdz21** [LunaPixelStudios/Better-MC#589]
### Describe the Bug

no shaders in bettermc 1.19
![Zrzut ekranu 2022-07-28 121118](https://user-images.githubusercontent.com/103502584/181481058-ffc4225d-960b-4c14-b686-adb0e5aeadc9.png)
9

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V4

### Optifine

No

**Comment by SHXRKIIE** [comment]
Reinstall because it is their unless you modified the modpack

**Comment by wilkuwdz21** [comment]
> Reinstall because it is their unless you modified the modpack

my friend that freshly installed it doesnt have the option, people on youtube under certain tutorial about shaders on 1.18 also upvote my comment that there isnt shader option for them, do you mind sending a screenshot of how your settings screen looks like?

**Comment by wilkuwdz21** [comment]
maybe its because i use fabric version? are you using fabric 1.19 or forge 1.19?

**Comment by SHXRKIIE** [comment]
As I said reinstall the modpack, unless you modified the modpack it will be there
![image](https://user-images.githubusercontent.com/79353591/181483412-6428ee10-0a62-4e5a-a161-557d42045bc4.png)

**Comment by SHXRKIIE** [comment]
their is no forge 1.19 better mc
