### ISSUE TITLE
Strange AdventureZ Stone Golem Crash

### ISSUE THREAD

**Issue by rotgruengelb** [LunaPixelStudios/Better-MC#590]
### Describe the Bug

The only known triggers are going to the nether, but I don't know if it matters where you go into the nether.
Server Crash report points at AdventureZs Stone Golem.

### Crash Report or Log

https://pastebin.com/pZk7zPAN

### Operating System

Debian 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v4

### Optifine

No

### Other Mods

BanHammer (Moderation Mod by PatBox) https://www.curseforge.com/minecraft/mc-mods/patboxs-banhammer/

**Comment by SHXRKIIE** [comment]
Disable the Stone golem in the configs for now
