### ISSUE TITLE
interfaz de inventario bugueada

### ISSUE THREAD

**Issue by Rubescu** [LunaPixelStudios/Better-MC#591]
### Describe the Bug

el bug es muy simple si pongo objetos en el inventario y lo cierro estos siguen apareciendo en la pantalla, como si el inventario estuviese abierto.

### Reproduction Steps

1.cojo objeto
2.abro  inventario
3.lo quito de la zona de la mano y cierro onventario
...

### Screenshots and Videos

https://user-images.githubusercontent.com/110187756/181585326-8f452078-086b-45b0-b682-ce0dfe11487f.mp4

### Operating System

propio minecraft

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

better minecraft

### Optifine

No

### Other Mods

no

**Comment by SHXRKIIE** [comment]
Dont speak your language, press O or I
