### ISSUE TITLE
server lag

### ISSUE THREAD

**Issue by googlegeekss** [LunaPixelStudios/Better-MC#592]
### Describe the Bug

i have a server with 8 gb ram but the server r lagging like when we eat it takes a long time  or when we r generating the world the server lags.

we r max 6 people in the server but normally with 3 guys the server starts lagging 

just tell me how many ram do i need on the server to stop the lag.

### Reproduction Steps

1. -
2.
3.
...

### Crash Report or Log

-

### Operating System

.

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
You need to pregen the world otherwise it will lag
