### ISSUE TITLE
The Server Dosent start

### ISSUE THREAD

**Issue by Skurusss** [LunaPixelStudios/Better-MC#593]
### Describe the Bug

if i want to start the server it says "./start.sh zeile 106: dateiende beim suchen nach `"' erreicht. And 107:  sytax fehler: Unerwatetes Dateiende.

### Reproduction Steps

1.just install it and try tostartit thefirst time

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/109823724/181748627-ff6225d8-2004-4c72-89ba-ebbeab88a1b7.png)

### Operating System

Debian 9

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Better MC [FORGE] v14 

### Optifine

No

**Comment by SHXRKIIE** [comment]
add " on line 32 otherwise just create your own start.sh which is easy youtube search

**Comment by Skurusss** [comment]
i dit that and its still saying that there is no ending me dumm
