### ISSUE TITLE
Follow Up to Corrupted World

### ISSUE THREAD

**Issue by KillerChris** [LunaPixelStudios/Better-MC#594]
### Describe the Bug

You replied to me before, but closed the thread before I could ask this question. What mod was removed with the new update of Better MC from version v11.5 to v13 that's causing my server to constantly crash?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft Plus V13

### Optifine

No

**Comment by SHXRKIIE** [comment]
Sculk & Warden but its not recommended to add back
