### ISSUE TITLE
Duplication with Storage Drawers

### ISSUE THREAD

**Issue by Ylgnik** [LunaPixelStudios/Better-MC#595]
### Describe the Bug

I was told to put this here so I am.

When putting a storage drawer (1x1) as a stack in the crafting table (so 64 or even 62) and putting 1 or more of the same upgrade like the Upgrade 1, it will duplicate the items and all the stacks you get have the upgrades in them and it doesn't use the items on the crafting table.
![2022-07-30_14 55 31](https://user-images.githubusercontent.com/105905730/181994558-2e6d30b6-9296-4d7f-89a0-30668ca11cce.png)
![2022-07-30_14 57 11](https://user-images.githubusercontent.com/105905730/181994559-9bc338f7-f900-4349-bbf4-6a336e4795b1.png)
![2022-07-30_14 57 15](https://user-images.githubusercontent.com/105905730/181994560-fe2df15e-5250-4f03-b7fa-4414807303a6.png)
![2022-07-30_14 58 27](https://user-images.githubusercontent.com/105905730/181994561-582566e8-67cc-4289-926c-fbff92ef1e84.png)

### Reproduction Steps

1. Put 1x1 Storage Drawer as a stack in the crafting table (I used 64).
2. Put any of the upgrades in the crafting table ( I had 7 of them but 1 works too).
3.  Press Shift+Enter to make the item.
4.  It will give you a bunch of items back with the upgrades already installed while keeping the old stuff in the crafting table.

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better Minecraft Plus v39.5

### Optifine

No

### Other Mods

No other mods

**Comment by SHXRKIIE** [comment]
Thanks for the report
