### ISSUE TITLE
Portable crafting not working

### ISSUE THREAD

**Issue by BluVirus** [LunaPixelStudios/Better-MC#598]
### Describe the Bug

I was previously playing BMC on V2.5 on a third-party hosted Minecraft server with my friends and the portable crafting from Charm was working fine (being able to craft items just by having a crafting table in your inventory), however after we updated our version to V4, we found out that we could no longer make use of this feature as both the button in the inventory as well as the hotkey disappeared.

### Reproduction Steps

1. Create crafting table
2. Hold it inventory
3. Open Inventory (note missing button)
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/110388792/182125026-34641821-da14-4d62-a020-c7b959d7777a.png)

Note that the portable crafting button is missing despite having a crafting table

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc V4

### Optifine

No

**Comment by Pyres1** [comment]
You have to go into Mod menu and Select Charm. In the top right hand corner you will see a button with 3 little lines that says configure when you mouse over it. Click this button. Scroll down the list to +PortableCrafting. Click this and enable the module. This will add the feature you are looking for. Same thing happened to me.
