### ISSUE TITLE
nether ruby not dropping after being mined

### ISSUE THREAD

**Issue by gamer45505** [LunaPixelStudios/Better-MC#600]
### Describe the Bug

when i try to mine nether ruby nothing will drop except exp and ive tried diamond, iron, gold, wood, and netherite pickaxes and still would not drop

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v3

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
WIll be fixed in v5, need to use Diamond and above

**Comment by OhhBucket** [comment]
I just mined 39 ore with fortune 3 and not a single ruby dropped. i was just given xp
