### ISSUE TITLE
waystone and quest boards not generating 

### ISSUE THREAD

**Issue by shadypenguin1** [LunaPixelStudios/Better-MC#601]
### Describe the Bug

my experience with the way stone and bountiful mods in 1.16.5 is that both way stones and quest boards spawn naturally in villages, however, on my multiplayer server we have not seen a single naturally spawning item from either mod. if anyone knows what the issue is it would be a great help.

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

57.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
They do spawn
