### ISSUE TITLE
Minecraft crafting bench crashes

### ISSUE THREAD

**Issue by ichtycushie** [LunaPixelStudios/Better-MC#602]
### Describe the Bug

Hi, every time someone in my server tries to craft something in the workbench it instantly crashes the whole server.
Please help lol.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/GM4naXGK

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MC PACK [FORGE] v57.5

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Remove visual workbench mod
