### ISSUE TITLE
cant join server

### ISSUE THREAD

**Issue by fooboy567** [LunaPixelStudios/Better-MC#603]
### Describe the Bug

an error code shows up every time i try to join right after it says "joining world" (im using minehut to host and ive tried resetting the server and the world and a few other things like removing resetting the server and then re-adding the mods)

### Reproduction Steps

1. downloaded better mc modpack for 1.19 (fabric)
2. downloaded the server pack for 1.19 (fabric)
3. added the server pack to my minehut server (set the server to fabric 1.19)
4. launched better mc and went into my server
5. error message that was shown in screenshot

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/110426137/182241370-4f50cc7e-7890-47aa-ba6b-e9a046485b67.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v4 zip

### Optifine

No

**Comment by SHXRKIIE** [comment]
It works, cant really help with other serverhost issues
