### ISSUE TITLE
Picking up Duck (Ducklings MOD) Crashes game for anyone rendering Animation

### ISSUE THREAD

**Issue by Slinkaroo** [LunaPixelStudios/Better-MC#604]
### Describe the Bug

If a player picks up a duck from the ducklings mod, anyone in range who renders the animation's game will crash. If the player picks up the duck in 3rd person there game will also crash.

### Reproduction Steps

1.Pick up Duck With 2nd player infront of you
2. Pick up the duck in 3rd person if alone

### Operating System

Windows 10 Pro

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V15

### Optifine

No

**Comment by SHXRKIIE** [comment]
yeah he is not meant to be picked up. need to blackist it
