### ISSUE TITLE
Villagers don't restock their trades

### ISSUE THREAD

**Issue by Xo-larian** [LunaPixelStudios/Better-MC#605]
### Describe the Bug

I discovered that there is a restocking bug in minecraft 1.19 regarding the villager trades, which should be fixed in the 1.19.1 minecraft version. Since Fabric released their Server Launcher for 1.19.1 already. I'd like to ask you, if it is possible to update the server pack to 1.19.1?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v4

### Optifine

No

**Comment by SHXRKIIE** [comment]
Villager trades do restock in my testing ang i cant just update it to 1.19.1
