### ISSUE TITLE
Generated a chunk with an entity crashing my game, now i cant join it.

### ISSUE THREAD

**Issue by randombo1xd** [LunaPixelStudios/Better-MC#606]
### Describe the Bug

I sailed across the ocean, then i came across an Island, stepped onto it and some Entity generated making my server crash, if i join it it will crash but if no one is in the server it wont crash.

I have the Dedicated Server and client on my PC and a friend was on the Server too.

### Reproduction Steps

1. Go to a Island on the Ocean (may also happen anywhere)
2. The Entity should then spawn into the server chunk render distance
3. You will be kicked and the server will save a crash log
...

### Crash Report or Log

https://pastebin.com/CrawT47r

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v39.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Somehow a TNTMinecartEntity is causing the crash, since you say its on a server fill the block that is located at -207.50, 8.00, 562.50

**Comment by randombo1xd** [comment]
Alright, thx for the help

**Comment by randombo1xd** [comment]
I cant load the chunk with the forceload command due to that making it crash too, ill just have to make a new world
