### ISSUE TITLE
Nether Tick lag

### ISSUE THREAD

**Issue by despapito** [LunaPixelStudios/Better-MC#608]
### Describe the Bug

Hi, when i finally reached nether it's hard to play. Integrated server tick is ~50ms while in overworld is ~10ms.

I created new world in creative mode and was flying around nether for 5mins - no problems.

Is my world broken?

### Reproduction Steps

1. Walk into the nether
2. Boom
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/62870869/182391922-5337241c-6388-4c07-bb34-e5eccaefa756.png)

![image](https://user-images.githubusercontent.com/62870869/182391974-8e38101c-bf09-4e58-898a-e12022571b99.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v4

### Optifine

No

**Comment by despapito** [comment]
Update:

I created another portal somewhere else and there is no lag. Fucked up chunk ?

**Comment by SHXRKIIE** [comment]
When was your world created?

**Comment by despapito** [comment]
Idk, ~2weeks ago on v2.5. I've tried to optimize but no results. It's working for a minute and then there is 50ms latency in this location. 
There is a lot of endermans there and some piglins

Its single player.

**Comment by SHXRKIIE** [comment]
Could be an issue with updating with older worlds, see if new update coming out soon fixes it otherwise cant really help with the ticking if new worlds are fine
