### ISSUE TITLE
Lost chest contents.

### ISSUE THREAD

**Issue by JustCallMeSK** [LunaPixelStudios/Better-MC#610]
### Describe the Bug

Was using an Acacia boat with chest to transport items.
Died while near the boat, not in it. Was sent back to spawn, which should still have been in the same loaded chunks.
Teleported back to death location, chest was empty.
Breaking the boat with chest did not drop items either.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v4

### Optifine

No

**Comment by SHXRKIIE** [comment]
Could not reproduce this myself and the items were still in the chest
