### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Evilzorel** [LunaPixelStudios/Better-MC#611]
### Describe the Bug

Missing Chili Peppers textures, i reloaded the resource packs and downloaded a different Expanded Delight version but didn't work

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-08-02_17 42 04](https://user-images.githubusercontent.com/110498880/182479072-ec24a294-11f5-4689-9099-b4ba99f93927.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

bmc v12

### Optifine

No

**Comment by SHXRKIIE** [comment]
1.18.2 is discontinued, try a reinstall of the modpack.
