### ISSUE TITLE
Bumble Zone crashing server, causing exception ticking world

### ISSUE THREAD

**Issue by ericvasile** [LunaPixelStudios/Better-MC#612]
### Describe the Bug

One out of three members of the server will crash the server when loading a corrupted entity. Bumblezone has confirmed that this is a bug on their end and has released a patch, however the v4 needs to be updated.

### Reproduction Steps

1. Launch server
2. fly around until corrupted entity
3. watch your beautiful world be rendered useless
...

### Crash Report or Log

https://mclo.gs/5nmaHVb

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC v4

### Optifine

No

### Other Mods

just bmc v4

**Comment by SHXRKIIE** [comment]
Will be fixed in v5, need to update the mod
