### ISSUE TITLE
Server loads fine but client side, game crashes without fail

### ISSUE THREAD

**Issue by Yourboymusti** [LunaPixelStudios/Better-MC#614]
### Describe the Bug

The client opens fine, and the server opens up fine, but once my friend or I try to log into the server, we both crash. On the multiplayer page, we both get the 'failed to connect to server error', but if I use the dynamic IP, I can log in if I disable the shaders (complementary shaders). But I don't think it's a shaders issue because my friend will disable the same shaders and still crash. Once I'm into the server and re-enable shaders, it does not crash. Teleporting and loading new chunks with shaders on, I crash sometimes. With all that information, The info I'm giving you is conflicting in some ways, but that's what I've been seeing with my testing. It's kinda random. I don't know where to start identifying the issue other than the crash reports. 
This only started happening on v5. We've been playing on v4 for the past week with no client or server issues, but since the server automatically updated to v5 earlier today, the crashes started. We still could get onto the server via v4, but after restarting, we couldn't anymore. We updated client v5 on our pcs via curseforge, and that hasn't solved it either. I have the crash reports for myself and my friend to help you figure this out, please. We still haven't finished our mansion yet :(

Minecraft fabric 1.19 v5 (client + server)
Aternos server provider 
PC 1: 5600x/3070
PC 2: Razer blade 14 2021

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

PC 1: https://pastebin.com/mLQNYBwC                 PC 2: https://pastebin.com/XyU17qS9

### Operating System

windows 10 

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19 & 1.18.2

### Optifine

No

### Other Mods

[Clear+Glass+Pack+1.19.zip](https://github.com/LunaPixelStudios/Better-MC/files/9256425/Clear%2BGlass%2BPack%2B1.19.zip)

**Comment by SHXRKIIE** [comment]
Aternos server issues is not really my problem. I'd say revert back to v4 but since your on aternos you cant even do that. Also remove the mods you added. This crash seems to be your old world isnt compatible with the new update

**Comment by Yourboymusti** [comment]
I don't think it server related. I think it's the client. The server works fine and is always running, if it was the server, then it should crash, and I would know on the website. But it's always up. Sometimes I can log in, and other times the 'client' crashes when trying to get into the server. Please look at the recording I attached.
[Minecraft 2022.08.04 - 16.34.53.12_Trim.zip](https://github.com/LunaPixelStudios/Better-MC/files/9261097/Minecraft.2022.08.04.-.16.34.53.12_Trim.zip)

**Comment by Yourboymusti** [comment]
PC 1: https://pastebin.com/mLQNYBwC

PC 2: https://pastebin.com/XyU17qS9
