### ISSUE TITLE
Not allowing teleportation from BBZ (-4Y location)

### ISSUE THREAD

**Issue by carefulpear21** [LunaPixelStudios/Better-MC#615]
### Describe the Bug

When mining down to -4 to exit the zone I am stuck at -4 Y location which is leaving me suspended at this level with text stating aborting teleportation and retrying. 

### Reproduction Steps

1. exit and reloaded the game 

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V6.1.5+1.19.1

### Optifine

No

### Other Mods

I am using the Better Minecraft Fabric v.5 (Most up to date so far)

**Comment by SHXRKIIE** [comment]
your modpack version "V6.1.5+1.19.1" makes no sense and have no idea what your asking

**Comment by carefulpear21** [comment]
Basically, as I am leaving the bumblebee zone (BBZ) you can leave by going
lower than Y axis 0. But I'm currently stuck at -4Y axis and it's stating I
cannot leave because it will not load the function of the mod that will
take me out of the zone and back into the main map.

Maybe I have it wrong on the information modpack version but what I put was
the modpack version of the bumblee bee zone which is version 6.1.5 +
Minecraft version 1.19.1 which it gave me on the modlist. Otherwise if what
you require is the modpack of BM Fabric then it's V5 which is the latest
and most updated and you have put you have fixed the crash of the BBZ but
it is crashing in a sense when I want to leave.

The zone ends at Y acid 0 but I am suspended in -4 without anyway if
leaving or moving.

Does this make sense?

**Comment by SHXRKIIE** [comment]
Tested it and I have no problem leaving the bumblezone. Best is to either cheat a Waystone or die if you cant leave.
