### ISSUE TITLE
Glitched Dragon Mounts

### ISSUE THREAD

**Issue by CryoMaelstrom** [LunaPixelStudios/Better-MC#616]
### Describe the Bug

After updating to BetterMC Forge 1.18 V15, all the Dragon Mounts appear to be glitched. You can hatch/summon new ones, but after a while, they turn to a Fire Dragon and become uncontrollable (you can mount but you can't control). Currently unsure if this applies to all pets, had a member of the server report that her Shibas act the same way.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BetterMC Forge 1.18 V15

### Optifine

No

### Other Mods

None

**Comment by SHXRKIIE** [comment]
Update the Mod
