### ISSUE TITLE
Server frezze upon entering the Lost Cities

### ISSUE THREAD

**Issue by Dragonblood2015** [LunaPixelStudios/Better-MC#617]
### Describe the Bug

As far as I can tell if the server tries to pace a CrystalSpike from the mod Galosphere in the Lost Cities and then the server freezes.

### Reproduction Steps

1. Enter the Lost Cities Dimension (Tested directly at spawn at the seed -8523549680435906590 in single player and on a server)
2. Freeze 

### Crash Report or Log

https://pastebin.com/c0FMiJHb , https://pastebin.com/CAScYBfb

### Operating System

WIndows 10, Debian 10.2.1-6

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft Plus [1.18.2] v13

### Optifine

No

**Comment by SHXRKIIE** [comment]
Yeah see if their are mod updates if not remove either one of the mods
