### ISSUE TITLE
disenchant problem

### ISSUE THREAD

**Issue by lonybone** [LunaPixelStudios/Better-MC#618]
### Describe the Bug

When trying to disenchant a tool it is not possible to put a book in the grindstone. Because of that you can't put the enchantments of the tool on the book.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
It is removed not an issue
