### ISSUE TITLE
Game crashing while playing (render issue)

### ISSUE THREAD

**Issue by xhek** [LunaPixelStudios/Better-MC#619]
### Describe the Bug

Sup, so yeah the game is just crashing when playing, seems like it has to do with some render issue and light allocation

Minecraft 1.18.2
Java 8.0.3410.10
Java 16.0.2.0

Modpack was not modified, only using shaders

### Reproduction Steps

1. Play the game
2.
3.
...

### Crash Report or Log

https://pastebin.com/f7fT0jik

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v13

### Optifine

No

### Other Mods

no, just shaders

**Comment by SHXRKIIE** [comment]
Could you try updating to latest version?
