### ISSUE TITLE
Exit Code -1

### ISSUE THREAD

**Issue by DJalonsi** [LunaPixelStudios/Better-MC#621]
### Describe the Bug

Hi! I've been really, really wanting to play Better Minecraft with Origins, specifically Origins and Mo's Grounded Origins, so I tried to add them for personal use. However, the error that came across was 
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
Exit Code: -1

Would you happen to know what this error means and how to fix it? I know it's not part of the original modpack, but if you could help out that's be amazing! I really love your guys' modpack!

### Reproduction Steps

1. Download compatible version of Mo's Grounded Origins to Better MC 1.18.2 through curseforge sight
2. Run Modpack through curseforge
3. Error java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
Exit Code: -1 pops up
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/41878722/183497047-d086c64b-e8c3-4597-baf0-871f7ce849f4.png)

### Crash Report or Log

https://pastebin.com/ZzALpUVM

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

V12

### Optifine

No

### Other Mods

Origins
Mo's Grounded Origins

**Comment by SHXRKIIE** [comment]
Remove the mods you added
