### ISSUE TITLE
Could not find or load main class @user_jvm_args.txt

### ISSUE THREAD

**Issue by Caseyxx** [LunaPixelStudios/Better-MC#622]
### Describe the Bug

this issue is happening when i try to launch the server pack supplied via the curseforge app, my java & game versions seem to be the same as what the server pack is trying to read.

whenever i try to start this happen is what happens

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/110855743/183507719-7fc47c8f-2b1f-4cb5-a2ca-b8f25cc746cf.png)

### Crash Report or Log

no crash log available

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

15

### Optifine

No

**Comment by SHXRKIIE** [comment]
Need Java 18

**Comment by Caseyxx** [comment]
oh ok, thank you very much!
