### ISSUE TITLE
Additional Banners Crashes Game

### ISSUE THREAD

**Issue by ScroungerHS** [LunaPixelStudios/Better-MC#623]
### Describe the Bug

I put the blank banners into the loom, I put the dyes into the loom, I attempt to put the additional banners banner pattern into the loom, the game freezes, then crashes.  I tried it with several of the banner patters, including sword and shield, and tried it with varying amounts of banners and dyes.  Crashes the game every single time, without fail.

Note, if you crash the game yourself(windows error reporting exit), without letting the game crash on its own, you will lose all items you were attempting this with.

### Reproduction Steps

1.  Insert blank banner into loom
2.  Insert chosen dye into loom
3.  Insert additional banners banner pattern into loom
4.  Crash

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v12

### Optifine

No

### Other Mods

I added HT tree chop.  I removed entity culling.

**Comment by SHXRKIIE** [comment]
Update to latest version
