### ISSUE TITLE
Game crashed when I open the map

### ISSUE THREAD

**Issue by t4kizzz** [LunaPixelStudios/Better-MC#625]
### Describe the Bug

When I open the ingame map, the game crashes 

### Reproduction Steps

1. Open Better Minecraft
2. Get into a server/world
3. Open the map

### Crash Report or Log

https://gist.github.com/t4kizzz/ee0434d38e4de21d1fb5e9f67851bded

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57

### Optifine

No

### Other Mods

Simple voice chat 1.16.5 2.2.52

**Comment by SHXRKIIE** [comment]
Are you using a brand new world or an older world from before?
