### ISSUE TITLE
Game crashes after attempting to enter a world - with fix

### ISSUE THREAD

**Issue by displm** [LunaPixelStudios/Better-MC#626]
if minecraft is having a hard time with terrain generation (at least I think it's terrain generation)

`Failed to load datapacks, can't proceed with server load java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/noise_settings / the_bumblezone:bz_noise_settings]' from registry Registry[ResourceKey[minecraft:root / minecraft:worldgen/noise_settings] (Stable)]`

it'll give this error and the way to get rid of it and go back to playing is odd but simple

go in your better mc path - on mac os this will be /Users/<username>/Documents/curseforge/minecraft/Instances/Better MC [FABRIC] - 1.19 & 1.18.2

find the saves directory and copy every world somewhere else, like the desktop since it's already there

start up minecraft like you would otherwise and then go into the singleplayer menu, go back to the main screen and add the world back to the "saves" directory, then go back to the singleplayer menu and your world should show up

upon joining the world everything should be fine

I'll record a video if I have time and is asked for - and I guess unless needed this issue can be closed

1.19 not 1.18

mac os

modloader is fabric-0.14.8

looks like I missed some steps but I have no idea how to get to them and I need to log off

**Comment by SHXRKIIE** [comment]
Datapacks loading fails does only occur when you mess with the modpack and in any way. This i can only assume you updated the modpack and your old world was not compatible
