### ISSUE TITLE
Boat with Chest Inventory Disappears After Traveling Far away with a waystation.

### ISSUE THREAD

**Issue by BeddyH** [LunaPixelStudios/Better-MC#627]
### Describe the Bug

Boat with Chest Inventory Disappears After Traveling with a way station.

### Reproduction Steps

1. Launch the title.
2. Create a world.
3. Gather resources to make 2 waystones and a boat with a chest.
4. Place down a waystone. 
5. Travel several hundred blocks away.
6. Place the second waystone.
7. Place the boat with a chest in water.
8. Place any item in the boat with a chest.
9. Travel back to the original waystone with from the second waystone.
10. Travel back to the second waystone via the original waystone.
11. Open the boat with a chest.
12. Observe lack of item.

### Screenshots and Videos

https://user-images.githubusercontent.com/111009659/183990152-105958b4-9f5b-49ae-9b70-75c4e1a48ae5.mp4

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] - 1.19

### Optifine

No

**Comment by xSHXRKIEx** [comment]
I wont be able to fix this
