### ISSUE TITLE
Issues with Controllable

### ISSUE THREAD

**Issue by adzam016** [LunaPixelStudios/Better-MC#628]
### Describe the Bug

Hi guys,

This modpack is awesome, and I wanted to start by saying thank you!

I am using Controllable 1.18.2 on Better MC 1.18.2. Everything is working perfectly except one tiny thing!

For some reason, I cannot use my DPAD to navigate the crafting menu like I normally would.

Is there a mod installed that might conflict with Controllable in some way causing this strange behaviour?

I have not added any mods to Better MC besides Controllable.

Thanks,

Adzam

### Reproduction Steps

1. Install Controllable 1.18.2 into Better MC 1.18.2 V5 
2. Try navigating the crafting menu with a controller
3.
...

### Operating System

Mac OS Monterey 12.5 (same issue on my friend's Win11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2 V5

### Optifine

No

### Other Mods

Controllable 1.18.2

**Comment by SHXRKIIE** [comment]
I don't know what could be conflicting it and your better off checking the Controllable Github or Discord and asking.

**Comment by hikinata** [comment]
Hey, for me controllable may that i can't launch minecraft better plus , what are you did for that work [adzam016]?
