### ISSUE TITLE
my server crashing

### ISSUE THREAD

**Issue by SalmanDX** [LunaPixelStudios/Better-MC#630]
### Describe the Bug

my server is shutdown and i don't know what is problem 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://anotepad.com/notes/x6nekqfi

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Remove encahnt with mob mod

**Comment by SalmanDX** [comment]
how can spawn The Wither?

photo for the wither bulid
[https://f.top4top.io/p_24151nbfl1.png](url)
