### ISSUE TITLE
Golemsteel brazier don't work (villager artifacts) 

### ISSUE THREAD

**Issue by MiniRaptor** [LunaPixelStudios/Better-MC#631]
### Describe the Bug

there is an item in the Villager Tools a.k.a Villager Artifacts mod that, according to the idea, should make the villagers follow you, but it does not work

### Reproduction Steps

1. hold golemsteel brazier in hand
2. villagers don't follow you
3. cover yourself in oil and die
...

### Crash Report or Log

none

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

No

### Other Mods

Ore excavation, casino craft.

**Comment by SHXRKIIE** [comment]
use Emeral/emerald blocks instead

**Comment by MiniRaptor** [comment]
ok, thx
