### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by MinePlay478** [LunaPixelStudios/Better-MC#632]
### Describe the Bug

game crash after i use the quest book or if i use the ftb chunks map. 

### Reproduction Steps

1.enter BetterMinecraf 1.16.5
2.join any world or server
3.press right click on the quest book or press on the key that active the ftb chunks map
4. you made your game crash :D

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/111091003/184243533-70e1abaa-b6a4-4eb3-91db-0d4ac9f439a8.png)

that what i see when i try to use the quest book in the inventory menu

### Crash Report or Log

https://mclo.gs/rCFbEMb

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
What launcher are you using? When you say join any server do you mean you this happened on multiple servers?

**Comment by MinePlay478** [comment]
im using Curse Forge. it seems that the problem fixed itself, but yes. when it happened no matter on what server or single player world i was in. if i open the quest book or the ftb chunks the game would crash immediately with the same crash log every time. but its look like it got fixed somehow..

**Comment by SHXRKIIE** [comment]
if it happesn next tiem try to reinstall
