### ISSUE TITLE
Mod is not working, I have it in my mods file.

### ISSUE THREAD

**Issue by DragonsRule2000** [LunaPixelStudios/Better-MC#633]
### Describe the Bug

After I put the mod in my mods file, C:\Users\####\AppData\Roaming\.minecraft\mods, I started up Forge on 1.18.2 (40.1.68) and it did not show up in forge. I have restarted the game, extracted the file, redownloaded the file, and it still will not get recognized by Forge. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18 & 1.19

### Modloader

Forge & Fabic

### Modpack Version

v15 + v5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Use a launcher
