### ISSUE TITLE
cant split or drop items from the inventory

### ISSUE THREAD

**Issue by SkullGamer2009** [LunaPixelStudios/Better-MC#634]
### Describe the Bug

cant drop any items or split items into other stacks in my inventory

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

**Comment by SHXRKIIE** [comment]
I have no ussie doing this myself, did you add any mods? Cna you show a video?
