### ISSUE TITLE
extreme game bug

### ISSUE THREAD

**Issue by scythgamer666** [LunaPixelStudios/Better-MC#636]
### Describe the Bug

when i entered my world time was frozen villagers wont move nothing will die and once i activate my elytra it stays in flight mode scooting across the floor. and i am limited to only a 2 by 2 chunk area nothing else will load i cant drop items i cant remove elytra i cant use rockets i cant shoot my bow its just totally broken

### Reproduction Steps

1.
2.
3.
...
i have no idea

### Operating System

window 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v56

### Optifine

No

**Comment by scythgamer666** [comment]
its actually version 1.16.5

**Comment by SHXRKIIE** [comment]
seems like a hardware issue or a world issue. You say when you entered your world, when was the last time you entered your world?

**Comment by scythgamer666** [comment]
well when it originally happend it was around a week ago, but it still lets me join and move around only
