### ISSUE TITLE
help With sings

### ISSUE THREAD

**Issue by ZanderGileYT** [LunaPixelStudios/Better-MC#637]
### Describe the Bug

I want to know what mods let me edit signs i want to remove them they interfere with my new server.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better Minecraft - 1.19

### Optifine

I used Optifine

**Comment by xSHXRKIEx** [comment]
Charm i think but you can aks this on discord on Github
