### ISSUE TITLE
FTB Chunks and Waystones

### ISSUE THREAD

**Issue by BeyondHawkeye** [LunaPixelStudios/Better-MC#638]
So when people try to use a waystone that is in a claimed chunk they can't. Is there any way to change this so people can go into a claimed area and explore and be able to leave without having to find another nearby waystone outside of the claimed chunk? They can teleport to it in the first place but can't interact with it to go back to wherever they came from.

**Comment by xSHXRKIEx** [comment]
Add them to the claimed chunks or unlcaim it

**Comment by BeyondHawkeye** [comment]
I figured that out for those two options, but I meant is there anyway that I can change it to allow anyone to access waystones and use them inside of the claimed chunks without being added to the team that claims them?
