### ISSUE TITLE
code 6 when opening world

### ISSUE THREAD

**Issue by bevv10** [LunaPixelStudios/Better-MC#640]
### Describe the Bug

just download curseforge and tried to start a world but got exit code 6. I am on mac if that helps :/

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

# # A fatal error has been detected by the Java Runtime Environment: # #  SIGSEGV (0xb) at pc=0x00007ffa19aaa656, pid=60466, tid=259 # # JRE version: Java(TM) SE Runtime Environment (8.0_74-b02) (build 1.8.0_74-b02) # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.74-b02 mixed mode bsd-amd64 compressed oops) # Problematic frame: # C  [libGLProgrammability.dylib+0xa4656]  glpLLVMGetFunctionGlobalVariableUse+0x5c # # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again # # If you would like to submit a bug report, please visit: #   http://bugreport.java.com/bugreport/crash.jsp # The crash happened outside the Java Virtual Machine in native code. # See problematic frame for where to report the bug.

### Operating System

MacOS monterey 12.4

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v57.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
This is a graphics driver issue, try ATLauncher or GDLauncher isntead
