### ISSUE TITLE
the wither not spawn

### ISSUE THREAD

**Issue by SalmanDX** [LunaPixelStudios/Better-MC#641]
### Describe the Bug

how can spawn The Wither?

photo for the wither bulid
[https://f.top4top.io/p_24151nbfl1.png](https://github.com/LunaPixelStudios/Better-MC/issues/url)

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Use Soul Stone from Bygone Nether
