### ISSUE TITLE
Cannot move after exiting a boat

### ISSUE THREAD

**Issue by emrchann** [LunaPixelStudios/Better-MC#642]
### Describe the Bug

I was traveling new area via boat. Going down a river, I wanted to exit my boat to approach the cliffside. I was able to exit the boat but my character could not move around. I was stuck in one place- on top of the boat. I could still jump, spin my head around (sometimes), mine things in my proximity, and pretty much everything else except move around. I have tried resetting my server, game, and computer, killing myself, having a player kill me, trying to enter and exit the boat- nothing changed. I finally managed to pull out a waystone, and travel home but even being in a different, familiar part of the map, I was still experiencing the same movement issue. Eventually I found that when an in-game mob kills your player, it grants you back the movement.

### Reproduction Steps

1. travel down a river in a boat
2. exit the boat with the shift key
3. somehow get stuck teleporting in the water, on the boat, into the water...
4. click the boat to re-enter to stop glitching in and out of the boat
5. exit the boat and remain there stuck

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v5

### Optifine

No

### Other Mods

none

**Comment by emrchann** [comment]
I meant to add that the movement issue also sometimes gets triggered by pausing the game and exiting the tab without closing it out completely.

**Comment by xSHXRKIEx** [comment]
I am unable to reprdouce this issue can you please show me a video?
