### ISSUE TITLE
cant go into creative 

### ISSUE THREAD

**Issue by Tempest-sily** [LunaPixelStudios/Better-MC#643]
### Describe the Bug

I cant go into creative when I type /gamemode creative. i have cheats enabled through REI. and I've been trying to figure it out but nothing works 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-08-14_23 55 54](https://user-images.githubusercontent.com/111263792/184576382-cfd1bd32-88f5-4a3b-8dc9-8e7e9bdcef7c.png)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v5 1.19 

### Optifine

No

**Comment by xSHXRKIEx** [comment]
You need to have cheats enabled -_-
