### ISSUE TITLE
Having torch in hand cause lag

### ISSUE THREAD

**Issue by kirosaki18** [LunaPixelStudios/Better-MC#645]
### Describe the Bug

When i put the torch in hand and start moving lags so much and when i switch to something else the lag is gone,
It only happens when you have the torch in hand

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/111284749/184631374-9574500f-7ea3-4d8a-aff6-f070eb81688f.mp4

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Change the dynamic lights settings to very fast
