### ISSUE TITLE
Cobble is A missing texture

### ISSUE THREAD

**Issue by DrRoy666** [LunaPixelStudios/Better-MC#646]
### Describe the Bug

Whe iloaded up the 1.18 - 1.19 better minecraft i realized that the cobble texture is missing and has the purple and black missing texture

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Press F3 + T
