### ISSUE TITLE
Water ripple effect doesn't shows properly

### ISSUE THREAD

**Issue by QuestionMark210** [LunaPixelStudios/Better-MC#647]
### Describe the Bug

For some reason the water ripple effect from Dynamic Surroundings can only be seen from a specific angle of a camera.

### Reproduction Steps

On the screenshots, i looking at the small pond, but when i'm moving my camera slightly to the left the water ripple effect from the rain disappear. 

### Screenshots and Videos

![Jre-legacy Screenshot 2022 08 16 - 14 35 39 15](https://user-images.githubusercontent.com/91344589/184870131-272325ab-2f44-433c-bfd5-03768bb83035.png)
![Jre-legacy Screenshot 2022 08 16 - 14 35 44 75](https://user-images.githubusercontent.com/91344589/184870133-9002516a-b8d0-4e03-9eac-4379d7ae71d4.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v57.5 (Forge)

### Optifine

No

### Other Mods

Spartan Weaponry, MmmMmmMmm (Target Dummy mod), Yung's better caves, Sit, Dungeon Crawl and Scuba Gear.

**Comment by xSHXRKIEx** [comment]
I believe its an issue between Rubidium and Dynamic Surroundings. Ill see if I can report this to them
