### ISSUE TITLE
Picking up villagers crashes the game

### ISSUE THREAD

**Issue by FiireWiinter** [LunaPixelStudios/Better-MC#648]
### Describe the Bug

Picking up a villager with a profession and trying to go into F5, will crash _**EVERYONE**_ on a server.

### Reproduction Steps

1. Pick up a villager with a profession 
2. Press F5
3. Observe

### Screenshots and Videos

https://www.youtube.com/watch?v=a9fkW0tfKUg

### Crash Report or Log

https://pastebin.com/G7h63thb

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

**Comment by FiireWiinter** [comment]
Note: I'm using MultiMC with the modpack freshly downloaded from CurseForge, the exact same Forge version, and the entire CurseForge installation being copied straight to the MultiMC Instance. The CurseForge Instance and the MultiMC Instance are 1:1

**Comment by xSHXRKIEx** [comment]
The reason it is crashing is because you are not suppose to be able to pick up full grown villagers but it seems I missed that. Fix is either to blacklsit them from being picked up or removing Merchant Markers (That Logo on their head) Mod.
