### ISSUE TITLE
Opening through the curseforge launcher doesnt work

### ISSUE THREAD

**Issue by nyxtropical** [LunaPixelStudios/Better-MC#649]
### Describe the Bug

When i opened through the curseforge launcher it would load the pack then start opening and closing the minecraft updater. When i manually put the mods into my minecraft mods folder and booted through the 1.18.2 forge in the minecraft launcher it crashed and came back with this code 

76490599

i just wanna play a server with my friends and im the only one having this problem

### Reproduction Steps

1. 
2.
3.
...
i dont know all i did was download the pack into my curse forge launcher and press play

### Screenshots and Videos

https://user-images.githubusercontent.com/111398909/185005516-cab4ecd4-dc13-4b20-83d1-4e886c258de9.mp4

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC forge v15

### Optifine

No

**Comment by xSHXRKIEx** [comment]
No idea why that is happening, I suggest trying another Launcher. GDLauncher or ATLuancher
