### ISSUE TITLE
Invisible blocks - Create - Better MC PLUS [1.18.2]

### ISSUE THREAD

**Issue by JackyCheckmark** [LunaPixelStudios/Better-MC#651]
### Describe the Bug

We have only experienced this using create contraptions.

When making contraptions with Create, if any non-vanilla blocks are used, they and other blocks will be invisible once the contraption becomes a solid block.
Blocks remain as ghostblocks with half collission, but can reappear by holding down rightclick on a surface that's touching the block. The exact same blocks are invisible for all clients, as it's on a server.

It's a server instance of the modpack, running through a Docker container. Clients connect using CurseForge.

We have attempted to remove oculus and Rubidium, but this didn't solve the issue. The same with trying diverse rendering settings.

### Reproduction Steps

1. Use a Create windmill bearing
2. Place a modded block, like Fir Planks on it
3. Attatch sails so it can become a contraption by right clicking the bearing
4. Right click the bearing and the blocks will, seemingly randomly, turn invisible
5. Using a vanilla block, like cobblestone, instead of fir planks, circumvents this issue.

### Screenshots and Videos

![javaw_0m5kvbizVp](https://user-images.githubusercontent.com/111564820/185576703-c92565a9-88f7-4a2b-93d2-a2eea8900045.png)

![image](https://user-images.githubusercontent.com/111564820/185576803-05681bab-5b97-4c04-8f11-e1e301dc81eb.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v13

### Optifine

No

### Other Mods

We have added the following mods:
SecurityCraft
Simple Voicechat
Sound Physics Remastered
Mob Grinding Utils

**Comment by xSHXRKIEx** [comment]
Can you see if possibly updating flywheel and create fixes it? an ddo you have radon in the mods folder>?

**Comment by JackyCheckmark** [comment]
We're using the newest public version of create v0.5.0d. 
Tried to update to Flywheel version 0.6.5, but it seems to be unstable, crashing clients on launch, so we reverted to flywheel v. 0.6.4, unable to test.
Radon is not currently being used on server or clients

**Comment by xSHXRKIEx** [comment]
Im not sure when ill be able to test this or if I will even be able to find a solution

**Comment by JackyCheckmark** [comment]
We've done some more testing, it seems to be purely on the server-side, if it's done in singleplayer or host to LAN, there's no issues. Extra mods/shaders does not seem to be the cause, as we have also tested it in the newest version of Better MC plus without modifications on a fresh world.

**Comment by chorbintime** [comment]
This version will be receiving an update soon. You can ping me in discord after this update releases and tell me if this still happens.
