### ISSUE TITLE
Can't wear Ender Backpack

### ISSUE THREAD

**Issue by Assenzio52** [LunaPixelStudios/Better-MC#652]
### Describe the Bug

Ender Backpack can't be equipped, neither in chest or backpack slot

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.16.5 v57.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
They cant be worn
