### ISSUE TITLE
invalid player data upon rising blood moon.

### ISSUE THREAD

**Issue by cazred** [LunaPixelStudios/Better-MC#654]
### Describe the Bug

Was playing for a few hours at this point, already had a few blood moons, but i was bring my dogs indoors and sitting them and it crashed, now whenever i try to relaunch i get invalid player data.

### Reproduction Steps

1. blood moon rising.
2. sit dogs down. 
3. i'm not sure what more.
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

### Other Mods

no.

**Comment by xSHXRKIEx** [comment]
need the log
