### ISSUE TITLE
Permanently bugged with slowness  

### ISSUE THREAD

**Issue by Y3NOX** [LunaPixelStudios/Better-MC#655]
### Describe the Bug

After using a Mob Enchant book, I died in the nether. The Book gave me speed II or III and when i respawned, my FOV is closer and my character now moves VERY slowly. there is no active status effect i can see but you can tell its not the base speed. I tried to use commands to fix it but idk where to start

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Bmc V15.Zip

### Optifine

I used Optifine

### Other Mods

Tinkers Construct, Most of the Macaws better Furniture, and travellers backpack

**Comment by xSHXRKIEx** [comment]
Did you try and relog?
