### ISSUE TITLE
display bug Better Minecraft FORGE 1.16.5

### ISSUE THREAD

**Issue by Survivia** [LunaPixelStudios/Better-MC#656]
### Describe the Bug

It's a display bug that doesn't display all chunks. It also doesn't display Minecraft water and vegetation. Reloading chunks or resource packs does not work. I also tried to increase or decrease the view distance but that doesn't work either.

### Reproduction Steps

1. Open the game
2. Create a new world
3. Look

### Screenshots and Videos

![2022-08-21_12 36 40](https://user-images.githubusercontent.com/111683586/185787522-c2b4a99f-e74d-4153-8af2-450e97b12f0f.png)

### Operating System

Windows 7

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v57.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
This is an issue with your PC not the Modpack. Your on windows 7 so I can only assume you have old hardware. Try removing Rubnidium and Oculus mod other than that I cant help further
