### ISSUE TITLE
Wither Not Spawning Better MC 1.16.5

### ISSUE THREAD

**Issue by Fanschmidt** [LunaPixelStudios/Better-MC#658]
### Describe the Bug

Completed most of the quests on the nether, but when i try to spawn the Wither, nothing happens, already checked for grass or other things next to the soul sand/soil and still wasn`t able to spawn it ( srry for any grammar error, english is my third language )

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-08-21_15 40 09](https://user-images.githubusercontent.com/111703751/185806049-b621b439-f159-494e-86a2-9c81674f55c0.png)
![2022-08-21_15 39 20](https://user-images.githubusercontent.com/111703751/185806050-66cffde4-c66e-4063-9914-8cbeb5ad6bfd.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V57.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
You need to use Soul Stone blocks from Bygone Nether

**Comment by Fanschmidt** [comment]
so no soil nor sand, Stone
okay, gotcha, thanks

**Comment by Fanschmidt** [comment]
Thank you so much...
