### ISSUE TITLE
Fabric 1.19.2 Can't Server OP

### ISSUE THREAD

**Issue by AzureDoom** [LunaPixelStudios/Better-MC#659]
### Describe the Bug

Unable to OP players on servers.

### Reproduction Steps

1. Start server
2. Try to op player. EX: `/op AzureDoom`
3. Get `An unexpected error occurred trying to execute that command`
...

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC Fabric 1HF

### Optifine

No

### Other Mods

No extra mods.

**Comment by xSHXRKIEx** [comment]
it is just op not /op

**Comment by AzureDoom** [comment]
> it is just op not /op

/op is ingame yes, but I made sure to test with `op AzureDoom` as well, I have confirmed this issue on our testing servers as well as well as a local server.
