### ISSUE TITLE
Can't use End Stone Smelter

### ISSUE THREAD

**Issue by TLiG98** [LunaPixelStudios/Better-MC#661]
### Describe the Bug

Trying to open the End Stone Smelter, but when i right click it, the server crashes.

### Reproduction Steps

Place a END STONE SMELTER.
RIGHT CLICK the end stone smelter.
Crash happens.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/26041401/185811190-100c7542-77df-449e-bd91-a671cb888484.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v4

### Optifine

No

### Other Mods

weaponmaster-multi-fabric-1-19.jar

**Comment by xSHXRKIEx** [comment]
Update to v5
