### ISSUE TITLE
Serverpack Not Launching

### ISSUE THREAD

**Issue by VincentViscusi** [LunaPixelStudios/Better-MC#662]
### Describe the Bug

After running the powershell file for the serverpack it has this message (See attached)

### Reproduction Steps

1.Download serverpack
2.Extract from zip
3. Run with powershell
...

### Screenshots and Videos

![BetterMC FABRIC 1 19 2](https://user-images.githubusercontent.com/79776035/185812910-8b14e020-dfa5-488c-b42e-5b5ab0bb46b8.png)

### Crash Report or Log

Uncaught exception in thread "main" java.lang.RuntimeException: An exception occurred when launching the server! 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) Caused by: java.lang.RuntimeException: Error invoking MC server bundler: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0 	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:102) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:190) 	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:177) 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) 	... 1 more Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0 	at java.lang.ClassLoader.defineClass1(Native Method) 	at java.lang.ClassLoader.defineClass(Unknown Source) 	at java.lang.ClassLoader.defineClass(Unknown Source) 	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor$1.loadClass(BundlerProcessor.java:65) 	at java.lang.ClassLoader.loadClass(Unknown Source) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Unknown Source) 	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:85) 	... 7 more

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC v1

### Optifine

No

**Comment by xSHXRKIEx** [comment]
You need Java 17 to run it
