### ISSUE TITLE
I set up a server and have a client-side bug that prevents me from logging on.

### ISSUE THREAD

**Issue by jruicker** [LunaPixelStudios/Better-MC#663]
### Describe the Bug

I keep getting an error

Connection Lost
Internal Exception io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException:
readerIndex(26955) + length(4) exceeds writerIndex(26955):PooledUnsafeDirectByteBuf(ridx: 26955,
cap: 26955)

I believe it is client side because the server log just indicates I joined then I disconnected. 

Server is on Bisect Hosting Fabric 1.19.2 I downloaded the server files from Curseforge, 

### Reproduction Steps

1.Multiplayer
2.Join Server
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

No

### Other Mods

Medieval Minecraft.

**Comment by xSHXRKIEx** [comment]
I need a log of the server and client. and what do you mean by other mods Medieval Minecraft?

**Comment by zkronix** [comment]
i have the same problem but no other mods, the thing is i want to play the v5 of Better MC of the 1.19 minecraft on on a server yet the server has the 0.14.9 modloader and the Better MC v5 (1.19 MC) has the 0.14.8

**Comment by jruicker** [comment]
This is not completed. I still have the same problem. I reinstalled the modpack on the server and on the client. Same problem.

**Comment by jruicker** [comment]
This isn't fixed. I reinstalled with the newest version on both server and
client and still have the same issue.

Let me know how to do this if I am doing something wrong.

**Comment by jruicker** [comment]
I have included all the logs that I thought might be useful to you. I don't
know how to open the .gz ones. I assume you know how. I have no additional
mods added. I put down the Medieval Minecraft because I was trying to fill
in the blanks. That is the name of the modpack that I am trying to play on.
I have been playing as a solo player, and I really enjoy it but I can't
play as a multiplayer.

Thank you
John

**Comment by ANiceHippo** [comment]
The same issue with the exact error code happens on Medieval MC[FABRIC] - MMC1 v14.5

**Comment by RustyBobJoe** [comment]
Hope to see this reopened, I'm having the same issue and have been unable to find a fix. 
Running Medieval MC [FABRIC] 1.19.2
