### ISSUE TITLE
Can not move items freely in inventory-

### ISSUE THREAD

**Issue by Rayychel** [LunaPixelStudios/Better-MC#664]
### Describe the Bug

When I click an item to move in my inventory it only moves between the hotbar and my inventory, in other words I can not choose where to put items it just snaps into my hotbar or the next available spot in my inventory. In addition to this, out of no where I can no longer right click on items in the JEI menu to see recipes. I have not touched key binds so I am unsure what has created this issue. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

40.1.68

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Go into a chest and unclick the shift lock button
