### ISSUE TITLE
Mod pack not loading into my minecraft

### ISSUE THREAD

**Issue by Shadowboi96** [LunaPixelStudios/Better-MC#667]
I downloaded the mod pack with the hopes of playing the game with the mods and when I downloaded the mod pack and extracted it to the mod folder for my minecraft game it doesn't load the mods into my mod pack. Is there a specific way you need to install each mod?
![unknown (3)](https://user-images.githubusercontent.com/111997715/186453558-fa101d2a-dd50-4c79-828c-8601f66dd64b.png)

**Comment by xSHXRKIEx** [comment]
nope you need to use a launcher.

**Comment by Shadowboi96** [comment]
> nope you need to use a launcher.

I don't suppose you know which launcher it is I gotta use, it's my first time modding Minecraft
