### ISSUE TITLE
Can't Control Dragons After Player Dies (Dragon Mounts: Legacy mod)

### ISSUE THREAD

**Issue by vee202** [LunaPixelStudios/Better-MC#668]
### Describe the Bug

After fully taming a dragon and putting a sadle on them if you end up dying in survival (server) you won't be able to control the dragon. i could still mount them and feed them but wasn't able to move around or fly while on the dragon. Mines was a fire dragon, i haven't tested with any other types of dragons. Also couldn't command them to sit or stay.

I also tried feeding them fish again after i died and still didn't work.

### Reproduction Steps

1.Tame Dragon Fully
2.Put Saddle on Dragon
3. Fly around
4. Die
5. Then Try to Control Dragon
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.18.2 v15

### Optifine

I used Optifine

### Other Mods

i did not add any other mods but optifine but i did remove Serene Seasons

**Comment by xSHXRKIEx** [comment]
How did you die while on the dragon? I can only assume that bugged it.
