### ISSUE TITLE
the shift stays maintained and does not work

### ISSUE THREAD

**Issue by sabioviejoven** [LunaPixelStudios/Better-MC#669]
### Describe the Bug

in the inventory and in the chests when I right click on it instead of dragging it, it puts it directly into the chest and when crafting I crafted the stack at once without me pressing shift. I have already tried restarting to change mouse options and of the keys but it does not work

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better minecraft 1.18

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Open a chest and unclick shift lock
