### ISSUE TITLE
glitched textures on mobs

### ISSUE THREAD

**Issue by icedcaveVF** [LunaPixelStudios/Better-MC#673]
### Describe the Bug

mobs with what seems to be darker textures are glitched and show up as almost completly black

### Reproduction Steps

1. just spawn certain mobs
ex: crystal golem, abylager, ember jack

### Screenshots and Videos

![2022-08-24_17 42 08](https://user-images.githubusercontent.com/112032659/186536300-fed0f242-35ec-4299-a95f-32d6c7db3f53.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.2

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Yes this is due to Shader Support, if you dont want it remove Oculus
