### ISSUE TITLE
Server stops after closing the console

### ISSUE THREAD

**Issue by FrezzWolf** [LunaPixelStudios/Better-MC#674]
### Describe the Bug

I am hosting on a root server and I would like to keep the server online 24/7 even if the server consolas is closed. 
I need a start.sh with screen or something else. Please help me :(

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v58.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
You need the console open cause that is how you run the server, this is what happens when you host yourself

**Comment by FrezzWolf** [comment]
So forge dont work with screen or something elsen?

**Comment by FrezzWolf** [comment]
Got it server is online without the Server console open, but ty anyway

**Comment by Blunerz** [comment]
HOW DID YOU MAKE IT SO THE SCREEN IS CLOSED AND SERVER IS RUNNING
