### ISSUE TITLE
Random crash in singleplayer world, seems to be caused by Twilight Forest assests?

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-MC#675]
### Describe the Bug

Hey! Me again, my world randomly crashed and i have no idea what happened, i looked through the crash report and most of it seemed to have come from Twilight Forest, however i cannot read crash reports easily.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/AAQ5x7a4

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

11.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Your many versions behind please update the modpack

**Comment by FevilGitHub** [comment]
thx for letting me know, i was tired that day n wanted to put in the report asap and forgot it was v15 not 11
