### ISSUE TITLE
An useful mod is missing

### ISSUE THREAD

**Issue by RAFSAN06** [LunaPixelStudios/Better-MC#676]
### Describe the Bug

I play better mc with my friend in an aternos server. We can build easy farms together but for harder farms we want to use litematica. Unfortunately we cannot add litematica to server. It only includes that mods that officially better mc modpack contains. So it would be a great help for us if you add litematica mod into the server pack version or both client and server side. If anyone needs it, they may use and if anyone dont need they may not use.  

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v2

### Optifine

No

### Other Mods

Litematica should be added

**Comment by xSHXRKIEx** [comment]
wont add it and this isnt a place to suggest mods
