### ISSUE TITLE
"Dragon Mounts: Legacy" Mod is broken!

### ISSUE THREAD

**Issue by PickleRelic** [LunaPixelStudios/Better-MC#678]
### Describe the Bug

Noticed right away when I opened the JEI and searched @dragon it only show the Forest dragon egg and spawn egg. After a while of exploring I found 2 Aether dragon eggs in a underground camp. After I hatched them both; two fire dragons spawned. They grew up and worked fine for the first 2 minutes, then I went to the Twilight Dimension for a few blocks and when I returned the dragon was uncontrollable(I can ride it but not fly, sit, or have it follow me). Got annoyed and got off for the day and when I got back on the next it was still broken, I went to a creative world and noticed it happened every time I went out of render distance of it. I love this mod and would love for it to be fixed or have a work around.

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft V15

### Optifine

I used Optifine

**Comment by xSHXRKIEx** [comment]
Not broken, if you read its page you they only provide the egg like that for compatiblity and to get different eggs you place them in different areas, like ice or water etc

**Comment by PickleRelic** [comment]
Literally did not answer the problem, idc if there is only fire dragons, it wont let me control it at all.
