### ISSUE TITLE
"Dragon Mounts: Legacy" Mod is broken!

### ISSUE THREAD

**Issue by PickleRelic** [LunaPixelStudios/Better-MC#680]
### Describe the Bug

Noticed right away when I opened the JEI and searched @dragon it only show the Forest dragon egg and spawn egg. After a while of exploring I found 2 Aether dragon eggs in a underground camp. After I hatched them both; two fire dragons spawned. They grew up and worked fine for the first 2 minutes, then I went to the Twilight Dimension for a few blocks and when I returned the dragon was uncontrollable(I can ride it but not fly, sit, or have it follow me). Got annoyed and got off for the day and when I got back on the next it was still broken, I went to a creative world and noticed it happened every time I went out of render distance of it. I love this mod and would love for it to be fixed or have a work around.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft V15

### Optifine

I used Optifine

**Comment by xSHXRKIEx** [comment]
Sorry I think I mixed up your issue with another, is this on a server?

**Comment by xSHXRKIEx** [comment]
I tested on server and singleplayer and cant seem to recreate this issue.

**Comment by Raymark97** [comment]
my server crashes whenever i try to breed. i noticed you're using BETA_1.1.0b1 version when there is the 1.1.4 stable version of the mod which seems to have fix the error

**Comment by xSHXRKIEx** [comment]
yeah in testing im also using BETA_1.1.0b1 and I can still fly it. did the new udpdate fix the issue?>

**Comment by Raymark97** [comment]
I can try it if you want. my issue is related to breed, when i give fish to two dragons the server crashes

**Comment by PickleRelic** [comment]
Im trying the newer version rn

**Comment by Raymark97** [comment]
> Im trying the newer version rn

any news?

**Comment by hermescostell** [comment]
This is a somewhat known issue with the mod itself. https://github.com/Kay9Unit/Dragon-Mounts-Legacy/issues/68
The mod owner has marked it as fixed, unfortunately, when it's obviously NOT. For my part I'm hosting a multiplayer game and I see all dragons properly as their various breeds, while the other player only sees them all as Fire dragons.

**Comment by PickleRelic** [comment]
I tried a few different versions without altering the modpack, and nothing seems to work. I'm using apex hosting and I've used it for tons of different packs, I'm not sure what to do now.

**Comment by Raymark97** [comment]
Btw the new version seems to fix the issue with breeding

**Comment by PickleRelic** [comment]
I havent had an issue with breeding them, once their tamed they work fine until out of render distance

**Comment by Raymark97** [comment]
But i did :D
Si updating the mod at least solves that issue

**Comment by PickleRelic** [comment]
https://www.curseforge.com/minecraft/modpacks/better-mc-forge This is the version I'm using, Just found out the mega torches aren't working either

**Comment by Raymark97** [comment]
> https://www.curseforge.com/minecraft/modpacks/better-mc-forge This is the version I'm using, Just found out the mega torches aren't working either

Me too, i tried to update Dragon Mounts Legacy to 1.1.14 [download](https://www.curseforge.com/minecraft/mc-mods/dragon-mounts-legacy/files/3926737)

**Comment by PickleRelic** [comment]
I downloaded the 1.1.4  version and it fixed the different breeds of the dragons but not being able to control them after leaving render distance. Im done trying, going to ark for a while.
