### ISSUE TITLE
Better Minecraft Crashing Issue

### ISSUE THREAD

**Issue by ShaynesRibShack** [LunaPixelStudios/Better-MC#681]
### Describe the Bug

When I boot up the launcher, I get all the way to the actual world generation, but upon the world generation being complete, I cannot load into the game because it instantly  crashes and 

### Reproduction Steps

1. Launch Curse Forge 
2. Launch Better Minecraft
3. Select World
4. Load Game
5. World Generation Complete
6. Game Crash

### Screenshots and Videos

![Screenshot 2022-08-28 173640](https://user-images.githubusercontent.com/100658170/187095508-a6458cc2-70ad-437e-bc49-50c8268bbf08.png)

### Crash Report or Log

https://gist.github.com/ShaynesRibShack/466f27c11a1a8da1bc276ed00fdd0243

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v54.4

### Optifine

I used Optifine

### Other Mods

Tinkers Construct

**Comment by xSHXRKIEx** [comment]
Remove tinkers construct
