### ISSUE TITLE
Latest Version Bug

### ISSUE THREAD

**Issue by Emilio-Github** [LunaPixelStudios/Better-MC#682]
### Describe the Bug

i tried customizing my keybinds but after i was done i couldnt click items in my inventory to switch their place and when i reset keybinds it didnt work again and i dont know how to fix this issue
i use a MacBook Air that was made in 2017 and bought in 2020 and i made a random seed world with keep inv on and instant respawning with the name being My world difficulty set to hard, suvival and no extra setting adjusted

### Reproduction Steps

1. Make a world with the things i mentioned
2. get any item and try to move it 
3. thats it
4.
5.
...

### Operating System

mac book air? 

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

latest version since sunday august 28th 2022

### Optifine

No

### Other Mods

all 194 mods that minecraft says im using (but for some reason forge says it uses 196)

**Comment by xSHXRKIEx** [comment]
Reinstall the modpack

**Comment by Emilio-Github** [comment]
thanks
