### ISSUE TITLE
Connection lost, timed out

### ISSUE THREAD

**Issue by Anakinn115** [LunaPixelStudios/Better-MC#683]
### Describe the Bug

Since my server was updated to the new bmc version, after a minute of entering in to the world, it loses connection and if I try to join again detects that I am still inside the server, so until I restart I can't enter the world, I have contacted my server support and they told me that it is caused by a mod in the modpack

### Reproduction Steps

1.Join the server 
2.After a minute kicks me out
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC v16

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Need a log to see what is causing the issue

**Comment by Chrysis-jpg** [comment]
I have the same Issue,

Here is the Connection Lost Error Code on Minecraft, if you want to Join an Server:

Internal Exception: io.netty.handler.codec.DecoderException:java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndes(12): PooledUnsafeDirectBuf(ridx: 12, widx: 12, cap: 12/13)

**Comment by xSHXRKIEx** [comment]
this doesnt helpo I need a log
