### ISSUE TITLE
postmortal 2 bug

### ISSUE THREAD

**Issue by kaithegoodguy** [LunaPixelStudios/Better-MC#684]
### Describe the Bug

eat a tomato from "@farmers delight" mod and you get the postmortal 2 achievement  

### Reproduction Steps

1.eat a tomato
2.get the achievement 
3.
...

### Crash Report or Log

no crash report

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

### Other Mods

nope

**Comment by xSHXRKIEx** [comment]
Doesnt seem to occur in v16 so its fixed
