### ISSUE TITLE
Better MC crashes/stops responding if Fabric API is updated above 0.56.0 and if Fabric Loader is above 0.14.8

### ISSUE THREAD

**Issue by xtosutosu** [LunaPixelStudios/Better-MC#685]
### Describe the Bug

Better MC crashes/stops responding if Fabric API is updated above 0.56.0 and if Fabric Loader is above 0.14.8

If the user is able to join the world, some of the chunks will stop being rendered (although they are still interactable), however after a few seconds the game will freeze and it might crash.

### Reproduction Steps

1. Update Fabric API to or above 0.56.0
2. Update Fabric Loader to or above 0.14.8
...

### Screenshots and Videos

Screenshots are not needed.

### Crash Report or Log

https://mclo.gs/oTQQXTB

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v12

### Optifine

No

### Other Mods

I tried to install Create (Fabric) but the modpack crashes even without it.

**Comment by xSHXRKIEx** [comment]
1.18 fabric is discontinued and you should be updating things in the first place

**Comment by xtosutosu** [comment]
I propose 1.18.2 should be continued due to chat reporting and also many mods still being available only for 1.18.2
