### ISSUE TITLE
better mc forge 1.9.2 V2 serveur : erreur de sécurité

### ISSUE THREAD

**Issue by neajjj** [LunaPixelStudios/Better-MC#686]
Bonjour, tout d'abord merci à tous pour le travail que vous faites ! 

J'ai voulu installer better mc forge 1.9.2 V2 serveur mais quand j'essaye de lancer le fichier start.ps1 j'ai une erreur de sécurité : 

 Vous ne pouvez pas exécuter ce script 
sur le système actuel. Pour plus d’informations sur l’exécution de scripts et la définition de stratégies d’exécution, voir la rubrique about_Execution_Policies à 
l’adresse https://go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : Erreur de sécurité : (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess

Aurriez-vous une solution pour palier au problème ? 

Merci d'avance.

**Comment by xSHXRKIEx** [comment]
I dont have a solution
