### ISSUE TITLE
Error while installing v16 server

### ISSUE THREAD

**Issue by MyLittleFoxxie** [LunaPixelStudios/Better-MC#687]
### Describe the Bug

I am unable to install the Better Minecraft v16 server due to an error that occurs during the 'start' Shell Script runtime.

Java 18 is installed.

### Reproduction Steps

1. Extract server files to new folder
2. run start shell script
3. Accept EULA
4. error

### Screenshots and Videos

![Screenshot_2](https://user-images.githubusercontent.com/78807369/187309310-5d14b728-6858-49b4-a443-14a816a93c6d.png)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

40.1.68

### Optifine

No

**Comment by xSHXRKIEx** [comment]
this isnt shelll script, you need to run it with shell
