### ISSUE TITLE
Taming bug v16

### ISSUE THREAD

**Issue by Brusein** [LunaPixelStudios/Better-MC#688]
Hi everyone, I tried to search and see if this was known but in v16 it seems if you tame an animal and logout and back in it is not tamed anymore. I've tested this on dogs as a user reported. 

Update: well apparently you can punch them and they are magically re-tamed lol

Update 2: this is a problem for dragons, I'm punching them and can make them sit and can mount them but they will not fly.

Someone let me know if this is me thing with version 16 or if it affects you as well.

**Comment by xSHXRKIEx** [comment]
peopel have reported this in the psat. I am unable to recreate it, I tam a dragon and wolf, I fly away, teleport to another dimension and even stop the server and comign back I can still fly the dragona and my wolf is also still tamed. I cant really fix something that doesnt occur with me on a new world.

**Comment by Brusein** [comment]
Totally get it @xSHXRKIEx any recommendations if I start looking into it myself and don't want to lose the world?

I was on version 14 before and it seems you did so much for 16 I don't want to miss out.

**Comment by Brusein** [comment]
FYI @xSHXRKIEx  I created a new server today 100% new files and world and still have the taming issue, not sure why. Trying to look into it tested dogs, horse, dragon all had the issue.

**Comment by kkshah96** [comment]
> peopel have reported this in the psat. I am unable to recreate it, I tam a dragon and wolf, I fly away, teleport to another dimension and even stop the server and comign back I can still fly the dragona and my wolf is also still tamed. I cant really fix something that doesnt occur with me on a new world.

FWIW I have only noticed this on my server, and couldn't reproduce on a single player world. In case it helps

**Comment by xSHXRKIEx** [comment]
I have tested it on a server where I tame a dragon, go to another dimension, go far away, stop the server and rejoin etc but every time I am able to fly the dragon.
