### ISSUE TITLE
server lag with Duplicate UUID entity causes crashing, timed out errors. Always a pesky crow

### ISSUE THREAD

**Issue by Rallam259** [LunaPixelStudios/Better-MC#689]
### Describe the Bug

During our server that is a few days old now, the world is working well, no errors as we know and everything going well. However now, an entity seems to be causing intense lag, so much so the server says in the log, assumed it crashed so it will stop the server to produce a crash log.

We tried to find a solution but nothing we have tried seems to work. I thought i would approach the modpack makers and get some more help if possible. ( I do not have access to teh crash log, i am at work and its on my friends computer)

Thank You for the help
Ryan H

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft 1.18.2

### Optifine

No

**Comment by xSHXRKIEx** [comment]
I need the Crash log and latest.log in order to help

**Comment by Rallam259** [comment]
[crash-2022-08-31_20.41.07-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/9471360/crash-2022-08-31_20.41.07-server.txt)

here is the crash log above ^^^^

[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/9471367/latest.log)

latest.log above ^^^^

**Comment by Rallam259** [comment]
we also have narrowed it down to a certain direction one of our friends was always walking in during every restart. as soon as a chunk in that direction or entity is spawned. it crashes the server every time without fail. but i do not know how to efficiently read crash dumps and we assume it could be a corrupted chunk.

**Comment by xSHXRKIEx** [comment]
See if removing Radium mod fixes it

**Comment by Rallam259** [comment]
So. Remove radium. Then go and render the area that crashes? Is it easy to remove a mod?

**Comment by xSHXRKIEx** [comment]
yeah, just delete it from the mods folder

**Comment by Rallam259** [comment]
i attempted this fix. and the results were unchanged. it still crashed going into a certain area of our world. So i have re-added the mod for stability as it appears to not be the issue.

**Comment by xSHXRKIEx** [comment]
Could you give me a report without the radium mod please

**Comment by Rallam259** [comment]
I tried to however it wouldn't generate one after 5 minutes of waiting. I will attempt again tomorrow.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rallam259** [comment]
[crash-2022-09-04_11.04.07-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/9484446/crash-2022-09-04_11.04.07-server.txt)

Crash log obtained. This is with radium removed. I removed it again since my server wouldnt run and it would crash on start up.

**Comment by xSHXRKIEx** [comment]
It really does not want to say what entity is causing it. So this is a new world for v16? or one updated from v15?
Could you add back radium then do /spark profiler --timeout 30 and send the link

**Comment by Rallam259** [comment]
Is it an entity at all? We've just encountered another location of our world that crashes the server too. Yeah its a fresh V16 server and modpack. The same day you released it. You made a server. Ill add back radium and do that as soon as i can.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rallam259** [comment]
https://spark.lucko.me/4SAqKdQaN2

Here is the spark link for you :)

**Comment by xSHXRKIEx** [comment]
Yeah this is a weird issue, it just does not want to give me the information i need. The only thing I could go off is that architery mod needs a possible update. YOu could try doing that for both client and server and if that still doesnt work the best I can recommemend is to wait for another update or go to 1.19.2

**Comment by Rallam259** [comment]
Okay then, question i have if you could answer please. what is the crash log telling you if anything? Can we port or world to 1.19.2? 

Last one is. we appear to find multiple areas around that cause looping or something and freezes the server. assumes it crashed stops and gives us a server crash log.

Thank you for the help
Ryan H

**Comment by xSHXRKIEx** [comment]
All it tells me is that there is a blockable event loop but no indiciation of what is causing it.
I dont think you can port.

Could you see if remiovng the Straw Golem mod maybe fixes it, just going over it again and maybe it could be the issue.

**Comment by Rallam259** [comment]
alright i tried your potentail fix of removing the strawgolems. i went to the problem area on the server and the server still crashed as it tried to render the area. if you are out of ideas or options. we can possibly try 1.19.2. are there big differances to the world so we cant port it over?

**Comment by xSHXRKIEx** [comment]
usinga  1.18.2 port in 1.19.2 is not recommened, let me do a silent update and see if that fixes your issue

**Comment by Rallam259** [comment]
Oh okay brilliant. Let me know what you want us to do. We enjoy your packs and we recuse to go anywhere else. Let me know what we can do to help you out and keep this up. Look forward to what you have coming. 🙂

**Comment by xSHXRKIEx** [comment]
See if updating to v16.5 Fixes your issue

**Comment by Rallam259** [comment]
Rightyo. just to be sure, we able to just set up the server as is and through our world in there and this should hopefully fix the issue?

**Comment by xSHXRKIEx** [comment]
Yes you add your world to the new serverpack and make sure your client is updated and see if the issue is fixed.

**Comment by Rallam259** [comment]
we added our world to the new server and the same error persists. we are going to make a new world sadly.

**Comment by xSHXRKIEx** [comment]
Yep that is the best thing you can do now unfortunately
