### ISSUE TITLE
Server crash v16

### ISSUE THREAD

**Issue by Raymark97** [LunaPixelStudios/Better-MC#690]
### Describe the Bug

I was exploring with my dragon and the server crashed. i was in twilight meadow biome. the game crashed 3 times. i allegate logs, i tried to look into them but i can't find the cause.

https://pastebin.com/fF9qv5Mz
https://pastebin.com/6JGSduaU

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/6JGSduaU

### Operating System

Linux

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v16

### Optifine

No

**Comment by xSHXRKIEx** [comment]
See if removing the Radium mod fixes it

**Comment by Raymark97** [comment]
i'll try and i'll let you know if it crashes again.

**Comment by Raymark97** [comment]
happened again while exploring with Aether dragon. Unfortunately (idk why) it didn't create the crash log, i'll try to make it crash again

**Comment by Raymark97** [comment]
i think the crashes are related to certain areas. like a big mushroom and some other places...

**Comment by xSHXRKIEx** [comment]
See if updating to v16.5 Fixes your issue

**Comment by xSHXRKIEx** [comment]
If it doesnt, I can only reccomemd a new world since I am unable to replicate this myself
