### ISSUE TITLE
Failure to Start Pack

### ISSUE THREAD

**Issue by LeFallenAngel** [LunaPixelStudios/Better-MC#691]
### Describe the Bug

Modpack refuses to start, alert pops up saying that it failed to create java virtual machine. According to most that means it doesn't have enough memory but it currently has 16-17gbs (I know thats over kill) but it still fails to load with this error

### Reproduction Steps

1.Just start the pack
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/112591932/187800771-26aa67d4-86ee-4b74-8805-0b87f483fc0f.png)

![image](https://user-images.githubusercontent.com/112591932/187800625-e0e25fa3-76ec-4698-a428-87fa59ad3288.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V3

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Thats a Curseforge launcher, try other launchers like ATLauncher
