### ISSUE TITLE
Random Crash due to Twilight Forest Trophy Rendering

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-MC#692]
### Describe the Bug

Just started up my game and it immediately crashed soon after due to Trophies i put up, idk why its an issue to render it in but it crashed and looked at the gist of it.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/jPjMvNNd

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v16

### Optifine

No

**Comment by FevilGitHub** [comment]
i have enough time to remove them, it just crashes otherwise.

**Comment by xSHXRKIEx** [comment]
Remove the Illager Plushies mod and see if that fixes it

**Comment by FevilGitHub** [comment]
I am unsure of how to remove mods in Better MC, i might just wait til the new update, not that im pissed or anything, i just have lack of expertise on mods lol
