### ISSUE TITLE
Pets won't sit 

### ISSUE THREAD

**Issue by EmeraldParrot** [LunaPixelStudios/Better-MC#693]
### Describe the Bug

Pets will not sit. I tamed a parrot but it wouldn't sit no matter what I tried. I tried attaching it to a lead and putting it on a fence post but whenever I left the chunk and returned and it loaded in it teleported to me with the broken lead. 

The same problem applies with pet dragons. As soon as I tamed the dragon I could make it sit and use it to fly but after I relogged I couldn't use the bone to make it sit or use it to fly. It was unresponsive but I could mount it.

### Reproduction Steps

1. Tame a pet
2. Relog (Dragon, the bird couldn't sit as soon as I tamed it)
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v15

### Optifine

No

**Comment by xSHXRKIEx** [comment]
I am unable to reproduce this issue, can you tell me how old this world is?

**Comment by EmeraldParrot** [comment]
According to my friend this world was made about 2 weeks ago with v15. I haven’t tried taming a wolf but I know parrots and dragons wouldn’t sit.

**Comment by xSHXRKIEx** [comment]
YOu can try updating to v16 but as I said I am unable to reproduce this with multiple ways peopel have told me how they experience it.
