### ISSUE TITLE
Dragon egg always spawns a fire dragon no matter the conditions

### ISSUE THREAD

**Issue by EmeraldParrot** [LunaPixelStudios/Better-MC#694]
### Describe the Bug

I had various types of dragon eggs (Aether, Fire and Forest) and they all hatched into a fire dragon despite having the different egg texture. My fire dragon egg turned into a forest dragon when I placed it in a jungle biome and I went to the height limit to hatch my Aether dragon but it still spawned as a fire dragon despite being an Aether egg.

### Reproduction Steps

1. Place an egg in any biome or setting.
2. Hatch it.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v15

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Update to v16 but I had no issues with it changing in v15
