### ISSUE TITLE
v16 300% CPU upon join instant crash

### ISSUE THREAD

**Issue by 2000niek** [LunaPixelStudios/Better-MC#695]
Been using the Better Minecraft v16 1.18.2 modpack for a few days now and ran with no issues for at least 12 hours of playtime. Now all of a sudden since yesterday whenever we join the server it crashes within 30 seconds. I am getting at least 6 errors throughout the startup process and hundreds of issue reports to do with mods items being broken/insufficient etc. I fully uninstalled and reinstalled the modpack from scratch but the issue occurs just the same. When the server is running by itself and no players are online it uses only 30% cpu which is fine. But as soon as a player joins this rises to 300 for a minute, then lowers down to 100 sometimes peaking to 200 (just 1 player).

'couldnt parse data file...' is a error message i get for many items in the game.

![image](https://user-images.githubusercontent.com/54068897/187914693-3353ed00-d04e-4b30-88f3-4c800a3b9c9e.png)
(hundreds if not thousands of these lines)

![image](https://user-images.githubusercontent.com/54068897/187914890-00200447-8cad-467f-a3fe-a5c7fc3c6ae7.png)
no players after startup

![player joinnn](https://user-images.githubusercontent.com/54068897/187916193-58f3d1bc-054c-48e1-a353-17f4d333624f.png)
player joins

Upon join i see this in my chat:

![2022-09-01_14 36 53](https://user-images.githubusercontent.com/54068897/187915847-113f3020-f0fd-4e90-91b0-bae2ff879402.png)

![2022-09-01_14 36 54](https://user-images.githubusercontent.com/54068897/187915857-cccd053c-3a7c-4db9-bed8-90a0e5953ed1.png)
![2022-09-01_14 36 55](https://user-images.githubusercontent.com/54068897/187915868-4fe1aedd-0795-47c8-ad25-bdbd26c20c9c.png)

Latest Log:
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/9469834/latest.log)

Debug Log:
[debug.log](https://github.com/LunaPixelStudios/Better-MC/files/9469837/debug.log)

Hope someone can somehow help me with this! Thanks!

**Comment by aesopcmc** [comment]
i alway crash

**Comment by xSHXRKIEx** [comment]
From those images you send,  I could be completelty wrong but it seems like you are somehow using scripts from the Vault Hunters Modpack and possbily other Modoacks too. So this raises the question that is this world from another Modpack, did someone accidently stuff up and add another modpack stuff into yours.

Can I also get a crash report please and in game can you run /spark profiler --timeout 30 an send it here.
