### ISSUE TITLE
error crash

### ISSUE THREAD

**Issue by BrenoFranca8** [LunaPixelStudios/Better-MC#696]
### Describe the Bug

crash minecraft tlaucher

### Crash Report or Log

https://github.com/BrenoFranca8/BrenoFranca8/edit/main/README.md

### Operating System

10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Dont support cracked launchers
