### ISSUE TITLE
Nether Portal Doesnt TP after updating server

### ISSUE THREAD

**Issue by Acenaika** [LunaPixelStudios/Better-MC#697]
### Describe the Bug

I updated the server from V56 to V58.5

  When trying to enter my nether portal, the portal does not TP instead keeps me swirling.

### Reproduction Steps

1. Create a server in V56
2. Create world
3. Generate Nether
4. Update server to V58.5
5.Try to enter nether
6.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v58.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
v57 required a new world and this is the reason why, you decided to skip past it and ignore its changelog so I cant help further. Best is to reset the nether dimension and thats about it
