### ISSUE TITLE
Server crashing. Better Minecraft [FORGE] 1.18.2

### ISSUE THREAD

**Issue by SawWenJie** [LunaPixelStudios/Better-MC#698]
### Describe the Bug

Was exploring around my world until I reach a point where it lags/crashes the server and it would timed me out. I have restarted the server several times and it would lags/crash at the same general area.

Trying to rejoin the server would result at being stuck at "Encrypting", and under the server list, it would still display my username under player list, despite the fact that I got timed out from the server.

Server wouldn't crash immediately, it would force close itself shortly after with the reason "ServerHangWatchdog detected that a single server tick took 120.00 seconds"

I noticed that the mini-map would also stop rendering pass a certain point, and the crash would happen shortly after.

Crash Report 1 - https://pastebin.com/0NzhG5J0
Crash Report 2 - https://pastebin.com/A89hKR05

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

Latest Crash Report - https://pastebin.com/25BrGP2x

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v16

### Optifine

No

### Other Mods

- Removed Illager Wear Armors
- Removed 3D Skin Layers
- Removed Immersive Weathering
- Removed Adorn

- Added MrCrayfish Furniture Mod
- Added Tinker's Construct
- Added Storage Drawers
- Added Bonsai Trees 3
- Added Cooking for Blockheads
- Added Titanium
- Added Industrial Foregoing
- Added ExpandAbility
- Added Artifacts
- Added Forbidden and Arcanus

**Comment by xSHXRKIEx** [comment]
The Crash Report is not indiciating what mod is causing the issue and I can onluy assume it is on of the mods you added. 
You can try removing Radium reforged other than that the best bet is to remove the mods you added.
