### ISSUE TITLE
Game stops working properly when promoting villagers ( from More villagers MOD )

### ISSUE THREAD

**Issue by Kukolog** [LunaPixelStudios/Better-MC#700]
### Describe the Bug

The problem happens when I promote the oceanographer or any new profession from level 2 to level 3 from  More Villagers [Fabric] MOD.

Game doesn't crash , but I can't interact with villagers or blocks. Looks like a lagged server but it never returns
Sometimes I can save the game and reopen normally. But sometimes after choosing the save option, the game just don't save anything and after a long time, I have to kill the java using task manager. 

Thanks

### Reproduction Steps

1. Create a local game on survival
2. Find a village
3. Try to upgrade the new villagers from the mod above level 2 making trades.

I did not test it in a new game or creative yet. 

### Operating System

Window 10 

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

I install Better MC from Curse and run from there

### Optifine

No

### Other Mods

There are hundreds of mods on Better MC [FABRIC] - 1.19 & 1.18.2

**Comment by xSHXRKIEx** [comment]
Remove the mod, this will be removed in the next update
