### ISSUE TITLE
Minecraft Crashes Loading Terrain

### ISSUE THREAD

**Issue by KatnissQueen** [LunaPixelStudios/Better-MC#703]
### Describe the Bug

Died in hardcore and when i try and load the world to spectate it crashes when it says loading terrain and makes a really annoying sound which i think is it repeating a sound that killed me over and over again.?

### Screenshots and Videos

https://user-images.githubusercontent.com/112755170/188266142-1e29f8b3-cdc3-4f5e-bb43-ad6dcc7659a3.mp4

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

3 I think?

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Need the crash report or latest.log

**Comment by KatnissQueen** [comment]
> Need the crash report or latest.log

I didn't get a crash report?

**Comment by xSHXRKIEx** [comment]
then a log

**Comment by KatnissQueen** [comment]
> then a log

how do i do that?

**Comment by xSHXRKIEx** [comment]
In the modpack folder > latest.log
Also what are we trying to do here? You want to be able to spectate your harcore world you died in?

**Comment by KatnissQueen** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/9491194/latest.log)

Yes i am trying to spectate my hardcore world so when i do that i can allow cheats and recover it but first i need to spectate.

**Comment by xSHXRKIEx** [comment]
This log indicates that their was no crash. I also tested this myself with no issues. See if making a new world on v4 helps? If you dont want to do that you can try updating the modpack and see if your world is fixed with it.

**Comment by KatnissQueen** [comment]
I have updated it and still crashes. It may not be registered as an official crash but it still crashes as you can see from the video. Is there anyway i can recover my world
