### ISSUE TITLE
Dragons wont move when hitting wasd keys or when i try to fly.

### ISSUE THREAD

**Issue by UnknownEnvy** [LunaPixelStudios/Better-MC#704]
### Describe the Bug

When I first hatch the egg and it grows up I can fly it, but when I go to a different dimension or log off the server the dragon will only turn or look, up, down, left or right. helppp

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v16

### Optifine

No

### Other Mods

BETTER MC FORGE 1.18.2 v16

**Comment by xSHXRKIEx** [comment]
Just like i have told the previous people, I am unable to replicate these issues with doing the same things. Therefore I am unable to help.

**Comment by PotatoPcUtilizer** [comment]
try relogging the world, but you said something about a server, so that might be causing problems, idk, i suck at troubleshooting.
