### ISSUE TITLE
World Crashes on Server, but works on Singleplayer.

### ISSUE THREAD

**Issue by SawWenJie** [LunaPixelStudios/Better-MC#705]
### Describe the Bug

I summited the same issue a few days ago and it was closed immediately after.

The issue still persist **after removing** every extra mods that I manually added + Radium.

I have also tested, with ALL the extras mod still installed, in a single-player world, and it does not crash the world.
However, moving onto a server/multi-player world would crash it, **with or without**, all the extra mods I manually added.
All the test was carried out in the same exact world using the same world seed.

Issue is as described previously:
"Was exploring around my world until I reach a point where it lags/crashes the server and it would timed me out. I have restarted the server several times and it would lags/crash at the same general area.

Trying to rejoin the server would result at being stuck at "Encrypting", and under the server list, it would still display my username under player list, despite the fact that I got timed out from the server.

Server wouldn't crash immediately, it would force close itself shortly after with the reason "ServerHangWatchdog detected that a single server tick took 120.00 seconds"

I noticed that the mini-map would also stop rendering pass a certain point, and the crash would happen shortly after."

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/V40XZvNB

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v16

### Optifine

No

### Other Mods

- Removed Illagers Wear Armors
- Removed 3D Skin Layers
- Removed Immersive Weathering
- Removed Adorn

**Comment by xSHXRKIEx** [comment]
So I have no issue removing those Mods and get no crash and the crash doesnt really tell me what is wrong either.

What do you mean by "The issue still persist after removing every extra mods that I manually added + Radium."
Did you add Radium? Because it is already in the modpack.

**Comment by Rallam259** [comment]
yeah thats exactly the same thing we get. 1 specific area. well actually 2 or 3 now that the server freezes up on. we call them dead man areas. we cant figure a fix. but if it works in singleplayer i havent a clue.

**Comment by xSHXRKIEx** [comment]
Well I dont know, I cant reproduce the issue nor does the crash really say what mod is causing it. You can try updating to v16.5 other than that the best is to make a new world.
