### ISSUE TITLE
'Showing Craftable' function in REI is showing a fixed list of recipes when inventory is empty

### ISSUE THREAD

**Issue by CoenJC** [LunaPixelStudios/Better-MC#706]
### Describe the Bug

REI 'Showing Craftable' function is showing these recipes when inventory is empty

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://www.reddit.com/r/feedthebeast/comments/x5hd44/better_mc_rei_showing_craftable_function_is/

### Operating System

Win 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
This is likely an issue with REI itself, as it tends to be buggy. You could poke around in the config and see if anything there helps.

**Comment by xSHXRKIEx** [comment]
We will see what we are able to do in the next update, it will not be garunteed a fix though.
