### ISSUE TITLE
dragons

### ISSUE THREAD

**Issue by UnknownEnvy** [LunaPixelStudios/Better-MC#707]
### Describe the Bug

The dragon eggs when hatched are only fire dragons??? why does this keep happening. I've been messing with this ever since I first posted my first issue. I still can't move the dragons and no one else can either. please help (Envy#5504 < discord)

### Reproduction Steps

1. hatch egg (survival or creative)
2. doesn't hatch as the right dragon
3. tame and fly it
4. go to different dimension or log off server then come back.
5. cant use dragon

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v16

### Optifine

No

**Comment by UnknownEnvy** [comment]
spawn eggs don't work either

**Comment by xSHXRKIEx** [comment]
Whats the point of opening a new issue when I already told you. that I cant help cause litrally testing this I have no issues.
