### ISSUE TITLE
Cannot drop items when using "g"

### ISSUE THREAD

**Issue by Koceto** [LunaPixelStudios/Better-MC#708]
### Describe the Bug

I'm using "g" as my drop key and for some reason, I cannot drop items from my hotbar(closed inventory).
When I open my inventory, everything works as expected. It's only when my inventory is closed, that I cannot drop items.
**Other keys work fine.**

I've tried removing mods and I was able to solve it after removing the following mods:
- Inventory HUD+
- Zoomify
- Drippy Loading Screen
- Fancy Menu
- Mod Menu
- Open Parties and Claims
- Spirit
- WTHIT
- Xaero's Minimap
- Xaero's World Map

I assume it's a dependency they have that's causing the issue. I've played other modpacks with some of the mods and I've never had issues.

There are no conflicts in the Key Binds menu.

### Reproduction Steps

1. Rebind drop key to "g"
2. With closed inventory, try to drop something.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v3

### Optifine

No

### Other Mods

I've added MiniHud and FreeCam.

**Comment by xSHXRKIEx** [comment]
Can you reset it back to q and see if it works?

**Comment by Koceto** [comment]
Yes, it's working with other keys, including "q". Just tested again to confirm.
"g" seems to be the issue.

**Comment by xSHXRKIEx** [comment]
Best I can just recomemend is to not use g, only thing i can think of is it is has a confilct but you said it doesnt

**Comment by Koceto** [comment]
Not really a solution.
Plus, further testing shows that "g" is unusable with other functions as well. I tried to use it as Empower (Spirit) key, which didn't work. Tried to use it as Open/Close inventory as well, which again, failed.
Please do take a look at what's hogging the key, or at least give some pointers as to where to look.

**Comment by Koceto** [comment]
> Best I can just recomemend is to not use g, only thing i can think of is it is has a confilct but you said it doesnt

Please re-open the issue. As I mentioned in my comment above, it appears no functions work with the g key, not only the drop.
