### ISSUE TITLE
Chests are empty in v4

### ISSUE THREAD

**Issue by EchoLWS999** [LunaPixelStudios/Better-MC#710]
### Describe the Bug

Chests in generated scructures are empty in the newest Fabric v4 update.

### Reproduction Steps

1. Download the newest Fabric Better MC update v4
2. Find a structure generated by Better MC with a chest
3. No items
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v4

### Optifine

No

### Other Mods

Essential

**Comment by xSHXRKIEx** [comment]
No issues on my end, probably caused by the essentail mod
