### ISSUE TITLE
Getting an internal server error when trying to enter into my server

### ISSUE THREAD

**Issue by TowHeadMark10** [LunaPixelStudios/Better-MC#711]
### Describe the Bug

I'm trying to enter into my server and I'm getting the following error: "internal server error". 

Here is the log:
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/9492770/latest.log)

I'm using v58.5 (current) better MC 1.16.5

Here is the log from Aternos server:
https://mclo.gs/Oig4cD1

Other players can normally enter into the server, we have the same latest version :(

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/Oig4cD1

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v58.5

### Optifine

No

**Comment by chorbintime** [comment]
Reinstall with GDLauncher, disable firewall and antivirus, make sure you can join other minecraft servers

**Comment by xSHXRKIEx** [comment]
I believe its more of a server issue that Aternos cant keep up
