### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BrenoFranca8** [LunaPixelStudios/Better-MC#712]
### Describe the Bug

 error -1

https://github.com/BrenoFranca8/dsadasdsa/issues/1

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://github.com/BrenoFranca8/dsadasdsa/issues/1

### Operating System

10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

No

**Comment by chorbintime** [comment]
delete the FancyMenu mod from your mods folder
