### ISSUE TITLE
Better MC 1.18.2Would i be able to add The Aether to your better MC pack for the server? I've missed it.

### ISSUE THREAD

**Issue by Rallam259** [LunaPixelStudios/Better-MC#713]
### Describe the Bug

Just wondering if i could add the Aether to your modpack and not have any issues in 1.18.2.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

16.5

### Optifine

No

**Comment by chorbintime** [comment]
I mean, you could if it existed for 1.18.2 Forge. But it doesn't. 

The original Aether mod is still on 1.12. The Aether II is still on 1.12. And Paradise Lost is on 1.18.2 Fabric.
