### ISSUE TITLE
abyss

### ISSUE THREAD

**Issue by yologoat123** [LunaPixelStudios/Better-MC#716]
### Describe the Bug

hey, I just want to ask if we can turn off freezing effect in the abyss in our server

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v58.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Questions can be asked in discord
