### ISSUE TITLE
Possible hanging timer server crash (After making a new world) (FIXED)

### ISSUE THREAD

**Issue by Rallam259** [LunaPixelStudios/Better-MC#717]
### Describe the Bug

We have found another chunk the server hates and it seizes up completely. I am prepared to send you the full server you can run for yourself and see if you can narrow it down to something.

Would you be able to do this?

it seizes pretty hard and refuses to produce a crash log.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2 v16

### Optifine

No

**Comment by Rallam259** [comment]
I was able to move the world into singleplayer and move the broken area. and it was also broken in singleplayer. so i can send you all the files you want and you can possibly find the fix.

**Comment by xSHXRKIEx** [comment]
Sending me the world wont help, I would have to spend hours removing each mod till it fixes itself. We have multiple people running 1.18.2 public servers without issues. How you are getting this on a new world doesnt make sense, instead of sending me your world, give me the seed and location.

**Comment by Rallam259** [comment]
I am my server host. i run the server myself for me and me friends.

the version we are using is ofcourse v16.5
the world seed is -7269525357505379374
the co-ords for the chunk that will not play nice is -2176, 149, 437 in a plains biome. if you can render the area around that chunk without problem wether in singleplayer, with a server in your own computer that only you can access then i dont know what the hell the problem is either.

**Comment by xSHXRKIEx** [comment]
![2022-09-08_16 39 31](https://user-images.githubusercontent.com/79353591/189076783-496f23e9-e56a-4540-bd3a-5bfa1eaac966.png)
No Crash, so yeah I dont know how to help other than makes sure everyhting is fresh. Possibly your pc having an issue? what operating sytem are you using and specs?

**Comment by Rallam259** [comment]
FFS. Another option i thought of is getting a world pre generator and running that through the server to pre-gen all the chunks. that would take alot of stress off of the CPU incase it is that.

I'm using windows 10 64-bit Home Edition

I have the server installed on an M.2 NVME SSD
I have an Intel-i7 10700K
AMD 6800XT
32GB RAM TRIDENTZ 3000MHZ
I allocated 14GB to the server i have seen it reach upto nearly 10GB get used at one time so i increased it.

Anything other info you would like to know? :)

**Comment by Rallam259** [comment]
Okay. I also put in the server seed in a singleplayer minecraft world. Fresh world fresh as can be. I travelled to those coords. And my minecraft singleplayer has crashed and frpzen in place. Only i can travel but no mobs or blocks respond to my input. 

Coords -2240

![16626555075907555899552202916031](https://user-images.githubusercontent.com/112554545/189179306-a722dbd8-bf8d-478b-b68f-9e2fd75a50cd.jpg)
![16626555473242972290086148395775](https://user-images.githubusercontent.com/112554545/189179425-5e64ac07-1c21-4199-9fa0-f78c9d779e70.jpg)

**Comment by Rallam259** [comment]
I have also re downloaded the server pack so its fresh as a baby. same world seed. Tped to the problem area as shown above and it has still crashed. i can confidently recreate this issue. i just cant get a crash log anymore because theserver hangs there from the server tick -1.

**Comment by chorbintime** [comment]
please send your spark profiler while the lag happens. Run the following command:
/spark profiler --interval 100
You may have to use the manual stop command. Then post the link here.

**Comment by Rallam259** [comment]
I'll try it for you. Although i am worried it will not yield results.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rallam259** [comment]
right okay. sorry for throughing info at you. The pack is never crashing. niether on my singleplayer nor the server. never has crashed. its literally INTENSE LAG. so much so everything comes to a stand still. so theres no corrupted chunks or entities. something is trying to be rendered but then because of something. the world gets stuck in LAG. The server previously closed itself because of the LAG. This could be good help to you. I may start removing mods one by one but that could take a hell of a long time. When i get home i will run the command for you unedited and then also go from there.

**Comment by Rallam259** [comment]
i tried to get you the spark profiler. however, because the servers freezes up from lag. it does not produce the file for you. Physically cannot achieve this goal with this issue. 

I managed to get a crash log but thats just from a force shutdown by server watchdog because of the huge lag.
Perhaps theres a mod outdatted or something just isnt playing right. if i could get a list of possible culprits i will try and narrow the mod down to render properly.

Am i able to use and install optifine into the server. this may optimise chunk loading? or i could be talking out of my arse.

[crash-2022-09-09_19.11.15-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/9537827/crash-2022-09-09_19.11.15-server.txt)

**Comment by chorbintime** [comment]
Optifine is not good, completely incompatible with several mods, and will only cause more issues. It is also not a serverside mod. Send the spark profiler by executing the command mentioned above then stop it manually with /spark profiler --stop

**Comment by Rallam259** [comment]
Fix Found on another thread. close this issue :)

**Comment by xSHXRKIEx** [comment]
What did you find on another thread? @Rallam259

**Comment by Rallam259** [comment]
It was the thread you closed. I commented on it too. The backport for the wild update causing significant lag. Then you reverted the mod by an update and its fixed.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
