### ISSUE TITLE
(Not A Bug) how do i add more ram in the server?

### ISSUE THREAD

**Issue by yookaaii** [LunaPixelStudios/Better-MC#718]
### Describe the Bug

i just wanna add more ram in the server but i cant find the option anywhere im using the server pack for 1.16.5

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

I used Optifine

**Comment by 2737471001** [comment]
add -Xmx#G in your server.bat

**Comment by 2737471001** [comment]
# can be any number you want (-Xmx8G)

**Comment by 2737471001** [comment]
13
