### ISSUE TITLE
I lost my backpack

### ISSUE THREAD

**Issue by GoldenXGamerZ** [LunaPixelStudios/Better-MC#719]
### Describe the Bug

All going well on my survival world on better mc 1.19.2 fabric, i got my first endless backpack from inmis mod, I die and when I get the totem of preserving my backpack is gone.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v4

### Optifine

No

### Other Mods

I added TrashSlot fabric.

**Comment by chorbintime** [comment]
This is likely an issue with the mod the totem is from. You can report it on their Github page.
