### ISSUE TITLE
Entity and block latency issues arise after first use of creative mode

### ISSUE THREAD

**Issue by EricR291** [LunaPixelStudios/Better-MC#720]
### Describe the Bug

I've been able to consistently reproduce the bug unfortunately... I've started three new worlds now with Better Minecraft and each time I go to build in creative mode for the first time, all entities begin to lag as well as blocks when I break them in survival. It does not appear to be a RAM or lack of power issue on the computer's side.

### Reproduction Steps

1. Start new world with Better Minecraft
2.Explore a bit
3. Get some stuff
4. Enter creative mode and build a home (or something more than just a few blocks - haven't tested at small volumes)
5. Observe entities in the world and be sad
...

### Operating System

MacOS Monterey V12.2

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better Minecraft V1.18.2

### Optifine

No

### Other Mods

N/A

**Comment by chorbintime** [comment]
Does this issue happen in survival? 

Also, please send your spark profiler while the lag happens. Run the following command:
/spark profiler --interval 100
You may have to use the manual stop command. Then post the link here.

**Comment by EricR291** [comment]
Apologies for the delay, yes. I also tried spectator and the issue continued. 
I did actually end up trying to recreate the issue again in a new world and it didn't seem to trigger the bug if I went right to placing blocks in creative. I also did test placing blocks from each mod and it didn't seem to trigger anything either. It's possible there was another correlation between all three of the other worlds that fell to the same demise of that lag... time.

All three of the other worlds I started, I ended up playing for about the same amount of time before entering creative mode to build my home. By the time I went back to playing in survival I would notice the lag. It was possibly somewhere between 8 and 12 hours of gameplay before this showed up in each world. I thought maybe the seasons mod? I tried disabling seasons, but I haven't tried removing them. Either way I think you'll have more expertise in the area of troubleshooting than me.

Here is what you requested: https://spark.lucko.me/NnW9HYQamd

**Comment by chorbintime** [comment]
Found the culprit. Allays are causing 87% of the server lag. You can run the following command to kill them all:
/kill @e[type=allay]
If that doesn't kill anything, then you'll need to find what mod the allays are coming from and put that mod's mod ID in front of "allay", such as /kill @e[type=minecraft:allay]. Or just kill everything with /kill @e[type=!player]

My theory is that, since you are going in creative, all mob pathfinding is no longer targeting you & this is ruining performance for some reason.
