### ISSUE TITLE
Better MC Server/Singleplayer Crash 1.18,2

### ISSUE THREAD

**Issue by TofuHell** [LunaPixelStudios/Better-MC#721]
Describe the Bug

Better Mc 1.18.2 will crash getting near a seemingly random chunk that was discovere by randomly exploring
going into spectator before going into the chunk revealed no unique mob/structure other then a unqiue overgrown mineshaft. 

On server: The server will near instantly crash when entering/going near affected area
On singleplayer: all AI for mobs break and commands will no longer be activate the game will always crash on attempting to save and exit the world. 

Reproduction Steps
1, Go creative 
2, fly around
3, either crash or notice AI freezing 

YouTube link to demonstration
https://youtu.be/hyTfoh3SROI
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/9531575/latest.log)

Operating system 
Windows 11

Version 
1.18.2 

Modpack Version 
16.5

Modloader 
Forge

Optifine 
No

Other Mods
Create 
Create Additions
Simple Planes
Framed BLocks
FTB Ultimine
AppleSkin
Croptopia

Removed Mods
The Conjurer
When Dungeons arise
Hunter Illager
Serene Seasons

**Comment by chorbintime** [comment]
Could you send your spark profiler please? Run the following command:
/spark profiler --interval 100

You may have to stop it manually.

**Comment by Rallam259** [comment]
Does croptopia clash with farmers delight and the add-ons in the pack possibly causing a lag in world rendering?

**Comment by TofuHell** [comment]
I am home from college so ill test the spark profiler now, to answer rallam259 question I disabled all the mods i added so i doubt thats the issue, me and my friends have traveled 8000 blocks in another direction and so far have not encountered this issue yet so i have no clue on whats causing it

**Comment by TofuHell** [comment]
How would one stop it manually since the console no longer works after loading effected chunk/area

**Comment by Rallam259** [comment]
Alrighty then. You have the exact issue we have. it even happens on singleplayer. something causes intense lag. me and my friends have bashed our heads against a wall to find something that cracks. nothing yet. we are close to checking every single mod big by bit but thats hours of work.

**Comment by chorbintime** [comment]
> Alrighty then. You have the exact issue we have. it even happens on singleplayer. something causes intense lag. me and my friends have bashed our heads against a wall to find something that cracks. nothing yet. we are close to checking every single mod big by bit but thats hours of work.



> How would one stop it manually since the console no longer works after loading effected chunk/area

You both need to send spark profiler links. The command to manually stop should be /spark profiler --stop

**Comment by Rallam259** [comment]
I thought you meant through the server. My apolagies. I'll get right to it when im kome later.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TofuHell** [comment]
YOOOOOO
i found it out! 

The wildback port version 1.2.2 causes any chunk with a pillager outpost to lag till timout
to fix this just roll back to 1.2.1 and everything works again, sing my praises

**Comment by Rallam259** [comment]
NOOO WAYYYYYY. HOW DID YOU FIND THIS!!!!

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xSHXRKIEx** [comment]
Uploading a Fix now

**Comment by Rallam259** [comment]
Well done everyone genuinely.
