### ISSUE TITLE
Anvil crash

### ISSUE THREAD

**Issue by Moona123456** [LunaPixelStudios/Better-MC#722]
### Describe the Bug

(Medieval MC Fabric v4.5)
When you Insert one of the new weapons the modpack adds in an anvil with any other item it immediately crashes the game and returns back to the launcher with exit code -1, and a message saying that an array failed because it was "null"

Examples for weapons that have done this: 
1) The Starless Night
2) Frost Scythe
Both of them were already enchanted.

### Reproduction Steps

1. Prepare an anvil.
2. Insert "The Starless Night" into the left slot (mine was enchanted).
3. Insert an enchanted book into the right slot.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V4.5

### Optifine

No

**Comment by chorbintime** [comment]
Does a crash report generate in the crash reports folder? If so, please attach the file.
