### ISSUE TITLE
Spawning issue for forge 1.16.5

### ISSUE THREAD

**Issue by Iamaturd** [LunaPixelStudios/Better-MC#723]
### Describe the Bug

Passive mobs will not spawn anymore. I have explored 5000 blocks of land and no cows, pigs, sheep or chicken will spawn. Only modded mobs like the raccoon from Alex's mobs will spawn, but no minecraft mobs that I listed 

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v58.5

### Optifine

No

### Other Mods

No other mods were added

**Comment by chorbintime** [comment]
Nothing can really be done about this, unfortunately. When you have hundreds of mods in a modpack, modded biomes and mobs will override the vanilla ones. Most of the mobs overriding the default ones have similar functions to the vanilla ones.

**Comment by Iamaturd** [comment]
Do you know if there's a way to decrease the effects of this?
