### ISSUE TITLE
Minecraft won't load world

### ISSUE THREAD

**Issue by KatnissQueen** [LunaPixelStudios/Better-MC#724]
### Describe the Bug

Yeah hey its me again, please can you try and help me this time. i try and load my world and it gets stuck on the loading screen making an annoying noise. its not an official crash so no crash log but it still breaks. please watch the video i linked if you need to understand whats happening.

### Screenshots and Videos

https://user-images.githubusercontent.com/112755170/188266142-1e29f8b3-cdc3-4f5e-bb43-ad6dcc7659a3.mp4

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

4

### Optifine

No

**Comment by xSHXRKIEx** [comment]
As I said before create a new world if it doesnt work, I cant help if the log indiciates nothing. Either create a new world or see if deleting your player data helps in the saves folder other than that I cant help
