### ISSUE TITLE
Backpack in bauble not placed in Totem of Preserving

### ISSUE THREAD

**Issue by DelterEcho** [LunaPixelStudios/Better-MC#725]
### Describe the Bug

While backpacks placed directly on the chest armor slot go into your totem, backpacks in the backpack bauble slot are left on the ground to despawn. I've lost a couple of backpacks now because of this and I wonder if this would be an easy fix. If you want me to report this directly to the Charm mod creator(s), could you give me the name of the mod that adds this backpack slot?

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Latest (1.19.2 v4)

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
This is up to the creators of the Charm mod. In newer updates, we will likely replace the Totem of Preserving with a corpse mod.
