### ISSUE TITLE
Cant Mine

### ISSUE THREAD

**Issue by Codizzle29** [LunaPixelStudios/Better-MC#726]
### Describe the Bug

If I use a pickaxe and mine with it, the pickaxe will mine the block as fast as my hand. Tried it will vanilla mc pickaxes as well as modded ones. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

v12

### Optifine

No

**Comment by chorbintime** [comment]
What dimension are you in?

**Comment by Codizzle29** [comment]
> What dimension are you in? Also, Fabric 1.18 is no longer maintained.

i am in the overworld. havent traveled outside of the overworld.

**Comment by chorbintime** [comment]
Does this issue persist in 1.19.2?

**Comment by Codizzle29** [comment]
It says its "Fixing world." It also had me check a box that said "I like trains." Idk what that was but i like trains so I checked it. But It fixed the problem thank you.
