### ISSUE TITLE
"upgradednetherite" mod fails to load upon startup (1.18.2)

### ISSUE THREAD

**Issue by EpicLPer** [LunaPixelStudios/Better-MC#727]
### Describe the Bug

Heya! Just discovered this mod and wanted to play it, however on 1.18.2 the mod "upgradednetherite" seems to cause an issue not letting Minecraft continue to load.

### Reproduction Steps

1. Download and Install
2. Launch
3. Mod fails to load

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/8442196/189524823-c7414c5a-3186-4fad-8602-80b0a5435720.png)

### Crash Report or Log

https://pastebin.com/wbtwPGF7

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.18.2 v17

### Optifine

No

**Comment by xSHXRKIEx** [comment]
haven you tried to relaunch>?

**Comment by chorbintime** [comment]
If the issue persists after relaunching 3 times, reinstall the modpack on GDLauncher.
