### ISSUE TITLE
Online mode declaration problem

### ISSUE THREAD

**Issue by Raulferval** [LunaPixelStudios/Better-MC#728]
### Describe the Bug

When I try to change the online-mode to false in the server.properties file and I launch the server using start.ps1 the server keeps trying to validate the users who try to join the world, making it impossible for no premium users to join the server.

### Reproduction Steps

1. Change online-mode to false
2. Open the server
3. Make a no premium minecraft user try to join the server
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v4

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Nope, dont do that and I can only assume you are trying to play cracked which is illegal and wont help with
