### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by hilox99** [LunaPixelStudios/Better-MC#729]
### Describe the Bug

when i go into my inventory, my game crash everytime. i tried to repair it in the curseforge launcher but the issue still there.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

[crash-2022-09-12_19.49.10-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/9550608/crash-2022-09-12_19.49.10-client.txt)

### Crash Report or Log

The game crashed whilst rendering screen Error: java.lang.NullPointerException: Cannot read field "enableMod" because "this.config" is null

### Operating System

windows 8

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Curse Forge: Better MC  [FABRIC] 1.19.2 v4 - (Beta)

### Optifine

No

### Other Mods

no, only better mc pack.

**Comment by chorbintime** [comment]
Does the Enchant Descriptions mod have an update available? If not, or the update doesn't fix this, report this issue here https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/new

**Comment by JoanUniverse** [comment]
I had the same issue. Probably, with a prior game crash, the config file for EnchantDescriptions mod had changed. In my case, there was a 'null' as content.
You need to find the 'enchdesc.json' file located in a config directory in your .minecraft data.
Then replace the file content with the following json:
```
{
  "enableMod": true,
  "onlyDisplayOnBooks": false,
  "onlyDisplayInEnchantingTable": false,
  "requireKeybindPress": false,
  "indentSize": 0,
  "style": {
    "color": "dark_gray"
  }
}
```
Now the game will be able to read the config file content and will not crash.
