### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Delsev** [LunaPixelStudios/Better-MC#731]
### Describe the Bug

After I updated to the latest version of the Forge version of the modpack and updated the mods in it to the latest versions, the game would crash whenever I try to open it. The Minecraft launcher loads but when loading the profile it crashes and doesn't even manages to show the Minecraft loading screen.
The same thing happens with the Fabric version.

### Reproduction Steps

1. Installed the modpack on CurseForge
2. Updated the mods from the modpack
3. Click on play
4. Wait for the Minecraft launcher to load and click on play
5. Game crashes and Minecraft launcher returns an error message

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v4

### Optifine

No

**Comment by chorbintime** [comment]
You're not supposed to manually update mods. Do a fresh install of the modpack. Some mods are left un-updated for a reason.
