### ISSUE TITLE
(1.19.2) Game Freezes on Create World

### ISSUE THREAD

**Issue by izofar** [LunaPixelStudios/Better-MC#732]
### Describe the Bug

Updated to Forge 1.19.2-43.1.25, installed modpack using config and mods folder from serverpack (v4). Upon creating a new world, the game froze, and gave the following [crash log](https://gist.github.com/izofar/5672e82c65fc9915fb8869d6eed6d7b7). Seeming an issue with Snow Real Magic, **I removed the mod from the pack and the issue did not persist.** 

### Reproduction Steps

1. Install Forge 1.19.2-43.1.25
2. Place config and mods folder from server pack v4 into desired version directory
3. Create a new world with seed [irretrievable]
4. Game freeze

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v4

### Optifine

No

### Other Mods

It Takes A Pillage v1.0.0-1.19.x (https://github.com/izofar/takes-a-pillage). Currently unreleased, but I chose this modpack for compatibility testing.

**Comment by chorbintime** [comment]
Did you test this without the added mod?

**Comment by izofar** [comment]
> Did you test this without the added mod?

Yes, having removed `takesapillage`, the crash still happens with the same error. I was able to reproduce in any world by teleporting to a snowy taiga biome. **Example** Seed: 3655561619755109649 Coords: `x=1329.50, y=95.12, z=-797.50`

**Comment by izofar** [comment]
Mod authors suggest `ferritecore` may be the issue, but I have not tested: https://github.com/Snownee/SnowRealMagic/issues/224

**Comment by chorbintime** [comment]
I re-read your original post and looked at your log.

Why did you put mods from the serverpack into the client? Your log says a Singleplayer world and you mention using the serverpack. 

This isn't the proper way to install a modpack and this could be causing your issue.
