### ISSUE TITLE
better end no crafting recipe

### ISSUE THREAD

**Issue by Shiynx** [LunaPixelStudios/Better-MC#733]
### Describe the Bug

No crafting recipe @better  end , Ender Dust in Anvil.
A lot of crafting recipes are not able to craft.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2

### Optifine

No

### Other Mods

Better End Modpack.

**Comment by chorbintime** [comment]
Better End Modpack? What? 

Also do you mean you can't craft Ender Dust? Like you are putting the stuff in a crafting table & it's not crafting? You put no reproduction steps and gave very little info.

**Comment by Shiynx** [comment]
betterEnd Mod. It is not possible to craft ender dust. Normally you craft it like with an Hammer and ender shard or ender pearl on an Anvil, but if i gonna do it there is nothing to craft.

**Comment by chorbintime** [comment]
Are you sure you're using a Smith Hammer from BetterEnd with an ender shard in an anvil?

**Comment by Shiynx** [comment]
yes I tried with all hammers and anvils, nothing seems to work. A lot of crafting recipes seems not working somehow.


![2022-09-17_10 13 27](https://user-images.githubusercontent.com/113501844/190847404-a6c5a05d-beea-4350-9d3a-3222ff5155b4.png)
![2022-09-17_10 13 29](https://user-images.githubusercontent.com/113501844/190847411-e9104f7d-502b-4294-b15c-8fc8eb1b204a.png)
![2022-09-17_10 13 10](https://user-images.githubusercontent.com/113501844/190847422-d012011c-363c-45ad-8544-9bd85dc13ff2.png)

**Comment by lajurcookie** [comment]
its true
![image](https://user-images.githubusercontent.com/98559240/190872491-51ca11bf-c4e4-4f81-888e-0a58f306837a.png)
![image](https://user-images.githubusercontent.com/98559240/190872521-cb80d140-5d32-45b6-92aa-5b9787b947d4.png)

**Comment by chorbintime** [comment]
Report on BetterEnd Github
