### ISSUE TITLE
Game launches in fullscreen

### ISSUE THREAD

**Issue by Xetaxheb** [LunaPixelStudios/Better-MC#735]
### Describe the Bug

The pack runs fullscreen by default

Please do not do this is can cause a wide variety of problems for people

### Reproduction Steps

1. Install pack
2. Run

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v5

### Optifine

No

**Comment by chorbintime** [comment]
What issues in specific are you referring to? Also I have never experienced the cursor issue & nobody has mentioned it before.

**Comment by chorbintime** [comment]
> I'm talking about general windows fullscreen program issues, not minecraft specifically. It's bad practice to run fullscreen by default because there are various different and independent issues that can arise, or interfering with other software like recording, or resolution bugs, or HDR issues. Plus if it freezes or locks up or lags for some reason you can get locked into it and have to hope ctrl+alt+delete works, failing that hard shutdown.

Will forward this to Sharkie. Thank you for the feedback.
