### ISSUE TITLE
If options.txt is going to be included anyway, set keybinds

### ISSUE THREAD

**Issue by Xetaxheb** [LunaPixelStudios/Better-MC#736]
### Describe the Bug

Either with defaultoptions fabric edition or options.txt, should unbind or change overlapping keybinds

Iris reload and open atlas are both R
New waypoint and backpack are both B
Open crafting, dragon fly, quiver, toggle empowered are all V
I assume it works properly but worth verifying dragon fly down and crawl don't interfere with eachother, being set to LEFT ALT

### Reproduction Steps

1. Install
2. Open keybinds
3. Click show conflicts

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v5

### Optifine

No

**Comment by chorbintime** [comment]
Will look into it in future updates.
