### ISSUE TITLE
Error while starting better mc (Code error: -1)

### ISSUE THREAD

**Issue by enricrf19** [LunaPixelStudios/Better-MC#737]
### Describe the Bug

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'entity_texture_features'!

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/uU0npDeA

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

0.14.9

### Optifine

No

**Comment by chorbintime** [comment]
Does this issue persist after relaunching 3 times and/or doing a fresh install?

**Comment by enricrf19** [comment]
It does persist after relaunching several times. I have not tried doing a fresh install. Would I loose my world file?

**Comment by chorbintime** [comment]
You won't lose your world file if you back it up.
