### ISSUE TITLE
Tom's mod pulling from inventory still not working (should've be fixed in v3)

### ISSUE THREAD

**Issue by Saharash** [LunaPixelStudios/Better-MC#738]
### Describe the Bug

Like tittle, i don't know, i opened a github issue a week ago, sharkie closed me it without any answer.

but the bug still not fixed. so i don't know if i did something wrong, i just updated from v3 to v4 on curseforge, and now it's v5 and it still don't work.

### Reproduction Steps

1. Enable not pulling from inventory
2. and it still pull from it
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better Minecraft Fabric V5 1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
If this is an issue with the Tom's Simple Storage mod, we can't really do anything about it.

**Comment by Saharash** [comment]
I see, but if it's writed fixed in v3 i don't understand why it still not working, that my question ^^

otherwise it not say fixed if the bug still occur

**Comment by chorbintime** [comment]
The changelog is based off the updates done by the creators of the mods. We have very little control over what is fixed, outside of reporting to the mod creators and looking at configs.

**Comment by Saharash** [comment]
> The changelog is based off the updates done by the creators of the mods. We have very little control over what is fixed, outside of reporting to the mod creators and looking at configs.

Oh ok i see, but if the owner of mod have fixed the problem and it still don't work, it mean that we don't have the latest on the modpack maybe?
