### ISSUE TITLE
Mobs Hp Doubles Up

### ISSUE THREAD

**Issue by Psychooz** [LunaPixelStudios/Better-MC#739]
### Describe the Bug

When pciking a mob up and put it back its hp doubles
medival 1.19 v4.5

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/86485110/190633236-49311233-a145-4bee-a96f-165a18b110c4.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v4.5

### Optifine

No

**Comment by chorbintime** [comment]
This is a common issue with the Carrier mod. You can report it on their Github.
