### ISSUE TITLE
Visual Glitch

### ISSUE THREAD

**Issue by GirthquakeII** [LunaPixelStudios/Better-MC#740]
### Describe the Bug

While mining there appears to be black spots that appear all over. they appear shortly after the block breaks. nothing too drastic just a weird thing.

### Reproduction Steps

1.mine (i was using stone pickaxe) 
2. black spots will appear shortly after the block breaks
3.  Happened at Y= 54
...

### Screenshots and Videos

unable to provide video or screen shots. 

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 V4

### Optifine

No

**Comment by chorbintime** [comment]
This is likely an issue on your side. You can try updating drivers and changing settings. VSync might fix this.
