### ISSUE TITLE
Spiders From Neapolitan Ignor Magnum Torches

### ISSUE THREAD

**Issue by Drunkenborn** [LunaPixelStudios/Better-MC#741]
### Describe the Bug

Hey so i have a base with magnum torches in a rainforest and this spiders still spawn from the Neapolitan idk if the need to get added to the magnum torch config or something other is false sorry for my bad english 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [PLUS] 1.18.2 v14

### Optifine

No

**Comment by chorbintime** [comment]
Spiders are not considered hostile mobs afaik.
