### ISSUE TITLE
Issue with achievments

### ISSUE THREAD

**Issue by Iamaturd** [LunaPixelStudios/Better-MC#742]
### Describe the Bug

I rejoined my better Minecraft world and the minute I started enchanting my gear I got the advancement enchanter, when thought i have enchanted many times before. I rejoined the world to see if there were any other advancements I had lost and there were. I took some diamonds out of my backpack and got the advancement Diamonds!. Literally all of my achievements were gone

### Screenshots and Videos

![bug 1](https://user-images.githubusercontent.com/113256134/190873815-3d308def-1961-4929-929a-60f0ce8f0b69.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

bmc v58.5

### Optifine

No

### Other Mods

No other mods

**Comment by chorbintime** [comment]
Since there are no reproduction steps we can't do anything about this. It is likely something on your side.
