### ISSUE TITLE
Ebony Crafting recipes

### ISSUE THREAD

**Issue by YamiKraken** [LunaPixelStudios/Better-MC#743]
### Describe the Bug

some items using the ebony logs as well as other non vanilla logs, the crafting items to be made arent working. attached is an example .

### Reproduction Steps

1. take ebony planks 
2. try the recipe for a chest
3. boom a normal chest comes out instead of an ebony chest
...

### Screenshots and Videos

![Minecraft Screenshot 2022 09 17 - 15 48 22 03](https://user-images.githubusercontent.com/54543940/190875958-40a15963-0c81-4824-b522-9ed9722324d5.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v4 and v5

### Optifine

No

**Comment by chorbintime** [comment]
Ebony chests probably just don't exist and the mod creator set it to make oak chests.
