### ISSUE TITLE
Villager won’t take forager profession?

### ISSUE THREAD

**Issue by stayingarmed** [LunaPixelStudios/Better-MC#744]
I’ve tried in both survival and creative and no villagers will take the profession.

**Comment by chorbintime** [comment]
Make sure there are no other profession blocks nearby and that it is trading hours.

**Comment by stayingarmed** [comment]
I had about 20 of the blocks in creative with a ton of villagers running around and nobody would take the trades and in my survival world he is isolated and with no other profession blocks around and he just stands there and wont take the job

**Comment by chorbintime** [comment]
What minecraft version are you playing?

**Comment by stayingarmed** [comment]
> What minecraft version are you playing?

Java….1.19.2 fabric

**Comment by chorbintime** [comment]
Update MoreVillagers mod if it has an update available.
If it has no update, report on their github/issue tracker.
