### ISSUE TITLE
Can't install on server linux/mac

### ISSUE THREAD

**Issue by Lalit64** [LunaPixelStudios/Better-MC#745]
### Describe the Bug

I've installed better mc on a server but it wont start.

I'm getting the following error.

<img width="592" alt="Screenshot 2022-09-19 at 09 06 30" src="https://user-images.githubusercontent.com/79628080/190945811-7d4ee3c7-50d0-4be4-8e76-2be6277862db.png">

minecraft-server is just an alias.

### Reproduction Steps

1. Follow 丂廾闩尺长工㠪 How to make a Server for Any Modpack [Forge & Fabric | 1.16 & 1.17] for fabric
2. Instead of start.ps1 use start.sh
3. Recieve the error
...

### Operating System

macOS Monterey

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v5

### Optifine

No

### Other Mods

Sodium

**Comment by chorbintime** [comment]
Sodium is already included in the modpack.

You need to run the start.ps1. If you are on a non-windows OS you can find a tutorial specifically for that.

**Comment by Lalit64** [comment]
@chorbintime running this with powershell installed threw homebrew results in these errors:

``` CMD: /opt/homebrew/etc/minecraft-server/start.ps1:61
Line |
  61 |      CMD /C "`"${Java}`" ${CommandToRun}"
     |      ~~~
     | The term 'CMD' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a
     | path was included, verify that the path is correct and try again.


CMD: /opt/homebrew/etc/minecraft-server/start.ps1:61
Line |
  61 |      CMD /C "`"${Java}`" ${CommandToRun}"
     |      ~~~
     | The term 'CMD' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a
     | path was included, verify that the path is correct and try again.


Exiting...
Press any key to continue
```

**Comment by chorbintime** [comment]
Try removing the smoothchunk mod.
