### ISSUE TITLE
Incomplete set of tags between client and server

### ISSUE THREAD

**Issue by PugLyf** [LunaPixelStudios/Better-MC#746]
### Describe the Bug

Better MC 1.16.5 Forge can't connect to server getting an incomplete server tags error. According to the error, there appears to be some sort of discrepancy between some of the mods for the client and server versions. I tried reinstalling the client through CurseForge multiple times (along with my friend who was trying to test connecting with me). Also tried reinstalling the server files and had no change.

### Reproduction Steps

1. Downloaded Better+MC+Server+Pack+FORGE+1.16.5+v58.5.zip and extracted the contents of the folder.
2. Renamed folder to "Minecraftserver".
3. Right-clicked on start.ps1 and ran with Powershell.
4. Followed instructions in the program and agreed to EULA.
5. Launched minecraft_server1.16.5.jar.
6. After the server was running tried connecting to IP in the Minecraft client.
7. Received error saying "Incomplete set of tags received from server. Please contact server operator."

### Screenshots and Videos

![Error](https://user-images.githubusercontent.com/28744016/190952645-bcc71310-f72f-4c64-ac43-01bce38acdcb.png)

### Crash Report or Log

Client log: https://gist.github.com/PugLyf/27a2d0459221d10c64955e3091fc4f0e Server Log: https://gist.github.com/PugLyf/aa411b00b69c8ed6eb8bb11ec05e025f

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v58.5

### Optifine

No

### Other Mods

No other mods. Used client and server pack downloads as is.

**Comment by chorbintime** [comment]
You need to run with the start.ps1. Not with the server jar.

**Comment by Starreactor** [comment]
![image](https://user-images.githubusercontent.com/12199521/191386477-63ab7400-c4ca-47a5-bb0c-0710c2eb3eb8.png)

**Comment by PugLyf** [comment]
That is what happens when start.ps1 is run. It doesn't start the server.

**Comment by chorbintime** [comment]
You need Java 17 for versions newer than 1.17.
You have Java 8. 
Download Java 17 off Google.

**Comment by PugLyf** [comment]
It is the 1.16.5 version, not 1.17. Is that the case for the version I am using as well?

**Comment by DigitalAegis001** [comment]
As this is the minecraft 1.16 i uninstalled JDK 17 while leaving Java 8 which allowed the server to launch properly

**Comment by chorbintime** [comment]
> It is the 1.16.5 version, not 1.17. Is that the case for the version I am using as well?

If you are on 1.16.5, you need Java 8.

**Comment by jlgoku450** [comment]
has anyone solved the issue?

**Comment by chorbintime** [comment]
It's not a modpack issue. This error means you don't have the same modpack installed as the server. It never will mean anything else.
