### ISSUE TITLE
Toms Storage Mod causes extreme lags

### ISSUE THREAD

**Issue by julian-piehl** [LunaPixelStudios/Better-MC#747]
### Describe the Bug

The larger the system, the more power is required.
According to spark, the mod alone uses 50% CPU of the whole server.

It seems like the Fabric method StorageUtil.move() is the reason.
The more boxes are connected, the more CPU is required. Especially if the chests are full of items.

Although the mod is quite cool, it should get replaced against another.

https://github.com/tom5454/Toms-Storage/issues/150

### Reproduction Steps

1. Create a storage system
2. Add more chests and cables
3. Put more items into the system
4. The server gets slower and slower

### Screenshots and Videos

With Tom Storage in use:
![image](https://user-images.githubusercontent.com/32363424/191123197-79fa7b8e-9508-4ccb-bd13-2dcaab2b6c8b.png)

Without Toms Storage in use:
![image](https://user-images.githubusercontent.com/32363424/191123264-bc87a65a-bc75-4656-b840-b3de6e91dfcc.png)

High thread usage:
![image](https://user-images.githubusercontent.com/32363424/191123325-b0c8423b-659a-44b7-9c98-3a5fb2e76a84.png)

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v5

### Other Mods

- Simpe Voice Chat

**Comment by chorbintime** [comment]
You should report this on the page for Tom's Simple Storage.
