### ISSUE TITLE
BUG: When getting killed by a Vindicator

### ISSUE THREAD

**Issue by Samplesito** [LunaPixelStudios/Better-MC#750]
![image](https://user-images.githubusercontent.com/113877491/191377203-e641819e-2ef3-4dbc-bfee-b5cd0d0d402f.png)
When getting killed by Vindicators, you get kicked and are not able to join the server, looks like your in game name get bugged.

![image](https://user-images.githubusercontent.com/113877491/191377220-16562497-3f91-4267-a648-5299069f9cde.png)

We reproduced it two times and the only way to fix it was changing accounts...
Exactly reproduced when killed via a Raid to a Village 
![image](https://user-images.githubusercontent.com/113877491/191379646-af18b7e2-bf2f-4843-a6e1-15a094e3067c.png)

**Comment by chorbintime** [comment]
I am unable to reproduce this, considering you labeled this issue as.. 1.15.

We host no 1.15 modpacks.
