### ISSUE TITLE
Villager won't get a job in Server, But will in Single player.

### ISSUE THREAD

**Issue by LieutenantDan96** [LunaPixelStudios/Better-MC#751]
### Describe the Bug

As the title says I am able to do the exact same steps in creating an area with regular blocks in the single player world to trab the villager, spawn him in, and then give him a job. In single player it works just fine I can give him any job block and he grabs it immediately. I have tried changing the times of days and still works just fine. But in the server i did the exact same thing I did in single player and none of the villagers will take the jobs. I dont know whats causing this. Im using bisect hosting for the server carrier and they refered me here to see if anyone else was having the same issue and I see only one person but they didnt get it fixed at all. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

No

**Comment by chorbintime** [comment]
Are there other career blocks nearby? 

This is likely an issue on your side. Since nobody else has reported this & this modpack hasn't been changed for months iirc.
