### ISSUE TITLE
Hoppers Breaking on both Server and Singleplayer

### ISSUE THREAD

**Issue by casuldud** [LunaPixelStudios/Better-MC#752]
### Describe the Bug

We updated the server to v5, saw that iron was falling out of the iron farm, and turned out that the hopper was not collecting the items as it should be. With some testing using a simple furnace system and trying it out in single-player, I found out that if there are more than 4 hoppers that have items in them and are filtering/waiting for their turn, the other one with items will not flow through as intended. Is this a bug or is this configurable in one of the new mods that were added in v5?

### Reproduction Steps

1. Updated server to v5
2. Played the game
3. Found the hoppers not collecting items
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/114123031/191643445-18846086-1546-424b-9c2b-3ef41eaa86fb.png) Here is the design I used

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v5

### Optifine

No

### Other Mods

none

**Comment by chorbintime** [comment]
Furnaces can not input items diagonally. I recreated the design, and the hoppers/chests vertical to the furnaces worked fine. I'm pretty sure this is a Vanilla feature.

Could not recreate the issue with items "falling out".
