### ISSUE TITLE
Backpack overwritten in Creative

### ISSUE THREAD

**Issue by HijabiGamer** [LunaPixelStudios/Better-MC#754]
### Describe the Bug

Backpacks (at least the iron one) get replaced by other items when inventory fills. Backpack and all its contents are overwritten and deleted. This has happened twice today.

### Reproduction Steps

1. Creative mode
2. Iron backpack in inventory (not on back slot), filled with items or empty
3. Acquire items
4. Fill all inventory slots with at least one unique item
5. Backpack should cease to exist when automatically picking up more items

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC 1.18.2 v13

### Optifine

No

### Other Mods

Bad Mobs
Farmer's Respite
More Babies
Ender Mail
Get in the Bucket
Brewin' n' Chewin'
Cultural Delights
Fast Leaf Decay
Vein Mining
(some of these may have already been included in the pack)

**Comment by chorbintime** [comment]
I'm not too sure what you mean with the reproduction steps? 

I threw about 100 unique items onto the ground in survival mode, and when I picked them up it went into my inventory. Nothing "automatically" went into the backpack? Nothing deleted, either. 

If you're unable to reproduce this in Survival mode, I don't really see the issue.

**Comment by HijabiGamer** [comment]
> I'm not too sure what you mean with the reproduction steps?
> 
> I threw about 100 unique items onto the ground in survival mode, and when I picked them up it went into my inventory. Nothing "automatically" went into the backpack? Nothing deleted, either.
> 
> If you're unable to reproduce this in Survival mode, I don't really see the issue.

Nothing automatically goes in the backpack. The backpack just disappears. It is an issue because everything I collected from a huge structure vanished when I was testing things in creative. Lots of work and time gone.

**Comment by chorbintime** [comment]
I am unable to replicate this and I think you should have a level of caution in creative anyway.
