### ISSUE TITLE
I can't host server 1.16.5

### ISSUE THREAD

**Issue by DustyFun2425** [LunaPixelStudios/Better-MC#755]
### Describe the Bug

I don't understand how host server on new version of modpack

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/102427867/191815947-162e6b0f-635e-4e41-bac7-acebaa96bfb5.png)
![image](https://user-images.githubusercontent.com/102427867/191815976-30a4e709-7547-49f7-babf-b227c7d74556.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

57.5

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
The "how to run start.ps1" tells you how to run the server.

Without any actual details on what issue you are facing, I am unable to assist you further.
