### ISSUE TITLE
visual glitch- breaking blocks causes flash of x-ray

### ISSUE THREAD

**Issue by mikdnonadls** [LunaPixelStudios/Better-MC#757]
### Describe the Bug

when in the pause menu, there will occasionally be flashes of blocks in the distance becoming transparent and exposing the caves below. when breaking or placing blocks, the same thing happens

https://user-images.githubusercontent.com/114306100/192110300-01b9deb9-d59e-4718-a9ff-47864055c9a9.mp4

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v6

### Optifine

No

**Comment by chorbintime** [comment]
This is an issue on your side.

Have you modified the modpack in any way? any setting changes?
