### ISSUE TITLE
Unable to use shaders

### ISSUE THREAD

**Issue by Gyrhub** [LunaPixelStudios/Better-MC#758]
### Describe the Bug

I am unable to use shaders (as in there is no shader option in the menu available) with this mod pack. Fabric works fine without it. Latest version of fabric is installed. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
You need to put the shaderpack ZIP in the shaderpacks folder.
