### ISSUE TITLE
Vein Mining does not work

### ISSUE THREAD

**Issue by Salah2309** [LunaPixelStudios/Better-MC#759]
### Describe the Bug

Recently updated from v58.5 to v59, pickaxe that had vein mining still read the enchantment however the enchantment doesn't actually apply. while using a pickaxe with enchantment (enchantment was added during v58.5) it mines one block at a time.
All other enchantment seem to be working fine

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V1.16.5 (1)

### Optifine

No

### Other Mods

Only modpack: Better MC [FORGE] 1.16.5 v59

**Comment by chorbintime** [comment]
You have to hold the ~ key to activate vein miner in the latest update. This was mentioned in the changelog.
