### ISSUE TITLE
Nether wont load (only swirling)

### ISSUE THREAD

**Issue by Mindcore** [LunaPixelStudios/Better-MC#760]
### Describe the Bug

I started hosting a server over Bisecthosting with 5Gb and when standing in the Nether Portal it only swirls and nothing is happening.
It works in single Player tho
allow Nether is enabled
I got suggested deleting the DIM-1 Folder wich i did, didnt help tho

### Reproduction Steps

1. join server
2. try to enter nether
3. swirling continues
...

### Screenshots and Videos

![Screenshot (292)](https://user-images.githubusercontent.com/66170503/192117576-2b7cc2e8-9b70-4980-97fa-2c396f0979b2.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v 5.0

### Optifine

No

**Comment by chorbintime** [comment]
Can you try deleting the NetherPortalFix mod?

**Comment by Mindcore** [comment]
Did that and sadly nothing changed.
We tried on a new world and it worked tho, so probably is just this world file
