### ISSUE TITLE
Having a quiver in your inventory causes some model issues

### ISSUE THREAD

**Issue by Demizilla** [LunaPixelStudios/Better-MC#761]
### Describe the Bug

Wearing the backpacked backpack, or other additions to your player model such as the 'Enchant With Mob' enchantment glint, with a quiver in your inventory, causes those features to be offset weirdly. holding the quiver makes everything be in the correct place. does not change armor models.

### Reproduction Steps

1.Wear a backpack or anything attached to your player model
2.put a quiver in your inventory

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/101365050/192119160-79683dbd-97c1-471e-9bb5-58c1ab4c1356.png)
![image](https://user-images.githubusercontent.com/101365050/192119326-01e92005-d385-491b-b956-fe441deabe6e.png)
![image](https://user-images.githubusercontent.com/101365050/192119391-c8d17235-6a12-42e9-b569-b0176511f979.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc 1.19.2 v5

### Optifine

No

**Comment by chorbintime** [comment]
This isn't something we can fix, or that individual mod creators really need to fix either. You could maybe report this on the Enchant With Mob github but I honestly don't see this as a significant problem.
