### ISSUE TITLE
So many versions for seemingly little to no reason.

### ISSUE THREAD

**Issue by faithfullunaa** [LunaPixelStudios/Better-MC#762]
There are so many of the same modpacks and I can't seem to find any major differences apart from a couple mods.
Can someone clarify what the author is thinking when they made a million different modpacks that all have naming conventions that are confusing as hell?

Examples of all the modpacks with basically the same name (FORGE VERSIONS ONLY, THERE ARE MORE FABRIC VERSIONS TOO -_-)
https://www.curseforge.com/minecraft/modpacks/better-mc-new
https://www.curseforge.com/minecraft/modpacks/better-mc-modpack
https://www.curseforge.com/minecraft/modpacks/better-mc-forge

**Comment by chorbintime** [comment]
You're clearly new to the Minecraft modding scene. 

People play on different versions of different modloaders for different reasons.

Fabric modpacks have better performance, more stability, and generally better mods. Our 1.19.2 Fabric modpacks have more mods than the 1.19.2 Forge modpacks.

Forge modpacks have certain mods which aren't on Fabric, and versions like 1.16 or 1.18 have features you won't find elsewhere. All of these modpacks will give you a different experience. 

![image](https://user-images.githubusercontent.com/112908845/192184310-bcfc5632-0c07-4a19-8b82-39b699ffbb02.png)
