### ISSUE TITLE
Crashes when enter snow biome

### ISSUE THREAD

**Issue by Daniel199438** [LunaPixelStudios/Better-MC#763]
### Describe the Bug

When entering snow biome, the game crashes with following crash log:
[crash-2022-09-25_16.57.20-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/9641070/crash-2022-09-25_16.57.20-client.txt)

https://github.com/Snownee/SnowRealMagic/issues/228

This issue is mentioned there too, but maybe there is a temporary solution like disabling SnowRealMagic Mod

### Reproduction Steps

1. Create a new world
2. Run towards a snow biome
3. Run around until it crashes
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc 1.19.2 v5

### Optifine

No

**Comment by chorbintime** [comment]
Not much we can do. Mod will be removed if issue effects more people. Thanks for the report.
