### ISSUE TITLE
my game keeps crashing 

### ISSUE THREAD

**Issue by thatonecarl** [LunaPixelStudios/Better-MC#764]
### Describe the Bug

what are the memory requirements, and how much is too much 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

0.14.9

### Optifine

No

**Comment by chorbintime** [comment]
Please do not ask things like this on Github. That's not what Github is for. 

The minimum memory is about 5 gigabytes.
