### ISSUE TITLE
I cant join a friends server after update

### ISSUE THREAD

**Issue by Jurtile** [LunaPixelStudios/Better-MC#766]
### Describe the Bug

Before Better Minecraft 1.19.2 v6 was released I could join my friends server fine but I update to v6 and its giving me an error

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Minecraft Screenshot 2022 09 27 - 01 17 52 97](https://user-images.githubusercontent.com/114463663/192438148-d525b409-2671-4552-9720-54d0a67f9f41.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v6

### Optifine

No

**Comment by ZxfoxZx** [comment]
I have the same issue, but in this case its my own server but I didn't even update it..
1.19.2 Fabric v6.5 Medieval Mc

**Comment by ZxfoxZx** [comment]
![MMMPBug](https://user-images.githubusercontent.com/69542986/192725212-862d7c87-4ded-4ef9-a41c-d853c074a72e.PNG)

**Comment by chorbintime** [comment]
> ### Describe the Bug
> Before Better Minecraft 1.19.2 v6 was released I could join my friends server fine but I update to v6 and its giving me an error
> 
> ### Reproduction Steps
> 
> ...
> 
> ### Screenshots and Videos
> ![Minecraft Screenshot 2022 09 27 - 01 17 52 97](https://user-images.githubusercontent.com/114463663/192438148-d525b409-2671-4552-9720-54d0a67f9f41.png)
> 
> ### Crash Report or Log
> _No response_
> 
> ### Operating System
> Windows 11
> 
> ### Minecraft Version
> 1.19
> 
> ### Modloader
> Fabric
> 
> ### Modpack Version
> v6
> 
> ### Optifine
> No
> 
> ### Other Mods
> _No response_



> ![MMMPBug](https://user-images.githubusercontent.com/69542986/192725212-862d7c87-4ded-4ef9-a41c-d853c074a72e.PNG)

Have a server admin /kill you as soon as you join the server. Will likely fix it. Avoid waystones for the time being.
