### ISSUE TITLE
Potential Memory Spike issue

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-MC#767]
### Describe the Bug

Im not too sure if its an issue but since i booted up my game suddenly the memory use went from 25% to around 50%-ish percent and i just created a new world for testing, being that i didnt like the removal of "This Rocks!" and "Biome Makeover" but i knew its better that way. Regardless, usually when my game boots up it doesnt spike all that much, usually from 25% to 32%-ish. Is this a bug?

### Reproduction Steps

1. boot up ur game
2. create a new world
3. boom entire computer lags like crazy
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v17

### Optifine

No

**Comment by chorbintime** [comment]
I uhh.. don't see the issue? You can join our Discord and follow the performance guide pinned in #general to help with lag but 32% memory usage is like, really good lol.

**Comment by FevilGitHub** [comment]
it is a good percentage! (in fact i usually tone it down for a better performance when im off of the game) but seeing it now spike to 50% started to concern me.
