### ISSUE TITLE
Visual bug (big yikes tho, like unplayable big yikes)

### ISSUE THREAD

**Issue by PotatoPcUtilizer** [LunaPixelStudios/Better-MC#768]
### Describe the Bug

water is invisible, the tops of blocks are invisible, 50ish% of all block sides are invisible

### Reproduction Steps

1.no clue how this occured
2.i just installed better minecraft (plus) 1.16.5 (v40 according to the icon thingy) and launched it
3. dont know what else to put here
...everything was invisible to the point i couldnt get wood

no clue

### Screenshots and Videos

my pc takes to long to load up minecraft so if there isnt a known fix to this, then i'll try to get a screenshot

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

according to the thing on the modpacks icon, v40

### Optifine

No

**Comment by chorbintime** [comment]
I can't help that well without a screenshot. This is probably an issue with your PC. Update your drivers via Device Manager in windows and follow performance guide in our Discord, pinned in #general.
