### ISSUE TITLE
server doesn't unload chunks

### ISSUE THREAD

**Issue by khris190** [LunaPixelStudios/Better-MC#769]
### Describe the Bug

server doesn't seem to unload chunks and crashed after a while of exploration

my args are :
java -Xms1G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Duser.timezone="Europe/Warsaw" -jar forge-wrapper.jar nogui

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://logs.panel.gg/2daa368ba6652cbccdd345f10111dc86

### Operating System

some docker img on winternode

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

R Server Pack PLUS 1.18 v14 HF

### Optifine

No

**Comment by chorbintime** [comment]
Can you try preloading chunks using the Chunk Pregenerator mod?

**Comment by khris190** [comment]
> Can you try preloading chunks using the Chunk Pregenerator mod? 

How would that help with chunks not being freed from memory?

**Comment by khris190** [comment]
Maybe i didn't write the problem well enough
My server crashes from OOM exception because it doesn't unload chunks so every time i move to "new" pregenerated or new chunk it doesn't matter it takes memory untill restart or crash

**Comment by chorbintime** [comment]
Could you send a spark profiler? Run this command ingame:
/spark profiler --interval 100

**Comment by khris190** [comment]
> Could you send a spark profiler? Run this command ingame: /spark profiler --interval 100

https://spark.lucko.me/6CpegYwsNq
during this the server went from 5GB of usage to about 6.4 GB

**Comment by khris190** [comment]
![unknown](https://user-images.githubusercontent.com/29352561/193369198-374be8d5-c4f5-4eca-9e88-c40542a87a2f.png)
ngl, something is really wrong but it might be a problem with hosting i'll try to resolve it with them if noone has any idea

**Comment by chorbintime** [comment]
This is likely to do with your server host.
