### ISSUE TITLE
Server failed to start

### ISSUE THREAD

**Issue by IamWife** [LunaPixelStudios/Better-MC#770]
### Describe the Bug

When trying to launch my Better MC server pack for fabric 1.19.2, Everything loads up like normal until it stops with a 'Failed to start the minecraft server', then a load of waffle i don't understand. I added a few mods, which were all fabric and they worked on the server yesterday and I havent touched it since. I was recommended to try just install a new server file (without new mods) and move the world folder over but once i did that I still got the issue so that might shorten it down to something within the world file. I will link below the text that is sent once the sever fails to start (no crash report).

### Reproduction Steps

1.Right click and launch PowerShell server
2. Type 'Yes'
3.Wait for it to load, then it fails.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/114769204/193329760-ae79b6a3-4491-44d8-b056-34ee40c01c07.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC V6

### Optifine

I used Optifine

### Other Mods

-Better animals plus
-Capybara
-Croptopia
-Enhanced Celestials 
-Gobber 2
-Immersive armour
-mcda
-mcdar
-mcdw
-mcsa
-Plushie Mod
-Sky Villages
-Toms Storage
-Weapon Master
![image](https://user-images.githubusercontent.com/114769204/193330736-0edbcfd1-fd25-4e8a-ae4c-f8b4192b773c.png)

**Comment by chorbintime** [comment]
1) Better Animals Plus includes the Capybara mod. This very well could be what's causing this crash, as it's explicitly stated on the Capybara mod page that they both occupy the same IDs.
2) You tagged this post as Optifine. Do not use Optifine.
3) Tom's Storage is already included in the modpack.
4) The "Not Enough Data Available" means something in configs isn't working. The 3 issues I mentioned above could all be causing this.
