### ISSUE TITLE
weird bug 

### ISSUE THREAD

**Issue by oldnetro** [LunaPixelStudios/Better-MC#771]
### Describe the Bug

hi my name is oldnetro. in game at least and i am having an issue i started a new game but i fell into a state where i have constant slowness i keep dyeing due to starvation i don't know if it is a mod related issue or a Minecraft one. thank you in advance 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

better minecraft 

### Optifine

No

### Other Mods

no

**Comment by chorbintime** [comment]
What were you doing when you got the slowness? Can you give a video example?

**Comment by oldnetro** [comment]
Never mind figured it had to do with the graves.
