### ISSUE TITLE
Modpack randomly reverting to Vanilla MC

### ISSUE THREAD

**Issue by CotardsSolution** [LunaPixelStudios/Better-MC#772]
### Describe the Bug

Sometimes when I play Better MC and I start up the modpack, the loading screen displays just fine, but whenever it finished loading up, the game starts at the options menu, and whenever you close it, the menu screen is that of Vanilla Minecraft, checking the mods list would reveal that all mods are disabled, and the game would play the same as Vanilla MC. Redownloading & Repairing the installation will not fix the bug.

### Reproduction Steps

1. Experience a game crash, in my case, by Alt + Tabbing out while a world is loading
2. Restart the modpack
3. Wait for the game to load
4. Bug successfully recreated

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v17

### Optifine

No

**Comment by chorbintime** [comment]
What launcher are you using?
