### ISSUE TITLE
[Server pack for v7.5] Everyone gets kicked out after de-opping a server operator

### ISSUE THREAD

**Issue by TheCSDev** [LunaPixelStudios/Better-MC#774]
### Describe the Bug

When de-opping a server operator, everyone on the server gets kicked out with the message `You are not whitelisted on the server` even tho whitelists have nothing to do with de-opping an operator. (this happened to me whenever i temporarily opped and then de-opped myself).

### Reproduction Steps

1. Op someone `/op [player_name]`
2. De-op the same person `/deop [player_name]`
3. Everyone gets kicked (I haven't tested if whitelisted players get kicked)

### Crash Report or Log

N/A

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [Fabric] - v7.5

### Optifine

No

### Other Mods

I do not know what mods (if any) are causing this bug.

**Comment by chorbintime** [comment]
I have no idea what would be causing this, and it doesn't seem like that big of an issue, since players can manually be added to both the opped players txt and the whitelist txt. If more people report this, I will look into it further. Thank you for the report.
