### ISSUE TITLE
Error on taking damage

### ISSUE THREAD

**Issue by johnycraft** [LunaPixelStudios/Better-MC#775]
### Describe the Bug

Ok so every time i take damage even if it is half a heart of fall damage my game kicks me of my world and shows this error here "Internal Exception: java.lang.NoSuchMethodError: 'net.minecraft.class_1297 net.minecraft.class_1657.methond_44329()' " how does one fix this? any help would be great thank you

### Reproduction Steps

1. Take Damage

### Screenshots and Videos

![Minecraft Error](https://user-images.githubusercontent.com/86728726/193626855-81112b52-0fdc-4dd3-a995-87e7a0c0b20b.PNG)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v7.5

### Optifine

No

**Comment by chorbintime** [comment]
What launcher are you using?

Have you modified the modpack in any way?

Do other players experience this?

**Comment by johnycraft** [comment]
First, i am using Curseforge through Overwolf.

Second, i added the first person mod and the gender mod and they don't do it i believe since never do anything with damage from what i know.

Third, i am playing on a singleplayer world by myself.

so yeah again i am unsure what is going on any help would be great thank you.

**Comment by chorbintime** [comment]
Does the issue persist with the added mods removed?
