### ISSUE TITLE
Enchanted entities getting invisible

### ISSUE THREAD

**Issue by dandark05** [LunaPixelStudios/Better-MC#776]
### Describe the Bug

Mobs/entities using enchanted armor are invisible as the screenshot shows. I'm not using any other mods or resource packs. Just the modpack alone.

### Reproduction Steps

1. Just find a mob using enchanted armor during day or night.
2.
3.
...

### Screenshots and Videos

![2022-10-03_13 10 47](https://user-images.githubusercontent.com/114941379/193627998-be246c0e-660c-4f0c-8e65-1b872c182762.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v59.5

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
This just happens with skeletons in this structure. Likely intended
