### ISSUE TITLE
Hummingbird Rendering Crash?

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-MC#778]
### Describe the Bug

Hey i was randomly playing on my world when my game suddenly crashed, but didnt display the usual minecraft launcher you usually use before booting up Better MC after the crash. A log was created upon further examination and from what i could tell on there, it seemed that a Hummingbird had failed to render and caused the entire world to crash. This could potentially be a problem later down the line.

### Reproduction Steps

Unsure. I believe i had too many Hummingbirds in my world idk

### Crash Report or Log

https://pastebin.com/kx0cYazF

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v17

### Optifine

No

**Comment by FevilGitHub** [comment]
Upon further examination this is caused by literally any hummingbird. This is going to be an issue going forward for those who enjoy the effects of hummingbirds like me :c

**Comment by chorbintime** [comment]
Report on Alex's Mobs github. It seems like the game is trying to render a Curios item on the bird.
