### ISSUE TITLE
Players cant rejoin after using maps

### ISSUE THREAD

**Issue by MemorialMocha** [LunaPixelStudios/Better-MC#779]
### Describe the Bug

Players cant rejoin my server after using maps

### Reproduction Steps

1.Used a map on the server
2. PLayer crashes
3. Downloaded the latest log
...

### Screenshots and Videos

![LOGAN ERROR](https://user-images.githubusercontent.com/115062741/193991564-a9d5b2bf-eac8-4ac4-868b-6073f728791a.jpg)

### Crash Report or Log

https://pastebin.com/gNezeRRg and https://pastebin.com/duufF1yk

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

7.5

### Optifine

No

**Comment by chorbintime** [comment]
Both of those logs are cut off about halfway through. Please post the full log on mclo.gs
