### ISSUE TITLE
mouse click issu

### ISSUE THREAD

**Issue by KidDeath888** [LunaPixelStudios/Better-MC#780]
### Describe the Bug

Okay I Don't know if this is a bug but it happens in any world I'm in & I  don't know how to fix it okay if I want use my inventory instead of draging my suff where i want like you usually do it just insta does it same well using a crafting table so i can't really use anything properly it's very anoyying can you please help

### Reproduction Steps

1.
2.
3.
...

### Operating System

windiow 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft

### Optifine

I used Optifine

**Comment by FevilGitHub** [comment]
This is because the settings for shift lock was stuck. to turn it off go to settings and put in a random keybind for it and press it in the inv. it should fix the issue (reset the keybind afterward so it doesnt happen). i aint no dev but i had this happen to me once so this should fix it.
