### ISSUE TITLE
Can't rejoin single player world after game has been updated.

### ISSUE THREAD

**Issue by randomperson12345789** [LunaPixelStudios/Better-MC#781]
### Describe the Bug

everytime I try and rejoin my single player world it just says reading world data, and then stays like that for a few seconds and then goes to a loading scree, but there are no words. My world was working perfectly fine, but now that there has been an update it doesn't.

### Reproduction Steps

1.no response
2.
3.
...

### Screenshots and Videos

no response

### Crash Report or Log

no response

### Operating System

no respone

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

no respone

### Optifine

No

### Other Mods

no other mods

**Comment by chorbintime** [comment]
Does this issue persist on GDLauncher? You can transfer your save.

**Comment by xSHXRKIEx** [comment]
also did what previous version did you update from?
