### ISSUE TITLE
void core kill glitch

### ISSUE THREAD

**Issue by dybber10** [LunaPixelStudios/Better-MC#782]
### Describe the Bug

a guy rtp to me and killed me in my home even tho i had pvp disabled
he also took my VERY good sword that i payed 15k for

his name was domonster

please see this and help me

-Dybber10

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better Mc

### Optifine

No

**Comment by chorbintime** [comment]
We do not have any control over any servers. All servers are community hosted.
