### ISSUE TITLE
1.19.2 v6 Clay Golem's

### ISSUE THREAD

**Issue by courcess** [LunaPixelStudios/Better-MC#784]
Ever since the update, the village I've been working in has become overcrowded with clay golems and it's causing my server to lag out. When it was iron golems I only had a handful, but with clay golems there is more than 40 of them, outnumbering the amount of villagers I have.

![Screenshot 2022-10-06 213254](https://user-images.githubusercontent.com/115201607/194456369-6c0b78ed-2ee4-4deb-bb49-cd74e97d1904.png)

**Comment by xSHXRKIEx** [comment]
In the Takesapillage, set the replace iron golems to false
