### ISSUE TITLE
BUG keeps me freezed when I die (MedievalMinecraft1.19.2)

### ISSUE THREAD

**Issue by pizzadekeslley** [LunaPixelStudios/Better-MC#785]
### Describe the Bug

When I Die i can see my body on the ground but I'm not able to move or break any block around me 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-10-07_03 22 28](https://user-images.githubusercontent.com/115210314/194481259-7b314cf0-602e-4cbf-87bb-f081d0c62e08.png)
![2022-10-07_03 21 27](https://user-images.githubusercontent.com/115210314/194481263-60e44f1f-07d0-4a36-a513-4e1cc118069f.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

MedievalMinecraft 1.19.12

### Optifine

No

**Comment by xSHXRKIEx** [comment]
are you in hardcore?

**Comment by pizzadekeslley** [comment]
> 

No, normal game, but the game mode its not the problem, its more like a annoying bug that glitches my player everytime I die. I tried to remove the Corpse mod but still the same.

**Comment by pizzadekeslley** [comment]
When I try to teleport myself to some point of the map appears the message "Cannot teleport when dead" Its like my character is dead or something, I cant move, break any block or go somewhere

**Comment by pizzadekeslley** [comment]
The bug itself was caused by an bug in Wither Wraith Origins class, more specific two mods (Origins and ibarn's quartet addon)
