### ISSUE TITLE
Enchantment not working on ultimerite bow

### ISSUE THREAD

**Issue by JinyuXu** [LunaPixelStudios/Better-MC#786]
### Describe the Bug

power/flame/punch enchantment not working on ultimerite bow. Worked on previous upgraded netherite bow.

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC 1.19.2 V5

### Optifine

No

**Comment by chorbintime** [comment]
If the Upgraded Netherite mods have no update available, or the issue persists after update, report on Ultimerite's github.
