### ISSUE TITLE
Crashing on launch [Fabric 1.19.2] V7 (Still occurs in V7.5)

### ISSUE THREAD

**Issue by Oliver-Williams** [LunaPixelStudios/Better-MC#789]
### Describe the Bug

Game is crashing on launch, installed through the Curseforge launcher. Tried reinstalling the pack, Curseforge, normal Minecraft on the PC, Java (Even though a version is bundled with the pack). Game does not crash with normal Minecraft or other mod packs.

Crash occurs on line 1664 and it seems to be an issue with geckolib3 as found on line 1682 of the attached log. It doesn't seem to crash, just hang after this point forever. Longest left here was a couple of hours, never progresses.

PC specs:
- x86-64 Windows 10, fully up-to-date
- Thinkpad X230
- 8GB of RAM (Allocated 7GB)
- 500GB 850 EVO

### Reproduction Steps

- Install through Curseforge
- Launch

### Crash Report or Log

https://pastebin.com/7N6Qmj0Q

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V7

### Optifine

No

**Comment by chorbintime** [comment]
Does this issue persist on GDLauncher?

Does a crash report generate?
