### ISSUE TITLE
Unable to connect to servers due to issue.

### ISSUE THREAD

**Issue by XXXenz** [LunaPixelStudios/Better-MC#790]
### Describe the Bug

Was playing for about 3 hours when I got kicked from my cousins server and was prompted with a connection lost issue. I tried re-downloading the ModPack, disabling my firewall, using a VPN but nothing has worked. Any ideas?
![Minecraft Screenshot 2022 10 09 - 17 22 01 44](https://user-images.githubusercontent.com/115435977/194787774-1c165514-0a49-48f7-bca1-b84b957c107b.png)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
Temporary solution is to /kill the player or delete there player data
