### ISSUE TITLE
Some chinese looking mob tower generating overloading amounts of entities that will crash even my singleplayer world

### ISSUE THREAD

**Issue by s0l1tary** [LunaPixelStudios/Better-MC#791]
### Describe the Bug

I'm not sure what exactly is causing it, i have pree decent pc with a ryzen 5 5600, rtx 3070 and 16gm ram.
When i went above the first level my RAM usage started spiking and the game just lags and eventually crashes. I have increased my parameters of -Xmx to 6g, 8g and 10g respectively and im still trying to get out of it and hope my hardcore world doesnt corrupt

### Reproduction Steps

1. Find the chinese looking mob tower
2. Go up 1-2 floors
3. RAM usage will increase tremendously and will crash mc
...

### Screenshots and Videos

![2022-10-10_21 41 54](https://user-images.githubusercontent.com/59859439/194881992-02ee55c7-8a51-4a9a-ae15-2cac51ce4def.png)

### Crash Report or Log

No

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better-Mc Forge v6

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
Does the issue persist with shaders off? Your GPU is at 100% which is probably due to high shader settings.

**Comment by s0l1tary** [comment]
I haven’t tried it without shaders sadly , but my gpu is around that range
all the time, I mostly optimised it for my high settings already, so far
every area I visited ran find except this one.

**Comment by xSHXRKIEx** [comment]
Can you run a /spark profiler --timeout 30 at the structure and send us the link?

**Comment by s0l1tary** [comment]
I’m not sure how to do that, but I have been avoiding that place ever
since, however I went exploring around and found some permafrost temple
with armoured skeletons i visited and it was near the infested tower, after
going in abit my game started lagging and straight up just froze again in a
matter of seconds , and this time with shaders off

**Comment by s0l1tary** [comment]
And oh is that a command you’re asking me to run?

**Comment by chorbintime** [comment]
Yes. Run the command please.

**Comment by s0l1tary** [comment]
Do I do it near the tower before it crashes or smth?

**Comment by chorbintime** [comment]
Yes.

**Comment by s0l1tary** [comment]
![2022-10-17_02 46 52](https://user-images.githubusercontent.com/59859439/196053110-4ea5c3c8-d1b9-4e3e-a7a0-be593b01d327.png)
![2022-10-17_02 48 08](https://user-images.githubusercontent.com/59859439/196053113-4fc0206e-7ed8-4acb-975a-d1ee2b2f8295.png)
![2022-10-17_02 56 28](https://user-images.githubusercontent.com/59859439/196053114-44f71275-6d3d-452c-af3d-40ed853bd941.png)
I have been avoiding that place ever since cos i didnt wanna risk losing my hardcore world, but surprisingly, I experienced the same issue when raiding the skeleton corsair. At first everything was smooth, I was clearing the bottom of the ship, upward until i reached the top where there were a lot. It started lagging similar with the previous structure i visited with a high RAM usage. I forced closed the game cos its pree much unplayable and gave it a good 10gb ram this time. 

However, despite the ram usage not actually hitting the max this time, stuff were mostly frozen , like i'm 999 ping in game with my resource usage not overwhelmingly concerning at times. I eventually wiped out the top of the ship and actually realized the ocean had a lot of them and its probably why its happening ? Fingers crossed, cos it isnt really alot but i really dont know why its happening, I tried running the command as you instructed but the game just goes to an unplayable state after a few seconds of loading into my world. 

The first image and second imagfe (i know its a screenshot and you can't actually see them moving) depicts me moving but every entity in that area has frozen as if im at 999 ping i could hit them, which maybe would register maybe like 5 mins later when i launch the game again but there is also no high GPU / ram usage as from the f3 stats. However, the third image shows that i eventually hit the intensive resource usage with the ram hitting up to 13gb. I dont know whats up, i have survived high entity counts like level 3 raids with alot of mobs shooting shit at me with no lag at all or a ton of silverfish spawning from the jungle temple but why are there certain areas that freeze my game?

**Comment by chorbintime** [comment]
I mean, you're not going to 'lose' your world because FTB Backups creates backups for you, but there could be a lot of reasons why this lag is happening. A spark profiler would help a lot with diagnosing this.
