### ISSUE TITLE
Bosses of Mass Destruction Crash

### ISSUE THREAD

**Issue by rayzuhl** [LunaPixelStudios/Better-MC#793]
### Describe the Bug

When summoning or loading in bosses from Bosses of Mass Destruction, the game immediately crashes. The game pauses for a second then closes.

Other mods are installed, but crash still occurs on a clean install of modpack.

### Reproduction Steps

1.Locate any boss structure
2. Use required items to spawn boss. Or walk close enough to boss (Void Lily)
3. Game crashes
...

### Crash Report or Log

https://pastebin.com/WhddgMMj

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v8

### Optifine

No

### Other Mods

Carrier
Chunky
malilib
minihud
MobCatcher
morevillagers
tradecycling

**Comment by xSHXRKIEx** [comment]
Thanks for the report, will update the modpack with a fix
