### ISSUE TITLE
exclude shaderpack screens from blur

### ISSUE THREAD

**Issue by yuri0r** [LunaPixelStudios/Better-MC#794]
that way you have a better time tweaking shaders as the game is clearly vissible in the background rather than blurred.

just add this line to the ` "blurExclusions": [...]` array in the `config/blur.json`
```
    "net.coderbot.iris.gui.screen.ShaderPackScreen"
```

comparsion below

blurry
![grafik](https://user-images.githubusercontent.com/9966894/195914890-3f35a914-ad00-478e-a612-d78ce38e348c.png)

clear:
![grafik](https://user-images.githubusercontent.com/9966894/195914693-bbcc9b76-2148-4388-a37f-6b9628b58f35.png)

**Comment by chorbintime** [comment]
Will be added in the next update, thanks for the feedback
