### ISSUE TITLE
mob lvl multiplier

### ISSUE THREAD

**Issue by BulCerClone** [LunaPixelStudios/Better-MC#795]
### Describe the Bug

so far I've only noticed it by wolfs but if you pick up a wolf and placed it again the level of the wolf gets multiplied. I then got killed by the wolf instantly

### Reproduction Steps

1. pick up the wolf
2. place the wolf
3. repeat
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v8.2

### Optifine

No

**Comment by chorbintime** [comment]
Known issue with RPGDifficulty mod, which is in Medieval MC, not Better MC
