### ISSUE TITLE
The run files arnt included in the latest 2 versions?

### ISSUE THREAD

**Issue by mylogicinu** [LunaPixelStudios/Better-MC#796]
### Describe the Bug

I cant find the run files in the latest two versions of the server pack. Im probably doing something wrong, no one else seems to have these problems. I have opened up many of the different versions, and only the latest 2 dont have run files.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Disable your antivirus

Don't use optifine, ever, for any reason
