### ISSUE TITLE
BOMD - Boss Of Mass Destruction Crash after starting a boss fight

### ISSUE THREAD

**Issue by JanPieterPan** [LunaPixelStudios/Better-MC#797]
### Describe the Bug

In BetterMC 1.19.2 Fabric:

I was playing with a friend on a server, after a while we started a boss from BOMD: Night Lich.
After 1 second of activating the boss fight our game crashes. After the crash i was looking in the console for what went wrong but there was no problem. So its in the game folder itself.

I hope this can be fixed asap, its a super dope modpack!!

### Reproduction Steps

1. Starting a world
2. Starting the boss fight
3. Game crashes

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v8

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Fixed in v8.5
