### ISSUE TITLE
Big Bertha

### ISSUE THREAD

**Issue by KoniSama** [LunaPixelStudios/Better-MC#798]
### Describe the Bug

When you pick up cows and put them somewhere their Lvl increases  in  very fast, i think quadtratically or something. I got my cow "Big Birtha" with a Lvl of 2147483633 and a health of 2147483648

### Reproduction Steps

1.Get a Cow with a level
2. Shift and r-click to take cow
3. Put Cow somewhere else with r-click
4. Return to 1.

### Screenshots and Videos

![BIgBertha](https://user-images.githubusercontent.com/115961789/196072972-6a32b6cf-b539-447a-b115-f840cd6b36bf.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v7

### Optifine

No

**Comment by KoniSama** [comment]
Uploading birth-of-bertha2_6WOAXZbT.mp4…

I hope this helps, took me long enough

**Comment by chorbintime** [comment]
1) You are not playing BMC. You are playing Medieval.
2) This is a known issue with the RPGDifficulty mod.
