### ISSUE TITLE
Wither Wraith Origin still bugged after death

### ISSUE THREAD

**Issue by gitFcked** [LunaPixelStudios/Better-MC#800]
### Describe the Bug

Once I die as a wither wraith I will respawn and I am unable to move, I can see my body and can even kill it. Relogging puts me in the death screen and it doesn't get fixed. (Not Hardcore mode)

### Reproduction Steps

1. Choose Wither Wraith Origin
2. Die
3. Respawn

### Screenshots and Videos

![2022-10-17_19 04 13](https://user-images.githubusercontent.com/91965096/196305747-99df0794-710f-437c-baf3-69dd8a52c507.png)
![2022-10-17_19 04 37](https://user-images.githubusercontent.com/91965096/196305755-009d8ff2-9791-48ab-8913-e90bfc9d75a9.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Medieval Minecraft v6.5

### Optifine

No

**Comment by chorbintime** [comment]
1) You're not playing BMC. You're playing Medieval.
2) There's not really anything we can do about this. It's an issue with whichever origin mod adds that origin. I would check if any of the origin mods have updates available, & if those updates don't fix this issue, find what mod adds the origin and report it on their github.
