### ISSUE TITLE
cant create ender dust

### ISSUE THREAD

**Issue by Mitchthemaker** [LunaPixelStudios/Better-MC#802]
### Describe the Bug

supposedly im able to use a smithing hammer on an anvil to create ender dust right?
i havent come across anything about that topic while googling the issue.
Am i doing something wrong/missing something?
cheers

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
1) This a known issue with the BetterEnd mod. We unfortunately can't do much about it.

2) Your game is not loading Optifine. Optifine is a forge mod.

Do not use Optifine in the future - it is not good & it hasn't been for years. It is incompatible with every modpack that doesn't state otherwise.
