### ISSUE TITLE
internal exception: io.netty.handler.codec.decoderexception: java.lang.indexoutofboundsexception:

### ISSUE THREAD

**Issue by iiDante76** [LunaPixelStudios/Better-MC#803]
### Describe the Bug

when i open the server that appear  what is the problem 
<img width="1280" alt="Minecraft Screenshot 2022 10 19 - 19 13 34 28" src="https://user-images.githubusercontent.com/116192809/196747709-acecfc47-fda8-42d6-a42d-be6b545e7ff7.png">

### Reproduction Steps

1.
2.
3.
...

### Operating System

win 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2 v8.5

### Optifine

No

**Comment by chorbintime** [comment]
"When i open the server" is not enough information.

What is being used to host the server?

Has the server worked before?

What launcher are you using?

Can others join?

**Comment by VuFlub** [comment]
Same exact thing happens on the forge 1.19.2 version. Able to play singleplayer but not multiplayer or even lan. 1.18.2 seems to work just fine I think it's a 1.19.2 forge issue.

**Comment by chorbintime** [comment]
> Same exact thing happens on the forge 1.19.2 version. Able to play singleplayer but not multiplayer or even lan. 1.18.2 seems to work just fine I think it's a 1.19.2 forge issue.

LAN is not supported, is very unstable, and is not intended to work. 
If you are getting this error on multiplayer, it means you are doing something wrong during server setup.

**Comment by Banasus** [comment]
> "When i open the server" is not enough information.
> 
> What is being used to host the server?
> 
> Has the server worked before?
> 
> What launcher are you using?
> 
> Can others join?

hey, i have the exact same problem with my server, can someone help me?
