### ISSUE TITLE
Deepslate Brick Vertical Slabs are unobtainable due to missing recipe file

### ISSUE THREAD

**Issue by LearningJavaWithMC** [LunaPixelStudios/Better-MC#804]
### Describe the Bug

BMC contains two mods that add deepslate, being Quark and Caves & Cliffs Backport. The only type of deepslate that naturally generates is from CaCB. The recipe for deepslate brick vertical slabs only exists through Quark (clicking on the CaCB variant in JEI doesn't give a recipe), but the Quark variant cannot use CaCB deepslate in it's crafting recipe. After digging through the CaCB JAR file I found there isn't a recipe file called `deepslate_brick_vertical_slab_from_deepslate_bricks_stonecutting.json` which would be the expected recipe file name (given the naming convention of other recipes like `deepslate_tile_vertical_slab_from_deepslate_tiles_stonecutting.json`

The fix is to add the following recipe files to the `/cavesandcliffs-1.16.5-7.2.0/data/cavesandcliffs/recipes/` folder in the JAR file

`deepslate_brick_vertical_slab_from_deepslate_bricks_stonecutting.json`
```
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "cavesandcliffs:deepslate_bricks"
  },
  "result": "cavesandcliffs:deepslate_brick_vertical_slab",
  "count": 2,
  "conditions": [
    {
      "type": "cavesandcliffs:quark_flag",
      "flag": "vertical_slabs"
    }
  ]
}
```

and `deepslate_brick_vertical_slab_from_cobbled_deepslate_stonecutting.json`
```
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "cavesandcliffs:cobbled_deepslate"
  },
  "result": "cavesandcliffs:deepslate_brick_vertical_slab",
  "count": 2,
  "conditions": [
    {
      "type": "cavesandcliffs:quark_flag",
      "flag": "vertical_slabs"
    }
  ]
}
```

and `deepslate_brick_vertical_slab_from_polished_deepslate_stonecutting.json`
```
{
  "type": "minecraft:stonecutting",
  "ingredient": {
    "item": "cavesandcliffs:polished_deepslate"
  },
  "result": "cavesandcliffs:deepslate_brick_vertical_slab",
  "count": 2,
  "conditions": [
    {
      "type": "cavesandcliffs:quark_flag",
      "flag": "vertical_slabs"
    }
  ]
}
```

### Reproduction Steps

N/A

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC v59.5

### Optifine

No

**Comment by chorbintime** [comment]
Will be fixed in a future update
