### ISSUE TITLE
Can't open crates from Go Fish mod

### ISSUE THREAD

**Issue by AphEX12** [LunaPixelStudios/Better-MC#806]
### Describe the Bug

I got a handful of crates from the _Go Fish_ mod: a handful of wooden and iron crates, 1 gold and 1 diamond. I can't open any of them by shift-clicking as the description says.

### Reproduction Steps

1. Go fishing
2. Get a crate
3. Try to open by shift-clicking as instructed
4. Crate does not open
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC v8.5

### Optifine

No

**Comment by chorbintime** [comment]
Report on Go Fish github if it exists
