### ISSUE TITLE
Dragon eggs aren't spawning

### ISSUE THREAD

**Issue by STEALTHIEST-11** [LunaPixelStudios/Better-MC#807]
### Describe the Bug

My friends and I have a server through BISECT Hosting and we can't find any dragon eggs in chests throughout the world, this is now our second server we've had that doesn't have eggs

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v17

### Optifine

No

**Comment by chorbintime** [comment]
I can assure you dragon eggs spawn. You're unlucky or looking in the wrong places.

**Comment by STEALTHIEST-11** [comment]
Have they become rarer to find? When I first played the modpack I was getting eggs left right and center. I've played on 2 of my servers and with 8 people searching for them with no luck

**Comment by chorbintime** [comment]
We haven't touched any loot tables.
