### ISSUE TITLE
missing sounds in game

### ISSUE THREAD

**Issue by Ixemius** [LunaPixelStudios/Better-MC#808]
### Describe the Bug

their is some missing sounds in the game, like when you heat or when you hit a mob, the footsteps. i don't know why

### Reproduction Steps

don't have steps to reproduce the bug it's just appear like that

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Medieval MC 1.19.2 v7

### Optifine

No

**Comment by chorbintime** [comment]
Reload textures
