### ISSUE TITLE
Vein Mining does not work.

### ISSUE THREAD

**Issue by CoreyWarren** [LunaPixelStudios/Better-MC#809]
### Describe the Bug

Vein mining works just as normal mining does--only one block at a time. This is for the latest Fabric v8.5 for Minecraft 1.19.2 (Better Minecraft)

### Reproduction Steps

1. Enchant Diamond Pickaxe with Vein Mining enchantment (after refreshing anvil enchantments some 5-15 times)
2. Use Diamond Pickaxe on a number of ore veins, including Coal, Iron, and Copper Ore Clusters.
3. The Ores break as normal (and NOT as entire Veins...).
4. Additionally, normal arrangements of blocks (cobblestone, stone, diorite, etc) do not seem to break in clusters either with the Vein Mining enchantment.
5. All other enchantments seem to work as intended (Fortune II, Efficiency III, Unbreaking III)
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v8.5

### Optifine

I used Optifine

**Comment by Deweyoxberg** [comment]
You need the Vein Mining enchantment on an applicable tool in order to use VeinMining.

**Comment by CoreyWarren** [comment]
> You need the Vein Mining enchantment on an applicable tool in order to use VeinMining.

![image](https://user-images.githubusercontent.com/46623610/197420352-0b0345e2-737a-4463-b334-dc86c51c5170.png)

It has it!

**Comment by CoreyWarren** [comment]
Doesn't work on shovel either, but the enchantment table recommended it to me several times.
![image](https://user-images.githubusercontent.com/46623610/197420892-a4ae4c42-08a4-411f-9fc3-18b62bec634e.png)
![image](https://user-images.githubusercontent.com/46623610/197420918-0b8230c3-00be-4f76-bc4d-c6cb97994c97.png)

**Comment by Kullnr** [comment]
Did you  set up the keybind you have to hold to use vein mining? The default keybind to activate vein mining on a tool with the enchantment is "~".

**Comment by CoreyWarren** [comment]
> Did you set up the keybind you have to hold to use vein mining? The default keybind to activate vein mining on a tool with the enchantment is "~".

Oh wow, that didn't use to be the case. (6 months ago on my last install) My apologies, I'll try it right now.

**Comment by CoreyWarren** [comment]
Can confirm, issue is I need to hold tilde (`/~) key to get vein mining to work.
Sorry, I wasn't familiar with this feature! It used to be automatic (which was sometimes a pain). Now that it's on a toggle, I actually like the feature a lot more now. Cool!
