### ISSUE TITLE
Charm of Keeping I, II, III and Gravestones

### ISSUE THREAD

**Issue by Kullnr** [LunaPixelStudios/Better-MC#813]
### Describe the Bug

Upon dying with Charm of Keeping II equipped, retrieving your gravestone destroys your armor and hotbar. I believe it is due to a clash of Graves and the Charm of Keeping II from twilight forest.

### Reproduction Steps

1. Equip Charm of Keeping II
2. Find a way to die
3. Retrieve gravestone
4. Say goodbye to hotbar and armor

### Screenshots and Videos

https://user-images.githubusercontent.com/116608792/197657448-9d3da8a6-4942-4c4b-94e3-d9acd33087ff.mp4

Sorry for the bad quality. Had to use a compressor to get it under 10mb.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better Minecraft Fabric v9 HF

### Optifine

No

### Other Mods

Appleskin
Bobby
Midnight Controls

**Comment by chorbintime** [comment]
Should be reported on Graves / Twilight Forest github
