### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component

### ISSUE THREAD

**Issue by Dzasterrr** [LunaPixelStudios/Better-MC#814]
### Describe the Bug

So as always i wanted to join my server minecraft ( aternos host) and i seen this message: Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component. This is something with this server, because on other servers i dont have this problem. It's nothing compared with RelicEX mod. I dont want to delete player data because i have good things

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better Minecraft Fabric v9

### Optifine

No

### Other Mods

Nope

**Comment by chorbintime** [comment]
Have someone /kill you, or use a repeating command block, or move your playerdata out to generate new playerdata, make a repeating /kill command block, disable command blocks, restart server, then grab your items from your grave.
