### ISSUE TITLE
"Move items" button missing in JEI while using Tom's Simple Storage 

### ISSUE THREAD

**Issue by KamilTr** [LunaPixelStudios/Better-MC#815]
### Describe the Bug

Can't move any recipe to the crafting grid while using any terminal from Tom's Simples Storage.
The plus button does not show up.

### Reproduction Steps

1. Open crafting terminal from Tom' Simple Storage, open recipe for a pickaxe.

### Screenshots and Videos

While using crafting terminal:
![bild](https://user-images.githubusercontent.com/26675408/197850676-7c390230-3ddb-4d28-9783-8dd83943d2e1.png)
Regular crafting workbench:
![bild](https://user-images.githubusercontent.com/26675408/197850762-d02a65a9-3c34-4c78-b7f7-570514f91b4a.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v9 HF

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
Nothing we can do about this afaik. This is a JEI issue. We have to use JEI for the time-being until an issue with Twilight Forest and REI is fixed.
