### ISSUE TITLE
Server Crashing on Opening some generated chests

### ISSUE THREAD

**Issue by Konin-Sensei** [LunaPixelStudios/Better-MC#816]
### Describe the Bug

Chests found in various structures are causing a server crash/time out upon first opening (so presumably during loot generation). It is not clear to me at the time of writing, what chests or what loot is responsible as it has occurred in structures that I believe come from different mods. One was a boat and the other was a medieval looking house.

### Reproduction Steps

1. Open an affected chest

### Screenshots and Videos

[Video of gameplay](https://youtu.be/-NUuNZplKrw) that caused the crash log at the pastebin link.
I didn't record a video and I'm not sure what mod adds these structures but a chest in the basement of the structure in [this image](https://imgur.com/a/5DPU7zw) also caused a crash.

### Crash Report or Log

https://pastebin.com/NXtsgedi

### Operating System

Linux (amd64) version 5.15.0-41-generic

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v9 HF

### Optifine

No

### Other Mods

I added the [travelers backpack mod](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric) to the pack.

**Comment by chorbintime** [comment]
I would suggest setting server timeout in server.properties to -1 so Server Watchdog no longer times out the server, and send a latest.log if you are able to recreate the issue afterwards.

**Comment by xSHXRKIEx** [comment]
Are you sure you didn't add any more mods as I have tested this myself with no issues.

**Comment by Konin-Sensei** [comment]
> I would suggest setting server timeout in server.properties to -1 so Server Watchdog no longer times out the server, and send a latest.log if you are able to recreate the issue afterwards.

I set that value as suggested and the server doesn't crash but the player opening the chest still gets booted after 10/15 seconds. After logging back in, the chest loot is generated so in a sense it works but not great.
[latest.log](https://pastebin.com/knzWh1B7)


> Are you sure you didn't add any more mods as I have tested this myself with no issues.

I'm certain I didn't add any other mods. the crash report file should list all installed mods if you would like to check for yourself there. [World save uploaded to google drive](https://drive.google.com/file/d/1Spqv9HF85ZA5ssRUesIlLkv7QrZlZCWm/view?usp=sharing). This is the backup zip for the world from right before opening the chest in my video. It's at x=3708, z=11814. Since the issue doesn't appear to be all chests, trying this one in particular might enable replicating the issue.

**Comment by xSHXRKIEx** [comment]
I'm pretty sure this isn't really an issue with the modpack and more with Vanilla, as this bug has been in the game since 1.18. The reason it is lagging is cause its trying to generate a Vanilla Buried Treasure or Shipwreck map.

Here is the bug for example: https://bugs.mojang.com/browse/MC-236740#:~:text=A%20large%20server%2Dside%20lag,some%20users%20have%20reported%20crashes.

Why it is not happening to me but to you I am not sure. Who is your server host?

**Comment by Konin-Sensei** [comment]
Gportal is the host. Running with 6GB of ram

**Comment by Konin-Sensei** [comment]
Would treasure maps appear in the chest in the basement of that medieval house pictured above?

**Comment by Konin-Sensei** [comment]
Instead of asking the question I should've just gone and answered it myself. 
Using the suggestion for my server timeout from earlier, I was able to get these 2 chests to generate loot. (though I still got kicked for a good minute upon trying to open them). They did both have treasure maps in them so I'd agree that it appears to be that issue
