### ISSUE TITLE
Unable to install modpack in MultiMC

### ISSUE THREAD

**Issue by JasonDerulo1259** [LunaPixelStudios/Better-MC#818]
### Describe the Bug

I am unable to use the native minecraft launcher as it is buggy for me, and I dont have great internet, so I use Multi/PolyMC for everything.

I downloaded the BetterMC 1.19.2 Fabric modpack zip from curseforge ([link](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric/files/4040648)) but it does not import into multimc.

It returns this error when importing it from the zip:
![image](https://user-images.githubusercontent.com/71148978/198180515-9f1ee93e-95eb-4ab8-8c34-3db4255eaa9c.png)

And this error when importing it from the link:
![image](https://user-images.githubusercontent.com/71148978/198180628-7104ffb3-4f59-42bf-9ece-bda57a47fa39.png)

### Screenshots and Videos

This is what the inside of the zip looks like:

_inside zip_
![image](https://user-images.githubusercontent.com/71148978/198180715-b932feaf-64d3-4257-9b8b-8c77aaf08bc8.png)
_Inside overrides folder_
![image](https://user-images.githubusercontent.com/71148978/198180763-316f7e96-57c1-4094-a39e-081b5e188e5e.png)
_inside config folder_
![image](https://user-images.githubusercontent.com/71148978/198180790-b2b34cfd-909a-49e5-87c7-1b3d46f67c6f.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v9

### Optifine

No

**Comment by JasonDerulo1259** [comment]
I mean honestly its not solved, but it was easy enough so i just switched to prismlauncher

**Comment by unclamped** [comment]
I do have this issue in MultiMc, and since I'm in Linux using other launchers might not be a good choice

**Comment by JasonDerulo1259** [comment]
> I do have this issue in MultiMc, and since I'm in Linux using other launchers might not be a good choice

I would reccomend [prismlauncher](https://github.com/PrismLauncher/PrismLauncher/releases) if it works for you.. It says that it supports linux, so if you know how to download it you should be fine?

It's a fork of MultiMC, and is similar to polyMC, but has a few extra features. Additionally, there is a lot of political drama surrounding polyMC at the moment and there are some worries of compromises and malicious code, however the truth surrounding that is also debated.

The features you may use is it's curseforge integration, allowing for downloading curseforge modpacks inside the app, and it also lets you import curseforge zips.

**Comment by unclamped** [comment]
> > I do have this issue in MultiMc, and since I'm in Linux using other launchers might not be a good choice
> 
> I would reccomend [prismlauncher](https://github.com/PrismLauncher/PrismLauncher/releases) if it works for you.. It says that it supports linux, so if you know how to download it you should be fine?
> 
> It's a fork of MultiMC, and is similar to polyMC, but has a few extra features. Additionally a lot of people are switching to it as there is a lot of political drama surrounding polyMC at the moment and there are some worries of compromises and malicious code, however the truth surrounding that is also debated.
> 
> The features you may use is it's curseforge integration, allowing for downloading curseforge modpacks inside the app, and it also lets you import curseforge zips.

LGTM! Works just fine in Linux and seems like a direct improvement of Multi. I'll check if I can do anything with it, thanks a lot!

**Comment by jdominguezs** [comment]
I'm having the same issue in MultiMC and PrismLauncher

![image](https://user-images.githubusercontent.com/109268957/230903911-479397af-40cc-4b45-91e0-a5f80b280869.png)

![image](https://user-images.githubusercontent.com/109268957/230903990-798f14aa-e657-47aa-bca9-9d07a8f6b08f.png)


In trying with the latest version Better+MC+FORGE+Server+Pack+1.19.2+v13.zip

Any clue of what might be happening?

Thanks
