### ISSUE TITLE
Saving world when enter

### ISSUE THREAD

**Issue by chrisko131** [LunaPixelStudios/Better-MC#819]
### Describe the Bug

I'm playing on better mc plus 1.16.5. It can't enter the title screen. Instead it'll say saving world and exit by itself.

### Reproduction Steps

1.Enter the game
2.crashes itself

### Crash Report or Log

https://gist.github.com/chrisko131/c6323d11fba2fe9f9992d0655ee8f6f4

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Better mc plus 1.16.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
remove fancy menu
