### ISSUE TITLE
smoothchunk says requires mc 1.19 when the game is 1.19.2 [BETTER MC FABRIC]

### ISSUE THREAD

**Issue by Maxwell1709** [LunaPixelStudios/Better-MC#820]
### Describe the Bug

clear error of what the game shows will be in the screenshot section, if i delete this mod other mods won't load and result in crashing of the game itself.

and the main smoothchunk mod only supports upto 1.19.1/1.19 and while the game is 1.19.2 

### Reproduction Steps

1.Starting launcher
2.Starting the game
3.And it occurs immediately about the incompatibility
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/116146426/198245349-2f9c29d2-37bd-40f2-856c-8710be69e959.png)

### Crash Report or Log

https://pastebin.com/ruJd36Q8

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v9 HF

### Optifine

I used Optifine

### Other Mods

None

**Comment by xSHXRKIEx** [comment]
Either you installed the modpack wrong or you are using a cracked launcher?

**Comment by Maxwell1709** [comment]
> Either you installed the modpack wrong or you are using a cracked launcher?

The modpack is installed through curseforge and no I'm not using a cracked launcher

**Comment by Maxwell1709** [comment]
My bad, it was that i chose forge instead of fabric for loading the mods, sorry for the inconvenience, it's fixed now
