### ISSUE TITLE
Backpack dupe

### ISSUE THREAD

**Issue by MrWa1ker** [LunaPixelStudios/Better-MC#821]
### Describe the Bug

You can dupe backpack from Improved Backpacks by placing it on boss arena in Everbright from Blue Skyes.

### Reproduction Steps

1. Enter boss arena in Everbright
2. Place backpack on the ground (only in survival gamemode)
3. Press Q (throw item keybind)

### Screenshots and Videos

https://www.youtube.com/watch?v=7GrQT8ujNAo

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v59.5

### Optifine

No

### Other Mods

Mods added:
 - Playing Cards ( https://www.curseforge.com/minecraft/mc-mods/playing-cards )
 - Farmer's Respite ( https://www.curseforge.com/minecraft/mc-mods/farmers-respite )
 - Cosmetic Armor Reworked ( https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked )
 - Simple Login ( https://www.curseforge.com/minecraft/mc-mods/simple-login )

Mods removed:
 - FTB Chunks
 - FTB Backups

**Comment by chorbintime** [comment]
Does this happen in Survival mode?

**Comment by MrWa1ker** [comment]
Yes, this happen in survival mode

**Comment by chorbintime** [comment]
You should probably report this on the github for Blue Skies then. Improved Backpacks devs could also probably do something about it. I doubt we can
