### ISSUE TITLE
Client Side Mod extended-armor-bars Causes file errors server-side.

### ISSUE THREAD

**Issue by p0t4t0sandwich** [LunaPixelStudios/Better-MC#822]
### Describe the Bug

After loading up a server, extended-armor-bars (A client side mod) creates a poorly set-up config file.
This is a known issue with the original mod, the person who ported it to later versions has not fixed it.
From a post in the fabric discord, it is found that the file is difficult to delete on windows. [Link](https://discord.com/channels/507304429255393322/507982463449169932/947628521935745074)
I have also found that the file prevents SFTP from reading the server directory.

Solution: Remove this mod from the server-side pack as it is not needed.

### Reproduction Steps

1. Install the server pack
2. start the server
3. `'config\config.json'` appears in the main server folder
...

### Operating System

Ubuntu 22.04, Pop! os 22.04, Ubuntu 20.04

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc fabric v5-v9

### Optifine

No

**Comment by chorbintime** [comment]
Thank you for the report. I will report this to the creator of Serverpack Creator so this can be excluded from serverpacks in the future. It may not be excluded immediately, but will be eventually.
