### ISSUE TITLE
Leafes

### ISSUE THREAD

**Issue by TheUltimateP1e** [LunaPixelStudios/Better-MC#823]
### Describe the Bug

ebry single Leaf works as intended but instead of looking normal or with changed textures they have a weird outline looking like they were drawn with a really thick pencil, it really destroys the atmosphere of forests and the immersion. this is only a problem with normal trees, every tree added with mods looks just fine

### Reproduction Steps

1.make a new world with the modpack
2.walk to a tree
3.look at leafes with outlines thicker then the sun
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Medieval Minecraft Fabric v9 on CurseForge App

### Optifine

No

**Comment by chorbintime** [comment]
Could you please attach a screenshot? 

Is this still present in v10?
