### ISSUE TITLE
Some recipes stopped working

### ISSUE THREAD

**Issue by ShowTeKPT** [LunaPixelStudios/Better-MC#825]
### Describe the Bug

After I updated the modpack from v6 to v7, some recipes stopped working.
The item still exists in the game but I can't craft it.

I posted a screenshot of one example.

### Screenshots and Videos

![2022-10-30_12 28 59](https://user-images.githubusercontent.com/95918238/198881117-17e129f5-14e2-46cf-92cc-98efd94b22f7.png)

### Crash Report or Log

https://pastebin.com/RsQeGSjN

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC Forge v7

### Optifine

Yes

**Comment by ShowTeKPT** [comment]
I reverted back to v6 for now

**Comment by chorbintime** [comment]
Update Every Compat if there's an update available. If not, or the update doesn't fix this, report it on their github instead.
