### ISSUE TITLE
G key not working

### ISSUE THREAD

**Issue by Shiigen** [LunaPixelStudios/Better-MC#826]
### Describe the Bug

G key is free to bind, so i bind my Sneak Key to G but i can't sneak. I tried with other key like H for try and i can sneak. 

btw there is not conflict with G key. Maybe a mod who use that key ?

### Reproduction Steps

1. Try to set sneak key to G
2. Try it
3. Don't work
...

### Screenshots and Videos

![Screenshot_5](https://user-images.githubusercontent.com/101335459/198900232-33abbc88-c4c8-4daa-b7e3-bd799deddcb1.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

V9

### Optifine

No

**Comment by chorbintime** [comment]
We are aware of the issue but have no idea how to fix it. It's best to just avoid the G key altogether.
