### ISSUE TITLE
Minecolonies error

### ISSUE THREAD

**Issue by rycoshe** [LunaPixelStudios/Better-MC#828]
### Describe the Bug

I have a problem to run the modpack with minecolonies, can you help me?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V58.5

### Optifine

No

### Other Mods

Minecolonies, tensura, project e, project ex, strage drawers

**Comment by chorbintime** [comment]
Never, at any point, in any scenario, should you spend time filling out a form to ask for permission to ask a question.

Just state your issue instead of doing... this.
