### ISSUE TITLE
Spirit JEI crash

### ISSUE THREAD

**Issue by slycrel** [LunaPixelStudios/Better-MC#829]
### Describe the Bug

when attempting to press 'u' or click on a spirit modded item (i.e. a broken spawner) in JEI, minecraft crashes.

I've searched the closed bugs and this appears to have happened earlier this year as well.

Crash log attached.
[crash report.txt](https://github.com/LunaPixelStudios/Better-MC/files/9923941/crash.report.txt)

### Reproduction Steps

search for `@spirit` in JEI.  Click on one of the spirit items.  Alternatively, press 'u'.  Both cases cause the crash.  I have not explored whether using these items in a crafting table will also cause a problem.

### Screenshots and Videos

<img width="566" alt="Screen Shot 2022-11-02 at 2 30 55 PM" src="https://user-images.githubusercontent.com/412564/199596557-cb70009d-8813-405e-b652-b0c39e49a942.png">
<img width="595" alt="Screen Shot 2022-11-02 at 2 34 14 PM" src="https://user-images.githubusercontent.com/412564/199597046-7ed0684c-8379-4629-8552-b30e8b7c4ae6.png">

### Operating System

macOS monterey

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2 v9

### Optifine

No

**Comment by chorbintime** [comment]
Report on Spirit github
