### ISSUE TITLE
Fish don't spawn

### ISSUE THREAD

**Issue by caizoago** [LunaPixelStudios/Better-MC#830]
### Describe the Bug

This doesn't seem to impact any other mob, but no fish spawn in the game naturally. I'm not sure what mod would be impacting the spawning of fish specifically. 

### Reproduction Steps

1. Attempted to locate fish in different locations (rivers, warm oceans, etc.), as well as at different distances from spawn. No fish at all spawned at any location. 
2. Attempted to locate fish in a world with the same seed, but had the same issue. 
3. Attempted to locate fish in 4 different new worlds, but had the same issue of none spawning. 

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v9

### Optifine

I used Optifine

### Other Mods

None

**Comment by chorbintime** [comment]
1) Nothing we can really do about this. this is just a result of having 200 mods
2) You are not using Optifine because if you were you'd be crashing on startup + Optifine is a forge mod (and not a good one)
