### ISSUE TITLE
tombstone doesn't give my stuff

### ISSUE THREAD

**Issue by Neji19** [LunaPixelStudios/Better-MC#831]
### Describe the Bug

i died in my minecraft world and wanted to get my stuff back from my tombstone but when i clicked on tombstone i didn't get my loot back.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2022-11-03_14 38 34](https://user-images.githubusercontent.com/117367701/199735855-cd5fca33-8248-4186-a717-f6e028cd1514.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v9 .zip

### Optifine

No

### Other Mods

better MC modpack

**Comment by chorbintime** [comment]
1) Why did you tag this as 1.14 fabric?
2) This is a known issue with the Twilight Forest mod. Happens everytime you die with a twilight forest item in your inventory from what I've been told, report on YIGD github or Twilight Forest github
