### ISSUE TITLE
Can't interact with anvils

### ISSUE THREAD

**Issue by Gamma502** [LunaPixelStudios/Better-MC#832]
### Describe the Bug

Unable to interact with crafted, spawned, or naturally spawned anvils at all on 1.19.2 forge medieval MC modpack.

### Reproduction Steps

1.Right click anvil.
2.Nothing happens.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V8 Medieval MC FORGE

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
1) Known issue
2) You are not using Optifine because if you were you'd be crashing on startup
3) You aren't playing Better MC, you're playing Medieval MC
