### ISSUE TITLE
Resource Pack issues arising

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-MC#833]
### Describe the Bug

Hey! I'd like to report an aesthetic issue where sometimes Better MC on v18 sometimes fails to load all the resource packs. This doesnt end in a crash, but it reverts it into normal Minecraft visual stuff. This only happened once, and im not sure what sometimes causes it.

### Reproduction Steps

1. boot up BetterMC
2. be unlucky
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

**Comment by chorbintime** [comment]
Issue with Curseforge as far as I'm aware
