### ISSUE TITLE
 Launcher failed to start

### ISSUE THREAD

**Issue by LanLano6o1** [LunaPixelStudios/Better-MC#834]
### Describe the Bug

I tried to add a mod in the mod pack, but nothing happens when I press the launcher after adding it.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/TiY9EpzT

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.18.2

### Optifine

No

### Other Mods

RPMTW Platform
Inventory Profiles Next
libIPN

**Comment by chorbintime** [comment]
Remove RPMTW Platform
