### ISSUE TITLE
Open Lan Better Minecraft 1.19.2 

### ISSUE THREAD

**Issue by lrj1818** [LunaPixelStudios/Better-MC#836]
### Describe the Bug

Basically The Same Modpack But When You Try To Join Open Lan This Happens
![Schermafbeelding 2022-11-04 221513](https://user-images.githubusercontent.com/77946452/200076206-3c235cec-2943-42b6-be91-70c3ad96758f.png)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Schermafbeelding 2022-11-04 221513](https://user-images.githubusercontent.com/77946452/200075990-3c30491e-1856-492f-9542-4b7305f20a83.png)

### Crash Report or Log

Issue When Joining Open Lan

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

No

### Other Mods

No Mods Added

**Comment by chorbintime** [comment]
Do not use LAN. We offer 0 support for LAN.

You need to use the serverpack files on the curseforge page to setup a server, or buy one from Bisect for better performance and reliability.
