### ISSUE TITLE
Farmer Villagers not trading

### ISSUE THREAD

**Issue by GoofyLuffy09** [LunaPixelStudios/Better-MC#840]
### Describe the Bug
BetterMC Fabric 1.19.2 v10
Villagers will take the farmer job but will not trade with me, instead they just nod their head, Also one was able to trade with me but will not show new trades when he levels up. Other villagers with different job will trade with me though just not the farmers. This just started happening when I updated to v10. 

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v10

### Optifine

No

**Comment by chorbintime** [comment]
Are you playing on a server?

**Comment by GoofyLuffy09** [comment]
Yes

**Comment by chorbintime** [comment]
Will look into it

**Comment by maynardadam** [comment]
Just opened another ticket as this is still happening :(

**Comment by chorbintime** [comment]
> Just opened another ticket as this is still happening :(

there have been no modpack updates since this issue was made. why do you expect it to be fixed lmfao

**Comment by chorbintime** [comment]
This appears to be an issue with the Paradise Lost mod. Please try removing this mod and see if the issue persists.

I apologize for any confusion.
