### ISSUE TITLE
rei items lists bug

### ISSUE THREAD

**Issue by kohryu1** [LunaPixelStudios/Better-MC#841]
### Describe the Bug

It is showing two items list in the side dont know how to fix it. Happend after updating better mc version

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/117565820/200162027-10b7d03d-331e-4768-b7b5-013130b9a6d6.png)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v10

### Optifine

No

**Comment by chorbintime** [comment]
You seem to still have JEI installed. How did you update the modpack? What launcher are you using?

**Comment by kohryu1** [comment]
Hello sorry late reply. Im using tlauncher on rei and im using better mc
modpack fabric

**Comment by chorbintime** [comment]
We offer 0 support whatsoever for TLauncher. It's a known virus. There are very few similarities between what we actually include in our modpacks and what TLauncher downloads.
