### ISSUE TITLE
No replay mod button in main menu

### ISSUE THREAD

**Issue by Tomacastana** [LunaPixelStudios/Better-MC#842]
### Describe the Bug

In the main menu I can't find the button for the replay mod.

The replay mod is installed and I have recordings but I can't access the mod menu.

Im in Medieval Minecraft 1.19.2 version 5.5

I hope you can help me with this

Thank you in advance

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Medieval MC 5.5

### Optifine

No

**Comment by chorbintime** [comment]
Delete FancyMenu mod

**Comment by Tomacastana** [comment]
Ok, thats easier than i thought.

Thank you
