### ISSUE TITLE
The game freezes in a specific area in the end

### ISSUE THREAD

**Issue by EndersteveGamer** [LunaPixelStudios/Better-MC#843]
### Describe the Bug

When getting close to an area, the game freezes and does not respond, forcing me to restart the game
Even after restarting the game, it freeze every time I get too close to that area
After checking the logs, it looks like the issue is caused by a StackOverflowError caused by the WrappistCrystalSpike structure by the Geode+ mod

The part of the logs pointing the issue:
```
java.util.concurrent.CompletionException: java.lang.StackOverflowError
Caused by: java.lang.StackOverflowError
	at net.yeoxuhang.geode.common.world.feature.WrappistCrystalSpikeFeature.placeSpike(WrappistCrystalSpikeFeature.java:97) ~[geode-1.1.5-1.19.2.jar.jar%23223!/:1.0.0]
```

The crash logs issue:
```
Time: 2022-11-06 11:19:04
Description: Exception ticking world

java.lang.StackOverflowError: Exception ticking world
	at net.yeoxuhang.geode.common.world.feature.WrappistCrystalSpikeFeature.placeSpike(WrappistCrystalSpikeFeature.java:97) ~[geode-1.1.5-1.19.2.jar.jar%23223!/:1.0.0] {re:classloading}
```

In the logs and the crash log it is spamming the same StackOverflowError, so it looks like the mod entered an infinite loop

### Reproduction Steps

1. Generate a world with seed -313985092756520355
2. Go in the end
3. Go to coordinates 477 46 -1535
4. Freeze every time you go in this area

### Screenshots and Videos

No screenshot or video

### Crash Report or Log

Crash log: https://pastebin.com/BgbfMSVJ
Logs (too big for PasteBin): [2022-11-06-3.log.gz](https://github.com/LunaPixelStudios/Better-MC/files/9945857/2022-11-06-3.log.gz)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better Minecraft 1.19.2 Forge v8

### Optifine

No

### Other Mods

No other mod

**Comment by chorbintime** [comment]
Report on Geode+ github
