### ISSUE TITLE
Sprouts Elephant

### ISSUE THREAD

**Issue by DGBaseball05** [LunaPixelStudios/Better-MC#844]
### Describe the Bug

When the Sprouts Elephant goes to water Crops it crashes the game.

### Reproduction Steps

1. Planted Wheat Field
2. Place Sprouts Elephant in wheat field
3. Allow a water source
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V14

### Optifine

No

**Comment by chorbintime** [comment]
Report on the github of whichever mod adds the sprout elephants
