### ISSUE TITLE
Cannot play single player, but can play multiplayer

### ISSUE THREAD

**Issue by TrashPandaVal** [LunaPixelStudios/Better-MC#847]
I cannot load or create single player worlds without the load screen crashing, saying "Invalid player data" and sending me to the multiplayer screen

**Comment by Ducky211** [comment]
#845 #846

**Comment by Ducky211** [comment]
@xSHXRKIEx

**Comment by Ducky211** [comment]
on curseforge - repair installation then repair profile

**Comment by paogucci08** [comment]
Same for me, I also noticed that the Better MC loading screen is gone and was replaced by fancy menu. a white bar at the top also covers the screen most of the time. Idk if this was intentional tho but if it is, the change is most certainly unwanted.

**Comment by paogucci08** [comment]
Anyway repairing the minecraft installation through curseforge then repairing the better mc profile fixes the issue.
