### ISSUE TITLE
Missing textures on coconut shelf (Every Compat)

### ISSUE THREAD

**Issue by TH3P1NK5T3R** [LunaPixelStudios/Better-MC#848]
The bottom textures for the Coconut Shelf (Every Compat mod) seem to be missing. Next to the coconut shelf is an Oak Shelf from the original "Another Furniture" mod for comparison. 
![missing textures on shelf](https://user-images.githubusercontent.com/105680957/201139888-5e7a517d-d4b9-46cc-aee6-1f1dc4c7fc52.png)

**Comment by chorbintime** [comment]
not our issue, issue with the mod that's adding the block
