### ISSUE TITLE
Can't start server on MacOS

### ISSUE THREAD

**Issue by viniisnap** [LunaPixelStudios/Better-MC#849]
``I know macOS can still execute .sh files, but whenever I try to run it from Terminal, I just get this:
```
Running Fabric checks and setup...
Fabric is not available for Minecraft 1.19.2, Fabric 0.14.10.
Exiting...
Press any key to continue
```

However, I also tried installing Powershell- but I get this error instead when attempting to launch the server.

`CMD: /.../start.ps1:62
Line |
  62 |      CMD /C "`"${Java}`" ${CommandToRun}"
     |      ~~~
     | The term 'CMD' is not recognized as a name of a cmdlet, function, script
     | file, or executable program. Check the spelling of the name, or if a
     | path was included, verify that the path is correct and try again.

CMD: /.../start.ps1:62
Line |
  62 |      CMD /C "`"${Java}`" ${CommandToRun}"
     |      ~~~
     | The term 'CMD' is not recognized as a name of a cmdlet, function, script
     | file, or executable program. Check the spelling of the name, or if a
     | path was included, verify that the path is correct and try again.

Exiting...`

**Comment by chorbintime** [comment]
Are you using the serverpack?

**Comment by viniisnap** [comment]
Yes, the most recent one on CurseForge. It has worked on a previous edition, but I don't have that file anymore.

**Comment by GriffinMeyer** [comment]
I had this exact issue within a docker container. The issue was that wget was not installed. After installing wget, the script seems to work!. It would appear that start.sh needs to be improved to handle the absence of wget and error out properly.

**Comment by chorbintime** [comment]
https://github.com/Griefed/ServerPackCreator/releases/tag/3.15.1

You can remake the serverpack yourself via SPC 3.15.1 as this issue has hopefully been fixed.
