### ISSUE TITLE
Farmer not trading

### ISSUE THREAD

**Issue by maynardadam** [LunaPixelStudios/Better-MC#850]
### Describe the Bug

Isolate Farmer in enclosed space. Only workstation in space is a composter. Takes Farmer Profession. Will not trade when right clicked. Will instead do the head shake animation and sigh

### Reproduction Steps

1.trap villager in space 
2.give composter work station 
3.right click 
4.no trading ui opens

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2 v10

### Optifine

No

**Comment by chorbintime** [comment]
will look into it

**Comment by ThyPutish** [comment]
Have the same problem but the villager does the headshake of a nitwit when clicked.

**Comment by maynardadam** [comment]
does closed mean we can expect a fix in the next release

**Comment by danif86** [comment]
Same here

**Comment by danif86** [comment]
[Paradise-Lost](https://github.com/devs-immortal/Paradise-Lost) - removing this fixes it?

**Comment by chorbintime** [comment]
This appears to be an issue with the Paradise Lost mod. Please try removing this mod and see if the issue persists.

I apologize for any confusion.
