### ISSUE TITLE
Blocks in create contraptions become invisible after converting from entity to block.

### ISSUE THREAD

**Issue by MAXimized490** [LunaPixelStudios/Better-MC#851]
### Describe the Bug

This bug is observed on multiplayer servers running the official server pack ([v14](https://www.curseforge.com/minecraft/modpacks/better-mc-plus-new/files/3984902)). This bug does not occur in singleplayer.
Any contraption using Create that involves converting a solid block into an entity and then back (minecart contraptions, elevators, doors, etc.) has a bug where random blocks on the contraption will become invisible to players on the server. Leaving and rejoining the server will fix the graphical error until the contraption changes states again.

### Reproduction Steps

1. Create anything with a few blocks and then move it with the Create mod. (This bug has only been observed with rope pulleys and minecart contraptions)
2. Move the contraption. More specifically, change it's state from an entity back to solid blocks.
...

### Screenshots and Videos

An elevator before its been moved. All blocks are visible.
![2022-11-11_18 21 47](https://user-images.githubusercontent.com/36754183/201447117-39996ad1-ac7e-4c2e-9f37-0186df9e56cc.png)
The same elevator after moving a few blocks down. Certain blocks are now invisible but they are still there (you can collide with them and trying to click where the blocks should be usually reveals the block).
![2022-11-11_18 22 08](https://user-images.githubusercontent.com/36754183/201447121-d3cc785e-6d9a-46f1-a9d7-da6f29791636.png)
The same elevator moved all the way back to where it started. Notice that different blocks are now invisible.
![2022-11-11_18 22 16](https://user-images.githubusercontent.com/36754183/201447125-cb3dc45f-702c-4b41-9603-08dacdab70bc.png)
An automatic miner before its been assembled.
![2022-11-11_18 22 46](https://user-images.githubusercontent.com/36754183/201447127-da0eefba-bd9e-411e-b438-e3c9cb4e0f0a.png)
The auto miner now assembled and an entity. All blocks still show.
![2022-11-11_18 22 54](https://user-images.githubusercontent.com/36754183/201447128-ba36e621-ed61-4230-a1ae-40e0105f1aa1.png)
The auto miner now disassembled back into blocks.
![2022-11-11_18 23 02](https://user-images.githubusercontent.com/36754183/201447129-0590b706-6c6a-4c24-b1f3-d40c80404879.png)

It's important to note that in both cases the blocks are still there on the server side but the client fails the render certain blocks. In both cases, the entire contraption is visible while moving/in an entity state. The bug only occurs after moving the contraption from how it was when you first logged on.

### Operating System

Client: Windows 11 - Server: Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

No

**Comment by chorbintime** [comment]
Known issue with the Flywheel mod which is a dependency for Create iirc. I don't think there's a lot that can be done by anyone except for Flywheel devs. I've also heard some people say it could be an issue with Oculus, Rubidium and Entity Culling

**Comment by MAXimized490** [comment]
Got it. Just wanted to let you know that I removed oculus-mc1.18.2-1.2.5a, entityculling-forge-mc1.18-1.5.1, rubidium_extras-1.18.2_v1.3.2, and rubidium-0.5.3a from my client and the issue was still observed. There are somewhat similar issues on our server where certain trees' leaves are invisible and doors being opened/closed by others do not update for everyone. Do you think these are related issues?

**Comment by chorbintime** [comment]
"Certain trees leaves are invisible" could just be because of ghost blocks which is a common issue with minecraft servers of all versions, vanilla and modded

The Create bug is almost definitely just a Flywheel issue but other mods could make it happen more often

**Comment by QianFuv** [comment]
Try [Block Limit Fix](https://www.curseforge.com/minecraft/mc-mods/block-limit-fix)
