### ISSUE TITLE
Hoppers doesn't work with composters

### ISSUE THREAD

**Issue by PRiewe** [LunaPixelStudios/Better-MC#852]
### Describe the Bug

Hoppers doesn't insert plant materials into composters (which works in vanilla Minecraft).

### Reproduction Steps

1. Place a composter
2. Place a hopper on top of composter 
3. Insert stack of saplings or seeds into hopper
...
Nothing happens.

In vanilla Minecraft, the same steps will result in the hopper inserting seeds into composter until a new bonemeal is ready. Normally a hopper at the bottom would extract bonemeal but that shouldn't be necessary to reproduce.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2v8

### Optifine

No

### Other Mods

n/a

**Comment by chorbintime** [comment]
It might be an issue with Debugify or Canary.

**Comment by PRiewe** [comment]
You’re right. It’s a know feature of Canary.

 See
https://github.com/AbdElAziz333/Canary/blob/mc1.19.2/dev/src/main/java/com/abdelaziz/canary/mixin/block/hopper/README.md#how-canary-hoppers-work-different-from-vanilla

**Comment by PRiewe** [comment]
Nothing to fix
