### ISSUE TITLE
Veinmining

### ISSUE THREAD

**Issue by Shadowlink061** [LunaPixelStudios/Better-MC#853]
### Describe the Bug

Vein mining doesnt work

### Reproduction Steps

1.Enchant a pickaxe with veinming
2.doesnt work
3.
...

### Screenshots and Videos

imagen a block breaking, but just one

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v8

### Optifine

No

### Other Mods

none

**Comment by chorbintime** [comment]
Hold the tilda key ~
