### ISSUE TITLE
Certain items just delete your inventory, needs to be fixed asap for a playable experience

### ISSUE THREAD

**Issue by The1Unic** [LunaPixelStudios/Better-MC#854]
### Describe the Bug

In the new Fabric version of Better MC 1.19.2 using any kind of charm of keeping and subsequently dying just deletes those items, in turn making you just want to delete the modpack. There is already a closed issue on this, were a mod just wrote that this has to be reported to the Twilight forest issue tracker or the Gravestones mod issue tracker. I think it would be safest to just remove the charms from the game until the issue is resolved, preventing further annoyances.

### Reproduction Steps

1. Use any kind of charm of keeping
2. Die (in minecraft)
3. Upon retrieving the grave, all items that were supposed to be saved are gone

### Screenshots and Videos

You can picture an empty inventory and a frustrated player (me)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v10

### Optifine

No

**Comment by chorbintime** [comment]
Issue with YIGD. Fixed in the latest YIGD version. Update You're In Grave Danger manually to fix.
