### ISSUE TITLE
generation bug

### ISSUE THREAD

**Issue by unleashbear** [LunaPixelStudios/Better-MC#855]
### Describe the Bug

Many structures are too close to each other when the world is generating, thus it overlapps many blocks of these sturctures. Also i have a world that aviary generates just on the obsidan pillars of the end island, which is a big issue since the mobs on that are too strong to deal when you first enter the end.

### Reproduction Steps

1. creat a new world 
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/118094250/201507083-e47fb3bb-8b25-476b-994c-ba62942f3e5f.png)

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

The newest v 10 

### Optifine

No

**Comment by chorbintime** [comment]
Not an issue
