### ISSUE TITLE
Some settings could not be saved.

### ISSUE THREAD

**Issue by Landidi666** [LunaPixelStudios/Better-MC#856]
### Describe the Bug

Some settings could not be saved.
E.g
1. In Options>Controls>Crawl, I changed "Hold" to "Toggle", but after I restarted the game, the settings were reverted to "Hold".
2. I added the "Moving Elevator" mod, but the elevator controller cannot save the elevator size and speed setting.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v8

### Optifine

No

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/moving-elevators

**Comment by chorbintime** [comment]
Could be an issue with the Crawl mod or you just didn't save it correctly.
