### ISSUE TITLE
Game crashes when trying to make new world.

### ISSUE THREAD

**Issue by anaka06** [LunaPixelStudios/Better-MC#857]
### Describe the Bug

When trying to create a new world the screen changes to "preparing to create world" before crashing. Reopening the Minecraft launcher shows a message about the crash and says the exit code is -1

### Reproduction Steps

1. Launch mod pack
2. Try to create new world
3. Crash

### Crash Report or Log

https://gist.github.com/anaka06/8cc11a6825867136a56be2f5c3d09eab#file-crash-2022-11-15_16-28-39-client-txt

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v10.zip

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
Can you try again with the "paxi" folder in configs deleted?

**Comment by chorbintime** [comment]
Could you try adding 1 thing at a time back to the paxi folder, and see what's causing it? I'm unable to recreate the issue. I'd start with the Oh The Biomes You'll Go Compat Datapack.
