### ISSUE TITLE
Every time I enter the nether (Better Minecraft PLUS) my hunger completely depletes even after death

### ISSUE THREAD

**Issue by snakejz** [LunaPixelStudios/Better-MC#858]
### Describe the Bug

So im on my second playthrough of Better Minecraft PLUS. I had to restart because the moment I enter the nether I am instantly depleting all my hunger. Even if I eat it will just go straight back to 0 and I'm forced to just suffer and starve. I die and respawn and the effect is still on me. I tried to go into log files to remove the effect manually, I also tried cheats and commands, still no luck. Every time I respawn I die of hunger. Is there some mod I'm missing out on? Am I just dumb and not aware of some armor set I need to wear to enter the nether? Two of my playthroughs are ruined due to this hunger issue and I cant seem to find anywhere online that has a solution to the problem.
I have a save that I backed up right before I go into the nether portal, I dont know how to link that on this form but I am happy to provide it if needed.

### Reproduction Steps

1.make nether portal in survival
2.go through
3.hunger will deplete to 0 even after death
...

### Screenshots and Videos

![2022-11-17_03 32 46](https://user-images.githubusercontent.com/118431534/202396245-470af228-dd5f-4691-9556-64e9738acfb8.png)

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [PLUS] - 1.18.2

### Optifine

No

### Other Mods

no

**Comment by snakejz** [comment]
I also get the achievement "It's gettin' kinda hot in here", I dont know if that effects it either

**Comment by snakejz** [comment]
![2022-11-17_03 39 52](https://user-images.githubusercontent.com/118431534/202397820-450034b0-2b6d-4e84-bd4d-d5a409bfb353.png)

**Comment by chorbintime** [comment]
What launcher are you using?

Are you sure you're playing PLUS?

Do you have the ring of seven curses equipped?
