### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by PeenB01** [LunaPixelStudios/Better-MC#859]
### Describe the Bug

When I first downloaded the pack I attempted to join a friends world and it wouldn't show up. So I checked all of my settings and deleted and redownloaded the pack and still nothing. The game works fine on my own but no worlds will show up for multiplayer. (Yes it was open to LAN on the other end)

### Reproduction Steps

1. Open the pack
2. Attempt to join a friend
3. Be sad
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2

### Optifine

No

### Other Mods

N/A

**Comment by chorbintime** [comment]
How are you hosting the server?
