### ISSUE TITLE
Advacements "Mighty Strangoff" and "Hydra Slayer" doesnt work

### ISSUE THREAD

**Issue by nnneura** [LunaPixelStudios/Better-MC#860]
### Describe the Bug

I was playing normally in my world, i arrieved the highlands after killing the snow queen and the toxic rain did not stop, at first i thought that i was missing something. When i saw the achievements i notice that this two are incomplete, i tried to kill the minoshroom again but no, i cant do these advancements, and cant progress normally on the twilight mod.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/118492693/202590692-247589a5-6a27-4143-8e65-d3e7c4132e22.png)
![image](https://user-images.githubusercontent.com/118492693/202590735-b99539d6-ef30-4b65-8078-2cf3af1c8475.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v59.5

### Optifine

No

**Comment by chorbintime** [comment]
You are likely progressing through Twilight Forest incorrectly. There are several wikis which show to progress through the mod correctly. 

If you are 100% sure you're doing everything correctly, report this on Twilight Forest's github.
