### ISSUE TITLE
Farmer Villagers Trades Not Working

### ISSUE THREAD

**Issue by Boomkinzz** [LunaPixelStudios/Better-MC#861]
### Describe the Bug

Farmer villagers, even naturally spawning ones are not allowing players to trade with them. All other functions seem to be working besides trading. Any suggestions would be great

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v10

### Optifine

No

**Comment by danif86** [comment]
https://github.com/devs-immortal/Paradise-Lost looks to be the problem

**Comment by chorbintime** [comment]
Issue with Paradise Lost mod
