### ISSUE TITLE
Game crashes when trying to load my world.

### ISSUE THREAD

**Issue by ashvathaman** [LunaPixelStudios/Better-MC#863]
### Describe the Bug

Describe the Bug

When trying to load my world the game crahs and says the exit code is -1.  
Reproduction Steps

    Launch mod pack
    Try to open my world
    Crash

Screenshots and Videos

No response
Crash Report or Log

https://gist.github.com/anaka06/8cc11a6825867136a56be2f5c3d09eab#file-crash-2022-11-15_16-28-39-client-txt
Operating System

Windows 11
Minecraft Version

1.19
Modloader

Fabric
Modpack Version

Better MC [FABRIC] 1.19.2 v10.zip
Optifine

No
Other Mods

No

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/sdPVYqhS

### Operating System

W11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
What launcher are you using?

Also, Optifine is a forge mod which is incompatible with all of our modpacks. You don't have Optifine installed because this is a Fabric modpack.

**Comment by ashvathaman** [comment]
I try the Curseforge launcher and the GDLauncher and both crash

**Comment by chorbintime** [comment]
Can you try deleting one file at a time from within the paxi folder in configs? Tell me which one fixes it.

**Comment by ashvathaman** [comment]
The mew version v11 seems to solve the problem
