### ISSUE TITLE
Honey block stick to slime block.

### ISSUE THREAD

**Issue by Fumyaaa** [LunaPixelStudios/Better-MC#864]
### Describe the Bug

Is this the intended behavior?
This does not happen if the slime block is moved.
And this did not happen in v8 and earlier.(I skipped v9 and played v10.)

### Reproduction Steps

1. Place the slime block and honey block side by side.
2.Move honey block with a piston, etc.

### Screenshots and Videos

https://user-images.githubusercontent.com/118468879/202671410-c9c098d2-bb13-4b20-98bf-740cbf7172a2.mp4

### Operating System

Windows10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v10

### Optifine

No

### Other Mods

advdebug-2.3.0(Avoid tick loop error )

**Comment by chorbintime** [comment]
Try updating or removing the Canary mod.
