### ISSUE TITLE
Skin Won't Load

### ISSUE THREAD

**Issue by jakebob02** [LunaPixelStudios/Better-MC#866]
### Describe the Bug

I select my skin in the launcher but when I hit play it loads the default steve skin. Someone smarter than me please help

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
1) Optifine is incompatible with all of our modpacks and is very bad in general
2) Skin servers were down last night. it's not an issue on our side.
