### ISSUE TITLE
FTB Quests are not showing up

### ISSUE THREAD

**Issue by Xets234** [LunaPixelStudios/Better-MC#867]
### Describe the Bug

I've made a little bit of progress in the game, killing some bosses in the twilight forest and such, however  no such quests or rewards have appeared. It is only showing the "modpack" section on the left. Could not find any solution online.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/118624754/202862125-c495eca7-4fa2-470d-aa4f-1d16150be38e.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5 v59.5

### Optifine

No

**Comment by chorbintime** [comment]
You installed configs incorrectly.

**Comment by HennrikeSocher** [comment]
how configure this in server ??

**Comment by chorbintime** [comment]
what?
