### ISSUE TITLE
bugs with the fabric seasons mod

### ISSUE THREAD

**Issue by Nickmines** [LunaPixelStudios/Better-MC#868]
### Describe the Bug

going into the snow queen's place all the ice around it starts to melt and it start to lag a lot and I think the seasons mod is the cause
I've also been experiencing crashes from the last biome and I'm not sure what's causing it and I'm not getting a crash report

### Reproduction Steps

1.wait for summer or spring
2. go to snow queen's place 

also check the last biome

### Screenshots and Videos

![2022-11-19_21 32 06](https://user-images.githubusercontent.com/97149345/202879984-959be68e-c16c-4795-ab8e-8c8d03cd6e8a.png)

### Operating System

Windows 10 Pro

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better Mc [FABRIC] 1.19.2 v10

### Optifine

No

### Other Mods

no other mods

**Comment by chorbintime** [comment]
The Fabric Seasons config only has the overworld on the whitelist. I have no idea why this happens in the Twilight Forest. You can try asking the Fabric Seasons dev on github/discord

**Comment by Nickmines** [comment]
Ok I'll try asking them
