### ISSUE TITLE
when not maximized it has a minor visual bug

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [LunaPixelStudios/Better-MC#869]
### Describe the Bug

the text of game menu is below back to game when not maximized.

### Reproduction Steps

1. don't maximize the window
2. game menu is below back to game while overlapping

### Screenshots and Videos

![2022-11-19_22 15 03](https://user-images.githubusercontent.com/110959420/202885184-44907ed9-fb34-4182-8cf7-213464850858.png)

### Operating System

ubuntu

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v11

### Optifine

No

### Other Mods

n/a

**Comment by chorbintime** [comment]
Nothing we can really do about this unfortunately
