### ISSUE TITLE
Can't trade with Farmer Villagers

### ISSUE THREAD

**Issue by Mainexox** [LunaPixelStudios/Better-MC#870]
### Describe the Bug

I have multiple farmer villagers who just shake their heads when I click on them and the trade menu doesn't pop up. Other villagers with jobs are working fine.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BETTER MC FABRIC 1.19.2 v11

### Optifine

No

**Comment by chorbintime** [comment]
known issue with the Paradise Lost mod. delete it or just ignore the issue
