### ISSUE TITLE
Punching a mob crashes game

### ISSUE THREAD

**Issue by DocFred226** [LunaPixelStudios/Better-MC#871]
### Describe the Bug

Using the server pack, when logged in to multiplayer game, my minecraft client freezes and goes to not responding when I punch a mob.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

59.5

### Optifine

No

**Comment by chorbintime** [comment]
I need a crash report or latest.log or I can't help you
