### ISSUE TITLE
Disappearing items

### ISSUE THREAD

**Issue by marymouse06** [LunaPixelStudios/Better-MC#872]
### Describe the Bug

Its not every mined item, but I will mine stuff and its mostly the rarer items disappear from my inventory. I pick them up and then they are gone shortly after. There was no lag in those moments and it keeps happening.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Medieval

### Optifine

No

**Comment by chorbintime** [comment]
Are you sure you have no enchants or anything which could do this?

**Comment by marymouse06** [comment]
Positive. I got stuff from a personal friend of mine and I verified with
them that no, nothing should be causing this issue. I also changed my
password thinking I had been hacked and the backpack I was given has also
seemingly disappeared.

**Comment by chorbintime** [comment]
Do you have any kind of ender backpack or storage system set up? Can you reproduce the issue on a singleplayer world?
