### ISSUE TITLE
lost all server progress

### ISSUE THREAD

**Issue by YoungerMarrow** [LunaPixelStudios/Better-MC#874]
### Describe the Bug

I was playing on the server last night and I just logged on and it made me restart and I lost all of my progress.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Medieval Minecraft (Fabric) 1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
What are you using to host the server?

Is your saves folder still present in the server files?

Does the saves folder have anything inside?

Have you checked your antivirus? It might have deleted it.
