### ISSUE TITLE
Can't throw Ender eyes or Soul Star in our server i don't know why 

### ISSUE THREAD

**Issue by Flapsss** [LunaPixelStudios/Better-MC#876]
The title say it all when we try to throw any of this locator items it just stay in our hands, but i tried in singleplayer and it worked perfectly fine.

**Comment by chorbintime** [comment]
Please follow the format or I can't help you. I don't know what modpack you are playing.

**Comment by Flapsss** [comment]
Sorry the modpack is 1.19.2 better-mc v11 i couldn't find any indication about a format for issues perhaps i missed it.

**Comment by Flapsss** [comment]
i'll do another one sorry
