### ISSUE TITLE
Players Freeze when joining server, Players getting timed out, Players out of sync with server

### ISSUE THREAD

**Issue by Empathyyyy** [LunaPixelStudios/Better-MC#877]
### Describe the Bug

I have started a 1.19.2 Better MC server v9 on forge 43.1.52, i downloaded the server pack through curseforge and got it up and running no problem. I am able to join perfectly fine with no issues on the local network, but when my friend joins from his network he is frozen in place for me but able to move around, I am frozen in place for him but am able to move around, this goes on for a total of about 30 seconds until he is eventually timed out. I am very confused as I have another friend able to join and play perfectly normally

### Reproduction Steps

1. Start Minecraft
2. Join the Server
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v9

### Optifine

No

**Comment by chorbintime** [comment]
disable anti-virus
disable firewall
flush dns
restart router
switch to GDLauncher

do this on both sides. you can also try portforwarding.
