### ISSUE TITLE
Server crashing on every backup

### ISSUE THREAD

**Issue by orangeflavored0** [LunaPixelStudios/Better-MC#879]
### Describe the Bug

Hosting a server running better mc fabric. Server crashes every time a backup is attempted.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/w0g9V8cE

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v11

### Optifine

No

**Comment by chorbintime** [comment]
Delete FTB Backups 2
