### ISSUE TITLE
Can't throw ender eyes or soul stars on server 

### ISSUE THREAD

**Issue by Flapsss** [LunaPixelStudios/Better-MC#880]
### Describe the Bug

I tried in solo to throw an ender eye or a soul star it worked perfectly but in v10 aswell as in v11 of bmc v11 we couldn't, we use a boxtoplay server if that can help.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v11 1.19.2

### Optifine

No

**Comment by Flapsss** [comment]
After some exploration it seems that there isn't any village aswell so i suppose the reason we can't throw ender eye is because there is no structure at all on the map so no stronghold

**Comment by chorbintime** [comment]
There are villages, and there are strongholds. If none are spawning, you disabled structures yourself. 

Normal eyes of ender do not work if the End Remastered mod is present. You need to use the modded eyes from End Remastered.
