### ISSUE TITLE
can't use shader(better mc 1.16.5)

### ISSUE THREAD

**Issue by baksomicin** [LunaPixelStudios/Better-MC#881]
### Describe the Bug

can't use shader

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![error](https://user-images.githubusercontent.com/110702393/204112827-a7d2ed01-426a-4109-9b7c-308b927464a1.png)

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

better mc v49

### Optifine

No

### Other Mods

off hand combat
ice and fire
spartan weaponry
spartan shield

**Comment by chorbintime** [comment]
How did you install the modpack?

Why are you playing on v49? The latest version is v59.5

**Comment by baksomicin** [comment]
> 

because in that version tower can't spawn i dont know why

**Comment by xSHXRKIEx** [comment]
well your using an older version so of course its not going to have the same mods.
