### ISSUE TITLE
Better-MC compat with (Lithium-Fabric)

### ISSUE THREAD

**Issue by meguroyama** [LunaPixelStudios/Better-MC#882]
### Describe the Bug

Hey there,

Is better-mc compatible with lithium-fabric (https://github.com/CaffeineMC/lithium-fabric) ? I'm having some issues with both fabric and forge when running the server due to tick lag / delay issue. 

Player count : 4-6
Spec : 24 core 48 threads
RAM : 6 GB VM
CPU : VM CPU

### Operating System

Debian

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Latest

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
You are not using Optifine. Optifine doesn't work on Fabric, its a Forge mod. Never use Optifine for any reason.

 The modpack already comes with Lithium. All of our modpacks are fully optimized.

**Comment by meguroyama** [comment]
My mistake . If the server is not running sufficiently is it mostly due to it being ran in a VM ? The hypervisor is qemu at the moment. The proc base frequency is 2.40 GHz, checking on the performance using netdata I'm not seeing any iowait at all on the VM.

**Comment by chorbintime** [comment]
https://github.com/etil2jz/etil-minecraft-flags 

If lag persists, do the following command ingame:
/spark profiler --interval 100

Then, send the link here.
