### ISSUE TITLE
spawning under world falling and crash

### ISSUE THREAD

**Issue by FeFeChwan** [LunaPixelStudios/Better-MC#883]
### Describe the Bug

when i enter a local game it spawns me under the world and i keep falling then disconnect
![loading](https://user-images.githubusercontent.com/119160244/204129401-e0f89925-ab9c-4c69-a29e-b748b95fa81d.png)

### Reproduction Steps

1.enter a local game
2.then it happens

### Screenshots and Videos

![loading](https://user-images.githubusercontent.com/119160244/204129404-bb14df97-d216-457a-9a4c-f337b7477135.png)

### Crash Report or Log

java out of bound

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

No

**Comment by xSHXRKIEx** [comment]
What launcher are you using? Have you tried reinstalling the modpack? can you send a latest.log

**Comment by chorbintime** [comment]
Under the crash report section, you said "java out of bound" which is not a crash report file, it is a series of words. I would appreciate a crash report file, or alternatively post on mclo.gs
