### ISSUE TITLE
Ladders not working and trees doesn't have leaves

### ISSUE THREAD

**Issue by puddovsky** [LunaPixelStudios/Better-MC#884]
### Describe the Bug

All ladders and vines do not work, you can't walk on them.
In addition, half of the trees have no leaves.
The tree chopping mod doesn't work either

### Reproduction Steps

1.
2.
3.
...

### Operating System

Win 10

### Minecraft Version

1.16

### Modloader

Fabric

### Modpack Version

bettermc v6

### Optifine

No

**Comment by xSHXRKIEx** [comment]
we dont have 1.16 fabric modpack?

**Comment by chorbintime** [comment]
We don't have a 1.16 Fabric modpack and we also don't have any modpacks that have v6 as the latest version lol
