### ISSUE TITLE
Server randomly crashing multiple times a day

### ISSUE THREAD

**Issue by lucasschmitz-dev** [LunaPixelStudios/Better-MC#885]
### Describe the Bug

bug report is linked: https://pastebin.com/8qSHsF0d

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/8qSHsF0d

### Operating System

Linux (amd64) version 5.15.0-52-generic

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC Server Pack FORGE 1.19.2 v10

### Optifine

No

### Other Mods

Server:
Dynamic View
Create
BetterCreeper
FastWorkbench (and Placebo)
EasierVillagerTrading reForged
//Backups only once a day!

Client:
Farsight
Create
FastWorkbench (and Placebo)
EasierVillagerTrading reForged

**Comment by xSHXRKIEx** [comment]
Update to v10.5
