### ISSUE TITLE
Blazeborn Thirst and Heat Inconsistency

### ISSUE THREAD

**Issue by HalfDecent** [LunaPixelStudios/Better-MC#886]
### Describe the Bug

When choosing Blazeborn as your starting origin, even with starting in the nether, both your thirst meter from Dehydration and heat meter from EnviromentZ are not effected in any way. However, after one death, both thirst and heat are negatively affected right away.  When starting as other origins, both temperature and thirst are concerns starting at the beginning, no death required. 

Either way; Blazeborn should either be thirst-less/heat immune always or never and this should not be affected by death. 

### Reproduction Steps

1. Start a survival single or multiplayer world and select Blazeborn as your starting origin. 
2. Stand near/in lava, magma or fire and observe no heat gain or thirst loss. 
3. Find a way to die. My favorites are fall damage, hoglins and starvation.
4. Respawn and stand near/in lava, magma or fire and observe the heat meter changing rapidly. Shortly afterward thirst will also be affected.
5. Start a new survival game as any other origin. Observe changes in temperature and thirst changes soon after start.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2v13HF

### Optifine

No

**Comment by chorbintime** [comment]
This is not an issue on our side unless I overlooked a config option. I would suggest asking the dev of the Origins mod about this.

Also, you are not playing Better MC. You're playing Medieval.
