### ISSUE TITLE
Pillager Raids causing crash and preventing to players to join servers 

### ISSUE THREAD

**Issue by SgrullamiLeMele** [LunaPixelStudios/Better-MC#887]
### Describe the Bug

A while ago one of my friends encountered an error which caused him not to be able to join the server anymore. In order to fix it, we had to edit his position in game through the playerdata files, but didn't know the source that caused this... Except for the fact that he died during a raid and respawned in the village. Today, i got the same issue, except i didn't die, i just used a waystone home and then back to the village. The cause of this error is raids, whenever you go far away and come back to it. 

EDIT: I saw other people having this same problem on another modpack, Medieval... Something occurred to me, might it be It Takes A Pillage? Both modpacks are using that mod.  

### Reproduction Steps

1. Cause a raid in a village
2. Use a waystone to somewhere and then use it back to te raided village
3. Enjoy the errors

This error doesn't happen in singleplayer, try it in a server.
...

### Screenshots and Videos

![Immagine 2022-11-29 142047](https://user-images.githubusercontent.com/119422857/204539848-69431f93-def6-4776-8b5b-8e0fb2d932c4.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v11

### Optifine

No

**Comment by chorbintime** [comment]
There are 4 potential fixes; change the coordinates in your playerdata with NBTStudio, have someone /kill you (its possible! a command block will help), delete your playerdata completely, or set the difficulty to peaceful
