### ISSUE TITLE
Better MC fabric Farmers dont trade

### ISSUE THREAD

**Issue by heim404** [LunaPixelStudios/Better-MC#888]
### Describe the Bug

The farmers dont trade

### Reproduction Steps

1.Find a farmer
2.Right click
3.hhhaaam
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

### Optifine

No

**Comment by xSHXRKIEx** [comment]
This is a current known issue, its due to the paradise lost mod and waiting for an update from them

**Comment by chorbintime** [comment]
Now fixed by Paradise Lost devs. Mod will be updated in both modpacks soon.
