### ISSUE TITLE
Double doors can't open

### ISSUE THREAD

**Issue by user182898** [LunaPixelStudios/Better-MC#889]
### Describe the Bug

when I go to open a double door it will appear to open for a few frames then close back a few frames later. When standing right next to the double door and spamming open the door acts like I'm walking into a wall, 

### Reproduction Steps

1. walk towards the double door
2. right click
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10.5.zip

### Optifine

No

### Other Mods

just the base mod pack

**Comment by KruegerWoods** [comment]
hello im having the same issue with double doors, when i go to right click on them they will open for like half a second and then close right after.

**Comment by xSHXRKIEx** [comment]
Remove the double doors mod, it will be fixed in the next update

**Comment by villaxd123** [comment]
Removing doubledoors works for me, thanks.
