### ISSUE TITLE
Graveyard

### ISSUE THREAD

**Issue by d1nked2** [LunaPixelStudios/Better-MC#890]
### Describe the Bug

Went into the minecell dimension, and went to beat the conjuctivitus. I died and because of the tentacles broke my grave, my items were destroyed, i went back 30 seconds later and the items were gone. Not sure if this is a bug or normal. 

### Reproduction Steps

1. battling conjutivitus
2. die while in the tentacle phase
3. grave will be broken with no return of items
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v13

### Optifine

No

**Comment by xSHXRKIEx** [comment]
This is the BetterMC github not Medieval
