### ISSUE TITLE
Overworld, The BumbleZone and The Twilight Zone block textures aren't loading

### ISSUE THREAD

**Issue by 101dolphinwolf101** [LunaPixelStudios/Better-MC#891]
### Describe the Bug

Literally says in the title. i cannot play in the overworld the bumblezone or the twilight zone. i only see entities.

### Reproduction Steps

i dont know how i made this bug

### Screenshots and Videos

![Minecraft Screenshot 2022 11 30 - 13 52 26 56](https://user-images.githubusercontent.com/14960237/204908768-00be2462-038e-467e-80f4-dfeaf3169320.png)
![Minecraft Screenshot 2022 11 30 - 13 53 11 32](https://user-images.githubusercontent.com/14960237/204908777-7dd12262-2049-4371-ba75-56d3cf36e804.png)
![Minecraft Screenshot 2022 11 30 - 13 53 24 10](https://user-images.githubusercontent.com/14960237/204908781-e72e0ab6-3857-499e-8575-724f017ee6ca.png)
![Minecraft Screenshot 2022 11 30 - 14 07 16 87](https://user-images.githubusercontent.com/14960237/204908784-a5ca1d99-39c4-49cd-ad83-f28f0bc772a7.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC V11

### Optifine

No

**Comment by chorbintime** [comment]
Can you try reloading chunks?
