### ISSUE TITLE
"Not A JSON Object" crash on newer updates

### ISSUE THREAD

**Issue by bumblebwee** [LunaPixelStudios/Better-MC#892]
### Describe the Bug

I had recently updated BetterMC for my multiplayer server and somewhere between the last update and this most recent update, something broke. Whenever I open the server, the message I get says something about a randomly generated Croptopia fruit/veggie/etc and how there's no JSON object. I've ensured it's properly downloaded on both client and server, tried to even restart my entire world with no luck.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2022-11-30 152956](https://user-images.githubusercontent.com/119540580/204912233-40a21db6-ef77-4fe1-ae95-227a4bd26482.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v10 and bmc v10.5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Croptopia is not in the modpack so you had to have added it and should remove it
