### ISSUE TITLE
xp not increasing with mob kills or xp showers. XP gaining is broken

### ISSUE THREAD

**Issue by Ap0thicaDeath** [LunaPixelStudios/Better-MC#893]
### Describe the Bug

when killing mobs of any kind or standing in an xp shower, no one is gaining xp or going up in levels.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v11

### Optifine

No

**Comment by chorbintime** [comment]
How is your server being hosted?

Is this a new issue? Was it happening before?

Does it happen in singleplayer?

**Comment by Ap0thicaDeath** [comment]
server is being hosted through bisect hosting. this has been like this since I started the server. Not sure about single player.

**Comment by chorbintime** [comment]
Well, it shouldn't be happening, and it's not happening to anyone else. I would suggest setting up a selfhosted server (only takes two minutes. Download the serverpack from the modpack's Curseforge page and then read the readme file) on your own PC and see if the issue happens there, or run a vanilla server through Bisect, and see if the issue persists.

Also, try singleplayer.
