### ISSUE TITLE
Hoppers won't feed composters

### ISSUE THREAD

**Issue by zero2kx** [LunaPixelStudios/Better-MC#894]
### Describe the Bug

When a hopper is placed on top of a composter and filled with compostable items, the items will not travel from the hopper into the composter. 

### Reproduction Steps

1.Place hopper on top of composters
2. Insert compostable item into hopper
3. Nothing happens
...

### Operating System

Windows 11 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC 3 1.19.2

### Optifine

No

### Other Mods

Create FORGE 1.19.2 v0.5.0f

**Comment by chorbintime** [comment]
add `mixin.block.hopper=false` in canary.properties in config folder

**Comment by chorbintime** [comment]
> Hello, did you fix the problem? I have the same problem, but no ability to fix it myself, need a guide.

add `mixin.block.hopper=false` in canary.properties in config folder

**Comment by baflo** [comment]
I lose all content of all chests, if I change this setting. Is there a way to keep the contents?
