### ISSUE TITLE
I can't use shaders [BTMC - 1.19.2] [Forge]

### ISSUE THREAD

**Issue by villaxd123** [LunaPixelStudios/Better-MC#897]
### Describe the Bug

I'm trying to use shaders as the modpack page says and can't use them.
![imagen](https://user-images.githubusercontent.com/29488884/205551182-b96ca8f7-d7fc-4c71-835b-d722ed7cdaeb.png)
The option is not implemented as i think.
![imagen](https://user-images.githubusercontent.com/29488884/205551272-61f979bd-8ccf-461c-8657-3dd9fe778c7a.png)

### Reproduction Steps

1. Open Minecraft
2. Go to Video Settings 
3. Don't find Shaders Option

### Screenshots and Videos

![imagen](https://user-images.githubusercontent.com/29488884/205551182-b96ca8f7-d7fc-4c71-835b-d722ed7cdaeb.png)
![imagen](https://user-images.githubusercontent.com/29488884/205551272-61f979bd-8ccf-461c-8657-3dd9fe778c7a.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 v10.5

### Optifine

No

### Other Mods

Apple Skin
Craft Tweaker
Framed Blocks
Inventory HUD
Just Zoom
Konkrete
No Recipe Book Reborn
Sophisticaded Backpacks
Sophisticaded Storage
Sophisticaded Core
Trash Slot

**Comment by xSHXRKIEx** [comment]
You are on a older version or you are using a cracked launcher, which one?

**Comment by villaxd123** [comment]
I'm using an official launcher and the lastest version of the modpack (v10.5).
![imagen](https://user-images.githubusercontent.com/29488884/205574878-6943e3de-b66d-4299-9f54-ccefdfbb0b6b.png)

**Comment by chorbintime** [comment]
Can you please give a step-by-step guide on how you're launching the modpack?

**Comment by villaxd123** [comment]
Steps:
- Starting from desktop
- Press Windows Key
- Write "mine" on this
- Open Minecraft Launcher
- Wait until it opens
- Press on "Jugar" (Play)
- Wait the loading process
- Minecraft loads the mods an all of his stuff
- Minecraft finishes his opening process
- I look on the settings
- Then i look on the video or graphics settings
- Did not found what i want
- Just play normal without shaders

If you need anything else to help with my issue, let me know.

**Comment by chorbintime** [comment]
Thats not how you play modpacks. You need to launch directly from the modded launcher you are using.
