### ISSUE TITLE
Failed to verify username!

### ISSUE THREAD

**Issue by fedyaka** [LunaPixelStudios/Better-MC#898]
### Describe the Bug

I play with tlauncher/
Uploaded via cruseforge, but transferred all the files to the .minecraft folder.

When i try to connect to the server i get an error:
Failed to verify username!
log:
[11:51:38] [User Authenticator #6/INFO]: Disconnecting /127.0.0.1:1326: Failed to verify username!
[11:51:38] [User Authenticator #6/ERROR]: Username 'fedyaka' tried to join with an invalid session
[11:51:38] [Server thread/INFO]: /127.0.0.1:1326 lost connection: Failed to verify username!

Maybe something else needs to be done?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v12

### Optifine

No

**Comment by chorbintime** [comment]
We offer no support for TLauncher whatsoever. It is very unstable and is also a known virus.

**Comment by fedyaka** [comment]
What launchers does it support?  Or how to turn off this security, because there have never been problems with tlauncher

**Comment by fedyaka** [comment]
> We offer no support for TLauncher whatsoever. It is very unstable and is also a known virus.

What launchers does it support? Or how to turn off this security, because there have never been problems with tlauncher.

**Comment by fedyaka** [comment]
> > We offer no support for TLauncher whatsoever. It is very unstable and is also a known virus.
> 
> What launchers does it support? Or how to turn off this security, because there have never been problems with tlauncher.

I figured out how to enable account verification
in server.properties:
online-mode=false
:)
