### ISSUE TITLE
Issue with Toms Simple Storage Mod

### ISSUE THREAD

**Issue by Xylunar** [LunaPixelStudios/Better-MC#899]
After update v12 the when opening crafting terminal or wireless crafting terminal it causes a ton of lag, and it makes it extremely hard to move or craft items.

**Comment by danif86** [comment]
here too

**Comment by chorbintime** [comment]
Report on Tom's Simple Storage github. It might not even be an issue at all. You could just have a lot of entities in your storage system. But there's nothing we changed except for updating the mod which could cause it.

Alternate Current or ImmediatelyFast are the only two mods which we added that could possibly cause it. You can try deleting both.

**Comment by danif86** [comment]
> Report on Tom's Simple Storage github. It might not even be an issue at all. You could just have a lot of entities in your storage system. But there's nothing we changed except for updating the mod which could cause it.
> 
> Alternate Current or ImmediatelyFast are the only two mods which we added that could possibly cause it. You can try deleting both.

Alternate Current or ImmediatelyFas = no effect removing.

It is working normaly with v11, so something happend?

**Comment by danif86** [comment]
Tried V11 again. and no lag.. :/
