### ISSUE TITLE
the medieval reasource pack does not work

### ISSUE THREAD

**Issue by StartingAura008** [LunaPixelStudios/Better-MC#900]
### Describe the Bug

when i started playing i had the reasource pack with all the cool skins and weapons and blocks. but after sigining in for the third time. and everything looks like the base vanilla textures and i dont know how to revert it back to the way this mod was suppose to look like

### Reproduction Steps

1.
2.
3.
...
when i started playing i had the reasource pack with all the cool skins and weapons and blocks. but after sigining in for the third time. and everything looks like the base vanilla textures and i dont know how to revert it back to the way this mod was suppose to look like

### Operating System

Windows 10

### Minecraft Version

1.12

### Modloader

Fabric

### Modpack Version

medieval MC minecraft

### Optifine

No

**Comment by chorbintime** [comment]
Reinstall with GDLauncher
