### ISSUE TITLE
the double doors is broken

### ISSUE THREAD

**Issue by Hamzagabe** [LunaPixelStudios/Better-MC#904]
### Describe the Bug

hello i want to report a bug ,when ever i open a double door it opens and closes at the same second

### Reproduction Steps

1.place 2 doors next to each other as if you're making a double door entrance
2.second try to open the doors
3.you will see the doors open and close in one second from one click
...

### Screenshots and Videos

https://user-images.githubusercontent.com/114304957/206632404-abd77db5-9412-44cd-a13d-a85b8bbbe95a.mp4

### Operating System

windows11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10,5

### Optifine

No

**Comment by xSHXRKIEx** [comment]
Duplicate #889
