### ISSUE TITLE
Wine Boxes and Storage does not work properly

### ISSUE THREAD

**Issue by MrSirLIVE** [LunaPixelStudios/Better-MC#905]
### Describe the Bug

Item description states to Shift Right-Click on Wine Box to open/close the box, Shift Right-Clicking instead picks up the box, same is true for the Small and Big Wine Bottle Storage blocks

### Reproduction Steps

1.Shift Right-Click on Wine Bottle Storage block or Wine Box block
2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/120224559/206805248-b9a78988-996f-4f37-96ff-3af31779efa1.mp4

### Crash Report or Log

N/A

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Fabric

### Modpack Version

v12.5

### Optifine

I used Optifine

### Other Mods

N/A

**Comment by MrSirLIVE** [comment]
***Minecraft Version is 1.19.2***

**Comment by chorbintime** [comment]
You are not using Optifine. Optifine is not a Fabric mod. It is incompatible with all of our modpacks and is a terrible mod in any context.

Wine boxes will be excluded from the Carrier mod in the next update.
