### ISSUE TITLE
Everything is invisible whithout shaders on. (Better Minecraft [Fabric] - BMC1)

### ISSUE THREAD

**Issue by alexnikou** [LunaPixelStudios/Better-MC#907]
### Describe the Bug

The bug is on Better Minecraft [Fabric] - BMC1

I create a world with shaders on, and when I turn them off, everything was invisible. But when I turn them back on, everything is normal.
![2022-12-10_23 49 06](https://user-images.githubusercontent.com/120282325/206876560-fb3b5798-38cc-4ece-98a9-3c9ecfacfc25.png)
![2022-12-10_23 49 13](https://user-images.githubusercontent.com/120282325/206876719-40389743-ac79-4eda-94d9-fa3bfacb266e.png)

### Reproduction Steps

1. Open Better Minecraft [Fabric] - BMC1
2. Create a world with shaders on
3. Remove shaders because 30fps

### Operating System

Windows 10 Home 21H2

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better Minecraft [Fabric] - BMC1

### Optifine

No

### Other Mods

Every mod that Better Minecraft [Fabric] - BMC1 has

**Comment by chorbintime** [comment]
Try reloading chunks with F3 + A

If that doesn't work, rejoin the world

**Comment by alexnikou** [comment]
I tried it and nothing, I create 2 worlds and still the same
