### ISSUE TITLE
Freeze and crash upon sleeping.

### ISSUE THREAD

**Issue by Zarepheth** [LunaPixelStudios/Better-MC#908]
### Describe the Bug

The first time I sleep, the game freezes, then eventually crashes - sometimes I assist the crashing by having MS windows kill the process when it stops responding.

I'm not sure if this is a problem with the mod-pack, or one of the extra mods I added to my Curse Forge Overwolf client profile.

In most cases, if I restart the game and let things stabilize, sleeping seems to work. I'm wondering if something resets when updating a mod, which then causes the crash on the next sleep attempt.

### Reproduction Steps

Using the Curse Forge Overwolf client:
1. Update the modpack or one of its mods.
2. Click "Play" to start the Minecraft launcher.
3. Click "Play" on the launcher to start the game.
4. Wait for game to start.
5. Select "Single Player".
6. Select my saved game.
7. Wait for saved game to load.
8. Do stuff in the game.
9. Return to base and sleep in bed.
10. Expect screen to dim, time to accelerate, and to reach morning in 1-15 seconds. Instead, game freezes. It may "gracefully" crash to desktop, saving state as it dies -- or it may stop responding and input attempts on the window (like clicking the mouse) may bring up MS Window's option to close the non-responding app. Choosing to close also crashes to desktop - which is sort of expected...

### Crash Report or Log

https://gist.github.com/Zarepheth/fdd328172fcddc29eedc898c061101c7

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v12,5

### Optifine

No

### Other Mods

A whole bunch, the full list is mixed with the modpack's mods in the crash report.

Mods of significance:
* **FTB Quests** (_part of modpack_), but stack trace points here.
* **Realistic Sleep** - because the crash occurs just before this mod ought to accelerate time.
* **Twilight Forest** (_part of modpack_)
* **Immersive Portals** (potential conflict with Twilight Forest - but so far, I've not had any problems obviously linked to such conflict)

**Comment by chorbintime** [comment]
Does the issue persist with the added mods removed? It's very likely an issue with something you added, probably Realistic Sleep.

**Comment by Zarepheth** [comment]
I removed realistic sleep and have not experienced the problem since.
