### ISSUE TITLE
Minecraft crashing while destroying Chests

### ISSUE THREAD

**Issue by lucasschmitz-dev** [LunaPixelStudios/Better-MC#909]
### Describe the Bug

Minecraft is crashing, when me or a friend destroyes a chest.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/lucasschmitz-dev/132b6ffab6927429bc642caba91a2f6c

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 v11

### Optifine

No

### Other Mods

Create is added to the mods folder, both client and server

**Comment by chorbintime** [comment]
Was a newly generated buried treasure map inside the chest?

**Comment by lucasschmitz-dev** [comment]
Content of the chest doesnt matter. This happens on empty chests too.

**Comment by chorbintime** [comment]
Please send a crash report from when you break an empty chest. Video would be nice aswell

**Comment by JustifYI** [comment]
In my case, if I try to open the chest from the lighthouse, my local server will crash without any log. I have to manually terminate the process since the server will not listen/perform any command.

![2022-12-14_17 45 58](https://user-images.githubusercontent.com/47337816/207657444-ed88bbe5-c94c-4a5a-9d3f-f3a6e7a007f3.png)
![2022-12-14_17 46 09](https://user-images.githubusercontent.com/47337816/207657460-760331f0-f892-4461-b2e9-9c817935a2f7.png)

**Comment by chorbintime** [comment]
> In my case, if I try to open the chest from the lighthouse, my local server will crash without any log. I have to manually terminate the process since the server will not listen/perform any command.
> 
> ![2022-12-14_17 45 58](https://user-images.githubusercontent.com/47337816/207657444-ed88bbe5-c94c-4a5a-9d3f-f3a6e7a007f3.png) ![2022-12-14_17 46 09](https://user-images.githubusercontent.com/47337816/207657460-760331f0-f892-4461-b2e9-9c817935a2f7.png)

Please send a crash report. Video would be nice aswell

**Comment by lucasschmitz-dev** [comment]
IMPORTANT: This may be related to: https://github.com/microsoft/openjdk/issues/337

I cant reproduce it right now, maybe this was an NVIDIA error? You can close this issue, if you want to. I will reopen, when I have a video of the issue or further information.
