### ISSUE TITLE
Server crashing with 3-4 People BMC3

### ISSUE THREAD

**Issue by AzuBeep** [LunaPixelStudios/Better-MC#910]
### Describe the Bug

I recently made a BMC3 server for a group of friends, however people are reporting the server _crashing with only 3 or 4 people._
One user reported an error of "java.net.socketexception connection reset"
Others report "Timed out: lost connection to server"

>  It starts to chug a lot with 4 or more people. Even with fewer people there is the occasional lag spike. The error message I always get is "Timed out: lost connection to server"
After a little bit of waiting we can jump back on the sever, but too many people and it will just kick everyone off again

The server is being accessed from multiple international locations.

I am using Forge 43.1.57, and Minecraft 1.19.2 with the Better MC Forge - BMC3.

I will attach the error logs below.

The specs for the server are:
Ubuntu Server 22.04.1 running as a VM on Unraid 6.11.0
Unraid is running on a Dell R710 with 120GB installed/98GB usable RAM, and 2x Intel® Xeon® CPU L5640 @ 2.27GHz.
The VM is assigned: 16GB RAM, initially 4 CPU threads, then 8, and is running off of the cache drive, which is a 500GB Samsung 980 Pro NVMe SSD.
The server is being hosted on a custom subdomain on my own domain, using CNAME records on Cloudflare to point to the DDNS address provided by TP-Link.

### Reproduction Steps

1.A 3rd or 4th person joins the server and it chugs then crashes.
2.
3.
...

### Crash Report or Log

https://pastebin.com/8Zk4TFUj

### Operating System

Ubuntu Server 22.04.1(host), Windows 10 (clients)

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC Server Pack FORGE 1.19.2 v10.5

### Optifine

No

**Comment by AzuBeep** [comment]
One forum post suggested removing Quark as one test, I will attempt this and monitor.

**Comment by chorbintime** [comment]
Removing mods randomly is not a viable solution.

Please follow this guide:
https://github.com/etil2jz/etil-minecraft-flags 

If lag persists, do the following command ingame:
/spark profiler --interval 100

You may need to run the spark stop command.

Then, reply with the spark link.
