### ISSUE TITLE
Previous Worlds not loading at all

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/Better-MC#911]
### Describe the Bug

Hey im not too sure why my previous worlds are refusing to load at all. Booting up is completely fine however when i attempt to go into a world i keep playing on it just doesnt load and continuously loops in the "Not Responding" stage and the "Responding" stage. This is also the case when doing as requested with the Resource/Texture Packs. The entire game crashes and only ending it in Task Manager actually stops the application when you want to reset it from Curseforge.

### Reproduction Steps

this is a loading issue.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/106572267/207211554-5634f4a5-623b-4e8e-b139-d73e1c6b4011.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11

### Optifine

No

**Comment by chorbintime** [comment]
Do not click while the game loads. Let it load.

How much RAM have you allocated to the game?

What launcher are you using?

**Comment by FevilGitHub** [comment]
Curseforge Launcher, the usual to boot it up. I have never clicked on it though it constantly faded white while in the loop.

**Comment by chorbintime** [comment]
https://youtu.be/P3hd9MKWvXw?t=130
