### ISSUE TITLE
Toms Storage Delay

### ISSUE THREAD

**Issue by KDC900** [LunaPixelStudios/Better-MC#912]
### Describe the Bug

When using advance wirless terminal there is lag between adding items and getting items from storage. Was not an issue in the last version but when the server admin updated to 12.5 it has a delay for everyone on the server even if you are on alone.

### Reproduction Steps

1.Open Advance wirless Terminal 
2.Add or remove items

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

cf_BetterMinecraftFABRIC_1.19.2_12.5.jar

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
You did not use Optifine. Optifine is not a Fabric mod. It is very incompatible with every modpack and is an all-around bad mod.

This is an issue with the Wilder Wild mod. It's an issue with the recipe book in specific. Simply close the recipe book in the simple storage GUI to fix this.
