### ISSUE TITLE
I can't attack when I click on my mouse.

### ISSUE THREAD

**Issue by Bangtangurlss** [LunaPixelStudios/Better-MC#913]
### Describe the Bug

I'm on a Mac and the mouse that I use is a Magic Mouse. but it never had an issue with the attack. im not sure if it's an issue only for me. 

### Reproduction Steps

1.trigger attack by clicking left on the mouse. 
2.
3.
...

### Operating System

Mac OS ventura version 13.0.1

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Fabric - 0.14.10

### Optifine

No

**Comment by chorbintime** [comment]
Try rebinding your attack to left mouse button
