### ISSUE TITLE
Better MC launch error

### ISSUE THREAD

**Issue by tong1543** [LunaPixelStudios/Better-MC#915]
### Describe the Bug

Hi I am a newbie on playing with Minecraft mob.

I have tried to install the mobpack but there was an error pop out as attached log file.

Appreciate if you could advise on this.
[hs_err_pid25948.log](https://github.com/LunaPixelStudios/Better-MC/files/10224240/hs_err_pid25948.log)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

Better MC [FABRIC] 1.19.2 v12.5.zip

### Optifine

No Optifine

**Comment by chorbintime** [comment]
The top of the log you sent already details several solutions:

# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Zero Based Compressed Oops mode in which the Java heap is
#     placed in the first 32GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 32GB virtual address.
# This output file may be truncated or incomplete.


Also, how are you installing the modpack?
