### ISSUE TITLE
1.19.2 starting error cloth-utils-v1 (fabric)

### ISSUE THREAD

**Issue by doubleaxes** [LunaPixelStudios/Better-MC#916]
**Describe the Bug**

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cloth-utils-v1'!

exit code:-1

**Reproduction Steps**
...

**Screenshots and Videos**
No response

**Crash Report or Log**
No response

**Operating System**
Windows 10

**Minecraft Version**
1.19.2

**Modloader**
Fabric

**Modpack Version**
Better MC [FABRIC] 1.19.2 v12.5.zip

Optifine
No Optifine

Other Mods
No response

**Comment by chorbintime** [comment]
Relaunch 3 times
