### ISSUE TITLE
Everyone can't do anything 

### ISSUE THREAD

**Issue by Alfikcz666** [LunaPixelStudios/Better-MC#917]
### Describe the Bug

when someone opens the door, write [MAIN HAND] you are not allowed to interact with this block in the chat

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot_20221214-191911_Discord](https://user-images.githubusercontent.com/77681831/207691926-5abbee77-5e70-490d-9bf1-d7d39b90e967.jpg)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V6

### Optifine

No

**Comment by chorbintime** [comment]
It says in chat what you need to do. You need an empty hand.
