### ISSUE TITLE
game crash when entering nether

### ISSUE THREAD

**Issue by Izisogxc** [LunaPixelStudios/Better-MC#919]
### Describe the Bug

Built a nether portal and hopped in, it reads "joining world" and crashes. first time entering the nether too.

### Reproduction Steps

1. Build a Nether Portal.
2. Enter the nether.
3. Crash?

### Screenshots and Videos

https://user-images.githubusercontent.com/120601734/207715572-4ef16f95-e550-4c11-90d2-83e04ea70f43.mp4

### Crash Report or Log

https://gist.github.com/Izisogxc/0a8a7f7ad1c3a7a2eb8f1c3ef3a6b77b

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v11

### Optifine

I used Optifine

### Other Mods

MCA Reborn (Minecraft Comes Alive Reborn)
Litematica Fabric
EnchantingInfuser
Malilib Fabric
Optifine

**Comment by chorbintime** [comment]
Does the issue persist with the added mods removed?

How much ram have you allocated?

Also try deleting all versions of java on your computer and just installing Java 18 from here 
https://adoptium.net/temurin/releases/?version=18 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
