### ISSUE TITLE
#914 was closed with close to no   info 

### ISSUE THREAD

**Issue by kitsunex3** [LunaPixelStudios/Better-MC#920]
### Describe the Bug

#914 was closed with the info " read the readme"  , readme says nothing about this issue  was not able to re-open my ticket . 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

11

### Optifine

No

**Comment by chorbintime** [comment]
The readme details how to properly run the modpack. You installed the modpack incorrectly on either client or serverside. Try using GDLauncher to install and play the modpack.

**Comment by kitsunex3** [comment]
installed trough the GDLauncher launcher ,  and i reinstalled  the server side with the adviced powershell script . 

 still getting the same error

**Comment by chorbintime** [comment]
You're doing something wrong. This isn't a modpack issue. Could you give full steps on what you're doing to both launch the game and install the server?

**Comment by kitsunex3** [comment]
i found the error ,  it was in the backup of my world  , probly the config that is incompattible , deleted the   serverconfig  folder  and if  ran ok
