### ISSUE TITLE
Minecraft crashes after enabling/disabling resourcepacks

### ISSUE THREAD

**Issue by ChelloVibes** [LunaPixelStudios/Better-MC#921]
### Describe the Bug

After I configure my Resourcepacks in the options to enable the new packs added in v11 and I hit the Done Button, Minecraft proceeds to load for a solid 10 minutes or so and then just straight up crashes with the error message "Crashed whilst rendering overlay". I already tried editing `options.txt` and get the Resourcepacks enabled from there (didn't work obviously).

### Reproduction Steps

1. Go to the resourcepacks menu
2. Select resourcepacks to enable
3. Hit "Done", Minecraft will load and then crash

### Screenshots and Videos

![Screenshot (93)](https://user-images.githubusercontent.com/107318006/207910243-e846d75e-0bf9-43bf-b02e-4e61b1386266.png)
![Screenshot (92)](https://user-images.githubusercontent.com/107318006/207910869-cd98e424-d490-4b96-a8a4-635b49ad2b40.png)

### Crash Report or Log

https://gist.github.com/ChelloVibes/67eb64f12d675f63e7ce7e71c25292da

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge (CurseForge Launcher)

### Modpack Version

Better MC [FORGE] BMC3 v11

### Optifine

No

### Other Mods

None

**Comment by chorbintime** [comment]
How much memory do you have allocated to MC?

You can also do a clean reinstall and transfer your world to have the resourcepacks enabled.

**Comment by ChelloVibes** [comment]
> How much memory do you have allocated to MC?
> 
> You can also do a clean reinstall and transfer your world to have the resourcepacks enabled.

Its 4096MB like it is by default. I tried to increase it but it wouldnt let me start the game when i put 5GB or higher.

**Comment by chorbintime** [comment]
> > How much memory do you have allocated to MC?
> > You can also do a clean reinstall and transfer your world to have the resourcepacks enabled.
> 
> Its 4096MB like it is by default. I tried to increase it but it wouldnt let me start the game when i put something higher.

Please elaborate. In what way were you being prevented from starting the game?

Allocate 8 gigabytes of ram.

**Comment by ChelloVibes** [comment]
The game just did not start. Clicked the Play button but didn't do anything. But I got it to work because I was using the Vanilla Launcher Instance to allocate more memory, when i didn't realize i could change it in the CurseForge Launcher itself. So I allocated 8GB of memory but it still crashes.

**Comment by chorbintime** [comment]
I need a crash report.

**Comment by ChelloVibes** [comment]
Ok so, when i tried to reproduce the crash again to get a new crash report it just worked for some reason? Well i guess i somehow got it to work.
