### ISSUE TITLE
Dragon egg better mc 1.19.2 fabric

### ISSUE THREAD

**Issue by Kanekinos** [LunaPixelStudios/Better-MC#922]
### Describe the Bug

Deahon eggs wont spawn since first killed dragon can u guys help?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Win 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
You can get more dragon eggs from the VoidZ dimension. 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
