### ISSUE TITLE
Server not starting. 1.19.2

### ISSUE THREAD

**Issue by mendezEsteban** [LunaPixelStudios/Better-MC#924]
### Describe the Bug

Get error when trying to start the powershell start file.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

<img width="863" alt="Screenshot 2022-12-17 130602" src="https://user-images.githubusercontent.com/90410362/208258966-756bc3d0-ce7c-4a8f-911e-945265656167.png">

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
Remove spaces from the file path
