### ISSUE TITLE
Game crashing at launch

### ISSUE THREAD

**Issue by xArzeus** [LunaPixelStudios/Better-MC#925]
### Describe the Bug

As the title suggests, the game crashes when launching with exit code 1. Tried to go through logs to see the pb but wasn't able to solve it.

Crash logs from BetterMC : 
[latest.log](https://github.com/LunaPixelStudios/Better-MC/files/10252805/latest.log)
Crash logs from launcher : 
[hs_err_pid8924.log](https://github.com/LunaPixelStudios/Better-MC/files/10252809/hs_err_pid8924.log)

I updated BetterMC version to 11 ( latest ) tried to repair the profile, but it didn't work.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v11

### Optifine

No

**Comment by chorbintime** [comment]
Resolved in Discord. Was an issue with AMD drivers and using Microsoft OpenJDK.
