### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by mushroomiez** [LunaPixelStudios/Better-MC#926]
Hello, I'm pretty new to learning how modpacks work but I just installed this one through aternos (just went to software and it was an option to install so i clicked that and did) and when i started it up this happened??? is there something else i need to install for it to work correctly?
![image](https://user-images.githubusercontent.com/120846258/208268284-72584a3f-c06f-4b9a-9962-c1bef7b49b91.png)

**Comment by chorbintime** [comment]
You need the modpack installed on the clientside. Use a modded launcher such as GDLauncher to install & play modpacks.
