### ISSUE TITLE
Sometimes getting stuck at the encrypting screen when trying to join my server

### ISSUE THREAD

**Issue by ChelloVibes** [LunaPixelStudios/Better-MC#930]
### Describe the Bug

So I got two Aternos servers for me and a friend of mine. And the problem is that sometimes (actually most of the time) when i try to join one of those servers it fails with "Disconnected", and then when I try to log into the server again I get stuck at the Encrypting screen. Also the cancel button stops working and when i try to click it, it crashes the game, so I have no other choice other than to end the games process with the task manager. You can surely image that waiting for the game to start again only for it to happen again is quite annoying. So all help is appreciated. Although this does not happen to my friend.

### Reproduction Steps

1. Join any server
2. That's litteraly it.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] BMC3 v11

### Optifine

No

### Other Mods

None

**Comment by chorbintime** [comment]
Stop using Aternos. Just selfhost using the serverpack.

It's likely an Aternos issue. It's slow.
