### ISSUE TITLE
Inventory items bugged out? - MultiMC launcher on Linux(Ubuntu 22.04.1)

### ISSUE THREAD

**Issue by MiniYM** [LunaPixelStudios/Better-MC#931]
### Describe the Bug

All items in my inventory will overlay the screen but the menu itself goes away.
-doesn’t affect gameplay mechanics besides viewing what is around the crosshairs

### Reproduction Steps

1. Make a multiMC world (fabric loader 0.14.10) (1.19.2 MC version)
2. Upload all mods and resource packs
I also added optifine for 1.19.2 and seus renewed v1.0.1 shaders
3. Play and fill up inventory (maybe load shaders on and off?)
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/121077433/208585256-041bfd0d-a703-46be-b964-5dfad1f56457.jpg)

### Operating System

Ubuntu 22.04.1

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 - v12.5

### Optifine

I used Optifine

### Other Mods

Optifine for 1.19.2
Shaders) seus renewed v1.0.1

**Comment by chorbintime** [comment]
You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

Press I. You turned on Extended Inventory. It could also be the hotbar swapper, which should be ALT.

**Comment by MiniYM** [comment]
Awesome, thanks! I’ll see if that fixes it.

- MiniYM
