### ISSUE TITLE
Double door´s close immidiately when i open them (medieval MC-MMC3

### ISSUE THREAD

**Issue by lilpeeplel** [LunaPixelStudios/Better-MC#932]
### Describe the Bug

when i place or try to open a double door they close immediately but if i place a trapdoor that works 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10.zip

### Optifine

No

**Comment by chorbintime** [comment]
Delete the Double Doors mod
