### ISSUE TITLE
All skeletons are purple entities

### ISSUE THREAD

**Issue by badpanda07** [LunaPixelStudios/Better-MC#933]
### Describe the Bug

upon entering the game, all of the skeletons appear as purple fuzzy blocks, no name is shown in the upper left and they all appear to be invincible

### Reproduction Steps

1.open game
2.all skeletons purple
3.die, alot
...

### Screenshots and Videos

![Untitled](https://user-images.githubusercontent.com/121137341/208783570-36ccf4dc-3aba-453e-9e3d-4d2cb6fac29f.png)

### Operating System

windows 11

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

12.5

### Optifine

No

**Comment by chorbintime** [comment]
That specific structure spawns invisible skeletons wearing enchanted armor. This is not an issue, nor are they showing up as purple fuzzy blocks.
