### ISSUE TITLE
Invisible giant block + game crashes when i try to break em

### ISSUE THREAD

**Issue by spawntraps** [LunaPixelStudios/Better-MC#934]
### Describe the Bug

when i get near to giant blocks everything is invisible, and if i try to break the gian block my game crashes.

This is the crash error i got 
https://pastebin.com/uvArpqs6

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image_2022-12-20_214342683](https://user-images.githubusercontent.com/121145559/208816561-930a1979-f427-4c45-abf2-7c0bdbf9aeb3.png)

### Crash Report or Log

https://pastebin.com/uvArpqs6

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v12.5

### Optifine

No

### Other Mods

no

**Comment by chorbintime** [comment]
Try updating the Twilight Forest mod. If the issue persists, report on Twilight Forest github.
