### ISSUE TITLE
Server crashing after opening randomly generated, vanilla Minecraft chest.

### ISSUE THREAD

**Issue by thegamer304** [LunaPixelStudios/Better-MC#935]
### Describe the Bug

Whilst playing on my BetterMC server, when I opened a chest found in some type of ocean structure, the whole server crashed. 

I am running the server on ubuntu 22.04.1 LTS, the server specs are the following:
12GB of ram
AMD A10-5800k

Attached, is the crash log. 
[crash-2022-12-20_09.24.32-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10279895/crash-2022-12-20_09.24.32-server.txt)
[crash-2022-12-19_18.58.55-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10279896/crash-2022-12-19_18.58.55-server.txt)

### Reproduction Steps

1. Find vanilla chest
2. open it
3. realize the server has frozen
4. get disconnected
5. look at error log and realize I have no idea what any of this means

### Operating System

Ubuntu 22.04.1 LTS

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Fabric 1.19.2 v12.5 (BMC1)

### Optifine

No

**Comment by chorbintime** [comment]
Likely due to https://github.com/microsoft/openjdk/issues/337

**Comment by thegamer304** [comment]
So what does this mean for the server? What do I have to do?

**Comment by chorbintime** [comment]
Stop using Microsoft OpenJDK. Switch to Adoptium Java 18. 
https://adoptium.net/temurin/releases/?version=18

**Comment by thegamer304** [comment]
That's what I currently have installed.

**Comment by chorbintime** [comment]
Its not. You have Java 17, but I'm unable to verify whether its Microsoft OpenJDK.

Retry with an Adoptium release of Java.

**Comment by thegamer304** [comment]
Yeah its not. 

On my machine running currently, I have the Adoptium release from 11-19 installed, as well as the default JRE, JRE 8 from ubuntu itself. 

When you have to troubleshoot this issue, specifically for linux, make sure you have the user run -java. It will list all the java installations on the machine. In order to fix this, have the user run "sudo apt-get remove --purge 'name of java here'", they may have to run this command multiple times in order to get rid of all of them.

My guess on why this happens is apt likes to install older version for compatibility reasons.
