### ISSUE TITLE
add optifine to BMC3 1.19.2 = Crash

### ISSUE THREAD

**Issue by Shikamiji** [LunaPixelStudios/Better-MC#936]
### Describe the Bug

When i add the Mod (Optifine H9 1.19.2) and try to start the game it Always  Crashes and says (Exit-Code: 1 )

What can i do to get BMC3 !.19.2 running with optifine

### Reproduction Steps

1.Download BMC3 1.19.2 From The Curseforge APP
2.Open the Mod
3.Open the mod folder
4.Download The Optifine H9 1.19.2 Mod (  https://optifine.net/adloadx?f=OptiFine_1.19.2_HD_U_H9.jar&x=0261  )
5.Drag the Optifine mod in the mod folder of BMC3 
6. Restart Minecraft Mod From the Curseforge APP
...

### Crash Report or Log

It Just says ( Exit-Code: 1 )

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11

### Optifine

No

### Other Mods

Not any other than Optifine

**Comment by chorbintime** [comment]
It is highly advised to not use Optifine, as it is very glitchy, will increase loading times to upwards of 10 minutes, and will decrease your FPS substantially. All Luna Pixel Studios modpacks come with shader support without Optifine via Oculus on Forge and Iris on Fabric. Optifine is also incompatible with all of our modpacks. The game will not launch with Optifine installed. 

If you are interested in Optifine alternatives for your own gameplay, you can find a list here https://github.com/LambdAurora/optifine_alternatives 
Note that a majority of these mods are already included in our modpacks.
https://cdn.discordapp.com/attachments/1046333354259259422/1046337216609271858/unknown.png

This is not a bug. It isn't something we will ever fix.
