### ISSUE TITLE
Server contains ore variants not present on client

### ISSUE THREAD

**Issue by Smith334** [LunaPixelStudios/Better-MC#938]
### Describe the Bug

I have installed a Better Minecraft Forge server (Better+MC+FORGE+Server+Pack+1.19.2+v11) and it is up and running on my computer. 
I have  then installed the Better Minecraft client (1.19.2+v11) on the same computer through curse forge.
When I now try and connect it shows a connection error in game about some missing ores on the client. I  have attached a screenshot of the logs after trying to connect

### Reproduction Steps

1.Download and Install forge server
2.Download and run the Better minecraft server
3.Copy files across to forge server directory. and start up
4.Install client through forge
5. try to connect

### Screenshots and Videos

![Screenshot 2022-12-23 114021](https://user-images.githubusercontent.com/28813931/209312811-8be12cb0-2042-44a2-9545-92c7d7735bf3.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2+v11

### Optifine

No

**Comment by chorbintime** [comment]
I would like to start by saying this is not an issue with our modpack. It is user/computer error.


Reinstall the modpack using ATLauncher. Make sure to install the opted out mods as it tells you.

If the issue persists, server configs are likely installed wrong.

**Comment by Smith334** [comment]
@chorbintime Thank you using ATLauncher, instead of the standalone curseforge launcher solved all my problems. Connects fine now.
