### ISSUE TITLE
Items vom Grab, wurden nicht zurück ins Inventar geschickt

### ISSUE THREAD

**Issue by Restic1** [LunaPixelStudios/Better-MC#939]
### Describe the Bug

Ein Kollege von mir starb während der Server am laggen war, vermutlich wollte er sein zeug währendessen nehmen, bekam jedoch nur wenige items wieder zurück. Was kann man tun? 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC

### Optifine

No

**Comment by chorbintime** [comment]
Use the `/yigd` command to retrieve items
