### ISSUE TITLE
Died, got following error on respawn: Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component 

### ISSUE THREAD

**Issue by LeoninJesterXII** [LunaPixelStudios/Better-MC#941]
### Describe the Bug

I died on a server a friend is hosting, and now I can't log into the game because of this error:

Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component 

None of the previous posts on this topic had a working fix.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

12.5

### Optifine

No

**Comment by chorbintime** [comment]
There are 4 potential fixes; change the coordinates in your playerdata with NBTStudio, have someone /kill you (its possible! a command block will help), delete your playerdata completely, or set the difficulty to peaceful
