### ISSUE TITLE
getting kicked all the time in new building: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@3a9cdfc2' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]

### ISSUE THREAD

**Issue by AhmetSine** [LunaPixelStudios/Better-MC#942]
### Describe the Bug

after entering the new building in the Nether i get kicked from the server, and everytime i try to join the server im getting kicked instantlly. 
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@3a9cdfc2' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot (1)](https://user-images.githubusercontent.com/116569218/209452522-f98f486a-aa5c-43ce-a916-e4d1eaa6cbef.png)

### Crash Report or Log

https://mclo.gs/qmii3Nh

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 BMC3 V11

### Optifine

No

**Comment by chorbintime** [comment]
Please post the log properly on a website such as mclo.gs

What do you mean "new building"?

**Comment by AhmetSine** [comment]
With the new Building i mean "Keeping Castle". I did post it on mclo.gs how should i send it to you or post a screenshot?

**Comment by chorbintime** [comment]
If this is only happening in the Keeping Castle, report it on Stalwart Dungeons github.
