### ISSUE TITLE
BMC3 v11 Torches don't go to same slot

### ISSUE THREAD

**Issue by TurboTophat** [LunaPixelStudios/Better-MC#943]
### Describe the Bug

when i accidentally place a torch and break it to pick it back up it doesn't go back to the stack it goes to a new slot in inventory 

### Reproduction Steps

1. place torch 
2. break torch 
3. open inventory and see it in a new solot

### Screenshots and Videos

https://user-images.githubusercontent.com/103705461/209457093-899b1ebf-eb04-4cf0-9b46-0cabcd0ec0e6.mp4

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc3 v11

### Optifine

No

**Comment by chorbintime** [comment]
Turn on Advanced Tooltips with, I think, F3 + H and send a screenshot of both torches.

**Comment by TurboTophat** [comment]
![toech 1](https://user-images.githubusercontent.com/103705461/209502494-75bdaafb-b21a-43e6-87f5-4eb6b7d3fb81.png)
![toech 2](https://user-images.githubusercontent.com/103705461/209502495-94ac30b8-2ccd-4ef8-bd92-97446344c2cf.png)

**Comment by chorbintime** [comment]
It seems like you've added mods? What did you add/remove?

**Comment by TurboTophat** [comment]
i removed jade and replaced it with one probe, i like a lot of Tech mods so i have most of the the popular tech mods out there like 
mekism + Addons
AE2 ( Applied Energistics 2 ) + Addons
Refined storage + Addons
RFTools + Addons
extreme reactors
building gadgets

i think Applied Energistics 2 might be causing it to do this ill check

**Comment by TurboTophat** [comment]
i have removed all the mods i added and loaded in to the world and all the torches are still going to to there own slot of of the inventory and not all together

**Comment by chorbintime** [comment]
I'll look into it in a future update, thanks for the report.
