### ISSUE TITLE
Various Leaves Missing Textures (Fabric)

### ISSUE THREAD

**Issue by RigorousPizza97** [LunaPixelStudios/Better-MC#944]
### Describe the Bug

Leaves blocks from various modpacks such as "Oh the Biomes You'll Go" or "Terrestria" are missing textures, instead showing the generic purple and black cube texture. Tried and Tested in singleplayer, on a server, on various PCs singleplayer and server, after redownloading. Version is v12.5.

Date Bug Identified: 25/12/2022

### Reproduction Steps

1. Join game and spawn affected block/approach affected tree.
2. Identify Missing Textures.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 v12.5 1.19.2 Fabric

### Optifine

No

### Other Mods

N/A

**Comment by chorbintime** [comment]
This is not an issue on our side and not something we can fix.

There is an incompatibility between Sodium and Paradise Lost, which is trying to modify leaves textures for Christmas.

You can set your PC calendar to January 1st to fix this.

https://github.com/devs-immortal/Paradise-Lost/issues/748
