### ISSUE TITLE
totem of undying clearing toolbar and all armor from player when he dies

### ISSUE THREAD

**Issue by GustavoTDomingues** [LunaPixelStudios/Better-MC#945]
### Describe the Bug

basically I have a server on the 1.19.2 v12.5 of the modpack and when a player dies he loses all his items in the toolbar slots and all the armor equipped, is this supposed to happen or is it a bug? and if it's not how can I change it?
my players said that it only happened when the totem was on the charm slot i didnt test it all yet

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v12.5

### Optifine

No

**Comment by chorbintime** [comment]
Are you sure you are on v12.5?

**Comment by GustavoTDomingues** [comment]
yes it was im pretty sure

**Comment by chorbintime** [comment]
Can you please take a screenshot of the modpack version you're on?
