### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by modzioo** [LunaPixelStudios/Better-MC#946]
### Describe the Bug

please help

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![dsa](https://user-images.githubusercontent.com/121395040/209474661-3586b80f-8e96-4c9c-ac5e-6c11de295fcf.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
How did you install the modpack?
How much RAM do you have allocated?

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
