### ISSUE TITLE
The game crashed whilst accessing legacyrandomsource from multiple threads Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by Heketiitus** [LunaPixelStudios/Better-MC#947]
### Describe the Bug

the game crashed after i made a new world with default settings except difficulty hard and played for a small amount of time.
the message was "The game crashed whilst accessing legacyrandomsource from multiple threads Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads"
people say this is an optifine issue if you google it, but i didnt modify anything. if optifine is existent by default then i do have optifine, i still put no optifine in there because i dont think theres optifine but i did nothing to affect the presence of optifine.

### Reproduction Steps

open minecraft with the modpack
make world
play in it 
crash at some point maybe

### Crash Report or Log

https://pastebin.com/M3JqAEZi

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v11

### Optifine

No

**Comment by ZelPie** [comment]
my cousin had this same issue with the latest version, and all she ahd to do is clear space on her hard drive and it works fine now. maybe check if you dont have enough ram allocated as well.  you can do this by going to the curseforge app > settings (bottom left) > Minecraft > Java Settings, and then allocate however much you want (ideally less than half of your total ram amount).

**Comment by chorbintime** [comment]
You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.
