### ISSUE TITLE
A lot of broken leaf textures

### ISSUE THREAD

**Issue by ZelPie** [LunaPixelStudios/Better-MC#948]
### Describe the Bug

a lot of the leaf textures are broken (have the purple and black texture). im not sure if its the christmas textures that minecraft has by default on christmas, or what but ill put the texture packs im using in order.

Not selected: 

Default-Dark-Mode-1.19-v1.3...
xali-s-Enchanted-Books-16x...
Programmer Art

Selected: 

MoreMcmeta Internal
Fabric Mods
Bumblezone - Anti Trypophobia
Twilight Classic
immersive_weathering/visual_...
immersive_weathering/biome_ti...
immersive_weathering/better_... (vanilla brick items)
immersive_weathering/better_... (nether brick blocks)
illuminations/pixelaccurate
illuminations/lowerres
continuity/glass_pane_culling...
continuity/default
wilderwild/new_main_menu
vinery/bushy_leaves
Snowyspirit Generated Pack
Immersive Weathering Generat...
lambdabettergrass/default
charmonium/journeyman
Xaero's Minimap - Mod Icons.zip
NoBushyLeaves.zip
Stay_True_1.19.zip
Supplementaries Generated P...
Everycomp Generated Pack
Default

### Reproduction Steps

1. Put the texture packs im using in that order (please tell me if its the order that's breaking the textures)
2.
3.
...

### Screenshots and Videos

![2022-12-25_15 20 33](https://user-images.githubusercontent.com/112595924/209481074-316e1563-0f8f-43b4-ab0a-86a5a497d51e.png)
![2022-12-25_15 20 36](https://user-images.githubusercontent.com/112595924/209481076-ce3f9d9c-71e1-4944-bf28-c836b31f8993.png)
![2022-12-25_15 20 37](https://user-images.githubusercontent.com/112595924/209481077-4c516d6c-e588-45db-987f-b10bce44345b.png)
![2022-12-25_15 20 38](https://user-images.githubusercontent.com/112595924/209481078-4433627c-ebfa-41c1-b993-c24f68f518b4.png)
![2022-12-25_15 20 39](https://user-images.githubusercontent.com/112595924/209481079-7227ef87-8500-485a-9d6d-7fca4a19f9c3.png)
![2022-12-25_15 20 41](https://user-images.githubusercontent.com/112595924/209481080-266ec174-1748-4d32-92aa-e2cce25403d2.png)
![2022-12-25_15 20 54](https://user-images.githubusercontent.com/112595924/209481081-bc62ee54-ef7f-4cbf-83dd-1fded41d5633.png)
![2022-12-25_15 20 56](https://user-images.githubusercontent.com/112595924/209481082-ea5ca898-612b-4611-b219-0555e26c1163.png)
![2022-12-25_15 20 57](https://user-images.githubusercontent.com/112595924/209481083-69a0b908-da74-4da1-aeca-1984b1b445e5.png)
![2022-12-25_15 21 00](https://user-images.githubusercontent.com/112595924/209481084-e2f0a492-6eac-4c11-82db-283894175454.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 - 1.19.2 v12.5

### Optifine

No

### Other Mods

Lootr - (Fabric)
Starlight - Fabric
Boosted Brightness

**Comment by chorbintime** [comment]
This is not an issue on our side and not something we can fix.

There is an incompatibility between Sodium and Paradise Lost, which is trying to modify leaves textures for Christmas.

You can set your PC calendar to January 1st to fix this.

https://github.com/devs-immortal/Paradise-Lost/issues/748
