### ISSUE TITLE
Cluster of Chunks just turned red, forest red, trees red, grass red

### ISSUE THREAD

**Issue by 2Strxng4You** [LunaPixelStudios/Better-MC#949]
### Describe the Bug

So i was just building and then everything green turned red, building in fragment forest but other biomes around are red too. 
![image](https://user-images.githubusercontent.com/56030866/209486581-eefdfe1c-700e-493d-b86a-ffd2b3af49af.png)

### Reproduction Steps

1. Build
2. Suddenly turn red
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

### Optifine

No

**Comment by chorbintime** [comment]
Serene Seasons mod. You just witnessed the season change.
