### ISSUE TITLE
Can't add favourite recipes with REI

### ISSUE THREAD

**Issue by ZelPie** [LunaPixelStudios/Better-MC#950]
### Describe the Bug

This is not an issue with REI itself (I tested on a world with just REI installed). It is also not just happening on servers because I also tested singleplayer. I am simply not able to add favourites. I tried changing keybinds, I tried removing mods I added and nothing works. 

### Reproduction Steps

1. Boot up Minecraft on version 12.5 of BMC 1 Fabric 1.19.2.
2. Try adding any item to your favourites (clicking "a" by default).
3. Try changing the keybind.
4. Click it on an item and it still won't work no matter what it's set to.

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 - 1.19.2 v12.5

### Optifine

No

### Other Mods

All these mods were added after I noticed you can't add favourites so they are definitely not the problem.

Lootr Fabric
Starlight (client side)
Boosted Brightness (client side)
Inventory Sorting
Iron Chests Fabric

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?

**Comment by ZelPie** [comment]
with apexhosting for the server. curseforge normally with for client side

**Comment by chorbintime** [comment]
Curseforge Launcher?

**Comment by ZelPie** [comment]
Yes

**Comment by chorbintime** [comment]
What did you bind the favorite key to?

G will not work. Does the default A keybind work? Is it enabled in the REI config?

**Comment by ZelPie** [comment]
Oh my god I’m so dumb for some reason it was set to no by default sorry for wasting ur time lol
