### ISSUE TITLE
game lags to 1fps when rendering new chunks

### ISSUE THREAD

**Issue by xeoneregg** [LunaPixelStudios/Better-MC#951]
### Describe the Bug

as it says in the title 
my newest spark: https://spark.lucko.me/hN2SzRGGzv
My pc: ryzen 3 1200 rx 570 16gb ram

### Reproduction Steps

1. video is provided 

https://user-images.githubusercontent.com/121525390/209748960-ba14e476-3c1f-46f2-878b-1bfd831b5e62.mp4

2.
3.
...

### Screenshots and Videos

https://user-images.githubusercontent.com/121525390/209748996-bfd91f60-05f1-4f2d-a8c2-815eb2dad315.mp4

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v12.5 fabric 1.19.2

### Optifine

No

**Comment by chorbintime** [comment]
Remove the Effective mod
Switch to Adoptium Java 18, set java path in Curseforge
