### ISSUE TITLE
Can't plough Lush Dirt or Grass

### ISSUE THREAD

**Issue by Skelke** [LunaPixelStudios/Better-MC#953]
I can't plough Lush Dirt or Lush Grass meaning I have to harvest dirt far away from my base and transplant it... Am I missing something; is there a specific hoe or something, or is it just unable to be ploughed?

**Comment by chorbintime** [comment]
What mod are these blocks from?

**Comment by Skelke** [comment]
Hey sorry for the late reply, it's from Oh The Biomes You'll Go

**Comment by chorbintime** [comment]
Ask in the Oh The Biomes You'll Go discord. This may be intended. If not, you can suggest them to make it tillable.
