### ISSUE TITLE
Uncrafting table duplicating items

### ISSUE THREAD

**Issue by Cyarc** [LunaPixelStudios/Better-MC#955]
### Describe the Bug

Placing items in the left side, then placing only 1 or more of the required items to the craft the item in the middle, then clicking the item on the right side duplicates the items in the middle

### Reproduction Steps

1.Place item that can uncraft in left slot
2.place 1 of the required resources in the middle
3.click on right slot
...

https://user-images.githubusercontent.com/119869274/210137822-06904bdf-d271-41dd-8527-f145ed0d07e9.mp4

### Operating System

Windows10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2       v12.5

### Optifine

No

**Comment by chorbintime** [comment]
You should report this to Twilight Forest devs.
