### ISSUE TITLE
[1.16.5] Stuck in a Crash Loop.

### ISSUE THREAD

**Issue by Handeril** [LunaPixelStudios/Better-MC#956]
I basically encountered "The Terror of the Deep" while playing with a friend, and ever since it grabbed a hold of me, I can't stop crashing - even after dying and even after teleporting myself away from the server console. If I render in at all for them, they crash too.

This is the crash report:
[crash-2022-12-31_11.03.13-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/10327888/crash-2022-12-31_11.03.13-client.txt)

**Comment by chorbintime** [comment]
Try deleting the Oculus mod.

**Comment by Handeril** [comment]
Finally tried this out, and yes, it did fix the issue. Thank you for the help!

**Comment by chorbintime** [comment]
If updating Oculus doesn't fix this, or no update is available, report it on their Github
