### ISSUE TITLE
Shield Crafing

### ISSUE THREAD

**Issue by stinkyttv** [LunaPixelStudios/Better-MC#957]
### Describe the Bug

I recently installed the BMC3 Forge edition and I cannot craft a vanilla minecraft shield. It shows up in the JEI ui and has crafting recipes to add banners and get trades from villagers, but I cannot craft it from wood and an iron ingot.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-01-01_01 53 57](https://user-images.githubusercontent.com/121746274/210164368-10453da7-dbd5-4e9c-b18c-4b11b2ff17e7.png)
![2023-01-01_01 54 01](https://user-images.githubusercontent.com/121746274/210164369-1705a25a-80e2-4c32-902f-4264f0ea8bd2.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v11

### Optifine

No

**Comment by chorbintime** [comment]
Unintended, will look into it next update
