### ISSUE TITLE
Backpack

### ISSUE THREAD

**Issue by Thund3rmonk3y1** [LunaPixelStudios/Better-MC#958]
### Describe the Bug

Backpacks mysteriously lost a few rows of storage and now there is only one

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V11

### Optifine

No

**Comment by chorbintime** [comment]
Please send a screenshot

**Comment by Thund3rmonk3y1** [comment]
> Please send a screenshot

![Minecraft-01-03-2023 18-50-09-881](https://user-images.githubusercontent.com/111509690/210460390-aeccb87e-5005-42ac-941c-b43be2f4e5b2.jpg)

**Comment by chorbintime** [comment]
What happens when you click the two icons at the top right of that menu?

Also, how did you install the modpack?

**Comment by Thund3rmonk3y1** [comment]
> What happens when you click the two icons at the top right of that menu?
> 
> Also, how did you install the modpack?

The icon on the left only changes the appearance of the backpack and the right one tells me to install a configuration mod to modify it's settings. I didn't try it because there's already a couple config mods in the pack and didn't know how they would react. 
I downloaded the pack straight from curseforge because it was the newest version and I wanted to see the caves and cliffs world generation with the mods lol

**Comment by chorbintime** [comment]
Curseforge, or Curseforge Launcher?

You need a modded launcher to properly install & play modpacks.

**Comment by Thund3rmonk3y1** [comment]
I didn't know there was a difference. I have just the curseforge downloaded and when I click play on one of the modpacks it brings me to the standard looking minecraft launcher where I have to click play again. All the modpacks work pretty well usually but I do expect things like the backpacks not working to happen every once in a while since most mods are not as bug free as a vanilla minecraft update.

**Comment by chorbintime** [comment]
You should ask the developer of the backpack mod about this.

**Comment by Thund3rmonk3y1** [comment]
Okay I'll get it sorted out, thank you!

**Comment by kitsunex3** [comment]
i have the same , sometimes    one of the backup mods  is unable to read  a config file and  reverts it to a standerd file  , i think it's one of the FTB- backup  mods

**Comment by kitsunex3** [comment]
short answer you can set   the rows in your config  file
