### ISSUE TITLE
Keep crashing

### ISSUE THREAD

**Issue by CuteLlama** [LunaPixelStudios/Better-MC#959]
### Describe the Bug

i keep crashing i dont know why i really dont 
i can stand still for 2 min and then it freezes and then crashes i cant sleep it crashes i can run around and it crashes but sometims its first after an hour sometimes after 5 min and if i go to game menu and out it crashes i love the game to much to just let it go 
i have played others where i had no issues maybe a bit lag but nothing bad 
i dont know what to do anymore 

im not a minecraft or pc expert but i know i have never seen anything this bad

### Reproduction Steps

1.
2.
3.
...

### Operating System

window 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

idk

### Optifine

No

### Other Mods

no nothing

**Comment by chorbintime** [comment]
Me, nor anyone else, can help you without a crash report or latest.log

**Comment by CuteLlama** [comment]
> Me, nor anyone else, can help you without a crash report or latest.log

i believe this is what u need that i couldnt find yesterday 
been searching for it for over an hour so i really hope this is it 

[crash-2022-12-31_11.03.13-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/10337697/crash-2022-12-31_11.03.13-client.txt)
