### ISSUE TITLE
1.19.2 v12.5

### ISSUE THREAD

**Issue by oguhdadad** [LunaPixelStudios/Better-MC#960]
### Describe the Bug

Whenever i die with a totem in hand i loose everything in my hotbar or my armor

### Reproduction Steps

1.totem in hand
2.hotbar filled or armor on
3.die
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

better mc fabric

### Optifine

No

**Comment by chorbintime** [comment]
Did you have a Twilight Forest charm of undying in your inventory?
