### ISSUE TITLE
Game crashes when starting world

### ISSUE THREAD

**Issue by Louisloltoll** [LunaPixelStudios/Better-MC#964]
### Describe the Bug

Whenever I go into a world go it crash and the text comes:
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot read field "ignoredNamespaces" because "net.darkhax.tipsmod.impl.TipsModCommon.CONFIG" is null

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

The game crashed whilst rendering screen Error: java.lang.NullPointerException: Cannot read field "ignoredNamespaces" because "net.darkhax.tipsmod.impl.TipsModCommon.CONFIG" is null

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v12.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
We need a crash report. A single line of a crash report is not enough.

How did you install the modpack.

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by chorbintime** [comment]
Remove the Tips mod
