### ISSUE TITLE
Don't know how to turn {"color":"white"} into a component: NO EXISTING SOLUTION

### ISSUE THREAD

**Issue by liam102102** [LunaPixelStudios/Better-MC#965]
### Describe the Bug
=
YES I HAVE READ THE OTHER ISSUES PRETAINING TO THIS, AND NO NONE OF THE SOLUTIONS HAVE HELPED
=
Playing on a Better Minecraft Fabric 1.19.2 Server, every time I log on, I crash with the crash message:
![image](https://user-images.githubusercontent.com/60496273/210922846-eee89775-dda6-4823-b47a-c3654e013456.png)
This has happened many times and once I start crashing I cannot stop until I have an admin teleport me out of the area, however upon return to the area the crash loop happens again.
This is difficult as the chunks which cause this loop happen to be my home base:
This does not happen on item pickup and is not an item in my inventory causing the issue.
This has occurred before, and the solution was to have an admin slowly approach the crashing chunks, which we theorize allowed some item to despawn. However, the only active things in the area, are a few villagers, Allays that spawned in the woodland mansion, still in their cells, and a Vindicator Spawner, located underground, we have verified by holding and interacting that no items these mobs drop could've been the cause, and while I'm actively there I've never had issue, the only time this crash loop happens is when I teleport away and then back: notably this does not occur every time I teleport away and back, but it has happened twice under that circumstance. Worth noting due to the nature of the spawner, a raid is typically active as the vindicators spawn with flags.
Anyone else who teleports to the chunk, or near by chunks also crash and cannot reconnect until teleported out. However they typically can come close enough to see the raid bar before crashing, indicating it may not be the raid proximity causing this issue.

My problem does not lie in that there are no ways to escape this loop: however admins being busy means I cannot play for days at a time when I enter this loop, my problem is that is is recurring in the same location, evident of a deeper bug.

Teleporting away stops me from crashing but it also renders me unable to return.

The solutions outlined here
![image](https://user-images.githubusercontent.com/60496273/210923823-71a62180-eb24-45c2-9359-338430fa4b96.png)
Failed to help, as again it renders me unable to return and even when the area is finally stable who knows when it will occur, as well as the server having been on the same version the whole time, never updating.

This solution just results in whoever comes to the chunk crashing
![image](https://user-images.githubusercontent.com/60496273/210924177-4923cdda-85fb-441b-ae6b-d13c7e9d772a.png)

And these solutions are purely temporary and still render me unable to return to my base
![image](https://user-images.githubusercontent.com/60496273/210924328-031c2106-80f3-482e-ac00-ff288dcc8a1c.png)
![image](https://user-images.githubusercontent.com/60496273/210924267-7b33aa8b-855f-4e52-a481-78a58be87ad3.png)

### Reproduction Steps

1. Using the spirit mod have a maxed out vindicator soul crystal
2. Use the crystal on a soul cage, making a vindicator spawner
3. Use the spawner and wait for a raid to start
4. Using a waystone teleport away
5. Using a waystone teleport back to the area
6. (likely unrelated but other factors): have some villagers and allays nearby

It's not 100% but its the only situations in which I've had this issue, which has occured twice in a day.

### Screenshots and Videos

All images should be above in the post.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v12.5

### Optifine

No

### Other Mods

All client side exclusive to me, others who had this issue did not have these mods

Voice chat
Voice chat interface
Appleskin

**Comment by chorbintime** [comment]
Our dev team is unable to recreate this issue. None of the players who have experienced the issue has been willing to debug it with us. We ask them to, they say they will, and never come back with a solution. The temporary solutions I've listed work for everyone.

If you are 100% sure it has something to do with waystones, post a report on their github with a latest.log and debug.log attached.

**Comment by liam102102** [comment]
it is not exclusive to waystones, it happens with any form of teleportation:
Additionally I'd be happy to debug it with you but all my solutions are temporary at best

**Comment by chorbintime** [comment]
Start by removing all pillager related mods - search "illager" in the mod list and remove anything that shows up. Savage & Ravage should also be removed if present.
