### ISSUE TITLE
game crashes during start up

### ISSUE THREAD

**Issue by crabbity** [LunaPixelStudios/Better-MC#966]
### Describe the Bug

net.minecraftforge.fml.ModLoadingException: SpectreLib (spectrelib) encountered an error during the common_setup event phase

i have no clue what is happening. please help 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11

### Optifine

No

**Comment by chorbintime** [comment]
send the crash report file

**Comment by SHXRKIIE** [comment]
If this is a fresh install and 1 crash then see if pressing play again fixes it other than that we need a crash report
