### ISSUE TITLE
cant download the modpack ...

### ISSUE THREAD

**Issue by HANAKO276** [LunaPixelStudios/Better-MC#967]
### Describe the Bug

i just cant download the modpack when it reaches "applying patch 4 of 6" it stops downloading without sending a msg or anything and the weird part is that this thing keeps happening with every 1.19.2 modpack except if it was a fabric plz help me :<  

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

.

### Operating System

.

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11 

### Optifine

No

**Comment by chorbintime** [comment]
This is not an issue on our side. It's a Curseforge issue.

Switch to ATLauncher.
