### ISSUE TITLE
Game crashes after dying

### ISSUE THREAD

**Issue by GloomySoul** [LunaPixelStudios/Better-MC#968]
### Describe the Bug

After dying, whether it's to an enemy or to the environment, my character respawns and after a few seconds the game freezes up and I get thrown out of the server with the error message (internal exception: java.net.SocketException: Connection reset)

### Reproduction Steps

1. Join the hosting server
2. Die to anything
3. Character respawns normally but after a few seconds the game freezes up and I get disconnected
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/47184622/211135277-1ab57efc-a2dc-4e32-b49c-8303f702d246.png)

### Crash Report or Log

https://pastebin.com/ig6te9U0

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

BMC 2 - version 1.18.2

### Optifine

No

**Comment by chorbintime** [comment]
What origin did you pick?

**Comment by GloomySoul** [comment]
Sorry but what do you mean by origin?

**Comment by GloomySoul** [comment]
Server is being hosted on apexminecrafthosting.com

**Comment by chorbintime** [comment]
Have you asked Apex support? It may be an issue on their side.

**Comment by GloomySoul** [comment]
I'm the only one with this issue amongst my friends, it would make sense for everyone to have it if the problem is server side no?

**Comment by chorbintime** [comment]
Not necessarily. 

A log file with more information would be helpful - play for a couple minutes, get killed, get kicked, then copy that latest.log into mclo.gs or pastebin.
