### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by MrNummyy** [LunaPixelStudios/Better-MC#969]
### Describe the Bug

i have  RTX 3070 Ryzen 3600x 32gb ram i allocate about 14gbs and i still gets very low fps 

### Reproduction Steps

1.something
2.
3.
...

### Screenshots and Videos

...

### Crash Report or Log

no crash

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] 1.19.2 v12.5.zip

### Optifine

no

### Other Mods

noda a daWD WAD WADWAD

**Comment by chorbintime** [comment]
Send a screenshot with F3 open
