### ISSUE TITLE
faible fps

### ISSUE THREAD

**Issue by jawel38** [LunaPixelStudios/Better-MC#970]
### Describe the Bug

j'ai une rtx 3060 et un ryzen 7 3800x 16 go de ram dont 8gb alloué a minecraft et meme quand je met le jeu en full low j'obtiens seulement 30-40fps

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Capture d’écran (2)](https://user-images.githubusercontent.com/122207016/211192630-1f0632c8-5ef7-4156-9ab9-e1c19e69bcca.png)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.18.2-1.19

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

Please send a screenshot with the F3 menu open.
