### ISSUE TITLE
Alex’s Mobs Issue

### ISSUE THREAD

**Issue by Klluff** [LunaPixelStudios/Better-MC#971]
### Describe the Bug

I’m using bisecthosting that automatically set up the server for me and can not find certain animals. For example, I can’t find any of the sharks, orcas, whales, giant squid’s, mimic octopus to name a few. Me and my friend have sat in the biome but they never spawn.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

I used Optifine

**Comment by Frontear** [comment]
please dont use optifine. lps modpacks are not compatible with optifine

**Comment by Klluff** [comment]
Sorry I accidentally clicked the wrong button for that! I actually don’t have optifine. All I did was download it off of curseforge and didn’t add anything to it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Frontear** [comment]
are you sure its not a matter of luck? if you went into the commands and tried to spawn the animals via the /summon command, do you see them?

**Comment by Klluff** [comment]
Yes just summoned one now. Me and my friend have been looking for days and never found one and I for sure have never seen the cachalot whale in the ocean before because of how big the icon is on the mini map

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SHXRKIIE** [comment]
Alex Mobs adds tons of mobs, combined with other mob mods, the mobs will be rare to find. If oyu want you can change the Alex Mobs config to make them more frequent to spawn.

**Comment by Klluff** [comment]
Yeah I have no clue whats wrong with my world/server. Even when I turn the spawn weight all the way up it still doesn’t spawn
