### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by coolsk3leton95** [LunaPixelStudios/Better-MC#972]
### Describe the Bug

The cherry leaves from Vinery has the black and purple checker box that can only mean missing textures. I have tried messing around with my graphic settings in game, but nothing is fixing the issue.

### Reproduction Steps

1. OPen game
2. Look at Vinery cherry tree
3. Purple and black checkered boxes
...

### Screenshots and Videos

![2023-01-10_18 14 36](https://user-images.githubusercontent.com/122411065/211686882-2664ff24-ea71-4359-8df0-f7b3e555e021.png)
![2023-01-10_18 14 29](https://user-images.githubusercontent.com/122411065/211686919-56cf2828-5d29-4387-b4b6-58cc3fc846af.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v13

### Optifine

No

**Comment by Frontear** [comment]
known issue with Lets do Wine.

![image](https://user-images.githubusercontent.com/31909298/211691655-543d9945-88fb-4ed6-93d6-073c0d485451.png)

**Comment by SHXRKIIE** [comment]
Duplicate #973
