### ISSUE TITLE
[Fabric] Better MC BMC1 - Cherry leaves 

### ISSUE THREAD

**Issue by Ansordrax** [LunaPixelStudios/Better-MC#973]
### Describe the Bug

Hi, 

I think i found a bug that impact only Cherry leaves from vinery when and only when ressource pack "vinery/bushy_leaves" is enabled. Only when the cherry leaves is in fruit state. (check attachements).
The texture seems to be missing. (Black and purple squares).

### Reproduction Steps

1.Put the ressource pack Vinery/bushy_leaves
2.grow a cherry tree
3.
...

### Screenshots and Videos

![without](https://user-images.githubusercontent.com/31321638/211688425-cc6028bc-4c7d-4ac5-8792-7774d153135b.png)
![Vinery](https://user-images.githubusercontent.com/31321638/211688429-e6dfc2a6-13c4-4a83-8f66-4e240467f53e.png)
![2023-01-11_01 03 18](https://user-images.githubusercontent.com/31321638/211688440-0d5b5444-dbff-416b-85c3-b1f9bf68ac62.png)
![2023-01-11_01 05 02](https://user-images.githubusercontent.com/31321638/211688441-6d21fb32-0998-4a70-a791-d606d08bd197.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Better MC [FABRIC] - 1.19.2 v13.zip

### Optifine

No

**Comment by Frontear** [comment]
known issue with Lets do Wine.

![image](https://user-images.githubusercontent.com/31909298/211691655-543d9945-88fb-4ed6-93d6-073c0d485451.png)

**Comment by Ansordrax** [comment]
Oh thanks man, i seached this night but haven't found the topics about it :)
