### ISSUE TITLE
Server backup causes everything to freeze

### ISSUE THREAD

**Issue by XTinxt** [LunaPixelStudios/Better-MC#974]
### Describe the Bug

After a while of playing, the game will do a server backup which doesn't let you then do anything like break any blocks, picking anything up or dropping items. Everything just disappears and if you are on a mount you cant get off the mount or open your inventory after the server backup. 

Bit of a weird bug to explain but also you cant even quit the game as it just enters a constant loop of "saving world" which then makes me have to force end the program through task manager. 

This all seems to of started when I got a mount known as the zar-apak or something like that, its a flying mount.

### Reproduction Steps

1. Get a flying mount (Zar-apak)
2. Fly around the map for a while, especially in unloaded parts of the map
...

### Operating System

Windows 10 pro

### Minecraft Version

1.19.2

### Modloader

Fabric

### Modpack Version

MMC1

### Optifine

No

**Comment by SHXRKIIE** [comment]
Please report to https://github.com/LunaPixelStudios/Medieval-MC/issues
