### ISSUE TITLE
Can't launch the modpack

### ISSUE THREAD

**Issue by Hubbichat** [LunaPixelStudios/Better-MC#975]
### Describe the Bug

I can't launch the modpack, I get an error on the minecraft launcher each time. 

### Reproduction Steps

1. Download the modpack from curseforge 
2. Wait
3. Click on "Jouer" (Sorry I'm french)
4. Same than 3. But on the minecraft launcher 
5. Wait again
6. And voila, I got an error

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/63476216/211892106-421089d4-5549-42be-beb0-507002e16b39.png)

### Crash Report or Log

https://gist.github.com/Hubbichat/99298f48d88b9ddc7afe4401f1418a05

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC V11

### Optifine

No

**Comment by SHXRKIIE** [comment]
We recommend trying ATLauncher isntead.
