### ISSUE TITLE
Server not start

### ISSUE THREAD

**Issue by sadwave29** [LunaPixelStudios/Better-MC#977]
### Describe the Bug

When I launch my server for the first time I encounter this error:

 Scheduler class: 'net.creeperhost.ftbbackups.org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'net.creeperhost.ftbbackups.org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'net.creeperhost.ftbbackups.org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[18:41:22] [Server thread/INFO] [ne.cr.ft.or.qu.im.StdSchedulerFactory/]: Quartz scheduler 'ftbbackups2' initialized from an externally provided properties instance.
[18:41:22] [Server thread/INFO] [ne.cr.ft.or.qu.im.StdSchedulerFactory/]: Quartz scheduler version: 2.0.2
[18:41:22] [Server thread/INFO] [ne.cr.ft.or.qu.co.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED started.
[18:41:22] [Server thread/INFO] [patchouli/]: Sending reload packet to clients

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows server 2022

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC 3

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
That is not an error. I need a full log or crash report to properly assist you. 

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by sadwave29** [comment]
[logs.txt](https://github.com/LunaPixelStudios/Better-MC/files/10411487/logs.txt)
Attached are the logs
Thank you for your reply. I haven't put optifine on this server yet.
i just downloaded Better MC [FORGE] BMC 3

**Comment by chorbintime** [comment]
I see no issues here. Your server seems to be started and I see no reason it wouldn't be.

Why do you think the server _isnt_ started? There aren't any errors - there's actually less than usual because the device you're hosting the server on is powerful enough to support the initial world generation without lag.

Were you having trouble joining? You join by typing `localhost` in the Multiplayer menu Direct Connect. If you're unable to join, make sure you have the exact same modpack installed on server & client side.

**Comment by SHXRKIIE** [comment]
?Are you unable to join your world because it says the server is ready?
[minecraft/DedicatedServer]: Done (47.181s)! For help, type "help"

**Comment by Quiczek** [comment]
![part 2](https://user-images.githubusercontent.com/122719323/212529604-fb294c44-dbf8-48ac-ad39-33957ec4ca26.png)
![part 1](https://user-images.githubusercontent.com/122719323/212529605-3795b318-3ed1-4fd9-b902-10c21fae702d.png)
Sorry for pushing my self into this post. I also have a problem with starting my server. Pictures above show my error and i have no idea what to do with it

**Comment by chorbintime** [comment]
I once again do not see the issue here. I'd suggest contacting your server host's support team.

**Comment by Quiczek** [comment]
> 

I dont think its the problem with server it self. it runs fine with no mods or a pack of mods i put together myself. i always had a problem with better mc when tried running it

**Comment by chorbintime** [comment]
Have you contacted your serverhost
