### ISSUE TITLE
Crash error when exploring Everbright.

### ISSUE THREAD

**Issue by JellyBubb1e** [LunaPixelStudios/Better-MC#978]
### Describe the Bug

In Everbright, a chunk caused the server to crash. After deleting this block, the server still crashes after the player enters the chunk.

### Reproduction Steps

1.Create a new world.
2.Open the Everbright portal.
3.Enter the Everbright.
4.Enter the mushroom forest
5.The world crash.
...

### Crash Report or Log

https://pastebin.com/6x487KDA

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V11

### Optifine

No

### Other Mods

- create
- breezy
- immersive armors
- Unique Enchantments Base
- Unique Enchantments
- Unique Enchantments - Utils
- Unique Enchantments - Battle
- TreeChop
- TreePlant
- TofuCraftReload
- Ench sort
- Disenchanting
- worldedit

**Comment by mrcornflakes** [comment]
I got the same error when I enter the mushroom forest in the everbright dimension

### **Crash Report or Log**

https://pastebin.com/qSDcCCp1

**Comment by JellyBubb1e** [comment]
![image](https://user-images.githubusercontent.com/107482912/212522916-8930a358-e66b-450f-9924-364202684326.png)

**Comment by chorbintime** [comment]
`mixin.entity.collisions = false` will be set in the next modpack update.
