### ISSUE TITLE
Cant interact with any entity.

### ISSUE THREAD

**Issue by yotehaw** [LunaPixelStudios/Better-MC#979]
### Describe the Bug

I cannot right click on any entity that brings up a seperate menu such as: villagers, goblin traders, paintings, minecraft with chests. I can right click on everything else. Just not entities

### Reproduction Steps

1.Right click on entity
2.Nothing happens
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 Fabric

### Optifine

No

**Comment by chorbintime** [comment]
Unable to recreate. Please send a video.
