### ISSUE TITLE
[BMC3] All particles get glitched when picking up an item

### ISSUE THREAD

**Issue by DeadPigman17** [LunaPixelStudios/Better-MC#981]
When you pick up an item, all particles around you turn black for a second, and this includes particles that you can't see because they are behind blocks, which turn visible for a second. In this screenshot, you can see how the torch particles and the falling leaves particles (which are outside of the house) turn black just as an item entered my inventory.
![2023-01-14_20 07 35](https://user-images.githubusercontent.com/22800252/212492074-e13a81a8-4caf-4553-b8a6-e098490ae42d.png)

**Comment by chorbintime** [comment]
Did you have any shaders enabled?

How did you install the modpack?

Are all of your drivers up to date?
