### ISSUE TITLE
JsonParseException: Don't know hot to turn {"color":"white"} into a Component

### ISSUE THREAD

**Issue by Samja2000** [LunaPixelStudios/Better-MC#982]
### Describe the Bug

Error when loading onto server or private world - may be entity related, or linked to Pillagers (banners, accessing inventories/grave around them). 

Previous Issues have been closed that are not solutions - Potential fixes such as "Delete All Player Data" is not a fix, it's a workaround.

https://github.com/LunaPixelStudios/Better-MC/issues/783

Would like to know if the modpack creators are aware of this issue at the moment.

### Reproduction Steps

1. Create a new world, and locate a Pillager camp (Alternatively, in the Prison Dimension there are Pillager Banners, place one of them around on the Overworld) - May also be related to RelicEx, but I am not too sure
2. Ensure the item is in your inventory and/or around, then quit out of the world
3. Attempt to relog - will return error code
...

### Screenshots and Videos

![Example Crash 2](https://user-images.githubusercontent.com/122817995/212734066-9d695783-137e-4601-897d-f7235d569dd5.png)
![Example Crash](https://user-images.githubusercontent.com/122817995/212734068-d9ccf037-18e9-4339-86de-9dc6fc9a0a3b.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15 Fabric

### Optifine

No

### Other Mods

Fresh Install

**Comment by chorbintime** [comment]
Add this mod to client & server side https://github.com/TheSeems/PacketPray/releases
