### ISSUE TITLE
Crash occurs when loading world

### ISSUE THREAD

**Issue by Kabelbo** [LunaPixelStudios/Better-MC#983]
### Describe the Bug

Crash occurs after creating a new world or trying to join my friend's world over LAN

### Crash Report or Log

https://pastebin.com/LMjiRS6e

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc v13.5

### Optifine

No

**Comment by chorbintime** [comment]
Do not use LAN. We offer no support for LAN whatsoever.

Use the serverpack on the modpack's curseforge page instead. Read the readme file for more information.
