### ISSUE TITLE
i cant hear anything

### ISSUE THREAD

**Issue by zothom** [LunaPixelStudios/Better-MC#985]
### Describe the Bug

i can hear scertain things like, certain animals, glass breaking but thats it. i will delete the game re install literally everything u can think and it still wont work!

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2

### Optifine

No

**Comment by chorbintime** [comment]
Reload textures & sounds with F3 + A
