### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by senpiekyle** [LunaPixelStudios/Better-MC#989]
### Describe the Bug

I'm honestly really confused on how to manually install this. I have it on my Apex server but for myself I'm a bit confused on how I get everything installed. Please help ;; 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC1

### Optifine

No

**Comment by sepiekyle** [comment]
Last time I "installed" this was just by putting the mods into the mods folder, then I was seeing i wasn't having the shaders tab, so I was like something wrong here, aha. Like I'm trying to have it to where I can play BMC1 on my Apex server as well with some friends.

**Comment by chorbintime** [comment]
> Last time I "installed" this was just by putting the mods into the mods folder, then I was seeing i wasn't having the shaders tab, so I was like something wrong here, aha. Like I'm trying to have it to where I can play BMC1 on my Apex server as well with some friends.

That's not how it works. To install on clientside, you NEED a modded launcher to install & play. Preferably ATLauncher but Curseforge will work too.

On the serverside, Apex should have a modpack auto-installer.
