### ISSUE TITLE
Problem with Server Pack

### ISSUE THREAD

**Issue by Tomax7u7** [LunaPixelStudios/Better-MC#991]
### Describe the Bug

When i start my server on my pc (Windows 10 pro) or my home server (Windows Server 2022) it's everything ok, but when i have to shut it down or restart it i have problems. When shutting it down the server never stops, it gets stucked on "Stopped IO worker" and the "Press any key to continue" (or something like that) message never shows... Also, when i import my server on MC Server Soft and i press "Stop" it also get stucked on "Stopped IO Worker" and the "Status:" says "Stopping", and the process never finishes, i have to manually kill it. 
The other problem is when i restart it. It gets stucked in the same message and never restarts, so, when i have to auto restart my server, it never happens. I thought it was my pc or drivers, but with the 12.5 version it doesn't happen, so i haven't been able to update my server because of that, and like i said, it happens on my personal pc and home server pc.  

PD: Sorry if you had some issues reading this, im a spanish speaker. Wish you all a good day/night! <3

### Reproduction Steps

1. Start server
2. Wait for it to completely start
3. Try to shut it down or restart it
4. It will fail. (Windows 10 Pro 22h2 and Windows Server 2022)
...

### Screenshots and Videos

https://user-images.githubusercontent.com/37155863/213263540-499cf921-74e4-4284-9eea-329a1baaefcb.mp4

https://user-images.githubusercontent.com/37155863/213263570-deadc390-450e-4d2d-a58a-f7243f41f56e.mp4

### Operating System

Windows 10 and Windows Server 2022

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1 13 and 13.5

### Optifine

No

**Comment by chorbintime** [comment]
Try deleting the FTB Backups mod

**Comment by Tomax7u7** [comment]
> Try deleting the FTB Backups mod

It doesn't work.

**Comment by chorbintime** [comment]
If you just close the server window, does the world save?

**Comment by Tomax7u7** [comment]
Yes it does.

**Comment by Tomax7u7** [comment]
Hey, it doesn't work for me man. I need my server to be fully auto, i don't have the time to restart it manually every few hours. The server pack works bad, thats for sure. I just hope this gets fixed on the next version.
