### ISSUE TITLE
Not able to use vivecraft with this modpack.

### ISSUE THREAD

**Issue by Xyloontwitch** [LunaPixelStudios/Better-MC#992]
### Describe the Bug

Exit code 0 o n launch

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

BMC 1 V59.5

### Optifine

No

### Other Mods

0

**Comment by chorbintime** [comment]
Cant help without a crash report or latest.log
