### ISSUE TITLE
can't wear specific types of armors

### ISSUE THREAD

**Issue by chunx47** [LunaPixelStudios/Better-MC#993]
I crafted durasteel armor from the mythic metal's mods but wasn't able to wear. I then spawned in other armors seeing if it was just the durasteel I couldn't wear. However, some i could wear but others like normal diamond armor I could not.

**Comment by chorbintime** [comment]
Durasteel is not in BMC. You're playing Medieval.

Press O. Your origin probably doesn't allow you to. You should read what your origin does before picking it.
