### ISSUE TITLE
Error when joining v12.5 server with v12.5 client.

### ISSUE THREAD

**Issue by alextoddslick** [LunaPixelStudios/Better-MC#994]
### Describe the Bug

Error when joining v12.5 server with v12.5 client.

Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component

### Reproduction Steps

1. Load Minecraft v12.5
2. Join v12.5 Server
3. You get error listed in the desc.

### Screenshots and Videos

![Screenshot 2023-01-18 204423](https://user-images.githubusercontent.com/78877316/213350393-a3bfe391-e6b3-40a8-b1ae-f4c8cf219a60.png)

### Crash Report or Log

NA

### Operating System

Windows 11 & Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v12.5

### Optifine

No

### Other Mods

No extra added mods to my knowledge, downloaded directly from the curseforge website.

**Comment by chorbintime** [comment]
Download this on client & serverside https://www.curseforge.com/minecraft/mc-mods/packetpray
