### ISSUE TITLE
Error when joining v12.5 server with v12.5 client.

### ISSUE THREAD

**Issue by bubs2031** [LunaPixelStudios/Better-MC#995]
### Describe the Bug

Error when joining v12.5 server with v12.5 client.

Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component

Even when i launch this BETTER MC mod (using my same mojang account) on another computer. Bug still remains. Its linked to account. Not the server or computer

### Reproduction Steps

1. Load Minecraft v12.5
2. Join v12.5 Server
3. You get error listed in the desc
...

### Screenshots and Videos

![FF9DDE3D-6B82-4818-B1BE-A22B29C90709](https://user-images.githubusercontent.com/123134561/213599763-9d6fa4ac-3d48-4590-bce4-9e591f73e578.png)
![21430159-99A7-4B04-A55A-4FBC97C7A4F6](https://user-images.githubusercontent.com/123134561/213599775-899084dc-830f-46b4-914d-311d5050f6ee.jpeg)

### Crash Report or Log

NA

### Operating System

Windows 10 & 11

### Minecraft Version

1.12

### Modloader

Forge

### Modpack Version

v12.5

### Optifine

No

### Other Mods

No

**Comment by bubs2031** [comment]
Minecraft version 1.19 not 1.12

**Comment by bubs2031** [comment]
Does anyone know how to fix this? or how to contact the mod's creator to solve this issue

**Comment by chorbintime** [comment]
Add the PacketPray mod to serverside & clientside https://www.curseforge.com/minecraft/mc-mods/packetpray
