### ISSUE TITLE
Extreme lag spiking 0fps

### ISSUE THREAD

**Issue by zaniers** [LunaPixelStudios/Better-MC#996]
### Describe the Bug

I have around 70-200fps depending on the area I'm at but every time I walk around and generate new chunks my fps fully drops to around 5 fps sometimes even to 0 which makes it absolutely impossible to play this. Maybe there is a way to fix this? or do I just fully need to upgrade my pc? My girlfriend can play this fully okay but she has a ryzen 5 3600 and 16gb of ram.. maybe theres something I could remove (mods) or something to help me.

My specs:
ryzen 3 1200, gtx 1650, 8gb ram, windows 11 newest version.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

No

**Comment by chorbintime** [comment]
https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide
Follow the performance guide 

Update the modpack please, v11.5 is very old. The latest version is v18. I will not be able to assist you further if you stay on an old version of the modpack.

**Comment by MasterKairiZ** [comment]
im on latest version it still does that i have a 5500xt and 8th gen i5 cpu, 16gb ddr4 ram and an nvme m.2 os with minecraft on it ..still lags like that until i turn down the chunk settings to like 8,8 and 5
