### ISSUE TITLE
All blocks, entities frozen and not responding. 

### ISSUE THREAD

**Issue by Reholas** [LunaPixelStudios/Better-MC#997]
All entities are frozen in place and not moving. Objects like grass and trees still have motion including water.  Any block that is broken does not drop the block. Tried breaking sugar cane but same effect, yet the only block that breaks is the one I targeted. 

Using a shader complimentary shaders, no other mods installed just the shader.
running with 9gb of ram allocated. 

https://user-images.githubusercontent.com/64102444/213777889-298a3942-50e2-4729-a308-139f0354007d.mp4

**Comment by chorbintime** [comment]
Follow the performance guide here https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide

Your internal server seems to have crashed or lagged out, this would be avoided by changing your coordinates inside of your playerdata to somewhere far away. You can do this using a program like NBTStudio.
