### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Freddiiy** [LunaPixelStudios/Better-MC#998]
### Describe the Bug

Game crashes when I try to load the world

### Reproduction Steps

1. Log onto server.
2. Walk to a specific point
3. Lose connection with error message.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/20381778/213878637-f8402381-1771-453c-a232-b87f5164c1e5.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v13 & v13.5

### Optifine

No

**Comment by Freddiiy** [comment]
Duplicate of #995

**Comment by chorbintime** [comment]
Add the PacketPray mod to serverside & clientside https://www.curseforge.com/minecraft/mc-mods/packetpray
